### ISSUE TITLE
Create new Windows class issue

### ISSUE THREAD

**Issue by horan74** [shimat/opencvsharp#1000]
# Summary of your issue
When I create a new Window class, after execution the window shows and closes immediately.
# Environment
Windows 7 64 bit
# What did you do when you faced the problem?
After creating a new Window class

## Example code:

```
using (Window window = new Window("Result")){}
```

## Output:

```

```

## What did you intend to be?
I thought when I explicitly call the method "ShowImage", the image should be shown. But not after creating the instance of the class.

**Comment by shimat** [comment]
Please use Cv2.WaitKey();
https://github.com/shimat/opencvsharp#usage

**Comment by horan74** [comment]
I know Cv2.WaitKey() doesn't close the window until you close it.

I'm trying to understand why after creating an instance window opens and closes immediately. 

For example:

I create an instance at the beginning of my program. The window opens and closes(I don't need it). 
Then there are many many operations.... My program works 10 minutes...

I wanna show the specific image. I invoke ShowImage method and then Cv2.WaitKey(). Here I understand why this method uses.

**Comment by shimat** [comment]
`new Window("windowName")` is a simple wrapping of `cv::namedWindow` (C++). Please check out the native OpenCV specs for `cv::namedWindow` and `cv::waitKey`. I am closing this issue as it is not about the wrapper.
