### ISSUE TITLE
Unable to build to Android with "OpenCV plus Unity"

### ISSUE THREAD

**Issue by jeyemwey** [shimat/opencvsharp#1009]
# Summary of your issue

We have used the Unity Package [**OpenCV plus Unity**](https://assetstore.unity.com/packages/tools/integration/opencv-plus-unity-85928) for our Unity Android Application. While the scenes with OpenCV references do compile on Windows and macOS, they crash on Android.

# Environment

We have integrated the Unity Asset above in an `Unity 2019.3.7f1` project and built our scenes with it. In the C# scripts, we reference your library with `using OpenCvSharp;`.

The target environment for Android is `ARMv7` (32bit) and `ARM64` (64bit). Unsafe Code is active in the build settings and we're using `il2cpp`.

# What did you do when you faced the problem?

We connected our Android phone to `adb logcat` and found the error logs (below).

## Example code:

```c#
using OpenCvSharp;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using System.Data;

public class Scanning_Code
{
	public Texture inTexture;
	public Texture outTexture;

    public void Start()
    {
 		if (inTexture == null)
        {
            Debug.LogError("Texture not given.");
            throw new ArgumentException("Input Texture is null");
        }

    	Mat image = Unity.TextureToMat(inTexture);

    	Mat grayImage = new Mat();
        Cv2.CvtColor(image, grayImage, ColorConversionCodes.BGR2GRAY);

		// ... and so on, this is not relevant
    }
}
```

## Output:

```
2020.07.23 14:11:15.063 10723 10749 Error Unity DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found.
2020.07.23 14:11:15.063 10723 10749 Error Unity   at OpenCvSharp.Unity.utils_texture_to_mat (System.IntPtr pixels32, System.Int32 w, System.Int32 h, System.Boolean flipVetically, System.Boolean flipHorizontally, System.Int32 rotationAngle) [0x00000] in <00000000000000000000000000000000>:0 
2020.07.23 14:11:15.063 10723 10749 Error Unity   at OpenCvSharp.Unity.PixelsToMat (UnityEngine.Color32[] pixels32, System.Int32 width, System.Int32 height, System.Boolean flipVertically, System.Boolean flipHorizontally, System.Int32 rotationAngle) [0x00000] in <00000000000000000000000000000000>:0 
2020.07.23 14:11:15.063 10723 10749 Error Unity   at OpenCvSharp.IaShirtDesigner.Scanning_Code.setMasks (UnityEngine.Texture2D v, UnityEngine.Texture2D h) [0x00000] in <00000000000000000000000000000000>:0 
2020.07.23 14:11:15.063 10723 10749 Error Unity   at UploadImage.<OpenImage>b__3_0 (System.String path) [0x00000] in <00000000000000000000000000000000>:0 
2020.07.23 14:11:15.063 10723 10749 Error Unity   at NativeGallery+MediaPickCallback.Invoke (System.String path) [0x00000] in <00000000000000000000000000000000>:0 
2020.07.23 14:11:15.063 10723 10749 Error Unity   at NativeGalleryNamespace.NGMediaReceiveCa
```

**Comment by shimat** [comment]
Sorry but I can't support Unity and Android environments; please contact the OpenCV plus Unity development team for more information.

Perhaps the native bindings (OpenCvSharpExtern) for Android don't exist or are incorrectly configured. I've never made it for Android, so I'm assuming it's being made by the OpenCV plus Unity team.

I wish I could support as many environments as possible, but my ability and time is limited.

**Comment by TheBricktop** [comment]
@jeyemwey  please check this repository, its the original author's repository of the project including the sharpextern 1-1 source,
im currently trying to add the bindings to the 4.5 version of opencv but im not too savvy in it yet.

**Comment by lmtapia** [comment]
@jeyemwey the problem is there is no ARM64 plugin, I used that package for some time and built Unity projects with Mono (2.0) without troubles targeting for ARMv7.  I would like to know if you found another solution or anything.

**Comment by lmtapia** [comment]
@TheBricktop did you forget to add the repo, is [InstytutXR/OpenCV-plus-Unity](https://github.com/InstytutXR/OpenCV-plus-Unity) right? I'm staring right now to build it later. I would know to know if is active.

**Comment by lmtapia** [comment]
@TheBricktop you forgot to add the repo. Is [InstytutXR/OpenCV-plus-Unity](https://github.com/InstytutXR/OpenCV-plus-Unity) right? I'm staring right now to build it later. I would like to know if it is active or it will be.
