### ISSUE TITLE
Compile opencvsharp and cuda

### ISSUE THREAD

**Issue by kesoul** [shimat/opencvsharp#1011]
# Summary of your issue

# Environment

Write your environment.
Windows10
Visual Studio 2019
opencvsharp 4.4.0
opencv_files (opencv 4.4.0 , opencv_contirb 4.4.0)
cuda10.2
cudnn 7.6.5
GTX 1060ti 6G
# What did you do when you faced the problem?

Write here
I have successfully compiled opencv in opencv_files, but I ran into problems when compiling opencvsharp.
First, I added ENABLED_CUDA in the opencvsharp4\src\OpenCvSharp\OpenCvSharp.csproj file; I added ENABLED_CUDA under Properties -> C/C++ -> Preprocessor.
Then, open the OpencvSharp project, and add the include directory under the OpenCvSharpExtern project -> Release x64 -> under the VC++ directory:
 opencv/include;opencv/include/opencv2;CUDA/v10.2/include; 
add opencv under the library directory -> /x64/vc16/lib;CUDA/v10.2/lib/x64; 
added opencv_world440.lib;opencv_world440d.lib; in the linker -> additional dependencies;

Then, when I generated the OpenCvSharpExtern project, an error (Undefined identifier) appeared in the cuda.h file. I followed the VS2019 prompt and added two lines of code, and the error disappeared 
#include <core\cuda.hpp>
using namespace cv::cuda;

But, when I compile again, the cuda_Mat.h file reported an error, unable to transfer CvSlice to cv::Range, unable to transfer cv::Size to CvSize, and unable to transfer cv::Point to CvPoint
I can't find a solution to this problem, can you help me?

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

## What did you intend to be?
At present, I can't find the complete documentation for compiling OpencvSharp (with GPU function, CUDA). There is no specific method in opencv_files and ReadMe.txt. Will you help me with this problem? or Can you tell me how to compile OpencvSharp with CUDA? I want to use CUDA acceleration in OpencvSharp.

**Comment by shimat** [comment]
Currently OpenCvSharp does not support CUDA, and implementations such as ENABLED_CUDA and cuda_Mat.h are so outdated. Sorry, I'm not addressing this issue so I'm closing it.
https://github.com/shimat/opencvsharp/pull/593
