### ISSUE TITLE
How to use iterator(like c++) and Cv2.Norm

### ISSUE THREAD

**Issue by lyling** [shimat/opencvsharp#1020]
# Summary of your issue
I get some c++ sample code from others. 

1.It use begin() and end() methods to get an iterator like  Mat_<Vec3b>::iterator it=ImageLab.begin<Vec3b>();

what is it in opecvsharp? 

2.  it uses “norm<int,3>” to calculate the distance bewteen two colors
 int dist=static_cast<int>(norm<int,3>(Vec3i((*it)[0]-target[0],
            (*it)[1]-target[1],(*it)[2]-target[2])));
I try Cv2.Norm methods. but i don`t know how to set the parameter. it`s InputArray.

# Environment

Windows 10
Visual Studio 2019

# What did you do when you faced the problem?

Write here

## Example code:

```
Mat colorDetect::process(const Mat& image)
{
    Mat ImageLab=image.clone();
    result.create(image.rows,image.cols,CV_8U);

    cvtColor(image,ImageLab,CV_BGR2Lab);
    Mat temp(1,1,CV_8UC3);
    temp.at<Vec3b>(0,0)=target;
    cvtColor(temp,temp,CV_BGR2Lab);
    target=temp.at<Vec3b>(0,0);

    Mat_<Vec3b>::iterator it=ImageLab.begin<Vec3b>();
    Mat_<Vec3b>::iterator itend=ImageLab.end<Vec3b>();
    Mat_<uchar>::iterator itout=result.begin<uchar>();
    while(it!=itend)
    {      
        int dist=static_cast<int>(norm<int,3>(Vec3i((*it)[0]-target[0],
            (*it)[1]-target[1],(*it)[2]-target[2])));
        if(dist<minDist)
            (*itout)=255;
        else
            (*itout)=0;
        it++;
        itout++;
    }
    return result;
}
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
1. Mat iterator is not available in C# as it is in C++. Instead, please access each pixel with an indexer.
```c#
int rows = ImageLab.Rows;
int cols = ImageLab.Cols;

// 1.simple
for (int y = 0; y < rows; y++)
{
    for (int x = 0; x < cols; x++)
    {
        Vec3b pixel = ImageLab.Get<Vec3b>(y, x);
        ...
        result.Set(y, x, (byte)255);
    }
}

// 2.indexer (faster than 1)
var indexer = ImageLab.GetUnsafeGenericIndexer<Vec3b>();
for (int y = 0; y < rows; y++)
{
    for (int x = 0; x < cols; x++)
    {
        Vec3b pixel = indexer[y, x];
        ...
```

2. I have tried to solve this problem by https://github.com/shimat/opencvsharp/pull/1036
