### ISSUE TITLE
HOG cascade is not supported?

### ISSUE THREAD

**Issue by otaisuke** [shimat/opencvsharp#1022]
# Summary of your issue

I have started to code with OpenCvSharp just recently and tried object recognition with cascade classifier.  
When an instance of CascadeClassifier class is created with trained data with HOG feature, OpenCvSharp.OpenCVException occurs as 
'HOG cascade is not supported in 3.0'.
However when an instance of CascadeClassifier is created with trained data with HAAR or LBP feature , the code works well.

# Environment

Windows 10 64bit
VS 2017,  .NET 4.7.2
OpenCvSharp 4.4.0 by Nuget.

# What did you do when you faced the problem?

I have tried to create instances of CascadeClassifier  with data of other features as HAAR and LBP and found no problems.
only with HOG was problem.
I searched HOG with openCV in internet and found that openCV stopped to support HOG feature at version 3.0. but it comes back after version.

## Example code:

```
 var cascade = new CascadeClassifier(".\\HOGcascade.xml");   -> Exception

 var cascade = new CascadeClassifier(".\\HAARcascade.xml");   ->  OK
 var cascade = new CascadeClassifier(".\\LBPcascade.xml");       ->  OK
``` 

## Output:

```
OpenCvSharp.OpenCVException: 'HOG cascade is not supported in 3.'
```

## What did you intend to be?

I am wondering if OpenCvSharp 4.4 equips with OpenCV 3.0 and want to know how to use CascadeClassifier class with data of HOG feature with OpenCvSharp.

Thank you for your kindness

Best regards,

**Comment by shimat** [comment]
The HOG cascade feature was deleted in OpenCV 3.0. https://github.com/opencv/opencv/issues/4989
OpenCvSharp4.4 wraps OpenCV4.4. I think you should try HOGDescriptor.

**Comment by otaisuke** [comment]
Thank you for you quick reply. got it.
