### ISSUE TITLE
WpfExtensions

### ISSUE THREAD

**Issue by VadCher** [shimat/opencvsharp#1023]
BitmapSourceConverters was removed to  WpfExtensions but WpfExtensions.dll is absent in last stable version 4.4.0.20200725

**Comment by shimat** [comment]
Thanks. I've included OpenCvSharp.WpfExtensions.dll in the Release package.
https://github.com/shimat/opencvsharp/releases/tag/4.4.0.20200725

There is already a NuGet package that only contains WpfExtensions.
https://www.nuget.org/packages/OpenCvSharp4.WpfExtensions

**Comment by VadCher** [comment]
Hello!
Something's wrong.

WpfExtentions not installed with base package via Visual Studio. Need an
additional WpfExtentions package to install. But in the base package ZIP
from github WpfExtentions is present.

Vadim.

вт, 18 авг. 2020 г. в 14:14, shimat <notifications@github.com>:
