### ISSUE TITLE
Cannot find MatOfUShort data type

### ISSUE THREAD

**Issue by dominota** [shimat/opencvsharp#1029]
# Summary of your issue

In my old project that uses OpenCvSharp3, there is a variable with data type **MatOfUShort**
Now i want to update my project to OpenCvSharp4 but i can not find MatOfUShort data type.
# Environment

Windows 10 x64
Visual Studio 2017

# What did you do when you faced the problem?

I can not build project because the compiler can not find MatOfUShort  data type

## Example code:
```
public OpenCvSharp.MatOfUShort depth;
```

## Output:
```
error CS0234: The type or namespace name 'MatOfUShort' does not exist in the namespace 'OpenCvSharp' (are you missing an assembly reference?)
```

## What did you intend to be?
Can you point me which data type i can replace for MatOfUShort ?
Thanks

**Comment by shimat** [comment]
Please use `Mat<ushort>` instead. Classes named `MatOf***` were deleted.

**Comment by dominota** [comment]
Thank you so much! @shimat
