### ISSUE TITLE
Correct way of reclaiming native objects

### ISSUE THREAD

**Issue by vnesterovsky** [shimat/opencvsharp#1030]
Many OpenCvSharp classes encapsulate native objects and implement IDisposable interface.
This means that all such objects are better to be disposed by program rather than to let GC to do the job.

Consider one of many examples I have seen:

```C#
using var mask = input.
  Threshold(100, 255, ThresholdTypes.BinaryInv | ThresholdTypes.Otsu).
  Dilate(new Mat());
```

This declaration creates at least two intermediate `Mat` instances (for `Threshold()` and `new Mat()`).
The similar intermediate objects are created when you deal with `MatExpr`, or with `InputArray` and `OutputArray`.

The problem is that the library the way it's written, using fluent API with overload of operators, hides most such intermediate objects. 

This makes native heap to tightly depend on GC, which is, in my opinion, bad.

Can you please confirm or dispel  my fears?

**Comment by shimat** [comment]
Your concerns are correct; I think it's preferable not to connect Mat method more than twice.
I am aware of the problems with this fluent API, but I am leaving it in place because it can be useful in some cases. One of the reasons for this is to maintain compatibility.

```c#
using var binary = input.Threshold(100, 255, ThresholdTypes.BinaryInv | ThresholdTypes.Otsu);
using var mask = binary.Dilate(null);
```

```c#
using MatExpr zerosExpr = Mat.Zeros(3, 3, MatType.CV_8UC1);
using Mat zeros = zerosExpr;
```

NET runtime is not concerned with memory allocated by native OpenCV, so it's hard to trigger automatic GC. It's better to make sure to use "using" or explicitly call GC.Collect.

**Comment by vnesterovsky** [comment]
Thank you for the confirmation.

To workaround the problem I've implemented a small API to keep scope of resources:

```C#
  public class Scope: IDisposable
  {
    public void Dispose()
    {
      ExceptionDispatchInfo error = null;
      
      while(resources.TryPop(out var resource))
      {
        try
        {
          resource.Dispose();
        }
        catch(Exception e)
        {
          if (error != null)
          {
            error = ExceptionDispatchInfo.Capture(e);
          }
        }
      }

      error?.Throw();
    }

    public T Add<T>(T resource)
      where T : IDisposable
    {
      resources.Push(resource);

      return resource;
    }

    private readonly Stack<IDisposable> resources = new Stack<IDisposable>();
  }

  public static class ScopeExtension
  {
    public static T In<T>(this T resource, Scope scope)
      where T : IDisposable
    {
      return scope.Add(resource);
    }
  }
```

Then the use case is:

```C#
using var scope = new Scope();

var mask = input.
  Threshold(100, 255, ThresholdTypes.BinaryInv | ThresholdTypes.Otsu).In(scope).
  Dilate(new Mat().In(scope)).In(scope);
```

This is still far from perfect but at least it disposes objects timely.

The library could introduce even stronger feature, e.g.:
- scope could use TLS to track current scope per thread;
- disposable instances could register themselves, if there is the current scope, if any.
