### ISSUE TITLE
CornerHarris: "Unknown/unsupported border type"

### ISSUE THREAD

**Issue by JulianGmp** [shimat/opencvsharp#1032]
Hello
Sorry for bothering about the corner detection (I opened #981)

I finally got around to test CornerHarris , but I ended up getting an OpenCVException saying "Unknown/unsupported border type".
I looked at the actual code pushed in #1006, I'm not entirely sure but I think there's a parameter missing.

It's declared with
```cs
imgproc_cornerHarris(IntPtr src, IntPtr dst, int blockSize, int ksize, int borderType)
```
https://github.com/shimat/opencvsharp/pull/1006/commits/361045143c5cbd0c97eabce780c4478c3006a3d6#diff-efb9adb54dc4a4a805a79ef5f1d66f43R88

Shouldn't the parameter `double k` (which is included in `Cv2.CornerHarris`) be the second to last? Like in the opencv implementation:
https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/imgproc/src/corner.cpp#L646

**Comment by shimat** [comment]
Thanks!
#1033
