### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by ucyildirim** [shimat/opencvsharp#1037]
# Summary of your issue

Everything is fine and working on Windows machine but, when I try to run my project on RaspberryPi, project throws an exception and says "cant find libOpenCvSharpExtern.so file". From what I understand, I've to build the OpenCVSharp on linux to generate *.so file.

According to [Wiki](https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Unix), everything fine until  **make**

```
git clone https://github.com/shimat/opencvsharp.git 
cd opencvsharp/src
cmake . 
make <--- HERE.
```

Once i hit enter, i get this error.

```
pi@raspberrypi:/home/cv/opencvsharp/src/build $ make
[ 96%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/aruco.cpp.o
In file included from /home/cv/opencvsharp/src/OpenCvSharpExtern/aruco.h:4,
                 from /home/cv/opencvsharp/src/OpenCvSharpExtern/aruco.cpp:1:
/home/cv/opencvsharp/src/OpenCvSharpExtern/include_opencv.h:49:10: fatal error: opencv2/img_hash.hpp: No such file or directory
 #include <opencv2/img_hash.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/build.make:63: OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/aruco.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
 ## Environment

Raspberry Pi 4 8GB, Raspbian Lite 32bit  

What I am doing wrong here? OR, do I realy have to build from source to generate *.so file?

**Comment by shimat** [comment]
> do I realy have to build from source to generate *.so file?

Yes. Please make sure that your OpenCV includes opencv_contrib and img_hash module.

**Comment by uurcm16** [comment]
> > do I realy have to build from source to generate *.so file?
> 
> Yes. Please make sure that your OpenCV includes opencv_contrib and img_hash module.

Thank you for the fast answer. Re-building the OpenCV with contrib fixed the issue.
Here is the deal, I've multiple Raspberry Pi's, and I want to move my project to the others. What is the right way to move that .so file? Building OpenCV on Raspberry takes forever.

**Comment by shimat** [comment]
Sorry, but I'm not familiar with the Raspberry Pi so I can't make any useful comments.
Due to dependent libraries, OpenCV(Sharp) may not work if you just copy the .so file you created once to another environment.
