### ISSUE TITLE
Cv2.Imshow()  AccessViolationException

### ISSUE THREAD

**Issue by danding7029** [shimat/opencvsharp#1039]
# Summary of your issue

When I try to use method Imshow() in opencvsharp 4 version 4.0.0.20181129. It's throw exception AccessViolationException

# Environment

Visual Studio 2017

# What did you do when you faced the problem?

Write here

## Example code:
```c#
IntPtr data = rawImage.DataPtr;
using (Mat img = new Mat((int)height, (int)width, MatType.CV_8UC3, data))
{
    Cv2.ImShow("photos", img);
    Cv2.WaitKey(1);
}
```

## Output:

AccessViolationException()

**Comment by shimat** [comment]
Could you tell me more about `rawImage`? How did you create it?

**Comment by danding7029** [comment]
OK. The rawimage is from the code "IManagedImage rawImage = cam.GetNextImage()"
I use the USB3.1 camera to capture the images. The IManagedImage is a interface, I can capture a image from it. 
 **The c++ code is**
unsigned int rows = pResultImage->GetHeight();
                    unsigned int cols = pResultImage->GetWidth();
                    unsigned int num_channels = pResultImage->GetNumChannels();
                    void *image_data = pResultImage->GetData();
                    unsigned int stride = pResultImage->GetStride();
                    Mat current_frame = cv::Mat(rows, cols, (num_channels == 3) ? CV_8UC3 : CV_8UC1, image_data, stride);

The code is used to convert the IManagedImage object to Mat object.

**I need to use C# code instead of C++ code, so I rewrite C# code** 

**The C# code is:**
 IntPtr data = rawImage.DataPtr;
                                    using (Mat img = new Mat((int)height, (int)width, MatType.CV_8UC3, data))
                                    {
                                        Cv2.ImShow("photos", img);
                                        Cv2.WaitKey(1);
                                    }

yesterday, I successfully use C# code to capture the image only once, but I can't use it later.

"AccessViolationException" is the cause. I want to know how can I new a Mat from a existed 

object. I think the system reclaims the object ahead of time.

**Comment by shimat** [comment]
What is the `rawImage`'s type?  It doesn't seem to be a Mat of OpenCvSharp; there is no member named DataPtr.

**Comment by danding7029** [comment]
The rawImage 's type is ManagedImage. The ManagedImage is a type that the USB camera supports. The ManagedImage type can be converted to Bitmap、byte[]、byte*

**Comment by shimat** [comment]
Thank you. I'm not sure, but if the ManagedImage is released immediately after creating a Mat from ManagedImage.DataPtr, I think that could cause AccessViolation. Copying the pixel value of the ManagedImage may possibly solve the problem.
```c#
// 1
long srcLength = stride * width;
using Mat img = new Mat((int)height, (int)width, MatType.CV_8UC3);
// requires .net framework 4.6 or later
Buffer.MemoryCopy(rawImage.DataPtr.ToPointer(), img.DataPointer, image.Step(), srcLength); 

Cv2.ImShow("photos", img);
...
```
```c#
// 2
using (Mat img = new Mat((int)height, (int)width, MatType.CV_8UC3, data))
using (Mat imgCopy = img.Clone())
{
    Cv2.ImShow("photos", imgCopy);
    ...
```

**Comment by danding7029** [comment]
Thank you. What is the type of "image" from "long dstSizeInBytes = image.Total() * image.ElemSize();" . Is the type of image Mat? How can I define the image?
`

`

**Comment by shimat** [comment]
Sorry, I modified the code. (I don't test it)

**Comment by danding7029** [comment]
Thank you.
