### ISSUE TITLE
MacOS runtime error (Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies)

### ISSUE THREAD

**Issue by ermaniwe** [shimat/opencvsharp#1041]
# Summary of your issue

Hi! My issue is very similar to #949. The only difference is that I use C# .NET Core 3.1 project.
I get Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies constantly while trying to create Mat object.
I have correct nuget packages and copiyng libOpenCvSharpExtern.dylib from runtimes to netcoreapp3.1 folder. I also made an app to run in x64, but it didn't help.

# Environment

MacOS 10.15.4, Visual Studio for Mac 8.7.4 (build 11)

## Output:

```
"Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libOpenCvSharpExtern, 1): image not found"
```

**Comment by Realgomu** [comment]
I have the same error

**Comment by szp11** [comment]
I had some error

**Comment by jlorek** [comment]
Had the same problem with Xcode already installed. What worked for me was to update all required libs for OpenCV. You can find them here: https://github.com/shimat/opencvsharp/blob/master/.github/workflows/macos10.yml
```
brew install wget pkg-config mono-libgdiplus gtk+ ffmpeg glog yasm harfbuzz jpeg libpng libtiff openexr openjpeg metis openblas opencore-amr protobuf tbb webp
```

**Comment by Lerseb** [comment]
OpenCvSharp library looks amazing and I am looking forward to see it in action.
But right now, I am having the same problem with OpenCvSharpExtern (Unable to load shared library) in my web app created with Visual Studio for Mac and deployed on a local docker container.
Visual Studio doesn't give much information on his Docker compose deployment and I don't know if I need OpenCvSharp-runtime for Mac or the one for Debian (which I kind of think the container is deployed locally on).
It would be amazing to have a detailed list of what needs to be done to make sure this dll is accessible to the app.
Any help would be wonderful!
