### ISSUE TITLE
Development / nightly builds

### ISSUE THREAD

**Issue by JulianGmp** [shimat/opencvsharp#1044]
Is there a convenient way to get the latest build (of the master branch)?
Something like nightly builds.

The readme links to https://ci.appveyor.com/nuget/opencvsharp
But the link seems to be dead?

I tried building it myself but I think I'm too stupid to understand Visual Studio with C++ and C#.
If you have a CI running it would be great to access these builds.

**Comment by shimat** [comment]
The link https://ci.appveyor.com/nuget/opencvsharp is alive and well. Please add the link as a new NuGet package source.

Here's an example of how to set it up in the Visual Studio’s Tools->Options dialog, though the Japanese UI may be confusing.
![image](https://user-images.githubusercontent.com/4434824/92386235-5b510180-f14e-11ea-9ed8-b721dffe5407.png)

**Comment by JulianGmp** [comment]
Oh it was a package source link. Sorry that went completely over my head

The command line equivalent to the options in visual studio should be
```sh
dotnet package add opencvsharp4 -s "https://ci.appveyor.com/nuget/opencvsharp"
```

I noticed two things:
- You need to specify `opencvsharp4`, and not `opencvsharp`. Otherwise you'll add a very outdated version which confused me for a moment.
- you can also use `http://` to avoid using TLS, useful if you're behind a corporate proxy

Thank you for your quick help!

**Comment by lemonfunk** [comment]
It seems the source is empty? i'm looking for a new build because of the "halftone" issue. In the moment, i  cannot use opencvsharp with my camera images.
