### ISSUE TITLE
Is there any way to set the loading path of DLL file

### ISSUE THREAD

**Issue by howzew** [shimat/opencvsharp#1047]
# Summary of your issue

Is there any way to set the loading path of DLL file?

For example, for ”OpenCvSharpExtern“ , the default path is ”bin / debug / DLL / x64“. If I want to change it to ”Desktop/MyProgect / DLL / x64“, what should I do? Is there a variable like "EnvironmentPath"?

# Environment

win 10 .NET Framework 4.6  vs 2019 C#

# What did you do when you faced the problem?

Can't change the loading path of the dll

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/PInvoke/WindowsLibraryLoader.cs#L64

Please try this:
```c#
var desktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
WindowsLibraryLoader.Instance.AdditionalPaths.Add(Path.Combine(desktop, "MyProgect/DLL/x64")); 
```

**Comment by howzew** [comment]
> https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/PInvoke/WindowsLibraryLoader.cs#L64
> 
> Please try this:
> 
> ```cs
> var desktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
> WindowsLibraryLoader.Instance.AdditionalPaths.Add(Path.Combine(desktop, "MyProgect/DLL/x64")); 
> ```

Thank you very much!
