### ISSUE TITLE
 Passing Mat to a function C#

### ISSUE THREAD

**Issue by alexdr488** [shimat/opencvsharp#1049]
# Summary of your issue

I have error: object is disposed

# Environment

.NetCore 3.1, C#

# What did you do when you faced the problem?

How to work properly with Mat as disposale object?

Do I have to write using ```Mat myMat = new Mat () ;``` ? Or is it possible without using?

## Example code:

How to work properly with Mat as disposale object?

I am getting the error object is disposed. 

Steps:

Method 1:
1) Create Mat:
```
using Mat myMat = new Mat () ;
```
2) Create Function:
 ```
     private Mat TransformMat(Mat myMat) {
         Cv2.GaussianBlur(myMay, myMat, new Size(3,3));
         //How to return myMat?
      }
```

3) Call function:  
  ```
    var result  = TransformMat(myMat);
  ```

Method 2:
1)  Create Function:
   ```
     private Mat TransformMat() {
         using Mat myMat = new Mat () ;
         Cv2.GaussianBlur(myMay, myMat, new Size(3,3));
        return myMat;
      }
```
2) Get result:
 ```
  var result  = TransformMat(myMat);
 //ERROR: disposable object!!!
 ```

Please tell me how to properly initialize Mat, pass it to a function, change it in a function and get the result? If possible, give an example, thanks.

**Comment by shimat** [comment]
You should not dispose return value in function.
```c#
using var mat = TransformMat();

Mat TransformMat() 
{
    Mat myMat = new Mat () ;
    Cv2.GaussianBlur(myMay, myMat, new Size(3,3));
    return myMat;
}
```

If the OpenCV function supports in-place mode (where we can specify the same variable for `src` and `dst`), you can write it as follows. (GaussianBlur supports in-place mode.)
```c#
using var mat = new Mat();
TransformMat(mat); 

void TransformMat(Mat mat) 
{
    Cv2.GaussianBlur(mat, mat, new Size(3,3));
}
```

This is a question about C#, not OpenCvSharp. It might be easier to understand if you think of it as replacing Mat with System.IO.StreamReader, for example.
