### ISSUE TITLE
Unable to perform Dual TV-L1 calculation

### ISSUE THREAD

**Issue by wouterpleizier** [shimat/opencvsharp#105]
I'm trying to calculate the optical flow between two images using the Dual TV-L1 algorithm. I am able to initialize the algorithm by calling `Cv2.CreateOptFlow_DualTVL1()`, but I can't seem to perform the calculation. The returned object's `Calc` method is protected and abstract, and it's only implemented in `DenseOpticalFlowImpl`, which is an internal sealed class.

Is the wrapper for this algorithm incomplete, or have I overlooked something?

**Comment by wouterpleizier** [comment]
I see that 64ff4838bb736dc2a3c494015f8e2e45e2dde875 addresses this issue. However, it looks like the most recent build does not include those changes. Is this intentional?

Thank you for your efforts, by the way. OpenCvSharp is very pleasant to work with :smiley:

**Comment by shimat** [comment]
The previous `DenseOpticalFlowExt.CreateDualTVL1` in OpenCvSharp calls createOptFlow_Farneback . I fixed this https://github.com/shimat/opencvsharp/commit/f5678cf21b2e74c7af91a316b938293bc647615c　Thank you :+1:

It looks like OpenCvSharp.CPlusPlus.dll in the latest release already contains a public Calc method.

**Comment by wouterpleizier** [comment]
> It looks like OpenCvSharp.CPlusPlus.dll in the latest release already contains a public Calc method.

Ah, I was looking at `DenseOpticalFlow` instead of `DenseOpticalFlowExt`. The latter indeed has a public Calc method. In that case, what is the purpose of `DenseOpticalFlow`? The difference between these classes is not clear to me.
