### ISSUE TITLE
cv2 output different in c# and python 

### ISSUE THREAD

**Issue by netilovefm1** [shimat/opencvsharp#1054]
# Summary of your issue

# Environment

.NET OPENCVSHARP4.WINDOWS

# What did you do when you faced the problem?

In Python cv2.imread() got a output : 
[[42. 49. 58.]
  [40. 47. 56.]
  [36. 43. 52.]
but in c# I got a output : 

63.00,82.00,95.00
61.00,83.00,95.00
77.00,97.00,114.00
first 3 row output 
(and other output also different)

I don't know why this happend .... 

When I tried to other project it was same but now it's different 
 
## Example code:

python : 
def read_image_bgr(path):

    image = cv2.imread(path) #수
    print(image[0,:])
    return  image 

c#:
            Mat img1 = Cv2.ImRead(path);
            img1.ConvertTo(img1, MatType.CV_32FC3);
            PrintDataMat(img1);

## Output:

n Python cv2.imread() got a output : 
[[42. 49. 58.]
  [40. 47. 56.]
  [36. 43. 52.]
but in c# I got a output : 

63.00,82.00,95.00
61.00,83.00,95.00
77.00,97.00,114.00

## What did you intend to be?
I wanted to get same output but it's different 
I guess to try to change x axis and y axis but it's not same ..... 
why it is happend ...

**Comment by shimat** [comment]
Could you tell us more about `PrintDataMat`?

**Comment by netilovefm1** [comment]
public void PrintDataMat(Mat m)
        {
            unsafe
            {
                for (int y = 0; y < m.Size().Height; y++)
                {
                    var p = m.Ptr(y); 
                    var ptr = (float*)p.ToPointer();
                    if (y == 1) break;
                    for (int x = 0; x < m.Size().Width * 3; x += 3)
                    {
                        if (x < 7 || x >= 1266) { Console.WriteLine($"{ptr[x]:f},{ptr[x + 1]:f},{ptr[x + 2]:f}"); }
                        
                    }
                }
            }
        }

this is PrintDataMat
first 3 row and last 4rows 
becasue python print(image) shows first 3row and last 3row 
so I make if  liket that 
and I tried to use mat.At too .... but got a same output

**Comment by shimat** [comment]
I tried your code with the attached jpeg image in my environment and got the following results. (OpenCvSharp 4.4.0)
```c#
using var img1 = new Mat("95073560-07830980-0748-11eb-89a0-42a05834765b.jpg");
img1.ConvertTo(img1, MatType.CV_32FC3);
PrintDataMat(img1);
```
```
47.00,53.00,58.00
49.00,55.00,60.00
48.00,54.00,59.00
23.00,32.00,41.00
24.00,33.00,42.00
28.00,37.00,46.00
28.00,37.00,46.00
```

`img1(0, 0) = (47,53,58)` (BGR)

In IrfanView, a well-known image viewer, the RGB pixel values at (0,0) of the image are `(58,53,47)`, which is consistent with my results. I couldn't see your problem.
![image](https://user-images.githubusercontent.com/4434824/95087076-32775880-075c-11eb-8baf-3ad17cafba08.png)

Incidentally, the pixel value of the JPEG-decoded output image can vary slightly depending on the type and version of the decoder.

**Comment by netilovefm1** [comment]
huh I updated to opencvshap4.4.0 output was same....

hmm 
the pixel value of the JPEG-decoded output image can vary slightly depending on the type and version of JPEG decoder.
but ... it's hard to understand 
it's why happened.... in my source ;;;; it makes me crazy

**Comment by netilovefm1** [comment]
ur windows version is what ?

**Comment by netilovefm1** [comment]
ah sorry was my mistake my source was corrupted thanks I close my issue
