### ISSUE TITLE
SEHException (0x80004005) on OCRTesseract.Run(...)

### ISSUE THREAD

**Issue by Blightbuster** [shimat/opencvsharp#1058]
# Summary of your issue

I have a application which runs fine on my development machine and most user machines.
Some users are however reporting that the application terminates with this error:
```
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at OpenCvSharp.NativeMethods.text_OCRTesseract_run1(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, Int32)
   at OpenCvSharp.NativeMethods.text_OCRTesseract_run1(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, Int32)
   at OpenCvSharp.Text.OCRTesseract.Run(OpenCvSharp.Mat, System.String ByRef, OpenCvSharp.Rect[] ByRef, System.String[] ByRef, Single[] ByRef, OpenCvSharp.Text.ComponentLevels)
```

# Environment

Windows 10 x64

# What did you do when you faced the problem?

Verified the function is called correctly ( not with null values ) and checked that the .net core 3.1 dependency is correctly installed.

## Code causing the issue
https://github.com/Blightbuster/RatScanner/blob/3ea387b9687fbfe44d5a19b640ae5eb3cecd7ea7/RatScanner/Scan/ItemNameScan.cs#L166

## Output:

```
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at OpenCvSharp.NativeMethods.text_OCRTesseract_run1(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, Int32)
   at OpenCvSharp.NativeMethods.text_OCRTesseract_run1(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, Int32)
   at OpenCvSharp.Text.OCRTesseract.Run(OpenCvSharp.Mat, System.String ByRef, OpenCvSharp.Rect[] ByRef, System.String[] ByRef, Single[] ByRef, OpenCvSharp.Text.ComponentLevels)
   at RatScanner.Scan.ItemNameScan.OCR(System.Drawing.Bitmap)
   at RatScanner.Scan.ItemNameScan..ctor(System.Drawing.Bitmap, RatScanner.Vector2)
   at RatScanner.RatScannerMain.NameScan(RatScanner.Vector2)
   at RatScanner.RatScannerMain+<>c__DisplayClass17_0.<OnMouseEvent>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by mpolicki** [comment]
I have encountered this as well, on Windows 10 x64, .Net Framework 4.7.2 and OpenCvSharp 4.5.1.20210210. Whether the exception gets thrown depends at least in part on the content of the image. I've whittled down a sample image that reliably causes this exception, along with this code:
```C#
using(var image = new Mat("SEHException minimum.png"))
using(var engine = OpenCvSharp.Text.OCRTesseract.Create(@"Data\tessdata", oem: 1))
    engine.Run(image, out var text, out _, out _, out _, OpenCvSharp.Text.ComponentLevels.TextLine);
```
![SEHException minimum](https://user-images.githubusercontent.com/1572421/109407423-f64dca00-7980-11eb-93ca-d1cecdd9181b.png)

The `Data\tessdata` folder contains a single file, `eng.traineddata`, obtained [here](https://github.com/tesseract-ocr/tessdata_best/blob/master/eng.traineddata) (the file is LSTM only which is why `oem` is `1` in the above code).

I assume there's an underlying exception that indicates the actual error. Is there any way to expose it to C# instead of just getting an `E_FAIL` `HResult`?

**Comment by levedeniz** [comment]
I am seeing this on Win10 x64 as well. I am using .Net 4.8 + OpenCvSharp 4.5.2. Only happens with **tessdata_best** and not with tessdata. Same code  works fine on Mac and Ubuntu though. There is not any information on the inner exception.

**Comment by Blightbuster** [comment]
I can confirm that this only happends with my custom trained lstm for a specific fint. It seems to fix the problem when using the pretrained `eng.traineddata`.

**Comment by mpolicki** [comment]
This still happens for me as described, in OpenCvSharp 4.5.3.20211207.

**Comment by EmonHaque** [comment]
Does it resolve the issue if you use `Mat` as follows instead of wrapping up that in using?
```
varocr = OpenCvSharp.Text.OCRTesseract.Create();
var mat = new OpenCvSharp.Mat(file);
ocr.Run(mat, out var outputText, out var componentRects, out var componentTexts, out var componentConfidences);
textBox.Text = outputText;
mat.Release();
mat.Dispose();
```
I've used these:
```
<ItemGroup>
  <PackageReference Include="OpenCvSharp4" Version="4.5.5.20211231" />
  <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.5.5.20211231" />
</ItemGroup>
```
in a WPF project and it works BUT in most of the cases it doesn't put space in between words.

**Comment by Blightbuster** [comment]
> Does it resolve the issue if you use `Mat` as follows instead of wrapping up that in using?
> 
> ```
> var ocr = OpenCvSharp.Text.OCRTesseract.Create();
> var mat = new OpenCvSharp.Mat(file);
> ocr.Run(mat, out var outputText, out var componentRects, out var componentTexts, out var componentConfidences);
> textBox.Text = outputText;
> mat.Release();
> mat.Dispose();
> ```
> 
> I've used these:
> 
> ```
> <ItemGroup>
>   <PackageReference Include="OpenCvSharp4" Version="4.5.5.20211231" />
>   <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.5.5.20211231" />
> </ItemGroup>
> ```
> 
> in a WPF project and it works BUT in almost all cases it doesn't put space in between words.

how does that make a difference? The `using` discards the allocated object only after the `ocr.Run(...)` and it already crashes before the end of the block is even reached.

**Comment by EmonHaque** [comment]
@Blightbuster, few hours ago I got the same error somewhere in my code, can't remember where exactly. Google/Bing brought me to this page and as I was reading suddenly the idea of using `Mat` that way came to my mind and gave that a shot and here's the result in my side:

![opencvsharp](https://user-images.githubusercontent.com/51259204/155598459-06610542-7716-46e9-8383-ff8f31d83938.PNG)

On the left the image and on the right the extracted Text. I've added these values in Constructor:
```
var ocr = OpenCvSharp.Text.OCRTesseract.Create(
    "tessData", 
    "eng", 
    "01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ -:'\"`~@#$%^&*()-=+_/<>?\\|",
    1);
```
to get space and other characters from image.

**Comment by Blightbuster** [comment]
But doesn't your code also work when not manually managing the allocated object by using the `using,` keyword?

**Comment by EmonHaque** [comment]
@Blightbuster, yes it does now, funny. At that time it didn't! I think, I also deleted `bin`, `obj` and `.vs` file after changing the code and closing the Visual Studio. This
```
using var mat = new OpenCvSharp.Mat(file);
ocr.Run(
    mat, 
    out var outputText, 
    out var componentRects, 
    out var componentTexts, 
    out var componentConfidences, 
    OpenCvSharp.Text.ComponentLevels.Word
);
box.Text = outputText;
```
now works as well.

Do you still have the issue?

**Comment by Blightbuster** [comment]
> @Blightbuster, yes it does now, funny. At that time it didn't! I think, I also deleted `bin`, `obj` and `.vs` folders after changing the code and closing the Visual Studio. This
> ```
> using var mat = new OpenCvSharp.Mat(file);
> ocr.Run(
>     mat, 
>     out var outputText, 
>     out var componentRects, 
>     out var componentTexts, 
>     out var componentConfidences, 
>     OpenCvSharp.Text.ComponentLevels.Word
> );
> box.Text = outputText;
> ```
> now works as well.
> 
> Do you still have the issue?

Yes I do. It seems to be an issue with the model used as described above.

**Comment by EmonHaque** [comment]
@Blightbuster, I also have tried it without any trained data like this:
```
ocr = OpenCvSharp.Text.OCRTesseract.Create(null, null,
    "01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ -:'\"`~@#$%^&*()-=+_/<>?\\;,|"); 
```
and it works fine without that. Looks like, all that it needs is a long string of characters you want to parse.

**Comment by Blightbuster** [comment]
It would be nice if at least (in case the issue cannot get properly fixed) the error message could become less obscure.
