### ISSUE TITLE
Are you support OCR feature?

### ISSUE THREAD

**Issue by jjnetpub** [shimat/opencvsharp#1059]
# Summary of your issue

I found BaseOCR.cs file in your directory.

But I can't find C# sample using your OpenCvSharp library for OCR feature.

Do I have to make my own OCR function?

**Comment by shimat** [comment]
The test code may help you.
https://github.com/shimat/opencvsharp/blob/master/test/OpenCvSharp.Tests/text/OCRTesseractTest.cs

**Comment by jjnetpub** [comment]
> The test code may help you.
> https://github.com/shimat/opencvsharp/blob/master/test/OpenCvSharp.Tests/text/OCRTesseractTest.cs

Thanks, But OpenClipBoard Failed exception occured at 

using (var tesseract = OCRTesseract.Create(TessData))

**Comment by jjnetpub** [comment]
> > The test code may help you.
> > https://github.com/shimat/opencvsharp/blob/master/test/OpenCvSharp.Tests/text/OCRTesseractTest.cs
> 
> Thanks, But OpenClipBoard Failed exception occured at
> 
> using (var tesseract = OCRTesseract.Create(TessData))

Solved. 

tessdata should be located at Debug or Release folder after downloading whole files from https://github.com/tesseract-ocr/tessdata.
