### ISSUE TITLE
FindCirclesGrid AccessViolation

### ISSUE THREAD

**Issue by nanostrukturtechniker** [shimat/opencvsharp#106]
I think, these are two different bugs, perhaps they mix up

Bug one was first mentioned in:
http://stackoverflow.com/questions/30004528/opencvsharp-accessviolationexception-in-findcirclesgrid

It seems that the call to the native function is ambiguous.

Bug two (if not the same as bug one or just masking it?)

If FindCirclesGrid is called in a function, the parameters seem to be garbage collected while still running. This leads to a AccessViolation. Accessing all parameters just after the whole detection seems to solve this.

**Comment by shimat** [comment]
Thank you. The exception does not occur in my environment, but I agree with you.

I added GC.KeepAlive before the end of FindCirclesGrid.
https://github.com/shimat/opencvsharp/commit/cf88602df322352d333631b9dee63a963d3fc5bc

This means that I have to add GC.KeepAlive to most OpenCvSharp methods... :scream:

**Comment by nanostrukturtechniker** [comment]
You can try moving the whole calibration routine into an extra DLL and call this from the main program. This triggers an AccessViolation for sure (at least at my environment: Latest OpenCVSharp and VS2013 Update 4). Also the error is more likely, when the PC is not under load. 
Atm, I try adding the GC.KeepAlive statements for all parameters after the call, but this did not help. The image is accessible (at least it can be displayed and accessed with other methods) and the other vars seem fine, too.
Unfortunately, this is company code and I cannot post it here and at home, I use plain C++...

**Comment by shimat** [comment]
> You can try moving the whole calibration routine into an extra DLL and call this from the main program. This triggers an AccessViolation for sure (at least at my environment: Latest OpenCVSharp and VS2013 Update 4). 
I could demonstrate the error. thanks! 

The AccessViolationException seems to be occurred by the ambiguity (you said 'bug one') of the native FindCirclesGrid invoker. After fixing the bug, the exception does not occur in my environment.

**Comment by nanostrukturtechniker** [comment]
It seems to work for me now. Thank you very much!

**Comment by nanostrukturtechniker** [comment]
Sorry, I have to reopen it: I used the function with no explicit blob detector called. When I use a SBD, the access violation occurs again (At least, when I'm using a grayscale image). If I use the same image after thresholding it, everythink works, so propably, the bug is in the SimpleBlobDetector?
