### ISSUE TITLE
Can not convert from NumSharp.NDArray to OpenCvSharp.InputArray

### ISSUE THREAD

**Issue by soundmartell** [shimat/opencvsharp#1062]
# Summary of your issue
I am converting a Pythion code to C# using Visual Studio 2019 with OpenCvSharp and NumSharp.

# Environment

using opencvsharp;
using numsharp;

# What did you do when you faced the problem?

I am converting a Pythion code to C# using Visual Studio 2019 with OpenCvSharp and NumSharp.

## Example code:

```
 kernel = np.ones((9, 9), np.uint8);
//frame2 and opening_ori are Mat, kernel is a NumSharp array
 Cv2.MorphologyEx(frame2, opening_ori, MorphTypes.Open, kernel);

```

## Output:

```
Can not convert from NumSharp.NDArray to OpenCvSharp.InputArray
```

## What did you intend to be?
I am converting this Python Code to C# using NumSharp and OpenCvSharp:
```
kernel = np.ones((9, 9), np.uint8)
opening_ori = cv2.morphologyEx(frame2, cv2.MORPH_OPEN, kernel)
```

**Comment by frg** [comment]
I'm having this issue too. I would guess that we need to convert it somehow but can't find the right way to do this.

**Comment by frg** [comment]
Just made my code work by making the following changes.

`var row1 = np.array(new[] {0, 1, 0}, np.uint8);`
`var row2 = np.array(new[] {0, 1, 0}, np.uint8);`
`var row3 = np.array(new[] {0, 1, 0}, np.uint8);`
`var kernel = np.array(new[] {row1, row2, row3}, np.uint8);`

`var morph = new Mat();`
`var kernelSize = kernel.GetData<int>();`
`var inputArray = InputArray.Create(kernelSize, MatType.CV_8U);`
`Cv2.MorphologyEx(canny, morph, MorphTypes.Open, inputArray);`

For anyone that got the error I cited in my previous comment, it seems like `CV_8U` is an alias for uint8

This means that the following code should work for you @soundmartell 

`kernel = np.ones((9, 9), np.uint8);`
`Cv2.MorphologyEx(frame2, opening_ori, MorphTypes.Open, InputArray.Create(kernel.GetData<int>(), MatType.CV_8U));`

Hope this helps

**Comment by minhduc66532** [comment]
The reason why your can't "consume" NDArray directly is because NumSharp.NET and OpenCVSharp are 2 different library developing by different people. If you want to use NDArray directly like in python use can try [SharpCV](https://github.com/SciSharp/SharpCV). But SharpCV missing A LOTS of features compare to OpenCVSharp

**Comment by hopeko** [comment]
Try this.
### Mat to NDArray
```csharp
public static NDArray ToNDArray(this Mat mat)
{
    var matType = mat.Type();
    var channels = mat.Channels();
    var size = mat.Rows * mat.Cols * channels;
    var shape = channels == 1 ? new Shape(mat.Rows, mat.Cols) : new Shape(mat.Rows, mat.Cols, channels);
    if (matType == MatType.CV_32SC1 || matType == MatType.CV_32SC2)
    {
        var managedArray = new int[size];
        Marshal.Copy(mat.Data, managedArray, 0, size);
        var aslice = ArraySlice.FromArray(managedArray);
        return new NDArray(aslice, shape);
    }
    if (matType == MatType.CV_32FC1)
    {
        var managedArray = new float[size];
        Marshal.Copy(mat.Data, managedArray, 0, size);
        var aslice = ArraySlice.FromArray(managedArray);
        return new NDArray(aslice, shape);
    }
    if (matType == MatType.CV_8UC1 || matType == MatType.CV_8UC3)
    {
        var managedArray = new byte[size];
        Marshal.Copy(mat.Data, managedArray, 0, size);
        var aslice = ArraySlice.FromArray(managedArray);
        return new NDArray(aslice, shape);
    }

    throw new Exception($"mat data type = {matType} is not supported");
}
```

### NDArray to Mat
```csharp
public static Mat ToMat(this NDArray nDArray) => 
    new Mat(nDArray.shape[0], nDArray.shape[1], nDArray.GetMatType(), (Array)nDArray);

public static MatType GetMatType(this NDArray nDArray)
{
    int channels = nDArray.ndim == 3 ? nDArray.shape[2] : 1;
    return nDArray.typecode switch
    {
            NPTypeCode.Int32 => channels == 1 ? MatType.CV_32SC1 : 
            channels == 2 ? MatType.CV_32SC2 :
            throw new ArgumentException($"nDArray data type = {nDArray.typecode} & channels = {channels} is not supported"),

            NPTypeCode.Float => channels == 1 ? MatType.CV_32FC1 :
            throw new ArgumentException($"nDArray data type = {nDArray.typecode} & channels = {channels} is not supported"),

            NPTypeCode.Byte => channels == 1 ? MatType.CV_8UC1 :
            channels == 3 ? MatType.CV_8UC3 :
            throw new ArgumentException($"nDArray data type = {nDArray.typecode} & channels = {channels} is not supported"),

            _ => throw new ArgumentException($"nDArray data type = {nDArray.typecode} is not supported")
    };
}
```
[The Interaction Between OpenCVSharp and NumSharp](https://www.cnblogs.com/dirtinfirework/articles/15468533.html)
