### ISSUE TITLE
Incomplete ANN_MLP setting methods

### ISSUE THREAD

**Issue by suomi-miartem** [shimat/opencvsharp#1065]
Hello!
I need to create and configure an ANN_MLP object, but I can do nothing but set layer sizes. For example, I want to set activation function like the same method from c++ documentation, but i haven't it in c# class. Nethertheless, I found ANN_MLP.ActivationFunctions enum in class desription. Does it have any activation function for correct work at all ? I guess ANN.MLP isn't done? Realize it soon please, I really need ))))

**Comment by shimat** [comment]
Thank you. I will add ActivationFunctions by #1070.

**Comment by suomi-miartem** [comment]
> Thank you. I will add ActivationFunctions by #1070.

God bless you! Now I don't need to "reinvent a (wheel) bicycle" making my own classifier class or trying to port c++ OpenCV libraries via c++/CLI. But will it appear in my my NuGet package ? I updated my current OpenCvSharp4.Windows NuGet package in Visual Studio, but for some reason I didn't find these changes there...

**Comment by shimat** [comment]
I only update NuGet occasionally because it's a lot of work.

You can use the nightly build (beta) versions of OpenCvSharp NuGet by registering https://ci.appveyor.com/nuget/opencvsharp as a NuGet Package Source.
