### ISSUE TITLE
Is there a way to display a Mat object inside the WPF Image tag and also with the SetMouseCallback event?

### ISSUE THREAD

**Issue by howzew** [shimat/opencvsharp#1066]
# Summary of your issue

I already know that I can use  BitmapSourceConverter.ToBitmapSource() to show the Mat in the WPF Image tag.
But I also want to use the SetMouseCallback event。
I checked the information and found that this method can only be used through two ways.

1:Cv2.SetMouseCallback(WindowName, Callbacksomething) ;
2:using var Image = new Window("image", WindowMode.AutoSize, img);
            Image.SetMouseCallback(...................
All of these methods need to create a new window。

Is there a way to display a Mat object inside the WPF Image tag and also with the SetMouseCallback event?

just like :
Mat Image = new Mat(@"C:\Users\Desktop\pic1.png", ImreadModes.AnyColor);
Image.SetMouseCallback(..............?

thank you!

# Environment

vs 2019 C# win 10 .net 4.6.1

# What did you do when you faced the problem?

Write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
You will have to define your own WPF mouse events. This isn't an OpenCvSharp topic, so I can't answer further.
```xml
<Window ... >
    ...
    <Image MouseDown="Image_MouseDown" MouseMove="Image_MouseMove" MouseUp="Image_MouseUp"/>
</Window>
```
```c#
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
namespace MouseCaptureSample
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
        private void ellipse1_MouseDown(object sender, MouseButtonEventArgs e)
        {
            ...
        }
        private void ellipse1_MouseMove(object sender, MouseEventArgs e)
        {
            ...
        }
        private void ellipse1_MouseUp(object sender, MouseButtonEventArgs e)
        {
            ...
        }
    }
}
```
