### ISSUE TITLE
Cannot find"findEssentialMat"in opencvsharp

### ISSUE THREAD

**Issue by andrealu2012** [shimat/opencvsharp#1067]
# Summary of your issue

# Environment

vs2017 win10
i get opencvsharp from nuget
# What did you do when you faced the problem?

Cannot find some method such as 

- findEssentialMat
- recoverPose

but this two methods can be found in
https://shimat.github.io/opencvsharp_docs/html/12c25bd5-c6f9-9d8b-1ee3-68b61fc78fb9.htm
https://shimat.github.io/opencvsharp_docs/html/10581f00-7a1a-057a-9747-20ffd60caa5e.htm

Thankyou!

**Comment by shimat** [comment]
You can use them... 
```c#
using OpenCvSharp;

Cv2.FindEssentialMat(...);
Cv2.RecoverPose(...);
```

**Comment by andrealu2012** [comment]
thank you,i mistake to use opencv3,and now change into opencv4 ,then them canbe found,thank you.
