### ISSUE TITLE
RecoverPose method question

### ISSUE THREAD

**Issue by andrealu2012** [shimat/opencvsharp#1069]
# Summary of your issue

when using recoverPose ,the application close immediately....please help ,thank you!
# Environment

Write your environment.
win10
vs2017
# What did you do when you faced the problem?

Write here

## Example code:

```
//cvp1 and cvp2 are List<OpenCvSharp.Point2f> with 8 points individually
            InputArray p1 = InputArray.Create(cvp1);
            InputArray p2 = InputArray.Create(cvp2);

            Mat r = new Mat();
            Mat tt = new Mat();

            OutputArray rr = OutputArray.Create(r);
            OutputArray ttt = OutputArray.Create(tt);

            OpenCvSharp.Cv2.RecoverPose(Essential, p1 , p2 , K, rr, ttt);
```

## Output:

```
when run the method,the application close immediately
```

**Comment by shimat** [comment]
Can we see the contents of variables Essential, cvp1, cvp2 and K?

**Comment by andrealu2012** [comment]
Essential:
[1.503247056657373e-16, -7.074103796034695e-16, -7.781514175638166e-16;
 6.720398606232961e-16, -6.189840821530359e-17, -0.7071067811865476;
 7.781514175638166e-16, 0.7071067811865475, -2.033804841359975e-16]

cvp1:
[1017.0883, 848.23529;
 1637, 848.23529;
 1637, 1648.7059;
 1017.0883, 1648.7059;
 2282.2144, 772;
 3034.9644, 772;
 3034.9644, 1744;
 2282.2144, 1744]

cvp2:
[414.88824, 848.23529;
 1034.8, 848.23529;
 1034.8, 1648.7059;
 414.88824, 1648.7059;
 1550.9714, 772;
 2303.7214, 772;
 2303.7214, 1744;
 1550.9714, 1744]

K:
[3011, 0, 1637;
 0, 3024, 1204;
 0, 0, 1]

Thank you very much!

**Comment by shimat** [comment]
Thank you. I found a bug in RecoverPose. It will be fixed by #1072.

**Comment by andrealu2012** [comment]
thank you,so could i update the opencvsharp.dll from github and compile again?

**Comment by shimat** [comment]
Yes, you can. #1072 has been merged into master.
Or you can use the nightly build version of nuget. Package source: https://ci.appveyor.com/nuget/opencvsharp
