### ISSUE TITLE
4.5.0 (13 Oct., 2020) The type initializer for 'OpenCvSharp.NativeMethods' threw an exception

### ISSUE THREAD

**Issue by blaisexen** [shimat/opencvsharp#1079]
windows 10 desktop app x64 .Net 4.6.1

when using with  versions 
OpenCvSharp-4.3.0-20200405 there is NO error, 
OpenCvSharp-4.4.0-20200917 there is NO error,
but with,
OpenCvSharp-4.5.0-20201013 there is AN error

The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

Cannot load the form

**Comment by shimat** [comment]
Could you check the dependencies of OpenCvSharpExtern.dll using [Dependency Walker](http://www.dependencywalker.com/) or [Dependencies](https://github.com/lucasg/Dependencies) or something similar tools?

**Comment by blaisexen** [comment]
@shimat Sir,
I tested both versions v4.4 and v4.5 they have the same library dependencies, 
OpenCvSharpExtern.dll of v4.5 has something wrong that I don't know.

I can compile it again, but still I don't know where's the problem occurs or started why it fails to load.

I will close this issue since you already know it,
thanks for your time
