### ISSUE TITLE
chamerMatching

### ISSUE THREAD

**Issue by VahidN** [shimat/opencvsharp#108]
Hello, Does OpenCVSharp support `chamerMatching`? Actually I want to convert this sample to OpenCVSharp: [chamfer.cpp](https://github.com/Itseez/opencv_attic/blob/master/opencv/samples/cpp/chamfer.cpp) and it uses a method called `chamerMatching` and I couldn't find it in OpenCVSharp.

**Comment by shimat** [comment]
Cv2.ChamferMatching was added at https://github.com/shimat/opencvsharp/releases/tag/2.4.10.20150820. Thanks!
