### ISSUE TITLE
Dnn Super Resolution Module

### ISSUE THREAD

**Issue by CobraCalle** [shimat/opencvsharp#1080]
Hello,

is an implemention for the DnnSuperResolution-module planned (https://github.com/opencv/opencv_contrib/tree/master/modules/dnn_superres)?

Thanks

Carl

**Comment by BergChristian** [comment]
Also interested in this!

**Comment by bradqiu1982** [comment]
pretty interesting in this

**Comment by bradqiu1982** [comment]
Hello,

I want to say your job is real nice. It make my job be very easy. 
Basing on your library, I build a really powerful OCR software.
I am so appreciate for your job.

I know you are very bussy, so I just hope to know whether the  dnn_superres function will be on your joblist.
The dnn_superres will make OCR software can read some poor quality picture.

Thank you
Brad

**Comment by bradqiu1982** [comment]
I blocked on below code. Any comment?

cv::dnn::LayerFactory::registerLayer("DepthToSpace", DepthToSpace::create);

**Comment by bradqiu1982** [comment]
It is so great that shimat will update on this issue. I almost check this issue every day. ^_^
