### ISSUE TITLE
Dnn.Net.ReadNetModelOptimizerでの挙動に関しての質問

### ISSUE THREAD

**Issue by yuki-snown** [shimat/opencvsharp#1083]
# Summary of your issue
お忙しい所失礼致します．
Dnn.Net.ReadNetModelOptimizerを呼ぶとエラーを吐いて落ちる.
interference_engine.dllを追加しようとしたが追加するpathが分からない．
といった所でつまづいており，アドバイスをいただけないでしょうか？

# Environment
windows10
visual studio2017
openvino
C#
OpenCvSharp4: v4.4.0
OpenCvSharp3-AnyCPU: v4.0.0

# What did you do when you faced the problem?

## Example code:

```
net = Dnn.Net.ReadNetModelOptimizer('hoge.xml', 'hoge.bin');
```

## Output:

```
OpenCvSharp.OpenCVExcaption: 'Build OpenCV with inteference Engine to enable loading models from Model Optimizer.'
```

## What did you intend to be?
エラーを解消したい．

**Comment by shimat** [comment]
OpenCvSharpは、私の方で事前にビルドしたOpenCVバイナリを元に動く構造です。そのビルドの際、Inference Engineを有効にしていないのが原因だと思います。

OpenCVの拡張モジュール・外部依存ライブラリの多さは正直常軌を逸していて、OpenCvSharpの今の仕組みを続ける以上は、すべての拡張を取り入れるのが現実的ではありません。かつ私個人の力ではカバーしきれないのもありまして、当面これを改善するのは考えていません。ただ、ご自分でカスタマイズは可能です。若干ハードルは高いので、C++やPythonで進める方が手っ取り早いとは思います。

（お使いの環境がわかりませんが仮にWindowsとして以下進めます）
OpenCVのバイナリ(DLL)は、以下のリポジトリでビルドしたものを使っています。
https://github.com/shimat/opencv_files

このPowerShellを動かせばよく、CMakeのパラメータが書いてあるのでそれをいじることになります。
https://github.com/shimat/opencv_files/blob/master/build_windows.ps1

本件ですと、試したことはないのですが以下を足す感じかと思います。
```
-D WITH_INF_ENGINE=ON `
-D InferenceEngine_DIR="<your_path>" `
```

これでOpenCVをビルドして、続いてOpenCvSharpのソリューションから `OpenCvSharpExtern` をビルドすると、`OpenCvSharpExtern.dll` というファイルができあがります。これを実行ファイルと同じ場所にでも置けばOKです。

WindowsではなくUbuntuでしたら、Dockerfileが参考になるかもしれません。
https://github.com/shimat/opencvsharp/blob/master/docker/ubuntu18-dotnetcore3.1-opencv4.5.0/Dockerfile

**Comment by yuki-snown** [comment]
お忙しい所ご回答ありがとうございます．
ご教授いただいた通り，試しにやってみます．
