### ISSUE TITLE
ubuntu 20.04 run error

### ISSUE THREAD

**Issue by LeifHwang** [shimat/opencvsharp#1085]
the error msg:
        linux-vdso.so.1 (0x00007ffeff7af000)
	libgtk-x11-2.0.so.0 => /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f94b57df000)
	libgdk-x11-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f94b5724000)
	libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f94b5601000)
	libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f94b55d9000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f94b5579000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f94b5450000)
	libtesseract.so.4 => /lib/x86_64-linux-gnu/libtesseract.so.4 (0x00007f94b5120000)
	libdc1394.so.22 => /lib/x86_64-linux-gnu/libdc1394.so.22 (0x00007f94b50a8000)
	libavcodec.so.57 => not found
	libavformat.so.57 => not found
	libavutil.so.55 => not found
	libswscale.so.4 => not found

help me

**Comment by shimat** [comment]
How did you set up your environment and how did you implement OpenCvSharp? The following NuGet is for 18.04, so it may not work on 20.04. https://www.nuget.org/packages/OpenCvSharp4.runtime.ubuntu.18.04-x64

Installing some additional apt packages may be a good solution.
https://github.com/shimat/opencvsharp/blob/master/docker/ubuntu18-dotnetcore3.1-opencv4.5.0/Dockerfile#L26
```
apt-get update && apt-get install \
      libjasper1 \
      libtiff-dev \
      libavcodec-dev \
      libavformat-dev \
      libswscale-dev \
      libxine2-dev \
      libv4l-dev
```

**Comment by LeifHwang** [comment]
> How did you set up your environment and how did you implement OpenCvSharp? The following NuGet is for 18.04, so it may not work on 20.04. https://www.nuget.org/packages/OpenCvSharp4.runtime.ubuntu.18.04-x64
> 
> Installing some additional apt packages may be a good solution.
> https://github.com/shimat/opencvsharp/blob/master/docker/ubuntu18-dotnetcore3.1-opencv4.5.0/Dockerfile#L26
> 
> ```
> apt-get update && apt-get install \
>       libjasper1 \
>       libtiff-dev \
>       libavcodec-dev \
>       libavformat-dev \
>       libswscale-dev \
>       libxine2-dev \
>       libv4l-dev
> ```





> How did you set up your environment and how did you implement OpenCvSharp? The following NuGet is for 18.04, so it may not work on 20.04. https://www.nuget.org/packages/OpenCvSharp4.runtime.ubuntu.18.04-x64
> 
> Installing some additional apt packages may be a good solution.
> https://github.com/shimat/opencvsharp/blob/master/docker/ubuntu18-dotnetcore3.1-opencv4.5.0/Dockerfile#L26
> 
> ```
> apt-get update && apt-get install \
>       libjasper1 \
>       libtiff-dev \
>       libavcodec-dev \
>       libavformat-dev \
>       libswscale-dev \
>       libxine2-dev \
>       libv4l-dev
> ```



> How did you set up your environment and how did you implement OpenCvSharp? The following NuGet is for 18.04, so it may not work on 20.04. https://www.nuget.org/packages/OpenCvSharp4.runtime.ubuntu.18.04-x64
> 
> Installing some additional apt packages may be a good solution.
> https://github.com/shimat/opencvsharp/blob/master/docker/ubuntu18-dotnetcore3.1-opencv4.5.0/Dockerfile#L26
> 
> ```
> apt-get update && apt-get install \
>       libjasper1 \
>       libtiff-dev \
>       libavcodec-dev \
>       libavformat-dev \
>       libswscale-dev \
>       libxine2-dev \
>       libv4l-dev
> ```

thanks!  :joy: finally it works!      I've tried the lib on hyper-v and a ubuntu tablet, all workd!
I uploaded the lib here :  https://github.com/LeifHwang/shared/tree/main/OpenCvSharp4.runtime.ubuntu.20.04-x64 .

Thanks again! You may publish the lib as a nuget package.
