### ISSUE TITLE
I can't write the mat to the video file when I use the ToMat method

### ISSUE THREAD

**Issue by gjlong** [shimat/opencvsharp#1089]
# my issue
Dear shimat,
I have some problems when I try to create a video file by the VideoWriter.
The first example is success.It can save the image file in the disk.
The second example can save the video file in the disk .And this video can be played.
But I can't play the video when I use the ToMat method in the third example.The video file is error.
When I used the ToMat method,I can create a image file in the disk.Why I can't create the video by this method？
Can you tell me where is wrong in my program and how to fix it？
Thank you.

# Environment

C#,
visual studio 2019,
.net framework 4.7.2,
OpenCvSharp4 4.5.0

## Example code:
Example 1:
```c#
Image img = System.Drawing.Image.FromFile(filePath);
Bitmap bmp = new Bitmap(img);
OpenCvSharp.Mat mat = BitmapConverter.ToMat(bmp);
Cv2.ImWrite("imagePath/imageName.bmp", mat);
```

Example 2:
```c#
OpenCvSharp.Size dsize = new OpenCvSharp.Size(1500, 3692);
FourCC codec = FourCC.XVID;
VideoWriter write = new VideoWriter("videoPath/videoName.avi", codec, 20.0, dsize, true);
DirectoryInfo directoryInfo = new DirectoryInfo("imagesPath");
FileInfo[] fileInfoList = directoryInfo.GetFiles();
foreach (FileInfo di in fileInfoList)
{
   OpenCvSharp.Mat mat = Cv2.ImRead(di.FullName);
    write.Write(mat);
}
    write.Release();
```

Example 3:
```c#
OpenCvSharp.Size dsize = new OpenCvSharp.Size(1500, 3692);
FourCC codec = FourCC.XVID;
VideoWriter write = new VideoWriter("videoPath/videoName.avi", codec, 20.0, dsize, true);
DirectoryInfo directoryInfo = new DirectoryInfo("imagesPath");
FileInfo[] fileInfoList = directoryInfo.GetFiles();
foreach (FileInfo di in fileInfoList)
{
      Image img = System.Drawing.Image.FromFile(di.FullName);
      Bitmap bmp = new Bitmap(img);
      OpenCvSharp.Mat mat = BitmapConverter.ToMat(bmp);
      write.Write(mat);
}
      write.Release();
```

## Output:

```
I can't create the video file in the third example.
```

**Comment by shimat** [comment]
Please make sure that `mat.Type()` is `MatType.CV_8UC3`. You may have to convert it into 8UC3 using `Cv2.CvtColor`. I don't even know for sure.

**Comment by gjlong** [comment]
> Please make sure that `mat.Type()` is `MatType.CV_8UC3`. You may have to convert it into 8UC3 using `Cv2.CvtColor`. I don't even know for sure.

The MatType is CV_8UC4.
I convert it into CV_8UC3.
And then this problem has been solved.
Now the video can be played.
Example code:
`
Cv2.CvtColor(mat, mat, ColorConversionCodes.BGRA2BGR);
`

Thank you very much!
