### ISSUE TITLE
Unity API updater breaks OpenCvSharp namespace

### ISSUE THREAD

**Issue by A00107408** [shimat/opencvsharp#1090]
# Summary of your issue

In 2018 I built a Unity project using OpenCvSharp for playing in Unity (never build or deploy to .exe). Now in 2020 I need to build and deploy this project to HoloLens 2 i.e.: Universal Windows Platform. When I try to build, Unity says my project is using obsolete APIs. When I build, The unity API updater breaks my code.

# Environment

Developing on Windows 10. Building for Universal Windows Platform targeting HoloLens 2.

# What did you do when you faced the problem?

Trying to build without API updater. No success. It always breaks the code when I try to build.

## Example code:

```
using OpenCvSharp;


```

## Output:

```
error CS0246: The type or namespace name 'OpenCvSharp' could not be found (are you missing a using directive or an assembly reference?)
```

## What did you intend to be?

Is the API updater detecting an old version of OpenCvSharp? Do I need to buy a new version from the asset store? Can I prevent Unity API updater from breaking OpenCvSHarp references in my project?

**Comment by KubilayT26** [comment]
I have same problem. Did you find any solution? Thanks.

**Comment by A00107408** [comment]
Yes , I paid for OpenCVForUnity which has all up to date APIs. OpenCV+Unity project is out of date.
