### ISSUE TITLE
Help building opencv with gstreamer support

### ISSUE THREAD

**Issue by valeriob** [shimat/opencvsharp#1098]
Hi,
i've rebuilt opencv in the repository of opencv_files with the gstreamer support (it automatically detects it once you put in the path the gstreamer installation folder).
Then i updated the content of this folder opencvsharp\opencv_files\opencv450_win_x64\ with the output of the opencv_files build, but when i try to rebuild opencvsharp, but i get this error :

![image](https://user-images.githubusercontent.com/1522516/101687728-3466dc00-3a6b-11eb-987f-bd1512123a4f.png)

I have added gstreamer pathsto the project OpenCvSharpExtern but without success :

![image](https://user-images.githubusercontent.com/1522516/101687787-4a749c80-3a6b-11eb-99f4-2c17b739e8a2.png)

Thanks

**Comment by shimat** [comment]
I guess you should modify linker settings to link gstreamer's .lib files.

**Comment by valeriob** [comment]
Thanks @shimat,
i've done that, is it possible that i need to use the msvc instead of the minigw version ?
![image](https://user-images.githubusercontent.com/1522516/101743368-fe594480-3aca-11eb-9da4-87a202fedeab.png)

**Comment by shimat** [comment]
You will probably need to change the Linker->Input settings as well. (I have no experience with GStreamer, so I can't comment further.)

**Comment by valeriob** [comment]
Thanks !

**Comment by ChengYen-Tang** [comment]
Hi @valeriob, 
Did you build it successfully.

**Comment by jbla77** [comment]
> You will probably need to change the Linker->Input settings as well. (I have no experience with GStreamer, so I can't comment further.)

Yes, this works for me. Just add following libs to OpenCVSharpExtern:

gstriff-1.0.lib
gstvideo-1.0.lib
gstbase-1.0.lib
gstreamer-1.0.lib
gstapp-1.0.lib
gobject-2.0.lib
glib-2.0.lib
gstadaptivedemux-1.0.lib
gstallocators-1.0.lib
gstbasecamerabinsrc-1.0.lib
gstcheck-1.0.lib
gstcodecparsers-1.0.lib
gstcontroller-1.0.lib
gstfft-1.0.lib
gstgl-1.0.lib
gstinsertbin-1.0.lib
gstisoff-1.0.lib
gstmpegts-1.0.lib
gstnet-1.0.lib
gstpbutils-1.0.lib
gstphotography-1.0.lib
gstplayer-1.0.lib
gstrtp-1.0.lib
gstrtsp-1.0.lib
gstrtspserver-1.0.lib

**Comment by valeriob** [comment]
Yes I was able to compile it, you need the minigw version and adding the .lib files above to the linker input.
