### ISSUE TITLE
Debugging in visual studio crashes when using submatrices

### ISSUE THREAD

**Issue by gravikovich** [shimat/opencvsharp#1105]
# Summary of your issue

When trying to debug a code which performs shallow copies of an image, the debugger crashes

# Environment

Windows 10, x64, VS 2019 Pro, .netcore 3.1, opencvsharp 4.5.0.20201013 

# What did you do when you faced the problem?

Tried to debug the following code

## Example code:

```
using OpenCvSharp;
using System;

namespace ConsoleApp3
{
    class Program
    {

        static Mat<byte> MakeSubmat(Mat<byte> im) => new Mat<byte>(im, OpenCvSharp.Range.All);


        static void Main(string[] args)
        {
            using var img1 = new Mat<byte>(100, 100);
            for (int i = 0; i < 10000; ++i)
            {
                using var img2 = MakeSubmat(img1);
                if (i % 100 == 0)
                {
                    Console.Write("X");
                }
            }
        }
    }
}
```

## Output:

When running the code without the debugger attached, all behaves as expected
When running with the debugger attached and breakpoint on the `using var img2` line, the process crashes (after continuing) with (native error evaluating ToString):

![image](https://user-images.githubusercontent.com/52130024/102226531-2bee2580-3ef1-11eb-8aac-d831e9f5d7db.png)

## What did you intend to be?

No crashes, debugger ignores disposed images (I guess this is the issue?)

**Comment by gravikovich** [comment]
I guess this is  due to the `ToString` implementation at https://github.com/shimat/opencvsharp/blob/09bbe6a0cf3b25fac7e44c43cbd0ce7dd3614124/src/OpenCvSharp/Modules/core/Mat/Mat.cs#L3749 which doesn't take into consideration a `Disposed` image.

**Comment by shimat** [comment]
Thank you!

**Comment by gravikovich** [comment]
Welcome, thank you!
