### ISSUE TITLE
Why is it generated OpenCvSharpExtern.dll The size of is 1.44 MB

### ISSUE THREAD

**Issue by WenYuanMo** [shimat/opencvsharp#1106]
# Summary of your issue

I make OpencvSharpExtern and generated OpenCvSharpExtern.dll , but the size of OpenCvSharpExtern.dll  is 1.44mb , i think that is error and i can not find why is it 1.44mb .

# Environment
i use vs2019 and opencv45 to make OpencvSharpExtern

# What did you do when you faced the problem?

Write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by hez2010** [comment]
OpenCvSharpExtern is only used for interop with OpenCV, it doesn't contain the entire OpenCV libraries.
