### ISSUE TITLE
Problems with .Net 5 on Ubuntu 20.04

### ISSUE THREAD

**Issue by guthom** [shimat/opencvsharp#1115]
Hello Everyone,
i tried to use OpenCVSharp with .Net5 on Ubuntu 20.04 but i ran in some trouble (Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies). I saw another [issue](https://github.com/shimat/opencvsharp/issues/1085) with 20.04 here on github but that did not help me. 
At this moment i'm not sure if the problems are related to my Ubuntu Installation or .Net 5 - maybe you could help me here.

Best Guthom

**Comment by hez2010** [comment]
You need to build native wrapper `OpenCvSharpExtern` manually. Please follow https://github.com/shimat/opencvsharp#ubuntu-1804-1

**Comment by guthom** [comment]
Hi hez, 
yeah you're right, worked like a charm after building everything from source - thank you very much. 

Best Guthom
