### ISSUE TITLE
Item0 Readonly

### ISSUE THREAD

**Issue by bobdavies2000** [shimat/opencvsharp#1121]
# Summary of your issue

I just tried the new 4.5.1 version of OpenCVSharp and found that all of my references to the Item0/1/2/3 were not compiling because these variable entries are now marked ReadOnly.  The example below compiles with the previous version of OpenCVSharp but fails with the 4.5.1 that was just posted.

# Environment

Latest Windows 10

# What did you do when you faced the problem?

I backed off the the October version of OpenCVSharp

## Example code:

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using cv = OpenCvSharp;

namespace itemBug
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            cv.Vec3f test;
            test.Item0 = 1;
        }
    }
}

## Output:

It won't compile...

## What did you intend to be?

It was previously working fine.

**Comment by shimat** [comment]
That's not a bug, but my intended modification(#1097), but I'm going to revert to the original behavior (#1123 ).
I will reconsider this in the future when "struct record" is adopted into the C# syntax.

**Comment by bobdavies2000** [comment]
Thanks for looking at this.  I have about a dozen places where I am updating or tallying counts in a Vec3f structure.  I could use a small array as an alternative but the values originate in a Vec3b or Vec3f.  It seemed natural to update a Vec3f since C++ Vec3f works that way but I can switch if needed.
