### ISSUE TITLE
cvHaarDetectObjects incorrect PInvoke signature

### ISSUE THREAD

**Issue by samueljfm** [shimat/opencvsharp#113]
There's a major bug in cvHaarDetectObjects causing it to stop working randomly. 
CvSize max_size parameter is missing in cvHaarDetectObjects function signature, so this parameter always contains random data from the call stack. When these width/height values of max_size are negative, the function stops detecting immediately.

**Comment by shimat** [comment]
I am sorry for so late reply. This bug is fixed.
https://github.com/shimat/opencvsharp/commit/b3bbc673e536e0b9fd7cfc07eb6278acc799cfa2
