### ISSUE TITLE
[Otsu] OpenCvSharp.OpenCVException:“Unknown/unsupported threshold type”

### ISSUE THREAD

**Issue by equiclouds** [shimat/opencvsharp#1147]
OpenCvSharp.OpenCVException:“Unknown/unsupported threshold type”

```csharp
             var color = Cv2.ImRead(path);
            var gray = new Mat();
            Cv2.CvtColor(color, gray, ColorConversionCodes.BGR2GRAY);
            var binary = new Mat();            
            Cv2.AdaptiveThreshold(gray, binary, 255, AdaptiveThresholdTypes.GaussianC, ThresholdTypes.Otsu, 15, -10);
            Cv2.ImShow("b", binary);
            Cv2.WaitKey(0);
            return 0;
```

**Comment by shimat** [comment]
> @ param thresholdType Thresholding type that must be either #THRESH_BINARY or #THRESH_BINARY_INV,

- https://github.com/opencv/opencv/blob/2f8c62999f8cd513120e28fc38cefffefe8b1567/modules/imgproc/include/opencv2/imgproc.hpp#L2943
- https://github.com/opencv/opencv/blob/fc1a15626226609babd128e043cf7c4e32f567ca/modules/imgproc/src/thresh.cpp#L1723
