### ISSUE TITLE
HoughLineP does not work ?

### ISSUE THREAD

**Issue by minhduc66532** [shimat/opencvsharp#1152]
# Summary of your issue

I'm trying to use HoughLineP for some line detection stuff. Detected lines should appear red on the image but for some reason, it don't 

## Example code:

```
// input MatType is CV_8U
var v_ = Cv2.HoughLinesP(input, 1, Cv2.PI / 180f, 50, 50, 10);
foreach(var _v in v_)
{
    Cv2.Line(input, _v.P1, _v.P2, new Scalar(0, 0, 255), 1);
}
```

## Output:

Input:
![image](https://user-images.githubusercontent.com/66398066/103600912-2063ac80-4f3b-11eb-835f-985c998a4d6b.png)
Expected (something like this):
![image](https://user-images.githubusercontent.com/66398066/103600967-3ffad500-4f3b-11eb-9504-4ee7580f10fa.png)
Reality:
![image](https://user-images.githubusercontent.com/66398066/103601033-6456b180-4f3b-11eb-8f7c-6e386bc5d997.png)

**Comment by shimat** [comment]
You should probably apply binarizing and dilating to the input image beforehand.

![image](https://user-images.githubusercontent.com/4434824/105616754-85b10c00-5e1c-11eb-97d7-7712b8113a9e.png)

```c#
using var src = new Mat("your_image.png", ImreadModes.Grayscale);

using var binary = new Mat();
Cv2.Threshold(src, binary, 0, 255, ThresholdTypes.Otsu);

var lines = Cv2.HoughLinesP(binary, 1, Cv2.PI / 180f, 50, 50, 10);

using var view = new Mat();
Cv2.CvtColor(src, view, ColorConversionCodes.GRAY2BGR);
foreach (var line in lines)
{
    Cv2.Line(view, line.P1, line.P2, Scalar.Red);
}

Window.ShowImages(new[] { src, binary, view}, new[]{"src", "binary", "lines"});
```

**Comment by minhduc66532** [comment]
@shimat Thank you for your answer
