### ISSUE TITLE
Opening and closing window with same title

### ISSUE THREAD

**Issue by mrspirytus** [shimat/opencvsharp#1159]
# Summary of your issue
It seems opening window with same title after closing previous, I do not get error but window is not visible.

# Environment
Windows 10, .Net 5, 

# What did you do when you faced the problem?
I do not have simple code. But the concept is simple. I have multiple remote robots that connect server. Each time robot looses connection it reconnects. Each time new connection is made, that connection is handled on separate thread.
For that reason on server I have
```
private ConcurrentDictionary<int, Window>  _cvWin;
```
So lets say robot with id 1 connects. It creates new window in _cvWin and displays images. 
```
                _cvWin.TryAdd(id, new Window(id.toString()));
```
That works on very first connection. Now robot 1 disconnects and that if 1 is removed from _cvWin
```
                if (_cvWin.TryRemove(id, out var window))
		{
                    Window.GetWindowByName(id);
                    window.Close();
                }
```
WITH OUT server restarting, robot one reconnects and follows same procedure as initially. It is not finding id in dictionary so it creates new Windows with same ID.

## What did you intend to be?
I do not get error. It is that new created windows are not shown. I do not see them on teak bar or when I try to switch between windows (Shift-Tab)

Am I missing something? Or is this a bug?

**Comment by shimat** [comment]
There was a bug in Window.Dispose (#1174) . What if you use Cv2.NamedWindow and Cv2.DestroyWindow instead?

```c#
private ConcurrentDictionary<int, object>  _cvWin;

...

Cv2.NamedWindow(id.ToString());
_cvWin.TryAdd(id, null);

...

if (_cvWin.TryRemove(id, out var _))
{
    Cv2.DestroyWindow(id.ToString());
}
```

**Comment by mrspirytus** [comment]
Awesome. That worked :)
