### ISSUE TITLE
[OpenCvSharp.Dnn.Net] Forward function overwrites data

### ISSUE THREAD

**Issue by andrei-shift** [shimat/opencvsharp#1162]
# Summary of your issue

When using the same model to predict different images in a sequential manner, the data gets overwritten each time
One needs to store the information of the outputed Mat to avoid this

# Environment

Windows 10 latest with Visual Studio 2019,  net472

# What did you do when you faced the problem?

I was using the same Cnn model to predict multiple images, one after another
I was storing the outputs in a List<Mat>

## Example code:

```c#
        private Net CNNModel = CvDnn.ReadNetFromTensorflow(ModelPath);

        public List<Mat> ComputeCnnHashWithTensorFlowModelRotationFloat(List<Bitmap> images)
        {
            var result = new List<Mat>();

            foreach (var bmp in images)
            {
                var mat = OpenCvSharp.Extensions.BitmapConverter.ToMat(bmp);
                var lastLayer = ComputeCnnHashWithTensorFlowModel(mat);
                result.Add(lastLayer);
            }

            return result;
        }

        private Mat ComputeCnnHashWithTensorFlowModel(Mat readImagesFromOcv)
        {
            var imgBlobs = CvDnn.BlobFromImage(readImagesFromOcv, scaleFactor: 1 / ScaleFactor, mean: MeanScalar, size: Size
                , swapRB: true, crop: false);
            return ForwardNeuralNetwork(imgBlobs);
        }

        private Mat ForwardNeuralNetwork(Mat input)
        {
            Mat output;
            CNNModel.SetInput(input);
            output = CNNModel.Forward();
            return output;
        }
```

## Output:

![image](https://user-images.githubusercontent.com/44770377/104476918-083a0000-55c1-11eb-8c3c-f4407ab5ff3a.png)

![image](https://user-images.githubusercontent.com/44770377/104476771-e5a7e700-55c0-11eb-93a3-d127c0631fc5.png)

## What did you intend to be?

I intended to have different data for each image

**Comment by RaimondB** [comment]
You can use BlobFromImages (plural) to proces multiple images in a single pass. This is also more efficient than looping yourself because it can use optimized cpu instructions. The data structure you get back for Forward will have an additional demension, being the index of the image you passed in.

**Comment by RaimondB** [comment]
Also, you can simply copy the Mat coming out. I have a similar application that processes images from multiple camera source in parallel. I read out the values I need from the Mat into a different strong typed data structure. Reusing Mat is better for performance since it saves on memory allocations.
