### ISSUE TITLE
uwp rtsp opencv videoCapture not open

### ISSUE THREAD

**Issue by sdrc2806** [shimat/opencvsharp#1171]
I want to stream rtsp from uwp to opencv
rtsp url works fine in not uwp app.
But in uwp [open("rtsp") == false].

and The webcam works fine. [VideoCapture(0)].
I have tried various tests, but I don't know why.

Help

code(uwp)
var cap = new VideoCapture();
var bOpen = cap.Open(@"rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov");
// bOpen == false
var output = new Mat();
var bRead = cap.Read(output );
and appxmanifest

<Capabilities>
    <Capability Name="internetClient" />
    <Capability Name="privateNetworkClientServer"/>
    <uap3:Capability Name="backgroundMediaPlayback"/>
    <uap:Capability Name="videosLibrary"/>
    <Capability Name="internetClientServer"/>
    <uap:Capability Name="enterpriseAuthentication"/>
    <DeviceCapability Name="webcam"/>        
</Capabilities>

**Comment by badpaybad** [comment]
I got the same problem, c# code.

 `
                          var capture = new VideoCapture();
                          capture.Set(VideoCaptureProperties.BufferSize, 3);            
                          capture.Open(streamRtspUrl,` VideoCaptureAPIs.ANY);
`
[ERROR:0] global D:\a\opencv_files\opencv_files\opencv\modules\videoio\src\cap.cpp (161) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised unknown C++ exception!

I google but no answer worked for this error.
