### ISSUE TITLE
std::vector<KeyPoint>の参照渡し問題

### ISSUE THREAD

**Issue by yukoba** [shimat/opencvsharp#118]
すいません、話がややこしいので、日本語で失礼します。

現状 3.0 ブランチ の 2D feature がバグってます。
cv::Feature2D::compute() は std::vector<KeyPoint> &keypoints で渡すのですが、
このvectorを参照渡しで渡す所が大事です。

現状の 3.0 ブランチ、キーポイント数が少ない時は正常に動作するのですが、
多い時に、参照渡しをしてないことが問題となって、メモリが破壊されます。

https://github.com/shimat/opencvsharp/blob/3.0/src/OpenCvSharp/modules/features2d/Feature2D.cs#L106
var keypoints = new VectorOfKeyPoint(10000);
のように、あらかじめ大きな数字を入れておくと正常に動作します。

少し格闘してみたのですが、解決策が良く分からなく、
vector の参照渡し、どのように解決すれば良いのでしょうか？

**Comment by shimat** [comment]
今のFeature2D実装で`Detect`と`Compute`を取り違えているというか変になっている感じでして、どのようなコードでそれが再現するのか確認させて頂けますか。

Detect -> Computeの流れで使うらしいので、ついさっきpushした版で動くコードですが、このように使ったということでよろしいでしょうか。
```c#
Mat img = new Mat("hoge.png", LoadMode.GrayScale);
KAZE kaze = KAZE.Create();

KeyPoint[] keyPoints = kaze.Detect(img);

Mat descriptors = new Mat();
kaze.Compute(img, ref keyPoints, descriptors);
```

**Comment by yukoba** [comment]
ごめんなさい！！

僕が Visual Studio 2015 でビルドしていて、元々の shimat さんのが Visual Studio 2013 でビルドしていて、その2つが混在すると、std::vector がおかしくなるという不具合でした。僕の勘違いでした。Visual Studio 2013 も入れておかないと駄目ですね。お騒がせしました。

残りの特徴点もラッパー実装して頂いて、ありがとうございます。
