### ISSUE TITLE
accessviolation in Or(), Mul(), and FindContours(), and maybe others.

### ISSUE THREAD

**Issue by rblenis** [shimat/opencvsharp#119]
The functions Or(), Mul(), and FindContours() need to use GC.KeepAlive() to prevent garbage collection of the managed objects after their unmanaged pointer is retrieved for passing to the opencv dll, as is done in And().  There may be other functions that need this applied as well, but I haven't investigated further, and this was in version 2.4.10-20150820

**Comment by rblenis** [comment]
I think these functions also suffer the same problem: Cv.ProjectPoints2, Cv.FindHomography, Cv.PolyLine, Cv.Circle, Cv.CloneImage, Cv.Not, Cv.CvtColor, Cv.Mul, Cv.Split

**Comment by shimat** [comment]
Yes, This is a long-standing issue. 
I added GC.KeepAlive to most Cv.*** functions: https://github.com/shimat/opencvsharp/commit/e594e7c31f018c9d43bb4286c33f6fd1d2a9c9ec

**Comment by rblenis** [comment]
Thanks!
