### ISSUE TITLE
There is no such method

### ISSUE THREAD

**Issue by bbhxwl** [shimat/opencvsharp#1192]
python 
sift=cv2.xfeatures2d.SIFT_create()

**Comment by shimat** [comment]
http://shimat.github.io/opencvsharp/api/OpenCvSharp.Features2D.SIFT.html

```c#
using var sift = OpenCvSharp.SIFT.Create();
```

Since the SIFT patent has expired, the SIFT module has been moved from xfeatures2d to features2d.
