### ISSUE TITLE
Building 4.5.1 OpenCvSharp for Raspberry Pi OS

### ISSUE THREAD

**Issue by drronnie85** [shimat/opencvsharp#1193]
Hi guys. I'm noob in linux. 
How I can build last version libOpenCvSharpExtern.so for Raspberry Pi OS?
The best is building in docker hosted on debian x64, because building openCv on Pi take >5 hours.
I found several Dockerfile's but all have different "-D" options for buildin openCv, I wan't just build my dotnetcore app on win and run it on Pi.
Also building NUGET package with arm runtimes for raspberry pi os in CI of this project will be great!
Thank you.

**Comment by lmoe** [comment]
Hey, I'm currently working on a 4.5.1 version for a raspberry pi. I ran the compilation over night, so I can't say how long it took.
If all is successful I will provide a link you can download. I haven't tested it yet.

If you want to do it for yourself, I think this tutorial could help:
https://nicruo.github.io/2020/02/12/opencvsharp-on-raspberry-pi-4.html

The easiest way to compile it would be on a Raspberry Pi or by using QEmu and emulating a Raspberry Pi. As the Raspberry Pi is ARM based, a x64 docker image will not really help you.

But as you only need to compile it once, it's only once a burden.

Maybe you want to compile the OpenCv libs statically, which you can with '-D BUILD_SHARED_LIBS=OFF'

My build args are:
```-D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules \
        -D ENABLE_NEON=ON \
        -D ENABLE_VFPV3=ON \
        -D WITH_OPENMP=ON \
        -D BUILD_TIFF=ON \
        -D WITH_FFMPEG=ON \
        -D WITH_GSTREAMER=OFF \
        -D WITH_TBB=ON \
        -D BUILD_TBB=ON \
        -D BUILD_TESTS=OFF \
        -D WITH_EIGEN=OFF \
        -D WITH_V4L=ON \
        -D WITH_LIBV4L=ON \
        -D WITH_VTK=OFF \
        -D OPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic \
        -D OPENCV_ENABLE_NONFREE=ON \
        -D INSTALL_C_EXAMPLES=OFF \
        -D INSTALL_PYTHON_EXAMPLES=OFF \
        -D BUILD_NEW_PYTHON_SUPPORT=OFF \
        -D BUILD_opencv_python3=FALSE \
        -D OPENCV_GENERATE_PKGCONFIG=ON \
        -D BUILD_EXAMPLES=OFF \
	-D BUILD_SHARED_LIBS=OFF -D WITH_GTK=OFF -D WITH_WIN32UI=OFF ..
```

as I don't need GUIs and python and such, Ive disabled all of it.

**Comment by drronnie85** [comment]
@lmoe thank you for your answer. Can you post step by step manual of building?
After connecting opencvsharp to my solution I stuck with building opencvsharp for raspberry almost week.

**Comment by lmoe** [comment]
Hey! :)

The link I had posted is basically a step by step manual. It guides you through the whole process of building OpenCV and also how to compile the OpenCVSharpExtern lib you require. 

My initial tests run fine by the way. It seems like the solution is correct. I just require some more time.

**Comment by drronnie85** [comment]
@lmoe you are right))) Sorry. I built libOpenCvSharpExtern.so by manual. After several attempts process finished without errors.
But when I try to start my dotnet application by command dotnet Sample.dll I see exception
`Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
`
Maybe I should set location of lib?
It exists in /home/pi/opencv/lib/libOpenCvSharpExtern.so
/home/pi/opencvsharp/src/build/OpenCvSharpExtern/libOpenCvSharpExtern.so
Thank you.

**Comment by drronnie85** [comment]
I should copy lib to folder with my project.
I think I should make pause)))
Thank you for your help

**Comment by lmoe** [comment]
Glad it worked! :)

**Comment by Luk164** [comment]
@lmoe I am having a simmilar problem to @drronnie85. I want to use OpenCvSharp in a project that is supposed to run on rpi, but including the arm runtime provided leads to `Unable to load shared library 'OpenCvSharpExtern'` I tried to build openCvSharp on my RPI but it failed with `opencv2/img_hash.hpp: No such file or directory` and I am having trouble fixing it. Any tips?
