### ISSUE TITLE
npoints2 >= 0 || npoints3 >= 0 exception Cv2.FitLine();

### ISSUE THREAD

**Issue by minhduc66532** [shimat/opencvsharp#1194]
# Summary of your issue

Weird exception throw when trying to use FitLine function

# Environment

Window 10

## Example code:

```
// v MatType is CV_8U
Mat v_ = v.EmptyClone();
Cv2.FitLine(v, v_, DistanceTypes.L2, 0, 0.01, 0.01);
```

## Output:

![image](https://user-images.githubusercontent.com/66398066/106386253-b2f64f00-6406-11eb-94d5-2a143c9d28fd.png)

**Comment by shimat** [comment]
https://github.com/opencv/opencv/blob/fc1a15626226609babd128e043cf7c4e32f567ca/modules/imgproc/src/linefit.cpp#L618

Could you tell us the type and contents of `v`?
In general, input Mat type should be CV_32SC2 or CV_32FC2 or CV_32SC3 or CV_32FC3.

```c#
var contour = new[]
{
    new Point(0, 0),
    new Point(5, 5),
    new Point(10, 10),
};
using var src = new Mat(contour.Length, 1, CV_32SC2, contour);
//using var src = new Mat(contour.Length, 2, CV_32SC1, contour); // also OK
using var dst = new Mat();
Cv2.FitLine(src, dst, DistanceTypes.L2, 0, 0.01, 0.01);

// dst.Size() == Size(1,4),  dst.Type() == MatType.CV_32FC1
float vx = dst.Get<float>(0);  // sqrt(2)/2
float vy = dst.Get<float>(1);  // sqrt(2)/2
float x0 = dst.Get<float>(2);  // 5
float y0 = dst.Get<float>(3);  // 5
```

**Comment by minhduc66532** [comment]
The v MatType is CV_8U, i've changed the code to this:
```
v.ConvertTo(v, MatType.CV_32SC2);
Mat v_ = new();
Cv2.FitLine(v, v_, DistanceTypes.L2, 0, 0.01, 0.01);
```
But the error still there, any ideas ?
v contents:
![image](https://user-images.githubusercontent.com/66398066/106465082-139b8f80-64cc-11eb-8cfd-2df265643ee5.png)

**Comment by shimat** [comment]
This is not a question for the wrapper, but for OpenCV, so I close this issue. I am only responding to issues related to bugs.

You should enter coordinates in fitline, not pixel values. Please see the original OpenCV's documentations. https://docs.opencv.org/4.5.1/d3/dc0/group__imgproc__shape.html#gaf849da1fdafa67ee84b1e9a23b93f91f
```c#
// remember disposing Mat instances by "using" 
using var src = new Mat("your_image.png");
using var gray = new Mat();
using var binary = new Mat();

Cv2.CvtColor(src, gray, ColorConversionCodes.BGR2GRAY);
Cv2.Threshold(gray, binary ,0, 255, ThresholdTypes.Otsu);

var pixels = new List<Point>();
var indexer = binary.GetGenericIndexer<byte>();
int h = src.Rows;
int w = src.Cols;
for (int y = 0; y < h; y++)
{
    for (int x = 0; x < w; x++)
    {
        var value = indexer[y, x];
        if (value != 0) // white
        {
            pixels.Add(new Point(x, y));
        }
    }
}

var line = Cv2.FitLine(pixels, DistanceTypes.L2, 0, 0.01, 0.01);
...
```

**Comment by minhduc66532** [comment]
Ahh ok, thank you for your answer
