### ISSUE TITLE
Unable to use OpenCvSharp on Arch Linux

### ISSUE THREAD

**Issue by martmists-gh** [shimat/opencvsharp#1199]
# Summary of your issue

OpenCvSharpExtern is not loaded by my application

# Environment

Arch Linux x64

# What did you do when you faced the problem?

I tried to run https://github.com/vignette-project/vignette

## Output:

Output from Rider, Debug | x64, Vignette.Application.Tests with LD_DEBUG=libs:
https://pastebin.com/uEvEwB8M

**Comment by sr229** [comment]
For additional context, we only supplied with the Ubuntu Runtime. According to the logs looks like the LD_LIBRARY search paths are wrong.
