### ISSUE TITLE
OpenCvSharp on Ubuntu or Raspberry Pi

### ISSUE THREAD

**Issue by geertendoornenbal** [shimat/opencvsharp#120]
Hi,

I'm trying to get OpenCvSharp working on Ubuntu or Raspberry Pi. 
I've got OpenCvSharp compiled, but when I try to compile it, it gives an error it can't find the opencv_core2410.
However the library on Ubuntu/RPi is called libopencv_core.so.2.4.10. 

Can you show a tutorial or a sample project where OpenCvSharp is working on Ubuntu?

Thanks.

**Comment by shimat** [comment]
This page may help you: http://www.mono-project.com/docs/advanced/pinvoke/dllmap/
Please try to put `OpenCvSharp.dll.config`.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <dllmap os="!windows" dll="opencv_core2410" target="libopencv_core.so.2.4.10" />
  <dllmap os="!windows" dll="opencv_imgproc2410" target="libopencv_imgproc.so.2.4.10" />
  ...
</configuration>
```

**Comment by geertendoornenbal** [comment]
Thanks, I will give that a try!

**Comment by inzi** [comment]
I know this is a very old question - is this still "the way?"

Or - is there a different approach currently?
