### ISSUE TITLE
LGPL license in "Blob" source included when top level license advertised Apache

### ISSUE THREAD

**Issue by milijan** [shimat/opencvsharp#1200]
# Summary of your issue

# Environment

Write your environment.

# What did you do when you faced the problem?

Write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
Thank you. I will remove Blob in the next version.

**Comment by bbn-bert** [comment]
@shimat besides the licensing differences, was there a reason the Blob namespace/project was completely removed and not moved? Was the project moved somewhere else not captured by the merge request and file change list? This created a breaking change that prevents upgrading to the latest version when using the OpenCVSharp.Blob namespace.
