### ISSUE TITLE
How to use FindContours and DrawContours in opencvsharp?

### ISSUE THREAD

**Issue by lunkyguy** [shimat/opencvsharp#121]

**Comment by VahidN** [comment]
Refer to [this sample](https://github.com/VahidN/OpenCVSharp-Samples/tree/master/OpenCVSharpSample12).

**Comment by lunkyguy** [comment]
Thank you! So how can I calculate the area and length of the contour?

**Comment by VahidN** [comment]
There's a `boundingRectArea` calculation In [bar code reader sample](https://github.com/VahidN/OpenCVSharp-Samples/tree/master/OpenCVSharpSample19).

**Comment by lunkyguy** [comment]
Point[][] contours; //vector<vector<Point>> contours;
 HiearchyIndex[] hierarchyIndexes; //vector<Vec4i> hierarchy;
There is a simple spelling mistake,you should replace HiearchyIndex with HierarchyIndex！
