### ISSUE TITLE
Cv2.Integral not working as expected

### ISSUE THREAD

**Issue by BMZE** [shimat/opencvsharp#1218]
# Summary of your issue
When using Cv2.Integral, the bottom right pixel of the mat should be the sum of all the pixels in the mat. However, the output is not the sum of all the pixels.

# Environment

VS2019
Windows 10

# What did you do when you faced the problem?

I've tried multiple ways of doing this, different mat types and the other methods of Cv2.Integral, but none are giving the expected output

## Example code:

```
using Mat mat = Mat.Ones(3, 3, MatType.CV_32SC1); //fill mat with ones
using Mat integralMat = new Mat();

Cv2.Integral(mat, integralMat); //get integral mat 

int sumIntegral = integralMat.At<int>(3, 3); //bottom right pixel
int sumCv2 = (int)Cv2.Sum(mat); 
```

## Output:

```
sumIntegral = 0

sumCv2 = 9
```

## What did you intend to be?

Both sumCv2 and sumIntegral should have a value of 9, instead sumIntegral is 0, and if you print out the values from integralMat all of them are 0

**Comment by shimat** [comment]
According to the following document, the type of `mat` should be 8-bit or floating-point (32f or 64f). In my environment, an error occurred when I input 32SC1 mat into the integral.
https://docs.opencv.org/3.4/d7/d1b/group__imgproc__misc.html#ga97b87bec26908237e8ba0f6e96d23e28

```c#
using var ones = Mat.Ones(3, 3, MatType.CV_8UC1);
using var sum = new Mat();

Cv2.Integral(ones, sum); 

Assert.Equal(9, sum.At<byte>(3, 3));  // OK
Assert.Equal(9, (int)Cv2.Sum(ones));
```

**Comment by BMZE** [comment]
Thanks for the quick response! I had completely misread that, 32f worked perfectly for me.
