### ISSUE TITLE
Cv2.PutText draw Chinese text  error code

### ISSUE THREAD

**Issue by chccc1994** [shimat/opencvsharp#1222]
How to draw Chinese text on the image using `Cv2.PutText`

**Comment by lwqwag** [comment]
Puttext's param in Opencv is required ascii.This is not about opencvsharp.You can draw text by using System.Drawing.doll

**Comment by lwqwag** [comment]
#695 opencv/opencv#14579

**Comment by chccc5** [comment]
What's the solution？
