### ISSUE TITLE
OpenCvSharp GPU problem

### ISSUE THREAD

**Issue by arslanekhan** [shimat/opencvsharp#123]
I have installed OpencvSharp 2.4 using Nuget Package manager in Microsoft Visual Studio 2013.

When i run this command 
int count = Cv2Gpu.GetCudaEnabledDeviceCount();

it always returns 0. on the other side i tried with another library named cudafy but that one gives me the count 1. but Opencvsharp always returns me count 0. 

Please help me out.

**Comment by arslanekhan** [comment]
I have resolved this problem. 

Build the opencv_Gpu and opencv_core dlls again. 

Make the source code of opencv using Cmake while selecting "with Cuda" option. 

Open the opencv solution then and just build opencv_core first and then opencv_gpu.  
After building get the new dlls and replace them in opencvsharp package. 

Now build your solution again and now it will copy the new dlls to the project build folder. Now it will detect the Cuda device.

I am using Nvidia GPU.

**Comment by died** [comment]
as i know, you need build(cmake) opencv with cuda enable option on your environment then replace it, and hope it work :)
