### ISSUE TITLE
[Question] How to transform a mat into a mat with single row or column

### ISSUE THREAD

**Issue by themronion** [shimat/opencvsharp#1238]
Hey, @shimat. amazing work and library. I am trying currently to implement some deblurring mechanisms and currenlty working on this formula - 
![image](https://user-images.githubusercontent.com/52563426/111903412-dc1c7e80-8a4a-11eb-87e2-9ce8b21f35aa.png)
where B+ is the pseudo-inverse matrix of a blurred image, B - our image, v - any vector, and g - is a single vector composed of all the columns of B. I am struggling to get the g vector, didn't find how to do it in C# on the web. Can u give me a small tip? Thanks in advance!

**Comment by shimat** [comment]
> How to transform a mat into a mat with single row or column

Sorry but I don't understand what you specifically want to do, but Mat.reshape will help you with the question of the issue title.

```c#
using var src = new Mat(20, 20, MatType.CV_8UC1);
using var dst = src.Reshape(0, 1);

Console.WriteLine("Rows={0}, Cols={1}", dst.Rows, dst.Cols); // Rows=1, Cols=400
```

**Comment by themronion** [comment]
Yeap. i guess thats exactly what i need, thanks. So simple though)
