### ISSUE TITLE
OpenCVSharp overwrites variable

### ISSUE THREAD

**Issue by maickdanckwardt** [shimat/opencvsharp#124]
Hi we just have some trouble with the function

```cs
Cv2.MinMaxIdx(InputArray src, out double minVal, out double maxVal, out int minIdx, out int maxIdx, InputArray mask = null)
```

in OpenCvSharp Version 2.x and 3 loaded via NuGet.

The variable declared just before maxIdx is reset by the function MinMaxIdx.

In the following example the variable test is valid until we call the function MinMaxIdx and is 0 after the function call.

```cs
private void OpenCVError()
    {
        var mat = new Mat(5, 1, MatType.CV_32FC1);
        var mat2 = new MatOfFloat(mat);
        var indexer = mat2.GetIndexer();
        indexer[0, 0] = 2f;
        indexer[1, 0] = 1f;
        indexer[2, 0] = 3f;
        indexer[3, 0] = 4f;
        indexer[4, 0] = 5f;
        double maxValue, minValue;
        var test = 10;
        int maxIdx, minIdx;
        Console.WriteLine(test);
        Cv2.MinMaxIdx(mat, out minValue, out maxValue, out minIdx, out maxIdx);
        Console.WriteLine(test);
    }
```

Do you have any ideas?

**Comment by fdncred** [comment]
@maickdanckwardt I don't represent shimat or OpenCvSharp but I just tested this exact code and did not experience your problem.  The test variable was 10 before and after MinMaxIdx().  It sounds like you may have some type of memory issue in your larger program.

**Comment by maickdanckwardt** [comment]
@fdncred we still can reproduce the reported error. We are just using this small example in a fresh project + OpenCVSharp from NuGet.
While checking this minimal example on a different workstation we found out that the error only occurs in x86 mode but not in x64.
Can you perhaps check if this is true for you?

**Comment by shimat** [comment]
Thank you for your report :+1:  @maickdanckwardt @fdncred 

This issue is a bottomless mystery... :tired_face:  I could reproduce the problem.
When I ran the program with debug mode (F5), the problem occurred. But when I ran the program without debug mode (CTRL+F5), it worked successfully.

**Comment by fdncred** [comment]
@maickdanckwardt @shimat Agreed.  Strange problem.  I was able to get around it in debug x86 mode by declaring a new object right after the int.  Not sure what is happening here in Debug x86 mode.
```chsharp
private void OpenCVError()
{
    var mat = new Mat(5, 1, MatType.CV_32FC1);
    var mat2 = new MatOfFloat(mat);
    var indexer = mat2.GetIndexer();
    indexer[0, 0] = 2f;
    indexer[1, 0] = 1f;
    indexer[2, 0] = 3f;
    indexer[3, 0] = 4f;
    indexer[4, 0] = 5f;
    double maxValue, minValue;
    var test = 10;
    object locker = new object();
    int maxIdx, minIdx;
    Console.WriteLine(test);
    Cv2.MinMaxIdx(mat, out minValue, out maxValue, out minIdx, out maxIdx);
    Console.WriteLine(test);
}	
```
You can also avoid the problem by making 'test' a class member variable or using x64.

**Comment by maickdanckwardt** [comment]
@shimat @fdncred when we declare our test variable at a different scope or declare a different variable in between our test variable does not get influenced by the function call - but obviously the variable that is now declared right before the out parameter gets overwritten.

Thats why we think that the underlying openCv function expects an out variable (minIdx + maxIdx) with type long but the wrapper function signature hands over an int. 

Is there the chance that the variable hand over between c# and c++ is kind of 

x86 : int (32 bit) <=> long (64 bit) - bad overrides other variables
x64 : int (64 bit) <=> long (64 bit) - everything is ok

By the way we tested debug and release compiled application within the IDE and external from cmd shell and in all x86 cases we got test == 0

**Comment by shimat** [comment]
I found the cause of the issue. The type declaration of `minIdx` and `maxIdx` should be not `out int` but `out int[]`. 
`cv::minMaxIdx` returns array of result indices. 

http://docs.opencv.org/modules/core/doc/operations_on_arrays.html
> pointer to the returned minimum location (in nD case); NULL is used if not required; Otherwise, it must point to an array of src.dims elements, the coordinates of the minimum element in each dimension are stored there sequentially.
