### ISSUE TITLE
[Question] DivSpectrums?

### ISSUE THREAD

**Issue by themronion** [shimat/opencvsharp#1240]
Hey, @shimat. Me again. Is it possible somehow to get this method working with your package? https://github.com/opencv/opencv/blob/94f00cf09694c38407cce23ed9fea288ab622b0f/modules/imgproc/src/phasecorr.cpp#L161
Or it requires to make a new build of opencv with this method included?

**Comment by shimat** [comment]
`divSpectrums` is an internal function of OpenCV and cannot be called from outside.

> Or it requires to make a new build of opencv with this method included?

Yes.

**Comment by themronion** [comment]
Hey, @shimat  - https://github.com/opencv/opencv/issues/19767. The proposed change has been merged in opencv. Let me know when an update to your lib is planning
