### ISSUE TITLE
Image Watch for VS debugging

### ISSUE THREAD

**Issue by Cunk** [shimat/opencvsharp#125]
There's a VS add-in made available by Microsoft called [Image Watch] (https://visualstudiogallery.msdn.microsoft.com/e682d542-7ef3-402c-b857-bbfba714f78d) that looks to be very useful for debugging OpenCV applications.  Unsurprisingly it doesn't appear to work with  OpenCvSharp (nor probably any of the other OpenCV .net wrappers).  Perhaps there's a trick to get this working or maybe there's another tool that will provide similar capabilities (watching image data while debugging a program) that works with OpenCvSharp?

**Comment by shimat** [comment]
Please consider using the debugger visualizers.
https://github.com/shimat/opencvsharp/wiki/Debugger-Visualizer

**Comment by Cunk** [comment]
Oh hey somehow I missed that.  Thanks!
