### ISSUE TITLE
What code should I use instead of Blob in OpenCvSharp 4.5.2 and later?

### ISSUE THREAD

**Issue by mirrdy** [shimat/opencvsharp#1252]
# Summary of your issue

# Environment

Write your environment.

# What did you do when you faced the problem?

Should I re-implement the codes for Blob myself? Or can I replace it with something that already exists? If there is something to replace, what is that?
## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by mirrdy** [comment]
Should I re-implement the codes for Blob myself? Or can I replace it with something that already exists? If there is something to replace, what is this?

**Comment by shimat** [comment]
There are several methods to get connected components.
- Cv2.ConnectedComponents
- Cv2.ConnectedComponentsWithStats
- Cv2.ConnectedComponentsWithStatsWithAlgorithm
- Cv2.ConnectedComponentsEx

The following links will help you understand how to use these methods.
- https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga107a78bf7cd25dec05fb4dfc5c9e765f
- https://github.com/shimat/opencvsharp/blob/ea7c67ff0df7b0bc003b46b245a413c7830ffb16/src/OpenCvSharp/Cv2/Cv2_imgproc.cs#L2862
- https://github.com/shimat/opencvsharp/blob/ea7c67ff0df7b0bc003b46b245a413c7830ffb16/test/OpenCvSharp.Tests/imgproc/ConnectedComponentsTest.cs

**Comment by mirrdy** [comment]
Thank you so much, I love you XD
