### ISSUE TITLE
Calibrating camera using chessboard pattern

### ISSUE THREAD

**Issue by Yddeon** [shimat/opencvsharp#1254]
# Summary of your issue

Hi! First of all sorry if this is not the proper question to ask through an issue. Let me know if there was a better place to ask this and sorry for any inconvenience this might cause!

I've been trying to archieve camera calibration using a chessboard pattern. I've seen you have some samples on how to perform calibrations in older versions of the wrapper but I cannot find any updated version of an exaple to use as reference (it should be similar but I haven't managed to make it work).

Is there any working code example avaliable?

# Environment

Right now I'm using latest NuGet release (4.5.2.20210404) for .NET framework 4.6.1

**Comment by shimat** [comment]
Some test code may help you. https://github.com/shimat/opencvsharp/blob/ac7299590071e71a5c3bb040024fee657e2105db/test/OpenCvSharp.Tests/calib3d/Calib3dTest.cs#L141
