### ISSUE TITLE
OpenCVSharp AccessViolationException in BackgroundSubtractorMOG2

### ISSUE THREAD

**Issue by ayb4btu** [shimat/opencvsharp#126]
I'm trying to use the OpenCV class BackgroundSubtractorMOG2 in a C# project via OpenCVSharp (OpenCvSharp3-AnyCPU Version 3.0.0.20150823 running in Visual Studio 2015 and installed via NuGet). However I'm running into an AccessViolationException which gives:

*An unhandled exception of type 'System.AccessViolationException' occurred in OpenCvSharp.dll Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.*

Here is the (stripped down) code that I'm using:

    using OpenCvSharp;    

    public class ImageBackgroundSubtraction
    {
        private BackgroundSubtractor mog;
        private Mat mask;
        private Mat colorImage;

        public ImageBackgroundSubtraction()
        {
            this.mog = BackgroundSubtractorMOG2.Create();
            this.mask = new Mat();
            this.colorImage = Cv2.ImRead(@"C:\Some\directory\path\testImage.tiff");
        }

        public void AddFrame()
        {
            // This line causes the AccessViolationException
            this.mog.Run(colorImage, this.mask, 0.01);
        }
    }

I'm not sure if my implementation is incorrect, or something else is failing, such as OpenCVSharp itself. If or when this works, do I also need to call

    mog.Dispose();

when I'm finished using my ImageBackgroundSubtraction class? Or does the Garbage Collector clean this up?

**Comment by shimat** [comment]
Thank you for your report. Sorry for the late reply.
There are bugs in BackgroundSubtractor*. Wrong object pointer is passed to the native function.
https://github.com/shimat/opencvsharp/commit/763c9bd0d59760684ee5367a18faef1c9080e100

**Comment by shimat** [comment]
It is recommended to implement finalization function of your class. The GC may not work well because the .NET runtime does not have OpenCV's native memory usage information.

This page is useful for implementing finalization process:  https://msdn.microsoft.com/en-US/library/b1yfkh5e(v=vs.100).aspx

**Comment by shimat** [comment]
The new nuget package was released :muscle:
