### ISSUE TITLE
OpenCvSharp4.runtime.linux-arm doesn't work on raspberry pi 4

### ISSUE THREAD

**Issue by dseferlis** [shimat/opencvsharp#1263]
# Summary of issue
Hello everyone.
First of all thank you for your effort to make this lib.
Trying to use opencvsharp on an image capture app on a raspberry pi. Installed the OpenCvSharp4.runtime.linux-arm nuget package thinking of this is what I need.
Although I get the error bellow.
Is there something I can do to make it work?

# Environment
Raspberry pi model 4 4GB
OS: Raspbian 10 buster (armv7l)
Project framework: .net 5

## Example code:

```
using OpenCvSharp;

namespace OpencvTest.Console
{
    class Program
    {
        static void Main(string[] args) {
            var capture = new VideoCapture(0);
            var window = new Window("Test");
            var image = new Mat();
            while (true) {
                capture.Read(image);
                if (image.Empty()) {
                    break;
                }
                
                window.ShowImage(image);
                if (Cv2.WaitKey(1) == 113) {
                    break;
                }
            }
            System.Console.WriteLine("Hello World!");
        }
    }
}

```

## Output:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: wrong ELF class: ELFCLASS64
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.ExceptionHandler.RegisterExceptionCallback()
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.videoio_VideoCapture_new3(Int32 device, Int32 apiPreference, IntPtr& returnValue)
   at OpenCvSharp.VideoCapture..ctor(Int32 index, VideoCaptureAPIs apiPreference)
   at OpencvTest.Console.Program.Main(String[] args)
```

**Comment by AvenSun** [comment]
you should check dependency of native library as follows
**`ldd ./lib/OpenCvSharpExtern.so`**  
Do use full path of library, find all marked "not found" then install .
but the best way is building OpenCvSharpExtern library on Pi 4.

**Comment by dseferlis** [comment]
Thanks for reply.
Project build produces a libOpenCvSharpExtern.so. Running ldd libOpenCvSharpExtern.so (even with full path) i get the error "not a dynamic executable". Am I missing something?

**Comment by AvenSun** [comment]
@dseferlis 

>  EDIT: using file libOpenCvSharpExtern.so i get:
> libOpenCvSharpExtern.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=2feb0d05276a0f30a7e6c2669610ca40685c2dca, not stripped
> 

It seems that libOpenCvSharpExtern.so you're referred is not a valid  library for arm (Pi 4)
you'd better build it on your own

**Comment by AvenSun** [comment]
@bitdeli-chef 

> EDIT: using file libOpenCvSharpExtern.so i get:
> libOpenCvSharpExtern.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=2feb0d05276a0f30a7e6c2669610ca40685c2dca, not stripped

It seems that libOpenCvSharpExtern.so you're referred is not a valid library for current OS .
Is your OS is 32bit ?

**Comment by dseferlis** [comment]
> Is your OS 32bit ?
Yes. It's the default for raspberry i think. At least in the official imager.

**Comment by AvenSun** [comment]
that's the problem
32-bit OS can not invoke 64-bit library .

**Comment by dseferlis** [comment]
So I should build library on pi i guess. 
Is there plans to release lib for arm32?

**Comment by AvenSun** [comment]
If you would like to use OpenCvSharp on arm32 
yes, you have to build on your own.
actually Pi 4 is [64 bit SOC](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/specifications/), you can also try 64-bit OS.

**Comment by dseferlis** [comment]
Thank you!!! I hadn't realize Pi can run 64bit OS...

**Comment by dseferlis** [comment]
Although what I don't get is that building project for linux-arm, which produces 32bit executable, libOpenCvSharpExtern.so is included in output directory, but when building for linux-arm64, which produces 64bit executable, libOpenCvSharpExtern.so is not included.

**Comment by AvenSun** [comment]
I can build it successfully on Jetson family (arm64).
you should check the  log

**Comment by jblam** [comment]
> libOpenCvSharpExtern.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=2feb0d05276a0f30a7e6c2669610ca40685c2dca, not stripped

> It seems that libOpenCvSharpExtern.so (64 bit) you're referred is not a valid library for current OS .

I'd just note that the latest version of the `OpenCvSharp4.runtime.linux-arm` [nuget package](https://www.nuget.org/packages/OpenCvSharp4.runtime.linux-arm/) (currently 4.5.2.20210507) includes the _x84-64_ binary, not an _ARM_ binary. So the package is guaranteed never to work, as I understand it.

I'd suggest unlisting that package, to avoid having other people encounter this problem and leave comments on this issue :)

**Comment by GitNao** [comment]
![image](https://user-images.githubusercontent.com/31090571/125149731-9d374380-e175-11eb-9a89-53d3f275a994.png)

try this (https://github.com/GitNao/opencvsharp/commit/080b3551310429b9a2d83c83a2ee516238457751#diff-f260d80d63498fdd7fb8dab34c17d5002bdf2249912fcbd1c7af7825f81b7ba7)

![image](https://user-images.githubusercontent.com/31090571/125149756-c1932000-e175-11eb-95b0-06fd804f2f18.png)

use Pi3B+
![image](https://user-images.githubusercontent.com/31090571/125149810-2484b700-e176-11eb-803e-09b40b27aa19.png)

libOpenCvSharpExtern.so (https://github.com/GitNao/opencvsharp/suites/3203466114/artifacts/74081383)
rename .nupkg -> .zip

**Comment by GitNao** [comment]
```
libavcodec.so.57 => not found
libavformat.so.57 => not found
libavutil.so.55 => not found
libswscale.so.4 => not found
```

libOpenCvSharpExtern.so (https://github.com/GitNao/opencvsharp/actions/runs/1017218277)
```
libavcodec.so.58 => /lib/arm-linux-gnueabihf/neon/vfp/libavcodec.so.58 (0x738f4000)
libavformat.so.58 => /lib/arm-linux-gnueabihf/neon/vfp/libavformat.so.58 (0x736ca000)
libavutil.so.56 => /lib/arm-linux-gnueabihf/neon/vfp/libavutil.so.56 (0x73641000)
libswscale.so.5 => /lib/arm-linux-gnueabihf/neon/vfp/libswscale.so.5 (0x735c6000)
```

**Comment by jblam** [comment]
@GitNao this looks great! Unfortunately I've since removed my dependency on OpenCV so I'm not in a position to verify the change.

**Comment by starrynightok** [comment]
I encountered the same problem on arm64，and cross-compile this library. it took effect.

**Comment by obie73** [comment]
> I encountered the same problem on arm64, and cross-compile this library. it took effect.

Did you compile on an Apple M1?

**Comment by CobraCalle** [comment]
Hello,

because there is an "arm64" nuget too, I ran into the same problem, because I would like to use the "original" raspberry os. I have to access the camera through mmal, and under 64bit debian I cannot access video frames larger than 2mp, but I have a 12mp camera attached)... I think that is because mmal(sharp) is not 100% officially supported under debian (64bit), so I would like to go back to 32bite rapbian...

I 32-bit nuget would be great, because than ir would be much mor easy to switch to a newer version.

thanks

carl

**Comment by timstokman** [comment]
> > libOpenCvSharpExtern.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=2feb0d05276a0f30a7e6c2669610ca40685c2dca, not stripped
> 
> > It seems that libOpenCvSharpExtern.so (64 bit) you're referred is not a valid library for current OS .
> 
> I'd just note that the latest version of the `OpenCvSharp4.runtime.linux-arm` [nuget package](https://www.nuget.org/packages/OpenCvSharp4.runtime.linux-arm/) (currently 4.5.2.20210507) includes the _x84-64_ binary, not an _ARM_ binary. So the package is guaranteed never to work, as I understand it.
> 
> I'd suggest unlisting that package, to avoid having other people encounter this problem and leave comments on this issue :)

Noticed the same thing. They do have a workflow for linux-arm, I wonder what is going on there: https://github.com/shimat/opencvsharp/blob/master/.github/workflows/linux-arm.yml

**Comment by syamaner** [comment]
A bit late to the discussion but recently I experienced a similar issue too. If using Docker to run on Raspberry Pi, building OpenCV and OpenCvSharp as a multi architecture Docker build and then copy the native libraries to the target image when building the application. 

Here is an example: https://github.com/syamaner/docker-multi-arch-opencvsharp/tree/main/docker
And a bit more in the post: https://dev.to/syamaner/docker-multi-architecture-net-60-and-opencvsharp-1okd

Essentially all it does is to build both libraries, copy libOpenCvSharpExtern.so and all dependencies to /artifacts directory. Then when building an application image, use it as a stage to copy contents of the /artifacts into the target image. the build image is only 94 to 125 mb depending on target architecture:

https://hub.docker.com/repository/docker/syamaner/opencvsharp-build/tags

This way I only need to add OpenCvSharp4 as a package reference and native bindings will be handled at Docker build time when building the application image. I have tested using 32 and 64 bit OS on Raspberry pi including official Rabpbian as well as Ubuntu 20.04 and 22.04. 

Hope it helps.

**Comment by shenlongju** [comment]
有可供下载使用的文件吗，不想从头编译了

**Comment by AvenSun** [comment]
@shenlongju 
the attached file I built works well on Jetson, but it's not the latest version. 
It should work on all arm64/aarch64 platform, you can have a try.
[libOpenCvSharpExtern for Jetson(arm64/aarch64)](https://github.com/shimat/opencvsharp/files/6489049/libOpenCvSharpExtern.zip)

**Comment by shenlongju** [comment]
thank you, but I need arm32 version.
it will run in orangepi zero , ubuntu 18.04 arm




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shimat/opencvsharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shimat/opencvsharp] OpenCvSharp4.runtime.linux-arm doesn't work on raspberry pi 4 (#1263)





 
@shenlongju
 the attached file I built works well on Jetson, but it's not the latest version.
 It should work on all arm64/aarch64 platform, you can have a try.
 libOpenCvSharpExtern for Jetson(arm64/aarch64)

**Comment by OaimIsGnay** [comment]
> @shenlongju我构建的附件在 Jetson 上运行良好，但它不是最新版本。它应该适用于所有arm64 / aarch64平台，您可以尝试一下。[libOpenCvSharpExtern for Jetson（arm64/aarch64）](https://github.com/shimat/opencvsharp/files/6489049/libOpenCvSharpExtern.zip)

<img width="828" alt="image" src="https://user-images.githubusercontent.com/58240619/204688123-5413009f-e984-4d6d-bcc6-1337730bd210.png">
Raspberry arm64 tips

**Comment by AvenSun** [comment]
@OaimIsGnay 
you can try install it via 
`apt install libjpeg-turbo8`

**Comment by OaimIsGnay** [comment]
> @OaimIsGnay you can try install it via `apt install libjpeg-turbo8`

hello . can't find

**Comment by OaimIsGnay** [comment]
> 

Can you tell me the source?

**Comment by AvenSun** [comment]
apt update first  then try it again

**Comment by OaimIsGnay** [comment]
> apt update first then try it again
Does not work Please give me your source address

**Comment by OaimIsGnay** [comment]
> apt update first then try it again

Does not work Please give me your source address

**Comment by vnetb** [comment]
I use this on my Raspi.

```
 $ ldd libOpenCvSharpExtern.so | grep jpeg
        libjpeg.so.62 => /lib/aarch64-linux-gnu/libjpeg.so.62 
```

https://github.com/shimat/opencvsharp/issues/1497#issuecomment-1317998861

**Comment by AvenSun** [comment]
> > apt update first then try it again
> 
> Does not work Please give me your source address

https://github.com/libjpeg-turbo/libjpeg-turbo

**Comment by hongzhuoxx** [comment]
Nuget Install  Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64

#========================================================================

Linux orangepi5plus 5.10.160-rockchip-rk3588 #1.0.8 SMP Fri Nov 10 17:58:32 CST 2023 aarch64 GNU/Linux

Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

#========================================================================

Test OK！

**Comment by lsqwithgithub** [comment]
> @shenlongju the attached file I built works well on Jetson, but it's not the latest version. It should work on all arm64/aarch64 platform, you can have a try. [libOpenCvSharpExtern for Jetson(arm64/aarch64)](https://github.com/shimat/opencvsharp/files/6489049/libOpenCvSharpExtern.zip)
Hello,I wish to built the attached file,but target pc no network,target pc is arm-64,kylin os,can you tell me what can i do.
I not a english speaker.Regret for my syntax.

**Comment by lsqwithgithub** [comment]
@AvenSun Hello,I wish to built the attached file,but target pc no network,target pc is arm-64,kylin os,can you tell me what can i do.
I not a english speaker.Regret for my syntax.

**Comment by lsqwithgithub** [comment]
@AvenSun Hello,I wish to built the attached file,target pc is arm-64,linux,can you tell me what can i do.
I not a english speaker.Regret for my syntax.
