### ISSUE TITLE
Loading more than 4GB of data causes out of memory error on x64 program

### ISSUE THREAD

**Issue by AlexandreLaborde** [shimat/opencvsharp#1264]
# Summary of your issue

I have a simple function to load all images in folder. The 23000 images are grayscale 8bit jpegs 690x690 wich should result in around 11GB of allocated space for my images.
After loading 7469 images the program's memory reaches close to 4GB and opencv throws a _"cv::OutOfMemoryError"_ error.
I am running my program on x64 mode I enabled <gcAllowVeryLargeObjects enabled="true" /> on my config file and that does not solve the problem.

It appears as if even tough my program is running on 64 bit, the underlying c++ opencv calls are still running on 32bit and thus bumping into the max memory allowed by Windows. Can anyone confirm this ?

# Environment
Visual Studio Community 2019 16.9.5
WPF app on .NET Framework 4.8
Windows 10 Pro x64 build 20H2
64 GB RAM

# What did you do when you faced the problem?

pray to @shimat to solve this issue 😅

## Example code:

```
string[] imageFiles = Directory.GetFiles(root, "*.jpg");
int n = imageFiles.Length;

Mat[] images = new Mat[n];
images[0] = new Mat(imageFiles[0], ImreadModes.Grayscale);

for (int i = 1; i < n; i++)
{ 
    images[i] = new Mat(imageFiles[i], ImreadModes.Grayscale);
    Debug.WriteLine($"Loading image {i}");
}
```

## Output:

```
An exception of type 'OpenCvSharp.OpenCVException' occurred in OpenCvSharp.dll but was not handled in user code
Failed to allocate 476100 bytes

opencv call stack:

OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1664_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData) at
OpenCvSharp.Internal.NativeMethods.imgcodecs_imread_Windows(String fileName, Int32 flags, IntPtr& returnValue) at
OpenCvSharp.Internal.NativeMethods.imgcodecs_imread(String fileName, Int32 flags, IntPtr& returnValue) at
OpenCvSharp.Mat..ctor(String fileName, ImreadModes flags) at 
... my code ...
```

**Comment by AlexandreLaborde** [comment]
it should read : I enabled `<gcAllowVeryLargeObjects enabled="true"/>` on my config file

**Comment by shimat** [comment]
Is your program really running as x64? If the target platform is AnyCPU, make sure that the "Prefer 32-Bit" mode is disabled.
And make sure that `IntPtr.Size == 8`.

**Comment by AlexandreLaborde** [comment]
Totally forgot about the stupid checkbox _Prefer 32-bit_ check box 🤦‍♂️
Thank you for the fast reply.
Keep up the good work!
