### ISSUE TITLE
Problem when using self-compiled lib on jetson nano : undefined symbol: _ZN2cv3MatC1Ev

### ISSUE THREAD

**Issue by developer-ken** [shimat/opencvsharp#1265]
# Summary of your issue

I use opencvsharp in my project on raspberry pi.  When I get libOpencvSharp.so from nuget, it all runs okay.  But I have to compile the lib myself to run it on jetson nano, so I did that.  
With the exactly same working code, I get this error on jetson nano (with the self-compiled .so file) :
`symbol lookup error: /myenvirounment/opencvsharp/src/build/OpenCvSharpExtern/libOpenCvSharpExtern.so: undefined symbol: _ZN2cv3MatC1Ev`

# Environment

Jetson nano, with latest jetson pack;  
.NET 5  

# What did you do when you faced the problem?

Run my project.

## Example code:

```
var src = new Mat();
var cap = Cv2.CreateFrameSource_Camera(0);
cap.NextFrame(src);
```

## Output:

```
./Detector: symbol lookup error: /myenvirounment/opencvsharp/src/build/OpenCvSharpExtern/libOpenCvSharpExtern.so: undefined symbol: _ZN2cv3MatC1Ev
```

## What did you intend to be?
Run normally

**Comment by AvenSun** [comment]
seems that  it is a mangled name for the opencv Mat class.
make sure you've built native library successfully and correctly.

**Comment by developer-ken** [comment]
I built this project again, this is the output I got:
`root@ken-desktop:/myenvirounment/opencvsharp/src/build# make -j4
Scanning dependencies of target OpenCvSharpExtern
[  9%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/calib3d.cpp.o
[  9%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/bgsegm.cpp.o
[  9%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/aruco.cpp.o
[ 12%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/core.cpp.o
[ 15%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/cuda.cpp.o
[ 18%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/dnn.cpp.o
[ 21%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/dnn_superres.cpp.o
[ 24%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/face.cpp.o
[ 27%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/features2d.cpp.o
[ 30%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/flann.cpp.o
[ 33%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/highgui.cpp.o
[ 36%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/img_hash.cpp.o
[ 39%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/imgcodecs.cpp.o
[ 42%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/imgproc.cpp.o
[ 45%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/line_descriptor.cpp.o
[ 48%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/ml.cpp.o
[ 51%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/objdetect.cpp.o
[ 54%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/optflow.cpp.o
[ 57%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/photo.cpp.o
[ 60%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/quality.cpp.o
[ 63%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/shape.cpp.o
[ 66%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/std_string.cpp.o
[ 69%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/std_vector.cpp.o
[ 72%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/stitching.cpp.o
[ 75%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/superres.cpp.o
[ 78%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/text.cpp.o
[ 81%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/tracking.cpp.o
[ 84%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/video.cpp.o
[ 87%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/videoio.cpp.o
[ 90%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/xfeatures2d.cpp.o
[ 93%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/ximgproc.cpp.o
[ 96%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/xphoto.cpp.o
[100%] Linking CXX shared library libOpenCvSharpExtern.so
[100%] Built target OpenCvSharpExtern
`

I searched the web and found some information, it says I should use `ldd` to check the .so file. I tried it:
`root@ken-desktop:~/FruitDetector# ldd /myenvirounment/opencvsharp/src/build/OpenCvSharpExtern/libOpenCvSharpExtern.so
        linux-vdso.so.1 (0x0000007fabdd9000)
        libopencv_dnn.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_dnn.so.4.1 (0x0000007fab71b000)
        libopencv_gapi.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_gapi.so.4.1 (0x0000007fab544000)
        libopencv_highgui.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_highgui.so.4.1 (0x0000007fab51d000)
        libopencv_ml.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_ml.so.4.1 (0x0000007fab471000)
        libopencv_objdetect.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_objdetect.so.4.1 (0x0000007fab415000)
        libopencv_photo.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_photo.so.4.1 (0x0000007fab35d000)
        libopencv_stitching.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_stitching.so.4.1 (0x0000007fab2b4000)
        libopencv_video.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_video.so.4.1 (0x0000007fab25d000)
        libopencv_videoio.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_videoio.so.4.1 (0x0000007fab1e7000)
        libopencv_imgcodecs.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_imgcodecs.so.4.1 (0x0000007fab0be000)
        libopencv_calib3d.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_calib3d.so.4.1 (0x0000007faaf6c000)
        libopencv_features2d.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_features2d.so.4.1 (0x0000007faaec6000)
        libopencv_flann.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_flann.so.4.1 (0x0000007faae63000)
        libopencv_imgproc.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_imgproc.so.4.1 (0x0000007faaadd000)
        libopencv_core.so.4.1 => /usr/lib/aarch64-linux-gnu/libopencv_core.so.4.1 (0x0000007faa7c0000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007faa62c000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007faa573000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007faa54f000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007faa3f6000)
        /lib/ld-linux-aarch64.so.1 (0x0000007fabdad000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007faa3ca000)
        libgtk-x11-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0 (0x0000007fa9ff9000)
        libgdk-x11-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgdk-x11-2.0.so.0 (0x0000007fa9f4a000)
        libcairo.so.2 => /usr/lib/aarch64-linux-gnu/libcairo.so.2 (0x0000007fa9e50000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x0000007fa9e21000)
        libgobject-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0 (0x0000007fa9dc4000)
        libglib-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0 (0x0000007fa9cb5000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007fa9ca0000)
        libgstreamer-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstreamer-1.0.so.0 (0x0000007fa9b70000)
        libgstapp-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstapp-1.0.so.0 (0x0000007fa9b52000)
        libgstriff-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstriff-1.0.so.0 (0x0000007fa9b34000)
        libgstpbutils-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstpbutils-1.0.so.0 (0x0000007fa9aef000)
        libavcodec.so.57 => /usr/lib/aarch64-linux-gnu/libavcodec.so.57 (0x0000007fa88a9000)
        libavformat.so.57 => /usr/lib/aarch64-linux-gnu/libavformat.so.57 (0x0000007fa8671000)
        libavutil.so.55 => /usr/lib/aarch64-linux-gnu/libavutil.so.55 (0x0000007fa85e2000)
        libswscale.so.4 => /usr/lib/aarch64-linux-gnu/libswscale.so.4 (0x0000007fa856f000)
        libjpeg.so.8 => /usr/lib/aarch64-linux-gnu/libjpeg.so.8 (0x0000007fa8525000)
        libpng16.so.16 => /usr/lib/aarch64-linux-gnu/libpng16.so.16 (0x0000007fa84ea000)
        libtiff.so.5 => /usr/lib/aarch64-linux-gnu/libtiff.so.5 (0x0000007fa846f000)
        libtbb.so.2 => /usr/lib/aarch64-linux-gnu/libtbb.so.2 (0x0000007fa8431000)
        libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000007fa8404000)
        libgmodule-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgmodule-2.0.so.0 (0x0000007fa83ee000)
        libpangocairo-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libpangocairo-1.0.so.0 (0x0000007fa83d2000)
        libX11.so.6 => /usr/lib/aarch64-linux-gnu/libX11.so.6 (0x0000007fa82a9000)
        libXfixes.so.3 => /usr/lib/aarch64-linux-gnu/libXfixes.so.3 (0x0000007fa8293000)
        libatk-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libatk-1.0.so.0 (0x0000007fa825f000)
        libgio-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgio-2.0.so.0 (0x0000007fa80e1000)
        libpangoft2-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libpangoft2-1.0.so.0 (0x0000007fa80bc000)
        libpango-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libpango-1.0.so.0 (0x0000007fa8065000)
        libfontconfig.so.1 => /usr/lib/aarch64-linux-gnu/libfontconfig.so.1 (0x0000007fa8015000)
        libXrender.so.1 => /usr/lib/aarch64-linux-gnu/libXrender.so.1 (0x0000007fa7ffc000)
        libXinerama.so.1 => /usr/lib/aarch64-linux-gnu/libXinerama.so.1 (0x0000007fa7fe9000)
        libXi.so.6 => /usr/lib/aarch64-linux-gnu/libXi.so.6 (0x0000007fa7fcb000)
        libXrandr.so.2 => /usr/lib/aarch64-linux-gnu/libXrandr.so.2 (0x0000007fa7faf000)
        libXcursor.so.1 => /usr/lib/aarch64-linux-gnu/libXcursor.so.1 (0x0000007fa7f96000)
        libXcomposite.so.1 => /usr/lib/aarch64-linux-gnu/libXcomposite.so.1 (0x0000007fa7f83000)
        libXdamage.so.1 => /usr/lib/aarch64-linux-gnu/libXdamage.so.1 (0x0000007fa7f70000)
        libXext.so.6 => /usr/lib/aarch64-linux-gnu/libXext.so.6 (0x0000007fa7f50000)
        libpixman-1.so.0 => /usr/lib/aarch64-linux-gnu/libpixman-1.so.0 (0x0000007fa7eec000)
        libfreetype.so.6 => /usr/lib/aarch64-linux-gnu/libfreetype.so.6 (0x0000007fa7e42000)
        libxcb-shm.so.0 => /usr/lib/aarch64-linux-gnu/libxcb-shm.so.0 (0x0000007fa7e2f000)
        libxcb.so.1 => /usr/lib/aarch64-linux-gnu/libxcb.so.1 (0x0000007fa7dff000)
        libxcb-render.so.0 => /usr/lib/aarch64-linux-gnu/libxcb-render.so.0 (0x0000007fa7de4000)
        libffi.so.6 => /usr/lib/aarch64-linux-gnu/libffi.so.6 (0x0000007fa7dcc000)
        libpcre.so.3 => /lib/aarch64-linux-gnu/libpcre.so.3 (0x0000007fa7d5a000)
        libgstbase-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstbase-1.0.so.0 (0x0000007fa7ce1000)
        libgstaudio-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstaudio-1.0.so.0 (0x0000007fa7c6d000)
        libgsttag-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgsttag-1.0.so.0 (0x0000007fa7c26000)
        libgstvideo-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstvideo-1.0.so.0 (0x0000007fa7b90000)
        libswresample.so.2 => /usr/lib/aarch64-linux-gnu/libswresample.so.2 (0x0000007fa7b6a000)
        libwebp.so.6 => /usr/lib/aarch64-linux-gnu/libwebp.so.6 (0x0000007fa7b10000)
        libva.so.2 => /usr/lib/aarch64-linux-gnu/libva.so.2 (0x0000007fa7ae1000)
        libzvbi.so.0 => /usr/lib/aarch64-linux-gnu/libzvbi.so.0 (0x0000007fa7a52000)
        libxvidcore.so.4 => /usr/lib/aarch64-linux-gnu/libxvidcore.so.4 (0x0000007fa796b000)
        libx265.so.146 => /usr/lib/aarch64-linux-gnu/libx265.so.146 (0x0000007fa770d000)
        libx264.so.152 => /usr/lib/aarch64-linux-gnu/libx264.so.152 (0x0000007fa75a9000)
        libwebpmux.so.3 => /usr/lib/aarch64-linux-gnu/libwebpmux.so.3 (0x0000007fa758e000)
        libwavpack.so.1 => /usr/lib/aarch64-linux-gnu/libwavpack.so.1 (0x0000007fa755c000)
        libvpx.so.5 => /usr/lib/aarch64-linux-gnu/libvpx.so.5 (0x0000007fa73b0000)
        libvorbisenc.so.2 => /usr/lib/aarch64-linux-gnu/libvorbisenc.so.2 (0x0000007fa7301000)
        libvorbis.so.0 => /usr/lib/aarch64-linux-gnu/libvorbis.so.0 (0x0000007fa72cb000)
        libtwolame.so.0 => /usr/lib/aarch64-linux-gnu/libtwolame.so.0 (0x0000007fa729c000)
        libtheoraenc.so.1 => /usr/lib/aarch64-linux-gnu/libtheoraenc.so.1 (0x0000007fa7258000)
        libtheoradec.so.1 => /usr/lib/aarch64-linux-gnu/libtheoradec.so.1 (0x0000007fa7231000)
        libspeex.so.1 => /usr/lib/aarch64-linux-gnu/libspeex.so.1 (0x0000007fa720c000)
        libsnappy.so.1 => /usr/lib/aarch64-linux-gnu/libsnappy.so.1 (0x0000007fa71f4000)
        libshine.so.3 => /usr/lib/aarch64-linux-gnu/libshine.so.3 (0x0000007fa71da000)
        librsvg-2.so.2 => /usr/lib/aarch64-linux-gnu/librsvg-2.so.2 (0x0000007fa719c000)
        libopus.so.0 => /usr/lib/aarch64-linux-gnu/libopus.so.0 (0x0000007fa714d000)
        libopenjp2.so.7 => /usr/lib/aarch64-linux-gnu/libopenjp2.so.7 (0x0000007fa70f2000)
        libmp3lame.so.0 => /usr/lib/aarch64-linux-gnu/libmp3lame.so.0 (0x0000007fa7076000)
        libgsm.so.1 => /usr/lib/aarch64-linux-gnu/libgsm.so.1 (0x0000007fa705c000)
        liblzma.so.5 => /lib/aarch64-linux-gnu/liblzma.so.5 (0x0000007fa702c000)
        libssh-gcrypt.so.4 => /usr/lib/aarch64-linux-gnu/libssh-gcrypt.so.4 (0x0000007fa6fb3000)
        libopenmpt.so.0 => /usr/lib/aarch64-linux-gnu/libopenmpt.so.0 (0x0000007fa6deb000)
        libbluray.so.2 => /usr/lib/aarch64-linux-gnu/libbluray.so.2 (0x0000007fa6d94000)
        libgnutls.so.30 => /usr/lib/aarch64-linux-gnu/libgnutls.so.30 (0x0000007fa6c33000)
        libxml2.so.2 => /usr/lib/aarch64-linux-gnu/libxml2.so.2 (0x0000007fa6a93000)
        libgme.so.0 => /usr/lib/aarch64-linux-gnu/libgme.so.0 (0x0000007fa6a3c000)
        libchromaprint.so.1 => /usr/lib/aarch64-linux-gnu/libchromaprint.so.1 (0x0000007fa6a1a000)
        libbz2.so.1.0 => /lib/aarch64-linux-gnu/libbz2.so.1.0 (0x0000007fa69f8000)
        libdrm.so.2 => /usr/lib/aarch64-linux-gnu/libdrm.so.2 (0x0000007fa69c3000)
        libvdpau.so.1 => /usr/lib/aarch64-linux-gnu/libvdpau.so.1 (0x0000007fa69af000)
        libva-x11.so.2 => /usr/lib/aarch64-linux-gnu/libva-x11.so.2 (0x0000007fa699a000)
        libva-drm.so.2 => /usr/lib/aarch64-linux-gnu/libva-drm.so.2 (0x0000007fa6987000)
        libjbig.so.0 => /usr/lib/aarch64-linux-gnu/libjbig.so.0 (0x0000007fa6968000)
        libselinux.so.1 => /lib/aarch64-linux-gnu/libselinux.so.1 (0x0000007fa6935000)
        libresolv.so.2 => /lib/aarch64-linux-gnu/libresolv.so.2 (0x0000007fa6910000)
        libmount.so.1 => /lib/aarch64-linux-gnu/libmount.so.1 (0x0000007fa68b3000)
        libharfbuzz.so.0 => /usr/lib/aarch64-linux-gnu/libharfbuzz.so.0 (0x0000007fa6813000)
        libthai.so.0 => /usr/lib/aarch64-linux-gnu/libthai.so.0 (0x0000007fa67f9000)
        libexpat.so.1 => /lib/aarch64-linux-gnu/libexpat.so.1 (0x0000007fa67ba000)
        libXau.so.6 => /usr/lib/aarch64-linux-gnu/libXau.so.6 (0x0000007fa67a7000)
        libXdmcp.so.6 => /usr/lib/aarch64-linux-gnu/libXdmcp.so.6 (0x0000007fa6792000)
        liborc-0.4.so.0 => /usr/lib/aarch64-linux-gnu/liborc-0.4.so.0 (0x0000007fa6719000)
        libsoxr.so.0 => /usr/lib/aarch64-linux-gnu/libsoxr.so.0 (0x0000007fa66b6000)
        libnuma.so.1 => /usr/lib/aarch64-linux-gnu/libnuma.so.1 (0x0000007fa6698000)
        libogg.so.0 => /usr/lib/aarch64-linux-gnu/libogg.so.0 (0x0000007fa6681000)
        libcroco-0.6.so.3 => /usr/lib/aarch64-linux-gnu/libcroco-0.6.so.3 (0x0000007fa663d000)
        libgcrypt.so.20 => /lib/aarch64-linux-gnu/libgcrypt.so.20 (0x0000007fa6580000)
        libgssapi_krb5.so.2 => /usr/lib/aarch64-linux-gnu/libgssapi_krb5.so.2 (0x0000007fa652f000)
        libmpg123.so.0 => /usr/lib/aarch64-linux-gnu/libmpg123.so.0 (0x0000007fa64d2000)
        libvorbisfile.so.3 => /usr/lib/aarch64-linux-gnu/libvorbisfile.so.3 (0x0000007fa64ba000)
        libp11-kit.so.0 => /usr/lib/aarch64-linux-gnu/libp11-kit.so.0 (0x0000007fa63a8000)
        libidn2.so.0 => /usr/lib/aarch64-linux-gnu/libidn2.so.0 (0x0000007fa637c000)
        libunistring.so.2 => /usr/lib/aarch64-linux-gnu/libunistring.so.2 (0x0000007fa61f7000)
        libtasn1.so.6 => /usr/lib/aarch64-linux-gnu/libtasn1.so.6 (0x0000007fa61d6000)
        libnettle.so.6 => /usr/lib/aarch64-linux-gnu/libnettle.so.6 (0x0000007fa6195000)
        libhogweed.so.4 => /usr/lib/aarch64-linux-gnu/libhogweed.so.4 (0x0000007fa6153000)
        libgmp.so.10 => /usr/lib/aarch64-linux-gnu/libgmp.so.10 (0x0000007fa60d6000)
        libicuuc.so.60 => /usr/lib/aarch64-linux-gnu/libicuuc.so.60 (0x0000007fa5f02000)
        libnvll.so => /usr/lib/aarch64-linux-gnu/tegra/libnvll.so (0x0000007fa5ee3000)
        libnvos.so => /usr/lib/aarch64-linux-gnu/tegra/libnvos.so (0x0000007fa5ec5000)
        libblkid.so.1 => /lib/aarch64-linux-gnu/libblkid.so.1 (0x0000007fa5e6f000)
        libgraphite2.so.3 => /usr/lib/aarch64-linux-gnu/libgraphite2.so.3 (0x0000007fa5e3e000)
        libdatrie.so.1 => /usr/lib/aarch64-linux-gnu/libdatrie.so.1 (0x0000007fa5e28000)
        libbsd.so.0 => /lib/aarch64-linux-gnu/libbsd.so.0 (0x0000007fa5e04000)
        libgomp.so.1 => /usr/lib/aarch64-linux-gnu/libgomp.so.1 (0x0000007fa5dc7000)
        libgpg-error.so.0 => /lib/aarch64-linux-gnu/libgpg-error.so.0 (0x0000007fa5da5000)
        libkrb5.so.3 => /usr/lib/aarch64-linux-gnu/libkrb5.so.3 (0x0000007fa5cd5000)
        libk5crypto.so.3 => /usr/lib/aarch64-linux-gnu/libk5crypto.so.3 (0x0000007fa5c97000)
        libcom_err.so.2 => /lib/aarch64-linux-gnu/libcom_err.so.2 (0x0000007fa5c81000)
        libkrb5support.so.0 => /usr/lib/aarch64-linux-gnu/libkrb5support.so.0 (0x0000007fa5c67000)
        libicudata.so.60 => /usr/lib/aarch64-linux-gnu/libicudata.so.60 (0x0000007fa42ae000)
        libnvrm.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm.so (0x0000007fa426b000)
        libnvrm_graphics.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_graphics.so (0x0000007fa424b000)
        libnvdc.so => /usr/lib/aarch64-linux-gnu/tegra/libnvdc.so (0x0000007fa422b000)
        librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000007fa4212000)
        libuuid.so.1 => /lib/aarch64-linux-gnu/libuuid.so.1 (0x0000007fa41fb000)
        libkeyutils.so.1 => /lib/aarch64-linux-gnu/libkeyutils.so.1 (0x0000007fa41e7000)
        libnvimp.so => /usr/lib/aarch64-linux-gnu/tegra/libnvimp.so (0x0000007fa41d2000)
`
Everything seems fine, but the problem is still there.

**Comment by AvenSun** [comment]
obviously It's not lack of dependecy. 
cuz the exception message does not look like as follows
> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies.

It looks like some module  is missing in native library.
make sure the version of opencv native library you build  is the same to OpencvSharp.
the attached file I built works well on Jetson, but it's not the latest version.
[libOpenCvSharpExtern.zip for Jetson(ARM aarch64)](https://github.com/shimat/opencvsharp/files/6489049/libOpenCvSharpExtern.zip)
you can have a try.

**Comment by developer-ken** [comment]
Thanks a lot.  I will try to rebuild opencv and opencvsharp.

**Comment by developer-ken** [comment]
It turns out that I have 2 different version of opencv installed on my board.  
The board come with one preinstalled, and I built a new one.  
When I build opencvsharp, it uses the defualt (preinstalled) one, which is the wrong version.  
Thankds a lot for help. I will close the issue.
