### ISSUE TITLE
Template matching with CCoeffNormed unhandled exception with Mask

### ISSUE THREAD

**Issue by yarden24** [shimat/opencvsharp#1268]
# Summary of your issue
The Template matching with CCoeffNormed does not currently work with a Mask, this feature has been fixed in openCV.

a similar older question with images and code was closed:
https://github.com/shimat/opencvsharp/issues/139#issue-112191858

I have taken the code and images and posted them below:

```
            Mat template = new Mat("\\template.png");
            Mat source = new Mat("\\image.png");
            Mat mask = new Mat("\\mask.png");
            OpenCvSharp.Mat r = new OpenCvSharp.Mat(source.Size(), OpenCvSharp.MatType.CV_8U);



            OpenCvSharp.Mat tGray = new OpenCvSharp.Mat(source.Size(), OpenCvSharp.MatType.CV_8U);
            OpenCvSharp.Cv2.CvtColor(template, tGray, OpenCvSharp.ColorConversionCodes.BGR2GRAY);

            OpenCvSharp.Mat sGray = new OpenCvSharp.Mat(source.Size(), OpenCvSharp.MatType.CV_8U);
            OpenCvSharp.Cv2.CvtColor(source, sGray, OpenCvSharp.ColorConversionCodes.BGR2GRAY);


            OpenCvSharp.Cv2.CvtColor(mask, mask, OpenCvSharp.ColorConversionCodes.BGR2GRAY);
```
![image](https://user-images.githubusercontent.com/29480312/119354425-c165c080-bcac-11eb-8aa3-8abefc5cf7c5.png)
![mask](https://user-images.githubusercontent.com/29480312/119354431-c296ed80-bcac-11eb-881a-b89f47f0fe04.png)
![template](https://user-images.githubusercontent.com/29480312/119354437-c32f8400-bcac-11eb-93e3-c5479dd6a8d4.png)

the following empty exception is outputted:

```
OpenCvSharp.OpenCVException
  HResult=0x80131500
  Message=
  Source=OpenCvSharp
  StackTrace:
   at OpenCvSharp.NativeMethods.<>c.<.cctor>b__1559_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
```

is it possible to add this feature to this project?

**Comment by shimat** [comment]
The code below worked fine for me.
```c#
using var template = new Mat("template.png", ImreadModes.Grayscale);
using var source = new Mat("image.png", ImreadModes.Grayscale);
using var mask = new Mat("mask.png", ImreadModes.Grayscale);
using var result = new Mat();
            
Cv2.MatchTemplate(source, template, result, TemplateMatchModes.CCoeffNormed, mask);
```

**Comment by yarden24** [comment]
hello,
It seems that the problem occurs because of a conflict with some other packages I installed,
when creating a new project the function does indeed work.

Ill close the comment for now.
