### ISSUE TITLE
Copy a Mat to another Mat's center   

### ISSUE THREAD

**Issue by DirkKramer** [shimat/opencvsharp#1269]
# Summary of your issue

I want to be able to Copy a Mat to another Mat's center.

For example:

I have a Mat with size 400x400, I want to put a Mat with size 100x100 in the middle of the first mat at location (150,150).

When I search for this functionality i get some opencv examples which are mostly using the ROI of a mat.  

Does anyone know how to do this with OpenCVSharp?

# Environment

Windows 
.NET 5 WPF

**Comment by shimat** [comment]
```c#
using var a = new Mat(400, 400, MatType.CV_8UC3, Scalar.Red);
using var b = new Mat(100, 100, MatType.CV_8UC3, Scalar.Blue);

using var aPart = a[new Rect(150, 150, 100, 100)];
b.CopyTo(aPart);
```

**Comment by DirkKramer** [comment]
Thank you very much for this fast reaction, everything works as espected now!
