### ISSUE TITLE
How to create a Mat from tiled images?

### ISSUE THREAD

**Issue by haruby511** [shimat/opencvsharp#1270]
I plan to handle huge pixels images. Therefore, I will tiling them to optimize memory usage and etc.
But it seems that the `Mat` only accept a serial of memory. There is clipping mask but I cannot find unifying method.
If have to make a serial of memory, it will be very expensive and inefficient way.
However, I cannot sure that it is possible to inherit the `Mat` and implement **a tiled** `Mat` without copy.
If there is an implementation, please show me where it is.
Otherwise, is it can be supported in the future?

**Comment by shimat** [comment]
I looked for such a feature but couldn't find it. You will probably have to create one yourself.

```c#
// This code is not debugged
class TiledMat
{
    private Mat[][] table;
    private Size tileSize;

    public TiledMat(Mat[][] table)
    {
        this.table = table;
        tileSize = table[0][0].Size();
    }

    public Vec3b GetPixel(int row, int col)
    {
        var targetMat = table[row / tileSize][col / tileSize];
        return targetMat.Get<Vec3b>(row % tileSize, col % tileSize);
    }

    ...
}
```

**Comment by haruby511** [comment]
@shimat If do that, how to work with `Cv2` methods?

I mean `Mat` compatible object not just data structure.
And I don't think it is proper to pass the `Mat` tile one by one to `Cv2`.
For example, the `Erode()` involve outside of the tile itself because of the kernel size.
Therefore, I need **A** tiled `Mat`.

Whatever, if there is not plan to add a feature such as unifying thing, in the end, copying is unavoidable in this state.
Limiting kernel size and processing 9 per 9 will be final optimized method. It is limited and not very efficient, though.
