### ISSUE TITLE
Documents 404

### ISSUE THREAD

**Issue by nbyh** [shimat/opencvsharp#1275]
Documents can't load, page not found!
![2021-06-02_175639](https://user-images.githubusercontent.com/7239908/120460720-f3bd9f00-c3cb-11eb-95df-3bb4b3547d11.png)

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp/runs/2702705398?check_suite_focus=true#step:3:188
https://github.com/dotnet/docfx/issues/5554

I'll wait for docfx to fix this issue.

**Comment by shimat** [comment]
The docfx bug has been fixed, so the OpenCvSharp documentation is back. Thanks.
