### ISSUE TITLE
Shared lib is not found on Ubuntu 20.04

### ISSUE THREAD

**Issue by VsevolodKzn** [shimat/opencvsharp#1276]
# Summary of your issue
I'm getting exception when trying to use opencvsharp on Ubuntu 2004 with packages:
<PackageReference Include="OpenCvSharp4" Version="4.5.2.20210404" />
<PackageReference Include="OpenCvSharp4.runtime.ubuntu.18.04-x64" Version="4.5.2.20210404" />

System.DllNotFoundException : Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory

Setting lib path is not helping to resolve the issue:
 "LD_LIBRARY_PATH": "${workspaceFolder}/VideoServer/bin/Debug/netcoreapp3.1/runtimes/ubuntu.18.04-x64/native"

# Environment
Ubuntu 2004

**Comment by VsevolodKzn** [comment]
Solved by getting older packages from archive:
sudo apt install libopenexr22
sudo apt install libswscale4
sudo apt install libavformat57
sudo apt install libavcodec57

Any way it'll be great to have Ubuntu2004 support.

**Comment by AvenSun** [comment]
try to run command as follows
ldd /xxx/libOpenCvSharpExtern.so
check the library marked "not found"
then install it
