### ISSUE TITLE
Issue with masks

### ISSUE THREAD

**Issue by exverse** [shimat/opencvsharp#1279]
I am currently trying to mask a object, both the template and mask are the same width/height same everything, i keep getting this error

OpenCvSharp.OpenCVException: '_templ.size() == _mask.size()'

```c#
Mat tplMat = new Mat("c:\\tmp\\Image1.png", ImreadModes.Grayscale);
Mat tplMatMask = new Mat("c:\\tmp\\Image1mask.png", ImreadModes.Grayscale);
Mat refMat = new Mat("c:\\tmp\\test1.png", ImreadModes.Grayscale);
Mat res = new Mat();

Cv2.MatchTemplate(tplMat, refMat, res, TemplateMatchModes.CCorrNormed, tplMatMask); /* Error is here */
```

**Comment by mpolicki** [comment]
Set a breakpoint on the MatchTemplate line, start debugging, and inspect the Mats to see what their sizes are. Most likely they're different, as the error message implies.
