### ISSUE TITLE
DFT Example question

### ISSUE THREAD

**Issue by fdncred** [shimat/opencvsharp#128]
I have a couple questions regarding the DFT sample.  I want to write out the spectrum Mat so I tried the following code.  None work as expected.  I'm using the 3.0.0 Aug 23 release.
```C#
//This writes out what appears to be a black png file
Cv2.ImWrite("dft2.png", spectrum);
//This also writes out what appears to be just a black png file
spectrum.SaveImage("dft.png");
//This throws an exception
System.Drawing.Bitmap b = OpenCvSharp.Extensions.BitmapConverter.ToBitmap(spectrum);
b.Save("dft3.png");
```
How do I save this out as it appears in the "Spectrum Magnitude" window?

My second question is related to this StackOverflow article http://stackoverflow.com/questions/16812950/how-do-i-compute-dft-and-its-reverse-with-emgu.  I'm essentially trying to reproduce the output in the article and your DFT "Spectrum Magnitude" output seems very different from the StackOverflow article.  Can you help me understand why your DFT is different and how to make the output match the SO article?

**Comment by fdncred** [comment]
I think I figured it out.  The reason the magnitude image doesn't match is because the DFT example pads the image and the SO article does not.  Thanks for a great wrapper.

**Comment by fdncred** [comment]
Regarding the first question, I can show Mat objects with Cv2.ImShow(mat) and they look great but when I try to save the mat with mat.SaveImage("filename.png") or with Cv2.ImWrite("filename.png", mat) the images are just black and never match the image that shows up with ImShow.  What am I missing?

Snippet
```chsarp
Cv2.ImShow("Spectrum", magI);
Cv2.WaitKey();
magI.SaveImage("output.png");

**Comment by shimat** [comment]
To save float Mat as displayable image, you may have to scale it to 8U mat using `Cv2.ConvertScaleAbs`.
```c#
Cv2.ConvertScaleAbs(magI, dst, 255/*specify proper scale*/);
```

**Comment by fdncred** [comment]
Shouldn't that be part of the DebuggerVisualizer?  Something like this perhaps.
```csharp
public MatProxy(Mat image)
{
    if (image.Type() != MatType.CV_8U)
        Cv2.ConvertScaleAbs(image, image, 255);
    ImageData = image.ToBytes(".png");
}
```
Is there anything wrong with doing it this way?

**Comment by shimat** [comment]
The value range of 32F Mat is not always between 0f to 1f.
Cv2.Normalize may be able to support general float Mats, but I think suitable conversion to 8U is different from Mat to Mat. 
(For example, if the target Mat has some minus values, what is the most suitable conversion to 8U?)

**Comment by fdncred** [comment]
Good points.  I'm not sure what the answer is but I know I do not have this problem when working directly with OpenCV nor do I have it when using EmguCV.  I've used EmguCV for a long time but I really like using OpenCvSharp because it's so much easier to port C++ code to it.  Thank you for taking the time to make it.  From a usability standpoint it would just be easier to have the SaveImage and DebuggerVisualizers work as expected.  It makes it easier to on ramp new users to your project.  Just my two cents.

**Comment by shimat** [comment]
I found a solution. `cvConvertScale` can convert float image to displayable (8UC3) image. 
```c#
public MatProxy(Mat image)
{
    using (var converted = new Mat())
    {
        Cv2.ConvertImage(image, converted); // I will add this function 
        ImageData = converted.ToBytes(".png");
    }
}
```

**Comment by fdncred** [comment]
I've been using this without issue but I haven't tried a lot of input image types so I'm not sure how safe it is.

```csharp
public MatProxy(Mat image)
{
    //Don't modify the original image
    Mat copyImg = image.Clone();
    if (copyImg.Type() != MatType.CV_8U &&
        copyImg.Type() != MatType.CV_8UC1 &&
        copyImg.Type() != MatType.CV_8UC2 &&
        copyImg.Type() != MatType.CV_8UC3 &&
        copyImg.Type() != MatType.CV_8UC4)
        Cv2.ConvertScaleAbs(copyImg, copyImg, 255);
    ImageData = copyImg.ToBytes(".png");
}

```

**Comment by fdncred** [comment]
@shimat Are you also going to update the SaveImage function to do this convert as well?

**Comment by shimat** [comment]
No. The OpenCvSharp wrapper aims not to change native functions' behavior.
