### ISSUE TITLE
Dockerfile based on .Net 5.0 including opencv

### ISSUE THREAD

**Issue by Lerseb** [shimat/opencvsharp#1281]
# Summary of your issue
Looking to migrate to .net 5.0 for my project using OpenCvSharp.

This is not a real issue, I am trying to create an image based on mcr.microsoft.com/dotnet/sdk:5.0 and install OpenCv.
I tried to use al2-dotnet5-opencv4.5.1 dockerfile as a model and changed from on the first line with mcr.microsoft.com/dotnet/sdk:5.0 but it doesn't build.
I don't have much experience building complex images and help would be awesome.
Thanks
# Environment

Write your environment.

# What did you do when you faced the problem?

Write here

## Example code:

```
FROM mcr.microsoft.com/dotnet/sdk:5.0

ENV OPENCV_VERSION=4.5.1

WORKDIR /

RUN yum update -y && \
    yum groupinstall -y "Development Tools" && \
    yum install -y \
        wget openssl-devel cmake3

# Setup opencv and opencv-contrib source
RUN wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip && \
    unzip ${OPENCV_VERSION}.zip && \
    rm ${OPENCV_VERSION}.zip && \
    mv opencv-${OPENCV_VERSION} opencv && \
    wget https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip && \
    unzip ${OPENCV_VERSION}.zip && \
    rm ${OPENCV_VERSION}.zip && \
    mv opencv_contrib-${OPENCV_VERSION} opencv_contrib

# Build OpenCV
RUN cd opencv && mkdir build && cd build && \
    cmake3 \
    -D OPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D BUILD_SHARED_LIBS=OFF \
    -D ENABLE_CXX11=ON \
    -D BUILD_EXAMPLES=OFF \
    -D BUILD_DOCS=OFF \
    -D BUILD_PERF_TESTS=OFF \
    -D BUILD_TESTS=OFF \
    -D BUILD_JAVA=OFF \
    -D BUILD_opencv_app=OFF \
    -D BUILD_opencv_java_bindings_generator=OFF \
    -D BUILD_opencv_python_bindings_generator=OFF \
    -D BUILD_opencv_python_tests=OFF \
    -D BUILD_opencv_ts=OFF \
    -D BUILD_opencv_js=OFF \ 
    -D BUILD_opencv_bioinspired=OFF \
    -D BUILD_opencv_ccalib=OFF \
    -D BUILD_opencv_datasets=OFF \
    -D BUILD_opencv_dnn_objdetect=OFF \
    -D BUILD_opencv_dpm=OFF \
    -D BUILD_opencv_fuzzy=OFF \
    -D BUILD_opencv_gapi=OFF \
    -D BUILD_opencv_intensity_transform=OFF \
    -D BUILD_opencv_mcc=OFF \
    -D BUILD_opencv_rapid=OFF \
    -D BUILD_opencv_reg=OFF \
    -D BUILD_opencv_stereo=OFF \
    -D BUILD_opencv_structured_light=OFF \
    -D BUILD_opencv_surface_matching=OFF \
    -D BUILD_opencv_videostab=OFF \
    -D WITH_GSTREAMER=OFF \ 
    -D OPENCV_ENABLE_NONFREE=ON \
    .. && make -j8 && make install

# Download OpenCvSharp
RUN wget https://github.com/shimat/opencvsharp/archive/master.zip && \
    unzip master.zip && rm master.zip && \
    mv opencvsharp-master opencvsharp && \
    cd opencvsharp 

# Install the Extern lib.
RUN mkdir /opencvsharp/make && cd /opencvsharp/make && \
    cmake3 -D CMAKE_INSTALL_PREFIX=/opencvsharp/make /opencvsharp/src && \
    make -j && make install && \
    rm -rf /opencv && \
    rm -rf /opencv_contrib && \
    cp /opencvsharp/make/OpenCvSharpExtern/libOpenCvSharpExtern.so /usr/lib64/
#RUN ldd /artifacts/libOpenCvSharpExtern.so

# Test OpenCvSharpExtern
#RUN echo -e "\n\
#int core_Mat_sizeof(); \n\
#int main(){ \n\
#  int i = core_Mat_sizeof(); \n\
#  printf(\"sizeof(Mat) = %d\", i); \n\
#  return 0; \n\
#}" > /test.c && \
#    gcc -I./ -L. test.c -o test -lOpenCvSharpExtern && \
#    ./test && \
#    rm -f /test*

RUN rm -rf /opencvsharp
```

## Output:

```
paste your output
```

**Comment by AvenSun** [comment]
there's no need to build native OpenCvSharpExtern library
 building OpenCvSharp in .Net5 is all

**Comment by Lerseb** [comment]
Hi AvenSun,
Previously when using dotnetcore 3.1, I had to build my app image using a base image (opencvsharp_base which base image include dotnet 3.1) including all the opencv dependencies.
Do you mean it is possible to install a specific Nuget in my app project and just use the .Net5 microsoft image as base?
This would be awesome because the way I used to build it creates a huge image of almost 7GB.
It would be awesome if you could share the steps to do what you said.
Thanks

**Comment by AvenSun** [comment]
@Lerseb 
Of course, there's a quick way you can try
compile all you need in physical server or docker
after finished successfully,  just copy the must dependency ( *.so ) of libOpenCvSharpExtern to the new target,  
new docker or physical server with the same OS version is OK.
that's all !

**Comment by diamondbarcode** [comment]
@AvenSun i get opencvsharp from nuget it does not work on .net5. I use sample code from here in new solution use framework 4.8 work just fine but I do exactly something in .net5 the app is run but nothing happen .. like something disconnect some where
