### ISSUE TITLE
AsyncArray  support

### ISSUE THREAD

**Issue by AvenSun** [shimat/opencvsharp#1287]
Hi, @shimat 
generally we can get better performance when making DNN inferences asynchronously
It seems there's no asyncarray implementation in OpenCvSharp
Is there some plan for this feature?
[AsyncArray](https://docs.opencv.org/4.5.2/d4/d20/classcv_1_1AsyncArray.html#ab70c3efa65213c3a099d7fec44c4c8cc)
[forwardAsync](https://docs.opencv.org/4.5.2/db/d30/classcv_1_1dnn_1_1Net.html#a814890154ea9e10b132fec00b6f6ba30)
[DNN async demo](https://github.com/opencv/opencv/blob/61359a5bd05fc6f808644c7a1e73ca2e47e0e9fe/samples/dnn/object_detection.cpp#L223)

**Comment by goodtogood** [comment]
I came to similar problem
It should be great if OpenCvSharp supports this feature
