### ISSUE TITLE
Unity + OpenCVsharp3  UDP stream VideoCapture not opened

### ISSUE THREAD

**Issue by JetJaguar-PSX** [shimat/opencvsharp#1289]
# Summary of your issue
VideoCapture from UDP stream is not working.
cap.IsOpened() returns false.

# Environment

Windows10
Unity 2020.3.10f1 LTS
OpenCVsharp3-AnyCPU Version4.0.0

## Example code:
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using OpenCvSharp;
using UnityEngine.UI;

public class CameraCap : MonoBehaviour
{
    VideoCapture cap;
    Mat mat;
    Texture2D texture2D;

    void Start()
    {
        string address = "udp://127.0.0.1:11111";
        cap = new VideoCapture(address);
        if (!cap.IsOpened())
        {
            Debug.Log("cap isnt opened!");
        }
        mat = new Mat();
        texture2D = new Texture2D(cap.FrameWidth, cap.FrameHeight, TextureFormat.RGB24, false);
        this.gameObject.GetComponent<Renderer>().material.mainTexture = texture2D;
    }

    void Update()
    {
        if (cap.Read(mat))
        {
            texture2D.LoadImage(mat.ImEncode());
        }
    }

    private void OnDestroy()
    {
        cap.Dispose();
        cap = null;
    }
}
```

## Output:
No error message was outputted.

## What did you intend to be?
cap.IsOpened() return true.

**Comment by AvenSun** [comment]
for UDP stream you should  specify VideoCaptureAPIs.FFMPEG

`capture = new VideoCapture(address, VideoCaptureAPIs.FFMPEG)`

**Comment by s195056** [comment]
I tried that but the result was the same.
cap.IsOpened() return false.

**Comment by AvenSun** [comment]
firstly you'd better use `ffplay udp://127.0.0.1:11111` to test your stream is valid or not
if it's good , It might be suggested that the opencv native library you're using doesn't support this operation
you can try new version or building native library by youself.

**Comment by s195056** [comment]
The stream is valid, so I'll try new version.

**Comment by s195056** [comment]
I tried OpenCVsharp4.Windows, but cap.IsOpened() still return false.
