### ISSUE TITLE
How to merge videos with OpenCVSharp?

### ISSUE THREAD

**Issue by zydjohnHotmail** [shimat/opencvsharp#1294]
How to merge videos with OpenCVSharp?
Hello:
I want to know if I can use opencvsharp to merge some video clips?
For example: I have one video file named: 1.mp4, it has duration of 2 minutes.  And I can use ffmpeg to split this video file into 2 video clips:
C:\Videos\>ffmpeg -i 1.mp4 -ss 00:00 -to 01:00 1a.mp4
C:\Videos\>ffmpeg -i 1.mp4 -ss 01:00 -to 02:00 1b.mp4
I want to know how I can merge the 1a.mp4 and 1b.mp4 to make a new video file: merged.mp4
Please show me the code.
By the way, I am using Windows 10 (Version 21H1), my IDE is: Visual Studio 2019 (Version 16.10.3), I want to target on .Net 5.0 on X64 platform.
Thanks,

**Comment by sdcb** [comment]
Sounds like it's more suitable to do it in `ffmpeg` or `https://github.com/Ruslan-B/FFmpeg.AutoGen`
