### ISSUE TITLE
Inverse dft opencvsharp

### ISSUE THREAD

**Issue by ysmony** [shimat/opencvsharp#13]
Firstly I am new at here so I don't really know where I must wright my requestes. If I do something wrong, I am sorry. 

I have problems about opencvsharp inverse fft. I couldn't get the wright image after  inverse fft. I saw the DFT code here but there is nothing about inverse dft. Would you help me please?

The dft code is here. https://github.com/nobnak/OpenCvSharpForUnity/blob/master/OpencvSharp/OpenCvSharp.Test/Samples/DFT.cs

**Comment by TearsWindpipe** [comment]
That's a good example, but can somebody tell me why I got an error? The location of the error in Cv2. ImShow (" Spectrum Magnitude ", Spectrum) and Cv2 ImShow (" Reconstructed by Inverse DFT ", inverseTransform); Error: OpenCvSharp. OpenCVException: "DST. Data = = (uchar *) dst_ptr" help! Help! Help!
