### ISSUE TITLE
First use of OpenCVSharp in Visual Studio Express 2012 is getting an exception

### ISSUE THREAD

**Issue by GustavoEHennemann** [shimat/opencvsharp#130]
Hello people,
I just installed OpenCVSharp and I'm trying to make a very simple example, but I'm getting the error:
"An unhandled exception of type 'System.TypeInitializationException' occurred in OpenCVSharp.dll
Additional informaion: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception."
As I'm new in OpenCV an OpenCVSharp, I'm thinking I'm loosing something. I already looked for some tutorial or manual for begginers, but not found.
I setted the VS' target to Debug - x64 and x86, but no difference.
The refferences added are "OpenCvSharp.Blob.dll", "OpenCvSharp.Exensions.dll", "OpenCvSharp.CPlusPlus.dll", "OpenCvSharp.dll" and "OpenCvSharp.UserInterface.dll".
I'm using:
- OpenCvSharp-2.4.10-x64-20150820
- Windows 7 Ultimate 64bits SP1
- Visual Studio Express 2012 for Windows Desktop

The example code is:
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Windows.Forms;

using OpenCvSharp;
using OpenCvSharp.CPlusPlus;
using OpenCvSharp.Blob;
using OpenCvSharp.Extensions;
using OpenCvSharp.UserInterface;

namespace OpenCV_test
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (CvCapture cap = CvCapture.FromCamera( CaptureDevice.Any, 1))
            //using (CvCapture cap = CvCapture.FromCamera( 0 ))
            {
                while (true)
	        {
	            Bitmap bm = BitmapConverter.ToBitmap(cap.QueryFrame());
	            bm.SetResolution(pctCvWindow.Width, pctCvWindow.Height);
	            pctCvWindow.Image = bm;
	        }   //  */
            }
        }
    }
}
```
Any tip?

Thanks in advance

**Comment by VahidN** [comment]
`OpenCvSharp-2.4.10-x64-20150820` doesn't contain all of the required DLL's.
You need to install this package using NuGet:
```
PM> OpenCvSharp-AnyCPU
```
And then refer to [this sample](https://github.com/VahidN/OpenCVSharp-Samples/blob/78216a149f0ff62b6b59016f64538f3eaa7922fe/OpenCVSharpSample06WinForms/FrmMain.cs) to see how to use Camera with OpenCVSharp.

**Comment by GustavoEHennemann** [comment]
Hi VahidN,
Thanks gor your tip, but...

- I got NuGet for command line and I installed the OpenCvSharp-AnyCPU, so far so good.
- My code still throwing the same exception.
- Also I tried the example you refered, and I got this exception (in the line ```using (var capture = CvCapture.FromCamera(index: 0))``` ):

![vs2012_opencvsharp_error](https://cloud.githubusercontent.com/assets/14845391/10120602/5d1dde84-649a-11e5-9c44-3bfd32885017.png)

I think I'm not using the correct dll or I forgot to add something to the project, or something like that.
Do you have some very basic check list to start a OpenCVSharp project?

thanks again

**Comment by shimat** [comment]
Could you show me the inner exception of the thrown exception?

**Comment by GustavoEHennemann** [comment]
Is this?
![opencvsharp_innerexception](https://cloud.githubusercontent.com/assets/14845391/10120900/1698b272-64a9-11e5-9fdc-bd4d2a1a7ec6.png)

**Comment by VahidN** [comment]
Do you have VC++ runtimes installed?
![ocvdlls](https://cloud.githubusercontent.com/assets/766010/10121440/72a9a95a-64f8-11e5-8e0f-0aaebfbb59f9.png)

**Comment by GustavoEHennemann** [comment]
Yes,
I have installed "Visual C++ Redistributable for Visual Studio 2012 Update 4" version x64.

**Comment by shimat** [comment]
Does `opencv_core2410.dll` exist in `/dll/x64/` or in the same directory as your .exe file?

Can you find the build configuration of your VS project? (AnyCPU / x64 / x86)

**Comment by GustavoEHennemann** [comment]
So,
In my code, according to the exceptions, I copied the files opencv_core2410.dll, opencv_highgui2410.dll and opencv_imgproc2410.dll to my .exe's directory and the application starts to working... finally!  :-)

After that, I tried to add the following directories to systems's path:
- C:\OpenCvSharp-AnyCPU.2.4.10.20150820\NativeDlls\x64
- C:\OpenCvSharp-AnyCPU.2.4.10.20150820\NativeDlls\x86
But, make no difference.

I really have to copy this dlls to all of my applications?
How to distribute a final application with OpenCVSharp?

**Comment by shimat** [comment]
To distribute your OpenCvSharp application, I think you have to bundle all OpenCV DLL files to it.

After building your project, is there a `dll` folder in the .exe's directory?  The NuGet build config should copy all OpenCV DLLs into the `dll` folder automatically.
![explorer](https://cloud.githubusercontent.com/assets/4434824/10134005/43107eaa-661d-11e5-9662-aa6210e58213.png)

**Comment by GustavoEHennemann** [comment]
Hello Shimat,
In my project all the dll files are in the same directory as the exe file. There aren't a dll folder.

**Comment by shimat** [comment]
Your way is also OK. But your app may not work on x86 environment. The most simple solution is to build your project as not `AnyCPU` but `x86`. 

My way can support both x64 and x86. On x64 computers OpenCvSharp loads DLLs from `dll/x64/`. On x86 computers OpenCvSharp loads DLLs from `dll/x86/`.

**Comment by GustavoEHennemann** [comment]
How to do your way? Do you use some tool to build the application?

**Comment by shimat** [comment]
My way, the OpenCvSharp NuGet,  can automatically copy all OpenCV DLLs to `dll/*` folder. On your project it seems not to work for some reason.... :cry: 

To distribute your app, I think it is recommended to build your project as x86 and put all OpenCV's x86 DLL files in the same directory as the exe file.

**Comment by GustavoEHennemann** [comment]
NuGet is not work because is disabled (I'm using the command line version), but this is another issue.
I think my doubt is solved.
Thank you guys (shimat and VahidN) to share a little bit of your knowledge.
```
     __
    |  )
   /  /_____
  /   (_____)
(_  ( _____)
 \  (_  ___)
  \__(____)
```

**Comment by MrCypressBai** [comment]
@VahidN #10 
@shimat 
@yukoba 
hi,guys. I meet this question .In fact, i had try EmguCV, which also this question  happened,so i parper to use opencvSharp.well, some question hits me, that is what i never thought about it.
 this is my code:

`public Form1()
        {
            InitializeComponent();
            using (VideoCapture capture = new VideoCapture(-1))
            {
                int sleepTime = (int)Math.Round(1000 / capture.Fps);
               Mat image = new Mat();// Frame image buffer
              
                while (true)
                {
                    capture.Read(image); 
                    if (image.Empty())
                        break;
                    Bitmap bitmap = OpenCvSharp.Extensions.BitmapConverter.ToBitmap(image);
                    pictureBox1.Image = (bitmap);
                }
            }
        }`

**Comment by VahidN** [comment]
I have updated [my sample to use v3](https://github.com/VahidN/OpenCVSharp-Samples/blob/master/OpenCVSharpSample06WinForms/FrmMain.cs). It's tested.
