### ISSUE TITLE
.NET Core detection seems to need support .NET 5 or more

### ISSUE THREAD

**Issue by emaame** [shimat/opencvsharp#1301]
# Summary of your issue

`OpenCvSharp.OpenCvSharpException: 'Failed to find dll "OpenCvSharpExtern", for processor architecture AMD64.'` is thrown when create `Mat` at first time on .NET 5.
But it can ignore and it seems everything works fine.
I doubt [`WindowsLibraryLoader.cs#L110`](https://github.com/shimat/opencvsharp/blob/162c86036dc3c3076f18d2497c623acb845a7eb7/src/OpenCvSharp/Internal/PInvoke/WindowsLibraryLoader.cs#L110) misses to detect .NET 5 or more.

# Environment

- Visual Studio 2019 / .NET 5.0.8
- OpenCvSharp 4.5.3.20210725

## What did you intend to be?

I guess, .NET Core detection needs to support .NET 5 or more ([`WindowsLibraryLoader.cs#L110`](https://github.com/shimat/opencvsharp/blob/162c86036dc3c3076f18d2497c623acb845a7eb7/src/OpenCvSharp/Internal/PInvoke/WindowsLibraryLoader.cs#L110)).

```opencvsharp/src/OpenCvSharp/Internal/PInvoke/WindowsLibraryLoader.cs
            return RuntimeInformation.FrameworkDescription.StartsWith(".NET Core", StringComparison.Ordinal);
```

[`RuntimeInformation.FrameworkDescription`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.frameworkdescription?view=net-5.0) returns

- .NET 5 : ".NET 5.0.8"
- .NET 6 (VS2022 preview 2) : ".NET 6.0.0-preview.6.21352.12"

I cannot show right answer is but it may check with Regex like `@"^.NET (\d|Core)"` or reject "NET Framework"?

**Comment by shimat** [comment]
Thank you :+1:

Here seems to be a simple solution: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L24
