### ISSUE TITLE
Can RPI Zero be used with OpenCvSharp? If so, how?

### ISSUE THREAD

**Issue by Luk164** [shimat/opencvsharp#1309]
# Summary of your issue

I would like to use this library in conjunction with Raspberry PI Zero. Is this at all possible? And if so, can you provide instructions on how to do so?

# Environment

Device: RPI Zero (ARMv6)
OS: Raspbian

**Comment by TheBricktop** [comment]
You'd be better off using python opencv on rasperry pi zero or boofcv

**Comment by Luk164** [comment]
> 
> 
> You'd be better off using python opencv on rasperry pi zero or boofcv

I already am, but it is painfully slow and there are problems using multiple cameras at once.

**Comment by TheBricktop** [comment]
Well since opencvsharp is a opencv dll with c# wrapper it wont be any faster, rpi zero is probably not the best board for CV either way, you might wanna check some exotic boards like radxa zero or rockpi 4c they are pretty decent

**Comment by Luk164** [comment]
@TheBricktop Those sound pretty interesting, I will check them out. As to the other thing, I only need opencv to take two pictures using two USB cameras. Meanwhile I managed to make it work by invoking fswebcam utility in c# and dumping its output to a memoryStream which I can use for stuff. OpenCV is really quite overkill for me but I do not know any other usable library. My communication library is already in .netstandard2.0 so I hoped to reuse it.
