### ISSUE TITLE
Creating multi-dimensional matrices

### ISSUE THREAD

**Issue by AlexandreLaborde** [shimat/opencvsharp#1312]
Hi shimat!

I have a HDF5 file with an image stack of 10 ,480x480 images and they are all stored inside the same variable that is size 10x480x480. (uint8).

I can load this into memory using a HDF5 package but in order to do this I need to pre allocate the memory inside my program.

Is there any to create n-dimensional Mat ?
As a test, I tried `var x = new Mat(new int[] {10,30,20 }, MatType.CV_8UC1);`  based on the code in https://github.com/shimat/opencvsharp/blob/ea7c67ff0df7b0bc003b46b245a413c7830ffb16/src/OpenCvSharp/Modules/core/Mat/Mat.cs#L369 but it does not seem to work as ncols and nrows report -1.

I looked trough the examples you provide but I can't seem to find any example for this.

Let me know if can provided any more info.
Keep up the good work!

**Comment by shimat** [comment]
I think your code is correct. The behavior is by design.

https://github.com/opencv/opencv/blob/5aa7435d2537e677611390b530e31b3b204773a3/modules/core/include/opencv2/core/mat.hpp#L2107
```c++
    //! the number of rows and columns or (-1, -1) when the matrix has more than 2 dimensions
    int rows, cols;
```

You can use `Mat.Size(int dim)` to get the size of the matrix along its i-th dimension.

```c#
using var m = new Mat(new int[] {10,20,30}, MatType.CV_8UC1);
            
Assert.False(m.Empty());
Assert.Equal(3, m.Dims);
Assert.Equal(-1, m.Rows);
Assert.Equal(-1, m.Cols);
Assert.Equal(10, m.Size(0));
Assert.Equal(20, m.Size(1));
Assert.Equal(30, m.Size(2));
```

**Comment by AlexandreLaborde** [comment]
Thanks great news @shimat ! 
I was not really sure what the expected behavior would so I decided to ask you.
Which is the best/ most efficient  way to extract one of the images of the this stack? as in extract a MxN Mat out of a MxNxL Mat .

**Comment by shimat** [comment]
You can use SubMat + Reshape to do this.
https://stackoverflow.com/a/51938164

```c#
using var m = new Mat(new int[] { 20, 30, 40 }, MatType.CV_8UC1);

for (int i = 0; i < 20; i++)
{
    using var mi_3d = m.SubMat(new Range(i, i+1), Range.All, Range.All);
    using var mi = mi_3d.Reshape(0, mi_3d.Size(1), m0_3d.Size(2));
    //Assert.Equal(2, mi.Dims);
    //Assert.Equal(30, mi.Size(0));
    //Assert.Equal(40, mi.Size(1));

    ...
}
```

**Comment by feiyuhuahuo** [comment]
@shimat @AlexandreLaborde , Can I stack a group of images into one 3 dimensional matrix ? I want to read ten 512x512 images, and stack them into a (10, 512, 512) mat. Could this be achievable? I am new to OpenCVShaop, really thanks.
