### ISSUE TITLE
 Fail to run iot edge module in raspberry pi: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. 

### ISSUE THREAD

**Issue by mariusDing** [shimat/opencvsharp#1313]
# Summary of your issue
I had a Iot edge module which is using OpenCVSharp to get camera stream~
It works well in my win10 pc locally
But when I deploy the module to raspberry pi(arm32V7)~ it always show following error~!!!!!!!
Do I miss anything?
Github repo:https://github.com/mariusDing/IoTEdgeDiscovery/tree/main/IotEdgeModule1
![2021-09-03_01h34_50](https://user-images.githubusercontent.com/11885340/131874038-bb4f0ffa-4eb0-4002-9915-7560171b556e.png)

That's the nugget package using in the project
![image](https://user-images.githubusercontent.com/11885340/131874703-96830367-d53b-473a-8765-51bc2a6007f5.png)

That's the dockerfile use to build the container
![2021-09-03_01h36_58](https://user-images.githubusercontent.com/11885340/131874868-a0e69214-b2c1-46c9-bee3-28d9a478a542.png)

Check the file in the container which built raspberry pi doesn't have `OpenCvSharpExtern.dll`~ Don't know why
![2021-09-03_01h35_23](https://user-images.githubusercontent.com/11885340/131875553-ffca0723-4031-43a6-8f08-3bfea15c3fc7.png)

# Environment

Issue happening on raspberry pi4 

# What did you do when you faced the problem?

I don't know how to solve it

## Example code:

```
paste your core code
```
Github repo:https://github.com/mariusDing/IoTEdgeDiscovery/tree/main/IotEdgeModule1

## Output:

```
paste your output
```

## What did you intend to be?

Want to run a project which can get camera stream from  raspberry pi

**Comment by mariusDing** [comment]
Highly think maybe it's because the docker file that needs to install OpenCV

Can someone who makes it work help to share the dockfile?

**Comment by AvenSun** [comment]
If you would like to use OpenCvSharp on arm32
you have to build native library on your own
the library on nuget should be 64bit
you can check this via 
`file libOpenCvSharpExtern.so  (full path)`

**Comment by mariusDing** [comment]
Thanks @AvenSun 
Found a base image that can use directly~ 
`https://github.com/scienta-scientific/docker.peak-dotnet-opencv-deps/blob/master/BuildImageRaspbian/Dockerfile`

But the image is quite big~
