### ISSUE TITLE
Async VideoCapture (for GStreamer)

### ISSUE THREAD

**Issue by turowicz** [shimat/opencvsharp#1318]
@shimat would it be possible to have an async return in `VideoCapture.Read()`? Currently having a blocked thread for pulling frames is starting to become a problem in our code as we aim to target ARM devices.

**Comment by turowicz** [comment]
cc @ursanon

**Comment by shimat** [comment]
There is a way to wrap VideoCapture.Read with Task.Run or Task.FromResult, but doesn't this meet your requirements?
```c#
Task<Mat> task = Task.Run(() => capture.Read());

Task<Mat> task = Task.FromResult(capture.Read());
```

**Comment by turowicz** [comment]
@shimat that will occupy an entire thread for the time being until the Mat is returned. We are now testing the usage of GStreamerSharp instead of VideoCapture from OpenCvSharp.

**Comment by AvenSun** [comment]
actually you can build opencv with gstreamer on
then it's straight forward to using videocapture with gstreamer

**Comment by Ursanon** [comment]
Thanks for comment @AvenSun. We're using opencv + gst already.
Unfortunately calling [`VideoCapture.read()`](https://docs.opencv.org/4.5.0/d8/dfe/classcv_1_1VideoCapture.html#a473055e77dd7faa4d26d686226b292c1) is synchronous.

**Comment by turowicz** [comment]
> Thanks for comment @AvenSun. We're using opencv + gst already.
> Unfortunately calling [`VideoCapture.read()`](https://docs.opencv.org/4.5.0/d8/dfe/classcv_1_1VideoCapture.html#a473055e77dd7faa4d26d686226b292c1) is synchronous.

Meaning that it occupies an entire thread in order to wait for an incoming frame. At this point we are trying to squeeze maxiumum performance from our code and this is a very important part to get thorugh.

**Comment by turowicz** [comment]
Solved with using GST#
