### ISSUE TITLE
Request sample Camera calibration for Version 3.0 please.

### ISSUE THREAD

**Issue by bprawit** [shimat/opencvsharp#132]
I'm trying to use the OpenCV  Camera calibration in a C# project via OpenCVSharp (OpenCvSharp3-AnyCPU Version 3.0.0.20150823 running in Visual Studio 2015 and installed via NuGet). But I couldn't to convert demo code from Version 2 to Version 3. This my source code:
```cs
static void CalCalibration(Mat[] images) {
            
            Size imageSize = images[0].Size();
            Size patternSize = new Size(9, 6);
            Size regionSize = new Size(4, 4);
            Size rectangleSize = new Size(20f, 20f);

            var imagePoints = new List<MatOfPoint2d>();
            var objectPoints = new List<MatOfPoint3d>();

            var objectPoint = new List<Point3d>();
            for (int i = 0; i < patternSize.Height; i++) {
                for (int j = 0; j < patternSize.Width; j++) {
                    objectPoint.Add(new Point3d(j * rectangleSize.Width,
                        i * rectangleSize.Height, 0.0F));
                }
            }

            for (int i = 0; i < images.Length; i++) {

                Mat currentMat = images[i];

                MatOfPoint2d corners = new MatOfPoint2d();
                bool isFoundChessboard = Cv2.FindChessboardCorners(currentMat, patternSize, OutputArray.Create(corners));
                if (!isFoundChessboard) {
                    continue;
                }

                bool isCornerSubpix = Cv2.Find4QuadCornerSubpix(currentMat, corners, regionSize);
                if (!isCornerSubpix) {
                    continue;
                }

                imagePoints.Add(corners);
                MatOfPoint3d objectPointMat = new MatOfPoint3d(patternSize.Width * patternSize.Height, 1, 
                    objectPoint.ToArray());
                objectPoints.Add(objectPointMat);
            }

            var cameraMatrix = new double[3, 3];
            var distCoeffs = new double[8];
            Vec3d[] rvecs, tvecs;
            
            Cv2.CalibrateCamera(objectPoints, imagePoints, imageSize, cameraMatrix, distCoeffs, out rvecs, out tvecs);
        }
```

However I'm running into an unhandled exception of type 'System.ArgumentException' occurred in OpenCvSharp.dll

Additional information: Too short array.Length

Could you demo camera calibration on OpenCVSharp V3 please.

Sorry for my English.

**Comment by TheMetalMonkey** [comment]
I have got this to work, I didn't use the MatOfPoint2d, the exception looks to be some conversion of this.

There are 2 ways, that I got working:
One is to use a List<IEnumeratable<Point2f>> and similar for Point3f Note it should be Point2f not Point2d - I submitted a fix which is now in the latest git version.

The second is to use the
The IEnumerable<Mat> objectPoints, version works in older releases.
To build the list of Mat[] I made this function.

   public static Mat[] ToMatPoint3f(IEnumerable<IEnumerable<Point3f>> input)
        {
            List<Mat> output = new List<Mat>();
            foreach (var item in input)
            {
                Point3f[] points = item.ToArray();
                Mat m = new Mat(points.Length, 1, MatType.CV_32FC3, points);
                output.Add(m);
            }
            return output.ToArray();
        }

**Comment by TheMetalMonkey** [comment]
I have made an additional fix in the MatOfT osed by MatOfPoint2f and MatOfPoint3f.
Your sample code now runs (just change Point2d and Point3d to Point2f and Point3f) - you will have to wait until shimat merges the fix into the version you use.

**Comment by bprawit** [comment]
Thank you @TheMetalMonkey , @shimat
