### ISSUE TITLE
missing mask option in OpenCvSharp.Cv2.MatchTemplate()

### ISSUE THREAD

**Issue by duronrulez** [shimat/opencvsharp#133]
Hello,

since OpenCV v3.0 MatchTemplate has one more option which is for masking of the template. But this option is missing in the bundle of OpenCvSharp (i used NuGet to install it).
http://docs.opencv.org/3.0.0/df/dfb/group__imgproc__object.html#ga586ebfb0a7fb604b35a23d85391329be

Is it a bug or i am doing something wrong?

**Comment by shimat** [comment]
Thanks! :+1:  The `mask` parameter is added in the latest commit. 
https://github.com/shimat/opencvsharp/commit/3c1860414f2bf6a3fcf530cfed2d0c90356ddfe2

**Comment by duronrulez** [comment]
Aweseme, thanks!
