### ISSUE TITLE
Cannot call InitUndistortMap with the right parameters

### ISSUE THREAD

**Issue by Soulskater** [shimat/opencvsharp#134]
I've the calibration results matrices, and i'm trying to call the InitUndistortMap, so passing the intrinsic and distortion matrices, but my question how to initialize the mapx, and mapy CvArr output params, because those are not out parameters so they cannot be null?

Thanks,
Gabor

**Comment by shimat** [comment]
please try the following code.
```c#
CvMat mapx = new CvMat(src.Height, src.Width, MatrixType.F32C1);
CvMat mapy = new CvMat(src.Height, src.Width, MatrixType.F32C1);
Cv.InitUndistortMap(intrinsic, distortion, mapx, mapy);
```

If you use the new API `OpenCvSharp.CPlusPlus.Cv2.InitUndistortRectifyMap`, you can pass empty `Mat` to mapx and mapy.

**Comment by Soulskater** [comment]
Thanks for your help, it works!
