### ISSUE TITLE
MatOfPoint2f missing or renamed in OpenCVSharp4

### ISSUE THREAD

**Issue by Dcruise546** [shimat/opencvsharp#1343]
# Summary of your issue
Upgraded from previously used OpenCvSharp3-AnyCPU to OpenCvSharp4. Everything seems to work from my previous project except the implementation of 'MatOfPoint2f' and 'MatOfPoint2f'

After upgrading the compiler throws the following error:

'The type or namespace name 'MatOfPoint2f' could not be found (are you missing a using directive or an assemble reference'

Is the MatOfPoint2f implementation moved to a new assembly? if so, I could not find the exact one.

# Environment
.NET Framework 4.7.2
Windows 10 x64 bit

# What did you do when you faced the problem?
Upgraded from deprecated version of OpenCvSharp to a newer variant

**Comment by shimat** [comment]
Please see https://github.com/shimat/opencvsharp/issues/1029.

**Comment by Dcruise546** [comment]
Sorry for duplicating! Thanks for the fast response @shimat
