### ISSUE TITLE
NuGet packages are copying native dlls incorrectly with .net 6

### ISSUE THREAD

**Issue by awardle** [shimat/opencvsharp#1349]
# Summary of your issue

If you target a project to .net 6 and include the windows runtime package (OpenCvSharp4.runtime.win), extra native dlls are copied to the build directory. This does not happen in .net 5

The build copies the `dll` folder as well as the `runtimes` folder. It should only copy the `runtimes` folder

# Environment

Windows 10 with .net 6 SDK

# Example

## Project targeting .net 5
![image](https://user-images.githubusercontent.com/464713/145996747-5fbca721-5d11-4221-82b2-84a86739efde.png)

## Project targeting .net 6
![image](https://user-images.githubusercontent.com/464713/145996861-ceacc7c1-9658-4265-80ee-24344f9a5442.png)

# Possible issue
`opencvsharp/nuget/OpenCvSharp4.runtime.win.props` includes the following checks

```xml
<ItemGroup Condition="!$(TargetFramework.Contains('netstandard')) And !$(TargetFramework.Contains('netcoreapp')) And !$(TargetFramework.Contains('net5'))">
		<Content Include="$(NativeDlls)\win-x86\native\OpenCvSharpExtern.dll">
			<Link>dll\x86\OpenCvSharpExtern.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="$(NativeDlls)\win-x86\native\opencv_videoio_ffmpeg453.dll">
			<Link>dll\x86\opencv_videoio_ffmpeg453.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
</ItemGroup>
```

This does not check if the target framework contains net6 so copies the dll folder.

**Comment by shimat** [comment]
Thank you. I'm not sure how to write the condition🤔 
```xml
<ItemGroup Condition="$(TargetFramework.Contains('net2')) Or $(TargetFramework.Contains('net3')) Or $(TargetFramework.Contains('net4'))">
```

**Comment by shimat** [comment]
With your suggested code, I get warning NU1701 when TargetFramework=net5.0 or netcoreapp. The nupkg always seems to be installed as not net5.0 but net461. I don't know what the solution is.
