### ISSUE TITLE
PCA.Mean returns EigenValues instead of Mean

### ISSUE THREAD

**Issue by ayb4btu** [shimat/opencvsharp#135]
I'm using PCA in OpenCVSharp (OpenCvSharp3-AnyCPU Version 3.0.0.20150823 running in Visual Studio 2015 and installed via NuGet), but PCA.Mean is returning what appears to be the wrong result.

If I have three points `(2,1), (2,2), (2,3)` that I perform PCA on, I would expect the mean to be `(2,2)`, but PCA.Mean gives me `(0.6666667, 0)`, which is the same as PCA.Eigenvalues.

Here is the code that I'm using:

    Mat input = new Mat(3,2, MatType.CV_32FC1);
    input.Set(0,0, 2f);
    input.Set(0,1, 1f);
    input.Set(1,0, 2f);
    input.Set(1,1, 2f);
    input.Set(2,0, 2f);
    input.Set(2,1, 3f);

    Mat mean = new Mat();
    PCA pcaResult = new PCA(input, mean, PCA.Flags.DataAsRow);

    float[] meanArray = new float[pcaResult.Mean.Height];
    pcaResult.Mean.GetArray(0,0, meanArray);

    float[] eigenvalues = new float[pcaResult.Eigenvalues.Height];
    pcaResult.Eigenvalues.GetArray(0, 0, eigenvalues);

`meanArray` is the same as `eigenvalues`.

**Update**
I found the issue, PCA.cs (found at this url: https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/modules/core/PCA.cs) has the same code for both Eigenvalues and Mean:

        public Mat Eigenvalues
        {
            get
            {
                if(disposed)
                    throw new ObjectDisposedException("PCA");
                IntPtr ret = NativeMethods.core_PCA_eigenvalues(ptr);
                return new Mat(ret);
            }
        }

        public Mat Mean
        {
            get
            {
                if (disposed)
                    throw new ObjectDisposedException("PCA");
                IntPtr ret = NativeMethods.core_PCA_eigenvalues(ptr);
                return new Mat(ret);
            }
        }

**Comment by shimat** [comment]
Thank you for your report! :+1:  
This bug is fixed by  https://github.com/shimat/opencvsharp/commit/d9760d9852b187e06f99f42708e8d8a427ab5f06
