### ISSUE TITLE
Error using OpenCvSharp4.runtime.wasm

### ISSUE THREAD

**Issue by bnemetchek2** [shimat/opencvsharp#1350]
# Summary of your issue

This may be my inexperience with trying to use the wasm version of OpenCvSharp4.  Maybe I need to manually add the runtime assembly manually to the index.html?  I could find not instructions or samples of how this should be set up

# Environment
nuget: 
OpenCvSharp4 4.5.3.20211207
OpenCvSharp4.runtime.wasm 4.5.3.20211203

client (WebAssembly) Blazor in .NET 6

# What did you do when you faced the problem?

searched thru this project's issues

## Example code:

```
var mat = new Mat();
```

## Output:

```
OpenCvSharpExtern
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.

```

an OpenCV Mat should be instantiated

**Comment by shimat** [comment]
I have created a sample that runs OpenCvSharp with Blazor WebAssembly. https://github.com/shimat/opencvsharp_blazor_sample
However, I'm still very new to Blazor WebAssembly, so it doesn't work as well as I would like. The OpenCvSharp.wasm package is experimental.

**Comment by bnemetchek2** [comment]
Thank you very much for this example!  I am able to get some of the basic features working.  I realize it's early days so although I get errors on a lot of calls, I shall wait patiently as this evolves.  I noticed that when errors occur, they are not caught in a catch statement but just dumps out something out like "Uncaught 67449680"  But, this wasm effort seems quite exciting and I look forward to using it as it improves.
