### ISSUE TITLE
Disposable objects not disposed

### ISSUE THREAD

**Issue by avendel** [shimat/opencvsharp#1351]
# Summary of your issue

The implicit operators converting e.g. ``Mat`` to ``InputArray`` and ``OutputArray`` make it very easy to create ``DisposableObject`` instances with finalizers that will be left to the garbage collector to call, with all the overhead that implies.

In some cases this can be dealt with by the caller, but in e.g. https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/core/Mat/Mat_CvMethods.cs, there are methods creating these instances without disposing them or leaving them for the caller to dispose.

# Environment

Windows, but this is not an environment-specific problem.

# What did you do when you faced the problem?

Here is an example where the caller can do something about it:

## Example code:

```csharp
using var mat = new Mat();
var res = Cv2.CountNonZero(mat);
```

In the example above, an implicit cast operator will create an ``InputArray`` instance, which might not be obvious to the caller. It can be handled like this:

```csharp
using var mat = new Mat();
using var input = InputArray.Create(mat);
var res = Cv2.CountNonZero(input);
```

However, a lot of methods in https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/core/Mat/Mat_CvMethods.cs implicitly creates these instances without disposing them. Here is an example:

```csharp
public Mat CvtColor(ColorConversionCodes code, int dstCn = 0)
{
    var dst = new Mat();
    Cv2.CvtColor(this, dst, code, dstCn);
    return dst;
}
```

It will create one `InputArray` for the first argument to the Cv2 method, and one `OutputArray` for the second argument. There are a lot of similar methods. I think they could all be fixed according to this pattern:

```csharp
public Mat CvtColor(ColorConversionCodes code, int dstCn = 0)
{
    var dst = new Mat();
    using var input = InputArray.Create(this);
    using var output = OutputArray.Create(this);
    Cv2.CvtColor(input, output, code, dstCn);
    return dst;
}
```

## Output:

```
// Did not remove this part, according to instructions in the issue template.
// The problem is detected using a memory profiler that reports objects queued for finalization.
```

## What did you intend to be?

All disposable objects disposed and no finalizers called.

**Comment by YoniSmolin** [comment]
My team is using OpenCvSharp in a C# computer vision pipeline. We ran into this issue when performing memory profiling.

@shimat - the issue has been opened almost two years ago. I'm wondering what is the barrier to fixing it. Is it considered low priority, or is it a matter not enough contributors to do the work?
