### ISSUE TITLE
End of support for System.Drawing.Common on linux

### ISSUE THREAD

**Issue by schalke046-1** [shimat/opencvsharp#1352]
# Summary of your issue
System.Drawing.Common was designed to be a thin wrapper over Windows technologies, its cross-platform implementation is subpar.
(https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)

Could you please have a look at that?
Because we currently enabled the using of System.Drawing.Common on Linux, but we have a bad feeling about using that solution.

Thanks,
Sascha

# Environment
Docker / Linux usage

**Comment by sdcb** [comment]
I would prefer a new package that drops the Bitmap support @shimat
