### ISSUE TITLE
Suggest not using <NativeDlls> in .props file

### ISSUE THREAD

**Issue by sdcb** [shimat/opencvsharp#1360]
Because `<NativeDlls>` looks pretty generic, so many project might be using this name, if one project include 2 NuGet packages that include native library which using `<NativeDlls>` defined in their `prop` file, these 2 `<NativeDlls>` **will** conflicted(and it happens in my project): 

https://github.com/shimat/opencvsharp/blob/51fee5e/nuget/OpenCvSharp4.runtime.win.props#L3

Maybe using a more specific word here will better, like `<OpenCvSharp4ExternalNativeDlls>`

**Comment by shimat** [comment]
Thank you 👍
