### ISSUE TITLE
Is it possible port to .net MAUI?

### ISSUE THREAD

**Issue by Mozart71** [shimat/opencvsharp#1363]
I've been try use OpenCvSharp on .net maui projects but it only work on desktop apps. So, i wan't to know if you can do runtime work on all platfrom Android,iOS,Windows and Mac OS?

Thanks

**Comment by GreenShadeZhang** [comment]
The official version of MAUI has been released, whether this proposal can be possible, if it can be compatible with MAUI multi-platform is really good.

**Comment by mzy666888** [comment]
I think so

**Comment by zxopink** [comment]
Couldn't make it work on Android using MAUI, guess it's because there's no xamarin version

**Comment by GreenShadeZhang** [comment]
Have you ever successfully invoked OpenCVSharp using MAUI on a Mac? For example, the chip of the Apple M2
