### ISSUE TITLE
OCR on cyrillic text

### ISSUE THREAD

**Issue by Blightbuster** [shimat/opencvsharp#1364]
# Summary of your issue

Using OCR on cyrillic text yields a empty string even with correct model and white list

# Environment

OpenCVSharp 4.5.3.20211228

# What did you do when you faced the problem?

- Verified that it works with english model on latin characters
- Tested the image from the example below in the console with the same model and got this result:
"Дульный тормоз-компенсатор Зенит "ДТК-1" 762х39 и 5.45х59 для АК"


## Example code:

![image](https://user-images.githubusercontent.com/24388294/147729662-5abbf027-cf3d-43bc-bc62-9333ff89e02a.png)
```
var whiteList = "АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя";
var model = OCRTesseract.Create("models", "rus", whiteList, 3, 7);
string text = "";
model.Run(img, out text, out _, out _, out _, ComponentLevels.TextLine);
if (text == "") Console.WriteLine("Empty");
```

**Comment by Blightbuster** [comment]
Could this perhaps be an issue with how the wrapper handles the conversion of string encodings? (wild guess)

**Comment by Blightbuster** [comment]
I also tried using the characters as in the `desired_characters` [file](https://github.com/tesseract-ocr/langdata_lstm/blob/main/rus/desired_characters).
`0123456789ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё`
Unfortunately with the same result...

**Comment by Blightbuster** [comment]
Perhaps related to this:
https://stackoverflow.com/a/9983550

**Comment by Blightbuster** [comment]
To circumvent this issue, the tesseract package on nuget can be used as it does not have this issue.

**Comment by n0099** [comment]
https://github.com/shimat/opencvsharp/issues/873#issuecomment-1458868153
