### ISSUE TITLE
Cv2.ImRead is not execute

### ISSUE THREAD

**Issue by wbw1990** [shimat/opencvsharp#1365]
# Summary of your issue

# Environment

in the docker 

Dockerfile :
FROM shimat/ubuntu18-dotnetcore3.1-opencv4.5.0:20201030
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
#COPY ["OpencvSharp/OpencvTest.csproj", "OpencvTest/"]
COPY ./OpencvTest.csproj ./
RUN dotnet restore ./OpencvTest.csproj
COPY . .
#WORKDIR "/src/OpencvTest"
WORKDIR /src
#RUN dotnet build "OpencvTest.csproj" -c Release -o /app/build
RUN dotnet build OpencvTest.csproj -c Debug -o /app

FROM build AS publish
#RUN dotnet publish "OpencvTest.csproj" -c Release -o /app/publish
RUN dotnet publish OpencvTest.csproj -c Debug -o /app

FROM base AS final
WORKDIR /app
#COPY --from=publish /app/publish .
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "OpencvTest.dll"]

# What did you do when you faced the problem?
 
Cv2.ImRead is not execute

## Example code:

```
   try
            {
                Console.WriteLine("---------start--" + DateTime.Now.ToString() + "---------");
                
                string img = "bali.png";
                Console.WriteLine("---------img name--" +img + "---------");
                var cv = Cv2.ImRead(img);
                // Mat src = new Mat(img, ImreadModes.Grayscale);
                Console.WriteLine(cv.ToString());
                Console.WriteLine("---------end--" + DateTime.Now.ToString() +"  ---------");
                
            }
            catch (Exception e)
            {
                Console.WriteLine("--------- err ---------");
                Console.WriteLine(e.Message);
            }
```

## Output:

```
 wbw$ docker run 3f1e96ee43b2
---------start--12/30/2021 13:32:56---------
---------img name--bali.png---------
 wbw$ 
```

**Comment by silverlight7** [comment]
Which expert can help? Thank you very much！！

**Comment by mpolicki** [comment]
OpenCV is notorious for failing silently when it can't open a file, and OpenCVSharp inherits that behavior. Try checking that the file exists with `System.IO.File.Exists`.

**Comment by silverlight7** [comment]
> 

thank you， the file is exists.

**Comment by sh0622-kim** [comment]
Are there any unusual logs written to Linux system kernel log right after calling Cv2.ImRead()?
