### ISSUE TITLE
Can't customize to add CUDA support

### ISSUE THREAD

**Issue by frankabbruzzese** [shimat/opencvsharp#1370]
# Summary of your issue

According to your instructions, I recompiled https://github.com/shimat/opencv_files, adding CUDA support to the CMAKE. However, this forced me to target vs 2019 in the CMake, instead of VS 2022, since CUDA, doesn't support VS 2022, yet.

I created the release files and copied the folder in the opencvsharp solution folder, ensuring that the folder tree matches the references in the OpenCvSharpExtern project. 

Now when I compile OpenCvSharpExtern it is able to find the include files, but then I get a linker error saying it is not able to find all opencv libraries.

To be sure there was no wrong path I copied the LibPath in the OpenCvSharpExtern project in windows explorer (replacing $SolutionFolder) with the actual value, the paths actually reference the right library.

So, it appears that there is some other problem, but the linker return me a LNK1181 error, meaning it is not able to find the 'IlmImf.lib' library. If there were a binary compatibility problem I should get a different message. So I am really stuck!

# Environment

Windows 10 +. VS 2022 for opencvsharp and VS 2019 for https://github.com/shimat/opencv_files

## Output:	

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'IlmImf.lib'	OpenCvSharpExtern	C:\src\OpenCvSharp\src\OpenCvSharpExtern\LINK	1
```

## What did you intend to be?
no errors, of course

**Comment by dabenpb** [comment]
Did you solve this issue?  I have been attempting the same thing.

**Comment by frankabbruzzese** [comment]
No, I am waiting for the VS 2022 versions.

**Comment by CobraCalle** [comment]
hello,

I have two questions realted to this topic:
1. I was able to build opencv with vuda-support under vs2022... so why are you saying that it does not support 2022?
2. @shimat says "opencvsharp" does not support cuda, you have to customize the native bindings by yourself"... does any know if he means that we realy only have to rebuild opencv with cuda support? or does he mean that even if you have a cuda enabled version of opencv, that opencvsharp will still not work?

thanks

carl

**Comment by frankabbruzzese** [comment]
@fabsenet No, it is just that NVIDIA has not supported VS 2022, yet.
