### ISSUE TITLE
V4.5.5.20211231 where are ToMat methods and Extensions?

### ISSUE THREAD

**Issue by LiorBanai** [shimat/opencvsharp#1371]
I was trying to upgrade to V4.5.5.20211231 but have compilation errors.
BitmapConverter is not found nor is ToMat method.

What should I do?

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp/pull/1356
Please use https://www.nuget.org/packages/OpenCvSharp4.Extensions additionally.

**Comment by dooferorg** [comment]
I did not find this extension package initially when looking on nuget in order to try and solve this myself, I wonder if that happened to other people as well. I think it gets pushed down the list somehow.

Still, with that package it all works fine. Thanks!
