### ISSUE TITLE
NuGet for newly added wechat_qrcode?

### ISSUE THREAD

**Issue by sdcb** [shimat/opencvsharp#1380]
I see https://github.com/shimat/opencvsharp/pull/1375 is merged, this is super cool, will it create a `nuget` package soon?

**Comment by shimat** [comment]
After adding wechat_qrcode, one GitHub Action is not working properly, and I cannot publish the new NuGet package without fixing it.
https://github.com/shimat/opencvsharp/runs/4988054483?check_suite_focus=true

Frankly speaking, I think that some pure C# libraries (e.g. ZXing.NET) are sufficient for QR code detection/recognition functions without relying on OpenCV. I've been struggling a lot lately to keep OpenCvSharp working on many platforms, and I'm reluctant to make changes that will make it harder to build. If OpenCvSharp runs on Windows and Ubuntu, that's good enough for my personal use.

If it is difficult to solve this problem, I am sorry to say that I may remove the wechat_qrcode feature.

**Comment by sdcb** [comment]
Actually ZXing.NET is not as good as wechat_qrcode in performance and accuracy.

**Comment by theb0rg** [comment]
I think we need to bump the version of cmake to make the build succeed. Maybe use 3.1-focal (20.04) instead of 3.1-bionic (18.04)?
