### ISSUE TITLE
OpenCvSharp.Extension moved in OpenCvSharp4?

### ISSUE THREAD

**Issue by Dcruise546** [shimat/opencvsharp#1385]
# Summary of your issue

Trying to port the code from OpenCvSharp3 to OpenCvSharp4. OpenCvSharp.Extensions namespace is not available from the OpenCvSharp4 NuGet package.

# Environment
Visual Studio 2019
Windows 10
.Net framework version 4.7.2

I guess this has to be a dumb mistake from my side. I also tried installing other NuGet packages related to OpenCvSharp4

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp/issues/1371
