### ISSUE TITLE
Template matching with mask results in unhandled exception in OpenCVSharp.dll

### ISSUE THREAD

**Issue by duronrulez** [shimat/opencvsharp#139]
Hello, when i try to use the masking in matchtemplate i get:
"An unhandled exception of type 'OpenCvSharp.OpenCVException' occurred in OpenCvSharp.dll"

            Bitmap template = new Bitmap("template.png");
            Bitmap source = new Bitmap("source.png");
            Bitmap mask = new Bitmap("mask.png");

            OpenCvSharp.Mat t = BitmapConverter.ToMat(template);
            OpenCvSharp.Mat s = BitmapConverter.ToMat(source);

            OpenCvSharp.Mat tGray = new OpenCvSharp.Mat(s.Size(), OpenCvSharp.MatType.CV_8U);
            OpenCvSharp.Cv2.CvtColor(t, tGray, OpenCvSharp.ColorConversionCodes.BGR2GRAY);

            OpenCvSharp.Mat sGray = new OpenCvSharp.Mat(s.Size(), OpenCvSharp.MatType.CV_8U);
            OpenCvSharp.Cv2.CvtColor(s, sGray, OpenCvSharp.ColorConversionCodes.BGR2GRAY);
            OpenCvSharp.Mat r = new OpenCvSharp.Mat(s.Size(), OpenCvSharp.MatType.CV_8U);

            OpenCvSharp.Mat tMask = BitmapConverter.ToMat(mask);
            OpenCvSharp.Cv2.CvtColor(tMask, tMask, OpenCvSharp.ColorConversionCodes.BGR2GRAY);

            //Exception: An unhandled exception of type 'OpenCvSharp.OpenCVException' occurred in OpenCvSharp.dll
            OpenCvSharp.Cv2.MatchTemplate(sGray, tGray, r, OpenCvSharp.TemplateMatchModes.CCoeffNormed, tMask);

This is the code i use and i've attached the 3 images.

![mask](https://cloud.githubusercontent.com/assets/981088/10585080/679cb69e-769e-11e5-9fdc-14098596d5d7.png)
![source](https://cloud.githubusercontent.com/assets/981088/10585082/67a0f1be-769e-11e5-865b-d5d88d271644.png)
![template](https://cloud.githubusercontent.com/assets/981088/10585081/67a08d0a-769e-11e5-8340-c42f45bc9c5e.png)

I am using the newest nuget build from 19.10.2015

**Comment by shimat** [comment]
I found that the current OpenCV implementation of matchTemplate with mask does not support `CCoeffNormed` method.
It supports only `CV_TM_SQDIFF` and `CV_TM_CCORR_NORMED`.

https://github.com/Itseez/opencv/blob/master/modules/imgproc/src/templmatch.cpp#L894

**Comment by duronrulez** [comment]
Oh, sorry, ill take another look and close it down if everything is fine.

**Comment by shimat** [comment]
You can see status code of native opencv error by managed Exception's `Status` property.
In this case it is a `OpenCvSharp.ErrorCode.StsNotImplemented`.

You can also see position of error by `Line`, `FuncName` and `FileName` properties. 
These are everithing the wrapper can provide... :disappointed_relieved:

**Comment by duronrulez** [comment]
Ah, thank you again for enlightening me :)
