### ISSUE TITLE
Missing MacOS/aarch64 bindings

### ISSUE THREAD

**Issue by zmarlon** [shimat/opencvsharp#1409]
Hello,
the macOS aarch64 natives are missing.

Are you planning to fix this? :)

**Comment by AvenSun** [comment]
the attached file I built works well on Jetson (aarch64) , but it's not the latest version.
[libOpenCvSharpExtern ](https://github.com/shimat/opencvsharp/files/6489049/libOpenCvSharpExtern.zip)
you can have a try.

**Comment by zmarlon** [comment]
Thank you very much :) I also compiled it by myself, working pretty fine. I think It would be nice to add this at NuGet package for everyone to download :)

**Comment by krjw-eyev** [comment]
@zmarlon could you share what exactly you did?

**Comment by tonieichelkraut** [comment]
Hi, @shimat I would also love to use the nuget package. Any chance, that you provide that as well? Thanx!
