### ISSUE TITLE
can not get any non-empty frame

### ISSUE THREAD

**Issue by Michael-Lee-Wang** [shimat/opencvsharp#1412]
# Summary of your issue

can not get any non-empty frame

# Environment

windows 7 Ultimate  x64   Service Pack 1
netcore3.1 LTS + winform
[C++ 2015-2022 package](https://aka.ms/vs/17/release/vc_redist.x64.exe) installed
Framework4.8/4.6.1 installed
nugetpackage  OpenCvSharp4.Extensions    OpenCvSharp4.runtime.win

# What did you do when you faced the problem?

- I added a usb camera device, the device is open, but I got empty frames(mat) always, and videoWriter is false at x64(any cpu work well)
- At my develope machine(win10 + vs2022), my code work well, so What special requirements for opencv on windows7

## Example code:

```
Task.Factory.StartNew(() =>
            {
                int index = 0;
                videoCapture = new VideoCapture(index);
                videoCapture.Set(VideoCaptureProperties.FrameWidth, 1920);
                videoCapture.Set(VideoCaptureProperties.FrameHeight, 1080);
                videoCapture.Set(VideoCaptureProperties.Fps, 25);
                if (!videoCapture.IsOpened()) return;
                string path = Path.Combine(AppContext.BaseDirectory, "temp", "out.avi");
                videoWriter = new VideoWriter(path, VideoWriter.FourCC(@"XVID"), videoCapture.Fps, new OpenCvSharp.Size(videoCapture.FrameWidth, videoCapture.FrameHeight), true);

                camera_running = true;
                while (camera_running)
                {
                    Mat camera = new Mat();
                    videoCapture.Read(camera);
                    if (camera.Empty()) continue;    // always empty
                    Mat image = new Mat();
                    camera.CopyTo(image);
                    videoWriter.Write(camera);

                    camera.Release();
                }
            }).ConfigureAwait(false);
```

## Output:
No any exeception

## What did you intend to be?
I want to know what is causeing this issue, and how to fix it.

Thanks!

**Comment by zhou123aw** [comment]
I have encountered the same problem as you. Have you solved it?

**Comment by zhou123aw** [comment]
@Michael-Lee-Wang
