### ISSUE TITLE
Incorrect [Flags] attributes

### ISSUE THREAD

**Issue by jgilbert2017** [shimat/opencvsharp#1415]
Numerous types seem to be incorrectly marked as `[Flags]` whereas they are non-flags enums.  `[Flags]` is meant to indicate that the enum values can be logically ORed together.  This can confuse autocomplete / smart editors.

    [Flags]
    public enum MorphTypes

    [Flags]
    public enum GemmFlags

**Comment by shimat** [comment]
Thank you!
