### ISSUE TITLE
How to dump vec or Mat fo file (p.ex. yaml)?

### ISSUE THREAD

**Issue by andife** [shimat/opencvsharp#1420]
# Summary of your issue

I wonder how I can dump a vector or mat into a file. Does anyone have an example for this?

**Comment by shimat** [comment]
(1)
```c#
using var fs = new FileStorage("foo.yml", FileStorage.Modes.Write);
fs.Write("name", mat);
```
[https://github.com/shimat/opencvsharp/blob/6f22fd5024e16b65c66bd3e06666c1989351135d/test/OpenCvSharp.Tests/core/FileStorageTest.cs#L69]()

(2)
```c#
var csvText = mat.Dump(FormatType.CSV);
System.IO.File.WriteAllText("foo.csv", csvText);
```

**Comment by andife** [comment]
Thank you!
