### ISSUE TITLE
Nuget version at 4.5.5, last version at github 4.5.3

### ISSUE THREAD

**Issue by andife** [shimat/opencvsharp#1423]
# Summary of your issue

I just realized that the Nuget version is at opencv 4.5.5, whereas the last version at github is 4.5.3?
Therefore I wonder if nuget is really 4.5.5?

**Comment by shimat** [comment]
Sorry, I forgot to create a Git(Hub) release tag for 4.5.5. Only the NuGet package for version 4.5.5 was released.
