### ISSUE TITLE
Test Run Aborted when running tests on linux

### ISSUE THREAD

**Issue by ptasev** [shimat/opencvsharp#1426]
# Summary of your issue
I noticed in your ubuntu builds often times the test run will be aborted due to some crash. I am experiencing the same thing with a docker build I have created for Oracle Linux 8. Calling the following command often results in the error:
```
dotnet test OpenCvSharp.Tests.csproj -c Release -f net6.0 --runtime ol.8-x64 --logger "trx;LogFileName=test-results.trx" < /dev/null

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
```

# Environment
Docker Oracle Linux 8

# What did you do when you faced the problem?
I ended up running the dotnet test command with the `--blame-crash` option. Using this I was able to get a crash dump. I unfortunately don't know how to make sense of this data. It seems like the crash happens due to this test:
```
The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
The test running when the crash occurred:
OpenCvSharp.Tests.ImgProc.ConnectedComponentsTest.Run

This test may, or may not be the source of the crash.
```

I opened the dmp file in WinDbg, and saw the following call stack:
![image](https://user-images.githubusercontent.com/23424044/171937641-14fd047c-e130-473f-8e90-3d7f59f0acd1.png)

Note that if you run all the other tests while ignoring the one that blame says is the cause of the crash, then the problem no longer appears. I think that confirms that this test is the issue. I filtered out this test by calling dotnet test with the argument `--filter FullyQualifiedName\!=OpenCvSharp.Tests.ImgProc.ConnectedComponentsTest.Run`.

I don't know how to proceed from here, but hopefully this helps to understand the problem.

**Comment by shimat** [comment]
Thank you for looking into the problem in detail. I was having it too.

I have just updated this project to OpenCV 4.6.0 and so far the error does not occur. I will give it a few more days to see how it goes.

**Comment by ptasev** [comment]
Looks like the problem has gone away with 4.6.0 in my docker builds as well. Thanks!
