### ISSUE TITLE
Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found.

### ISSUE THREAD

**Issue by brspurri** [shimat/opencvsharp#143]
This looks to be a great library/wrapper, and I can setup and run the `console` app samples with no problem. However, I am trying to use this in a `WebApiApplication` that calls a custom library DLL, and am running into:

```
Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found.
```

My project is structured such that the WebApiApplication calls a DLL form another project I created (and this is where the **OpenCVSharp3** calls happen), so I have installed `OpenCVSharp3-AnyCPU` on both projects (`MyWebApiProject` and `MyLibraryProject`). I am using the NuGet install method, for `OpenCVSharp3-AnyCPU` (so OpenCV 3.0, as of the October 19, 2015 push to NuGet).

When I build and run the project, my bin directory(s) look like:

```
**MyWebApiProject**
Bin
│
├───dll
│   │
│   ├───x86
│   │   ├───msvcp120.dll
│   │   ├───msvcr120.dll
│   │   ├───opencv_ffmpeg300_64.dll
│   │   ├───opencv_world300.dll
│   │   └───OpenCvSharpExtern.dll
│   │
│   └───x64
│       ├───msvcp120.dll
│       ├───msvcr120.dll
│       ├───opencv_ffmpeg300_64.dll
│       ├───opencv_world300.dll
│       └───OpenCvSharpExtern.dll 
│   
├───OpenCvSharp.dll
├───OpenCvSharp.Blob.dll
├───OpenCvSharp.Extensions.dll
├───OpenCvSharp.UserInterface.dll
│
├───MyLibraryProject.dll
│
└───Additional DLL and binary files 

**MyLibraryProject**
Bin
│
├───dll
│   │
│   ├───x86
│   │   ├───msvcp120.dll
│   │   ├───msvcr120.dll
│   │   ├───opencv_ffmpeg300_64.dll
│   │   ├───opencv_world300.dll
│   │   └───OpenCvSharpExtern.dll
│   │
│   └───x64
│       ├───msvcp120.dll
│       ├───msvcr120.dll
│       ├───opencv_ffmpeg300_64.dll
│       ├───opencv_world300.dll
│       └───OpenCvSharpExtern.dll
│
├───OpenCvSharp.dll
├───OpenCvSharp.Blob.dll
├───OpenCvSharp.Extensions.dll
├───OpenCvSharp.UserInterface.dll
│
└───Additional DLL and binary files 
```

So to me, everything looks like it is in place.

However, the first time I call into an **OpenCVSharp3** method (such as: `Mat image = Mat.FromImageData(buffer, ImreadModes.Color);`), I get the `Unable to load DLL 'OpenCvSharpExtern' error.

Does anyone have any idea how to use `OpenCVSharp3` in a web application? Or could it be that my custom DLL is messing things up?

Any help would be greatly appreciated. I'm at a loss here.

Also, if it matters, I am using **Visual Studio 2015** on **.Net-Framework 4.5**.
~Brett

**Comment by shimat** [comment]
I have ever used OpenCvSharp in some ASP.NET MVC5 WebApi projects.
I also bother about this problem. :confused: 

Please try to copy the native DLL files (`opencv_*.dll`, `msvc*.dll` and `OpenCvSharpExtern.dll`) from `Bin\dll\[x86 or x64]\` to `Bin\`, or add the location of native DLLs to the `PATH` environment variable.

**Comment by brspurri** [comment]
After several months, I finally got back to trying this out.

Unfortunately, this approach isn't working for me. I have copied:
```
msvcp120.dll
msvcr120.dll
opencv_ffmpeg300_64.dll
opencv_world300.dll
OpenCvSharpExtern.dll
```

to `\Bin`, and I am still seeing the error. Has anyone tried this? It's simple enough to reproduce.

**Comment by BjornMelgaard** [comment]
Have the same problem, given project structure generated by Monodevelop and NuGet by default

**Comment by shimat** [comment]
Did you try to configure the `PATH` variable?

**Comment by BjornMelgaard** [comment]
yes, i try 
```
% PATH=$PATH:.
% ls
dll   opencv.exe               OpenCvSharp.Blob.dll        OpenCvSharpExtern.dll
msvcp120.dll  opencv.exe.mdb           OpenCvSharp.dll             OpenCvSharp.UserInterface.dll
msvcr120.dll  opencv_ffmpeg310_64.dll  OpenCvSharp.Extensions.dll  opencv_world310.dll
% mono opencv.exe 
OpenCvSharpExtern
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: OpenCvSharpExtern
  at (wrapper managed-to-native) OpenCvSharp.NativeMethods:core_Mat_sizeof ()
  at OpenCvSharp.NativeMethods.TryPInvoke () <0x413db2a0 + 0x0007b> in <filename unknown>:0 

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: OpenCvSharpExtern
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: OpenCvSharpExtern
  at (wrapper managed-to-native) OpenCvSharp.NativeMethods:core_Mat_sizeof ()
  at OpenCvSharp.NativeMethods.TryPInvoke () <0x413db2a0 + 0x0007b> in <filename unknown>:0  ---> System.DllNotFoundException: OpenCvSharpExtern
  at (wrapper managed-to-native) OpenCvSharp.NativeMethods:core_Mat_sizeof ()
  at OpenCvSharp.NativeMethods.TryPInvoke () <0x413db2a0 + 0x0007b> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at OpenCvSharp.NativeMethods.TryPInvoke () <0x413db2a0 + 0x0013b> in <filename unknown>:0 
  at OpenCvSharp.NativeMethods..cctor () <0x413c8500 + 0x00193> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at OpenCvSharp.VideoCapture..ctor (System.String fileName) <0x413c81f0 + 0x00053> in <filename unknown>:0 
  at opencv.Program.Main () <0x413c7e10 + 0x00047> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: OpenCvSharpExtern
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: OpenCvSharpExtern
  at (wrapper managed-to-native) OpenCvSharp.NativeMethods:core_Mat_sizeof ()
  at OpenCvSharp.NativeMethods.TryPInvoke () <0x413db2a0 + 0x0007b> in <filename unknown>:0  ---> System.DllNotFoundException: OpenCvSharpExtern
  at (wrapper managed-to-native) OpenCvSharp.NativeMethods:core_Mat_sizeof ()
  at OpenCvSharp.NativeMethods.TryPInvoke () <0x413db2a0 + 0x0007b> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at OpenCvSharp.NativeMethods.TryPInvoke () <0x413db2a0 + 0x0013b> in <filename unknown>:0 
  at OpenCvSharp.NativeMethods..cctor () <0x413c8500 + 0x00193> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at OpenCvSharp.VideoCapture..ctor (System.String fileName) <0x413c81f0 + 0x00053> in <filename unknown>:0 
  at opencv.Program.Main () <0x413c7e10 + 0x00047> in <filename unknown>:0
```

**Comment by shimat** [comment]
Your console looks like Bash.  Isn't your OS Windows?  or mingw?

**Comment by BjornMelgaard** [comment]
No, it`s archlinux
Clue: I tried to play video with VideoCapture on Windows (Visual Studio, code from wiki, opencvsharp was installed from Nuget, project structure is the same) and program simply exit without any error until I copy libraries from **Bin/dll/x64** to **Bin**, suppose problem was in opencv_ffmpeg.dll

**Comment by BjornMelgaard** [comment]
In new project even coping don't help
[source](https://dropmefiles.com/wdU6i)

**Comment by fedorkov** [comment]
`OpenCvSharpExtern` is a native library, you have to compile it as described [here](https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Unix#how-to-use-cplusplus).

I compiled it, but still get the same error. I tried to run it in debug mode: `MONO_LOG_LEVEL=debug mono test.exe`, and got [this output](http://pastebin.com/raw/AmyCSkqb) with an interesting line in it:
```
Mono: DllImport error loading library 'libOpenCvSharpExtern.so': './libOpenCvSharpExtern.so: undefined symbol: _ZTIN2cv16ParallelLoopBodyE'.
```
Any help would be greatly appreciated.

**Comment by Portekoi** [comment]
I have the same issue. My project is working in command project but not in MVC Web Project.

Any ideas?

**Comment by brunsgaard** [comment]
I do not know if this helps any of you, but here is an example running OpenCvSharp in a windows container environment. We saw the same Error message and solved it by adding missing `dll`s.
https://github.com/brunsgaard/OpenCVSharp-docker-example

**Comment by hard25670559** [comment]
You can try this one.
`VideoCapture capture = VideoCapture.FromFile("Your file path");`

Holp it helps.

**Comment by komcat** [comment]
Working for me is to copy OpenCvSharpExtern.dll to debug folder.

\Documents\Visual Studio 2017\Projects\emgucv1\emgucv1\bin\Debug * put here

**Comment by titicruz** [comment]
I Got the same error and installed from NuGet "opencvsharp3-AnyCPU" and it removed the problem for me

**Comment by sajjad-z** [comment]
> I have ever used OpenCvSharp in some ASP.NET MVC5 WebApi projects.
> I also bother about this problem. 😕
> 
> Please try to copy the native DLL files (`opencv_*.dll`, `msvc*.dll` and `OpenCvSharpExtern.dll`) from `Bin\dll\[x86 or x64]\` to `Bin\`, or add the location of native DLLs to the `PATH` environment variable.

it fix my MVC project : |

**Comment by GraphSam** [comment]
I am facing the same problem by referencing OpenCvSharp version OpenCvSharp-v4.4.0-20200917\ManagedLib\net461 the binaries OpenCvSharp.dll, OpenCvSharp.Blop.dll and OpenCvSharp.Extensions.dll into my Project built for x64, off course the same problem for x86 and AnyCPU. 

Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

   at OpenCvSharp.NativeMethods.imgcodecs_imread(String fileName, Int32 flags, IntPtr& returnValue)
   at OpenCvSharp.Mat..ctor(String fileName, ImreadModes flags)

Do you have any solution for it?
Could you post the needed files? …. There are as well missing binaries in your build folder such as OpenCvSharp.CPlusPlus.dll and OpenCvSharp.UserInterface.dll
