### ISSUE TITLE
question ColorMomentHash

### ISSUE THREAD

**Issue by kerwinxu** [shimat/opencvsharp#1435]
# Summary of your issue
public override void Compute(
	InputArray inputArr,
	OutputArray outputArr
)
outputArr
Type: [OpenCvSharp.OutputArray](https://docs.nuspatial.xyz/OpenCvSharp/html/99bf1533-7e83-69d2-0c44-691f9635954d.htm)
42 hash values with type CV_64F(double)
Excuse me ，
the bytes of size is (42 * 64 = 2688 ) bytes ?
but :
```c#
 Mat mat = new Mat(@"2022-06-19-10-09-8176.jpg");
 Mat mat2 = new Mat();
 var hashfun = ColorMomentHash.Create();
 hashfun.Compute(mat, mat2);
 byte[] bs = mat2.ToBytes();
 Console.WriteLine("字节长度:" + bs.Length.ToString());
```
result = 69 bytes ,  why ?

# Environment

Write your environment.

# What did you do when you faced the problem?

Write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
The test code below may help you.
https://github.com/shimat/opencvsharp/blob/master/test/OpenCvSharp.Tests/img_hash/ColorMomentHashTest.cs

```c#
using Mat mat = new Mat(@"2022-06-19-10-09-8176.jpg");
using Mat mat2 = new Mat();
using var hashfun = ColorMomentHash.Create();
hashfun.Compute(mat, mat2);

mat2.GetArray(out double[] hashValues);
Console.WriteLine("Length: {0}", hashValues.Length); // 42
```

**Comment by kerwinxu** [comment]
> 
win7 , net 3.5, OpenCvSharp3-AnyCPU 
I found the following , 
var hash = new Mat<**double**>()
but in my code , an error was generated ，
I write the following,
var hash = new Mat(new Size(1,42), MatType.CV_64FC1)

The Rows is ok .
The Cols is ok .
but the data is not ok , 
I don't have the ToArraymethod here.
I use the following method .
hash.ToBytes()
hash.ToMemoryStream().ToArray()
but the number of byte is 69

**Comment by shimat** [comment]
You should not use ToBytes, since ToBytes is an alias for ImEncode, which returns the PNG-encoded result of its Mat data.

**Comment by kerwinxu** [comment]
> You should not use ToBytes, since ToBytes is an alias for ImEncode, which returns the PNG-encoded result of its Mat data.

Thank you . i use the following .
`
 double[] dbl = new double[42];
 hash.GetArray(0, 0, dbl);
`
