### ISSUE TITLE
Cv2.CountNonZero throws OpenCvSharp.OpenCVException 'cn == 1'

### ISSUE THREAD

**Issue by matthewpetch** [shimat/opencvsharp#1445]
# Summary of your issue

Tried to use Cv2.CountNonZero to see if the frame is black (as that's what happens when a camera is in use by another application already)

# Environment

Windows 10
VS 2022
.NET Framework 4.6.1
OpenCvSharp 4.6.0.20220608

# What did you do when you faced the problem?

Called Cv2.CountNonZero and passed my current camera frame to it when using the camera in another application first

For what it's worth, .Empty() doesn't work here either

## Example code:

```
while (_capture.Read(frameMat))
{
    if (frameMat.Empty())
    {
        Cv2.PutText(frameMat, "EMPTY", new OpenCvSharp.Point(320, 200), HersheyFonts.HersheyScriptSimplex, 1, Scalar.Red);
    }
    if (Cv2.CountNonZero(frameMat) == 0)
    {
        Cv2.PutText(frameMat, "NOTHING", new OpenCvSharp.Point(320, 240), HersheyFonts.HersheyScriptSimplex, 1, Scalar.Red);
    }
```

## Output:

```
OpenCvSharp.OpenCVException 'cn == 1'  at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1675_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.core_countNonZero(IntPtr src, Int32& returnValue)
   at OpenCvSharp.Cv2.CountNonZero(InputArray mtx)
```

## What did you intend to be?

Returns 0

**Comment by shimat** [comment]
If `frameMat` is a color image, `CountNonZero` is designed to fail.

https://docs.opencv.org/3.4/d2/de8/group__core__array.html#gaa4b89393263bb4d604e0fe5986723914

> **Parameters**
> 　　src | single-channel array.

Please try converting `frameMat` to a grayscale image using the CvtColor method.

```c#
using var grayFrameMat = new Mat();
Cv2.CvtColor(frameMat, grayFrameMat, ColorConversionCodes.BGR2GRAY);

Console.WriteLine(frameMat.Channels()); // 3
Console.WriteLine(grayFrameMat.Channels()); // 1

if (Cv2.CountNonZero(grayFrameMat) == 0)
{
    ...
```
