### ISSUE TITLE
Runtime issue in Linux

### ISSUE THREAD

**Issue by Robinbr21** [shimat/opencvsharp#1461]
is there a global Runtime for linux os
i only saw runtime for ubuntu 18 and 16

if any know please commant

**Comment by dsoronda** [comment]
I opened similar issue here : https://github.com/shimat/opencvsharp/issues/1448

**Comment by PKloren** [comment]
When using linux docker images, I've build both opencv and opencvsharp on a custom image. In my .net core app I then use the OpenCVSharp4.runtime.ubuntu.18.04-x64 together with the OpenCvSharp4 core package to build. This works fine. The base images I use to build my image are the mcr.microsoft.com/dotnet/sdk:6.0-focal (during build) and mcr.microsoft.com/dotnet/aspnet:6.0-focal (runtime).
