### ISSUE TITLE
Which packages do I need to install?

### ISSUE THREAD

**Issue by rpowell6** [shimat/opencvsharp#1473]
# Summary of your issue

I am looking for a replacement for the ASP.Net System.Drawing namespace.

# Environment

The project I have inherited runs on  Ubuntu/Docker/NGINX in production; however, I am using Windows/IIS for development purposes.

# What did you do when you faced the problem?

Which opencvsharp packages do I need to install?

## Example code:

```
n/a
```

## Output:

```
n/a
```

**Comment by shimat** [comment]
I recommend ImageSharp as a replacement for System.Drawing. 
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action
