### ISSUE TITLE
Runtime issue in MacOS Monterey

### ISSUE THREAD

**Issue by dubovskymarek** [shimat/opencvsharp#1474]
# Summary of your issue

Following exception occurs on calling function from OpenCV:

{System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libOpenCvSharpExtern, 0x0001): tried: 'libOpenCvSharpExtern' (no such file), '/usr/local/lib/libOpenCvSharpExtern' (no such file), '/usr/lib/libOpenCvSharpExtern' (no such file), '/Users/all/Projects/OpenCVTest2/OpenCVTest2/bin/Debug/netcoreapp3.1/libOpenCvSharpExtern' (no such file)
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.ExceptionHandler.RegisterExceptionCallback()
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()}

# Environment
MacOS Monterey Version 12.4
Mac mini (Later 2014)

# What did you do when you faced the problem?
Always occurs on launch app.

## Example code:

```
using System;
using OpenCvSharp;

class Program
{
    static void Main()
    {
        try
        {
            using var src = new Mat("/path_to_directory/sample_image.png", ImreadModes.Grayscale);
            using var dst = new Mat();

            Cv2.Canny(src, dst, 50, 200);
            using (new Window("src image", src))
            using (new Window("dst image", dst))
            {
                Cv2.WaitKey();
            }
        }
        catch(Exception e)
        {
            Console.WriteLine("------EXCEPTION-------");
            Console.WriteLine(e.ToString());
        }
    }
}

```

## Output:

```
{System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libOpenCvSharpExtern, 0x0001): tried: 'libOpenCvSharpExtern' (no such file), '/usr/local/lib/libOpenCvSharpExtern' (no such file), '/usr/lib/libOpenCvSharpExtern' (no such file), '/Users/all/Projects/OpenCVTest2/OpenCVTest2/bin/Debug/netcoreapp3.1/libOpenCvSharpExtern' (no such file)
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.ExceptionHandler.RegisterExceptionCallback()
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()}
```

## Possible causes

I spent a lot of time finding out the cause, and found the following possible causes:

First problem is that libOpenCvSharpExtern is originally placed inside directory
"<project_directory>/bin/Debug/runtimes/osx-x64/native/libOpenCvSharpExtern.dylib"
but app is trying load from path
"<project_directory>/bin/Debug/libOpenCvSharpExtern" .

Second problem is many problematic dependencies from libOpenCvSharpExtern dylib. I explored all dylib dependencies by otool and all dependencies are not exist. For example OpenCV contains dependency to freetype library that is not installed in MacOS or many other libraries are the same problem. 
all dependencies from libOpenCvSharpExtern are in bellow list:

python3 /Users/All/Desktop/otool_recursive.py /Users/all/Projects/OpenCVTest2/OpenCVTest2/bin/Debug/netcoreapp3.1/runtimes/osx-x64/native/libOpenCvSharpExtern.dylib
/Users/all/Projects/OpenCVTest2/OpenCVTest2/bin/Debug/netcoreapp3.1/runtimes/osx-x64/native/libOpenCvSharpExtern.dylib
@rpath/libOpenCvSharpExtern.dylib
/usr/local/opt/freetype/lib/libfreetype.6.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/local/opt/freetype/lib/libfreetype.6.dylib (No such file or directory)
/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib (No such file or directory)
/usr/local/opt/tesseract/lib/libtesseract.5.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/local/opt/tesseract/lib/libtesseract.5.dylib (No such file or directory)
/usr/lib/libarchive.2.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/libarchive.2.dylib (No such file or directory)
/usr/lib/libcurl.4.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/libcurl.4.dylib (No such file or directory)
/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (No such file or directory)
/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (No such file or directory)
/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation (No such file or directory)
/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (No such file or directory)
/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (No such file or directory)
/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (No such file or directory)
/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (No such file or directory)
/usr/lib/libiconv.2.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/libiconv.2.dylib (No such file or directory)
/usr/lib/libSystem.B.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/libSystem.B.dylib (No such file or directory)
/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (No such file or directory)
/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (No such file or directory)
/usr/lib/libc++.1.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/libc++.1.dylib (No such file or directory)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (No such file or directory)
/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (No such file or directory)
/usr/lib/libobjc.A.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /usr/lib/libobjc.A.dylib (No such file or directory)

**Comment by Y2KPRABU** [comment]
I also have same issue

**Comment by gx56q** [comment]
Same for me on macos 13.0.1
Looks like there is no runtime for macos greater than 10

**Comment by animaonline** [comment]
Any updates on this?
