### ISSUE TITLE
WeChatQRCode recognizes image QR codes, the CPU and memory usage increases significantly

### ISSUE THREAD

**Issue by woaiwojiabinge** [shimat/opencvsharp#1483]
In Windows system, when WeChatQRCode is used to identify the QR code on the picture, a small number of pictures will cause a large increase in the CPU and memory usage of the machine, and the value will not be returned for a long time.

The required pictures are as follows。

![微信图片_20221003174816](https://user-images.githubusercontent.com/2289880/193763746-302a0167-4b60-4b27-b0b7-3a55991adc20.jpg)

**Comment by woaiwojiabinge** [comment]
![image](https://user-images.githubusercontent.com/2289880/193764094-f17283f9-11ab-4d86-b36c-dae50e208bc7.png)

**Comment by woaiwojiabinge** [comment]
Very few pictures will do this, most pictures will be normal. It will cause the thread to be continuously occupied, and the machine CPU and memory will be heavily occupied.

**Comment by woaiwojiabinge** [comment]
opencvsharp version is 4.6.0.20220608

**Comment by sdcb** [comment]
it seems you don't Dispose the instance of WeChatQRCode?
