### ISSUE TITLE
SubMat's operator problem

### ISSUE THREAD

**Issue by jjack000** [shimat/opencvsharp#1484]
# Summary of your issue

# Environment

Windows 11

# What did you do when you faced the problem?

SubMat's operator Add, Substract, +, - ... doesn't work.
but setTo works well

## Example code:

```
var test = new Mat(1, 10, MatType.CV_8UC1, 50);
using (var t2 = test.SubMat(new Rect(0, 0, 5, 1)))
{
// this code doesn't work.
    t2.Subtract(20);
    Console.WriteLine(test.Dump());

// this code works well
    t2.SetTo(30);
    Console.WriteLine(test.Dump());
}
```

## Output:

```
[ 50,  50,  50,  50,  50,  50,  50,  50,  50,  50]
[ 30,  30,  30,  30,  30,  50,  50,  50,  50,  50]
```

## What did you intend to be?
c++ works followings
```
int Test()
{
    Mat mat(1, 10, CV_8UC1);
    mat.setTo(50);
    Mat sub1(mat, { 0, 0, 5, 1 });
    sub1 -= 20;
    cv::print(mat);
    return 0;
}

```
Result
```
[ 30,  30,  30,  30,  30,  50,  50,  50,  50,  50]
```

**Comment by shimat** [comment]
`SetTo` is a method that destructively changes Mat itself, while `Subtract` is not.

```c#
var newMat = mat.Subtract(...);
```

`sub1 -= 20;` in C++ is not the same as `mat.Subtract(20);` in OpenCvSharp. It is equivalent to `mat = mat.Subtract(20);`.

> (In OpenCvSharp, it is preferable to use `using var mat2 = mat.Subtract(20);` to ensure disposing.)

**Comment by jjack000** [comment]
What I say is not Subtract Method but SubMat.

see my test codes.

### Code
```cs
var test = new Mat(1, 10, MatType.CV_8UC1, 50);
test -= 20;
Console.WriteLine($"Normal mat works {test.Dump()}"); // It works well. all elements in test 30
var t2 = new Mat(test, new Rect(0, 0, 5, 1));
t2 -= 20;
// It doesn't work. The first 5 elements will be set 10.  but all elelments keep 30
Console.WriteLine($"Sub mat works {test.Dump()}"); 
```

### Result
Normal mat works [ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30]
Sub mat works [ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30] => It shoud be [ ***10,  10,  10,  10,  10***,  30,  30,  30,  30,  30]

**Comment by jjack000** [comment]
I think this problem occurs because c# does not support += operator overloading.
It can be solved in the following way, but too many memory copies occur.

### Code
```cs
var test = new Mat(1, 10, MatType.CV_8UC1, 50);
test -= 20;
Console.WriteLine($"Normal mat works {test.Dump()}");
Mat t2 = test.SubMat(new Rect(0, 0, 5, 1));
t2.Subtract(20).ToMat().CopyTo(t2);
Console.WriteLine($"Sub mat works {test.Dump()}");
```
### Result
Normal mat works [ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30]
Sub mat works [ 10,  10,  10,  10,  10,  30,  30,  30,  30,  30]

I decided to make and use the following expansion function.

```cs
unsafe public static void SubtractBy(this Mat mat, byte b, Rect r)
{
    mat.SubMat(r).ForEachAsByte((v, p) =>
    {
        *v -= b;
    });
}

var test = new Mat(1, 10, MatType.CV_8UC1, 50);
test -= 20;
Console.WriteLine($"Normal mat works {test.Dump()}");
test.SubtractBy(20, new Rect(0, 0, 5, 1));
Console.WriteLine($"Sub mat works {test.Dump()}");
```
This code works well.

Normal mat works [ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30]
Sub mat works [ 10,  10,  10,  10,  10,  30,  30,  30,  30,  30]

I think there is a need for a warning that the operation on SubMat may not work properly.
