### ISSUE TITLE
publish my project using vs2022, But run failed on Linux platform 

### ISSUE THREAD

**Issue by zuixiaosanlang** [shimat/opencvsharp#1489]
![image](https://user-images.githubusercontent.com/20105627/197732595-102dc48d-fb80-4d35-a1a2-72a3395ae57d.png)

windows run well. 
But run failed on Linux platform: 
       Exception: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception

what should i do on Linux/windows platform.

thanks

**Comment by Moreno-Borsalino** [comment]
I have the same problem. Hope someone answer with a good solution

**Comment by GF-Huang** [comment]
Same issue for win-x64.

**Comment by GF-Huang** [comment]
I found that change to .NET 6 from .NET 7 solve this issue.
