### ISSUE TITLE
arm runtime nuget package include wrong so lib.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [shimat/opencvsharp#1497]
# Summary of your issue

This package include the x64 so lib.

# Environment

ubuntu aarch64

**Comment by vnetb** [comment]
see #1263

ffmpeg
https://github.com/vnetb/opencvsharp/actions/runs/2976652832

gstreamer
https://github.com/vnetb/opencvsharp/actions/runs/2976652830

**Comment by OaimIsGnay** [comment]
> see #1263
> 
> ffmpeg https://github.com/vnetb/opencvsharp/actions/runs/2976652832
> 
> gstreamer https://github.com/vnetb/opencvsharp/actions/runs/2976652830

I use the so file you provided.
No. 1. I didn't find it at first, but I installed it .
No. 2. I don't know where to install it .

<img width="439" alt="image" src="https://user-images.githubusercontent.com/58240619/204944845-90a4178e-139e-40b9-88f8-3ca58ba5853a.png">

**Comment by vnetb** [comment]
1. https://github.com/vnetb/opencvsharp/blob/cp_main/docker/linux-arm64/Dockerfile#L33

`apt-get install  libtesseract-dev `

2. https://github.com/vnetb/opencvsharp/blob/cp_main/docker/linux-arm64/Dockerfile#L23

`apt-get install  libdc1394-22-dev `

$ ldd libOpenCvSharpExtern.so | grep dc1394
        libdc1394.so.22 => /lib/aarch64-linux-gnu/libdc1394.so.22
