### ISSUE TITLE
Can't capture video from a webcam

### ISSUE THREAD

**Issue by teddy108** [shimat/opencvsharp#150]
Hi,
I tried to run the "Capturing Video" sample with videoCapture set to
new VideoCapture(-1); 
to receive the video stream from the notebook built in camera.

However, the line
capture.Read(image);
throws the following exception:
"Unknown/unsupported array type"

I'm using openCvSharp3, Windows 7, 64 bit.

Does anybody know what is causing this isssue?

Thank you

**Comment by shimat** [comment]
please see #142 :bow:

**Comment by teddy108** [comment]
Thanks, it works!
