### ISSUE TITLE
Camera does not open in .NET 6 WPF

### ISSUE THREAD

**Issue by dca00** [shimat/opencvsharp#1508]
Porting a .NET 4.8 Winforms app that uses OpenCVSharp4 to WPF. Both now use the same nuget package 4.0.20220628.
The same code that opens camera #0 in Winforms 4.8 does not open the camera in WPF 6.0. 

`VideoCapture.Open(0, VideoCaptureApis.ANY);`

Has no effect. The camera light stays off, and the captured frame is empty.

What is the path to migrating to .NET 6?

**Comment by alatriste-lee** [comment]
x86 same asking，x64 and any are ok

4.10.0.20240616

**Comment by dca00** [comment]
And this was closed because... Complete the sentence. Is this fixed? Is this not going to be fixed?
