### ISSUE TITLE
CvBlobs RenderBlob broke?

### ISSUE THREAD

**Issue by fdncred** [shimat/opencvsharp#151]
Why can't I get RenderBlob from CvBlobs to render with only one of the Enums?

This does not work and gives an exception about the value not being in the dictionary.
```csharp
    CvBlobs cvBlobs = new CvBlobs(bitonal);
    Mat rend = bitonal.CvtColor(ColorConversionCodes.GRAY2BGR);;
    cvBlobs.RenderBlobs(bitonal, rend, RenderBlobsMode.Color);
```
This works
```csharp
    CvBlobs cvBlobs = new CvBlobs(bitonal);
    Mat rend = bitonal.CvtColor(ColorConversionCodes.GRAY2BGR);;
    cvBlobs.RenderBlobs(bitonal, rend, (RenderBlobsMode)0x001f);
```
EDIT: I take it back 0x001f doesn't work either.  It just uses the default and doesn't complain about it.

**Comment by shimat** [comment]
Sorry for the late reply. The program works for me... :confused: 
Can you show me the detailed exception information?

```c#
var src = new Mat("shapes.png", ImreadModes.GrayScale);
var bin = src.Threshold(0, 255, ThresholdTypes.Otsu);
var view = bin.CvtColor(ColorConversionCodes.GRAY2BGR);

var blobs = new CvBlobs(bin);
blobs.RenderBlobs(bin, view, (RenderBlobsMode)0x001f);
Window.ShowImages(bin, view);
```

shapes.png
![shapes](https://cloud.githubusercontent.com/assets/4434824/11168602/f4f88798-8bd9-11e5-952c-72e73d0f3c5a.png)

**Comment by fdncred** [comment]
Issue 1:
My output is different than yours.  I did a git put and ran the sandbox app without any changes and this is the resulting two windows.
![out1](https://cloud.githubusercontent.com/assets/343840/11219243/0545d4f2-8d1f-11e5-98b5-ddd38274e9e2.png)

Issue 2:
The point is that we should be able to call it like this:
```csharp
cvBlobs.RenderBlobs(bitonal, rend, RenderBlobsMode.Angle);
```
and not have to do this:
```csharp
blobs.RenderBlobs(bin, view, (RenderBlobsMode)0x008f);
```

When I call RenderBlobs with RenderBlobsMode.Angle or RenderBlobsMode.Angle|RenderBlobMode.BoundingBox I get the exception mentioned above.

Issue 3:
Also, isn't your image wrong.  You are trying to draw blobs in color and everything is gray.

What am I missing?

**Comment by shimat** [comment]
My attached file is not a RenderBlob result but a source image.

Thank you for the information. I found that the current rendering method crashes when `mode` does not contain `RenderBlobsMode.Color`.

fixed in the next release :runner: 
https://github.com/shimat/opencvsharp/commit/d5d588c183087510c8af0058e3357d76a6cf1382

**Comment by fdncred** [comment]
Looks good.  Thank you.
