### ISSUE TITLE
OpenCVSharp Rect Coordinates do not match up with System.Drawing.Rectangle

### ISSUE THREAD

**Issue by DoomDrop** [shimat/opencvsharp#1510]
# Summary of your issue

I have tested this by using both the base System.Drawing.Rectangle and other library's that use System.Drawing.Rectangle as a reference and the coordinates do not match up and it is on OpenCvSharp4s side.
It seems the coordinates outputted by both are the same values but the end result doesn't match up particuallry OpenCvSharp4 seems to be shifting the pixels an extraordinary amount. 
This can be seen in the example below. Even though the example uses another library the issue still stands and the other library simply uses System.Drawing.Rectangle as a variable input. If you with to test it with the library it is IronOcr Version: 2022.11.10109

# Environment

Microsoft Visual Studio Community 2022 (64-bit)
Version 17.4.2

# What did you do when you faced the problem?

I have sent an email to IronOcr developers to see if its a problem they would be willing to face but since its mostly your problem and they have basically denied to take initiative so I have taken it upon myself to submit the issue here.
I have also began using OpenCvSharp4s integration with Tesseract but its requiring a lot more work to get my desired result then IronOcr would be able to accomplish.

## Example code:

```
// Get the original Image
fullPage = Cv2.ImRead(@"C:\Projects\AnExperiment\WpfApp1\Images\DifferentFontsTest.PNG");
// Resize it so it works with the cordinates stored previously in a json file
Cv2.Resize(fullPage, resizedMat, SetResolution(fullPage, dpi));
String[] splitText;
//---------------------------------------------------------------------- METHOD 1 ----------------------------------------------------------------------
// The best OCR and least work but problems with combination of OpenCvSharp Rect to System.Drawing.Rectangle
var Ocr = new IronTesseract();
using (var Input = new OcrInput())
{
                                                            //Top Left X, Top Left Y, Width, Height
    OpenCvSharp.Rect openCVRectangle = new OpenCvSharp.Rect(      56    ,     127   ,  279,   256  );

    // Box Cordinates
    var TLX = openCVRectangle.TopLeft.X;
    var TLY = openCVRectangle.TopLeft.Y;
    var BRX = openCVRectangle.BottomRight.X; 
    var BRY = openCVRectangle.BottomRight.Y;
    Debug.Print("OpenCvSharp4 Rect: ("+ TLX + "," + TLY + ")(" + BRX + "," + BRY + ")");
    var width = BRX - TLX; 
    var height = BRY - TLY;

    // Since IronOcr Uses System.Drawing.Rectangle lets just try inputing the same values we just obtained from the OpenCvSharp Rectangle
    System.Drawing.Rectangle systenDrawRect = new System.Drawing.Rectangle(TLX, TLY, BRX, BRY);
    Debug.Print("System.Drawing.Rectangle:  " + systenDrawRect.Location + ", (" + systenDrawRect.Width + "," + systenDrawRect.Height +")");
    IronOcr.CropRectangle r = new CropRectangle(systenDrawRect);

    // Lets draw the rectangle on the image to confirm the cordinates match up to what we are looking for
    resizedMat.Rectangle(new OpenCvSharp.Point(TLX, TLY), new OpenCvSharp.Point(BRX, BRY), Scalar.Green, 3);
    // SHow the mat so we can physically see the rectangle we just drew
    Cv2.ImShow("TestImage", resizedMat);

    // Take original image and apply the crop rectangle so we only get the piece we want to read
    Input.Add(@"C:\Projects\AnExperiment\WpfApp1\Images\DifferentFontsTest.PNG", r);
    Input.EnhanceResolution();
    var Result = Ocr.Read(Input);
    ResultBox.Text = Result.Text;

    //Seperate lines to display in our textblock
    splitText = ResultBox.Text.Split('\n');
}
```

## Output:

```
OpenCvSharp4 Rect: (56,127)(335,383)
System.Drawing.Rectangle:  {X=56,Y=127}, [(335,383)]
```
Image below shows what OpenCVSharp4 draws but what's in the textbox is what System.Drawing.Rectangle captures showing they are not the same area / coordinates.
[https://flic.kr/p/2o5twrG](url)

## What did you intend to be?
I intend the coordinates to actually match up. But even without the other library you can tell System.Drawing.Rectangle and OpenCvSharp4 do not match up by using a canvas.

**Comment by shimat** [comment]
I guess this is not a OpenCvSharp bug. It seems your code has a problem, The constructor of System.Drawing.Rectangle takes x, y, width, and height as arguments, just like OpenCvSharp.Rect.

```c#
System.Drawing.Rectangle systenDrawRect = new System.Drawing.Rectangle(TLX, TLY, BRX, BRY);
```
:arrow_down: 
```c#
System.Drawing.Rectangle systenDrawRect = new System.Drawing.Rectangle(
    openCVRectangle.X, 
    openCVRectangle.Y,
    openCVRectangle.Width,
    openCVRectangle.Height);
```

If you want to use left/bottom instead of width/height, use FromLTRB.
```c#
System.Drawing.Rectangle systenDrawRect = System.Drawing.Rectangle.FromLTRB(TLX, TLY, BRX, BRY);
```
