### ISSUE TITLE
Can CascadeClassifier be created with an xml string instead of a file location?

### ISSUE THREAD

**Issue by LostBeard** [shimat/opencvsharp#1511]
I am using the OpenCVSharp4 wasm runtime with Blazor WenAssembly and I am having trouble creating a CascadeClassifier using a relative link to the xml file. I am guessing it is because the OpenCVSharp is assuming it's a local file, but it's a relative http path.

So my question:
Can CascadeClassifier be created with an xml string instead of a file location? 
Thank you.

**Comment by shimat** [comment]
The native C++ CascadeClassifier does not seem to have a function to initialize from an XML string.
https://github.com/opencv/opencv/blob/b4b35cff15041c9a2795c749a8dfcffc317acefc/modules/objdetect/include/opencv2/objdetect.hpp#L232

This internal OpenCV implementation may be helpful: https://github.com/opencv/opencv/blob/8b4fa2605e1155bbef0d906bb1f272ec06d7796e/modules/objdetect/src/ cascadedetect.cpp#L934

**Comment by LostBeard** [comment]
Thank you for the fast reply. I will take a look and see if I can figure out a way.

**Comment by LostBeard** [comment]
Looking at modules\objdetect\src\cascadedetect.cpp CascadeClassifierImpl::load and CascadeClassifierImpl::read I can see how to make a FileStorage, then get the root FileNode with GetFirstTopLevelNode, and then use the CascadeClassifier.Read(FileNode fileNode) method to load it. But the created CascadeClassifier throws an exception if I call DetectMultiScale on it. Any help is appreciated.

```
var newfs = new FileStorage(".xml", FileStorage.Modes.Memory | FileStorage.Modes.Write);
newfs.Open(xmlString, FileStorage.Modes.Read | FileStorage.Modes.Memory);
if (newfs.IsOpened())
{
    // The below line returns the xmlString I wrote so it looks like it worked
    //var xmlTest = FileStorage.ReleaseAndGetString();
    RootNode = newfs.GetFirstTopLevelNode();
    if (RootNode != null)
    {
        var cascade = new CascadeClassifier();
        if (cascade.Read(RootNode))
        {
            // gets here without any problems
            // but errors when I try top use the CascadeClassifier (I have verified grayImage is valid)
            var faces = cascade.DetectMultiScale(grayImage, 1.3, 5);
            // never gets here ...
        }
    }
}
```

**Comment by LostBeard** [comment]
I just tested in a fresh .Net 7 console project and the above code is working. Full example below.

```
using OpenCvSharp;

using var srcImage = Cv2.ImRead(@"media\test-image-1.jpg");
using var grayImage = srcImage.CvtColor(ColorConversionCodes.BGR2GRAY);
var xmlString = File.ReadAllText(@"haarcascades\haarcascade_frontalface_default.xml");
var newfs = new FileStorage(".xml", FileStorage.Modes.Memory | FileStorage.Modes.Write);
newfs.Open(xmlString, FileStorage.Modes.Read | FileStorage.Modes.Memory);
if (newfs.IsOpened())
{
    // The below line returns the xmlString I wrote so it looks like it worked
    //var xmlTest = FileStorage.ReleaseAndGetString();
    var RootNode = newfs.GetFirstTopLevelNode();
    if (RootNode != null)
    {
        var cascade = new CascadeClassifier();
        if (cascade.Read(RootNode))
        {
            // gets here without any problems
            // but errors when I try top use the CascadeClassifier (I have verified grayImage is valid)
            var faces = cascade.DetectMultiScale(grayImage, 1.3, 5);
            // gets here in .Net 7 console app but not wasm app
            var count = faces.Length;
        }
    }
}
```


The exception it causes in Blazor wasm can't be caugght with a try catch block. It show and error in the console though

```
dotnet..0o06bbrt2r.js:5 Uncaught (in promise) Error: Assert failed: Value is not an Error number
    at eo (dotnet..0o06bbrt2r.js:5:29152)
    at b.javaScriptExports.complete_task (dotnet..0o06bbrt2r.js:5:59170)
    at dotnet..0o06bbrt2r.js:5:28913
```

I'll keep digging.

**Comment by LostBeard** [comment]
I think it may be an issue with the OpenCVSharp4 wasm runtime as that is the key difference. I wrote a minimal Blazor wasm app to test as identical code as possible in Blazor wasm and .Net console app both using .Net 7 and the same version of OpenCVSharp4. The only difference was the runtime and it is working in the console app.

I also think I found a bug in OpenCVSharp4 wasm. Cv2.ImDecode, and Mat.FromImageBytes are returning the wrong type of Mat. See below example code for me details. Identical files were used in both test apps.

(I define CONSOLEAPP in my console app)
```
#if CONSOLEAPP
var xmlString = File.ReadAllText(@"haarcascades\haarcascade_frontalface_default.xml");
var srcImageBytes = File.ReadAllBytes(@"media\test-image-2.png");
using var srcImage = Cv2.ImDecode(srcImageBytes, ImreadModes.Color);
var matType = srcImage.Type().ToString();
// matType == "CV_8UC3"
#else
var xmlString = await httpClient.GetStringAsync(@"haarcascades/haarcascade_frontalface_default.xml");
var srcImageBytes = await httpClient.GetByteArrayAsync(@"media/test-image-2.png");
using var srcImage = Cv2.ImDecode(srcImageBytes, ImreadModes.Color);
var channels = srcImage.Type().ToString();
// matType == "CV_8UC1" - Should be "CV_8UC3"
#endif
```
