### ISSUE TITLE
[Docker windows] System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies

### ISSUE THREAD

**Issue by yoyos** [shimat/opencvsharp#1516]
# Summary of your issue

I'm running a .NET 7 project on windows docker mcr.microsoft.com/dotnet/sdk:7.0-windowsservercore-ltsc2019 and when the step running my tests arrives it crashes asking for a dll.

I tested this project with OpenCvSharp4.Windows
or
OpenCvSharp4 and OpenCvSharp4.runtime.win

Command used to reproduce crash : dotnet test -c Release Project\Project.Lib.Tests.csproj
The publishing step is working but not the execution of units tests (using xunit)

Using my VS2022 IDE on W10, I have no problem building, running, publishing those projects

# Environment

windows docker image: mcr.microsoft.com/dotnet/sdk:7.0-windowsservercore-ltsc2019

# What did you do when you faced the problem?

Used a command in a docker docker mcr.microsoft.com/dotnet/sdk:7.0-windowsservercore-ltsc2019 to run my xunit test project.

## Example code:

```
dotnet test -c Release Project\Project.Lib.Tests.csproj
```

## Output:

```
[xUnit.net 00:00:04.24]     Project.Lib.Tests.ShouldSucceedTest [FAIL]
  Failed Project.Lib.Tests.ShouldSucceedTest [3 s]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at Project.Lib.Tests.ShouldSucceedTest() in C:\builds\dc\components\project\Project.Lib.Tests\Test.cs:line 68
--- End of stack trace from previous location ---
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.videoio_VideoCapture_delete(IntPtr obj)
   at OpenCvSharp.VideoCapture.DisposeUnmanaged()
   at OpenCvSharp.DisposableObject.Dispose(Boolean disposing)
   at OpenCvSharp.DisposableObject.Finalize()
```

## What did you intend to be?

I would like my test project executing correctly like on my dev environment.

**Comment by yoyos** [comment]
I found the problem.

I buit my project using another location of my nuget package cache folder and when running the tests, it seems it tried to use the dlls in this nuget package cache folder instead of its bin folder.

I thought the bin folder was self suffisent but it seems not ..

**Comment by clibequilibrium** [comment]
@yoyos try [this](https://github.com/brunsgaard/OpenCVSharp-docker-example/blob/master/README.md)

**Comment by yoyos** [comment]
I'll try that asap thanks
