### ISSUE TITLE
CvBlobs Outline calculated incorrection

### ISSUE THREAD

**Issue by fdncred** [shimat/opencvsharp#152]
This is separate but related to issue 151.

When calling CvBlobs.RenderBlobs() I have noticed that every rectangle bounding box is one pixel short on the width and height.

I wrote my own render routine and corrected it like this.
```charp
Rect realBlobRect = new Rect(blob.Rect.X, blob.Rect.Y, blob.Rect.Width+1, blob.Rect.Height+1);
```

One pixel offset is hard to see unless you zoom in.  If you do you'll notice that the bounding boxes are offset.

Before Image
![nodots](https://cloud.githubusercontent.com/assets/343840/11005267/7f1e2e78-8482-11e5-94d2-1b89c292b52d.png)
After Image
![nodots-rect](https://cloud.githubusercontent.com/assets/343840/11005295/963a767a-8482-11e5-8f14-0432613a0e69.png)
Corrected Image
![nodots-corrected](https://cloud.githubusercontent.com/assets/343840/11005340/c9a4efea-8482-11e5-8d88-3ebe44c9bec1.png)

**Comment by shimat** [comment]
Thank you for your report :+1: 
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp.Blob/BlobRenderer.cs#L81

fixed in the next release :bow:

**Comment by fdncred** [comment]
I'm not sure why but even with the change you made it still seems to be off by one pixel to the right and one pixel to the bottom.

If you download and look at these images zoomed in, you'll see that the top image is ran without any modification to the CvBlobs[x].Value.Rect and is one pixel off but the bottom image is padded by 1 pixel on the width and height and looks correct.

The input image is the same one above.

![1 nodots-cvblobs2-inva](https://cloud.githubusercontent.com/assets/343840/11220329/1242925c-8d25-11e5-95c7-7e85af9ef97c.png)
![1 nodots-cvblobs2-invb](https://cloud.githubusercontent.com/assets/343840/11220328/1241adc4-8d25-11e5-886e-d0866603c096.png)

**Comment by fdncred** [comment]
I fixed this by changing the Rect property from this:
```csharp
public Rect Rect
{
    get { return new Rect(MinX, MinY, MaxX - MinX, MaxY - MinY); }
    set
    {
        MinX = value.Left;
        MinY = value.Top;
        MaxX = value.Right;
        MaxY = value.Bottom;
    }
}
```
To this:
```csharp
public Rect Rect
{
    get { return new Rect(MinX, MinY, MaxX - MinX + 1, MaxY - MinY + 1); }
    set
    {
        MinX = value.Left;
        MinY = value.Top;
        MaxX = value.Right;
        MaxY = value.Bottom;
    }
}
```
This change also matches the FromLTRB Rect Method - Note the additional +1 to the Width and Height.
```csharp
public static Rect FromLTRB(int left, int top, int right, int bottom)
{
    Rect r = new Rect
    {
        X = left,
        Y = top,
        Width = right - left + 1,
        Height = bottom - top + 1
    };

    if (r.Width < 0)
        throw new ArgumentException("right > left");
    if (r.Height < 0)
        throw new ArgumentException("bottom > top");
    return r;
}
```

**Comment by shimat** [comment]
I am sorry for the late reply. I employ your solution. Thanks! :+1:
