### ISSUE TITLE
Problem with KAZESample in Unity

### ISSUE THREAD

**Issue by nuttonutto** [shimat/opencvsharp#153]
Hello,

I tried to use KAZE in my Unity project but I always got this error.

'ArrayTypeMismatchException: Source array type cannot be assigned to destination array type.
(wrapper stelemref) object:stelemref (object,intptr,object)
System.Collections.Generic.Dictionary`2[System.Type,OpenCvSharp.Ptr`1+ReleaseFunc[OpenCvSharp.KAZE]].Add (System.Type key, OpenCvSharp.ReleaseFunc value) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:429)
OpenCvSharp.Ptr`1[OpenCvSharp.KAZE]..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for OpenCvSharp.Ptr`1
OpenCvSharp.KAZE..ctor (IntPtr p)
OpenCvSharp.KAZE.Create (Boolean extended, Boolean upright, Single threshold, Int32 nOctaves, Int32 nOctaveLayers, KAZEDiffusivity diffusivity)
Test.Start () (at Assets/Test.cs:24)'

when var kaze = KAZE.Create(); and var akaze = AKAZE.Create(); are called. I can't find how to solve this yet.

**Comment by shimat** [comment]
Sorry but it is difficult to support Unity. Please consider using *OpenCV for Unity* (https://www.assetstore.unity3d.com/en/#!/content/21088).
