### ISSUE TITLE
IplImage not finding library

### ISSUE THREAD

**Issue by JohnDavidHanna** [shimat/opencvsharp#154]
I'm not familiar with loading libraries.
Used Nuget package and the using works fine.
![capture](https://cloud.githubusercontent.com/assets/15808704/11108300/d8632c4c-88b3-11e5-9e5f-eec78d59e6f7.PNG)
well i hope this image displays

**Comment by shimat** [comment]
According to the image, opencv_core**240** was tried loading. It is a quite old OpenCV DLL. The latest nuget package should use opencv_core**2410**.
Are there any old OpenCvSharp assemblies on your computer?

**Comment by JohnDavidHanna** [comment]
Thanks so much for getting back to me.
I did load different libraries into test projects before I found your work.
I'll work it from that angle tomorrow and report what I find.
Again, thanks so much

**Comment by onethousansouls** [comment]
![image](https://user-images.githubusercontent.com/48967610/210118825-c14e542f-91d2-446a-85ec-b09360caff0c.png)
