### ISSUE TITLE
OpenCvSharp-AnyCPU v2.4.10.20150820 throws exception opencv_core2410 not found

### ISSUE THREAD

**Issue by karolys** [shimat/opencvsharp#155]
I have installed(VIA NuGet) OpenCvSharp-AnyCPU v2.4.10 which as far as I understand it should have the base OpenCV DLLs included within it. When attempting to make any calls I receive a runtime exception that it was unable to find 'opencv_core2410.dll'. I have manually included the OpenCV DLLs within my project and everything works as it should, but I was under the impression this was not the intention of that build.

**Comment by fdncred** [comment]
I have had problems with this as well and when I debugged the code I found that where the DLLs are at is very important.  Recently I had to move the DLLs into this folder structure:

C:\Path\To\Project\ProjectName
+---bin
¦   +---Debug
¦   +---ProjectName.exe
¦   +---OpenCvSharp.dll
¦   +---OpenCvSharp.Extensions.dll
¦   +---OpenCvSharp.Blob.dll
¦   +---x64
¦   ¦   +---Debug
¦   ¦   ¦   +---dll
¦   ¦   ¦   ¦   +---x64
¦   ¦   ¦   ¦   +---opencv_ffmpeg300_64.dll
¦   ¦   ¦   ¦   +---opencv_world300.dll
¦   ¦   ¦   ¦   +---opencv_world300d.dll
¦   ¦   ¦   ¦   +---OpenCvSharpExtern.dll

**Comment by radunedelcu** [comment]
I have noticed that the issue happens if you compiled OpenCV with external libraries and the external libraries are missing - one example: TBB.dll
