### ISSUE TITLE
Cv2.BuildOpticalFlowPyramid - Cannot convert second parameter to OutputArray

### ISSUE THREAD

**Issue by aaapes3** [shimat/opencvsharp#157]
I'm trying to use pyramid estimation of optical flow but seems impossible passing the second parameter of the method:
Cv2.BuildOpticalFlowPyramid(InputArray, OutputArray, Size, Int)

Usually in C++ i can pass 'vector\<Mat>'.
If i try to pass a 'List\<Mat>' it says:

Argument 2: cannot convert from 'System.Collections.Generic.List\<OpenCvSharp.Mat>' to 'OpenCvSharp.OutputArray'

**Comment by shimat** [comment]
please try `OutputArray.Create(list);`.

The managed OutputArray class has a implicit cast operator method from `Mat` to `OutputArray`. I also tried to make a cast method from `List<T>` to `OutputArray`, but C# cast operator does not support generic types. :cry:  

`OutputArray.Create` is a approach similar to `System.Tuple.Create`.

**Comment by shimat** [comment]
Ah.. OutputArray does not support `List<Mat>`...

```c#
public static OutputArray Create<T>(List<T> list)
    where T : struct  // !!!
```

I try to provide something different method :bow:

**Comment by aaapes3** [comment]
Exactly, that's the problem!

However thank you so much for the wrapper. I'm using it with Unity3D and
works like a charm!

2015-11-26 5:58 GMT+01:00 shimat <notifications@github.com>:

**Comment by shimat** [comment]
I made an overload of BuildOpticalFlowPyramid
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Cv2/Cv2_video.cs#L105
