### ISSUE TITLE
cvSmooth 

### ISSUE THREAD

**Issue by GongKuiJun** [shimat/opencvsharp#1587]
How to call cvSmooth

**Comment by shimat** [comment]
OpenCV 1.x's `cvSmooth` was split into separate functions such as `cv::medianBlur`, `cv::GaussianBlur`, etc. in OpenCV 2.x and later.
In OpenCvSharp, try methods such as `Cv2.GaussianBlur`.

**Comment by GongKuiJun** [comment]
Thank you
