### ISSUE TITLE
Moving forward...HDR

### ISSUE THREAD

**Issue by Tharyn** [shimat/opencvsharp#159]
Thank you for the starting the HDR implementation. I now understand how it works and have been adding the rest of the functionality.  I figured out what this error is in the process.

Unity3D ERROR: ArrayTypeMismatchException: Source array type cannot be assigned to destination array type. (wrapper stelemref) object:stelemref (object,intptr,object)

Answer: Unity3D uses an older version of Mono that has a bug preventing it from passing complex pointers of classes back.  So you can't instantiate a class like CalibrateDebevec and hand the ptr back. 

The solution was simple. I created several NativeMethods that take the same input variable and return a Mat with the result, doing all the work on the C++ side.

Cheers,
Tharyn

**Comment by shimat** [comment]
Thank you for your information :smile: 
I hear repeated stories of opencvsharp problems on Unity... Unity, please use the latest Mono :weary:

**Comment by Tharyn** [comment]
We are all waiting for them to do so ;)
