### ISSUE TITLE
Unable to load shared library 'OpenCvSharpExtern'

### ISSUE THREAD

**Issue by chrisgilliam72** [shimat/opencvsharp#1600]
I am getting the following error when running an OpenCVSharp project on my raspberry pi:
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/chris/.dotnet/shared/Microsoft.NETCore.App/7.0.10/OpenCvSharpExtern.so: cannot open shared object file: No such file or directory
/home/chris/.dotnet/shared/Microsoft.NETCore.App/7.0.10/libOpenCvSharpExtern.so: cannot open shared object file: No such file or directory
/home/chris/.dotnet/shared/Microsoft.NETCore.App/7.0.10/OpenCvSharpExtern: cannot open shared object file: No such file or directory
/home/chris/.dotnet/shared/Microsoft.NETCore.App/7.0.10/libOpenCvSharpExtern: cannot open shared object file: No such file or directory

   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.ExceptionHandler.RegisterExceptionCallback()
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.objdetect_CascadeClassifier_newFromFile(String fileName, IntPtr& returnValue)
   at OpenCvSharp.CascadeClassifier..ctor(String fileName)
   at Program.<Main>$(String[] args) in /home/chris/Dev/OpenCVSharpDemo2/Program.cs:line 7
   
   
   I have built both OpenCV and OpenCvSharp locally on my PI and have tried copying the LibOpenCvSharpExtern.so to various folders but it never finds it.
I have also run ldd on  LibOpenCvSharpExtern.so and there appears to be no missing librartes

**Comment by grayfox99** [comment]
Yep, I am facing the same issues and I've tried every solutions suggested in other threads. I am running Rider on MacOS.

**Comment by chrisgilliam72** [comment]
Hey so I found the solution for raspberry pi I just had to move that lib into /usr/lib.I think if you just move it into the shared library folder of your Mac that would solve it . Sent from my iPhoneOn 16 Aug 2023, at 13:42, Fahad ***@***.***> wrote:﻿
Yep, I am facing the same issues and I've tried every solutions suggested in other threads. I am running Rider on MacOS.

**Comment by grayfox99** [comment]
Thanks for the response! I will give it a shot. I am currently trying to follow the solutions posted here since that thread explicitly mentions a MacOS solution: https://github.com/shimat/opencvsharp/issues/1528

**Comment by chrisgilliam72** [comment]
Hello everyone I solved this on my RaspberryPI by moving OpenCvSharpExtern.so into /usr/lib
