### ISSUE TITLE
RTrees.ActiveVarCount property should be of type int

### ISSUE THREAD

**Issue by ura14h** [shimat/opencvsharp#1611]
The ActiveVarCount property should be of type int.

Currently it is defined as a bool type. This means that only 0 or 1 can be passed to the native runtime library.

https://github.com/shimat/opencvsharp/blob/15d39479fa2e4cef26615ba5b109a8d5d0aba8c0/src/OpenCvSharp/Modules/ml/RTrees.cs#L104

Native runtime library methods are defined as type int.

https://github.com/opencv/opencv/blob/7b399c4248fd6a399f2f5a731864448883fdd364/modules/ml/src/rtrees.cpp#L441-L442

**Comment by shimat** [comment]
Thank you! 
#1612
