### ISSUE TITLE
Will this project support .NET 8 (LTS) once its released?

### ISSUE THREAD

**Issue by hedronn** [shimat/opencvsharp#1616]
No issue, just a question. Will this project support .NET 8 (LTS) once its released?

**Comment by shimat** [comment]
Currently OpenCvSharp provides a .NET 6 assembly, which should also work as .NET 8. I think it will be some time before OpenCvSharp.dll will be built as TargetFramework=net8 .

**Comment by hedronn** [comment]
Assuming there are no breaking changes porting .net6 version to .net8 (which i doubt) it should be fairly easy to simply reference the new framework, plus the project would benefit from the massive performance improvements from version 6 to 8.

Happy to assist in the investigation

**Comment by rhalaly** [comment]
How will this affect consumers who use older .NET versions in their product and want the latest OpenCV features?

**Comment by LostBeard** [comment]
@rhalaly Nuget packages can have multiple framework targets. .Net 7 or .Net 8 targets can be added without losing .Net 6 support. If that were to be the route taken, it would not affect consumers who use older .Net versions at all. Multitargeting in a project as large as this one may not be easy though, and could be a real pain in the rear.

If he simply switched to .Net 8 as the target framework the change would be easier but then, as you stated, people still using older frameworks would not be able to use it.

That is probably why @shimat wrote  
> I think it will be some time before OpenCvSharp.dll will be built as TargetFramework=net8 .

**Comment by rhalaly** [comment]
Didn't know it can support multiple .NET versions at once (I know it can support several versions between frameworks, for example .NET and .NET Framework)

Thanks!

**Comment by hedronn** [comment]
>That is probably why @shimat wrote: - I think it will be some time before OpenCvSharp.dll will be built as TargetFramework=net8> 

Not too long I hope, as we also need to consider the lifecycle of .NET frameworks, below is the Microsoft page link to the roadmap for support of .NET releases. 

Note: .NET 6 (LTS) support ends November 12, 2024

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
