### ISSUE TITLE
NuGet package name for Ubuntu contains a typo(?)

### ISSUE THREAD

**Issue by cryocz** [shimat/opencvsharp#1622]
# Summary of your issue
There is an underscore in the NuGet package name for ubuntu (` OpenCvSharp4_.runtime.ubuntu.20.04-x64`), however the README contains the name without an underscore (`OpenCvSharp4.runtime.ubuntu.20.04-x64`). Is that a typo in the package name on NuGet, or is the README wrong?

**Comment by shimat** [comment]
The package name was intended to avoid a name conflict with https://www.nuget.org/packages/OpenCvSharp.runtime.ubuntu.20.04-x64, which was created by someone who is not me, but looking at it again carefully, we can remove that underscore.
