### ISSUE TITLE
CornerMinEigenVal() changes format of src input array

### ISSUE THREAD

**Issue by MWHID** [shimat/opencvsharp#1629]
# Summary of your issue

When I call into CornerMinEigenVal() with the "src" input array format CV_8UC1, after the call returns the format of "src" has changed to CV_32FC1.  This caught me off guard as I did not expect "src" to change at all, and the format of "src" does not change in the Python version of CovernMinEigenVal().  Is this the expected behavior for OpenCVSharp?  

# Environment

Windows 11 x64
Microsoft Visual Studio 2022
C# .NET Framework 4.7.2
OpenCVSharp4 v4.8.0.20230708
OpenCVSharp4.runtime.win 4.8.0.20230708

# What did you do when you faced the problem?

Trying to figure out if it's a bug or intended behavior

## Example code:

```
            // myfile.bmp is a (1080 x 1920) 24bpp RGB image.  Note it is 1080 wide and 1920 tall (tall and skinny)
            Mat src = Cv2.ImRead("myfile.bmp", ImreadModes.Grayscale);
            // src is now format CV_8UC1
            OutputArray dst = OutputArray.Create(src);
            Cv2.CornerMinEigenVal(src, dst, 2, 5, BorderTypes.Default);
            // src is now format CV_32FC1
```

## Output:

```
See above, format of src input array has changed
```

## What did you intend to be?

Intended src to remain unchanged

**Comment by shimat** [comment]
In your code example, I think the way you created the OutputArray is incorrect. Could you try the following code?

```c#
using var src = Cv2.ImRead("myfile.bmp", ImreadModes.Grayscale);
using var dst = new Mat();

Cv2.CornerMinEigenVal(src, dst, 2, 5, BorderTypes.Default);
```

**Comment by MWHID** [comment]
Thanks, that does seem to resolve it.  It appears there are 2 lessons for me:  1 - I was doing it wrong, 2 - OutputArray.Create() actually returns a reference and not a copy.  Thank you for your help!

**Comment by MWHID** [comment]
Adding a comment to close the issue.  The issue was my fault, not a bug.
