### ISSUE TITLE
ASP.NET project throws DllNotFoundException

### ISSUE THREAD

**Issue by YoungjaeKim** [shimat/opencvsharp#163]
I followed the article http://schima.hatenablog.com/entry/2014/01/30/105406 but it throws TypeInitializationException which has DllNotFoundException in InnerException. My own project shows same error.

I tried whole two days,
1. put `tbb.dll` file but not working. http://stackoverflow.com/a/9616219/361100
2. put dlls in same bin directory not working.
3. change x86, x64 with many variations but not working.
4. `localhost` nor `azurewebsites` deploy both not working.
5. referenced lots of stackoverflow but not helped.
6. troubleshooting links not helps. http://www.ipentec.com/document/document.aspx?page=csharp-using-opencvsharp-x64-type-initialization-exception

Could you upload your asp.net sample project? I'd like to try with it.
My dev environment is Visual Studio 2015 with IISExpress.

**Comment by YoungjaeKim** [comment]
OMG.
I tried desperately again and I made it.
I uploaded my sample job at below link.
https://github.com/YoungjaeKim/OpenCVSharpWebDemo

**Comment by shimat** [comment]
:+1:
