### ISSUE TITLE
cv::groupRectangles not wrapped

### ISSUE THREAD

**Issue by RGL73** [shimat/opencvsharp#164]
Hi,
I need to utilize 
CV_EXPORTS   void groupRectangles(std::vector<Rect>& rectList, int groupThreshold, double eps = 0.2);
from objdetect.hpp

But it is not wrapped.
Any idea?
Thanks a lot

**Comment by shimat** [comment]
Thanks :+1: 
added in the next release
https://github.com/shimat/opencvsharp/commit/d43e97d1f1b7bb461bdae9b419c6f42fe05e93ff

**Comment by RGL73** [comment]
Do You have any idea on the release date.

**Comment by shimat** [comment]
This was released. Sorry for the late release. :bow:
