### ISSUE TITLE
OpenCvSharpExtern c++ project not building on VS2015

### ISSUE THREAD

**Issue by RGL73** [shimat/opencvsharp#165]
Hi,
this project links to: 
opencv_calib3d249d.lib
opencv_contrib249d.lib
opencv_core249d.lib
opencv_features2d249d.lib
opencv_flann249d.lib
opencv_gpu249d.lib
opencv_highgui249d.lib
opencv_imgproc249d.lib
opencv_legacy249d.lib
opencv_ml249d.lib
opencv_nonfree249d.lib
opencv_objdetect249d.lib
opencv_photo249d.lib
opencv_stitching249d.lib
opencv_superres249d.lib
opencv_video249d.lib
opencv_videostab249d.lib

still older than current 300. 
Is it correct?

**Comment by shimat** [comment]
The latest OpenCvSharp links to OpenCV3.0 or OpenCV2.4.10.
What branch did you check out?

**Comment by RGL73** [comment]
I checked out the master branch, making the assumption was the 3.0 one.
Anyway here the additional dependencies from 3.0 branch:

opencv_calib3d249d.lib
opencv_contrib249d.lib
opencv_core249d.lib
opencv_features2d249d.lib
opencv_flann249d.lib
opencv_gpu249d.lib
opencv_highgui249d.lib
opencv_imgproc249d.lib
opencv_legacy249d.lib
opencv_ml249d.lib
opencv_nonfree249d.lib
opencv_objdetect249d.lib
opencv_photo249d.lib
opencv_stitching249d.lib
opencv_superres249d.lib
opencv_video249d.lib
opencv_videostab249d.lib

**Comment by shimat** [comment]
The OpenCvSharpExtern project in the master branch should link `opencv_world300.lib`.
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj#L199

Your code seems to be old?? please try git pull.

**Comment by RGL73** [comment]
Hi
pull done, same result, looking more in detail on the project file you mentioned
probably there is some misalignment from Debug and Release version...
see:
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj#L167
Is it correct?

**Comment by shimat** [comment]
Thank you. I got it.  The Debug config is not updated :bow:  

The managed OpenCvSharp assemblies utilize OpenCvSharpExtern.dll as not Debug but Release build. Please select the Release build configuration.

**Comment by RGL73** [comment]
Thank You
Should I close the issue or You close it when updated the project?
My compliments for the excellent work you have done.

**Comment by shimat** [comment]
:+1: 
fixed by https://github.com/shimat/opencvsharp/commit/738a263ebc79b8c09059bf59de651e42054d352b
