### ISSUE TITLE
たびたびの質問をお許しください。

### ISSUE THREAD

**Issue by apli0128** [shimat/opencvsharp#166]
すいません。if文は勘違いしてしまいました。
Cv.DrawLine(dst, blob, nearestBlob, CvScalar(0,0,0),3,4);
このように書くと
エラー	1	'OpenCvSharp.CvScalar' は '型' ですが、'変数' のように使用されています。	C:\Users\kuni\documents\visual studio 2012\Projects\Project1\Project1\Example.cs	34	53	Project1
と出てきます。
また、ループ文でblobが最後までいったら終了するためにはどのように書けばいいんでしょうか。

**Comment by apli0128** [comment]
さっきはDistance内に書いていたのですが、今度のはmainのほうに書いてあります。
どちらにどのように書くのかが、いまいち理解できていないのが現状です。

**Comment by shimat** [comment]
コメントで書いたように、**new** CvScalarです。

ループの最後をどうするかというのは、今どきの言語ではその心配が要らないループが必ずあります。(`foreach`)

今書かれているコードを出せるだけ、全部貼って頂けますか？

**Comment by apli0128** [comment]
using System;
using System.Drawing;
using System.Linq;
using OpenCvSharp;
using OpenCvSharp.Blob;
using OpenCvSharp.Extensions;

namespace ConsoleApplication1
{
    class Program
    {
        static double Distance(CvBlob b1, CvBlob b2)//距離の最小値(３平向の定理)
        {
            var p1 = b1.Centroid;
            var p2 = b2.Centroid;
            return Math.Sqrt(Math.Pow(p1.X - p2.Y, 2) + Math.Pow(p1.Y - p2.Y, 2));
        }
        static void Main(string[] args)
        {
            using (IplImage src = new IplImage("tenji02.png", LoadMode.GrayScale))//画像をグレイスケールで読み込み
            using (IplImage dst = src.Clone())//閾値を決めてから2値化
            {
                int blockSize = 7;
                double k = 1.5;
                double R = 10;
                Binarizer.SauvolaFast(src, dst, blockSize, k, R);
                Cv.Not(dst, dst);//ネガポジ反転
                CvBlobs blobs = new CvBlobs();
                blobs.Label(dst);
                blobs.FilterByArea(100, 500);//面積99以下500以上は削除
                var blob = blobs.First();//最初のblobを基準とする
                (foreach){
                var nearestBlob = blobs.Except(new[] { blob }).OrderBy(b => Distance(b.Value, blob.Value)).First();
                Cv.DrawLine(dst, blob, nearestBlob, newCvScalar(0,0,0),3,4);//直線描画
            }
                IplImage imgRender = new IplImage(src.Size, BitDepth.U8, 3);
                blobs.RenderBlobs(src, imgRender);
                CvWindow.ShowImages(imgRender);
                Cv.WaitKey(0);
            }
        }
    }
}
(foreach)を書いてみたのですが、’(foreach)’は無効です。と出てきます。

**Comment by apli0128** [comment]
申し訳ありません。()を付けたまま書いてしまいました。foreachのあとをどのように書けばよいのでしょうか

**Comment by shimat** [comment]
デバッグせずここに書いているので、多少変なところあるかもしれませんが、エラーメッセージ等を頼りに修正して下さい。

```c#
using System;
using System.Drawing;
using System.Linq;
using OpenCvSharp;
using OpenCvSharp.Blob;
using OpenCvSharp.Extensions;

namespace ConsoleApplication1
{
    class Program
    {
        static CvBlob FindNearestBlob(IEnumerable<CvBlob> blobs, CvBlob b)
        {
            // 自分以外を距離順に昇順ソート。
            // 昇順だから距離最小が始めに来るので、Firstを返す。
            return blobs.Except(new[]{b}).OrderBy(bb => Distance(b, bb)).First();
        }
        static double Distance(CvBlob b1, CvBlob b2)//距離の最小値(３平向の定理)
        {
            var p1 = b1.Centroid;
            var p2 = b2.Centroid;
            return Math.Sqrt(Math.Pow(p1.X - p2.Y, 2) + Math.Pow(p1.Y - p2.Y, 2));
        }
        static void Main(string[] args)
        {
            using (IplImage src = new IplImage("tenji02.png", LoadMode.GrayScale))//画像をグレイスケールで読み込み
            using (IplImage dst = src.Clone())//閾値を決めてから2値化
            {
                int blockSize = 7;
                double k = 1.5;
                double R = 10;
                Binarizer.SauvolaFast(src, dst, blockSize, k, R);
                Cv.Not(dst, dst);//ネガポジ反転
                CvBlobs blobs = new CvBlobs();
                blobs.Label(dst);
                blobs.FilterByArea(100, 500);//面積99以下500以上は削除

                foreach (CvBlob blob in blobs)
                {
                    var nearestBlob = FindNearestBlob(blobs, b);

                    var p1 = new CvPoint((int)blob.Centroid.X, (int)blob.Centroid.Y);
                    var p2 = new CvPoint((int)nearestBlob.Centroid.X, (int)nearestBlob.Centroid.Y);
                    Cv.DrawLine(dst, p1, p2, new CvScalar(0,0,255),3,4);//直線描画
                }

                IplImage imgRender = new IplImage(src.Size, BitDepth.U8, 3);
                blobs.RenderBlobs(src, imgRender);
                CvWindow.ShowImages(imgRender);
                Cv.WaitKey(0);
            }
        }
    }
}
```

**Comment by apli0128** [comment]
ご丁寧にありがとうございます。
エラー	1	型または名前空間名 'IEnumerable' が見つかりませんでした。using ディレクティブまたはアセンブリ参照が不足しています。
と出てくるのですが、このエラーはどう解決すればよいのでしょうか

**Comment by apli0128** [comment]
using System.Collections.Generic;
を追加することでIEnumerableのエラーは解決できたのですが、新しく
エラー1	型 'System.Collections.Generic.KeyValuePair<int,OpenCvSharp.Blob.CvBlob>' を型 'OpenCvSharp.Blob.CvBlob' に変換できません。	C:\Users\kuni\documents\visual studio 2012\Projects\Project1\Project1\Example.cs	39	17	Project1
エラー2	名前 'b' は現在のコンテキスト内に存在しません。	C:\Users\kuni\documents\visual studio 2012\Projects\Project1\Project1\Example.cs	41	62	Project1
エラー3	'OpenCvSharp.Cv.DrawLine(OpenCvSharp.CvArr, OpenCvSharp.CvPoint, OpenCvSharp.CvPoint, OpenCvSharp.CvScalar, int, OpenCvSharp.LineType)' に最も適しているオーバーロード メソッドには無効な引数がいくつか含まれています。	C:\Users\kuni\documents\visual studio 2012\Projects\Project1\Project1\Example.cs	45	21	Project1
エラー4	引数 6: 'int' から 'OpenCvSharp.LineType' に変換できません	C:\Users\kuni\documents\visual studio 2012\Projects\Project1\Project1\Example.cs	45	74	Project1
というふうにエラーが出てきます。
この場合はusing System.Collections.Genericを使わずにIEnumerableを解決する方法があるのでしょうか。

**Comment by shimat** [comment]
`foreach (CvBlob blob in blobs.Values)` でどうでしょう

**Comment by apli0128** [comment]
それはusing System.Collections.Genericを使った後のエラーの対処でよろしいでしょうか。
forearch(CvBlob blo in blobs.values)に変更した後は
エラー1	名前 'b' は現在のコンテキスト内に存在しません。	C:\Users\kuni\documents\visual studio 2012\Projects\Project1\Project1\Example.cs	41	62	Project1
エラー2	'OpenCvSharp.Cv.DrawLine(OpenCvSharp.CvArr, OpenCvSharp.CvPoint, OpenCvSharp.CvPoint, OpenCvSharp.CvScalar, int, OpenCvSharp.LineType)' に最も適しているオーバーロード メソッドには無効な引数がいくつか含まれています。	C:\Users\kuni\documents\visual studio 2012\Projects\Project1\Project1\Example.cs	45	21	Project1
エラー3	引数 6: 'int' から 'OpenCvSharp.LineType' に変換できません	C:\Users\kuni\documents\visual studio 2012\Projects\Project1\Project1\Example.cs	45	74	Project1
のようになりました。
var nearestBlob = FindNearestBlob(blobs, b);この文のbと
Cv.DrawLine(dst, p1, p2, new CvScalar(0,0,255),3,4);の文にエラーが起きています。

**Comment by shimat** [comment]
var nearestBlob = FindNearestBlob(blobs, blob);
ですね。

（間違えてる私が悪いんですが、さすがにそのくらいは察し付きませんか？）

**Comment by apli0128** [comment]
大変申し訳ないと思っています。しかし周りに質問できる人もおらず、プログラムを組むこと自体も理解が浅いために教えを乞い少しずつ理解していくことしかできません。誠に申し訳ありません。

**Comment by apli0128** [comment]
var nearestBlob = FindNearestBlob(blobs.Values, blob);にすることでこの文のエラーを解決することはできたのですが
Cv.DrawLine(dst, p1, p2, new CvScalar(0,0,255),3,4);の文の
エラー1 'OpenCvSharp.Cv.DrawLine(OpenCvSharp.CvArr, OpenCvSharp.CvPoint, OpenCvSharp.CvPoint, OpenCvSharp.CvScalar, int, OpenCvSharp.LineType)' に最も適しているオーバーロード メソッドには無効な引数がいくつか含まれています。 
エラー2 引数 6: 'int' から 'OpenCvSharp.LineType' に変換できません。
というエラーの解決法がわかりません。
どうかこの二つをご教授ください。誠に自分勝手なのはわかっております。ですがどうかお願いします。

**Comment by shimat** [comment]
最後の引数(4)を削除したら、とりあえず動きそうです。

これを開発している私が申すのもあれなのですが、OpenCvSharpの利用者は本物のOpenCVに比べると圧倒的に少なく、従ってネット上の情報も少ないです。
ご経験に不安があるなら、C++かPythonで作られた方が、検索していて何かしらヒットしやすく、開発のスタートがしやすいはずです。

（このDrawLineの4という値も、どこかのC++のコードにあった値ではありませんか？）

ご質問を伺うに、貼っていただいたプログラムが動くまではできそうですが、このままだとそれ以上に進むのが困難に思えます。私もどこまでも回答を続けることはできません。老婆心ながら、失礼します。
