### ISSUE TITLE
VideoCapture.Retrieve is throwing an OpenCVException

### ISSUE THREAD

**Issue by ayb4btu** [shimat/opencvsharp#167]
I'm using PCA in OpenCVSharp (OpenCvSharp3-AnyCPU Version 3.0.0.20151220 running in Visual Studio 2015 and installed via NuGet), but when I try to get a frame from a video stream (saved using opencvsharp with LAGS fourcc) I get an OpenCVException: An exception of type 'OpenCvSharp.OpenCVException' occurred in OpenCvSharp.dll but was not handled in user code
Additional information: !fixedSize()

This is the code:

```
string fileName = @"C:\some\directory\to\file.avi";
VideoCapture videoReader = new VideoCapture(fileName);
Mat frame = new Mat(videoReader.FrameHeight, videoReader.FrameWidth, MatType.CV_8UC3);
videoReader.Retrieve(frame, 0); \\ <- exception occurs here
```

An additional problem is that the optional arguments of Retrieve wont let a single parameter be entered as both methods have two input parameters with the second parameter being a default value. This still occurs if `Mat frame = new Mat();`. However, this seems to work:

```
bool frameGrabbed = videoReader.Grab();
if (frameGrabbed)
{
    Mat frameGrabbed = this.videoReader.RetrieveMat();
}
```

**Comment by another-guy** [comment]
Hi @ayb4btu 

I apologize for intervening. Have you tried to run the  **VideoCaptureSample** from **OpenCvSharpSamples** solution? Does it work for you? It seems that the library has an issue. I get a different exception, though.

**Comment by ayb4btu** [comment]
@another-guy The work I was doing ended up going in a different direction, so I didn't needed to look into this any further. Have you posted the exception that you got into the issues?
