### ISSUE TITLE
BackgroundSubtractorMOG2 dont work

### ISSUE THREAD

**Issue by seekerquoc** [shimat/opencvsharp#168]
Hi
when i use BackgroundSubtractorMOG2, it give error "A first chance exception of type 'System.EntryPointNotFoundException' occurred in OpenCvSharp.dll"
 using (var mog = BackgroundSubtractorMOG2.Create())
            {
                mog.Apply(converted, fg, 0.01);
            }
            show_detect_vehicle.Image = converted;

**Comment by shimat** [comment]
🤔  it works for me... i think this problem seems to be resolved by recent patches. thanks.
