### ISSUE TITLE
OpenCV Dependencies

### ISSUE THREAD

**Issue by fdncred** [shimat/opencvsharp#169]
Can you post the OpenCV 3.x source code you use when you fully compile this project?  Every time I have to compile OpenCV I have to fight with it for hours.  Now that 3.1 is out I'd like to recompile everything but I don't have time to fight with OpenCV.

I would love to have one solution with OpenCV and OpenCvSharp and be able to click build all and just have it work.

**Comment by LightCZ** [comment]
I am doing exactly that for last 6 hours. This code management in this project is really a setback.
Also this project should really add the new opencv_contrib part - since only there is SIFT and SURF.
There are mentions about that in source code but i was unable to fight that battle to the successful end.

**Comment by shimat** [comment]
The OpenCV 3.x files (headers and static link libraries) that OpenCvSharp use is in `lib\opencv`. https://github.com/shimat/opencvsharp/tree/master/lib/opencv

The IncludePath and LibraryPath of the OpenCvSharpExtern project is already configured.
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj#L118

So, you should be able to build OpenCvSharp without compiling native OpenCV yourself.

**Comment by fdncred** [comment]
@shimat Thanks for the info but the point is that I want to use OpenCV v3.1 and not v3.0.  So in order for me to use 3.1 I have to compile the source.  That's what I'd like to get away from by you including the OpenCV project in your source code distribution so that I can benefit from all your hard work of compiling the source code and i can stay up to date with the new opencv source code and compile and use your C# solution as well.

**Comment by shimat** [comment]
I don't try to use OpenCV3.1 yet, but I think you don't have to build OpenCV3.1.
The official install package for Windows contains pre-built .lib files. http://opencv.org/downloads.html

You only have to replace the files in `lib\opencv\*` with the pre-built .lib and header files.

**Comment by shimat** [comment]
ah... got it. There are only x64 binaries in the official package. :bow: 
I`ll try to add OpenCV3.1 x86/x64 binaries to this repository.

**Comment by shimat** [comment]
I created a branch for OpenCV3.1. OpenCV headers and x86 and x64 binaries are added.
https://github.com/shimat/opencvsharp/tree/3.1

**Comment by fdncred** [comment]
Confirmed working for my needs.  Was able to load large g4 tiff without resorting to work-around.
