### ISSUE TITLE
Add Release Tag for 4.10

### ISSUE THREAD

**Issue by ptasev** [shimat/opencvsharp#1713]
# Summary of your issue

We create our own builds for different versions of linux and rely on the release tags of this repo. Can you please add a release tag for the latest release (4.10)? This will help us make sure to download the right version of the repo.

# Environment

Write your environment.

# What did you do when you faced the problem?

Write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp/releases/tag/4.10.0.20241024
Sorry for the delay in creating the release tag.

**Comment by ptasev** [comment]
No problem, thanks for your hard work!
