### ISSUE TITLE
 Unable to access buffer when converting Mat to memory stream

### ISSUE THREAD

**Issue by daisou64** [shimat/opencvsharp#1725]
# Summary of your issue

An exception occurs when using the GetBuffer() method of a memory stream created with the ToMemoryStream() method held by mat.
The reason is that a constructor is used in which the public option is disabled when the MemoryStream is materialized.

There is no problem if the user creates a MemoryStream with the publishing option enabled.
Is it intended that buffer access be private?
## Example code:

```
using (MemoryStream stream = mat.ToMemoryStream())
{
    byte[] buff= stream.GetBuffer();
}
```

## Output:

```
System.UnauthorizedAccessException: 'MemoryStream's internal buffer cannot be accessed.'
```

## What did you intend to be?
GetBuffer() is used internally when accessing MemoryStream from an external library

## How to solve the problem 

sample1
```
byte[] bytes = mat.ToBytes();
using (MemoryStream stream = new MemoryStream(bytes, 0, bytes.Length, false, true))
{
    byte[] buff = stream.GetBuffer();
}
```
sample2
```
using (MemoryStream stream = new MemoryStream())
{
    mat.WriteToStream(stream);
    byte[] buff = stream.GetBuffer();
}
```

**Comment by shimat** [comment]
Thanks, I will change it to return an instance created by the constructor of `new MemoryStream(bytes, 0, bytes.Length, false, true)`.

**Comment by daisou64** [comment]
Thank you for responding!
