### ISSUE TITLE
About converting byte[] to Mat

### ISSUE THREAD

**Issue by alyssonds** [shimat/opencvsharp#173]
Hello, I need to convert an image that is stored as byte[] to Mat to manipulate inside OpenCVSharp. To do so, I followed the instructions in:
https://github.com/shimat/opencvsharp/wiki/%5BCpp%5D-Converting-Image

//Im sure the data contains a byte[] that represents a RGB image
Mat src = new Mat(texture.height,texture.width,MatType.CV_8UC3);
src = Cv2.ImDecode(bytes, ImreadModes.Color);
src.SaveImage("bytes.jpg",new ImageEncodingParam(ImwriteFlags.JpegProgressive,255));

This is not working, and nothing is written at bytes.jpg. Am I missing something?

**Comment by shimat** [comment]
When your byte[] represents encoded image data (ex. JPEG, PNG, etc.), you can use `ImDecode`.

```c#
Mat src = Cv2.ImDecode(bytes, ImreadModes.Color);  
```

When your data represens pixel data (RGBRGBRGB...) , you need to hard-code copying operation. (I don't debug the following code)

```c#
var src = new Mat(height, width, MatType.CV_8UC3);
var indexer = src.GetGenericIndexer<Vec3b>(); 
for (int y = 0; y < height; y++)
{
    for (int x = 0; x < width; x++)
    {
        int pos = y * width + x * 3;
        byte blue = bytes[pos + 2];
        byte green = bytes[pos + 1];
        byte red = bytes[pos + 0];
        Vec3b newValue = new Vec3b(blue, green, red);
        indexer[y, x] = newValue;
    }
}
```

If your byte[] data's step length is equal to the Mat's, there is a more effective way.
```c#
var src = new Mat(height, width, MatType.CV_8UC3);
int length = height * width * 3; // or src.Height * src.Step;
Marshal.Copy(bytes, 0, src.ImageData, length);
```

**Comment by MhamzaM** [comment]
how can we convert a byte[ ] having a grayscale image to openCV Mat ?

**Comment by youngjin-song** [comment]
please helf me...
**How can we convert a byte[ ] having a grayscale image to openCV Mat ????!!!!!**

**Comment by shimat** [comment]
```c#
var src = new Mat(height, width, MatType.CV_8UC1);
int length = height * width
Marshal.Copy(bytes, 0, src.ImageData, length);
```

**Comment by chacoff** [comment]
> (I don't debug this code)
> 
> ```cs
> var src = new Mat(height, width, MatType.CV_8UC1);
> int length = height * width
> Marshal.Copy(bytes, 0, src.ImageData, length);
> ```
 something like this will do it:

```
byte[] byteArray = new byte[img.Width * img.Height * img.ElemSize()];
GCHandle handle = GCHandle.Alloc(byteArray, GCHandleType.Pinned);
IntPtr dataPtr = img.Data;
Marshal.Copy(dataPtr, byteArray, 0, byteArray.Length);
handle.Free();

```
