### ISSUE TITLE
Serializing and Deserializing Mat

### ISSUE THREAD

**Issue by LightCZ** [shimat/opencvsharp#174]
I have the following code:

``` csharp
 KeyPoint[] keypoints;
var descriptors = new MatOfFloat();
 var image2 = Cv2.ImRead(imagePath2, ImreadModes.Unchanged);
AKAZE.Create().DetectAndCompute(image1, null, out keypoints, descriptors);
```

Now i want to serialize keypoints to the file and then deserialize them back.
i tried this:

``` csharp
var byteStream = descriptors.ToMemoryStream();
var deserialized = MatOfFloats.FromStream(byteStream);
```

but the deserialized i different than original descriptors and this code also throw exception when i use MLDB algorithm in Akaze.
How to safely serialize and deserialize Mats  to/ from stream ?

**Comment by fdncred** [comment]
@LightCZ This isn't serialization but it may work for you.

```c#
static void RunKaze(string inFile)
{
    using (var gray = new Mat(inFile, ImreadModes.GrayScale))
    using (var dstAkaze = new Mat())
    using (var kaze = KAZE.Create())
    using (var akaze = AKAZE.Create())
    using (var kazeDescriptors = new Mat())
    using (var akazeDescriptors = new Mat())
    //using (var kazeDescriptors = new MatOfFloat())
    //using (var akazeDescriptors = new MatOfFloat())
    using (var dstKaze = new Mat())
    {
        KeyPoint[] kazeKeyPoints = null, akazeKeyPoints = null;
        var kazeTime = TimeMeasurer.Measure(() =>
            kaze.DetectAndCompute(gray, null, out kazeKeyPoints, kazeDescriptors));
        var akazeTime = TimeMeasurer.Measure(() =>
            akaze.DetectAndCompute(gray, null, out akazeKeyPoints, akazeDescriptors));

        //Make a byte array from the descriptors and save it
        byte[] barr = kazeDescriptors.ToBytes();
        File.WriteAllBytes("kaze.des", barr);

        //Read the byte array from the descriptor and make it a Mat
        byte[] inArr = File.ReadAllBytes("kaze.des");
        var kazedes = new Mat(kazeDescriptors.Rows, kazeDescriptors.Cols, kazeDescriptors.Type(), inArr);

        Cv2.DrawKeypoints(gray, kazeKeyPoints, dstKaze);
        Cv2.DrawKeypoints(gray, akazeKeyPoints, dstAkaze);

        using (new Window($"KAZE [{kazeTime.TotalMilliseconds:F2}ms]", dstKaze))
        using (new Window($"AKAZE [{akazeTime.TotalMilliseconds:F2}ms]", dstAkaze))
        {
            Cv2.WaitKey();
        }
    }
}
```

**Comment by shimat** [comment]
`ToMemoryStream` may not support float matrix.
In the latest OpenCvSharp, the `FileStorage` class supports Mat I/O.
please see https://github.com/shimat/opencvsharp/wiki/%5BCpp%5D-FileStorage

**Comment by turowicz** [comment]
@shimat any way to read / write MatOfDouble as a strong type? I see FileStorage only supports ReadMat() which I then don't know how to turn into MatOfDouble.

**Comment by RenWal** [comment]
For anyone stumbling across this now: The code example here does not seem to work in OpenCVSharp 4.

The `kazeDescriptors.ToBytes()` call produces a PNG encoded byte array by default (be really careful when you have float matrices!), however, `new Mat(kazeDescriptors.Rows, kazeDescriptors.Cols, kazeDescriptors.Type(), inArr)` expects raw pixel data. This will *not* throw an exception, but the resulting matrix will be broken. Use `Mat.FromImageData` instead to load the encoded array.
