### ISSUE TITLE
OCR関係について

### ISSUE THREAD

**Issue by ikeda28** [shimat/opencvsharp#175]
はじめまして、openCV3.0以降OCRの機能が追加されたようですが、opencvsharpでの対応予定は
ありますでしょうか？

**Comment by shimat** [comment]
OCRモジュールは本体ではなくcontribの方だったと思いますが、まずは本体からと思っていましてなかなか着手できていません :bow:  

OCRモジュールはtesseractを要しますが、このような外部モジュールや、さらにはGPUなどハードウェアまで要する機能もあるので、ラッパーは作れたとして配布の形態が大変悩ましいです。

純粋にラッパーだけ作り、OpenCVなどネイティブ周りの準備はご自分で、というのが落としどころと思ったりなどしていて及び腰、というまま時間が過ぎております...

**Comment by ikeda28** [comment]
了解いたしました。
ご検討よろしくお願いいたします。
