### ISSUE TITLE
IplImage doesn't have toBitmap() anymore?

### ISSUE THREAD

**Issue by 9tontruck** [shimat/opencvsharp#179]
My old project uses "OpenCvSharp" but now I can only search out "OpenCvSharp2" on NuGet.
The new version seems quite different from the old one. For example, the old version had "IplImage.toBitmap()" while the new version doesn't. 

Why does the new version not have that function? 
Did I miss anything when I was installing the library?

**Comment by shimat** [comment]
Please add a reference to `OpenCvSharp.Extensions.dll` .

https://github.com/shimat/opencvsharp/blob/2.x/src/OpenCvSharp.Extensions/BitmapConverter_IplImage.cs#L256

**Comment by thomasbielagk** [comment]
NuGet also has version 3, but only finds it when you explicitly search for "OpenCvSharp3". Just going for "OpenCvSharp" only finds v2.

**Comment by 9tontruck** [comment]
Thanks!
