### ISSUE TITLE
fillpoly does not fill polygons.

### ISSUE THREAD

**Issue by 9tontruck** [shimat/opencvsharp#181]
Hi,

I am trying to draw white filled polygons so tried IplImage.FillPoly and Mat.FillPoly. But they just draw polygon line just like DrawPoly does. OpenCvSharp's FillPoly does not seem to fill the polygons.

> IplImage output = new IplImage( image.Size, image.Depth, 1 );
> output.Set( CvColor.Black );
> output.FillPoly( ContourData.GetPoints( contours ), CvColor.White );
> //ContourData.GetPoints( contours ) returns CvPoint[][]

Is this a bug or my mistake? Would you tell me what I should do to draw filled polygons?

**Comment by fdncred** [comment]
@9tontruck I just played around with FillPoly() quickly and came up with this that works fine. I'm using OpenCvSharp 3.1 here.
```c#
Mat output = new Mat(new Size(100, 100), MatType.CV_8U, new Scalar(1));
output.SetTo(Scalar.Black);
List<List<Point>> ListOfListOfPoint = new List<List<Point>>();
List<Point> points = new List<Point>();
points.Add(new Point(10, 10));
points.Add(new Point(10, 50));
points.Add(new Point(50, 50));
points.Add(new Point(50, 10));
ListOfListOfPoint.Add(points);
output.FillPoly(ListOfListOfPoint, Scalar.White);
Cv2.ImShow("Window", output);
Cv2.WaitKey();
```

**Comment by 9tontruck** [comment]
My company usng OpenCvSharp 2.4.10.20151220 
Can't still draw filled polygons :S

**Comment by fdncred** [comment]
I just did this in 2.x
```c#
Mat output = new Mat(new Size(100, 100), MatType.CV_8U, new Scalar(1));
output.SetTo(Scalar.Black);
List<List<Point>> ListOfListOfPoint = new List<List<Point>>();
List<Point> points = new List<Point>();
points.Add(new Point(10, 10));
points.Add(new Point(10, 50));
points.Add(new Point(50, 50));
points.Add(new Point(50, 10));
ListOfListOfPoint.Add(points);
output.FillPoly(ListOfListOfPoint, Scalar.White);
output.SaveImage("fillpoly.png");
```
![fillpoly](https://cloud.githubusercontent.com/assets/343840/13019610/16cd2d5e-d196-11e5-8c47-3a605453b888.png)

**Comment by 9tontruck** [comment]
Thanks fdncred.

You are right. There wass no problem on FillPoly. It turned out that my FindContour function returns wrong information. My FindContour keeps returning "contour of edge" instead of contour of region. Please see below code:

        private IplImage RemoveNoise( IplImage image, int minArea )
		{			
			List<CvPoint[]> listOfPoints = new List<CvPoint[]>();

			CvSeq<CvPoint> contoursRaw;
			List<ContourData> contours = new List<ContourData>();
			using( CvMemStorage storage = new CvMemStorage() )
			{
				//find contours
				Cv.FindContours( image, storage, out contoursRaw );

				while( contoursRaw != null )
				{
					CvSeq<CvPoint> result = contoursRaw;
					double area = Cv.ContourArea( result );

					//filter out small regions
					if( area >= minArea )
					{					
						List<CvPoint> points = new List<CvPoint>();
						int i = 0;
						while( result[ i ] != null )
						{
							points.Add( new CvPoint( result[ i ].Value.X, result[ i ].Value.Y ) );
							i++;
						}
						listOfPoints.Add( points.ToArray() );
					
					}
					contoursRaw = contoursRaw.HNext;
				}
			}

			// draw large regions
			IplImage output = new IplImage( image.Size, image.Depth, 1 );
			output.Set( CvColor.Black );
			CvPoint[][] ArrayOfPoints = listOfPoints.ToArray();
			output.FillPoly( ArrayOfPoints, CvColor.White );

			return output;
		}


![untitled-1 copy](https://cloud.githubusercontent.com/assets/5342388/13022028/7bda77c2-d193-11e5-9a49-ae6faf8125b7.jpg)
Upper image is the input image and the bottom one is output image.

What is wrong with my contour detection code?

**Comment by fdncred** [comment]
@9tontruck Have you tried adjusting the contourretrieval or contourchain? I'd start there and then you may want to look at the samples.  From what I see, FindContour is used 24 times in the samples. I'm betting one of them would help your understanding.
```c#
Cv.FindContours(img, storage, out contours, CvContour.SizeOf, ContourRetrieval.Tree, ContourChain.ApproxSimple);
```

**Comment by 9tontruck** [comment]
Thanks fdncred,

I tried what you suggested but I am still getting "contour of edges" .. :S
Would you please help me to get through this?
Here's my code with your suggestion and a sample image. It's a super simple function that removes small area blobs. Would you try to run my code?

		private IplImage RemoveNoise( IplImage image, int minArea )
		{
			
			List<CvPoint[]> listOfPoints = new List<CvPoint[]>();

			CvSeq<CvPoint> contoursRaw;
			
			List<ContourData> contours = new List<ContourData>();
			using( CvMemStorage storage = new CvMemStorage() )
			{
				//find contoures
				//Cv.FindContours( image, storage, out contoursRaw );
				Cv.FindContours( image, storage, out contoursRaw, CvContour.SizeOf, ContourRetrieval.Tree, ContourChain.ApproxSimple );
				//contoursRaw = Cv.ApproxPoly( contoursRaw, CvContour.SizeOf, storage, ApproxPolyMethod.DP, 3, true );

				while( contoursRaw != null )
				{
					CvSeq<CvPoint> result = contoursRaw;
					double area = Cv.ContourArea( result );

					//filter out small regions
					if( area >= minArea )
					{					
						List<CvPoint> points = new List<CvPoint>();
						int i = 0;
						while( result[ i ] != null )
						{
							points.Add( new CvPoint( result[ i ].Value.X, result[ i ].Value.Y ) );
							i++;
						}
						listOfPoints.Add( points.ToArray() );
					
					}
					contoursRaw = contoursRaw.HNext;
				}
			}

			// draw large regions
			IplImage output = new IplImage( image.Size, image.Depth, 1 );
			output.Set( CvColor.Black );
			CvPoint[][] ArrayOfPoints = listOfPoints.ToArray();
			output.FillPoly( ArrayOfPoints, CvColor.White );

			return output;
		}

![01-01_binary](https://cloud.githubusercontent.com/assets/5342388/13056261/27c71090-d3c9-11e5-8563-46075ae44915.jpg)

**Comment by fdncred** [comment]
@9tontruck This may be closer.  I'm not real sure what you're trying to do.
```c#
IplImage input = new IplImage(@"C:\Users\20396600\Downloads\cont.jpg");
IplImage gray = new IplImage(input.Size, BitDepth.U8, 1);
IplImage invert = gray.Clone();
input.CvtColor(gray, ColorConversion.BgrToGray); //Make it gray - could probably skip this and just threshold
gray.Threshold(invert, 70, 255, ThresholdType.BinaryInv); //Make sure it's inverted

private IplImage RemoveNoise(IplImage image, int minArea)
{
    IplImage output = new IplImage(image.Size, BitDepth.U8, 3);//image.Depth, 1);
    output.Set(CvColor.Black);
    CvSeq<CvPoint> contoursRaw;

    using (CvMemStorage storage = new CvMemStorage())
    {
        //find contours
        Cv.FindContours(image, storage, out contoursRaw, CvContour.SizeOf, ContourRetrieval.Tree, ContourChain.ApproxSimple);

        //Taken straight from one of the OpenCvSharp Samples
        using (CvContourScanner scanner = new CvContourScanner(image, storage, CvContour.SizeOf, ContourRetrieval.Tree, ContourChain.ApproxSimple))
        {
            foreach (CvSeq<CvPoint> c in scanner)
            {
                //Some contours come back negative so make them all positive
                double area = Math.Abs(c.ContourArea());
                //Uncomment below to see the area of each contour
                //Console.WriteLine(area.ToString());
                if (area >= minArea)
                {
                    // -1 means filled
                    output.DrawContours(c, CvColor.White, CvColor.Green, 0, -1, LineType.AntiAlias);
                    //Uncomment these two lines to understand which contours area being drawn
                    //Cv.ShowImage("Window", output);
                    //Cv.WaitKey();
                }
            }
        } 
    }
    output.SaveImage("output.png");

    return output;
}
```

**Comment by 9tontruck** [comment]
I wanted to FillPoly instead of DrawContours becuase I need to tweak the coordinates little bit - I need to smooth curves. It seems like I cannot make a custom CvSeq<CvPoint> object and that was the reason why I stored all of the points into point array.

DrawContours works as it's supposed to. But I still have a problem on FillPoly :S

**Comment by fdncred** [comment]
@9tontruck Works pretty much the same.
```c#
IplImage input = new IplImage(@"C:\Users\20396600\Downloads\cont.jpg");
IplImage gray = new IplImage(input.Size, BitDepth.U8, 1);
IplImage invert = gray.Clone();
input.CvtColor(gray, ColorConversion.BgrToGray);
gray.Threshold(invert, 70, 255, ThresholdType.BinaryInv);
RemoveNoise(invert, 150);

private IplImage RemoveNoise(IplImage image, int minArea)
{
    IplImage output = new IplImage(image.Size, BitDepth.U8, 3);//image.Depth, 1);
    output.Set(CvColor.Black);
    CvSeq<CvPoint> contoursRaw;

    using (CvMemStorage storage = new CvMemStorage())
    {
        //find contours
        Cv.FindContours(image, storage, out contoursRaw, CvContour.SizeOf, ContourRetrieval.Tree, ContourChain.ApproxSimple);

        //Taken straight from one of the OpenCvSharp samples
        using (CvContourScanner scanner = new CvContourScanner(image, storage, CvContour.SizeOf, ContourRetrieval.Tree, ContourChain.ApproxSimple))
        {
            foreach (CvSeq<CvPoint> c in scanner)
            {
                //Some contours are negative so make them all positive for easy comparison
                double area = Math.Abs(c.ContourArea());
                //Uncomment below to see the area of each contour
                //Console.WriteLine(area.ToString());
                if (area >= minArea)
                {
                    List<CvPoint[]> points = new List<CvPoint[]>();
                    List<CvPoint> point = new List<CvPoint>();
                    foreach (CvPoint p in c.ToArray())
                        point.Add(p);

                    points.Add(point.ToArray());
                    //Use FillPoly instead of DrawContours as requested
                    output.FillPoly(points.ToArray(), CvColor.Red, LineType.AntiAlias);
                    
                    //-1 means fill the polygon
                    //output.DrawContours(c, CvColor.White, CvColor.Green, 0, -1, LineType.AntiAlias);
                    
                    //Uncomment two lines below to see contours being drawn gradually
                    //Cv.ShowImage("Window", output);
                    //Cv.WaitKey();
                }
            }
        } 
    }
    output.SaveImage("output.png");

    return output;
}
```

**Comment by fdncred** [comment]
@9tontruck Before I delete this test code forever I played around with thinning the contours.  Just figured I'd pass it on. The code calculates the moments and from there gets the center of mass.  Then it figures out the euclidean distance between the center and each point on the contour. Then it figures out the angle. Then it recreates each point in the countour 2 pixels closer to the center. Finally it draws the original filled contour in red and the "thinner" one in green.  Again, I was just playing around.
```c#
using (CvContourScanner scanner = new CvContourScanner(image, storage, CvContour.SizeOf, ContourRetrieval.Tree, ContourChain.ApproxSimple))
{
    foreach (CvSeq<CvPoint> c in scanner)
    {
        double area = Math.Abs(c.ContourArea());
        CvMoments m = c.ContoursMoments();
        Point center = new Point(m.M10 / m.M00, m.M01 / m.M00);
        Console.WriteLine(area.ToString());
        if (area >= minArea)
        {
            List<CvPoint[]> points = new List<CvPoint[]>();
            List<CvPoint> point = new List<CvPoint>();
            List<CvPoint> newPoints = new List<CvPoint>();
            foreach (CvPoint p in c.ToArray())
            {
                double distance = Math.Sqrt(Math.Pow(center.X - p.X, 2) + Math.Pow(center.Y - p.Y, 2));
                double angle = Math.Atan2((center.Y - p.Y), (center.X - p.X));
                Point newPoint = new Point(center.X + Math.Cos(angle + Math.PI) * (distance - 2), center.Y + Math.Sin(angle + Math.PI) * (distance - 2));
                point.Add(p);
                newPoints.Add(newPoint);
            }
            points.Add(point.ToArray());
            output.FillPoly(points.ToArray(), CvColor.Red, LineType.AntiAlias);
            points.Clear();
            points.Add(newPoints.ToArray());
            output.FillPoly(points.ToArray(), CvColor.Green, LineType.AntiAlias);

            //output.DrawContours(c, CvColor.White, CvColor.Green, 0, -1, LineType.AntiAlias);
            Cv.ShowImage("Window", output);
            Cv.WaitKey();
        }
    }
}
```
