### ISSUE TITLE
VideoWriter - Encoder issues..   - QUESTION / HELP

### ISSUE THREAD

**Issue by giluriel** [shimat/opencvsharp#184]
Hello all,

My app is creating videos. I'm using vb.net 2015, Windows 7 64bit.
relevant lines are:
`Videoz = New VideoWriter(Destination, FourCC.H264, DFR, mySize, color)`
..
..
`Dim m As Mat = BitmapConverter.ToMat(img2)` 
`Videoz.Write(m)`

If I'm changing the 1st line to FourCC.Prompt and I'm selecting "x264vfw - H.264/MPEG-4 AVC" and then clicking "Configure..."
I'm getting the x264vfw configuration window. inside that window I'm setting my preferred setup and that result in a perfect video file. BTW, in this window I can see that the "VFW FourCC" of that codec is set to H264.

However, If I'm using the 1st line as it quotes here ("FourCC.H264") - I get a zero sized file. :(

Any idea why?
Thanks

**Comment by przemo1983** [comment]
Same for me. File size is 0 when setting FourCC to H264.
giluriel, have you solved this issue?

**Comment by shimat** [comment]
I found a bug of the `vector<Mat>` wrapper. https://github.com/shimat/opencvsharp/pull/577/commits/99b1744a438d2ba316a45ee141b12a208347c4d8
This may be fixed in the next release.
