### ISSUE TITLE
Error C3073 and C2583 when using OpenCV in CLR

### ISSUE THREAD

**Issue by nanostrukturtechniker** [shimat/opencvsharp#185]
When using OpenCVSharp in /clr mode like:

```
    public ref class ImageObject
    {
    public:
        ImageObject();
        ImageObject(const ImageObject %rhs){};
                    .
                    .
        property OpenCvSharp::Mat Img;    //C2582 and C2582
                    .
                    .
    };
```

Are there some methods missing in OpenCVSharp or am I missing something (I don't have too much experience in mixed mode DLLs)...

**Comment by shimat** [comment]
When you use C++/CLI, I recommend you to use native OpenCV.

Please try the following. 
```c++
property OpenCvSharp::Mat ^Img; 
```

**Comment by nanostrukturtechniker** [comment]
OK, thanks. Helped for me :-) Unfortunately, I have to pass my image data in both directions: To C++ with OpenCV and To .net with OpenCVSharp... Elsewise I'd prefer OpenCV, although OpenCVSharp is great!! Thanks again!

**Comment by shimat** [comment]
You can create a managed `OpenCvSharp.Mat` from a native `cv::Mat*` pointer.
```c++
cv::Mat native = cv::imread("abc.jpg");
auto managed = gcnew OpenCvSharp::Mat(IntPtr(&native));
```

The `OpenCvSharp.Mat.CvPtr` property represents native `cv::Mat*` pointer. 
```c++
cv::Mat *native = reinterpret_cast<cv::Mat*>(managed->CvPtr.ToPointer());
```

So, I think there is no need to use OpenCvSharp in C++/CLI. For example, when you have managed Mat and you want to call native function that requires cv::Mat, the following is a solution:
```c++
// C++
__declspec(dllexport) void __cdecl MyThreshold(cv::Mat *src, cv::Mat *dst)
{
    cv::threshold(*src, *dst, 128, 255, cv::THRESH_BINARY);
}
```
```c#
// C#
[DllImport("nativeLibrary.dll")]
public static extern void MyThreshold(IntPtr src, IntPtr dst);
```
```c#
var src = new Mat("abc.jpg");
var dst = new Mat();
MyThreshold(src.CvPtr, dst.CvPtr);
```
