### ISSUE TITLE
StarDetectorSample crushes

### ISSUE THREAD

**Issue by pterodactilus** [shimat/opencvsharp#190]
I try to execute StarDetectorSample. The 2.4.10 version works fine, but 3.1.0 crushes on line 

StarDetector detector = StarDetector.Create(45)

with this message:
Не удается найти точку входа "xfeatures2d_StarDetector_create" в DLL "OpenCvSharpExtern".
can not find entry point ...

Here is a stack trace:

   в OpenCvSharp.NativeMethods.xfeatures2d_StarDetector_create(Int32 maxSize, Int32 responseThreshold, Int32 lineThresholdProjected, Int32 lineThresholdBinarized, Int32 suppressNonmaxSize)
   в OpenCvSharp.XFeatures2D.StarDetector.Create(Int32 maxSize, Int32 responseThreshold, Int32 lineThresholdProjected, Int32 lineThresholdBinarized, Int32 suppressNonmaxSize)
   в SamplesCS.StarDetectorSample.Run() в f:\Программирование проекты\PGMania\Other\Libs\OpenCV\Sample-3.1.0-20160116\Sample-3.1.0-20160116\SamplesCS\Samples\StarDetectorSample.cs:строка 16
   в SamplesCS.Program.Main(String[] args) в f:\Программирование проекты\PGMania\Other\Libs\OpenCV\Sample-3.1.0-20160116\Sample-3.1.0-20160116\SamplesCS\Program.cs:строка 48
   в System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   в System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   в Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   в System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()

**Comment by fdncred** [comment]
See #146. Same reason.
