### ISSUE TITLE
MatchTemplate with Webcam problem

### ISSUE THREAD

**Issue by Flutschi** [shimat/opencvsharp#191]
Hi Guys,

I want to find on my Webcam the smaller picture you see on the bottom.

Right now he recognizes that there should be a picture in there but he finds the same frame at every card i hold under the camera..

he can't destinguish different cards somehow, and i dont know why..

At the bottom you can see the first picture is my camera, then i want to compare that with a smaller version of a file i have on my computer to find out what card i hold under the camera..
The last picture shows that he somehow draws a circle around the right spot but he does that with every other picture i compare it to..

Anyone can help me?

``` vb
Img = cap.QueryFrame()
        globalmin = 10 ^ 10
        globalmax = 0        

For b = 0 To a - 1
            tpl = Cv.LoadImage(CardArrayfromFolder(b), LoadMode.AnyColor)
            NewW = tpl.ROI.Width
            NewH = tpl.ROI.Height
            ResizeFactor = 0.7

            NewImg = Cv.CreateImage(Cv.Size(NewW * ResizeFactor, NewH * ResizeFactor), tpl.Depth, tpl.NChannels)
              Cv.Resize(tpl, NewImg)

            w2.Image = NewImg

            If Img.Height < NewImg.Height Then
                Output.Text = Output.Text + vbNewLine + "Img.Height < NewImg.Height"
                Exit For
            End If

            If Img.Width < NewImg.Width Then
                Output.Text = Output.Text + vbNewLine + "Img.Width < NewImg.Width"
                Exit For
            End If

            Res = Cv.CreateImage(Cv.Size(Img.Width - NewImg.Width + 1, Img.Height - NewImg.Height + 1), BitDepth.F32, 1)

            Cv.MatchTemplate(Img, NewImg, Res, MatchTemplateMethod.SqDiff) 'CCoeffNormed
            Cv.MinMaxLoc(Res, minvalP, maxvalP, minloc, maxloc)
            Output.Text = CardArrayfromFolder(b) + " SqDiff - minvalP: " + minvalP.ToString + "  maxvalP: " + maxvalP.ToString + vbNewLine + Output.Text


            Output.Text = Output.Text + vbNewLine + vbNewLine

            If minvalP < globalmin Then
                globalmin = minvalP
                perfectsize = ResizeFactor
                bestloc = minloc
                bestValue = b
            End If



            Cv.ReleaseImage(Res)
            Cv.ReleaseImage(tpl)
            Cv.ReleaseImage(NewImg)
```

![win_20160224_13_11_13_pro](https://cloud.githubusercontent.com/assets/17320163/13285016/6cb28de8-daf8-11e5-80ff-25a4f2484b20.jpg)
![nettle sentinel](https://cloud.githubusercontent.com/assets/17320163/13285021/72ae24e6-daf8-11e5-81db-402580254297.jpg)
![mana leak](https://cloud.githubusercontent.com/assets/17320163/13285022/72d28782-daf8-11e5-8204-335b6365fe2f.jpg)
![capture](https://cloud.githubusercontent.com/assets/17320163/13285075/d967e00a-daf8-11e5-8b29-f0cf91d5a3e1.PNG)

**Comment by fdncred** [comment]
I think you'll have problems trying to use template matching to identify cards.  The main problem is that template matching is not rotation and scale invariant.  I suggest using SURF, SIFT, or KAZE (opencv3). There are also other techniques such as this one, https://github.com/YenTheFirst/card_scan. He has a 3 part video for matching cards and it's open source.
