### ISSUE TITLE
Reading a dicom image in opencvsharp

### ISSUE THREAD

**Issue by RohiniKamaraj** [shimat/opencvsharp#192]
Hello all!
Well..I am working on image processing. I have tried houghlines code using opencvsharp which i got from internet. But, i need to read a dicom image. Iplimage doesnt support that format.
What will i do now?
is there any other solution for this?
Please help me!

**Comment by fdncred** [comment]
Apparently DICOM is not supported by OpenCV so you'll have to write your own implementation to convert DICOM to Mat.  See these links for more details.

http://answers.opencv.org/question/52181/dicom-images-in-opencv/
http://answers.opencv.org/question/54967/opencv-30-clahe-with-16bit-images/

**Comment by pdoh00** [comment]
I think it's a misunderstanding to think of DICOM as an image. DICOM is a medical protocol, which not only has images, but patient data.  DICOM toolkits exist, which extract the data.  I feel extracting image data from DICOM is outside of the scope of opencv.
