### ISSUE TITLE
多角形の描画方法

### ISSUE THREAD

**Issue by takumi3451** [shimat/opencvsharp#193]
はじめまして、OpenCvSharpを利用させていただいております。

Windowsフォームアプリで動画上の顔にモザイクをかけるアプリを開発しております。
顔の矩形の座標は別のライブラリで取得している状態から、
OpenCvSharpでGraphics#DrawPolygonに当たる書き方はどのようにしたらよろしいでしょうか。
IplImage#DrawPolyLineかなと思っているのですが、CvPointの指定の仕方がよくわかりません。
以下でも描画できているのですが、OpenCvSharpで書いた場合の速度が気になるので質問しました。

    var list = GetFaceDetectionInfo(gray, capture);
    using (Graphics graphics = Graphics.FromImage(bmp))
    using (Pen pen = new Pen(Color.White, 2))
    {
        list.ForEach(x =>
        {
            graphics.DrawPolygon(pen, new System.Drawing.Point[] {
                x.LeftTop,
                x.LeftBottom,
                x.RightBottom,
                x.RightTop
            });
        });
    }

**Comment by shimat** [comment]
おそらくこんな感じかと思います。（`list`の型は適当に書いています。また、面倒なのでLeftTop等がCvPointという前提にしています。）

```c#
void DrawPolygonTest(IplImage img, IEnumerable<Quadrangle> faces)
{
    Point[][] points = faces
        .Select(f => new[]{ f.LeftTop, f.LeftBottom, f.RightBottom, f.RightTop })
        .ToArray();

    Cv.PolyLine(img, points, true, CvColor.White, 2);
}
```

**Comment by takumi3451** [comment]
早急に返信くださりありがとうございます。
無事描画できました。
たぶんpointsの型はCvPointですよね。

**Comment by shimat** [comment]
直しました
