### ISSUE TITLE
OpenCvSharp.CPlusPlus.DenseOpticalFlow.Calc is protected?

### ISSUE THREAD

**Issue by fubukirokka** [shimat/opencvsharp#195]
Is there an interface to use DualTVL1 optical flow?

**Comment by shimat** [comment]
This is just my implementation mistake :bow:

fixed by https://github.com/shimat/opencvsharp/commit/38dc7072d9e208f55e255a7f3fbcd1c952638abc

**Comment by fubukirokka** [comment]
Thank you for your rapid reply :bow:
