### ISSUE TITLE
MatchTemplate with mask abnormal behavior 

### ISSUE THREAD

**Issue by BjornMelgaard** [shimat/opencvsharp#201]
Is this right result from [MatchTemplateSample](https://github.com/shimat/opencvsharp/blob/master/src%2FOpenCvSharp.Sandbox%2FProgram.cs#L120) (i highlighted minLoc and maxLoc)? Why gem isn't selected? Other modes work fine (almost :smile:).
![screenshot_23](https://cloud.githubusercontent.com/assets/7573215/13677580/32ae3668-e6f3-11e5-95a3-1b1fa7ce5b69.png)

Result without mask
![screenshot_24](https://cloud.githubusercontent.com/assets/7573215/13677791/31d08024-e6f4-11e5-8563-134834d4748c.png)

**Comment by fdncred** [comment]
I have not debugged your sample but you may find help by reviewing #182.
