### ISSUE TITLE
Finalizer tries to free memory when the Mat was created from a cvPtr and OpenCV does not manage the Image data

### ISSUE THREAD

**Issue by nanostrukturtechniker** [shimat/opencvsharp#202]
Sorry for the long headline, I'm just trying to summarize my problem:

I'm writing a wrapper for native code containing OpenCV 3.1.
This native code maintains a memory pool for a predefined number of images with the same size. A new Image is create by 
`Mat::Mat(int ndims, const int* sizes, int type, void* data, const size_t* steps=0)`
with data pointing to the memory pool.

In the wrapper, an OpenCVSharp Mat is created from the native Mat with: 
`OpenCvSharp::Mat(System::IntPtr(PointerToNativeMat))`

When the OpenCVSharp::Mat is not used anymore and garbage collected, the finalizer tries to free the native Mat, even if it was created natively leading to a AccessViolation.

**Comment by shimat** [comment]
I am sorry for the late reply. Please try `mat->IsEnabledDispose = false;`
