### ISSUE TITLE
UWP porting

### ISSUE THREAD

**Issue by GibbOne** [shimat/opencvsharp#204]
Is possible to use this project also on Universal Windows Platform?
I found that base OpenCV 3 was already built on UWP: https://blogs.msdn.microsoft.com/lucian/2015/11/27/opencv-building-uwp-binaries/

What's your feeling?

**Comment by JimSEOW** [comment]
https://blogs.msdn.microsoft.com/lucian/2015/11/25/opencv-unsure-how-to-proceed/

**Comment by SpikingNeurons** [comment]
:( I hope to get the support. Will it be possible in near future?

**Comment by shimat** [comment]
same as #256

**Comment by LyalinDotCom** [comment]
There might be a solution now using a bridge project that i found in the UWP sample library here: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraOpenCV

Disclaimer: I have not tested it yet nor fully understand this topic in detail, but i am exploring and wanted to put this note here in case it really is useful to someone
