### ISSUE TITLE
Can ANN_MLP Class have a bug?

### ISSUE THREAD

**Issue by TheDiabolik** [shimat/opencvsharp#206]
Hello,

when i try to create an instance for ANN_MLP class with "new" keyword. It gives a accessible error. When i check the DLL (ver 3.0) i saw constructor define with "protected" keyword. I think its reason for this error. But also in the same class, there is a "Create" method. For old version this method can take a parameters but in ver 3.0 it can not.

Have can i create an instance ANN_MLP and then train it?

Thanks.

**Comment by notenot** [comment]
Hello. I'm sorry, but I have the same question about TrainData class. Does it work correctly now? Because its constructor has no parameters and I don't know how work with it.
Thanks.

**Comment by pdoh00** [comment]
@notenot TrainData is not implemented yet. Check out the source at https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/modules/ml/TrainData.cs

**Comment by pdoh00** [comment]
@TheDiabolik I think you should try using the static Create method. 
```
public static ANN_MLP Create()
	    {
            IntPtr ptr = NativeMethods.ml_ANN_MLP_create();
            return new ANN_MLP(ptr);
	    }
```
Notice that ANN_MLP ctor is protected.

**Comment by TheDiabolik** [comment]
Thanks for answering. 

I saw the method too but i couldnt find how can i pass a parameters (ANN params) when i create it with this.

**Comment by pdoh00** [comment]
Pretty sure you create it then use

```
public virtual bool Train(InputArray samples, SampleTypes layout, InputArray responses)
```
to pass in your training data.

Check out http://docs.opencv.org/3.1.0/db/d7d/classcv_1_1ml_1_1StatModel.html#af96a0e04f1677a835cc25263c7db3c0c&gsc.tab=0 for more information on the parameters.

**Comment by notenot** [comment]
@pdoh00  I'm sorry for being inattentive. Thanks for your help!

**Comment by notenot** [comment]
> Pretty sure you create it then use ... to pass in your training data.
It means this code should work correctly? trainMat and lblMat are Mat.
`var _network = ANN_MLP.Create();
 _network.Train(trainMat, SampleTypes.RowSample, lblMat);`
But I have an exception OpenCvSharp.OpenCVException. Additional information: "The network has not been created. Use method create or the appropriate constructor."

**Comment by TheDiabolik** [comment]
Yes, still i have same problem and i tried to override TrainData class but i couldnt. If you can find a way to solve it please inform me.

**Comment by pdoh00** [comment]
@notenot @TheDiabolik I haven't started using the ML classes yet, but can see that TrainingData overloads are generally not supported yet.  If you can post some training data and result data I could try and help debug.  One thing you could try is a different method(e.g. NaiveBayes) and see if you encounter the same problem.

**Comment by notenot** [comment]
@pdoh00 I use [MNIST database](http://yann.lecun.com/exdb/mnist/) in my work.

**Comment by yalkhorshid** [comment]
Hello,
Has anyone solved the problem with accessing ANN_MLP (protected constructor) and the "Create" method? please give us an update if you fixed the problem.

**Comment by yalkhorshid** [comment]
Hello,
Has anyone solved the problem with accessing ANN_MLP (protected constructor) and the "Create" method? please give us an update if you fixed the problem.

**Comment by shimat** [comment]
probably you should set `layer_sizes`.
https://github.com/opencv/opencv/blob/master/modules/ml/src/ann_mlp.cpp#L668

I'm sorry but the ANN_MLP wrapper does not support `ANN_MLP::setLayerSizes` :bow: It will be added to the next version.
https://github.com/shimat/opencvsharp/commit/f0bcd8e65720c59efe5538cbce0ecfa95b0a9d09
