### ISSUE TITLE
Cv.Load<CvHaarClassifierCascade>() causes memory leak

### ISSUE THREAD

**Issue by djluck** [shimat/opencvsharp#207]
`Cv.Load<CvHaarClassifierCascade>()` returns an object that when disposed, will not release memory allocated, probably because `IsEnabledDispose` is set to false. 

The following code sample replicates and fixes the bug:

```c#
static void Main(string[] args)
{
	for (var i = 0; i < 10000; i++)
	{
		//A potential b.ug in OpenCVSharp marks CvHaarClassifierCascade.IsEnabledDispose = false, preventing the IDispoable pattern from 
		//cleaning up the memory allocated when loading the face detection features
		using (var res = Cv.Load<CvHaarClassifierCascade>("./haarcascade_frontalface_default.xml"))
		{
			//Calling this method cleans up the region of allocated memory correctly. 
                        //Comment out these two lines to reproduce the memory leak.
			var ptr = res.CvPtr;
			NativeMethods.cvReleaseHaarClassifierCascade(ref ptr);
		}
	}
}
```

**Comment by shimat** [comment]
Thanks :+1: 
I changed the type argument of Cv.Load to DisposableCvObject and enabled disposing.
https://github.com/shimat/opencvsharp/commit/a84b15af242f89c6d65bcd37a4589ed4bd7c2cdd

**Comment by djluck** [comment]
Thanks for adding these changes so quickly @shimat. Any idea when the next 2.* release might make it out?

**Comment by shimat** [comment]
Please try this! https://www.nuget.org/packages/OpenCvSharp-AnyCPU/2.4.10.20160316

**Comment by djluck** [comment]
It's looking good. I'm no longer seeing the leak in our applications, thanks for all your help :+1:
