### ISSUE TITLE
FileStorage issue

### ISSUE THREAD

**Issue by arh24** [shimat/opencvsharp#211]
i coded a program for plate recognition in c++ and i wanted to migrate my code to c# i am trying to use opencvcsharp and i learned a lot from your github page, thank u in advance
when i am trying to train my MLP from xlm file unfortunately in c# it give error
i appreciate if u could help me through
part of my code:
        ```
        FileStorage fs;
    fs.open("OCR_9.xml", FileStorage::READ);
    Mat TrainingData1;
    Mat classes2;
    fs["TrainingDataF30"] >> TrainingData1;
    fs["classes"] >> classes2;

```
```

**Comment by saugat** [comment]
did you solved this issue?? I am also stucked in this problem and cannot find any useful tutorial about fileStorage.

**Comment by shimat** [comment]
I am sorry for the late reply. The FileStorage's read functions are not implemented :bow: 
This feature will be added to the next version.
https://github.com/shimat/opencvsharp/commit/3e442efa0d3e7e08e26d88e2f34522b9511117e8

```c#
using (var fs = new FileStorage(fileName, FileStorage.Mode.Read))
{
    int i = fs["foo"].ReadInt();
    Mat m = fs["bar"].ReadMat();
}
```
