### ISSUE TITLE
Problem with OpenCvSharp.VideoWriter

### ISSUE THREAD

**Issue by PhilRounds** [shimat/opencvsharp#213]
I'm trying to save a video from a camera stream, where the video stream is not compatible with the openCV camera.

I get a bitmap, and try to save it to a video using VideoWriter.  The process throws no errors, but the resultant .AVI file is empty even after 2000 writes to it.

I've noticed that neither the constructor nor the .Open method likes to have the second parameter, FourCC, specified but the default AVI would be fine, as long as it works.  When I look at the specs of my VFwriter after it's been opened, all the parameters are correct (size, color, framerate, etc),  It's just that the Write method doesn't actually write a valid Mat

All thoughts welcomed (and by welcomed, I mean I'm begging).

Phil

```c#
try
{
    VFwriter = new OpenCvSharp.VideoWriter();
    VFwriter.Open(theFile, -1, 13, new OpenCvSharp.Size(theBitmap.Width, theBitmap.Height), true);
}
catch (Exception ex2)
{
    MessageBox.Show("Exception at VFWriter.open(...)" + ex2.InnerException.Message);
}
```

Adding to the video is as follows:

```c#
try 
{
    Mat image = BitmapConverter.ToMat(thisone.bmp );
    VFwriter.Write(image);
    if (this.iGrabCounter < 10)
    {
        image.SaveImage("C:\\temp\\image#" + iGrabCounter.ToString() + ".bmp"); 
    }
    // above line is just to verify that the Mat 'image' is valid - it is
    image.Dispose();
    thisone.bmp.Dispose();
}
catch (Exception ex)
{
    MessageBox.Show("Exception in savebmp_dowork" + ex.InnerException.Message);
}
```

**Comment by ioxFR** [comment]
Hi,

I got the same issue on my side. I'm able to do SaveImage it's working fine but when i want to write Mat to create video file, file is not created.

`using (var capture = new VideoCapture())
            {
                capture.Set(CaptureProperty.FrameWidth, 1920);
                capture.Set(CaptureProperty.FrameHeight, 1080);
                capture.Set(CaptureProperty.Fps, 60.0);
                capture.Set(CaptureProperty.FrameCount, 80.0);
                capture.Open(0);
                Size dsize = new Size(capture.FrameWidth, capture.FrameHeight);
                if (!capture.IsOpened())
                    throw new Exception("capture initialization failed");

                using (VideoWriter writer = new VideoWriter(OutVideoFile, FourCC.Prompt, capture.Fps, dsize))
                using (var window = new Window("capture"))
                {
                    // Frame image buffer
                    using (Mat image = new Mat())
                    {
                        var count = 0;
                        // When the movie playback reaches end, Mat.data becomes NULL.
                        while (true)
                        {
                            if (count == 500)
                                break;

                            capture.Read(image); // same as cvQueryFrame
                            if (image.Empty()){
                                break;
                                }
                            image.SaveImage($"C:\\temp\\out{count}.bmp");
                            Console.CursorLeft = 0;
                            Console.Write($"FPS: {capture.Fps} FRAME COUNT {capture.FrameCount}");

                            writer.Write(image);
                            
                            window.ShowImage(image);

                            Cv2.WaitKey(5);
                            count++;
                        }
                    }
                }
            }`

Someone can help us?

Thanks

**Comment by Tum4ik** [comment]
@ioxFR Hi,
you could replace `FourCC.Prompt` to `capture.FourCC` when you create VideoWriter object... in this case the file will be created, but you will not be able to open it in any player ;)  seems a bug

**Comment by seaboye** [comment]
I met the same problem, the VideoWriter object file is not created...
The software is Visual Studio 2017. Codes are as follow.
Can someone experienced help me? Thank you very much.

VideoCapture capture = new VideoCapture(@"E:\video.mp4");
Mat image = new Mat();
capture.Read(image);
Cv2.ImShow("output", image);
OpenCvSharp.Size frame_size = new OpenCvSharp.Size(960, 544);
FourCC codec = FourCC.MPG4;
VideoWriter video_save = new VideoWriter(@"E:\video_save.avi", codec, 60, frame_size, true);
int i = 10;
while (i > 0)
{
i--;
capture.Read(image);
Cv2.ImShow("output2", image);

video_save.Write(image);

//MessageBox.Show(i.ToString());
}
video_save.Release();
