### ISSUE TITLE
CalibrateCamera2(...) error

### ISSUE THREAD

**Issue by 9tontruck** [shimat/opencvsharp#215]
Hi,

I am currently playing with CalibrateCamera2(...) to calculate the distortion coefficients. BUt I keep having this error:

> Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

I think it's because I put wrong size or dimensions on some objects but I can hardly find it..

```
        CvPoint3D32f[] pPointWorldPos = new CvPoint3D32f[ 5 ];
        pPointWorldPos[ 0 ] = new CvPoint3D32f( 100, 100, 0 );
        pPointWorldPos[ 1 ] = new CvPoint3D32f( 200, 200, 0 );
        pPointWorldPos[ 2 ] = new CvPoint3D32f( 300, 300, 0 );
        pPointWorldPos[ 3 ] = new CvPoint3D32f( 400, 400, 0 );
        pPointWorldPos[ 4 ] = new CvPoint3D32f( 500, 500, 0 );

        CvPoint2D32f[] pPointImagePos = new CvPoint2D32f[ 5 ];
        pPointImagePos[ 0 ] = new CvPoint2D32f( 100, 100 );
        pPointImagePos[ 1 ] = new CvPoint2D32f( 200, 200 );
        pPointImagePos[ 2 ] = new CvPoint2D32f( 300, 300 );
        pPointImagePos[ 3 ] = new CvPoint2D32f( 400, 400 );
        pPointImagePos[ 4 ] = new CvPoint2D32f( 500, 500 );

        int nDataPoints = pPointWorldPos.Length;

        CvMat pMatWorldPos = new CvMat( 1, nDataPoints, MatrixType.F32C3, pPointWorldPos );
        CvMat pMatImagePos = new CvMat( 1, nDataPoints, MatrixType.F32C2, pPointImagePos );
        CvMat pMatPosCount = new CvMat( 1, 1, MatrixType.S32C1, nDataPoints );

        float[] intrinsicData = new float[ 9 ];
        float[] distortionData = new float[ 4 ];            

        CvMat intrinsic = new CvMat( 3, 3, MatrixType.F32C1, intrinsicData );
        CvMat distortion = new CvMat( 1, 4, MatrixType.F32C1, distortionData );

        Cv.CalibrateCamera2( pMatWorldPos, pMatImagePos, pMatPosCount, new CvSize(width,height), intrinsic, distortion );
```

Can somebody tell me which part is wrong please?

**Comment by 9tontruck** [comment]
Anyone please?

**Comment by TheMetalMonkey** [comment]
There is a post on the forum which has an example. I recall commiting a fix
to make it work. Please compare your code with the code in the post:
"Request sample Camera calibration for Version 3.0 please"

Toby

**Comment by 9tontruck** [comment]
Thanks Toby, 

I have definitely looked through existing OpenCVSharp sample code that I could find online. The one that you pointed, (https://github.com/shimat/opencvsharp/issues/132) is OpenCVSharp3 version and  the only difference I could find was he used var distCoeffs = new double[8]; and I used var distCoeffs = new double[4];. 

Would you point out the problem of my code as well please?

**Comment by JimSEOW** [comment]
Please add Camera [Calibration sample ](https://github.com/shimat/opencvsharp/issues/132)
