### ISSUE TITLE
Cuda with opencvsharp3

### ISSUE THREAD

**Issue by newuser124** [shimat/opencvsharp#217]
How do you get opencvsharp3 to work with the cuda libraries? I keep getting 0 for Cv2Gpu.GetCudaEnabledDeviceCount(). I can't just replace opencv_gpu with a cuda enabled library from cmake since it uses different dlls such as opencv_world310.dll Could someone list the steps to do so?

Thanks!

**Comment by radunedelcu** [comment]
Hi,

How are your dlls different? 

We tried to use OpenCvSharp with CUDA and had to recompile OpenCV with CUDA enabled - be aware that dlls for OpenCv come in 2 flavors: versiond - debug dll ( 310d.dll ) and version - release dll ( 310.dll ).

**Comment by newuser124** [comment]
Where are you replacing the dlls?

I installed opencvsharp 3.1.0.20160316 through nuget. The dlls I have for opencv are in the native dll folder under packages called

msvcp120.dll
msvcr120.dll
opencv_ffmpeg310_64.dll
opencv_world310.dll
there's also a OpenCvSharpExtern.dll in this folder

I can't find a way to replace the opencv_world310.dll and I'm not sure if I need to. Maybe I'm looking for the opencv dlls in the wrong place?

**Comment by radunedelcu** [comment]
Hmm, this is a bit outside my experience with OpenCVSharp unfortunately. I just downloaded it from here and then replaced the dlls with opencv dlls compiled by me with CUDA enabled.

Maybe someone who used it with nuget can help you more.

**Comment by newuser124** [comment]
Would you mind listing what version you used to do this and the location of the .dll files you replaced? Maybe I could do it without nuget like you did. 

Thanks!

**Comment by radunedelcu** [comment]
Hey,

I used part of this tutorial : https://initialneil.wordpress.com/2014/09/25/opencv-2-4-9-cuda-6-5-visual-studio-2013/ in conjunction with OpenCVSharp 2.4.10 (20 Dec., 2015) when I tried.
