### ISSUE TITLE
IIS use of OpenCVSharp

### ISSUE THREAD

**Issue by LightCZ** [shimat/opencvsharp#221]
I am using OpenCVSharp in running application without any issues, but when i deploy new web-application to IIS it sometimes throw:

> System.TypeInitializationException:
> The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.

with inner exception:

> Delegates cannot be marshaled from native code into a domain other than their home domain.

on line:

`Mat.FromStream(stream, LoadMode.Unchanged)`
where stream is instance of FileStream.

Whats really wierd that it just happens at random, but when it happens it is broken forever until IIS server restart and application redeploy.

**Comment by GertGregers** [comment]
We see the same issue when running tests in VS. The issue appears to be multiple appdomains calling into the original (unloaded) native opencv code. We've tried calling FreeLibrary ourselves until unload returns false, but to no effect. 

You might find this kb article helpful as it mentions asp.net apps specifically: https://support.microsoft.com/en-us/kb/309694

**Comment by andyliuliming** [comment]
@LightCZ  you need to copy the binary

/bin/dll/x64 to the /bin

**Comment by ManyouRisms** [comment]
@andyliuliming Do the instructions say to do that somewhere?

**Comment by M0J0R1S1NG** [comment]
@ManyouRisms It was included in as a post build command but some people removed that because it was causing build errors

**Comment by ManyouRisms** [comment]
Hey great, thanks.

**Comment by mscrivo** [comment]
Has anyone found a solution for this?  We're also seeing the above exceptions at random in a WebAPI project hosted inside of IIS.  It also randomly happens and takes down the worker process when it does.

**Comment by mscrivo** [comment]
yeah, that's not going to fly for us :) .. thanks for the quick response @LightCZ

**Comment by pranavmehta** [comment]
I have the same issue. Was somebody able to get this to resolve. Recycling the App Pool in IIS is the only solution and that is not a practical solution for production environments.

**Comment by andyliuliming** [comment]
@pranavmehta you can take a look at https://www.nuget.org/packages/OpenCvSharpAspDotNet
and that nuget package copy the binary needed for you.

**Comment by pranavmehta** [comment]
Hi @andyliuliming 

Thanks for the quick reply, but unfortunately that did not help much. I still see this exception around 1 in 10 executions or so. Can you tell me whats different in the suggested Nuget package that is missing from the regular package so I can try to debug and fix it for myself.

I've noticed that it fails with the exception a lot more when you're debugging than when you've deployed the code and no breakpoints are being hit.

**Comment by gambled** [comment]
Anybody have updates on this?  
I having this problem in production and do not see it test or during unit testing.  Was working fine for 2 months, now I am having issues.  I have already copied the correct architecture *.dll files from the ..\bin\dll folder to ..\bin.  I am using 3.3.1.   Running on IIS 7.5 with .NET 4.5.2.  Already double-checked that the correct VC++ 2015 Runtime library is installed and running.

I am in a regulated environment which hampers my ability to just try stuff.

**Comment by pranavmehta** [comment]
I couldn't get this resolved so ended up using Emgu library instead.

**Comment by shimat** [comment]
Thank you everyone. I am trying fixing this big problem by #628. 
I also use OpenCvSharp with IIS at work and always face this problem. I am annoyed by it for many years.

Disabling shadow copy is said to be one solution, but I do not believe it much.
https://code.marketing.logos.com/page/2/

**Comment by aymericfraise** [comment]
I'm commenting on this issue because i had the same problem and couldn't find a solution here.

To solve the problem i disabled shadow copying by adding this to the web.config :
```
<configuration>
  <system.web>
    <hostingEnvironment shadowCopyBinAssemblies="false" />
```
(as mentioned in [this](https://stackoverflow.com/a/52152079/11378690) stackoverflow post, and mentioned by @shimat just above)

I'm not completely sure what the actual cause is, probably that OpenCvSharpExtern.dll is a native dll so it is not copied during the shadow copy.
