### ISSUE TITLE
Identify basic shapes

### ISSUE THREAD

**Issue by RuwanH** [shimat/opencvsharp#223]
Are there any sample codes or tutorials for learn about shapes identification in OpencvSharp? 

Thank you!

**Comment by shimat** [comment]
The following (legacy) samples may help you.
https://github.com/shimat/opencvsharp/blob/2.x/sample/CStyleSamplesCS/Samples/Squares.cs
https://github.com/shimat/opencvsharp/blob/2.x/sample/CStyleSamplesCS/Samples/ConvexityDefect.cs
