### ISSUE TITLE
動画ファイルをVideoCaptureを使用して再生するときに関して

### ISSUE THREAD

**Issue by nanahuse** [shimat/opencvsharp#224]
`string filepath = @"hogehoge.mp4";`
`VideoCapture sourcevideo = new VideoCapture(filepath);`
`sourcevideo.IsOpened();
`
上記のようにVideoCaptureでパスを指定して動画ファイルを開くと、IsOpenedがTrueにならずファイルが開いていないようです。
デバッグモードに切り替えて実行したところエラーは表示されませんでしたがブレークポイントを設定しsourcevideoの中身を確認したところ

> 'sourcevideo.Brightness' threw an exception of type 'System.NotSupportedException'

のようにエラーが確認できました。
同様にContrast, Exposure, Gain, Hue, Saturationでも'System.NotSupportedException'となっていました。
flvやtsなど他の形式でも試してみましたが同様に開けませんでした。
なにか処理が足りないのでしょうか？
答えていただけますと幸いです。

環境
version 3.1.0.20160316
windows 10
Visual studio 2015 Community
Release mode

**Comment by shimat** [comment]
とうに確認済みのことなら失礼しますが、
まず、`File.Exists(filepath)`がtrueを返すかどうか。
あとは、ffmpeg (opencv_ffmpeg310.dll) 関係の問題かもしれません。mp4以外のほかの形式はどうなのか。
実装の問題は確認したところでは見つかりませんでした。

**Comment by nanahuse** [comment]
ご返答ありがとうございます
`System.IO.File.Exists(filepath)`がtrueを返すことは確認しております
他にflvやtsのファイル(GOMPlayerの公式サンプルのもの)を試しておりますが同様の結果でした
ffmpegについては少し調べてみようと思います。

質問後にもいろいろと試しているうちにOpenCvSharp 3.1.0.20160316からOpenCvSharp 2.4.10.20160316に変更しコードに`using OpenCvSharp.CPlusPlus;`を加えたところ動画を開けるようになることがわかりました。
