### ISSUE TITLE
Mat[]が１次元の時にメモリリークする

### ISSUE THREAD

**Issue by c13proto** [shimat/opencvsharp#225]
Mat[]を扱う関数で，受け取るMat[]型の次元の変化に対応できるようにしている関数を作りました．
なおこの関数はプログラム中何度も繰り返し呼ばれます．

受け取ったMat[]をCloneして適当な処理をしてからDisposeするのですが，
Mat[]の次元が1の時だけ，恐らくうまくDisposeされずにメモリの使用量が増大していきます．

なお，Mat[]のDisposeはfor文で一つづつ行っています．

開発環境はVS2015でOSはWin7
現在最新版のOpenCV3を使っています

**Comment by shimat** [comment]
問題の見当がつきませんね... :persevere:
次元というのは、`Array`型でいうところの`Rank`のことで合っていますか？ `Mat[]`なら1で、`Mat[,,]` なら3、のような。
それとも`Length`のことですか？

解放部分のコードなど載せていただくとわかるかもしれません。

**Comment by c13proto** [comment]
すみません，Lengthの事です．
Lengthが1の時にメモリリークします．
2~5ではリークしません．

なおこの処理を繰り返し呼び出して行うのですが，
これを1回だけ呼び出した後に再度同じ処理を実行するとLengthが1の時でもリークしないことが分かりました．
たまたま気付いたのですが，プログラムとしては再度実行する間に何もしていないため全く原因がつかめずに居ます．

以下にコードを書きます．

private int 評価結果(Mat[] テンプレート,Mat[] 合成用素材,Mat[] 合成画像,int[][,] 正解座標,int p1, int p2, int p3, int p4, int p5)
 {
            int 検査面数 = テンプレート.Length;
            Mat[] dst = new Mat[検査面数];
            int[] scores = new int[検査面数];
            int width = テンプレート[0].Width;
            int height = テンプレート[0].Height;

（省略）
            
            for(int i=0;i<dst.Length;i++)dst[i].Dispose();

            return (int)scores.Average();
 }

**Comment by c13proto** [comment]
http://schima.hatenablog.com/entry/2015/12/07/235645
この記事を参考に，returnの前に以下のコードを書いてProcessとManagedを出力してみました．

Console.WriteLine("Process:{0:F2}MB / Managed:{1:F2}MB", System.Diagnostics.Process.GetCurrentProcess().WorkingSet64 / 1024.0 / 1024.0,System.GC.GetTotalMemory(false) / 1024.0 / 1024.0);


Lengthが1の時はやはり増大していきます
Process:335.49MB / Managed:6.45MB　　（←途中で止めました）

Lengthが5の時は，差はありつつも増大はしません
Process:134.39MB / Managed:4.17MB
