### ISSUE TITLE
does this project supports the OCRs and ERFilter modules?

### ISSUE THREAD

**Issue by willgart** [shimat/opencvsharp#229]
Hi,

This opencvsharp version is great.
In my case I want to use the OCR and text detections features:
http://docs.opencv.org/3.1.0/d4/d61/group__text.html#gsc.tab=0

is it supported today with opencvsharp?

**Comment by shimat** [comment]
"opencv_contrib" features are not supported today ☹️ 
I'd like to support them someday...
see https://github.com/shimat/opencvsharp/issues/146

**Comment by ManoLazar** [comment]
I ask again : OpenCVSharp3-AnyCPU (v4.0.0.20181129)
does this project supports the OCRs and ERFilter modules
use the OCR and scene text detections features like:

class cv::text::ERFilter
class cv::text::TextDetector

and so on..
