### ISSUE TITLE
The type initializer for 'OpenCvSharp.Mat' threw an exception.

### ISSUE THREAD

**Issue by Joshi-Ravi** [shimat/opencvsharp#230]
When Passing parameter to the
`ProjectPoints(IEnumerable<Point3d> objectPoints,double[] rvec,double[] tvec,double[,] cameraMatrix,double[] distCoeffs,out Point2d[] imagePoints,out double[,] jacobian,double aspectRatio = 0)` 

jacobian i am getting exception.

initializing jacobian as
`double[,] jacobia = new double[3, 3] {{0, 0, 0} ,   {0, 0, 0} , {0, 0, 0}  };`
`Cv2.ProjectPoints(objPointList, r, t, c, distortion, out outputxy1, out jacobia,1);`

![exception](https://cloud.githubusercontent.com/assets/13161939/16415438/d4c7dea0-3d5a-11e6-937c-9dca239f8e91.png)

How to initialize jacobian to remove exception

**Comment by TheMetalMonkey** [comment]
jacobian is an 'out' so no initialisation is required.
I have recently used this function and found that the Point3d should
actually be Point3f (opencv uses 32bit values for points not 64 bit).

I will commit my fix and issue a pull request to shimat.

**Comment by Joshi-Ravi** [comment]
How to resolve ..i replaced point3d->point3f still error coming...
![exception](https://cloud.githubusercontent.com/assets/13161939/16483290/6ac07882-3ed1-11e6-8396-bc108e7fb7ee.png)

**Comment by Joshi-Ravi** [comment]
Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E ...when adding to my project showing error 
![exception](https://cloud.githubusercontent.com/assets/13161939/16487941/7471139a-3eeb-11e6-9664-8c099ddd140e.png)

**Comment by ekyle125** [comment]
Have there been any updates on this bug? Anything I try to do something with Mat results in an initializer exception. If I downgrade to OpenCvSharp3 it works as expected.
