### ISSUE TITLE
Xamarin.Android

### ISSUE THREAD

**Issue by Sturnus** [shimat/opencvsharp#235]
I added the OpenCvSharp3 AnyCpu nuget to my Xamarin.Android application in Visual Studio 2015. I can use the library just fine in my code, but I am getting missing files exceptions while debugging. Are there any libraries other than OpenCvSharp.dll I should be referencing? Has anyone successfully used OpenCvSharp with Xamarin.Android?

**Comment by mattleibow** [comment]
This might be better discussed on #240
