### ISSUE TITLE
how to use umat or opencl like function?

### ISSUE THREAD

**Issue by chenjeff622** [shimat/opencvsharp#238]
i use opencvsharp 3.1 . it seems has umat datatype after opencv 3.0 version. the wiki don't have any umat demo. does someone can help me or give some demo code for umat?

**Comment by dsoronda** [comment]
In [OpenCV documentation](https://www.learnopencv.com/opencv-transparent-api/) we should use umat type but there is no such implementation (yet) in opencvsharp  (or I can't find any).

```cpp
Mat mat = imread("image.jpg", IMREAD_COLOR); 
// Copy Mat to UMat
UMat umat; 
mat.copyTo(umat);
```

**Comment by joreg** [comment]
@shimat could you tell us what it would take to get support for UMat?
Is that something you'd accept a pull-request for? Or is there a way to contract you to do it?

**Comment by Ursanon** [comment]
Hey @shimat! Is this enhancement on your roadmap?

**Comment by Ursanon** [comment]
F5
