### ISSUE TITLE
Xamarin iOS and Android support

### ISSUE THREAD

**Issue by rmarinho** [shimat/opencvsharp#240]
I think this could be an cool feature to work on. What's your idea?

**Comment by kwcoffee1** [comment]
Hi Rui,

That’s an interesting project. I written a couple of Android Apps in Xamarin-CS. But still new to Xamarin and CVSharp3.
The OpenCVSharp3 nuget project is a DotNet add-in. So, is it already compatible to the Xamarin IDE?

King


From: Rui Marinho 
Sent: Sunday, July 31, 2016 6:58 PM
To: shimat/opencvsharp 
Subject: [shimat/opencvsharp] Xamarin iOS and Android support (#240)

I think this could be an cool feature to work on. What's your idea?

**Comment by rmarinho** [comment]
yeah that's cool for windows, and maybe running in XS, but cool is having the same abstraction over OpenCV for any client platform. WPF, iOS, Android, UWP. 

I work at Microsoft/Xamarin but i m not a C expert, but i m glad to help .

**Comment by kwcoffee1** [comment]
I’m a proficient intermediate C# programmer and would like to help as well, but I’m only familiar with the C# .Net platform.
I think Microsoft is now opening the .Net library for compilation into other platforms like iOS and Linux. The Xamarin language
platform allow C# .Net to Android Java transparency. I worked with an opencvsharp library for .Net programming at:
http://shimat.github.io/opencvsharp/html/1bb515b3-6278-49e4-9a33-1054bd279323.htm

The library is a C Sharp wrapper class which interface to the C++ native code dll.

I written a C# code primer to illustrate the code syntax for beginners at:
http://www.codeproject.com/Articles/1085960/Getting-Started-With-OpenCvSharp

**Comment by mattleibow** [comment]
Hey guys, this is a cool idea. I am the guy working on SkiaSharp (a C# wrapper around Google's Skia) (https://github.com/mono/SkiaSharp)
I would like to see if I can help out here. I don't always have the time since I am working alone on SkiaSharp, but maybe I could do something?

I had a few seconds look at the code here and it appears that the first issue would be getting the native libraries built for iOS/Android.

**Comment by mattleibow** [comment]
Hey @rmarinho ! How's it going? Did you get any work done on this at all?

**Comment by rmarinho** [comment]
hey @mattleibow not really was just exploring :)

**Comment by qrzychu** [comment]
Could you provide some help with compiling OpencvsharpExtern for android? If I understand it correctly, this is the only obstacle before using this wrapper in Xamarin.Android.

You could add projects ex OpenCvSharpExtern.Droid and iOS that will just compile and produce .so files and whatever the extension is for iOS

**Comment by TechnikEmpire** [comment]
If this project supports .net core already properly then this it should be a short hop skip and jump (native binaries per supported platforms) to get this working everywhere .net core does.

**Comment by gmlwns2000** [comment]
Hi guys,

Now OpenCvSharp is working on Xamarin! #375

[OpenCvSharp For Xamarin](https://github.com/Kawaian/OpenCvSharp)

**Comment by redcurry** [comment]
I would like to help in getting this library to work with Xamarin.iOS, but I'm not sure how to go about it. Can anyone provide any tips or resources? Thanks.

**Comment by softlion** [comment]
> Hi guys,
> 
> Now OpenCvSharp is working on Xamarin! #375
> 
> [OpenCvSharp For Xamarin](https://github.com/Kawaian/OpenCvSharp)

That's android only. It does work. Now iOS :)
OpenCv native build for iOS (Framework) can't be bound using sharpie.
Maybe a .a file is all what's needed.
