### ISSUE TITLE
CvBlobsを使用した時のガベージコレクタの発生について

### ISSUE THREAD

**Issue by motohashi1020** [shimat/opencvsharp#241]
以下のページを参考にしてラベリング処理を行っています。
　http://schima.hatenablog.com/entry/2014/01/19/120540

カメラからの画像を受け取って処理を行っているのですが
最初のうちは発生しないのですが、5コマ目ぐらいから毎回発生するようになります。
タイミング的にはLabelメソッドを呼び出した時のようです。

バージョンは2.4.10.20160316です。
実装時に注意することなどはありますか？

**Comment by shimat** [comment]
回答が遅すぎて大変申し訳ありません。今更にはなりますが...

GCの発動は環境にもよりますので一概に言いづらいながら、ラベリング内部処理では、IplImageの画素データを毎度`byte[]` にすべてコピーしてから行っています。このbyte[]がそこそこの大きさになるとは思いますので、GCが発生しやすいと思います。

これを抑える手はあるので検討しますが、言い換えますとGCが効く実装になっていて、リークの心配は低い状態です。メモリが潤沢ならばあまり心配はいらないと思われます。
