### ISSUE TITLE
Report: Intel recent driver 21.20.x causes Access Violation during debugging

### ISSUE THREAD

**Issue by YoungjaeKim** [shimat/opencvsharp#243]
It was hard to diagnose but finally I got it.

**System**
- Windows 10 64 bit, Intel graphics (Lenovo thinkpad i7 laptop), VisualStudio 2015 Enterprise.
- OpenCvSharp3-AnyCPU version 3.1.0.20160316~3.1.0.20160622

**Symptom**
- `vshost.exe` is stopped during Visual Studio with 0xC0000005 Access Violation exception.

**How to know**
1. Turn on `Enable native code debugging` option in Project properties.
2. Run the app (will be very slow) and it causes access violation exception on whatever OpenCV line .
3. Read detail message. The message is as below.

> Exception thrown at 0x00007FFD6EAFA73A (igdrcl64.dll) in Visualizer.exe: 0xC0000005: Access violation reading location 0x0000000000000994.

**Solution**
`igdrcl64.dll` is from Intel Graphics driver. For me, it updated 8/10/2016 automatically by Windows Update. In Device Manager, go to Display adapter > Intel HD Graphics. Open Properties window. At there, for me, the driver version is `21.20.xxxx` (forgot detailed number) and Driver Date is 6/xx/2016.
In Driver tab, Click `Roll Back Driver`. The driver will be changed to previous one. mine is `20.19.15.4444`.

Now it works fine.

I think this problem could be raised by many windows laptop as the hardware is almost default ultrabook system.

**Comment by skondratov** [comment]
Have similar error on discrete graphic.

**System**
PC with Core i5-6400 CPU and GTX 950 on board. 

Some time ago i made tests with integrated graphic, installed Intel Graphics Driver. After that switched back to discrete graphics and this problem started annoy me.

Thanks @YoungjaeKim for pointing me right direction. As it occurred, it is not enough to just uninstall Intel Graphics Driver to avoid OpenCL working on GPU. It is required to manually remove *.dll from Windows\System32 and SysWOW64. That is really weird. Why don't include it to uninstallation process..

Info:
https://software.intel.com/en-us/articles/intel-sdk-for-opencl-applications-2013-release-notes

CPU Device Limitations part:
> After you uninstall the the Intel Graphics Driver, you need to remove the following files to make the CPU only runtime package work:
> On 64-bit version of Windows OS:
> C:\Windows\System32\igdbcl64.dll
> C:\Windows\System32\igdfcl64.dll
> C:\Windows\System32\igdrcl64.dll
> C:\Windows\SysWOW64\igdbcl32.dll
> C:\Windows\SysWOW64\igdfcl32.dll
> C:\Windows\SysWOW64\igdrcl32.dll
> On 32-bit version of Windows OS:
> C:\Windows\System32\igdbcl32.dll
> C:\Windows\System32\igdfcl32.dll
> C:\Windows\System32\igdrcl32.dll

Still not clear why it crashes only under vshost.exe. Not sure it is OpenCvSharp problem. But i didn't find better place to leave this info.

**Comment by YoungjaeKim** [comment]
Today, my laptop Windows Update installed **21.20.16.4506**, Driver version **8/19/2016** and I confirmed that it works fine. It could be a bug fixed version.

**Comment by kobewangdd** [comment]
thanks very much
