### ISSUE TITLE
キャプチャー解像度について

### ISSUE THREAD

**Issue by ikeda28** [shimat/opencvsharp#245]
Intensity Shuttle for USB3.0からパソコン画面をキャプチャーしようとしていますが、SD画像であれば
問題無くキャプチャー出来ますが1080iでキャプチャーしようとすると黒い画面になってしまいます。
            m_cap = new VideoCapture();
            m_cap.Set(OpenCvSharp.CaptureProperty.FrameHeight, 1080.0);　// 追加してみた
            m_cap.Set(OpenCvSharp.CaptureProperty.FrameWidth, 1920.0);   // 追加してみた
上記2行を追加してみましたが、変わりはありませんでした。
何がいけないのでしょうか？

**Comment by shimat** [comment]
大変遅くてすみません :bow:
デバイスによっては、OpenCV標準の仕組み (DirectShow?) でサポートしきれない場合があります。私も経験があります。http://schima.hatenablog.com/entry/20090928/1254113351

OpenCV VideoCaptureを使わずに、開発元が提供するSDK等を使用してキャプチャし、その画像データをOpenCVに渡すような設計が必要かもしれません。
