### ISSUE TITLE
LineSegmentDetector <Vec4i> filled with floats

### ISSUE THREAD

**Issue by FickoDeLux** [shimat/opencvsharp#248]
The "Vec4i" seems to be filled with float values.

``` C#
var lsd = LineSegmentDetector.Create(LineSegmentDetectorModes.RefineNone);
var vl = new List<Vec4i>(); // List<Vec4f> is OK!
var oasl = OutputArray.Create(vl);
lsd.Detect(_cvimg, oasl);
```

**Comment by shimat** [comment]
Thanks :+1: 
The native implementation of lsd.Detect seems to always return `lines` as Vec4f. 
https://github.com/opencv/opencv/blob/42fbfb9be0dbb677b1cc4a37617069ded8e1a79d/modules/imgproc/src/lsd.cpp#L417

I added another overload of the Detect method that returns results as managed array for convenience.
https://github.com/shimat/opencvsharp/commit/f5151732413dac0b913431caecc612b24a65fa00
