### ISSUE TITLE
Feature2D Create methods throwing

### ISSUE THREAD

**Issue by Keboo** [shimat/opencvsharp#250]
It would appear that the static Create method on all derived classes of OpenCvSharp.Feature2D are throwing EntryPointNotFoundException.

![image](https://cloud.githubusercontent.com/assets/952248/18494183/7e7b7e20-79c9-11e6-901d-089ef6825f6b.png)

**Comment by fdncred** [comment]
See #146

**Comment by Keboo** [comment]
Thanks, I assume there are no immediate plans to include the contrib module?

**Comment by shimat** [comment]
yes, i have no immediate plans... :bow:
