### ISSUE TITLE
GetBuildInformation AccessViolationException

### ISSUE THREAD

**Issue by dhanarfmlx** [shimat/opencvsharp#255]
Hi @shimat,

I tried to execute GetBuildInformation but I get AccessViolationException (see screenshot). I am using OpenCvSharp3-AnyCPU.3.1.0.20160622 from NuGet. Is this a bug? Or, did I do something wrong?

![image](https://cloud.githubusercontent.com/assets/19921467/18774366/81a31250-8182-11e6-8c28-03b6dc5a7106.png)

**Comment by shimat** [comment]
Thanks! This bug will be fixed in the next version.
https://github.com/shimat/opencvsharp/commit/0e34dc73df1c7f61130afc8556a1c372eb8eaefa
