### ISSUE TITLE
Windows 10 Universal Windows Compile

### ISSUE THREAD

**Issue by utekai** [shimat/opencvsharp#256]
It looks like it's running on .Net framework 2.x.

Can you provide for Windows 10 for .Net Core/UWP?

This would be useful for hololens development. EXTREMELY useful.

It does now run on WIndows 10, but the request is for it to be running as a UWP app.

**Comment by SpikingNeurons** [comment]
Please add the support for UWP. Also, update us  about when you will add support . It will be very useful.

**Comment by shimat** [comment]
Sorry for the delay. The latest package contains `netstandard` assembly. This can be used for UWP.
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/project.json#L6
