### ISSUE TITLE
cv::Mat_<float>

### ISSUE THREAD

**Issue by nanoMV** [shimat/opencvsharp#257]
Dear all,

How can i define a variable "cv::Mat_<float>" with opencvsharp ?

Thank you,

**Comment by shimat** [comment]
`cv::MatOfFloat`

**Comment by nanoMV** [comment]
Dear Shimat, 
Thank you for the great wrapper, i want to converts my algorithms (particle filter, correlation filter tracking) from c++ with opencv to OpencvSharp3 and i really need your helps. Thank you

**Comment by fdncred** [comment]
What exactly do you need help with?  The great thing about this implementation is that it is very close to using C++.
