### ISSUE TITLE
How can i solve this c++ code in c#?

### ISSUE THREAD

**Issue by nanoMV** [shimat/opencvsharp#258]
Hi,

I want to convert these c++ code to OpencvSharp

cv::Mat_<float> m_temp = cv::Mat_<float>::zeros(m_temp.size());

In OpencvSharp, cv::Mat_<float>::zeros returns a MatExpr

Thank you,

**Comment by shimat** [comment]
```c#
Mat m_temp = Mat.Zeros(...);
```
see http://shimat.github.io/opencvsharp/html/539419a7-dc3b-2ad2-707b-cee73103e8fd.htm

**Comment by nanoMV** [comment]
How can i  solve this c++ code in c#?
Mat image = ....
uchar v = image.at<uchar>(3,4) + 4;

OpenCvSharp doesn't have uchar type
Thanks

**Comment by shimat** [comment]
|C++|C#|
------------ | -------------
|uchar|byte|
|ushort|char|
|long|int|
|__int64|long|

**Comment by shimat** [comment]
```c#
Mat image = ... // a grayscale image
byte v = image.At<byte>(3,4) + 4;
```

**Comment by nanoMV** [comment]
thank you,
