### ISSUE TITLE
Do you have a plan to produce opencvsharp on .net core ?

### ISSUE THREAD

**Issue by bruceyclee** [shimat/opencvsharp#260]
Do you have a plan to produce opencvsharp on .net core ?

**Comment by shimat** [comment]
The latest OpenCvSharp works on .NET Core. thanks.

**Comment by JetstreamRoySprowl** [comment]
Can you point me to the NuGet package that would work on Windows .NET Core 2.2 without compiler complaint? All of the packages I can seem to find produce this warning: 

Warning	NU1701	Package 'OpenCVSharp 2.4.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.	ImageResize	C:\Clients\AIVideo\ImageResize\ImageResize.csproj	1

**Comment by millennial9** [comment]
@JetstreamRoySprowl  Same problem

**Comment by ShumailaAhmed** [comment]
> Can you point me to the NuGet package that would work on Windows .NET Core 2.2 without compiler complaint? All of the packages I can seem to find produce this warning:
> 
> Warning NU1701 Package 'OpenCVSharp 2.4.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project. ImageResize C:\Clients\AIVideo\ImageResize\ImageResize.csproj 1

Getting the same warning was anyone able to resolve this? I get an error while reading the image.

**Comment by shimat** [comment]
OpenCVSharp 2.4 is obsolete. To use OpenCvSharp on .NET Core, please use the latest nuget package (OpenCvSharp4.*) instead.

**Comment by ShumailaAhmed** [comment]
> OpenCVSharp 2.4 is obsolete. To use OpenCvSharp on .NET Core, please use the latest nuget package (OpenCvSharp4.*) instead.
actually, I am trying to make an old code functional, it was built with OpenCVSharp 2.4. 
Using OpenCvSharp4.* gives my definition errors, is there documentation to translate/ migrate the code from OpenCVSharp to OpenCVSharp4? 

Attaching the screenshot of the error
![cv4](https://user-images.githubusercontent.com/48616120/111421475-dd7a3e00-870e-11eb-8c37-2f4cf46b87f6.PNG)

**Comment by lwqwag** [comment]
some types had a lot change in opencvsharp4 compared with 2.4. so you can change the some type yourself.such as CvMat->Mat,
CvColor->Scalar

**Comment by ShumailaAhmed** [comment]
so there is any documentation on the changes I can refer to for these changes, I was trying to do so ... CvMat>Mat was quite intuitive but not for most of other types unfortunately
