### ISSUE TITLE
BOW bag of word

### ISSUE THREAD

**Issue by zpmmehrdad** [shimat/opencvsharp#261]
how can i use bow in opencvsharp?

**Comment by shimat** [comment]
BOW features will be added to the next version 🙏 

https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/modules/features2d/BOWTrainer.cs
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/modules/features2d/BOWKMeansTrainer.cs
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/modules/features2d/BOWImgDescriptorExtractor.cs

**Comment by zpmmehrdad** [comment]
thanks👍
