### ISSUE TITLE
libOpenCvSharpExtern.so: undefined symbol: _ZTIN2cv16ParallelLoopBodyE

### ISSUE THREAD

**Issue by dsdante** [shimat/opencvsharp#262]
`OpenCvSharpExtern` was compiled successfully, but when I try to use it on a [simple example](https://github.com/shimat/opencvsharp#usage), I get [these errors](http://pastebin.com/raw/jrxpG5tw) (with `MONO_LOG_LEVEL=debug`) with the mentions of an undefined symbol. `ldd libOpenCvSharpExtern.so` doesn't show any links to OpenCV. It looks like a relapse of #85 after the migration of 3.x branch to master.

**Comment by shimat** [comment]
🤔 
please try the following
https://ubuntuforums.org/showthread.php?t=2109967
https://github.com/kyamagu/mexopencv/issues/123

**Comment by fedorkov** [comment]
Thanks for the answer, I'll return to this in a month or two.

**Comment by Hodapp87** [comment]
Seeing this also on NixOS; more details at https://github.com/shimat/opencvsharp/issues/273#issuecomment-277501280
