### ISSUE TITLE
Can't find BilateralFilter.

### ISSUE THREAD

**Issue by OHahn-IfaD** [shimat/opencvsharp#263]
Hi there,

please excuse me being stupid, I am sure I'm missing something obvious.

I am using the NuGet https://www.nuget.org/packages/OpenCvSharp3-AnyCPU/ 
and I want to use the OpenCv function adaptiveBilateralFilter (http://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html?highlight=bilateralfilter#adaptivebilateralfilter),  but I can't find it in OpenCvSharp.

What am I doing wrong?

**Comment by shimat** [comment]
adaptiveBilateralFilter seems to be removed from OpenCV3.0 :cry:
OpenCvSharp2.4.10 still supports the method. https://github.com/shimat/opencvsharp/blob/2.x/src/OpenCvSharp.CPlusPlus/Cv2/Cv2_imgproc.cs#L174
