### ISSUE TITLE
BOW

### ISSUE THREAD

**Issue by zpmmehrdad** [shimat/opencvsharp#268]
hi @shimat 
i download latest version "opencvsharp-3.1.0.20161105" and compiled it when run this 
"var trainer = new OpenCvSharp.BOWKMeansTrainer(1000);" i got this an error =>
Unable to find an entry point named 'features2d_BOWKMeansTrainer_new' in DLL 'OpenCvSharpExtern'.

**Comment by zpmmehrdad** [comment]
hi guy
i solved my problem.i get opencvsharpextern project and compiled it.after an hours i found my problem
@shimat please add #include "features2d_BOW.h" to "features.2d.cpp" 
thanks

**Comment by zpmmehrdad** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5433346/20139855/6bbe480c-a69d-11e6-847c-ab3b45fedbb1.jpg)

new problem

**Comment by shimat** [comment]
I am sorry for the late reply :bow: This is fixed by https://github.com/shimat/opencvsharp/commit/95976675a80eda28dc4fa6491b85b838b14350fc
