### ISSUE TITLE
System.AccessViolationException thrown when using Stitcher.stitch

### ISSUE THREAD

**Issue by lovegu** [shimat/opencvsharp#271]
I am trying to run the sample code provided in this repository.

but I am getting Exception thrown: 'System.AccessViolationException' in OpenCvSharp.dll

I have no problem running other methods, but method from Stitcher throws AccessViolationException.

This is the source I am trying to run
https://github.com/shimat/opencvsharp/blob/master/sample/SamplesCS/Samples/Stitching.cs

**Comment by jujusoso** [comment]
Hello,

I've exactly the same issue when i'm trying to use the stitcher.stitch function.

I've tested to create an inputarray with a list or an array of  Mat and it returns the same error so I think that the Issue comes from the conversion.

Best regards,
