### ISSUE TITLE
Safest way to create new mat from the other one?

### ISSUE THREAD

**Issue by ganzikk02** [shimat/opencvsharp#272]
Hello,
First of all I would like to thank you for amazing wrapper of opencv to c#. However lately I have been experiencing problems with **System.AccessViolation** read or write protected memory and I am kinda helpless now. I am using opencvsharp 2.4. It always crashes on MAT creation from another MAT. I tried using **CopyToMat**, **Clone** and also **new Mat(cvmat)**, however with no success. For your information, the program where it crashes runs through the same code for hundreds - thousands of times before it crashes on Access Violation. So is there any safer method or procedure for mat assignment, or can it be problem with something else?

Thank you in advance

**Comment by Kugi** [comment]
Hi. In my experiences, I recommend you to use Clone() method to create a Mat object from other:
  Mat newMat = srcMat.Clone();

or you can use CopyTo() like below:
  Mat newMat = new Mat(srcMat.Size(), srcMat.Type());
  srcMat.CopyTo(newMat);


When you use the constructor with 'srcMat' like below, the new Mat object is sharing data with original one.
  Mat newMat = new Mat(srcMat);

So, It could make an exception if you access 'newMat' after 'srcMat' has been disposed.


In addition, you'd better to keep your mind on the mothod SubMat() that is also sharing data with original one.

Good luck. :)
