### ISSUE TITLE
StereoBM and StereoSGBM missing compute method

### ISSUE THREAD

**Issue by Eule01** [shimat/opencvsharp#274]
Hi, 
I might be doing something completely wrong but I can find the compute method on StereoBM and StereoSGBM objects. 

I am using "OpenCV3.1 All-in-one package" via nuget in Visual Studio 2015.

I want to calculate the disparity map between the left and right stereo images. 

      ```
            Mat left = BitmapConverter.ToMat(aImageLeft);
            Mat right = BitmapConverter.ToMat(aImageRight);
            int numDisparities = 16;
            int blockSize = 15;
            
            StereoBM stereo = StereoBM.Create(numDisparities, blockSize);

The only think left now is to call:
disparity = stereo.compute(left ,right)

but .compute does not exist.

Any help would be very appreciated.
Thank a lot for the effort of creating this wrapper.

**Comment by shimat** [comment]
Thanks. this is an elementary mistake... .Compute method is added in the next release. https://github.com/shimat/opencvsharp/commit/98af2692e823b9fb09f82d33f88a09b8377efe2b
