### ISSUE TITLE
RNG issue

### ISSUE THREAD

**Issue by mertus** [shimat/opencvsharp#276]
I'm using VS2013, 64 bit and Nuget release with my opencv_world310.dll
If I do

            var r = new OpenCvSharp.RNG(1234);
            var r1 = r.Uniform(0, 10);
            var r2 = r.Uniform(0, 10);
            var r3 = r.Uniform(0, 10);

I get r1 == r2 == r3 == 4

But if I use the c-code, using the same opencv_world310.dll

			auto r = new cv::RNG(1234);
			auto r1 = r->uniform(0, 10);
			auto r2 = r->uniform(0, 10);
			auto r3 = r->uniform(0, 10);

I get r1 == 4, r2 == 6, r3 == 9

However, randu behaves correctly in C# and C++

More information.  The State value of RNG in C# never changes from the seed 1234 while in the C++ code it changes.

So I looked at your code.  The issue appears to be, for example, RNG.schar call core_RNG_operator_schar passing a state variable but that is not by reference anywhere.  Thus the state never changes.  I think if you just put in ref it would work.  I don't know very much about OpenCV but there appears maybe an efficiency issue.  Each time you do a RNG.uniform etc, you recreate a c++ RNG with that seed.  I don't know the cost of that but it could be much more expensive than the Multiply with Carry of a single random generator.

That said, I really don't care about efficiency!  Thanks for all your work

**Comment by shimat** [comment]
Thanks!
