### ISSUE TITLE
Unable to find an entry point named 'face_createLBPHFaceRecognizer'

### ISSUE THREAD

**Issue by DVDima** [shimat/opencvsharp#279]
I've added OpenCvSharp3-AnyCPU via the NuGet Package Manager.
When I run "var recognizer = OpenCvSharp.Face.FaceRecognizer.CreateLBPHFaceRecognizer(1, 8, 8, 8, 123);" I am getting the next error:
"Unable to find an entry point named 'face_createLBPHFaceRecognizer' in DLL 'OpenCvSharpExtern'."

It is working on OpenCvSharp2. The next code: "var recognizer = OpenCvSharp.CPlusPlus.FaceRecognizer.CreateLBPHFaceRecognizer(1, 8, 8, 8, 123);" is working correct.

**Comment by shimat** [comment]
This problem was fixed in the latest release. thanks!
