### ISSUE TITLE
 Window.CreateTrackbar throws exception when trackbar is clicked

### ISSUE THREAD

**Issue by flamoedo** [shimat/opencvsharp#281]
The methods Window.CreateTrackbar, or CvTrackbar, both creates a trackbar in some window, but when it is clicked the program throws a exception.

InvalidVariant occurred
Message: Managed Debugging Assistant 'InvalidVariant' has detected a problem in 'C:\....\Visual Studio 2015\Projects\image\image\bin\Debug\image.vshost.exe'.
Additional information: Uma VARIANT inválida foi detectada durante uma conversão de uma VARIANT não gerenciada em um objeto gerenciado. A transferência de VARIANTs inválidas para o CLR pode causar exceções inesperadas, danos ou perda de dados.

**Comment by VahidN** [comment]
@shimat 
[Here is a sample to reproduce it](https://github.com/VahidN/OpenCVSharp-Samples/blob/master/OpenCVSharpSample08/Program.cs).

**Comment by shimat** [comment]
Thanks! This is fixed in the next release.
