### ISSUE TITLE
some files missing in OpenCvSharp3-AnyCPU 3.2.0.20170110

### ISSUE THREAD

**Issue by ItoldU** [shimat/opencvsharp#286]
OpenCvSharp version 3.2.0.20170110 is installed via NuGet and fails with
`A first chance exception of type 'System.Exception' occurred in OpenCvSharp.dll
Additional information: Failed to find dll "opencv_world320", for processor architecture x86.`

After downgrade using `Update-Package OpenCvSharp3-AnyCPU -Version 3.2.0.20170107` app works fine.

**Comment by shimat** [comment]
Thank you.  opencv_world is no longer necessary.
https://github.com/shimat/opencvsharp/commit/333102834b88ba9cf4a3d0af5f3619cab9d3a5f2
