### ISSUE TITLE
MatOfDouble.FromArray assigns first element to the whole Mat

### ISSUE THREAD

**Issue by redoced** [shimat/opencvsharp#288]
`var m = MatOfDouble.FromArray(0,1);`
results in:
`m.Get<double>(0) == m.Get<double>(1) == 0`

my guess: `core_Mat_nSetD` is broken

**Comment by shimat** [comment]
Thanks 👍 It's fixed in the  next release. https://github.com/shimat/opencvsharp/commit/e0b77dad328aeb5bdf032f6304a7507ba97f2fef

as you say, MatOfDouble.FromArray does not work correctly but other MatXX.FromArray methods work fine 😕
