### ISSUE TITLE
AccessViolationException at OpenCvSharp.NativeMethods.videoio_VideoCapture_operatorRightShift_Mat

### ISSUE THREAD

**Issue by bigjam** [shimat/opencvsharp#290]
Hi,

I capture live tv stream with`videocapture.
I use this  version 3.2.0.20170110  
Sometimes my app crash with this error:

Application: AdsDetectionWF.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at OpenCvSharp.NativeMethods.videoio_VideoCapture_operatorRightShift_Mat(IntPtr, IntPtr) at OpenCvSharp.VideoCapture.Read(OpenCvSharp.Mat) at AdsDetectionWF.MonitoringChannel.Start(Boolean, Boolean) at AdsDetectionWF.Form2+<>c__DisplayClass2_1.<button2_Click>b__0() at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.Execute() at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef) at System.Threading.Tasks.Task.ExecuteEntry(Boolean) at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() `

Any suggestion ?
thx for your help !

**Comment by shimat** [comment]
can you post your code snippet to capture?

**Comment by bigjam** [comment]
`while (true)
                {
                    
                    frameToCapture = new OpenCvSharp.Mat();
                   
                    if (_captureLive.IsOpened())
                    {
                        try
                        {
                            Utils.logger.Trace("We are going to read frame");
                            
                            capSucess = _captureLive.Read(frameToCapture);
                            //capSucess = _captureLive.Grab();
                            //frameToCapture = _captureLive.RetrieveMat();
                            //NativeMethods.videoio_VideoCapture_operatorRightShift_Mat(_captureLive.CvPtr, frameToCapture.CvPtr);
                        }
                        catch (Exception ex)
                        {

                            capSucess = false;
                            Utils.logger.Error(ex," exception for channel {0}", Channel_ID);

                        }
                    }
                    else
                    {
                        capSucess = false;
                        Utils.logger.Trace("Videocapture  is not open !");
                    }

                    if (capSucess)
                    {
                        bool empty = frameToCapture.Empty();
                        if (empty)
                        {
                            EmptyFrameCount++;
                            Utils.logger.Warn("Le frame lu est EMPTY pour la {0} depuis le début du record", EmptyFrameCount);

                        }
                        else
                        {`

**Comment by shimat** [comment]
🤔 

please try the following code
```c#
var frameToCapture = new OpenCvSharp.Mat(); 
while (true)
{
    if (_captureLive.IsOpened())
    {
        try
        {
            Utils.logger.Trace("We are going to read frame");
            capSucess = _captureLive.Read(frameToCapture);
        }
        catch (Exception ex)
        {
            capSucess = false;
            Utils.logger.Error(ex," exception for channel {0}", Channel_ID);
        }
    }
    ...
}
```

**Comment by bigjam** [comment]
I will try.
For information my initialisation, before the while , of frameCapture is :
OpenCvSharp.Mat frameToCapture = null;

THANKS !

**Comment by bigjam** [comment]
24 hours with your code:  it seems to run without crash.... 
It sounds good. I'll continue my test.

I have changed my code  and i have "played" with opencv_ffmeg320 and OpenCvSharpExtern.dll x86 and x64 version ... (My app is build in x86 and the 2 dll above is now x64 version in the parent directory, i don't know if it's correct ?)

Thanks for your help shimat !

**Comment by bigjam** [comment]
Hi,

I reopen this issue because i have few crash these last days...
The error occurs ramdomly, the script can work few hours without crash..
I have notice in my log that when the frame is empty several times in succession the app crash, sometimes...


2 errors in Event Viewer: 

- the first : 
`Application: AdsDetectionWF.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at OpenCvSharp.NativeMethods.videoio_VideoCapture_operatorRightShift_Mat(IntPtr, IntPtr) at OpenCvSharp.VideoCapture.Read(OpenCvSharp.Mat) at AdsDetectionWF.MonitoringChannel.Start(Boolean, Boolean) at AdsDetectionWF.Form2+<>c__DisplayClass2_1.<button2_Click>b__0() at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.Execute() at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef) at System.Threading.Tasks.Task.ExecuteEntry(Boolean) at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() `


- the second, 2 seconds later:
`AdsDetectionWF.exe 
   1.0.0.0 
   5884cb0a 
   opencv_ffmpeg320.dll 
   0.0.0.0 
   58416d22 
   c0000005 
   009f26d8 
   f14 
   01d27ba4ac5c4e08 
   C:\Kanap\AdsDetectionWF.exe 
   C:\Kanap\dll\x86\opencv_ffmpeg320.dll 
   1d62edf8-e799-11e6-958e-4ccc6a61d76a 
`
Or sometimes with OpenCvSharpExtern.dll:
`AdsDetectionWF.exe 
   1.0.0.0 
   5884cb0a 
   OpenCvSharpExtern.dll 
   0.0.0.0 
   5873f28e 
   c0000005 
   013fece7 
   198 
   01d27b8a70656dfc 
   C:\Kanap\AdsDetectionWF.exe 
   C:\Kanap\dll\x86\OpenCvSharpExtern.dll 
   0c609ad3-e78c-11e6-958e-4ccc6a61d76a 
`


Thanks for your help.

**Comment by simonbuehler** [comment]
i have the very same crash on a machine:

```
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.AccessViolationException
   bei OpenCvSharp.NativeMethods.videoio_VideoCapture_operatorRightShift_Mat(IntPtr, IntPtr)
   bei OpenCvSharp.VideoCapture.RetrieveMat()
   bei Mask.model.VideoReader+<>c__DisplayClass13_0+<<ReadFrame>b__0>d.MoveNext()
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon ByRef)
   bei Mask.model.VideoReader+<>c__DisplayClass13_0.<ReadFrame>b__0()
   bei System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

```

how can i dbeug this any further?
