### ISSUE TITLE
Unable to find an entry point named 'face_createLBPHFaceRecognizer'

### ISSUE THREAD

**Issue by Martinses93** [shimat/opencvsharp#293]
Hello,
I already read your last post in terms of fixing this issue but it seems like im still occuring it.
Today i tried both versions of the wrapper the "OpenCvSharp-AnyCPU" and the "OpenCvSharp3-AnyCPU" and it seems like in both versions the bug still occurs.
For example in CV2 the visual studio message was : 

```
An exception of type 'System.EntryPointNotFoundException' occurred in OpenCvSharp.CPlusPlus.dll but was not handled in user code
Additional information: The entry point "contrib_createLBPHFaceRecognizer" could not be found in "OpenCvSharpExtern".
```

If the bug is already fixed then im sorry for the report but somehow im still occuring the problem.

**Comment by shimat** [comment]
Thank you. The bug is already fixed but the nuget packages are not updated.

**Comment by shimat** [comment]
The new nuget package that includes FaceRecognizer functions was released.
