### ISSUE TITLE
Cv2.CvtColor memleak?

### ISSUE THREAD

**Issue by przemo1983** [shimat/opencvsharp#298]
Hi.

I have to use Cv2.CvtColor function in my code. 
This function must be called at least 25 times per a second.

I have code as follows (using OpenCvSharp 3.2.0.20170126):

        private void workerDoReadCamera(object sender, DoWorkEventArgs e)
        {
            using (var capture = new VideoCapture(CaptureDevice.Any, index: 0))
            {                
                var fps = getFps(capture);
                var interval = (int)(1000 / (fps));

                using (Mat frame = new Mat())
                using (Mat temp = new Mat())
                {
                    while (_worker != null && !_worker.CancellationPending)
                    {
                        frame.SetTo(Scalar.Black); 
                        capture.Read(frame);
                        if (frame.Empty())
                            break;

                        if (motionDetection.motion_enabled == true)
                        {                            
                                Cv2.CvtColor(frame, temp, ColorConversionCodes.BGR2GRAY);
                                //Cv2.Dilate(frame, temp, null, iterations: 2);
                                temp.CopyTo(frame);                           
                        }

                        _worker.ReportProgress(0, frame);
                        Thread.Sleep(interval);
                    }
                }
            }
        }

When I use CV2.Dilate function everything works fine. Memory is in normal usage (about 400MB). Picture is changed correctly on PictureBox.

When I use CV2.CvtColor function memory increases to 2GB in very short time. Picture is divided, and at the top on the PictureBox there are 3 same small pictures with gray color overlaying 1/3 of original picture. See attached screenshot.
![cvtcolor_issue](https://cloud.githubusercontent.com/assets/2435251/22485084/82ca50c4-e804-11e6-81b1-0dfd0fd1d268.png)

Is there any mem leak in cvtcolor function or I wrote wrong code?

**Comment by przemo1983** [comment]
I managed to fix the memory leak issue but still have divided image.

_worker.ReportProgress(0, frame); is following code:

      private void workerProgressChanged(object sender, ProgressChangedEventArgs e)
        {
            var image = e.UserState as Mat;                   
            if (image == null) return;
            
            image.SaveImage("image.png"); //please note that in this place image.png is correctly written as gray image to file
            
            pictureBoxIpl1.RefreshIplImage(image); //but please not that after this I have divided picture.
       }

Could You please give me any clue?

**Comment by przemo1983** [comment]
This is very stange to me.

After changing workerProgressChanged to following code:

    private void workerProgressChanged(object sender, ProgressChangedEventArgs e)
    {
        var image = e.UserState as Mat;                   
        if (image == null) return;
        
        image.SaveImage("image.png");

        Bitmap bitmap = image.ToBitmap();
        pictureBoxIpl1.Image = bitmap;
        pictureBoxIpl1.RefreshIplImage();
    }
Now, I have gray frame in the pictureBoxIpl but of cource memory consumption increases twice at least.
Does it mean that pictureBoxIpl1.RefreshIplImage(image) function has some issue in case of Mat gray data?

**Comment by przemo1983** [comment]
Sorry for so many comments.
Finally I found the solution of this.
Maybe it will help someone in the future.

Instead of calling 

      pictureBoxIpl1.RefreshIplImage(image);
Simply call:

       pictureBoxIpl1.ImageIpl = image;
       pictureBoxIpl1.RefreshIplImage();

**Comment by eisendorn** [comment]
> I managed to fix the memory leak issue but still have divided image.

Can you please tell me how you did that? I came across the memory leak issue as well with CV2.CvtColor().

Best regards

Simon
