### ISSUE TITLE
Unusual Memory upload in bitmap conversion to mat and Intptr to mat.

### ISSUE THREAD

**Issue by arman1717** [shimat/opencvsharp#300]
Hi, 

I am Replicating this code for Point Grey camera to opencv:  https://gist.github.com/kevinhughes27/5543668

This line specifically:
```
// convert to OpenCV Mat.
unsigned int rowBytes = (double)rgbImage.GetReceivedDataSize()/(double)rgbImage.GetRows();       
 cv::Mat image = cv::Mat(rgbImage.GetRows(), rgbImage.GetCols(), CV_8UC3, rgbImage.GetData(),rowBytes);
```
Equivalent in OpenCvSharp 3.2 in unsafe code.
```
unsafe
{
uint rowBytes = m_processedImage.receivedDataSize / m_processedImage.rows;
Mat imageIn;
imageIn = new Mat((int)m_processedImage.rows, (int)m_processedImage.cols, MatType.CV_8UC3, (IntPtr)m_processedImage.data, rowBytes);
}
```
Work but memory up to 500MB and some lag.

i too did 2 try with: ` imageIn= BitmapConverter.ToMat(m_processedImage.bitmap); `, 
too work with lag and memory up to 1.4 GB.

Usually the application should not have lag, with the memory regulated at about 125 MB without forcing GC(I do not want to apply it). If directly use: `PictureBox.image =m_processedImage.bitmap;` . Dammm, Memory usage only 85MB (work for a basic app).

What conversion can I do to have the best performance? 
Is there a way to make a real(actual) copy of the data and not just reassigning the pointer to the data?

Thanks for your attention.

**Comment by shimat** [comment]
please try to dispose the Mat instance after calling `cv::waitKey`.

`void BitmapConverter.ToMat(Bitmap, Mat)` is more efficient than `Mat BitmapConverter.ToMat(Bitmap)` if the Mat instance is defined before the loop to capture.
```c#
Mat frame = null;
while(true)
{
    if (frame == null)
        frame = new Mat(rgbImage.GetRows(), rgbImage.GetCols(), MatType.CV_8UC3);

    BitmapConverter.ToMat(m_processedImage.bitmap, frame);
}
```

**Comment by arman1717** [comment]
Thanks for answer so soon shimat. 

This problem was punctual for a USB3 camera from the manufacturer PointGrey but so far I have solved it.

1st problem: is when you perform Bitmap transformation to Mat (Raw >> Bgr >.Bitmap> Mat)* 
`BitmapConverter.ToMat(m_processedImage.bitmap, frame);`  === (lag for this case). 
I read some post and indicated go directly to the pointer. Then use the function of the first post again but Mat instance is defined in the header.

2nd problem:  ToBitmap if you use the windows.forms picturebox. 
For example: `Picbox.Image = dst.ToBitmap();`  The above with dst as variable type Mat.

So,
To solve the first thing I did:

```
 private unsafe void GrabLoop(object sender, DoWorkEventArgs e)
        {
            BackgroundWorker worker = sender as BackgroundWorker;
            while (m_grabImages)
            {
                try
                {
                    m_camera.RetrieveBuffer(m_rawImage);                    
                }
                catch (FC2Exception ex)
                {
                    Debug.WriteLine("Error: " + ex.Message);
                    continue;
                }
                lock (this)           
                {
                    m_rawImage.Convert(PixelFormat.PixelFormatBgr, m_processedImage);
                   // frame = null;         //Also works. ok
                    uint rowBytes = m_processedImage.receivedDataSize / m_processedImage.rows;
                   // if (frame == null)               // Also works. ok                                                       
                    frame = new Mat((int)m_processedImage.rows, (int)m_processedImage.cols, MatType.CV_8UC3, (IntPtr)m_processedImage.data, rowBytes);                   
                }
                worker.ReportProgress(0);
            }
            m_grabThreadExited.Set();
        }
```
And for the second, was to use the control of OpenCvSharp.UserInterface.PictureBoxIpl In the other event:

```
private void captureimage(object sender, ProgressChangedEventArgs e)
        {
            //Space for imaging processing and return to picturebox
            // Picbox.Image = dst.ToBitmap();  // Very lag...
            //  Picbox.Invalidate();            
            PicBoxCV.ImageIpl = dst;
            
        }
```

The memory is OK (so far so good),  Happy now.
Look at these four pictures:  http://imgur.com/a/Q13FC

Thanks.

Att. Alexander Recalde
alexander.recalde@gmail.com
