### ISSUE TITLE
.NETCore, Universal windows app, getting System.Runtime version 4.1.0 issue

### ISSUE THREAD

**Issue by rpysork** [shimat/opencvsharp#301]
.NET CoreとUWPを組み合わせるのは初体験です。
OpenCVSharpはWPFで使わせてもらっています。
ここからは英語に変えます。

The application compiles and runs fine but as soon as the code hits any references to OpenCV library, I get the runtime error saying I have the wrong version of System.Runtime. ( I will paste the error at the bottom for your reference. )  I'm not quite sure but am I having this issue because OpenCV requires system.Runtime 4.1.0 but since I'm using .net core and UWP, it is referencing different version of system.runtime? I've tried loading system.runtime for 4.1.0 via nuget, but I'm getting an error. 

宜しくお願い致します。
"System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)".

**Comment by rpysork** [comment]
I thought a little more info would be helpful. I did tried to install the package as specified here https://www.nuget.org/packages/OpenCvSharp3-AnyCPU/3.2.0.20170110, and said uap10.0 is not supported. So I downloaded the latest dlls from the latest under the release and manually referenced the dll. Then I saw the runtime error from my earlier question.

**Comment by shimat** [comment]
thank you for your report. please try to install the following NuGet package
https://www.nuget.org/packages/OpenCvSharp3-AnyCPU/3.2.0.20170205-beta

**Comment by rpysork** [comment]
I was able to install without an issue! Thank you for your quick resolution!
助かりました！ありがとうございます！

**Comment by rpysork** [comment]
I'm back...I spoke too early since initially I had a run time error I tested further and perhaps the error is still related as I reported above. 

This happened when I tried both of these lines...
Mat src = new Mat("someImage.png", ImreadModes.GrayScale);

 VideoCapture capture = new VideoCapture("somevideo.avi");

Both lines yielded the same error as the following:  "Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

**Comment by shimat** [comment]
😕  could you try to install this nuget package? https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation/

**Comment by rpysork** [comment]
Ok progress!!...now the error has changed to the following:
Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Do I need to install a separate package for this or is it supposed to be installed as a dependency of OpenCvSharp3-AnyCPU?

**Comment by shimat** [comment]
Please try this 🙏  
https://www.nuget.org/packages/OpenCvSharp3-AnyCPU/3.2.0.20170210-beta

Make sure a directory named `dll` is exist in the same directory as your executable file.

If a failure still occurs, try to put OpenCvSharpExtern.dll into the same directory as your executable file. 
It may be helpful to check OpenCvSharpExtern.dll's dependencies using [DependencyWalker](http://www.dependencywalker.com/).

**Comment by rpysork** [comment]
Thank you again for continuing to help me. 

Here's the update.
I got the package specified above installed. Then found that there's dll folder under bin folder as you told me. specifically bin\x64\Debug\dll\x64\ there were opencv_ffmpeg320.dll and OpenCvSharpExtern.dll. 

I then copied those 2 dlls at the root of my project, included in the project. 
This worked when running/debugging on x64 local machine. I was able to display a video using  VideoCapture class with mp4 file.  

Wooo hooo!

What I really needed to do was to capture a live video with windows phone which is hooked up to my PC, so I compiled ARM version.
I found the following folder under bin. \bin\ARM\Debug\dll. However under dll folder, there's only x64 and x86, no ARM. When running the same example as I did above with instanciating VideoCapture class pass in a video file, or doing the following: 
VideoCapture capture = new VideoCapture(CaptureDevice.VFW);

Does not work. It fails to instantiate VidoeCapture object. The exception seems to be telling me that I have the wrong version of dll since I did not find the ARM specific dlls??

Here's the exception:
Failed to create VideoCapture
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
   at OpenCvSharp.VideoCapture..ctor(Int32 index)
   at OpenCvSharp.VideoCapture..ctor(CaptureDevice device)
   at Blank.MainPage.<StartReadingTagAsync>d__3.MoveNext()

**Comment by shimat** [comment]
I tried to build OpenCvSharpExtern.dll for ARM platform. Please try this 🙏 🙏 [OpenCvSharpExtern.zip](https://github.com/shimat/opencvsharp/files/782528/OpenCvSharpExtern.zip)
My ARM debug environment is not working now 😢  so this DLL may not work.
 
It is better to build OpenCV3.2 and OpenCvSharpExtern.dll for ARM by yourself. To build OpenCvSharpExtern.dll, please see #307. OpenCV3.2 lib files for ARM are required before building OpenCvSharpExtern.

**Comment by rpysork** [comment]
The zip you posted did not work unfortunately, I got the same error "Failed to create VideoCapture".

I'm not familiar with rest of the steps you specified. I'm hoping you can help me.

When you say "to build OpenCV3.2", do you mean I need to follow instructions in this link? http://docs.opencv.org/2.4/doc/tutorials/introduction/windows_install/windows_install.html#windows-installation

I've also downloaded the source code for OpenCV3.2 and used cMake targeted ARM which generated as the following image.
![image](https://cloud.githubusercontent.com/assets/5322481/23148471/091a42b0-f7b4-11e6-91e8-bf598d9adc9c.png)

...or did you mean "OpenCvSharp-3.2.0" instead of "OpenCV3.2"? 

The project I'm trying to work on is on Windows using Windows Phone with Windows 10.
Thank you!

**Comment by shimat** [comment]
> When you say "to build OpenCV3.2", do you mean I need to follow instructions in this link? 

Yes. Build ALL_BUILD and INSTALL.

After OpenCV building you can get opencv_xxx320.lib files. Next, please download the OpenCvSharp source files, run cmake (`cmake src`) targeted ARM, and build the OpenCvSharpExtern.vcxproj created by cmake with opencv_xxx320.lib files. 

不慣れなもので、お手数をおかけします :bow: 

> The project I'm trying to work on is on Windows using Windows Phone with Windows 10.

I could not find Windows Phone emulators when the target architecture is ARM.

**Comment by Yihcheng** [comment]
@shimat, will you have a fix to add OpenCvSharpExtern.dll for Linux OS in your future release ?

**Comment by rpysork** [comment]
I've had no luck with building OpenCV. 

I've tried many permutations of different settings within CMake as I am not familiar with what options are needed, and exactly what path needs to be pointed where, as well as what additional installs are needed beyond the description from this site:  http://docs.opencv.org/2.4/doc/tutorials/introduction/windows_install/windows_install.html#windows-installation.
 I downloaded all which were explained in the openCV's page, plus MatLab. 

When trying to open sln file that gets generated via CMake, I'm not able to get a successful builds.

**Comment by shimat** [comment]
(日本語で)
返信が遅れて申し訳ありません。
よくよく調べるとARM以前にx86でも動作できず、諸々がんばっているのですが、すぐにはいかんともし難いとわかりました。#339 をご参照ください。完全に諦めたわけではありませんが、一旦は断念とさせてください。すみません。

そもそもC++/CXでもそこそこ難しい課題のようです。#339にも貼っていますが例えばこれが参考になります。http://blog.goo.ne.jp/yoossh/e/63bc59daa6f6cab4d09104989ccf9cd6

**Comment by matjanos** [comment]
Hi guys!
I'm really keen to have OpenCvSharp working on .NET Core on Linux. I've prepared a Docker image which isolates the problem. It compiles the OpenCv and the OpenCVSharp projects on the top of Microsoft's dotnet image and runs a simple Console application which creates a `Mat` object. 

https://github.com/matjanos/opencvsharp-linux-test

It works well on Windows, but throws an exception when I launch it on Docker container (Debian/jessie):
```
Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke()
```

The Linux version of OpenCvSharpExtern is built and it lives in `/usr/local/lib/libOpenCvSharpExtern.so`.

It works perfectly with VS2017, so you can load the solution and play with it. Basically you can switch between Linux and Windows by setting the Startup project from `docker-compose` to `TestConsoleApp`

WARNING: This docker image builds ages and has 7 GBs after all... It's because of OpenCV dependencies and build tools. If anyone manage to slim it down, please let me know or contribute the project. Anyway it's worth to wait!

**Comment by PArpad** [comment]
Hi Matjanos!

Did you get a solution for your problem?
I have the same issue as you stated above.

Regards:
Arpad

**Comment by vincenzoml** [comment]
Please comment on the solution, I'm also stuck on dotnet core on linux trying to use opencvsharp, same issues.

**Comment by ilyabreev** [comment]
Same problems but on dotnet core on macOS.
