### ISSUE TITLE
Mat.SaveImage causes color change in image

### ISSUE THREAD

**Issue by PhilRounds** [shimat/opencvsharp#302]
I've noticed subtle color changes in images I'm processing in opencvsharp, so I started testing.
I have a jpeg which I read in, then immediately write out using 

```c#
Mat matCompare1;  // Original jpeg
Mat matCompare2;  //  opens saved version of matCompare1

 ImageEncodingParam IEP = new ImageEncodingParam(ImwriteFlags.JpegQuality, 100 );
 string path = System.IO.Path.GetFullPath(ofd.FileName);  // OFD is the OpenFileDialog I used to find my image
matCompare1.SaveImage(path.Replace(".jpg", "_Saved.jpg"), IEP);
matCompare2 = new Mat((path.Replace(".jpg", "_Saved.jpg")

// Looping code over row/column
Vec3b vCompare1= matCompare1.At<Vec3b>(iY, iX);
                    Vec3b vCompare2 = matCompare2.At<Vec3b>(iY, iX);
                    if (vCompare2.Item0 != vCompare1.Item0 || vCompare1.Item1 != vCompare2.Item1 || vCompare1.Item2 != vCompare2.Item2)
                        System.Diagnostics.Trace.WriteLine("vec1 != vec2 @ Row" + iY.ToString() + ", col = " + iX.ToString());

// end looping code
```

I get different values at the vast majority of elements of matCompare1.  Most aren't significant, but some are.

Any ideas?  Are there other parameters I should be using in either the open or save process when working with jpegs to assure I don't change any colors?

Thanks

**Comment by shimat** [comment]
This is because matCompare2 is re-encoded as jpeg even if the JpegQuality parameter is 100. A solution is to use png, bmp or tiff.

**Comment by PhilRounds** [comment]
My code is 
 ImageEncodingParam IEP = new ImageEncodingParam(ImwriteFlags.JpegQuality, 100 );
Mat matCompare1 = new Mat("mypic1.jpg")
matCompare1.Savefile("mypic1_saved.jpg", IEP);
Mat matCompare2 = new Mat("mypic1_saved.jpg);

You're saying I can't expect that mypic1.jpg and mypic1_saved.jpg are identical? That  matCompare1 and matCompare2 aren't the same?

**Comment by shimat** [comment]
> You're saying I can't expect that mypic1.jpg and mypic1_saved.jpg are identical? That matCompare1 and matCompare2 aren't the same?

Yes. 
In the following code matCompare1 and matCompare2 are identical.
```
Mat matCompare1 = new Mat("mypic1.jpg"); 
matCompare1.Savefile("mypic1_saved.png");
Mat matCompare2 = new Mat("mypic1_saved.png);
```
