### ISSUE TITLE
BOWImgDescriptorExtractor.Compute -> Send KeyPoints

### ISSUE THREAD

**Issue by korhun** [shimat/opencvsharp#303]
I hope this is not a silly request but, I have a feeling that there is something wrong with the definition of BOWImgDescriptorExtractor.Compute method. KeyPoints are defined as **out**. How will we send the key points then? In EMGU it is not defined like that. 

I could not able to get a result with the Compute method. The descriptor output is always empty:
```
DescriptorMatcher matcher = new FlannBasedMatcher();//nearest neighbor matcher
                BOWImgDescriptorExtractor bowDE = new BOWImgDescriptorExtractor(featureDetector, matcher);
                bowDE.SetVocabulary(this.Vocabulary);

                Mat samples; Mat responses;
                SVMHelper.GetTrainingData(class_mats, out samples, out responses, (mat) =>
                {
                    Mat desc0 = new Mat();
                    KeyPoint[] kp = featureDetector.Detect(mat, null);

                    int[][] pnts;
                    bowDE.Compute(mat, out kp, desc0, out pnts);
                    //bowDE.Compute(mat, desc0, out pnts);
                    //bowDE.Compute2(mat, out kp, desc0);

                    return desc0;
                }, null);
```

**Comment by korhun** [comment]
That's great, thank you shimat :)

**Comment by korhun** [comment]
Hi shimat. I am checking if the new version has been released almost every day. I would be very happy if you release latest changes soon. Thank you very much..

**Comment by shimat** [comment]
Try the following NuGet package source. The appvayor CI creates NuGet package every time the master is updated.
https://ci.appveyor.com/nuget/opencvsharp-1wksfub2jrci

**Comment by korhun** [comment]
Shimat thank you very much for spending your valuable time for my questions. But I couldn't manage to update with this link. I am using Visual Studio 2015, and update using Package Manager Console (Install-Package OpenCvSharp3-AnyCPU -Version 3.2.0.20170126 for example) I coun't find how to update with https://ci.appveyor.com/nuget/opencvsharp

BTW: I am very happy with using OpenCVSharp. Thank to everyone that is involved on this great project.

**Comment by shimat** [comment]
Please try this command.
```
PM> Install-Package OpenCvSharp3-AnyCPU -Source https://ci.appveyor.com/nuget/opencvsharp -IncludePrerelease
```
