### ISSUE TITLE
BitmapSourceConverter.ToBitmapSource displays RGB not BGR in 16 bits

### ISSUE THREAD

**Issue by mertus** [shimat/opencvsharp#304]
I notices that using 16 bit mats and BitmapSourceConverter displays red as blue and visa versa
Enclosed is a test program that shows this.
You need to put your OpencvSharp DLLs  in the Debug Directory for it to work

[BitmapSourceTest.zip](https://github.com/shimat/opencvsharp/files/768609/BitmapSourceTest.zip)

Once again thank you for all your hard work.
-jam

**Comment by shimat** [comment]
Thank you for your easy-to-follow test program 👍
