### ISSUE TITLE
Noise on Mat

### ISSUE THREAD

**Issue by Kiru32** [shimat/opencvsharp#310]
Hi
I have a issue on copying and creating new Mat
I want to get empty(black) image and I use following code
but except no.1, unexpected noise occurs on the result like capture
is there other way to create empty image or my usage has fault??

1. Mat result = new Mat(src.Size(), src.Type(), Scalar.Black);
2. Mat result = new Mat(src.Size(), src.Type());
3. Mat result = src.EmptyClone();

![em](https://cloud.githubusercontent.com/assets/21092229/23105295/70a0ee50-f720-11e6-808f-ef6aaafe91e4.PNG)

**Comment by shimat** [comment]
Please use `Clone()` instead of `EmptyClone()`. 

```c#
class Mat
{
    public void Clone()
    {
        var result = new Mat(this.Size(), this.Type());
        this.CopyTo(result);
        return result;
    }
    public void EmptyClone()
    {
        var result = new Mat(this.Size(), this.Type());
        return result;
    }
}
```
