### ISSUE TITLE
Email Overload

### ISSUE THREAD

**Issue by fdncred** [shimat/opencvsharp#311]
@shimat Why am I getting emails for old PRs I submitted over and over again.  I've received about a dozen in the last 24 hours.

**Comment by shimat** [comment]
Perhaps this is because I did git push many times to decrease the repository size. I'm sorry to have caused you trouble.
https://confluence.atlassian.com/bitbucket/maintaining-a-git-repository-321848291.html

**Comment by fdncred** [comment]
Perhaps, but I wonder if it has anything with appveyor and automatic builds. Each time listed below I received 2 emails.  These are in central time.

2/20 7:09pm
2/20 5:00pm
2/20 7:28am
2/20 3:38am
2/20 2:06am
2/20 1:23am
2/19 10:59pm
2/19 9:15pm
2/19 8:20pm
2/19 8:55am
2/19 8:16am
2/19 7:53am
2/19 7:32am
2/17 7:05pm
2/17 5:53pm
2/17 7:57am

**Comment by fdncred** [comment]
Haven't received anything in a couple days so I'm closing.
