### ISSUE TITLE
AccessViolationException at SetTo() method with a mask.

### ISSUE THREAD

**Issue by Kugi** [shimat/opencvsharp#314]
Hi,

I tried to use SetTo() with a mask, but it throw an AccessViolationException.

My code snippet is below:
```
	using (Mat graySrc = Cv2.ImRead("C:/test.jpg", ImreadModes.GrayScale))
	using (Mat resultImage = graySrc.Clone())
	using (Mat mask = graySrc.InRange(100, 200))
	{
		resultImage.SetTo(0, mask); // System.AccessViolationException
	}
```

SetTo() without mask(mask==null) has no problem.

If you know what the problem is, please reply me to fix it up.

Thank you :)

**Comment by shimat** [comment]
thanks! this is fixed in https://github.com/shimat/opencvsharp/commit/0b59d0fbf7f6fbea039b7525a69450fa75e45b98

**Comment by georgianjalba** [comment]
Do you have any idea when the next release to nuget will be and if this fix will be included in the release?

Also I think the if (mask == null) should be reversed since if the mask is not null you're not using it.
