### ISSUE TITLE
support for Windows IoT Core (UWP)

### ISSUE THREAD

**Issue by sowsan** [shimat/opencvsharp#321]
Hello -

Does this support Windows IoT core ? https://developer.microsoft.com/en-us/windows/iot/Samples/OpenCV ?

Thanks !

Regards,
Sowmyan

**Comment by shimat** [comment]
Please see #339 . I am sorry but the current OpenCvSharp does not support UWP.

**Comment by JimSEOW** [comment]
For @sowsan, To @shimat  I have seen your #339 
Please check this out. [A managed c++ wrapper for OpenCV 3 for UWP](https://github.com/cvwin/cvwin) is coming. 
C++ OpenCV3 for UWP is now available from Nuget. 
I hope you can re-consider your decision for not supporting UWP - as Windows on ARM will not move fast without .NET OpenCV for UWP.
