### ISSUE TITLE
Cuda Support

### ISSUE THREAD

**Issue by korhun** [shimat/opencvsharp#323]
Hi,

Sorry if this is a stupid question. I could not able to work with GpuMat. Is there a way to work with Cuda support? I've searched for cuda release dlls of OpenCV 3.2 but couldn't find.

I use: OpenCvSharp3-AnyCPU -Source https://ci.appveyor.com/nuget/opencvsharp -IncludePrerelease

**Comment by korhun** [comment]
I have tried with these Cuda supported OpenCV 3.2 relase:
http://jamesbowley.co.uk/build-opencv-v3-2-with-cuda-8-0-and-intel-mkltbb/
Installed Cuda drivers from https://developer.nvidia.com/cuda-downloads
My display adapter is NVIDIA Quadro K600

`int count = Cv2.GetCudaEnabledDeviceCount();`

is still 0.

**Comment by TonyDou** [comment]
I checked the build information of the latest nuget package https://www.nuget.org/packages/OpenCvSharp3-AnyCPU/3.3.1.20171117

  Other third-party libraries:
    Use Intel IPP:               2017.0.3 [2017.0.3]
               at:               C:/libs/opencv/mybuild/3.3.1_x86_vc15_static/3rdparty/ippicv/ippicv_win
    Use Intel IPP IW:            sources (2017.0.3)
                  at:            C:/libs/opencv/mybuild/3.3.1_x86_vc15_static/3rdparty/ippicv/ippiw_win
    Use Lapack:                  NO
    Use Eigen:                   NO
    Use Cuda:                    NO
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO

So CUDA flag is not enabled in the build of the native dlls. Can anyone provide a build with CUDA flag enabled in the Nuget package? Is it straight forward?

**Comment by captainst** [comment]
#450
