### ISSUE TITLE
RTSP memoryleak

### ISSUE THREAD

**Issue by ghost** [shimat/opencvsharp#324]
Hello,

i have problem with version 3.2.0.20170126 which i download from NuGet.

When i use rtsp stream from ip camera as source for VideoCapture then unmanaged memory starts growing around 30mb per hour.
I need my application run 24/7 so this is huge blocker for me.

Can you please take a look on this problem. 

Thank you

**Comment by shimat** [comment]
Can you show me your capturing code? Perhaps some Mat instances are not explicitly disposed.

**Comment by mareknereca** [comment]
I forgot to mention that i using several streams in multiple threads. I used dotMemory profiler.
So here is example of code which makes memory leak aroun 3mb in 1h 30min

            string source = "rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/mp4:bigbuckbunnyiphone_400.mp4";
            VideoCapture _capture = new VideoCapture(source);            
            while (true)
            {
                try
                {

                    if (_capture.Grab())
                    {
                        using (Mat mat = _capture.RetrieveMat())
                        {
                            byte[] bytes = mat.ToBytes(".bmp");
                            //just do something
                            Console.WriteLine(bytes.Length);
                        }
                    }
                    else
                    {
                        _capture.Open(source);
                    }
                //Thread.Sleep(33);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

**Comment by 970065574** [comment]
That is wjat I met. any solution about this?
