### ISSUE TITLE
Error Linking to openCV(?)

### ISSUE THREAD

**Issue by novamahend** [shimat/opencvsharp#327]
Hi,
I used mono in Raspberry Pi 3. I've successed install OpenCvSharp as this step : https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Ubuntu-14.04.

But when I execute your simple example program, I got this error:
TestMono.cs(24,2): error CS0246: The type or namespace name `Mat' could not be found. Are you missing an assembly reference?
TestMono.cs(25,9): error CS0246: The type or namespace name `Mat' could not be found. Are you missing an assembly reference?
TestMono.cs(26,9): error CS0103: The name `Cv2' does not exist in the current context
Compilation failed: 3 error(s), 0 warnings

I've put OpenCvSharp.dll and libOpenCvSharpExtern.so in the same directory as the executable file.
Thank you for helping!

**Comment by novamahend** [comment]
I've fixed it. Thank you! 👍

**Comment by szondvics** [comment]
How did you do it exactly? I get the same error message, when I build with mono, but I can build and run with dotnet command line tool. The problem is, I need it to work with Mono.
