### ISSUE TITLE
static Mat.Diag(Mat) の戻りが正方対角行列になっていない

### ISSUE THREAD

**Issue by takuya-takeuchi** [shimat/opencvsharp#329]
引数に rows x columns 3x1 の行列を渡した結果が 1x1 の行列になってしまっている。
C++で直接 static Mat::diag(Mat&) で 3x1 の行列を渡した結果は 3x3 の行列になります。
OpenCVSharpのソースを見ると、static Mat.Diag(Mat) は、クラスメソッドである cv::Mat::diag(int d) を呼び出しているが、static Mat::diag(Mat&) の実装は、

```
inline Mat Mat::diag(const Mat& d)
{
    CV_Assert( d.cols == 1 || d.rows == 1 );
    int len = d.rows + d.cols - 1;
    Mat m(len, len, d.type(), Scalar(0)), md = m.diag();
    if( d.cols == 1 )
        d.copyTo(md);
    else
        transpose(d, md);
    return m;
}
```
であり、OpenCV::Mat::diag(int d) を呼んでいません。

**Comment by shimat** [comment]
#330 で解決。ありがとうございます 👍
