### ISSUE TITLE
SURF detector fails

### ISSUE THREAD

**Issue by teddy108** [shimat/opencvsharp#331]
Hi,
SURF detector detect() throws an exception.

Sample code:
var image = new Mat(imagePath, ImreadModes.GrayScale);
var minHessian = 400;
var detector = SURF.Create(minHessian);
 var imageKeypoints = detector.Detect(image);

System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenCvSharp.NativeMethods.features2d_Feature2D_detect_Mat1(IntPtr detector, IntPtr image, IntPtr keypoints, IntPtr mask)
   at OpenCvSharp.Feature2D.Detect(Mat image, Mat mask) in C:\Users\shima\Documents\Visual Studio 2015\Projects\opencvsharp\src\OpenCvSharp\Modules\features2d\Feature2D.cs: line 164

**Comment by takuya-takeuchi** [comment]
Hi teddy108.
I found the resolution and fix bugs.
I guess I can send PR soon.

Thank you!!

**Comment by shimat** [comment]
Fixed by #336. thanks!

**Comment by krishnashine** [comment]
hi takuya-takeuchi how did you fix that bug, I am having same problem. could you plese send me link of detail. Thank you

**Comment by takuya-takeuchi** [comment]
Hi, Krishnashine.
This issue has already been fixed and merged.
Please check 7b40cd6669aad39440c20cd4f9fe1c715f8b6f24.
But merged date is March 31 and NuGet library is not updated yet.
