### ISSUE TITLE
OpenCvSharp.Extensions for UWP

### ISSUE THREAD

**Issue by ranborn** [shimat/opencvsharp#332]
First of I want to thank you for your hard work on this project and supporting UWP with your latest release. I have been developing a Windows based tablet application using your package and WPF, but I want to port it to UWP. The package from March 24th works fine for my WPF project, but when I want to implement the same functionality in a UWP project with NetCore 5.2.2 there is no OpenCvSharp.Extensions namespace available. I am specifically looking for the bitmap conversion of Mat using ToWriteableBitmap(). Am I just missing something here or is this functionality not available currently? If so, are you planning to support it in the future or offering a different way to display Mat elements?

**Comment by shimat** [comment]
Please see #339 . I am sorry but I'll remove UWP support fron OpenCvSharp.

**Comment by Alexcandra22** [comment]
Will there OpenCvSharp in UWP be supported in the future?
Are there other ways to combine OpenCv with UWP?

**Comment by JimSEOW** [comment]
@shimat  I have seen your #339 
Please check this out. [A managed c++ wrapper for OpenCV 3 for UWP](https://github.com/cvwin/cvwin) is coming. 
C++ OpenCV3 for UWP is now available from Nuget. 
I hope you can re-consider your decision for not supporting UWP - as Windows on ARM will not move fast without .NET OpenCV for UWP.

**Comment by JimSEOW** [comment]
@shimat  I understand your decision. I just need to keep trying. Have you seen this Nuget for WinOnARM for OpenCV?

Nuget: https://www.nuget.org/packages/OpenCV.Win.Core/ provides

Once Nuget Install e.g. in an empty VS2015 UWP C++ project.
In the packages folder, we get win10-arm native dll and static lib

opencv_core310.dll
opencv_core310d.dll
opencv_core310.lib
opencv_core310d.lib
