### ISSUE TITLE
UWP: System.TypeInitializationException

### ISSUE THREAD

**Issue by wbueschel** [shimat/opencvsharp#333]
Trying to get this to run in a UWP project, I always get a System.TypeInitializationException when trying to, e.g., create a Mat object. I've been fiddling with this for hours, copying DLLs to different locations and trying out different versions of the nuget package.

Is this supposed to work for UWP? If so, what are the exact steps/requirements to get a working UWP app/package?

**Comment by shimat** [comment]
Please see #339 . I am sorry but the current OpenCvSharp does not support UWP.
