### ISSUE TITLE
'OpenCvSharpExtern': The specified module could not be found.

### ISSUE THREAD

**Issue by sarendshorst** [shimat/opencvsharp#339]
Using version `3.2.0.20170324` via NuGet in an UWP project targeting x86 I get the following error.

![exception](https://cloud.githubusercontent.com/assets/4550589/24613999/3c34785e-188a-11e7-8576-2ae3b9a7a0f7.PNG)

Are there any fixes?

**Comment by takuya-takeuchi** [comment]
I also have faced this issue!!

>>shimat-san
FYI

The following code reproduce this issue.

`    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();

            var test = new OpenCvSharp.Mat();
        }
    }`

Excuse me to use Japanese in order to explain my question accurately.

>> shimatさん
OpenCvSharp3-AnyCPU.propsの<Link>dll\x86\OpenCvSharpExtern.dll</Link>を<Link>OpenCvSharpExtern.dll</Link>に変更し、再ビルドすることで、OpenCvSharpExtern.dllをOpenCVSharp.dllと同じ階層に置くように試みましたが、これも意味がありませんでした。
何か他に情報は必要ですか？

**Comment by shimat** [comment]
Thank you all.

I had made the OpenCvSharp NuGet package without knowing that it is difficult to build OpenCV for UWP. 😞 

https://msdn.microsoft.com/en-US/library/mt186162.aspx
https://msdn.microsoft.com/ja-jp/library/mt186162.aspx (Japanese)
> UWP Apps run in a protected environment, and as a result, many Win32, COM, and CRT API calls that might compromise the security of the platform are not allowed. 

In the current OpenCvSharpExtern design, it seems to be hard to change it to work with UWP. I have another big issue that the current OpenCvSharpExtern can not support ARM.
When we use OpenCV with UWP, I think it is easier to use C++/CX. So, I am poorly motivated to support UWP with OpenCvSharp. I will remove UWP (UAP 10.0) support from the OpenCvSharp NuGet.

## References
- http://stackoverflow.com/questions/33489924/can-you-use-c-dlls-in-c-sharp-code-in-a-uwp
- https://mtaulty.com/2016/01/11/windows-10-uwp-and-pinvoke-getnativesysteminfo/
- https://social.msdn.microsoft.com/Forums/en-US/f4440c2d-9386-4df5-9419-6b016cf8b345/uwp-native-pinvoke-dll-compiled-with-mingw?forum=wpdevelop
- https://social.msdn.microsoft.com/Forums/en-US/97de2205-7ddd-4dc2-887c-2cb27a10dffa/uwppinvoke-in-uwp?forum=wpdevelop
- https://github.com/Microsoft/opencv/tree/vs2015-samples#building-for-winrt-10

## Reference (Japanese)
- http://qiita.com/moonmile/items/e3232820de5dc22ac8eb

**Comment by JimSEOW** [comment]
For  @takuya-takeuchi  @Nfear , To  @shimat  I have seen your #339 
Please check this out. [A managed c++ wrapper for OpenCV 3 for UWP](https://github.com/cvwin/cvwin) is coming. 
C++ OpenCV3 for UWP is now available from Nuget. 
I hope you can re-consider your decision for not supporting UWP - as Windows on ARM will not move fast without .NET OpenCV for UWP.

**Comment by shimat** [comment]
Thank you for your information. 

It does not matter that there was no OpenCV binary for UWP. Probably I can easily create it.
The problem is that we can not call the C++ wrapper of OpenCV from .NET UWP code. 
To support UWP, it costs as much effort as making another wrapper.

**Comment by JimSEOW** [comment]
@shimat  I do not understand how Microsoft want to push UWP without addressing .NET need for OpenCV. I have seen that you are also contemplating .NET wrapper for dlib for facial landmark. Are you facing the same issue as above for doing that in UWP?

**Comment by LyalinDotCom** [comment]
It seems Microsoft UWP docs team published the sample (linked below) that uses some sort of C++ bridge library to make it work. 

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraOpenCV

Does this somehow make it possible for OpenCV to work generally now with UWP projects?

Sorry if I'm confusing things i have a lot of ignorance in this topic and just started exploring the OpenCV ecosystem and its capabilities in the last 12 hours :)
