### ISSUE TITLE
file name containing unicode

### ISSUE THREAD

**Issue by magicsgram** [shimat/opencvsharp#342]
Just started using opencvsharp, and is amazed to how awesome and efficient the whole development process has become since using it.

However, Cv2.imread and Cv2.imwrite doesn't seem to take non-ascii characters in the file name

I'm using Windows 10 en-US and the error message I get is

System.ArgumentException: 'Cannot marshal: Encountered unmappable character.'

I get the same error when I use Mat.SaveImage

Is there ways to get around the problem?
Or is there a plan to fix this in the future?

Thanks

**Comment by magicsgram** [comment]
To answer to my original question, 

I guess one workaround will be to open file stream to the original file, and use Mat.FromStream to the file stream.

thanx

**Comment by takuya-takeuchi** [comment]
Hi magicsgram

It is not OpenCVSharp issue. As you know, OpenCVSharp is just OpenCV wrapper.
But OpenCV uses fopen function in imread. Please check and trace https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp.

Refer: https://github.com/opencv/opencv/issues/4292

Thanks

**Comment by magicsgram** [comment]
I see, then we'll have to wait until OpenCV gets it fixed.
In a mean time, opening a file stream to a file within C# and using stream based methods work well in OpenCVSharp (with the minimum performance impact fortunately).
I'll just stick to it for now. Thanks:)
