### ISSUE TITLE
I am using "OpenCvSharp3-AnyCPU" version="3.2.0.20170419" on class library project  

### ISSUE THREAD

**Issue by robela** [shimat/opencvsharp#348]
I got the from nuget 
when i call this function using (Mat imgGray = new Mat(Tempdir, ImreadModes.GrayScale))
i face ar error says {"The type initializer for 'OpenCvSharp.NativeMethods' threw an exception."}

{"The type initializer for 'OpenCvSharp.NativeMethods' threw an exception."}
Plase help me

**Comment by korhun** [comment]
I get the same error plus AccessViolation errors and the main application closes with 3.2.0.20170419 on a project that is working fine with 3.2.0.20170324.
