### ISSUE TITLE
Failed to load OpenCvSharpExtern.dll using .NET Framework 3.5

### ISSUE THREAD

**Issue by LeonidVasilyev** [shimat/opencvsharp#352]
I use OpenCvSharp3-AnyCPU 3.2.0.20170419, .NET Framework 3.5, Visual Studio 2015 on Windows 8.1 x64. Exception is thrown every time. Same code works fine using .NET Framework 4.0 and newer.

Steps to reproduce:
1. Create console application with single Program.cs file:
```c#
using OpenCvSharp;

namespace Foo
{
    class Program
    {
        static void Main(string[] args)
        {
            var mat = new Mat(100, 100, MatType.CV_8UC1, new Scalar(0));
            Cv2.ImShow("test", mat);
            Cv2.WaitKey();
        }
    }
}
```
2. Install OpenCvSharp3-AnyCPU 3.2.0.20170419 using NuGet package manager
3. Launch application using Ctrl+F5

Actual result:
Application crashes with unhandled exception:
>System.TypeInitializationException: The type initializer for 'OpenCvSharp.Mat' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0
x8007007E)
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.Mat..cctor() in C:\projects\opencvsharp\src\OpenCvSharp\Module
s\core\Mat\Mat.cs:line 610
   --- End of inner exception stack trace ---
   at OpenCvSharp.Mat..ctor(Int32 rows, Int32 cols, MatType type, Scalar s)
   at Foo.Program.Main(String[] args)

Expected result:
Black square image is shown

**Comment by thienvu20** [comment]
I got the same problem, in the mean time you can add an initialize an cvSVMparam = new cvSVMParam(); and use mat

**Comment by LeonidVasilyev** [comment]
The `OpenCvSharp.NativeMethods.IsUnix();` call allows me to successfully create matrix instance, yet I couldn't reproduce issue with static constructor in Visual Studio 2015 Community.

**Comment by shimat** [comment]
I found another condition. The problem occurs if P/Invoke class has `[SuppressUnmanagedCodeSecurity]` attribute and the .NET version is 3.5 or older.

https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/PInvoke/NativeMethods.cs#L20

I will remove SuppressUnmanagedCodeSecurity when .NET < 4.0
```c#
#if DOTNET_FRAMEWORK && !net20
[SuppressUnmanagedCodeSecurity]
#endif
static class NativeMethods
{
   ...
```
