### ISSUE TITLE
BOWImgDescriptorExtractor.Compute exception

### ISSUE THREAD

**Issue by nesteffe** [shimat/opencvsharp#354]
I am trying to translate a python application into dotnet core to do image classification but am getting an exception when I try to use the Compute method of the BOWImgDescriptorExtractor class.

```
            var indexParams = new IndexParams();
            var searchParams = new SearchParams(50);

            using (var matcher = new FlannBasedMatcher(indexParams, searchParams))
            using (var kaze = KAZE.Create()){
                Mat gray = new Mat();
                using (var bowde = new BOWImgDescriptorExtractor(kaze, matcher))
                //using (var gray = Cv2.ImDecode(input, ImreadModes.GrayScale)){
                using (var image = Cv2.ImRead(@"C:\Users\<snip>\Documents\cv\tests\photo1.jpg")) {
                    Cv2.CvtColor(image, gray, ColorConversionCodes.BGR2GRAY);
                    Mat vocabulary;
                    using (var fs = new FileStorage(@"data/bow.yaml", FileStorage.Mode.Read)){
                        var data = fs["bow"];
                        vocabulary = data.ReadMat();
                    }

                    bowde.SetVocabulary(vocabulary);

                    var kp = kaze.Detect(gray, null);
                    int[][] arr;
                    var dsc = new Mat();
                    bowde.Compute(gray, ref kp, dsc, out arr);
```

The Compute method always throws the below error.

```
'System.Runtime.InteropServices.SEHException' in OpenCvSharp.dll
```

The exception object doesn't seem to have any more useful information in it. I didn't see any error codes and the InnerException is null.

At first I assumed this was a problem loading the image properly so I tried several different methods, all of which resulted in the same error. Then I guessed there was a problem loading the BOW data from the YAML file, so I wrote all of the code to build the BOW and train a SVM in C# also, but it still throws the same exception on the same method.

```
                foreach(var dir in classes){
                    foreach(var file in Directory.GetFiles(Path.Combine(inputpath, dir))){
                        var gray = new Mat(file, ImreadModes.GrayScale);
                        //var gray = Cv2.ImRead(file, ImreadModes.GrayScale);
                        var kp = kaze.Detect(gray);
                        var dsc = new Mat();
                        int[][] arr;
                        bowde.Compute(gray, ref kp, dsc, out arr); // <-- SEHException here
                        trainlist.Add(dsc);
                        responselist.Add(Array.IndexOf(classes, dir));
                    }
                }
```

The Compute method again throws the SEHException.

I have tried this with 3.2.0.20170324 and 3.2.0.20170419, both show the same behaviour.

Any help determining what may be the problem would be appreciated.

**Comment by takuya-takeuchi** [comment]
You should check http://answers.opencv.org/question/82221/error-using-flann-matcher-for-bowimgdescriptorextractor-in-opencv-python/.

If you wanna use BOWImgDescriptorExtractor, you must use BFMatcher as mathcer.
The following code works.

            var dictionarySize = 2;
            var bowTrainer = new BOWKMeansTrainer(dictionarySize);


            var indexParams = new IndexParams();
            var searchParams = new SearchParams(50);
            
            //using (var matcher = new FlannBasedMatcher(indexParams, searchParams)) <--- not work
            using (var matcher = new BFMatcher())
            using (var kaze = KAZE.Create())
            using (var bowde = new BOWImgDescriptorExtractor(kaze, matcher))
            using (var gray = Image("lenna.png", ImreadModes.GrayScale))
            {
                KeyPoint[] keypoints;
                var descriptors = new Mat();
                kaze.DetectAndCompute(gray, null, out keypoints, descriptors);
                descriptors.ConvertTo(descriptors, MatType.CV_32F);
                bowTrainer.Add(descriptors);
                var codebook = bowTrainer.Cluster();
                
                var kp = kaze.Detect(gray);
                var dsc = new Mat();
                dsc.ConvertTo(dsc, MatType.CV_32F);
                int[][] arr;
                bowde.SetVocabulary(codebook);
                bowde.Compute(gray, ref kp, dsc, out arr);
            }

**Comment by nesteffe** [comment]
Thank you, I will try that when I get back into the office. I am curious why it works in Python with OpenCV 3.2 built from source, maybe the fix referenced in the linked issue didn't make it into the 3.2 release.

**Comment by nesteffe** [comment]
This worked, thank!
