### ISSUE TITLE
Problem compiling on Mac

### ISSUE THREAD

**Issue by torshid** [shimat/opencvsharp#356]
Hi,

I am trying to compile the sources on Mac in order to get the "libOpenCvSharpExtern.so" file, and I read the page "Tutorial for Unix" in the wiki.
But when I make I get this error:

> [  3%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/aruco.cpp.o
> In file included from /Users/MDesk/downloads/opencvsharp/src/OpenCvSharpExtern/aruco.cpp:1:
> In file included from /Users/MDesk/downloads/opencvsharp/src/OpenCvSharpExtern/aruco.h:4:
> /Users/MDesk/downloads/opencvsharp/src/OpenCvSharpExtern/include_opencv.h:24:10: fatal error: 
>       'opencv2/aruco.hpp' file not found
> #include <opencv2/aruco.hpp>
>          ^
> 1 error generated.

Did I completely miss something? Where should I get and place those files?

Thank you.

**Comment by torshid** [comment]
I got the compiling (I had to specify the modules path when compiling OpenCV):

> Install the project...
> -- Install configuration: ""
> -- Installing: /usr/local/lib/libOpenCvSharpExtern.dylib

But I get this error with C#:

> System.DllNotFoundException: libOpenCvSharpExtern.so
>   at (wrapper managed-to-native) OpenCvSharp.NativeMethods:core_Mat_sizeof ()
>   at OpenCvSharp.NativeMethods.TryPInvoke () [0x0000e] in <aa5a7a1155b043e0bef65444c7d350fd>:0 

The file is not found even if I change the extension 'so' to 'dylib' and I place the file in the build folder of the program.
Any idea?

**Comment by shimat** [comment]
Please see http://www.mono-project.com/docs/advanced/pinvoke/dllmap/

```xml
<!-- OpenCvSharpExtern.dll.config -->
<configuration>
  <dllmap dll="OpenCvSharpExtern.dll" target="libOpenCvSharpExtern.dylib" os="osx" />
</configuration>
```

**Comment by torshid** [comment]
I have the same error even with the config file, it is not found, this is the complete error output:

> libOpenCvSharpExtern.dylib
> *** An exception has occurred because of P/Invoke. ***
> Please check the following:
> (1) OpenCV's DLL files exist in the same directory as the executable file.
> (2) Visual C++ Redistributable Package has been installed.
> (3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.
> 
> System.DllNotFoundException: libOpenCvSharpExtern.dylib
>   at (wrapper managed-to-native) OpenCvSharp.NativeMethods:core_Mat_sizeof ()
>   at OpenCvSharp.NativeMethods.TryPInvoke () [0x0000e] in <aa5a7a1155b043e0bef65444c7d350fd>:0 
> 
> Unhandled Exception:
> System.TypeInitializationException: The type initializer for 'OpenCvSharp.Mat' threw an exception. ---> System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: libOpenCvSharpExtern.dylib

These are the files in my build folder:

- libOpenCvSharpExtern.dylib
- OCvTest.exe
- OpenCvSharp.Blob.dll
- OpenCvSharp.dll
- OpenCvSharp.dll.config
- OpenCvSharp.Extensions.dll
- OpenCvSharp.UserInterface.dll
- OpenCvSharpExtern.dll

I appreciate your help.

**Comment by matjanos** [comment]
When you install OpenCV you can install some additional packages "opencv_contib". In order to do this you should use this repository: https://github.com/opencv/opencv_contrib
Then, when you perform cmake on opencv sources, you need to pass additional argument
`cmake -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules <opencv_source_directory>`

**Comment by torshid** [comment]
I already did that as said in my second post. The problem seems to come from OpenCvSharp, as I did not find how the library is loaded on OSX in the source code.

**Comment by torshid** [comment]
Any news?
