### ISSUE TITLE
Issue with vs2017 installed/using vs2017?

### ISSUE THREAD

**Issue by Antagonistic** [shimat/opencvsharp#357]
# Summary of your issue

This is the issue: https://github.com/aspnet/Tooling/blob/master/known-issues-vs2015.md#missing-sdk
Refuses to continue, and not about to change system-wide PATH to exclude paths my other dev projects require.

Attempting to open the solution in VS2017 forces migration which... breaks net20, net40 and net46, while netcoreapp1.0 netstandard1.6 appears to succeed.

# Environment

Windows 10, latest
Visual Studio Community 2015 installed
Visual Studio Community 2017 installed
C++/CLR and .NET Core stuff ticked in VS2017 installer.

## Output:

Build log for VS2017 follows.  It appears that these errors only apply to SOME of the targets.

1>------ Build started: Project: OpenCvSharp, Configuration: Release Any CPU ------
1>Fundamentals\DisposableCvObject.cs(24,22,24,30): warning CS0169: The field 'DisposableCvObject.disposed' is never used
1>OpenCvSharp -> C:\Users\lando\workspace\opencvsharp\src\OpenCvSharp\bin\Release\netstandard1.6\OpenCvSharp.dll
1>Done building project "OpenCvSharp.csproj".
1>Fundamentals\DisposableCvObject.cs(24,22,24,30): warning CS0169: The field 'DisposableCvObject.disposed' is never used
1>OpenCvSharp -> C:\Users\lando\workspace\opencvsharp\src\OpenCvSharp\bin\Release\netcoreapp1.0\OpenCvSharp.dll
1>Done building project "OpenCvSharp.csproj".
1>Fundamentals\DisposableCvObject.cs(24,22,24,30): warning CS0169: The field 'DisposableCvObject.disposed' is never used
1>OpenCvSharp -> C:\Users\lando\workspace\opencvsharp\src\OpenCvSharp\bin\Release\net20\OpenCvSharp.dll
1>Done building project "OpenCvSharp.csproj".
1>Util\Platform.cs(43,18,43,36): error CS0103: The name 'RuntimeInformation' does not exist in the current context
1>Util\Platform.cs(43,50,43,60): error CS0103: The name 'OSPlatform' does not exist in the current context
1>Util\Platform.cs(44,18,44,36): error CS0103: The name 'RuntimeInformation' does not exist in the current context
1>Util\Platform.cs(44,50,44,60): error CS0103: The name 'OSPlatform' does not exist in the current context
1>PInvoke\WindowsLibraryLoader.cs(100,20,100,38): error CS0103: The name 'RuntimeInformation' does not exist in the current context
1>PInvoke\WindowsLibraryLoader.cs(100,52,100,62): error CS0103: The name 'OSPlatform' does not exist in the current context
1>PInvoke\WindowsLibraryLoader.cs(145,60,145,71): error CS1061: 'Type' does not contain a definition for 'GetTypeInfo' and no extension method 'GetTypeInfo' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
1>PInvoke\WindowsLibraryLoader.cs(329,21,329,39): error CS0103: The name 'RuntimeInformation' does not exist in the current context
1>PInvoke\WindowsLibraryLoader.cs(329,53,329,63): error CS0103: The name 'OSPlatform' does not exist in the current context
1>PInvoke\NativeMethods.cs(178,20,178,38): error CS0103: The name 'RuntimeInformation' does not exist in the current context
1>PInvoke\NativeMethods.cs(178,52,178,62): error CS0103: The name 'OSPlatform' does not exist in the current context
1>PInvoke\NativeMethods.cs(179,17,179,35): error CS0103: The name 'RuntimeInformation' does not exist in the current context
1>PInvoke\NativeMethods.cs(179,49,179,59): error CS0103: The name 'OSPlatform' does not exist in the current context
1>Fundamentals\DisposableCvObject.cs(24,22,24,30): warning CS0169: The field 'DisposableCvObject.disposed' is never used
1>Done building project "OpenCvSharp.csproj" -- FAILED.
2>------ Build started: Project: OpenCvSharp.Extensions, Configuration: Release Any CPU ------
2>CSC : error CS0006: Metadata file 'C:\Users\lando\workspace\opencvsharp\src\OpenCvSharp\bin\Release\net40\OpenCvSharp.dll' could not be found
2>Done building project "OpenCvSharp.Extensions.csproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 3 up-to-date, 0 skipped ==========

**Comment by Antagonistic** [comment]
So a bit more work on this.  The following steps work in the main folder:

dotnet migrate

THEN, modify OpenCvSharp.csproj with the following:
<PropertyGroup Condition=" '$(TargetFramework)' == 'net40' ">
    <DefineConstants>$(DefineConstants);DOTNET_FRAMEWORK;net40</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <DefineConstants>$(DefineConstants);DOTNET_FRAMEWORK;net46</DefineConstants>
  </PropertyGroup>
(this is basically adding DOTNET_FRAMEWORK defines.

Then compiling from VS2017 IDE works, OR dotnet build -f net40, but the latter spews hundreds of errors on the Tests project, but the rest actual libraries compile fine.

**Comment by shimat** [comment]
Thanks. I converted the master project from vs2015 into vs2017. The above problem should have been resolved. please try it.
