### ISSUE TITLE
CaptureProperty enum has no member for setting auto focus behavior

### ISSUE THREAD

**Issue by joshberry** [shimat/opencvsharp#358]
The CaptureProperty enum does not include member for CAP_PROP_AUTOFOCUS (38).

# What did you do when you faced the problem?

I'm able to manually set the camera focus (when supported) using the Focus property. However, once I do that, auto-focus is turned off and there's no way turn it back on without completely rebooting the camera.

## Example code:

```
videoCapture.Focus = 15; // This works fine
videoCapture.AutoFocus = true; // This property doesn't exist
```

**Comment by takuya-takeuchi** [comment]
I guess that CAP_PROP_AUTOFOCUS did not exist in OpenCV2.
Ref: http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html

Maybe, OpenCVSharp author just forgot to add new enum value.
