### ISSUE TITLE
Erosion and Dilation mixed?

### ISSUE THREAD

**Issue by strpipe** [shimat/opencvsharp#360]
# Summary of your issue

Using MorphologyEx on a thresholded image with MorphTypes.EROSION actually dilates it and vice versa.

# Environment

VS 2015 on Windows 10 with current nuget package v3.2.0.20170419

## Example code:

Cv2.MorphologyEx(thresholding, morph, MorphTypes.DILATE, elem);

**Comment by shimat** [comment]
It works correctly for me. 
Are you misunderstanding dilation and erosion operation for white and black?
The erosion operation increases black pixels and decreases white pixels.
