### ISSUE TITLE
Please guide me to capture image from Desktop Screen

### ISSUE THREAD

**Issue by gonsalves2003** [shimat/opencvsharp#361]
I am using Visual Studio 2017 C# and am trying to capture a portion of my screen and I already have a transparent form from which I am able to capture the desktop area using OpenCVSharp Rect. The system detects only Mat and not IpImage. Not able to figure out how to capture the image from the Rectangle area selected (ROI)

Please help since I am working on this for last 4 days...

**Comment by shimat** [comment]
You can use partial matrix instead of IplImage's ROI.

```c#
var image = new Mat("foo.png");
var part = new Mat(image, new Rect(10, 10, 192, 168));
```
