### ISSUE TITLE
.Net framework issued

### ISSUE THREAD

**Issue by thienvu20** [shimat/opencvsharp#368]
When we use OpenCVsharp version 2.4.10 with an application in .Net framework 3.5, we meet a problem that we cannot init mat(program crash)
 Mat m_matLFeature = new Mat();
or Mat m_matLFeature = new Mat(100,100,Mattype.CV8UC1);
but if we change framework to 4.0 
or add 
CvSVMParams m_SVMParams = new CvSVMParams();
before init a mat
We can init it
How to fix it

**Comment by shimat** [comment]
please see #352
