### ISSUE TITLE
Cv2.Subtract Method Broken？

### ISSUE THREAD

**Issue by cnSchwarzer** [shimat/opencvsharp#369]
# Summary of your issue
Mat  Image; is a 1 channel grayscale image.
When i use Cv2.Subtract(new Scalar(255),Image,Image) I got a full black image that is absolutely wrong.
But use Image = new Scalar(255) - Image and the result is right.
The results should be same but something is wrong.
# Environment
OpenCvSharp3 - Any CPU

**Comment by cnSchwarzer** [comment]
By the way both result are same in native opencv 2.4.9

**Comment by shimat** [comment]
thanks. I added three overload methods of Subtract to avoid this issue.
![default](https://user-images.githubusercontent.com/4434824/27891935-b4dc1342-6237-11e7-9e79-834479fbf8bd.png)
