### ISSUE TITLE
Mat GetArray

### ISSUE THREAD

**Issue by lyziew** [shimat/opencvsharp#371]
# Summary of your issue
There is some wrong with the method of "GetArray" 
# Environment
Win10 VS2015 x86
# What did you do when you faced the problem?
Create a new Mat,  Ex: a mat named small  size 100*100 type: CV_8UC3
then 
if use  public void GetArray(int row, int col, byte[] data);
```
 byte[] data = new byte[100*100*3];
 small.GetArray(0, 0, data);
```
then it catch Exception
Mat data type is not compatible: CV_8UC3

if Use public void GetArray(int row, int col, Vec3b[] data);
```
  Vec3b[] data = new Vec3b[100*100];
  small.GetArray(0, 0, data);
```
then catch Exception
 Provided data element number (10000) should be multiple of the Mat channels count (3)

**Comment by Kuczylas** [comment]
Why was this closed? I experienced this as well and believe it is still an issue.
Is there any way of fixing this? Any other method i could use?
