### ISSUE TITLE
How to build from source with Windows

### ISSUE THREAD

**Issue by myepros** [shimat/opencvsharp#378]
# Summary of your issue
I am trying to build the opencvsharp library from source but the solution does not load properly in VisualStudio.  The solution explorer shows OpenCVSharp,  OpenCVSharp.Blob, OpenCVSharp.Extensions, OpenCVSharp.UserInterface and OpenCVSharp.Tests as unavailable.  If I try to reload the individual projects I get an error that the default namespace for the project is not correct.

# Environment
Windows 10 x64, VisualStudio 2015

# What did you do when you faced the problem?
I have tried loading the solution in VisualStudio 2015, 2013 and 2017.  

## Output:

```
C:\Users\xxxx_000\Projects\opencvsharp\src\OpenCvSharp\OpenCvSharp.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\xxxx_000\Projects\opencvsharp\src\OpenCvSharp\OpenCvSharp.csproj


```

## What did you intend to be?
Are there any instructions on how to build the project from source?

**Comment by shimat** [comment]
The solution file can only be opened in Visual Studio 2017. 
Despite you use VS2017, you face the problem? :thinking:

**Comment by myepros** [comment]
I have made some progress in the past day.  I am not sure why I had an issue with VS2017 when I originally tried it but now I am able to open the solution.  I must have been confused with the different things I was trying.

I still have a question:  Do I need to use cmake to build the OpenCvSharpExtern dll?  It does not build as a part of the solution and am not sure what steps I need to take to build it correctly.

**Comment by myepros** [comment]
I still need assistance getting opencvsharpextern.dll to build correctly.  What steps / environment are used.  

I am building everything as x86.

I am able to build/debug openCv.  openCvSharp seems to build correctly.  The opencvsharpextern.dll is much smaller than the one installed by NuGet and will not load when running my test application.

Your help is greatly appreciated.

**Comment by shimat** [comment]
1. `git clone https://github.com/shimat/opencvsharp`
1. `git submodule update --init`  to get opencv_files
1. start Visual Studio 2017 and open the OpenCvSharp.sln
    1. Probably you should install VS2017 with VC++2015 compiler option
1. set the build configuration to x86/Release
    1. OpenCvSharpExtern.dll may work only in Release build.
1. build

**Comment by myepros** [comment]
Thank you, that worked.  I originally did not do "git submodule update --init".
 Hopefully just one more question.  I need to modify the opencv library, so I assume I will need to build the opencv library from source and copy the lib files to the opencvsharp/opencv/3.2/x64/vc14/staticlib directory.  Can you give me any guidance?  Thank you again.

**Comment by shimat** [comment]
http://funvision.blogspot.jp/2017/04/opencv-build-and-install-visual-studio.html

set `BUILD_SHARED_LIBS=0` (uncheck) to build as static library.

**Comment by myepros** [comment]
Thank you for your help.  I have everything working now.

**Comment by myepros** [comment]
I would like to make a donation to help support your project.  If you contact me via email maybe we can arrange something.  The domain is b o w m a n x r f dot com.  The name is m a g y a r.  
Please remove this comment after you read it so my email address doesn't get more spam.
