### ISSUE TITLE
MatOfT dispose problem

### ISSUE THREAD

**Issue by VadCher** [shimat/opencvsharp#379]
Hi.

When we creat Mat<TElem, TInherit> fom anothe Mat and then dispose one - memory dealoceted two times:
1 - when disposing  Mat<TElem, TInherit> class
2 - when disposing sourceMat (when GC working)

**Comment by vshawn** [comment]
you are right
here is the case:

            Mat newm = img;                   //work well
            newm.Release();
            img.Release();

            //Mat newm = img.Clone();             //work well
            //img.Release();
            //newm.Release();

            //Mat newm = new Mat(img);          //throw exception when return

            //Mat newm = new Mat(img.Clone());  //throw exception when return

            return;

**Comment by VadCher** [comment]
It is anothe case

var sourceMat = new Mat(10, 20, MatType.CV_64FC1);
var doubleMat = new MatOfDouble(sourceMat);
sourceMat = null;
doubleMat.Dispose(); // after it when GC will working program broken

**Comment by shimat** [comment]
Thanks :+1: This is fixed by https://github.com/shimat/opencvsharp/pull/380/commits/fe3b036c40cbfe8d2df4aff9d2fe25cbd8a09e02
