### ISSUE TITLE
Memory Leak while using operators

### ISSUE THREAD

**Issue by Melodeathguy** [shimat/opencvsharp#391]
# Description

Hey there,

I wanted to do a stress test of a custom filter.
I ran into some memory leaks and tried to isolate the Problem.
When I start this method I get an Exception "u!=0" after passing the while loop around 80 times.
From what I have heared this means there is no more free memory to allocate.
How can this happen even though I dispose the Matrix every single time?

Should the * operator do an inplace operation? 
So why does it seem to allocate memory?

# Environment

I am using OpenCvSharp3-AnyCPU v3.2.0.20170911 and VS2017.
I use Windows 7 and have a 1 TB Harddrive.

# Code
```c#
public void stresstest()
{
	while (true)
	{
		Mat mat = new Mat(new Size(4000, 4000), MatType.CV_8UC1);
		mat *= 4;
		mat.Dispose();
	}
}
```

I found out that this method works if you add the line.
```
System.GC.Collect();
```

Is there a more elegant way?

Thank you very much,
Melodeathguy

**Comment by shimat** [comment]
This is a serious problem and difficult to solve. This is because .NET GC can not know native memory allocation by OpenCV.

Solution 1
```c#
using (Mat mat = new Mat(new Size(4000, 4000), MatType.CV_8UC1))
using (MatExpr mat4expr = mat * 4) // Optional... MatExpr's allocation is small
using (Mat mat4 = matexpr)
{
}
```

Solution 2
```c#
using (var eye = Mat.Eye(src.Size(), src.Type()))
{
    Cv2.Multiply(src, eye, src, 4);
}
```

I think it is effective to repeatedly call GC.Collect because it is difficult to prevent leakage of memory completely.
