### ISSUE TITLE
"LineTypes" do not include the the definition of "Filled"

### ISSUE THREAD

**Issue by shuaxinkong** [shimat/opencvsharp#398]
# "LineTypes" do not include the the definition of "Filled"

# Environment

OpenCvSharp3-AnyCPU(3.2.0.20170911)+OpenCV(3.2.0)+VS2015UP3+WPF

# What did you do when you faced the problem?

// When calling Mat.Rectangle Method (Point, Point, Scalar, Int32, LineTypes, Int32),
// "LineTypes.Filled" should exist with regards to
// https://shimat.github.io/opencvsharp_docs/html/061b9b43-3fbe-61ac-69d9-ab8046163ba0.htm

## Example code:

```
  private static void test()
        {
            Mat test = new Mat(new Size(333, 256), MatType.CV_8UC3, Scalar.All(0));
            test.Rectangle(
                new Point(0, 0),
                new Point(256, 255),
                new Scalar(0, 0, 255),
                1,
                LineTypes.Filled // ERROR! "LineTypes" do not include the the definition of "Filled"
                );
            using (new Window("histMat", test))
            {
                Cv2.WaitKey();
            }

        }
```
<img width="455" alt="default" src="https://user-images.githubusercontent.com/16322322/31923925-509d0e52-b8b0-11e7-9339-d3db1434a885.png">

**Comment by shimat** [comment]
Please see #370

**Comment by shuaxinkong** [comment]
Did you mean I should correct the code like this:
  test.Rectangle(
                new Point(0, 0),
                new Point(256, 255),
                new Scalar(0, 0, 255),
                -1
                );
