### ISSUE TITLE
Selective Search Segmentation for proposed ROI

### ISSUE THREAD

**Issue by deepakkumar1984** [shimat/opencvsharp#401]
Is there any Selective Segmentation function implemented in C# version similar to the code below:
Need this for Fast RCNN object detection implementation in C#.

    ss = cv2.ximgproc.segmentation.createSelectiveSearchSegmentation()
 
    # set input image on which we will run segmentation
    ss.setBaseImage(im)
 
    # Switch to fast but low recall Selective Search method
    if (sys.argv[2] == 'f'):
        ss.switchToSelectiveSearchFast()
 
    # Switch to high recall but slow Selective Search method
    elif (sys.argv[2] == 'q'):
        ss.switchToSelectiveSearchQuality()
    # if argument is neither f nor q print help message
    else:
        print(__doc__)
        sys.exit(1)
 
    # run selective search segmentation on input image
    rects = ss.process()
    print('Total Number of Region Proposals: {}'.format(len(rects)))

**Comment by vackup** [comment]
@deepakkumar1984 have you use these new functions?

**Comment by deepakkumar1984** [comment]
No I haven't tried it yet. Will let you know if I am able to do it

**Comment by vackup** [comment]
I'm stucked... cause there is no createSelectiveSearchSegmentation method in OpenCVSharp..  there is something similar.. 

var ss = OpenCvSharp.XImgProc.CvXImgProc.Segmentation.CreateSelectiveSearchSegmentationStrategyFill();

Also there is no ss.setBaseImage(im) or ss.process()

Any clue @shimat ?
