### ISSUE TITLE
Cv2.CalibrateCamera distCoeffs always zero / Other behavior then C++ version

### ISSUE THREAD

**Issue by WeitesFeld** [shimat/opencvsharp#402]
# Summary

In contrast to the C++ version of calibrateCamera, the C# version CV2.Calibrate camera does not modify the Input/Output parameter distCoeffs. The array only contains zeroes. This is a different behaviour then the C++ equivalent.

OpenCV Description: https://docs.opencv.org/3.2.0/d9/d0c/group__calib3d.html#ga3207604e4b1a1758aa66acb6ed5aa65d
Issue regarding this problem: 
https://github.com/shimat/opencvsharp/issues/253
Nuget version 3.2.0.20170419

For testing purposes, I compiled the current OpenCVSharp Master, including a fixed version of #253 (adding some missing "<>") and it worked.
The calibrateCamera method is crucial for camera undistortion, so a fix would be appreciated.

**Comment by NilesDavis** [comment]
I just experienced the same which is really disappointing. I also could not fix the #253 because of missing opencv_world300d.lib 
Could you provide a fixed version of OpenCvSharpExtern?

**Comment by WeitesFeld** [comment]
[OpenCvSharpExtern.zip](https://github.com/shimat/opencvsharp/files/1481873/OpenCvSharpExtern.zip)
OpenCVSharpExtern.dll Win32 Release Build. Try it out. Hope it fixes your problem

**Comment by NilesDavis** [comment]
works like charm, thank you! I don't get why @shimat does not use the fix. I am not that mmuch into c++ but his arguments in #253 don't look like more than 10 minutes of work, or am I wrong?

**Comment by WeitesFeld** [comment]
I don't know why but I worked with OpenCV C++ before and used that method and can say for sure, that the current C# implementation does not work as intendent.

**Comment by ravazquez** [comment]
Hi, I am trying to do a non-planar camera calibration and am also getting 0 in all distCoeffs values.  I already tried the fix proposed in #253 and the dll provided in this thread as well but am still getting all zeroes.

I am passing in the following flags: 

CALIB_USE_INTRINSIC_GUESS
CALIB_FIX_K1 through 6
CALIB_ZERO_TANGENT_DIST

My cameraMatrix is being calculated properly.

I have an analogous example from a friend on Emgu and it is handing back proper distCoeffs values.

Does anybody have any information that might help me? 

Thanks!

**Comment by NilesDavis** [comment]
Sorry @ravazquez I have no experience using non planar camera calibrations. Anyway this camera calibration topic still seems to be a thing to work on. I would be glad to get some more attention of @shimat because this looks like an issue in the C++ part

**Comment by shimat** [comment]
If you specify wrong array size of distCoeffs, the distCoeffs result seems to contain only zero.

For example, in the test code below, if distCoeff is `double[8]`, the result is zero. If distCoeff is `double[5]`, the result is set. I am not sure of the cause of this behavior. https://github.com/shimat/opencvsharp/blob/ae6af025dc167e7004ac0f61aaf594e5f15910bb/test/OpenCvSharp.Tests/calib3d/Calib3dTest.cs#L47

I recommend the Mat argument overload of calibrateCamera.

**Comment by 159199** [comment]
Got the same problem with RationalModel flag. Im passing double[8] as an argument but getting zero array result. It works fine for other flags. Any ideas?

**Comment by CobbsLab** [comment]
if you pass the flags CALIB_FIX_K1 through 6 no distortion distCoeffs will be computed

for example the flag CALIB_FIX_K1 means that the K1 parameter will not computed
