### ISSUE TITLE
Can't add controls to Toolbox

### ISSUE THREAD

**Issue by egedib** [shimat/opencvsharp#417]
# Can't Place controls into the toolbox

# Environment

The project is WPF project and I'm using .NET Framework 4.6.1 (but I tried with 4.6 too).
# What did you do when you faced the problem?

Right click under General tab -> Choose Items -> .NET Framework Components tab -> Browse, then selected the OpenCvSharp.UserInterface.dll file.

## Output:

The following controls were successfully added to the toolbox but are not enabled in the active designer:

- PictureBoxIpl
- TrackbarWithLabel

Make sure the controls to add are compatible with the current designer and .NET Framework version.

![opencvsharpcontrols](https://user-images.githubusercontent.com/7786398/32793919-9a1115fc-c967-11e7-882f-1eaa16588389.PNG)

**Comment by d4az** [comment]
hi I also recently had the same problem with visual studio 2019 and i tried to fix it but nothing worked. so what i did was i reinstalled visual studio 2017 and now it works perfectly 

thanks,
Dasith
