### ISSUE TITLE
OpenCvSharp3のフットプリントについて

### ISSUE THREAD

**Issue by YSRKEN** [shimat/opencvsharp#420]
# Summary of your issue
OpenCvSharpExtern.dllのファイルサイズが巨大なので、それが依存する箇所をチェックしてできれば使用しないようにしたいです。

# Environment
・Windows 10 64bit
・Visual Studio 2017
・.NET Framework 4.6.2
・Nugetにて「OpenCvSharp3-AnyCPU」を導入。そのバージョンが3.3.1.20171117

# What did you do when you faced the problem?
　私はC#でアプリ開発をしております。
　開発の際、OpenCVの機能を利用するため、Visual StudioのNugetからOpenCvSharpを上記の通りインストールしました。
　そしてデバッグ後に配布物を作成する段階になって、OpenCvSharpExtern.dllのファイルサイズが巨大(x86版・x64版共に30MB以上)だと気付きました。
　プログラム上で使用しているOpenCVの機能は
・Mat型とBitmapとの相互変換
・モノクロ化とビット反転と二値化
・テンプレートマッチング
ぐらいで(どれもOpenCV Ver.1時代のもの)、ラベリング機能は使用していません。なので(Blob機能に関係するらしい)OpenCvSharpExtern.dllは必要ないだろうと思いましたが、削除すると今度は(開発した)アプリが起動しなくなりました。
　同様の機能を以前「OpenCvSharp-AnyCPU(Nugetでの名称。2.x系のラッパー)」で実装した際はそこまで巨大にならなかったので、原因が分からず困っています。よろしくお願いします。

**Comment by shimat** [comment]
OpenCvSharpExtern.dllはC++とC#の橋渡しをする純粋なネイティブ実装ですが、これが巨大なのは、少し前にダイナミックリンクからスタティックリンクに変えて、OpenCVのあれこれを全部積んでいる状態になっているためです。
> 利用の際の簡便化を優先しています。いまお持ちのような状況があり得ることは予想し悩みましたが、これまでDLL読み込みに失敗したという類の問い合わせが非常に多数で、それの解決を優先したところです。

また、私の古いブログを参照なさっていたのかもしれず恐れ入りますが、OpenCV2系以降は全ての処理に関しておよそOpenCvSharpExtern.dll は必須です。OpenCVのAPIがCからC++になり、直接ラップすることが難しくなったためです。

提示頂いている処理に必要なのは以下のDLLです。Externをどう削るか（＝ダイナミックリンクに変える）という課題になると思います。
- OpenCvSharp.dll
- OpenCvSharp.Extensions.dll (Bitmapとの変換のため)
- OpenCvSharpExtern.dll

配布のNuGetで -AnyCPU と -WithoutDll があり、後者はExternが抜いてありマネージDLLのみを含みます。これはLinux等の環境向けにExternを自前でビルドしていただくことを意図しています。そのために一応はCMakeの設定ファイルがあります。もし挑戦されるならサポートします。(参考: https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Ubuntu-14.04)

または、使われている機能はかなり基礎的な処理なので、昔のOpenCvSharpを使うだとか、またはAccord.net 等のほかの選択肢もあると思います。
お手数をおかけします :pray:

**Comment by YSRKEN** [comment]
返答ありがとうございます。自前でExternをビルドし直すことが必要なのですね。

**Comment by shimat** [comment]
対応不要と判断しますので閉じます
