### ISSUE TITLE
GStreamer backend support for VideoCapture

### ISSUE THREAD

**Issue by jstumpin** [shimat/opencvsharp#427]
# Summary of your issue
There is no API to replace FFMPEG as the default CaptureDevice for VideoCapture's backend like what we have in [OpenCV](https://docs.opencv.org/3.3.1/d0/da7/videoio_overview.html). 

# Environment
Windows 10 (x86). MSVC 2017.

## Example code:
This code segment works on OpenCV v3.3.1:
```
cv::VideoCapture reader;
string pipe = "rtspsrc location=" + Uri + " latency = 0 ! decodebin ! videoconvert ! appsink sync = false";
reader.open(pipe, cv::CAP_GSTREAMER);
```

This do nothing:
```
string pipe = "rtspsrc location=" + Uri + " latency = 0 ! decodebin ! videoconvert ! appsink sync = false";
var reader = new VideoCapture(pipe);
reader.open(pipe, cv::CAP_GSTREAMER); <-- (".open" doesn't exist)
```

## What did you intend to be?
Do we need to build OpenCvSharp from source with OpenCV + GStreamer to enable this feature? If so, how, since I've only successfully built OpenCV + GStreamer via CMake?

**Comment by turowicz** [comment]
@jstumpin I add `-D WITH_GSTREAMER=ON -D WITH_FFMPEG=OFF` to the build arguments and GStream works with "rtspt://location:port". It does not work with the gstream pipe definitions that you mention though.

@shimat is this API planned?

**Comment by linh20111789** [comment]
re

> # Summary of your issue
> There is no API to replace FFMPEG as the default CaptureDevice for VideoCapture's backend like what we have in [OpenCV](https://docs.opencv.org/3.3.1/d0/da7/videoio_overview.html).
> 
> # Environment
> Windows 10 (x86). MSVC 2017.
> 
> ## Example code:
> This code segment works on OpenCV v3.3.1:
> 
> ```
> cv::VideoCapture reader;
> string pipe = "rtspsrc location=" + Uri + " latency = 0 ! decodebin ! videoconvert ! appsink sync = false";
> reader.open(pipe, cv::CAP_GSTREAMER);
> ```
> 
> This do nothing:
> 
> ```
> string pipe = "rtspsrc location=" + Uri + " latency = 0 ! decodebin ! videoconvert ! appsink sync = false";
> var reader = new VideoCapture(pipe);
> reader.open(pipe, cv::CAP_GSTREAMER); <-- (".open" doesn't exist)
> ```
> 
> ## What did you intend to be?
> Do we need to build OpenCvSharp from source with OpenCV + GStreamer to enable this feature? If so, how, since I've only successfully built OpenCV + GStreamer via CMake?

By default, GStreamer is enabled. But if you want to rebuild OpenCVSharp with optional, download OpenCVSharp project and rebuild it, change option with CMake_Vars_x64.txt file in this project

**Comment by turowicz** [comment]
@shimat is it possible to define a gstreamer pipeline in the `VideoCapture` constructor? I haven't been able to so far.

**Comment by turowicz** [comment]
Seems that this is a general opencv issue. The extern code just calls the `cv::VideoCapture` constructor.

I think this is out of @shimat's hands

**Comment by turowicz** [comment]
The following works:

```
private bool TryCreateCapture(string networkAddress, out VideoCapture capture)
{
    capture = new VideoCapture();
    try
    {
        capture.Open($"rtspsrc location=\"{networkAddress}\" latency=10 ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! appsink");
    }
    catch (Exception)
    {
        capture.Dispose();
    }
    return capture.IsOpened();
}
```

Where `networkAddress` is `rstpt://{someip}/{someparams}`

**Notice the `t` in `rstpt://`**

**Comment by valeriob** [comment]
Hi,
i've rebuilt opencv in the repository of opencv_files with the gstreamer support (it automatically detects it once you put in the path the gstreamer installation folder.
Then i updated the content of this folder opencvsharp\opencv_files\opencv450_win_x64\ with the output of the opencv_files build, but when i try to rebuild opencvsharp, but i get this error : 
![image](https://user-images.githubusercontent.com/1522516/101287833-11ca8e00-37f3-11eb-836f-5e1807c06d86.png)
I have added gstreamer headers to the project OpenCvSharpExtern but without success : 
![image](https://user-images.githubusercontent.com/1522516/101287861-2c046c00-37f3-11eb-8285-b40c0728be47.png)


Do you have an idea what am i missing?

**Comment by mridah** [comment]
@shimat any update?
