### ISSUE TITLE
Tracker.Init (Tracking.Tracker) crashes with TrackerTypes.KCF

### ISSUE THREAD

**Issue by WeitesFeld** [shimat/opencvsharp#435]
KCF tracker alwas crashes when trying to init. with tracker.Init(Mat, Rect2d). Using the same code with MIL tracker, it works. 

I'm using ver. 3.2.0.20170913 from 13. september. Afaik in OpenCV 3.3 instead 3.2 they only changed the way of creating those trackers.

Using 

```
var tracker = Tracker.Create(OpenCvSharp.Tracking.TrackerTypes.KCF);
var bbox= new Rect2d(10, 10, 100, 100);
var frame = ... // Init valid mat here
bool initSuccess = tracker.Init(frame, bbox); // ## ALWAYS CRASHES HERE
```

**Comment by rblenis** [comment]
Can you test the 3.3.1.20171117 version?  There have been several fixes related to garbage collection and Tracker disposing that may resolve this issue for you.

**Comment by WeitesFeld** [comment]
I did, compiled and tested the current master (which is newer, hope that was ok). Same problem still exists. 

```
var tracker = TrackerKCF.Create();
var bbox= new Rect2d(10, 10, 100, 100);
var frame = ... // Init valid mat here
bool initSuccess = tracker.Init(frame, bbox); // ## ALWAYS CRASHES HERE
```

KCF crashes, MIL works.

**Comment by rblenis** [comment]
hmm, I just ran this code with latest and it didn't crash. Even put it in a loop and ran it many times.  I wonder if it could be image or host environment specific. Can you provide sample image used and project settings, etc. (32/64 bit, windows/linux, ...)?

**Comment by WeitesFeld** [comment]
Sure.
OS: Windows 7, x64 with VS 2015 Update 3
Project is x86 Debug and Release, NET 4.6.2
Compiled binaries are x86 Release (with VS 2017, same OS)

Tested input mats are either BGR or Grayscale, Size is 463*753 but may differ
Rect2d is {(x:64,6813250828544 y:41,6813250828544 width:32,6373498342912 height:32,6373498342912)} where X and Y coordinates may differ from test to test. 

Sadly I cannot provide a sample image but you can share one that I can test as first frame.

**Comment by rblenis** [comment]
yep, as soon as I change to non-integer bounding box, I get it to crash as well. Without digging further, it appears to be a problem with the underlying opencv TrackerKCF and not an opencvSharp issue.

**Comment by WeitesFeld** [comment]
I found the next problem related to KCF tracker and I don't know if it is related to the C# wrapper or the underlying opencv c++ code.

If your Mat is grayscale it will init but crash on Tracker.Update

**Comment by rblenis** [comment]
Just stepped through the code and both are definitely issues with opencv, not opencvsharp.

**Comment by WeitesFeld** [comment]
I wrote a reported and they adressed this issue.
https://github.com/opencv/opencv_contrib/issues/1472

Then this issue can be closed. Thanks
