### ISSUE TITLE
 fast  access to pixels

### ISSUE THREAD

**Issue by Talla2k** [shimat/opencvsharp#441]
If I use slow access to pixels, then everything is fine. As soon as I use fast, an crash occurs (APPCRASH).
Do I need to specify something in the project properties?

**Comment by shimat** [comment]
You say methods in this page occurs crash? (https://github.com/shimat/opencvsharp/wiki/%5BCpp%5D-Accessing-Pixel)

**Comment by Talla2k** [comment]
Yes. Only the first example works. The rest also work and are perfectly compiled, but after a short time the failure.

**Comment by augasur** [comment]
I also have the same problem. If I try to set/get Mat pixel values from byte array using GenericIndexer or TypeSpecificMat program crashes. Tested both in Debug and Release modes. Alsmost always it works on the first image, but crashes on second.

**Comment by joshmer** [comment]
I'm not sure if this has been addressed yet, but I may have found a fix for this crash. You need to explicitly call 'Dispose()' on the MatOf* object at the end of your method.

It seems like automatic garbage collection corrupts the original Mat when it tries to cleanup the MatOf* object.

**Comment by shimat** [comment]
Perhaps this problem is fixed by https://github.com/shimat/opencvsharp/pull/472.  I am sorry but the latest NuGet package is old, so it does not contain the fix.

**Comment by joshmer** [comment]
I tried to build from Master and it looks like the crash no longer happens. Thanks!

**Comment by grisharav** [comment]
Any plans to release a new nuget?
