### ISSUE TITLE
Initialized Mat with array

### ISSUE THREAD

**Issue by thinever** [shimat/opencvsharp#442]
# Summary of your issue
i want to create a Mat with my own data:
 float[] data = new float[12] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
 Mat src = new Mat(4, 3, MatType.CV_32FC1, data);
but error occurs:
System.TypeInitializationException
even with the 2D array    float[ , ] data,   still the same error;
Hope help;
Thanks
# Environment
opencvsharp 3.2,vs2013

**Comment by thinever** [comment]
when i use opencvsharp2.4.9, it is ok to initialize a Mat witt array:
   CvMat src = new CvMat(512, 424, MatrixType.F32C1, imagedata);//imagedata is  float[] imagedata

**Comment by shimat** [comment]
Can you check StackTrace and Message of the TypeInitializationException? 
Perhaps VC++2017 redistributable package is not installed on your computer.
