### ISSUE TITLE
Using VideoCapture in OpenCVSharp and transfering to picturebox in C#

### ISSUE THREAD

**Issue by kwiksys** [shimat/opencvsharp#444]
I am new to OpenCVsharp.
I am trying to transfer the Mat image  frame using VideoCaptured from camera or video  to a picturebox
in c# windows form application. 

Appreciate if you can assist me by showing an example.

----------------------------------------------------------------------
   var capture = new VideoCapture("c:\\Video.mp4");

            // var capture = new VideoCapture(@"D:\Chiam\VideoAnalytic\PeopleWalkOverhead.mp4");

            int sleepTime = (int)Math.Round(1000 / capture.Fps);

            using (var window = new Window("capture"))
            {
                // Frame image buffer
                Mat image = new Mat();

                // When the movie playback reaches end, Mat.data becomes NULL.
                while (true)
                {
                    capture.Read(image); // 
                    if(image.Empty())
                        break;
                // Tried this way but nothing is shown
                 picturebox1.image = OpenCvSharp.Extensions.BitmapConverter.ToBitmap(image); 

                //    window.ShowImage(image);   <==  this has no issue 

                    Cv2.WaitKey(sleepTime);
                } 
            }
        }
--------------------------------------------------------------------------------------------------------------------

Thank You
Peter

**Comment by shimat** [comment]
:thinking:  Please try this
```c#
while (true)
{
    if (picturebox1.Image != null)
        picturebox1.Image.Dispose();
    picturebox1.Image = OpenCvSharp.Extensions.BitmapConverter.ToBitmap(image); 
    picturebox1.Refresh();

    Thread.Sleep(50); 
    Application.DoEvents();
}
```

I think it is recommended to use Timer.
```
timer1.Tick = delegate{
    picturebox1.Image =  ...
}
```

**Comment by shimat** [comment]
Please refer the code snippets in my page http://schima.hatenablog.com/entry/20090925/1253852774
