### ISSUE TITLE
Actually this is a Question, OpenCvSharp_dnnFaceRecognizer

### ISSUE THREAD

**Issue by blaisexen** [shimat/opencvsharp#447]
hi @shimat 

Do you think you can make a class of dnn face algorithm  and add it on opencvSharp face recognizer?

I got help links from here, 
https://github.com/died/OpenCvDnnVggFace

it's yes or no?
and I hope it's more accurate than lbph face recognizer

**Comment by died** [comment]
Hi @blaisexen , I just using dnn module load caffe model then do what it can do.
I think you can use dnn to load anything that can support and test it, no need make another algorithm for that.
