### ISSUE TITLE
InRange not show error

### ISSUE THREAD

**Issue by bezblue** [shimat/opencvsharp#449]
var m = arg.Mat;
var lower_blue = new OpenCvSharp.Scalar(20, 100, 100);
ar upper_blue = new OpenCvSharp.Scalar(30, 255, 255);
Cv2.InRange(m, lower_blue, upper_blue, mask);
Cv2.ImShow("a", mask);
/// App in Mobile stop working but not show error.
help me pls.

**Comment by bezblue** [comment]
cv::Exception'
  what():  /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:9748: error: (-215) scn == 3 || scn == 4 in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
02-05 03:03:46.713 F/libc    ( 4019): Fatal signal 6 (SIGABRT), code -6 in tid 4041 (Threadpool work)

**Comment by shimat** [comment]
what is depth and number of channels of `m` and `mask` ?

**Comment by bezblue** [comment]
i don't understand.
pls example to me pls.
thanks bro.

**Comment by shimat** [comment]
According to the error message, your Mat may have wrong channels or depth for some opencv functions.
```
error: (-215) scn == 3 || scn == 4 
```

Check your Mat information. 
Try converting mat type to CV_8UC3.
```c#
Console.WriteLine(m.Channels);
Console.WriteLine(mask.Type());
```
