### ISSUE TITLE
Aruco Module EstimatePoseSingleMarker

### ISSUE THREAD

**Issue by alek5k** [shimat/opencvsharp#451]
Hello,

I noticed that the aruco module hasn't had the function "EstimatePoseSingleMarkers" implemented - https://docs.opencv.org/3.1.0/d9/d6a/group__aruco.html#gafdd609e5c251dc7b8197323657a874c3.

I started doing my own implementation like so:

NativeMethods.cs:

```C#
static partial class NativeMethods
{
[DllImport(DllExtern, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
public static extern void aruco_estimatePoseSingleMarkers([MarshalAs(UnmanagedType.LPArray)] IntPtr[] corners, float markerLength, IntPtr cameraMatrix, IntPtr distCoeffs, IntPtr rvecs, IntPtr tvecs);
}
```

CvAruco.cs:

```C#
public static void EstimatePoseSingleMarkers(Point2f[][] corners, float markerLength, InputArray cameraMatrix, InputArray distortionCoefficients, OutputArray rvec, OutputArray tvec)
{
    if (corners == null)
        throw new ArgumentNullException(nameof(corners));

    if (cameraMatrix == null)
        throw new ArgumentNullException(nameof(cameraMatrix));

    if (distortionCoefficients == null)
        throw new ArgumentNullException(nameof(distortionCoefficients));

    using (var cornersAddress = new ArrayAddress2<Point2f>(corners))
    {
        NativeMethods.aruco_estimatePoseSingleMarkers(cornersAddress.Pointer, markerLength, cameraMatrix.CvPtr, distortionCoefficients.CvPtr, rvec.CvPtr, tvec.CvPtr);
    }

    GC.KeepAlive(corners);
    GC.KeepAlive(cameraMatrix);
    GC.KeepAlive(distortionCoefficients);
}
```

However, when I run this new code, I get an exception called "Unknown/unsupported array type". More interestingly, the status shows `StsNotImplemented` which is of type `OpenCvSharp.ErrorCode`. My question is, what else do I need to do to be able to hook into this OpenCV method? I am happy to PR this code if you can assist me with figuring out what this error means.

Ive included the exception info here while debugging:
![image](https://user-images.githubusercontent.com/20435565/36307527-c08e49c2-1370-11e8-9794-9c215d3b0952.png)

Thanks,
Aleks

**Comment by alek5k** [comment]
Potentially related:

https://github.com/opencv/opencv_contrib/issues/574

**Comment by shimat** [comment]
Thanks. I will add EstimatePoseSingleMarker in the next release. https://github.com/shimat/opencvsharp/commit/af0d8e12db75a02b49168a3e92ce2afdd5f0ff6d
The error has solved.

**Comment by alek5k** [comment]
Great, thanks!
