### ISSUE TITLE
Vector compare bug?

### ISSUE THREAD

**Issue by DanielDavis5** [shimat/opencvsharp#452]
There appears to be an error in the Equals method of [Vec3b.](https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/core/Struct/Vec/Vec3b.cs)

Line 88 does not appear to be valid C#:
`return obj is Vec3b b && Equals(b);`

Based on the pattern used in the other vector classes I believe this was intended:
`return obj is Vec3b && Equals((Vec3b)obj);`

How did this compile? Is it special syntax to .Net Core?

**Comment by shimat** [comment]
It is a new C# syntax. Please use Visual Studio 2017.

**Comment by DanielDavis5** [comment]
Got it.
