### ISSUE TITLE
UWP compatible version

### ISSUE THREAD

**Issue by Firifire** [shimat/opencvsharp#453]
@shimat  I have made a version that works with UWP application [here](https://github.com/Firifire/OpenCvHololens).

I used [opencv-hololens](https://github.com/sylvain-prevost/opencv-hololens) by Sylvain Prevost and I made UWP class library using OpenCvSharp 3.1 source as base, and I took some wrapper codes from 3.3.1 version to make to compatible and fix some issues. and made some small changes to the OpenCvSharpExtern codes so that the dll import would work for UWP.

I will try to redo what Sylvain Prevost did with the more recent version of openCV and try to incorporate latest OpenCvSharp wrapper.

Maybe these changes could be added to OpenCvSharp to make it UWP compatible for the future

**Comment by Wroud** [comment]
Hi, can you post instructions to run opencvsharp on UWP application, im trying to recompile **OpenCvSharpExtern** with ARM target platform, but get errors. If i try run opencvsharp application in UWP app, i get exception "System.BadImageFormatException: An attempt was made to load a program with an incorrect format." i think it is OpenCvSharpExtern dll import exception, also have troubles with building OpenCV with ARM target platform, whats im doing wrong?

**Comment by Firifire** [comment]
Well I updated the wrapper to the latest release.
