### ISSUE TITLE
Unable to load DLL 'opencv_core240': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by watoo** [shimat/opencvsharp#456]
I created a new console application and installed opencvsharp using nuget:
![image](https://user-images.githubusercontent.com/5346797/37030327-65d2d9b8-215c-11e8-9a60-27067bec233a.png)

When I run application, I get error:

> Unable to load DLL 'opencv_core240': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I searched error online and I found that I need to put the native .DLL files of OpenCV in my application. So I downloaded http://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.2/OpenCV-2.4.2.exe/download 

and it have lot of directories: 
-build
 |_bin
 |    |_opencv_ffmpeg341.dll
 |    |_opencv_ffmpeg341_64.dll
 |_include
    |_opencv
    |_opencv2
-sources
-LICENSE.txt

I'm confused which file I need, so I placed all files in myConsoleApplication/bin/debug folder and it gives same above error message.

**Comment by watoo** [comment]
I created a new console application and downloaded this package:
![image](https://user-images.githubusercontent.com/5346797/37032310-dacc1caa-2163-11e8-8d0e-b1dfabcc6da3.png)

and it says 

> The type or namespace name IplImage could not be found.

Please guide me, which is the correct package that I need to install from nuget and which extra files or dlls do I need.

**Comment by afiqmuzaffar** [comment]
@watoo , I'm facing this challenges. Any idea to resolve?
