### ISSUE TITLE
Check similarity between two faces

### ISSUE THREAD

**Issue by watoo** [shimat/opencvsharp#460]
I have two images, image1 is newly uploaded and other is face.png already saved. I want to compare faces detected from image1 with face.png

```
static void Main(string[] args)
        {
           //new image
            var srcImage = new Mat(@"..\..\Images\image1.jpg");
            Cv2.ImShow("Source", srcImage);
            Cv2.WaitKey(1); // do events

            var grayImage = new Mat();
            Cv2.CvtColor(srcImage, grayImage, ColorConversionCodes.BGRA2GRAY);
            Cv2.EqualizeHist(grayImage, grayImage);

            //load patterns for face detection
            var cascade = new CascadeClassifier(@"..\..\Data\haarcascade_frontalface_alt.xml");

            var faces = cascade.DetectMultiScale(
                image: grayImage,
                scaleFactor: 1.1,
                minNeighbors: 2,
                flags: HaarDetectionType.DoRoughSearch | HaarDetectionType.ScaleImage,
                minSize: new Size(30, 30)
                );

            Console.WriteLine("Detected faces: {0}", faces.Length);
            
            var rnd = new Random();
            var count = 1;
            foreach (Rect faceRect in faces)
            {
                Mat detectedFaceImage = new Mat(srcImage, faceRect);
                Cv2.ImShow(string.Format("Face {0}", count), detectedFaceImage); //save this face
                Cv2.WaitKey(1); // do events

                //read already saved image
                Mat imageFromDb = new Mat(@"face.png");
                Cv2.ImShow("image", imageFromDb);
                Cv2.WaitKey();

               **  //compare imageFromDb with detectedFaceImage ?? **
                
            }
        }
```

**Comment by watoo** [comment]
I tried following function to compare faces:

```
public static int FindDifference(Mat in1, Mat in2)
        {
            Mat diff = in1;
            Cv2.Compare(in1, in2, diff, CmpTypes.NE);
            return Cv2.CountNonZero(diff);
        }
```

and using this function as:
`var diff = FindDifference(detectedFaceImage, imageSavedImage);`

But getting exception: 

> An unhandled exception of type 'OpenCvSharp.OpenCVException' occurred in OpenCvSharp.dll

Additional information: cn == 1

![untitled1111](https://user-images.githubusercontent.com/5346797/37203507-af782884-23af-11e8-8017-e01a49f5d5fa.png)

**Comment by joreg** [comment]
the error message says "cn == 1" which you need to read as: "the input mat must have only 1 channel"

**Comment by watoo** [comment]
okay, I converted both `detectedFaceImage` and `savedFaceImage` to single channel, now `FindDifference` function reuturned 1924 for same faces. Why so pixel difference for same images? Is there a way I can get difference in percentage like two images for 75% similar. I'm searching from 4 days but couldn't find any documentation regarding faces comparison.

**Comment by shimat** [comment]
https://docs.opencv.org/3.3.0/da/d60/tutorial_face_main.html

**Comment by rafaP** [comment]
public double getSimilarity(Mat A, Mat B)
    {

        if (A.Rows > 0 && A.Rows == B.Rows && A.Cols > 0 && A.Cols == B.Cols)
        {
            // Calculate the L2 relative error between the 2 images.
            double errorL2 = Cv2.Norm(A, B, NormTypes.L2);
            // Convert to a reasonable scale, since L2 error is summed across all pixels of the image.
            double similarity = errorL2 / (double)(A.Rows * A.Cols);
            return similarity;
        }
        else
        {
            //cout << "WARNING: Images have a different size in 'getSimilarity()'." << endl;
            return 100000000.0;  // Return a bad value
        }

    }
