### ISSUE TITLE
VS2017 Xamarin for android

### ISSUE THREAD

**Issue by xiaobl** [shimat/opencvsharp#462]
How to use this to vs2017 xamarin android?

**Comment by DiomedesDominguez** [comment]
Just add the reference and start developing, it use the same class as desktop or xamarin.ios

**Comment by whSwitching** [comment]
not sure if you really tried. 
but I did, code edit is fine but when runtime (Android emulator x86) I got a lot of 
`D/Mono    ( 6251): DllImport error loading library libOpenCvSharpExtern` 
and
` 'dlopen failed: library "/data/app/com.example.app/lib/x86/`
`/storage/emulated/0/Android/data/ccom.example.app/files/.__override__/libOpenCvSharpExtern" not found'.`

**Comment by TheBricktop** [comment]
Same issue, i tried https://github.com/Kawaian/OpenCvSharp but there is opencvsharp.android part that says its incompatible with current VS version
