### ISSUE TITLE
Cv2.Mean() returning strange values ?

### ISSUE THREAD

**Issue by A00107408** [shimat/opencvsharp#465]
# Summary of your issue

Translating project from OpenCv in Java to OpenCvSharp in C#.
 Cv2.Mean() returning strange values.

# Environment
Unity on Windows 10.

## Example code:
**Original Java Code:**
Mat mat = MyImage;
measuredColorArray[n][m] = Core.mean(mat).val;

**C# Code:**
Mat mat = MyImage;
measuredColorArray[n][m][0] = Cv2.Mean(mat).Val0;
measuredColorArray[n][m][1] = Cv2.Mean(mat).Val1;
measuredColorArray[n][m][2] = Cv2.Mean(mat).Val2;
measuredColorArray[n][m][3] = Cv2.Mean(mat).Val3;

**Or I can do:**
Scalar avg = new Scalar();
Mat mat = MyImage;

avg = Cv2.Mean(mat);
measuredColorArray[n][m][0] = avg.Val0;
measuredColorArray[n][m][1] = avg.Val1;
measuredColorArray[n][m][2] = avg.Val2;
measuredColorArray[n][m][3] = avg.Val3;

I need the results in this array for further processing.

## Output:
White => White     (ok)
Green => Green     (ok)
Blue => Brown       (strange)
Orange => Blue     (strange)
yellow => Indigo   (strange)
Red => Dark Blue  (strange)

## What did you intend to be?
Mean() of single color image should be roughly the same as the original image yes?

**Comment by A00107408** [comment]
Hmmm...

Even when I do:

Vec3b color = mat.At<Vec3b>(100,100);

on a yellow monochrome image, it still returns RGB values for indigo???

What is happening here?

**Comment by shimat** [comment]
OpenCV uses **BGR** color format. The behavior is by design.

**Comment by A00107408** [comment]
AH.. thank you. it works now.

But can I ask about alpha channel. Is it **ABGR** or **BGRA** ?

**Comment by ravazquez** [comment]
It would be BGRA.

**Comment by A00107408** [comment]
Thanks for your help.
