### ISSUE TITLE
Question: about enhancement Facemark and others

### ISSUE THREAD

**Issue by blaisexen** [shimat/opencvsharp#467]
Just a question:
EmguCv has added enhancement FacemarkLBF and FacemarkAAM
and Added training function to Facemark?

Does the same to OpenCvSharp?

**Comment by FFMB2018** [comment]
Is this feature already ready to use?

I´ve made a build on the latest sources today, but I get an AccessViolationException in the Facemark.Fit() method.

Maybe I´m using it the wrong way, too. I´ve tried to convert the original C++ samples to C#.

Here´s my code:
```
CascadeClassifier classifier = new CascadeClassifier(@"haarcascade_frontalface_alt2.xml");

Mat input = MatHelper.ToMat(source);

Mat gray = new Mat();
Cv2.CvtColor(input, gray, ColorConversionCodes.BGR2GRAY);

Rect[] facesRects = classifier.DetectMultiScale(input);
InputArray facesArray = InputArray.Create<Rect>(facesRects);

Facemark facemark = FacemarkLBF.Create();
facemark.LoadModel(@"d:\lbfmodel.yaml");

Mat landmarks = new Mat();
facemark.Fit(input, facesArray, landmarks);     // <-- AccessViolationException
```

The pre-trained I´m using for my tests model is this one:
https://raw.githubusercontent.com/kurnianggoro/GSOC2017/master/data/lbfmodel.yaml
from
https://github.com/opencv/opencv_contrib/blob/master/modules/face/tutorials/facemark_usage/facemark_usage.markdown


Thanks for support!

**Comment by blaisexen** [comment]
so nice for the usage,
thank you

**Comment by FFMB2018** [comment]
@erraineon 
Unfortunately not. I have tried some approaches, but I always get the same error message. Also different builds didn't improve.

**Comment by DiomedesDominguez** [comment]
@FFMB2018 , can you please try again with the latest commit?

**Comment by FFMB2018** [comment]
@DiomedesDominguez 
Sorry for my late reply.

I tried it today with the current release from Nov 08, 2018. Unfortunately I still get an AccessViolationException.

@noname-2 
I have ported the source code of some C++ examples. Unfortunately, I am not sure if I do this correctly. I'll do another web search, maybe I'll find better or other examples.

**Comment by alastaira** [comment]
I've only just strated dabbling with OpenCV/OpenCVSharp, but isn't your problem here?:

> Cv2.CvtColor(input, gray, ColorConversionCodes.BGR2GRAY); 
Rect[] facesRects = classifier.DetectMultiScale(input);

You convert the input mat to greyscale but then, instead of providing the greyscale version to the classifier, you give it the original image. In other words, shouldn't this be?:

>Cv2.CvtColor(input, gray, ColorConversionCodes.BGR2GRAY);
Rect[] facesRects = classifier.DetectMultiScale(gray);

**Comment by blaisexen** [comment]
Mat frame;
Mat grayImage = new Mat();
CascadeClassifier cascade;
                
Cv2.CvtColor(frame, grayImage, ColorConversionCodes.BGRA2GRAY);
                var faces = cascade.DetectMultiScale(
                                image: grayImage,
                                scaleFactor: 1.1,
                                minNeighbors: 10,
                                flags: HaarDetectionType.DoRoughSearch | HaarDetectionType.ScaleImage,
                                                                minSize: new OpenCvSharp.Size(34, 34)
                                );

hi,
I used like that

**Comment by alastaira** [comment]
Hmm, ok, so even having corrected the bug in the previous code, it seems I can't get facemark.Fit() to run without generating a runtime error either. Has anyone had any success with this?

It seems to me that the return type of landmarks parameter (InputOutputArray) is surprising considering the OpenCV source uses OutputArrayOfArrays (https://docs.opencv.org/3.4/db/dd8/classcv_1_1face_1_1Facemark.html) -  I would have expected this parameters type to be, say, VectorOfVectorPoint2d instead?

**Comment by FFMB2018** [comment]
> 
> 
> I've only just strated dabbling with OpenCV/OpenCVSharp, but isn't your problem here?:
> 
> > Cv2.CvtColor(input, gray, ColorConversionCodes.BGR2GRAY);
> > Rect[] facesRects = classifier.DetectMultiScale(input);
> 
> You convert the input mat to greyscale but then, instead of providing the greyscale version to the classifier, you give it the original image. In other words, shouldn't this be?:
> 
> > Cv2.CvtColor(input, gray, ColorConversionCodes.BGR2GRAY);
> > Rect[] facesRects = classifier.DetectMultiScale(gray);

You're right, this seems to be a bug in my code. I played around with it for quite some time and probably uploaded the wrong version.

Thanks for the correction! :-)

However, I didn't get the code to work either, even if I used the grayscale image. It still throws the AccessViolationException.

**Comment by tedghost** [comment]
Got same issue. 

public virtual bool Fit(   InputArray image,  InputArray faces,  InputOutputArray landmarks){
    .......................
NativeMethods.face_Facemark_fit(ptr, image.CvPtr, faces.CvPtr, landmarks.CvPtr);
    .......................
}
How can in warp Rect[] got from classifier.DetectMultiScale() to InputArray. and warp VectorOfVectorPoint2f landmarks to InputOutputArray.

**Comment by man2201** [comment]
Got same issue.

Problem with warping VectorOfVectorPoint2f to InputOutputArray.

Will there be any updates?

**Comment by blaisexen** [comment]
it would be nice that you paste the whole code here, I'll be glad to solved the issue.
or if not?, 
if I will got it right by my own ideas then I will post it here only the binaries.

**Comment by man2201** [comment]
`CascadeClassifier faceDetector = new CascadeClassifier("D:/cascade.xml");
            Mat image = imageInput.Clone();
            Mat grayImage = new Mat();
            Cv2.CvtColor(image, grayImage, ColorConversionCodes.BGR2GRAY);
            Cv2.EqualizeHist(grayImage, grayImage);
            
            var faces = faceDetector.DetectMultiScale(grayImage);

            var fParams = new FacemarkLBF.Params();
            fParams.CascadeFace = "D:/lbfmodel.yaml";

            var facemark = FacemarkLBF.Create(fParams);

            Mat landmarks = new Mat();

            InputArray facesArray = InputArray.Create<Rect>(faces);
bool success = facemark.Fit(grayImage, facesArray, landmarks);`
code crashed on method Fit()

**Comment by blaisexen** [comment]
@man2201, 
I tried, but I failed,
I think this implementation with OpenCvSharp is a bug, 
even @shimat don't have a simple sample code to make it right.

I look at the implementation with emguCv, I think it works a charm, 
https://stackoverflow.com/questions/50090124/how-to-use-facemarker-in-emgucv,

but I more like OpenCvSharp that's why I stick on this framework, 
but I'm still thinking....until now...I switch or I stay.

**Comment by jcast07** [comment]
I'm new to OpenCvSharp and ran into the same issue, will there be an update anytime soon? 
It seems that DlibDotNet also does facial landmarking will give it a try since I can't move to emguCV.

**Comment by blaisexen** [comment]
Still OpenCvSharp is faster or the fastest of them all.

**Comment by erraineon** [comment]
why close the issue? the bug is still there

**Comment by blaisexen** [comment]
Actually it's not a bug, it's the structure of the code that doesn't fall from OpenCv functions, types, and parameters.

I'm sorry, you can open in your own.

**Comment by FFMB2018** [comment]
Created a new bug report at https://github.com/shimat/opencvsharp/issues/653.
