### ISSUE TITLE
Question: Does OpenCvSharp 3.4.1 support CUDA

### ISSUE THREAD

**Issue by blaisexen** [shimat/opencvsharp#468]
if not, how to use CUDA for my face detection? any link could help?

**Comment by blaisexen** [comment]
hi,
thanks for the comments,
yes I know where to check the Cuda support in cmake openCv source, 
but I don't understand
> then replace it with opencvsharp's opencv dlls

I just know this files:
OpenCvSharp.dll
OpenCvSharpExtern.dll

So what do you mean?

**Comment by died** [comment]
@blaisexen you can check this issue #123 .

**Comment by blaisexen** [comment]
thanks a lot :+1:
