### ISSUE TITLE
Does OpencvSharp support YOLO like native opencv?

### ISSUE THREAD

**Issue by i-interested** [shimat/opencvsharp#473]
Opencv 3.4.1 support YOLO

https://docs.opencv.org/3.4.1/da/d9d/tutorial_dnn_yolo.html. 

Does OpencvSharp support for YOLO if I install OpencvSharp from nuget?

**Comment by died** [comment]
https://github.com/died/OpenCvSharpDnnYolo
Yes, OpenCVSharp supported YOLO since 3.3(or early), I didn't test YOLOv3 at 3.4.1 yet but I guess it support too.
