### ISSUE TITLE
Bindings for FreeType module

### ISSUE THREAD

**Issue by Sergey-Terekhin** [shimat/opencvsharp#477]
Hi!
Do you have wrapper for FreeType2 class to work with custom fonts?
Link to OpenCv docs: https://docs.opencv.org/3.4.1/d9/dfa/classcv_1_1freetype_1_1FreeType2.html

**Comment by shimat** [comment]
There is not freetype wrapper yet.
The freetype functions can be substituted by GDI + (System.Drawing). I think this enhancement is low priority.

**Comment by Sergey-Terekhin** [comment]
We would like to drop GDI+ from our project... It looks like that we need to use SkiaSharp for our purposes
