### ISSUE TITLE
How to save a FREAK descriptor?

### ISSUE THREAD

**Issue by hismichael** [shimat/opencvsharp#486]
As I've read that FREAK uses 512-bit descriptor, while how can I save it into database?

A FREAK descriptor is represented as a Mat object, when I convert it into byte array through the Mat.ToBytes() method, the result byte[] is about 40KB in size.

Can I only save a 512-bit long byte string or a similarly short representation?

Thank you very much!

**Comment by shimat** [comment]
# Save
```cs
using (var fs = new FileStorage("foo.yml", FileStorage.Mode.Write))
{
    fs.Write("mat", mat);
}
```

# Load
```cs
using (var fs = new FileStorage("foo.yml", FileStorage.Mode.Read))
{
    using (var node = fs["mat"])
    using (var mat = node.ReadMat())
    {
        // ...
    }
}
```

**Comment by hismichael** [comment]
Thanks!
