### ISSUE TITLE
where is subspaceProject()?

### ISSUE THREAD

**Issue by juicycool92** [shimat/opencvsharp#489]
# Summary of your issue

Hello, im new of Cv, therefore i might be way wrong approach.
here's the thting what i done and want to do.

i try to follow face recognization tutorial from official document.
its for OpenCv, not OpenCvSharp. but i figured out CvSharp has preety much every method or mecro in OpenCv. therefore i keep typing and converting for CvSharp.

it was fine until i met subspaceProject() and subspaceReconstruct()
i try to find every source file and google search, but no luck to me.
Anyone please tell me where to find subspaceProject() and subspaceReconstruct()?

Thanks.

# Environment

Vs2017 C# Wpf

# What did you do when you faced the problem?

trying to calling'em

## Example code:

```
Mat projection = subspaceProject()
```

## Output:

```
not declared subspaceProject method
```

## What did you intend to be?

trying to follow fisherface tutorial via [here](https://docs.opencv.org/2.4/modules/contrib/doc/facerec/facerec_tutorial.html#fisherfaces)

**Comment by shimat** [comment]
I added `LDA.SubspaceProject` in #495. thanks.
