### ISSUE TITLE
Does OpenCvSharp use multiple CPU cores by default?

### ISSUE THREAD

**Issue by hismichael** [shimat/opencvsharp#490]
When I run the BFmatcher.Match() operation, I notice that It seems taking more than one CPU. But I have difficulty to view details thru debugger. We're developing a Cv server therefore threading is a critical concern for us.

Can you give me some insights?

Thank you very very much!

**Comment by hismichael** [comment]
I made a call to Cv2.SetNumThreads(1) before the matching operation, and did observe that OpenCvSharp uses only one thread now. So I think this is a viable approach to control threading.

Am I on the right track?

**Comment by shimat** [comment]
Probably yes :ok_hand:

**Comment by hismichael** [comment]
Thanks for your kind help as well as your fantastic contribution.
