### ISSUE TITLE
ReadNetFromCaffe error

### ISSUE THREAD

**Issue by derekmoc** [shimat/opencvsharp#498]
Getting an error trying read in some DNN models.  Specifically this one:

https://docs.opencv.org/3.4/d5/de7/tutorial_dnn_googlenet.html

but had no luck with these either

https://github.com/BVLC/caffe/tree/master/models

This one works fine
https://github.com/weiliu89/caffe/tree/ssd#models (07++12+COCO - SSD512)

Visual Studio 2017 C#

```c#
string root = "local directory path";

CvDnn.ReadNetFromCaffe(
    Path.Combine(root, "deploy.prototxt"), 
    Path.Combine(root, "bvlc_googlenet.caffemodel"));
```
This is the exception I get
OpenCvSharp.OpenCVException: 'FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: .............

Very new to all this so have probably missed something obvious.

**Comment by shimat** [comment]
You might be using wrong prototxt. 
Please see https://github.com/shimat/opencvsharp/blob/master/test/OpenCvSharp.Tests/dnn/CaffeTest.cs#L22

**Comment by derekmoc** [comment]
Still get the same error, I downloaded the bvlc_googlenet.prototxt and bvlc_googlenet.caffemodel off your github site.  The model file gets downloaded in the code (await PrepareModel(caffeModel);)

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: _data\text\bvlc_googlenet.prototxt)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\derekmoc\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs:line 22

Inner Exception 1:
OpenCVException: FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: _data\text\bvlc_googlenet.prototxt

**Comment by derekmoc** [comment]
Just tried Emgu and get the same error so might be something with OpenCV instead.  Both OpenCVSharp and Emug work with https://github.com/weiliu89/caffe/tree/ssd#models (07++12+COCO - SSD512)
