### ISSUE TITLE
How to set DPI of image?

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [shimat/opencvsharp#502]
Using this library, how can I set the dpix and dpiy of image?

**Comment by shimat** [comment]
Probably OpenCV can not change DPI of image. https://stackoverflow.com/questions/10860969/change-dpi-of-an-image-in-opencv

**Comment by ThunderBoltEngineer** [comment]
@shimat  You were right.  I need to use Bitmap module for getting image with new DPI.
