### ISSUE TITLE
Using With_Cuda option. but opencvsharpextern build fail label:question

### ISSUE THREAD

**Issue by NaJongHeon** [shimat/opencvsharp#504]
# Summary of your issue
I build succeeded openCV 3.4.1 with_cuda
Also, I excluded from option "TBB"
However, build errors such as attachments still occur.
![image](https://user-images.githubusercontent.com/24406907/42125933-bc058434-7cba-11e8-80b9-8b622431b73e.png)

# Environment
Win 10 64bit
Write your environment.

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

## What did you intend to be?
It would be nice if Nuget could get a version that can use with _ cuda.
or I want to know the cmake option of openCV.
ex)openCVSharpExtern for
openCV ver
openCV contrib ver
leptonica ver
tesseract ver
etc...
Thanks~!

**Comment by Wiggi86** [comment]
I had the same problem. For me it worked with openCv world. Try to check world option in cmake for openCV and change all libs (in linker properties of openCvExtern) to opencv_world341.lib

**Comment by NaJongHeon** [comment]
@Wiggi86  Thank for your kindness reply. I'll try it as you said.
