### ISSUE TITLE
Seek a particular frame at timestamp n

### ISSUE THREAD

**Issue by karanmartian** [shimat/opencvsharp#505]
Hi,

Is there a way to read a frame of a video file at a particular timestamp say at 40 secs using this library?

**Comment by shimat** [comment]
You can use `PosFrames` or `PosMsec` properties of VideoCapture.
```c#
var capture = new VideoCapture("foo.avi");
int secs = 40;
capture.PosFrames = (int)(capture.Fps * secs);

var frame = new Mat();
capture.Read(frame);
```

**Comment by karanmartian** [comment]
Thanks that works!
