### ISSUE TITLE
need openCV to detect frontal face and the side of the face .

### ISSUE THREAD

**Issue by atiato78** [shimat/opencvsharp#514]
Hello ,

I'm using OpenCVSharp with streaming from Camera :

frontal face is detected with the following code in OpenCVSharp :

var haarCascade = new CascadeClassifier("haarcascade_frontalface_alt2.xml");
// Detect faces
OpenCvSharp.Rect[] faces = haarCascade.DetectMultiScale(
                                   alt, 1.08,2, HaarDetectionType.ScaleImage, new OpenCvSharp.Size(30, 30));

for the Cascade Classifier Do you have XML that can consider face side as a face as well with certain angle ?

I'm able to detect frontal face only with this XML , I need to detect frontal face and if I got a face from his side I need also to consider it .

I need both detection for frontal face and face side to be included both in the XML.

thanks,
Omar Atia

**Comment by shimat** [comment]
haarcascade_profileface.xml may be of help to you.
https://github.com/opencv/opencv/tree/master/data/haarcascades
https://github.com/opencv/opencv/tree/master/data/lbpcascades
