### ISSUE TITLE
Include .dylib and .so for OpenCvSharpExtern in release files

### ISSUE THREAD

**Issue by turowicz** [shimat/opencvsharp#515]
It is required to manually compile the extern library in order to get it to work on Mac or Linux, while Windows dll is provided out of the box.

It is a big challenge to compile this library on Mac or Linux, as I get into the rabbit hole of fixing dependencies and figuring out why my installation of opencv doesn't have the include files required to build this project.

It would be SO much easier if the libraries were precompiled and ready to be used. You could also include them in your nuget package.

**Comment by turowicz** [comment]
This library does such a thing: https://github.com/michaelfaisst/DinkToPdf

**Comment by turowicz** [comment]
[libOpenCvSharpExtern.dylib.zip](https://github.com/shimat/opencvsharp/files/2249556/libOpenCvSharpExtern.dylib.zip)

**Comment by turowicz** [comment]
[libOpenCvSharpExtern.so.zip](https://github.com/shimat/opencvsharp/files/2249689/libOpenCvSharpExtern.so.zip)

**Comment by shimat** [comment]
Thank you for your suggestion and library files 👍 
To continuously release OpenCvSharp's Linux/Mac binaries in future years, a CI system is required. I would like to try CircleCI or other CIs.

**Comment by Venzz** [comment]
> [libOpenCvSharpExtern.so.zip](https://github.com/shimat/opencvsharp/files/2249689/libOpenCvSharpExtern.so.zip)

Does it work on Raspbian?

**Comment by Trapov** [comment]
If I understand this correctly then the opencv libraries should be copied as wel as the bindings for dotnet. 

> https://github.com/shimat/opencvsharp/blob/master/nuget/OpenCvSharp3-AnyCPU.nuspec
> https://github.com/shimat/opencvsharp/blob/master/nuget/OpenCvSharp3-AnyCPU.props

@shimat, Wouldnt it be bad to include those libraries in the nuget-package, for each platform seperatly and then switch to one and another with some flag/switch or something?

**Comment by stebigs** [comment]
@Venzz  I don't know about Raspbian but I tried on Ubuntu 18.04 and it didn't work. Do you know if anyone used them successfully?

Thanks!

**Comment by Trapov** [comment]
@stebigs couldn't get it to work on Ubuntu as well.

**Comment by turowicz** [comment]
I use OpenCVSharp on Ubuntu 18.04 and 16.04 without any issues. Make sure you've got `.so` files copied into your app folder.

**Comment by turowicz** [comment]
Also check stdout as it has dependencies on `ffmpeg` and others.

**Comment by turowicz** [comment]
From my dockerfile

RUN apt-get update -y
RUN apt-get install -y \
    vim \
    git \
    zip \
    wget \
    curl \
    cmake \
    libsm6 \
    python3 \
    gfortran \
    libxext6 \
    pkg-config \
    libblas-dev \
    python3-dev \
    python3-pip \
    libjpeg-dev \
    python3-numpy \
    libgtk2.0-dev \
    liblapack-dev \
    libswscale-dev \
    libxrender-dev \
    graphicsmagick \
    libavcodec-dev \
    libavformat-dev \
    build-essential \
    libatlas-base-dev \
    libgraphicsmagick1-dev \
    software-properties-common \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

**Comment by shimat** [comment]
> @shimat, Wouldnt it be bad to include those libraries in the nuget-package, for each platform seperatly and then switch to one and another with some flag/switch or something?

Good. I want to do so.
There is a problem with NuGet package size. Currently some people already say that OpenCvSharp NuGet is too large by including both x86 and x64 OpenCvSharpExtern DLLs.
As adding .so and .dylib make the size of NuGet even bigger, I am looking for a good solution. For example, try installing [SkiaSharp](https://www.nuget.org/packages/SkiaSharp) to see this problem.

**Comment by IvanKulikov** [comment]
Ok, i've build the .so file. Putting it alongside the .NET CORE .dll executable is no use - same error. 
**No such file or directory**
`/usr/local/lib` 
and 
`/usr/lib`
too.
Can someone specify where do i put it or what am I doing wrong?

**Comment by turowicz** [comment]
@IvanKulikov which operating system are you on? If its linux then which one?

**Comment by IvanKulikov** [comment]
> @IvanKulikov which operating system are you on? If its linux then which one?

It's Ubuntu 18.04 LTS

**Comment by turowicz** [comment]
@IvanKulikov this is what my docker file does with that library

```
# Install OpenCVSharp
WORKDIR /
RUN git clone --single-branch -b 3.4 https://github.com/shimat/opencvsharp.git
WORKDIR /opencvsharp/make
RUN cmake ../src && make -j 4 && make install
RUN cp /opencvsharp/make/OpenCvSharpExtern/libOpenCvSharpExtern.so /usr/lib
```

**Comment by turowicz** [comment]
@IvanKulikov many times .NET will tell you it can't load the `.so` but in reality it's missing it's dependencies. Use http://www.bnikolic.co.uk/blog/linux-ld-debug.html and set it to `libs` to trace which dependency (usually parts of OpenCV) isn't there.

I literally have to copy OpenCV from `/usr/local/lib/` to `/usr/lib` in order to make it work.

**Comment by SuperSimon81** [comment]
Ok I have the .dylib. Where do I put it?

**Comment by turowicz** [comment]
@SuperSimon81 `/usr/lib` or `/usr/local/lib`.
