### ISSUE TITLE
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by powerWriter** [shimat/opencvsharp#516]
running version：OpenCvSharp-3.4.1-x86-20180712。
windows xp 32bit。
please tell me how to fix , Why is it happen?

**Comment by powerWriter** [comment]
get it，thanks

**Comment by cdyfly** [comment]
@powerWriter  OpenCvSharp-3.4.1-x86 in Windows xp 32bit using?

**Comment by powerWriter** [comment]
yeah

**Comment by powerWriter** [comment]
> @powerWriter OpenCvSharp-3.4.1-x86 in Windows xp 32bit using success?

yep

**Comment by cdyfly** [comment]
@powerWriter  Can I send out use dll library for windows XP，or Provide a download address

**Comment by a312586670** [comment]
> 991683156@qq.com

Can I send out use dll library for windows XP，or Provide a download address
my email：312586670@qq.com

**Comment by cdyfly** [comment]
&nbsp;Can you send out use dll library for windows XP，or Provide a download address
my email：991683156@qq.com




------------------原始邮件------------------
发件人： &nbsp;“ powerWriter” <notifications@github.com&gt;;
发送时间： &nbsp;2019年11月25日（星期一）下午2:47
收件人： &nbsp;“ shimat / opencvsharp” <opencvsharp@noreply.github.com&gt;;
抄送： &nbsp;“小熊维尼” <991683156@qq.com&gt;;“评论” <comment@noreply.github.com&gt;;
主题： &nbsp;回复：[shimat / opencvsharp]“ OpenCvSharp.NativeMethods”的类型初始值设定项引发了异常。（＃516）



 
@powerWriter Windows XP 32bit中的OpenCvSharp-3.4.1-x86使用成功吗？
  
是的
  
— 
您收到此评论是因为您发表了评论。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by JonasHdez** [comment]
Could you please send me the library for Windows XP to my email:

**Comment by powerWriter** [comment]
> Could you please send me the library for Windows XP to my email:

sorry，I can not find it ,it was on my last company's computer, I don't have a backup.

**Comment by mailspeed** [comment]
I also encountered this problem. I finnaly find out that it's the reason lies in operation system itself.
In my case, the OS is Windows10 N edition, which is lack of "**Windows_MediaFeaturePack**".
After download and install "**Windows_MediaFeaturePack_x64_1803.msu**", it works.
