### ISSUE TITLE
CvMat default constructor produces (natively) non-initialized object

### ISSUE THREAD

**Issue by Svolo4** [shimat/opencvsharp#52]
CvMat and all other DisposableCVObject-derived objects when created with default constructor (or the one with single bool parameter) use DisposableObject.AllocMemory to allocate memory for native structure. That method in turn uses Marshal.AllocHGlobal method which produces non-initialized memory. As a consequence code like "new CvMat().Dispose()" crashes.
My suggestion would be to zero-initialize allocated memory inside DisposableObject.AllocMemory.
But that alone won't be sufficient as OpenCV expects some magic value to be put in the first field of every structure (like cvCreateMat or cv::Mat::Mat() does by putting CV_MAT_MAGIC_VAL (0x42FF0000) to the type/flags field) and that is what CvMat's (and other objects') constructor should be doing.

**Comment by kdbanman** [comment]
Has this bug been resolved?
