### ISSUE TITLE
How to turn off libpng warning?

### ISSUE THREAD

**Issue by kkc0923** [shimat/opencvsharp#520]
# Summary of your issue
When using OpenCVSharp, it prints "libpng warning: [some message]".

I'm using opencvsharp for deep learning project, and it reads massive images and its "libpng warning" message hides my important application log.

# Environment
Windows 10, .NET Framework 4.7.1 x64

**Comment by shimat** [comment]
Could you tell me the detailed warning message?  
For example, if it is `libpng warning: Image width is zero in IHDR`, the image may be uninitialized or broken.

**Comment by kkc0923** [comment]
The messages is here:
libpng warning: iCCP: known incorrect sRGB profile

Also, loaded image is correctly processed.

**Comment by shimat** [comment]
It seems to be a bug of libpng. There is a solution using ImageMagick.
https://tex.stackexchange.com/questions/125612/warning-pdflatex-libpng-warning-iccp-known-incorrect-srgb-profile
https://gist.github.com/bluenex/0af2f41fda9954df73a8

Perhaps using Magick.NET or System.Drawing.Bitmap or other libraries is also helpful. 

```c#
var mat = new Mat("a.png"); // libpng warning?

var bitmap = new Bitmap("a.png");
var mat2 = OpenCvSharp.Extensions.BitmapConverter.ToMat(bitmap); 
```

**Comment by kkc0923** [comment]
Oh, I see.

But my dataset is a big (millions of images) and managed by using md5 hash, so clearning-up can not be a solution.

I'll change my logging mechanism. Thanks for investigation.

**Comment by shimat** [comment]
Probably on-memory converting from your original png to stripped png is useful for your situation. My code above is its example.
