### ISSUE TITLE
Why exception occur with OpenCvSharp MatchTemplete ?

### ISSUE THREAD

**Issue by Lay4U** [shimat/opencvsharp#527]
public void searchIMG(Bitmap screen_img, Bitmap find_img)
    {
        //스크린 이미지 선언
        using (Mat ScreenMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(screen_img))
        //찾을 이미지 선언
        using (Mat FindMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(find_img))
        //스크린 이미지에서 FindMat 이미지를 찾아라
        using (Mat res = ScreenMat.MatchTemplate(FindMat, TemplateMatchModes.CCoeffNormed))
        {
            //찾은 이미지의 유사도를 담을 더블형 최대 최소 값을 선언합니다.
            double minval, maxval = 0;
            //찾은 이미지의 위치를 담을 포인트형을 선업합니다.
            OpenCvSharp.Point minloc, maxloc;
            //찾은 이미지의 유사도 및 위치 값을 받습니다. 
            Cv2.MinMaxLoc(res, out minval, out maxval, out minloc, out maxloc);
            Debug.WriteLine("찾은 이미지의 유사도 : " + maxval);
            //이미지를 찾았을 경우 클릭이벤트를 발생!!
            if(maxval >= 0.8)
            {
                InClick(maxloc.X, maxloc.Y);
            }
        }
    }

i tried very many times but i don't know why occur exception and solution

please help me

when i execute this program then Exception occur like this [exception](https://i.stack.imgur.com/KSKSK.jpg)

when i do debugging and check the different like this [debug](https://i.stack.imgur.com/xuOJp.jpg)

i don't know why exception occur and how can fix it

and if you want to see full souce then click below

[Full Source] (https://colorscripter.com/s/UYNfKXf)

**Comment by shimat** [comment]
According to your [exception](https://i.stack.imgur.com/KSKSK.jpg), `type == _templ.type()` is required.
But on your [execution](https://i.stack.imgur.com/xuOJp.jpg), the input image is 8UC"4" and the template image is 8UC"3". Please try converting your input image from 8UC4 to 8UC3.  It is also ok to convert screen_img's PixelFormat from 32bppArgb to 24bppRgb.

**Comment by Lay4U** [comment]
Thanks answer captain
i try 
Bitmap screen = new Bitmap(screen_img.Width, screen_img.Height, System.Drawing.Imaging.PixelFormat.Format32bppPArgb);
            Bitmap find = new Bitmap(find_img.Width, find_img.Height, System.Drawing.Imaging.PixelFormat.Format32bppPArgb);

            Mat ScreenMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(screen);
            Mat FindMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(find);

now it's not exception but the result is horrible.
output of MinMaxLoc's minval, maxval is 1 and minloc, maxloc positions is {0,0}
where is Wrong i don't know T.T

**Comment by shimat** [comment]
Pixel data of original images are not copied to new bitmaps. 
Probably the matchTemplate method does not support alpha channel, so you should convert images from 32bpp to 24bpp (bitmap), or from 8UC4 to 8UC3(Mat).

**Comment by Lay4U** [comment]
i did 

           Bitmap screen = new Bitmap(screen_img.Width, screen_img.Height, System.Drawing.Imaging.PixelFormat.Format24bppRgb);


            Bitmap find = new Bitmap(find_img.Width, find_img.Height, System.Drawing.Imaging.PixelFormat.Format24bppRgb);

but doesn't working 

and convert  8UC4 to 8UC3 is also not working 

i tried almost and debugging and  i did every thing as i can do 

like this

        public void searchIMG(Bitmap screen_img, Bitmap find_img)
        {

            //Bitmap clone = new Bitmap(find_img.Width, find_img.Height,System.Drawing.Imaging.PixelFormat.Format32bppArgb);
            //Bitmap clone = find_img.Clone(new Rectangle(0, 0, find_img.Width, find_img.Height), PixelFormat.Format32bppArgb);
            //PixelFormat = Format24bppRgb
            //Bitmap clone = new Bitmap(screen_img.Width, screen_img.Height, System.Drawing.Imaging.PixelFormat.Format24bppRgb);
            //using (Graphics gr = Graphics.FromImage(clone))
            //{
            //    gr.DrawImage(screen_img, new Rectangle(0, 0, clone.Width, clone.Height));
            //}
            //pictureBox1.Image = clone;



            //    //스크린 이미지 선언
            //    //using (Mat ScreenMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(screen_img))
            //    Mat ScreenMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(screen_img);
            //    Mat ScreenMatDst = new Mat(ScreenMat.Size(), MatType.CV_8UC4);
            //    OpenCvSharp.Extensions.BitmapConverter.ToMat(screen_img, ScreenMatDst);
            //    //Cv2.CvtColor(ScreenMat, ScreenMatDst, ColorConversionCodes.BGRA2BGR);

            //    //찾을 이미지 선언
            //    Mat FindMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(find_img);
            //    Mat FindMatDst = new Mat(FindMat.Size(), MatType.CV_8UC4);
            //    OpenCvSharp.Extensions.BitmapConverter.ToMat(find_img, FindMatDst);


            //    //스크린 이미지에서 FindMat 이미지를 찾아라
            //    using (Mat res = ScreenMatDst.MatchTemplate(FindMatDst, TemplateMatchModes.CCoeffNormed))
            //    {
            //        //찾은 이미지의 유사도를 담을 더블형 최대 최소 값을 선언합니다.
            //        double minval, maxval = 0;
            //        //찾은 이미지의 위치를 담을 포인트형을 선업합니다.
            //        OpenCvSharp.Point minloc, maxloc;
            //        //찾은 이미지의 유사도 및 위치 값을 받습니다. 
            //        Cv2.MinMaxLoc(res, out minval, out maxval, out minloc, out maxloc);
            //        Debug.WriteLine("찾은 이미지의 유사도 : " + maxval);


            //        //이미지를 찾았을 경우 클릭이벤트를 발생!!
            //        int offsetY = 35;
            //        if (maxval >= 0.8)
            //        {
            //            InClick(maxloc.X + FindMatDst.Width / 2, maxloc.Y + FindMatDst.Height / 2 - offsetY);
            //        }
            //    }
            pictureBoxIpl1.Image = screen_img;
            //스크린 이미지 선언
            //Mat ScreenMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(screen_img);
            //찾을 이미지 선언
            //Mat ScreenMat(screen_img)
            //Mat FindMat = Cv2.ImRead(@"img\rpg.png",ImreadModes.Color);
            // Mat FindMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(src);
            //스크린 이미지에서 FindMat 이미지를 찾아라

            Bitmap screen = new Bitmap(screen_img.Width, screen_img.Height, System.Drawing.Imaging.PixelFormat.Format24bppRgb);
            Bitmap find = new Bitmap(find_img.Width, find_img.Height, System.Drawing.Imaging.PixelFormat.Format24bppRgb);

            //스크린 이미지 선언
            //using (Mat ScreenMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(screen_img))
            Mat ScreenMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(screen);

            Mat FindMat = OpenCvSharp.Extensions.BitmapConverter.ToMat(find);
            //FindMat.AssignTo(FindMat, MatType.CV_8UC4);
            FindMat.ConvertTo(FindMat, MatType.CV_8UC4);
            using ( Mat res = ScreenMat.MatchTemplate(FindMat, TemplateMatchModes.CCoeffNormed))

            {

                //찾은 이미지의 유사도를 담을 더블형 최대 최소 값을 선언합니다.
                double minval, maxval = 0;
                //찾은 이미지의 위치를 담을 포인트형을 선업합니다.
                OpenCvSharp.Point minloc, maxloc;
                //찾은 이미지의 유사도 및 위치 값을 받습니다. 
                Cv2.MinMaxLoc(res, out minval, out maxval, out minloc, out maxloc);
                Debug.WriteLine("찾은 이미지의 유사도 : " + maxval);

                //이미지를 찾았을 경우 클릭이벤트를 발생!!
                if (maxval >= 0.8)
                {
                    InClick(maxloc.X, maxloc.Y);
                }
            }
        }

but i didn't solved it

**Comment by shimat** [comment]
```c#
using (Mat screenMat8UC4 = OpenCvSharp.Extensions.BitmapConverter.ToMat(screen_img))
using (Mat screenMat8UC3 = new Mat())
{
    Cv2.CvtColor(screenMat8UC4, screenMat8UC3, ColorConversionCodes.BGRA2BGR);

    ...
}
```

**Comment by shimat** [comment]
why don’t you use 8UC3 Mat for MatchTemplate?
Or the template image’s size and the original image’s target region size may be different.

**Comment by Lay4U** [comment]
if i use 8UC3 is res's value is same

i  treid many times but maxval is fixed as 0.338....

can't i solve it?

**Comment by shimat** [comment]
The template image that you uploaded here is smaller than the original image's area that you want to match.
The image below is my test result. The blue rectangle is the best match area. It is smaller than the original gun image. So, I think your result of `maxval = 0.338` is reasonable. Basic template matching methods are not scale-invariant.

```c#
using (var src = new Mat(@"44958495-18834000-af1c-11e8-859c-edee484765fe.jpg"))
using (var template = new Mat(@"44958500-3486e180-af1c-11e8-99b2-c0420d50decc.jpg"))
using (var result = new Mat())
{
    Cv2.MatchTemplate(src, template, result, TemplateMatchModes.CCoeffNormed);
    Cv2.MinMaxLoc(result, out var minVal, out var maxVal, out var minLoc, out var maxLoc);

    src.Rectangle(maxLoc, new Point(maxLoc.X + template.Width, maxLoc.Y + template.Height), Scalar.Blue, 5);
    Window.ShowImages(src, template);
}
```
![sample](https://user-images.githubusercontent.com/4434824/45042906-d0dcef80-b0a6-11e8-9987-5b49ba524652.png)

**Comment by Lay4U** [comment]
Thank you very much for your sincerity reply.

**Comment by blaisexen** [comment]
I'm Glad I read it, useful soon.
thanks
