### ISSUE TITLE
 Faster RCNN. Problem with dnn net.forward(List<Mat> outputBlobs, List<string> outBlobNames)

### ISSUE THREAD

**Issue by xkaple01** [shimat/opencvsharp#528]
# Summary of your issue
I'm using Faster RCNN architecture for detection and classification task.
`net.forward(List<Mat> outputBlobs, List<string> outBlobNames)`  method doesn't work.
Below is my code: 

## Example code:

```
Mat clsProb = _net.Forward("cls_prob");        //works well, clsProb is 300x5 Mat


//but
List<Mat> outBlobs = new List<Mat> {};  // (1)
//or
List<Mat> outBlobs = new List<Mat> {new Mat(), new Mat()};  // (2)



List<string> outBlobNames = new List<string> {"cls_prob", "bbox_pred"};
_net.Forward(outBlobs, outBlobNames);

// In (1) case the outBlobs list is empty (contains 0 items)
// In (2) case the outBlobs list contains 2 Mat items, each Mat has height = 0 and width = 0 


```

# Environment

Windows 7, Visual Studio 17, OpenCvSharp 3.4.1, py-faster-rcnn

**Comment by officeautomata** [comment]
This still doesn't work with the latest update. The addition of GC.KeepAlive(outputBlobs); in reference to NativeMethods.dnn_Net_forward3 didn't seem to work. Perhaps an overload that returns an array of new Mat's like dnn_Net_forward1 would work.

**Comment by shimat** [comment]
I found a bug of the `vector<Mat>` wrapper. https://github.com/shimat/opencvsharp/pull/577/commits/99b1744a438d2ba316a45ee141b12a208347c4d8
This issue may be fixed in the next release.

**Comment by maazullah96** [comment]
<img width="519" alt="Issue" src="https://user-images.githubusercontent.com/30190807/76216088-372b5c80-61cd-11ea-8db3-7e1b7ce88a71.PNG">
I am getting this exception while using multithreading for detection
