### ISSUE TITLE
Loss of YCbCr

### ISSUE THREAD

**Issue by Sago92** [shimat/opencvsharp#529]
Hello together,

I have a file in the YCbCr (CMYK) color format and want to save them in the same color format.

I use the following and simple source code.

```
Mat imageForProcessing = Cv2.ImRead(@"C:\Test\Original.tif");
Cv2.ImWrite(@"C:\Test\result.tif", imageForProcessing);
```

After saving the file, the color format is RGB

I already tried different ImreadModes but it will alway be converted into RGB.

I attached the Tiff file. I would appreciate any help!

[original.zip](https://github.com/shimat/opencvsharp/files/2347774/original.zip)

**Comment by shimat** [comment]
I don't know how to save YCbCr image as is. Probably OpenCV does not have the feature.
One way is to store pixel data in separate files for each channel. Another way is: https://stackoverflow.com/questions/22367263/take-and-save-an-image-in-ycbcr-format-using-opencv
