### ISSUE TITLE
SetMouseCallback not working

### ISSUE THREAD

**Issue by claudeHasler** [shimat/opencvsharp#537]
# Summary of your issue
Im trying to select a ROI by mouse input. I wish to get the pixel coordinates by means of a mouseCallback, however the mouseCallback never seems to be called. Other callbacks such as trackbar seems to work just fine.

# Environment
Visual Studio 2017  WPF

## Example code:

        public void getMouseClickCoordinates(MouseEvent e, int x, int y, MouseEvent f)
        {
            System.Windows.MessageBox.Show("im a callback");
        }

        public void trackbarCallback(int pos, object userdata)
        {
            System.Windows.MessageBox.Show("im a trackbarcallback");
        }

        public MainWindow()
        {
            InitializeComponent();
        }

       int bla = 5;

        private void Button_Click(object sender, RoutedEventArgs e)
        {

            Mat mat;
            mat = Cv2.ImRead("C:\\Users\\Master\\Desktop\\img.png");
            Cv2.NamedWindow("myWindow");

            
            
            Cv2.CreateTrackbar("myTrackbar", "myWindow", ref bla, 0, new 
            CvTrackbarCallback2(trackbarCallback));

            Cv2.SetMouseCallback("myWindow", new CvMouseCallback(getMouseClickCoordinates));

            Cv2.ImShow("myWindow", mat);
            Cv2.WaitKey(2000);

            

        }

**Comment by shimat** [comment]
Thanks 👍

**Comment by FaridGad** [comment]
Hello,
Sorry to reopen this issue. But it seems that this fix doesn't work with the latest version of OpenCVSharp.
This is the error that I got:

Error	CS0123	No overload for 'getMouseClickCoordinates' matches delegate 'CvMouseCallback'	

I tried to initialize the delegate with no luck. I was wondering what was the correct syntax to get the mouse click coordinates.
Thanks.
