### ISSUE TITLE
Getting all connected camera devices

### ISSUE THREAD

**Issue by thohemp** [shimat/opencvsharp#538]
Is there any way to get a list of all connected camera devices without using AForge?
Since OpenCV is crossplattform these kind of functions are not supported, but maybe someone here has an idea.

I can't use AForge due licence issues.

**Comment by thohemp** [comment]
> 
> 
> I have been using DirectShowLib, however it doesn't really show which cameras are connected rather which camera drivers are installed. In my case it doesn't really matter if the user picks the wrong camera so I didn't try to see if there is a way to check if the camera is connected. Going to check if there is a way to do it though.

There is way by using the Microsoft Expression Encoder (https://www.microsoft.com/en-us/download/details.aspx?id=27870)

`var vidDevices = EncoderDevices.FindDevices(EncoderDeviceType.Video);`

It's not what I am looking for, but it may help with your issue.

**Comment by thohemp** [comment]
I created a simple device enumerator. Next step: Get friendly device names.

https://github.com/thohemp/OpenCVSharpCameraDeviceEnumerator

**Comment by ravazquez** [comment]
The following code gives you a list of connected devices and their supported configurations using MediaFoundation:

https://github.com/vvvv/VL.OpenCV/blob/master/src/VideoInInfo.cs

Hope that helps

**Comment by XamtasticPenn** [comment]
So I got around to updating from v.3 => v.4.........now I just lost **ALL my Cameras** 😢

**Comment by blaisexen** [comment]
https://sourceforge.net/projects/csharp-web-cam-list/
