### ISSUE TITLE
System.TypeInitializationException when trying to initialize Mat

### ISSUE THREAD

**Issue by clifu** [shimat/opencvsharp#539]
# Summary of your issue
Mostly whenever I am trying to initialize new object of Mat type I get an exception. I do not get details from it but the message says: 'System.TypeInitializationException: The type initializer for 'OpenCvSharp.Mat' threw an exception. '. If it can be helpfull I am writting an app for Android and trying to make new Mat whenever I get new frame from my phone's camera.

# Environment
I am using VS 2017 community, I have updated everything I could. I do have the newest version of Microsoft c++ redistributable 2017.

## Example code:

```
OpenCvSharp.Mat frame = new OpenCvSharp.Mat(640,480,OpenCvSharp.MatType.CV_8SC3);
```
It's not working even for that code:
```
OpenCvSharp.Mat frame = new OpenCvSharp.Mat();
```

## Output:

```
System.DllNotFoundException: OpenCvSharpExtern
  at (wrapper managed-to-native) OpenCvSharp.NativeMethods.core_Mat_sizeof()
  at OpenCvSharp.NativeMethods.TryPInvoke () [0x0000e] in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:118

10-02 23:00:13.192 I/mono-stdout(19312): OpenCvSharpExtern
10-02 23:00:13.194 I/mono-stdout(19312): *** An exception has occurred because of P/Invoke. ***
10-02 23:00:13.194 I/mono-stdout(19312): Please check the following:
10-02 23:00:13.194 I/mono-stdout(19312): (1) OpenCV's DLL files exist in the same directory as the executable file.
10-02 23:00:13.194 I/mono-stdout(19312): (2) Visual C++ Redistributable Package has been installed.
10-02 23:00:13.195 I/mono-stdout(19312): (3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.
10-02 23:00:13.195 I/mono-stdout(19312): 
10-02 23:00:13.195 I/mono-stdout(19312): System.DllNotFoundException: OpenCvSharpExtern
10-02 23:00:13.195 I/mono-stdout(19312):   at (wrapper managed-to-native) OpenCvSharp.NativeMethods.core_Mat_sizeof()
10-02 23:00:13.195 I/mono-stdout(19312):   at OpenCvSharp.NativeMethods.TryPInvoke () [0x0000e] in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:118 

```

**Comment by tednyberg** [comment]
I've run into this same problem when trying to run this in a Xamarin app.

The package is supposed to work for .NET Core (.NET Standard 2.0), but it seems there is a dependency to System.Drawing.Common, so I'm not sure how this should work on .NET Core without having the "old" System.Drawing.Common available (which you wouldn't in a "pure" .NET Standard 2.0 environment).

Perhaps I'm just misunderstanding something basic here?

**Comment by tednyberg** [comment]
Do you have `OpenCvSharpExtern.dll` in your **bin** folder?

**Comment by clifu** [comment]
Yes, I do have that file in my bin folder.

**Comment by mailspeed** [comment]
I also encountered this problem. I finnaly find out that the reason lies in the operation system itself.
In my case, the OS is Windows10 N edition, which is lack of "**Windows_MediaFeaturePack**".
After download and install "**Windows_MediaFeaturePack_x64_1803.msu**", it works.
