### ISSUE TITLE
How to enable auto exposure after disable auto exposure?

### ISSUE THREAD

**Issue by yuzifu** [shimat/opencvsharp#541]
# Summary of your issue
I used the code cap. AutoExposure = 0.25 to disable auto exposure. What should I do if I want the camera to auto-explode again? I tried setting cap.AutoExposure to 0 or 1, but it didn't work. 
# Environment
OpenCvSharp 3.4.1

**Comment by DiomedesDominguez** [comment]
This might be something odd but you can try using a variable to store the previous value, like this:

```c#
double autoExposure = capture.AutoExposure;
capture.AutoExposure = 0.25;
//Do your thing with capture
capture.AutoExposure = autoExposure;
```

**Comment by yuzifu** [comment]
@DiomedesDominguez tks!
