### ISSUE TITLE
HOGDescriptorのCellSizeプロパティの返却値がWinSizeになっている

### ISSUE THREAD

**Issue by Kanimiya** [shimat/opencvsharp#546]
Tag:2.4.10.20170126を使っています。

HOGDescriptorのCellSizeプロパティの取得のところで
NativeMethodを呼び出している呼び出し先のobjdetect_HOGDescriptor_cellSize_get関数内で
cv::HOGDescriptorのwinSizeを返しています。

**Comment by Kanimiya** [comment]
最新版の3.4でも同様の現象を確認しました。

**Comment by shimat** [comment]
ありがとうございます 👍  #547 で修正します。
