### ISSUE TITLE
Subtract Operator is reversed.

### ISSUE THREAD

**Issue by harmonypiano** [shimat/opencvsharp#552]
matExpr - 1 gives wrong results, e.g (1,2,3) - 1 should be (0, 1, 2), instead it gives (0, -1, -2). Turns out that there are bugs in the following code in which subtraction with scalar is implemented reversed.
Also, note that addition with scalar is also implemented reversed, but in this case the order does not matter.

```
CVAPI(cv::MatExpr*) core_operatorSubtract_MatExprScalar(cv::MatExpr *e, CvScalar s)
{
    cv::MatExpr expr = s - (*e);
    return new cv::MatExpr(expr);
}
CVAPI(cv::MatExpr*) core_operatorSubtract_ScalarMatExpr(CvScalar s, cv::MatExpr *e)
{
    cv::MatExpr expr = (*e) - s;
    return new cv::MatExpr(expr);
}
```

**Comment by shimat** [comment]
Thanks!! 👍
