### ISSUE TITLE
Mat object is leaking memory.

### ISSUE THREAD

**Issue by Temppus** [shimat/opencvsharp#559]
# Summary of your issue
When mat is disposed by Garbage collector, allocated memory by native OpenCV library is not freed.

# Environment

Windows 10, 64 bit. OpenCv wrapper 3.4.1.20180830.

## Example code:

```
while (true)
{
    var mat = new Mat();
    //mat.Dispose();
}
```

## Output:
Expected result would be that garbage collector will call destructor of mat object and allocated memory is freed. But allocated memory keeps getting larger. If we call dispose manually, everything works as expected.

**Comment by shimat** [comment]
Please see #540. This issue is hard to solve.

**Comment by DiomedesDominguez** [comment]
I have to implement something like this to manage the memory

```csharp
            byte counter = 0;
            using (var camera = new VideoCapture(0))
            {
                using (var image = new Mat())
                {
                    while (++counter > 0)
                    {
                        camera.Read(image);
                        if (image.Empty()) break;
                        imgCamera.Source = image.ToBitmapSource();
                        await Task.Delay(33);
                        if (counter == byte.MaxValue)
                        {
                            counter = 0;
                            GC.Collect();
                        }
                    }
                }
            }
```

**Comment by shimat** [comment]
Close this duplicate issue
