### ISSUE TITLE
there is a few delay to capture frames from IP camera

### ISSUE THREAD

**Issue by msobhan69** [shimat/opencvsharp#560]
I've a Dahua IP camera. I want to read frames from it. The connection string is: rtsp://user:pass@ip:554/live.
I've found that rtsp use network caching. In VLC, there isn't any delay when I use ':rtsp-caching=1' or ':network-caching=1' but some frames are lost. Also, in web browsers, there isn't any delay.
As I found, there are two solution to solve my problem:
1- using http protocol: but I can't find the http connection string!!
2- using rtsp with less caching size of protocol: but i can't find this parameters in OpenCV, OpenCVsharp or Emgu!!

# Environment
Windows 10 64bit
C#

**Comment by msobhan69** [comment]
Dear @shimat , I tried that, but didn't work.

**Comment by yun-xu** [comment]
@shimat  it doesn't work.
