### ISSUE TITLE
Mat cannot be disposed

### ISSUE THREAD

**Issue by steeler18** [shimat/opencvsharp#561]
# Summary of your issue
Mat cannot be disposed 

# Environment
Windows 10. 64 bit. OpenCv Wrapper 3.3.1

## Example code:

while (true)
{
    var m = new Mat();
    m -= 1;
    m.Dispose();
}

## Output:
The memory usage keeps increasing. My speculation is that m-=1 creates some temporary objects that hold reference to the underlying matrix so m.Dispose() does not do what I expected.

**Comment by shimat** [comment]
Your code is interpreted as below.
```c#
Mat m = new Mat();
MatExpr expr = m - 1;
Mat newM = (Mat)expr;
newM.Dispose();
```

The result of `m - 1` is MatExpr. GC does not dispose `expr` and `m`. 
I defined custom operator overloads in order to approximate OpenCV C++ usage. But after I recognized I am annoyed with this problem for many years. I use cv :: subtract as much as possible.
