### ISSUE TITLE
GroupRectangle not working

### ISSUE THREAD

**Issue by thohemp** [shimat/opencvsharp#565]
# Summary of your issue
I don't get any useful results with groupRectangle. Setting the threshold to 1, it removes all rectangles.

## Example code:
What I am using currently:
`Cv2.GroupRectangles(rectList, 1, 0.2);`

## What did you intend to be?
I have a lot of rectangles in a list. I want overlapping rectangles to be merged.

**Comment by ScottHuang0710** [comment]
Hi,
Have you solved the problem？
Because I meet the same problem.

Thanks.

**Comment by thohemp** [comment]
No, as far as I am remember I didn't find a solution for this. I used a work around, that's not available anymore.
