### ISSUE TITLE
OpenCV 4.0 Updating new Branch

### ISSUE THREAD

**Issue by nemesis567** [shimat/opencvsharp#567]
# Summary of your issue

I am currently updating opencvsharp to use openCV 4. I am having trouble figuring out the correct process though. So what I did was compile all modules with contrib. I cloned this repo and replaced the linked .lib and includes for each module.

I wonder what's the next step in order to build the OpenCV external .dll. Since external dependencies are set I need to figure out how to update the remaining code base in this project.

# Environment

VS2017 enterprise
Windows 10 Pro

## What did you intend to be?

I need to update to 4.0 since I need to use Yolo V3. I could have updated to 3.4.2 but since I'm doing it I better just do the whole process.

**Comment by MateuszBogdan** [comment]
Great work on the project. It is very useful.
Have you figured out the 4.0 migration process? I am in dire need of NMSBoxes support which is predicted to ship with 4.0 PR. (#578) also for the yolo reason. Would love to know the ETA (even beta release) of this branch.
