### ISSUE TITLE
Cv2.Add needs to implement Scalar addition

### ISSUE THREAD

**Issue by gsonnenf** [shimat/opencvsharp#579]
# Summary of your issue
Was unit testing some interop and discovered Cv2.Add is not overloaded for scalar addition. It accepts scalars it just doesn't function properly.

# Environment
Windows 10, visual studio

# What did you do when you faced the problem?
Cv2.Subtract does function with scalars and I'm using that as a work around. It took me a while to figure out it wasn't my code that was broken, and that it wasn't implemented. The program really should have it.

# Core code:

The addition should be in: <opencvsharp/src/OpenCvSharp/Cv2/Cv2_core.cs>

Array/Array Addition:

Line 204: `public static void Add(InputArray src1, InputArray src2, OutputArray dst, InputArray mask = null, int dtype = -1)`

Array/Scalar Addition:
[The Array Scalar addition should be added here. a quick work around would be to just wrap the Array/Scalar subtraction and invert the scalar sign. It would be better to add it to NativeMethods and the CPP extern.]

Array/Array Subtraction:

Line 243: `public static void Subtract(InputArray src1, InputArray src2, OutputArray dst, InputArray mask = null, int dtype = -1)`

Array/Scalar Subtraction:

Line 281: `public static void Subtract(InputArray src1, Scalar src2, OutputArray dst, InputArray mask = null, int dtype = -1)`

**Comment by shimat** [comment]
I found a bug of conversion from Scalar to InputArray. This is fixed in #577. https://github.com/shimat/opencvsharp/pull/577/commits/2e6904507b50102eadc952fd5a659ed6b9d0358e

Scalar or double value is implicitly converted to InputArray, so the overload with Scalar is not necessary.

**Comment by gsonnenf** [comment]
Ok. I hope it fixes all the scalar operations then.

Please see the following:

# Code
`            Console.WriteLine("Pixel:" + mat.Get<Single>(0, 10));
            Cv2.Subtract(mat,1,mat);
            Console.WriteLine("subtracted 1:" + mat.Get<Single>(0, 10));
            Cv2.Divide(mat, 2.0, mat);
            Console.WriteLine("multiply 2:" + mat.Get<Single>(0, 10));
            Cv2.Divide(mat, 2.0, mat);
            Console.WriteLine("divide 2: " + mat.Get<Single>(0, 10));
            Cv2.Add(mat,1,mat);
            Console.WriteLine("add 1:" + mat.Get<Single>(0, 10));`

# Output
Pixel:-0.9957013
subtracted 1:-1.995701
multiply 2:-8
divide 2: -8
add 1:-8
