### ISSUE TITLE
How to use Gpu in opencvsharp?

### ISSUE THREAD

**Issue by Naked-Hidden** [shimat/opencvsharp#581]
Hi,How to use gpu in opencvsharp
# Environment
win10+vs2017+opencvsharp4.0.0

## Example code:
```c#
using OpenCvSharp;
using OpenCvSharp.Cuda;
using static OpenCvSharp.Cv2;
namespace ConsoleCV
{
    class Mycv
    {
        public static void useGpu()
        {
            GpuMat gmat = new GpuMat(new Size(300,300),MatType.CV_8UC3,new Scalar(100,100,100));
            new Window("gpumat",WindowMode.Normal,gmat);
            WaitKey();
        }
    }
}
```
this is my device,device with cuda.
![device](https://user-images.githubusercontent.com/30792256/49354816-ae875c00-f6ff-11e8-9586-ee0b39415125.png)

![wr](https://user-images.githubusercontent.com/30792256/49325763-a2c25b00-f582-11e8-98ad-7f2d8bfe3ddd.png)

**Comment by shimat** [comment]
The GPU features' wrapper is almost unimplemented. Since GPU features require users to build themselves, general-purpose wrapper implementation is difficult. I am considering deleting OpenCvSharp.Gpu.

**Comment by Naked-Hidden** [comment]
okay, i know, thank you.
