### ISSUE TITLE
VideoCapture error in latest version

### ISSUE THREAD

**Issue by MrGints** [shimat/opencvsharp#583]
# Summary of your issue I have been using Version 3.4.1.20180830 to capture images from a AmScope MU1803 camera (USB3 connection). I tried updating to version 4.0.0.20181129 and I can no longer capture images. If I return to Version 3.4.1.20180830 I can again capture images.  I did make a simple C3 project to recreate this issue. 

3.4.1.20181108 also works but 3.4.4.20181118 does not.

This error also exists with a second AmScope Camera. I am using the latest DirectShow driver from AmScope.

# Environment 
Visual Studio 4.7.03056

# What did you do when you faced the problem?

 I tried updating to version 4.0.0.20181129 and I can no longer capture images. If I return to Version 3.4.1.20180830 I can again capture images.  I did make a simple C3 project to recreate this issue. 

3.4.1.20181108 also works but 3.4.4.20181118 does not.

## Example code:
```c#
using OpenCvSharp;
using DirectShowLib;
using System.Diagnostics;

namespace QuickOpenCVTest
{
    public class TestClass
    {
       public  Mat m = new Mat();
        public DsDevice[] _systemCameras = DsDevice.GetDevicesOfCat(FilterCategory.VideoInputDevice);
        public TestClass()
        {
            Mat imgZero = new Mat();
            Mat imgOne = new Mat();
            Mat imgTwo = new Mat();
            int i = 0;
            VideoCapture[] videoCaptures = new VideoCapture[3];
            foreach (DsDevice dsDevice in _systemCameras)
            {
                videoCaptures[i] = new VideoCapture(CaptureDevice.DShow, i);
                if(!videoCaptures[i].IsOpened())
                {
                    //MU1603 hits this if the problem exisits
                    Debug.WriteLine($"camera {i} not opened"); 
                }
                i++;
            }
            videoCaptures[0].Read(imgZero); //integrated web cam
            videoCaptures[1].Read(imgOne); // usb 2.0 cam
            videoCaptures[2].Read(imgTwo); // MU1603

             videoCaptures[0].Dispose();
            videoCaptures[1].Dispose();
            videoCaptures[2].Dispose(); 
            
        }
    }
```

imgTwo is empty.

## Output:

```
paste your output
```

## What did you intend to be?
imgTwo to have an img

Thanks.

**Comment by blaisexen** [comment]
@MrGints 
.
NO
it doesn't for me, updated OpencvSharp4.0.0(with NO CUDA support)
.
My <Test? application withOUT DirectShowLib FILE anymore :dancing_women: 
https://sourceforge.net/projects/opencvsharp-live-face-detect/
