### ISSUE TITLE
Mat.GetArray -> CheckArgumentsForConvert - row and col input

### ISSUE THREAD

**Issue by facebamm** [shimat/opencvsharp#585]
# Summary of your issue

My issue is, if you use Mat.Rows or Mat.Cols you will always get an error bc. the "CheckArgumentsForConvert" method checking for row (input parameter) bigger then equal (>=) this.Rows(your object). 
The next problem is GetArray doesn't work. 
# Environment

Visual Studio 2019 Preview

# What did you do when you faced the problem?

```csharp
 int byteCount = IntPtr.Size == 8 
        ? (int)(outputMat.DataEnd.ToInt64() - outputMat.DataStart.ToInt64())
        :  outputMat.DataEnd.ToInt32() - outputMat.DataStart.ToInt32();
            
byte[] buffer = new byte[byteCount];
Marshal.Copy(outputMat.DataStart, buffer, 0, byteCount);
```
## Exception Example code: 

```csharp
int byteCount = outputMat.Rows * outputMat.Cols * 4; //MatType.CV_8UC4
byte[] buffer = new byte[byteCount];
outputMat.GetArray(outputMat.Rows, outputMat.Cols, buffer);  
//throw new ArgumentOutOfRangeException("row");
```

**Comment by shimat** [comment]
please try `outputMat.GetArray(0, 0, buffer);  `
0, 0 means top-left coordinates

**Comment by facebamm** [comment]
work 👍 thx.
