### ISSUE TITLE
OpenCVSharp Version 4 depends on mfplat.dll

### ISSUE THREAD

**Issue by grisharav** [shimat/opencvsharp#589]
# Summary of your issue

When deploying our application that was upgraded to latest OpenCVSharp all worked fine in desktop environment, but when I tried to use OpenCVSharp 4.0.0 on Win 2012 R2 environment I got:

> System.TypeInitializationException : The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
---- System.DllNotFoundException : Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenCvSharp.NativeMethods.core_Mat_new2(Int32 rows, Int32 cols, Int32 type)
   at OpenCvSharp.Mat..ctor(Size size, MatType type) in C:\projects\opencvsharp\src\OpenCvSharp\Modules\core\Mat\Mat.cs:line 121

After some digging and running Procmon, I noticed that the code tries to load  `C:\Windows\System32\mfplat.dll`

I installed Windows Server Essentials Media Pack (https://www.microsoft.com/en-us/download/details.aspx?id=40837), and got the dependency satisfied, but I believe the code should run in server environment since no device interaction is performed.

# Environment

Windows Server 2012 R2

# What did you do when you faced the problem?

Just run any code referencing OpenCVSharp on a server without mfplat.dll available.

**Comment by grisharav** [comment]
It actually seems that OpenCVSharp 3.4.4 has this issue as well, when 3.4.1 does not.

**Comment by shimat** [comment]
It may be because I built OpenCV with WITH_MSMF flag enabled. I will reconsider the flag in development of 4.0.1 or later. https://github.com/opencv/opencv/blob/7fb70e170154d064ef12d8fec61c0ae70812ce3d/CMakeLists.txt#L344

**Comment by grisharav** [comment]
Thanks, when can we expect 4.0.1 release?

**Comment by shimat** [comment]
Thank you for waiting https://www.nuget.org/packages/OpenCvSharp4/4.0.1.20190326

**Comment by Sicos1977** [comment]
I still get the mfplat.dll error even with the latest version on nuget

**Comment by gravikovich** [comment]
Hi, could it be that the issue is back? I now test it with 4.1.1 and see it again...

**Comment by gravikovich** [comment]
Hi, I see the dependency upon `mfplat.dll` is back again on newer versions of the library (4.4, 4.5). Is this intentional?
