### ISSUE TITLE
FLIP X and Y wrong enum values

### ISSUE THREAD

**Issue by Xtian74** [shimat/opencvsharp#594]
# Environment

Visual studio community 2017

# What did you do when you faced the problem?

Simply flipped an image: according with opencv documentation FlipMode.Y should be 1, FlipMode.Y 0. Constant are iverted.

## Example code:

```
frameY = frame.Flip(FlipMode.X) 'flips the image vertically
```

**Comment by shimat** [comment]
https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L1054

As you say, the enum flag names of the OpenCvSharp's Flip mode may create misunderstandings, but the names are not wrong. FlipMode.Y means flipping around y-axis. In other words, target image is flipped in the x-axis direction.
