### ISSUE TITLE
Error CS1705 when using OpenCvSharp3-AnyCPU

### ISSUE THREAD

**Issue by sansjunk** [shimat/opencvsharp#597]
# Summary of your issue
I get the following error when I include package OpenCvSharp3-AnyCPU

```error CS1705: Assembly 'OpenCvSharp.Extensions' with identity 'OpenCvSharp.Extensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6adad1e807fea099' uses 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Drawing.Common' with identity 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'```

# Environment

I am using OpenCVSharp3-AnyCPU (v4.0.0.20181129) in a DLL project that targets both .NET Framework 4.0 and .NET Standard 2.0. The project builds fine for .NET Framework 4.0 but throws the above error when building for .NET Standard 2.0.

**Comment by frank-ozgul** [comment]
I have the same problem. I was about to post the same error text here just now.
