### ISSUE TITLE
OpenCVSharpのMulti Trackerがうまく使えません。

### ISSUE THREAD

**Issue by aytk** [shimat/opencvsharp#601]
# Summary of your issue
OpenCVSharpのMulti Trackerがうまく使えません。

# Environment
Visual Studio 2017
unity

# What did you do when you faced the problem?
追跡領域を２箇所にしたいのですが、１つ目しかトラッキングされず、２つ目はUpdateすると(x:0 y:0 width:0 height:0)になってしまいます。（Updateする前は(x:300 y:300 width:100 height:100)）
[追記] ２つ目がAddできてないかもしれないです。

## Example code:

void Start()のMultiTracker部分

```
multitracker = MultiTracker.Create();
tracker = TrackerMIL.Create();
bbox1 = new Rect2d(10, 10, 200, 200); 
bbox2 = new Rect2d(300, 300, 100, 100);  
bboxArray = new Rect2d[] { bbox1, bbox2 };
trackers = new Tracker[] { tracker, tracker };
bool add = multitracker.Add(trackers, mat, bboxArray);
```
void Update()のMultiTracker部分

`bool update = multitracker.Update(mat, out bboxArray);`

**Comment by shimat** [comment]
遅くなりましてすみません。
OpenCVの仕様と思われました。実装に問題は見つけられません。
https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/src/multiTracker_alt.cpp#L62

同じtrackerインスタンスを重複して配列に入れてしまうと、上記箇所で2重にinitされ、1度目は良いですが2度目でAddの返り値がfalseになるようです。従ってコメント頂いている通り、2つ目がAddできていないようです。今回で言えば、 `TrackerMIL.Create();` を2回行って2つのインスタンスを作れば、一応は回避できます。
