### ISSUE TITLE
Bug in GrabCut

### ISSUE THREAD

**Issue by yjr930** [shimat/opencvsharp#603]
# Summary 
Throw
OpenCvSharp.OpenCVException: 'dtrm > std::numeric_limits<double>::epsilon()'
When use grabcut.

# Environment
win10 x64
.Net 4.6.1
opencvsharp 4.0.0, 3.4.4

# What did you do when you faced the problem?
This is an old bug which has been fixed but it appears in opencvsharp.

## Example code:

```
            Mat bgdModel = new Mat(new Size(65, 1), MatType.CV_64FC1);
            Mat fgdModel = new Mat(new Size(65, 1), MatType.CV_64FC1);

            Mat grab_mask = new Mat(MaskMat.Size(), MatType.CV_8UC1, new Scalar((double)GrabCutClasses.PR_BGD));

            for (int r=0; r<MaskMat.Height; r++) {
                for (int c=0; c<MaskMat.Width; c++) {
                    var p = MaskMat.At<double>(r, c);
                    if (p == FG_Brush) {
                        grab_mask.Set<double>(r, c, 1.0);
                    } else {
                        grab_mask.Set<double>(r, c, 0.0);
                    }
                }
            }
            src_img.GrabCut(grab_mask, new Rect(), bgdModel, fgdModel, 3, GrabCutModes.InitWithMask);
```

## Output:

```
OpenCvSharp.OpenCVException: 'dtrm > std::numeric_limits<double>::epsilon()'
```

**Comment by shimat** [comment]
> This is an old bug which has been fixed but it appears in opencvsharp.

🤔 
https://stackoverflow.com/questions/13007926/opencv-grabcut-cpp-error

I don't know what to do. I don't want to define NDEBUG because of exception message usability.

**Comment by yjr930** [comment]
I found the problem at last.
We shouldn't define `bgdModel` and `fgdModel` as:
```
Mat bgdModel = new Mat(new Size(65, 1), MatType.CV_64FC1);
Mat fgdModel = new Mat(new Size(65, 1), MatType.CV_64FC1);
```
It is an all-zoro matrix which will cause the `dtrm` become zero.
We should just define them as `new Mat()`:
```
Mat bgdModel = new Mat();
Mat fgdModel = new Mat();
```
Or just:
`src_img.GrabCut(grab_mask, new Rect(), new Mat(), new Mat(), 3, GrabCutModes.InitWithMask);`
