### ISSUE TITLE
OpenCvSharp4.Windows Unable to load DLL 'OpenCvSharpExtern'

### ISSUE THREAD

**Issue by died** [shimat/opencvsharp#605]
# Summary of your issue
Getting OpenCvSharp4.Windows from nuget, try [demo code](https://github.com/shimat/opencvsharp#usage) of lenna, got this error
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
  Source=OpenCvSharp
  StackTrace:
   at OpenCvSharp.NativeMethods.imgcodecs_imread(String filename, Int32 flags)
   at OpenCvSharp.Mat..ctor(String fileName, ImreadModes flags)
   at OpenCvSharpYolo3.Program.Main(String[] args) in D:\Users\Died.Liu\source\repos\OpenCvSharpYolo3\OpenCvSharpYolo3\Program.cs:line 14

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
# Environment
package id="OpenCvSharp4.Windows" version="4.0.0.20181225" targetFramework="net46"
win 10 v1809 , vs2017 v18.8.9

# What did you do when you faced the problem?
the demo code work on OpenCvSharp v3, it should be work at v4

## Example code:
 [demo code](https://github.com/shimat/opencvsharp#usage) 

# Quick fix
**stupid way** copy dll folder from previous project that using OpenCvSharp3.
 ![img](https://i.imgur.com/olorooo.png)
put into your `\bin\debug` then it work, but I think it's for v3 not v4.

## Guess
Maybe it's typo or something, @shimat can you check it ?

I noticed on frontpage [ubuntu build Instructions](https://github.com/shimat/opencvsharp#ubuntu-1804-1) have `Build native wrapper OpenCvSharpExtern`, so I think it maybe miss on OpenCvSharp4.Windows nuget package, it didn't include OpenCvSharpExtern.dll,

**Comment by died** [comment]
I test Sample-4.0.0-20181130.zip from [release](https://github.com/shimat/opencvsharp/releases), it got same error.

**Comment by died** [comment]
BTW, I checked x64 and x86 zip in [release](https://github.com/shimat/opencvsharp/releases), both have include OpenCvSharpExtern.dll, so I think it must be some kind of forgot 😄

**Comment by shimat** [comment]
Please try the latest package. https://www.nuget.org/packages/OpenCvSharp4.Windows/4.0.0.20190108
The problem may be caused by my mistake in the .props file name.

**Comment by died** [comment]
It's work, thanks for your efforts.

**Comment by CityAndTheStars** [comment]
This is still a problem with the latest version (4.2....).
Do you have a plan to fix this?

**Comment by doug62** [comment]
I have the same problem with the VideoCaptureForm and SamplesVB projects

**Comment by nombrote** [comment]
I have the some project with versión 4.2.20200421

**Comment by nombrote** [comment]
I have the some project with versión4.22.20200208

**Comment by dev-ptdi** [comment]
I have the same problem version 4.3.0.20200524

**Comment by shinkamui** [comment]
v4.5.1.20210210 still the same.
I just download sample project directly from github, set the VideoCaptureForm as startup proj and run, the error showed up. Did I miss any step?

**Comment by hamed-ahangari** [comment]
Same runtime exception with installed version : 4.5.3.20210817

**Comment by hamed-ahangari** [comment]
Hello guys.
You need to install both of these NuGet packages not only the first one (in my case, it fixed the problem):

- OpencvSharp4
- OpencvSharp4.runtime.win
hope it helps.

**Comment by hamed-ahangari** [comment]
Hello guys.
You need to install both of these NuGet packages, not only the first one (in my case, it fixed the problem):

- OpencvSharp4
- OpencvSharp4.runtime.win

I hope it helps.
