### ISSUE TITLE
DrawContours instability

### ISSUE THREAD

**Issue by CpBobette** [shimat/opencvsharp#606]
# Summary of your issue
When using Cv2.DrawContours with an empty Mat some random-ish pixels are drawn.

# Environment
.Net framework 4.6.1 with 4.0.0.20181129 NuGet with DLL

## Example code:

this will work
            Mat mask = Img.Clone();
            Cv2.DrawContours(mask, savedContour, 0, new Scalar(255), -1);

this will add random pixels
           Mat mask = new Mat(Img.Size(), MatType.CV_8UC1);
           Cv2.DrawContours(mask, savedContour, 0, new Scalar(255), -1);

I get the same behavior while using a different line thickness and with BGR images.
When using this in a more complex scenario I would get the issue every once in a while, could it be a race condition?

Best regards, 
## Output:
![image](https://user-images.githubusercontent.com/46541110/50927456-d7e58700-1425-11e9-865f-bf44a19c97f2.png)

## What did you intend to be?
![image](https://user-images.githubusercontent.com/46541110/50927320-5e4d9900-1425-11e9-9f2c-4c1b870d18f1.png)

**Comment by shimat** [comment]
The behavior is by design. You should zero-fill input image beforehand by `Mat.Zeros()` or `Mat.SetTo(Scalar.All(0))`, etc.
