### ISSUE TITLE
DllNotFoundException : Impossible to load Dll 'OpenCvSharpExtern'

### ISSUE THREAD

**Issue by AmraniRiyad** [shimat/opencvsharp#610]
I am using OpenCvSharp to perform homography calculation and PerspectiveTransform. I use MVVM patern. OpenCvSharp works perfectly but I have this error message (attached file) at every software startup and after closing the error message I can use the my software normally.

![opencverror](https://user-images.githubusercontent.com/9655024/51190103-bc74f300-18e1-11e9-8827-fa3e83c58f26.png)

I tried to upgrade to OpenCvSharp4 4.0.0.20190108 but this time my software crashes completly and opencv do not work.

OpenCvSharpExtern.Dll is in :
Bin/Debug/dll/x64 
&
Bin/Debug/dll/x86

I tried to copy it to Debug folder but same problem.

# Environment
OpenCvSharp3-AnyCPU 4.0.0.20181129
NET Framework 4.7.1
Windows 7

**Comment by shimat** [comment]
Please try checking dependencies of the OpenCvSharpExtern.dll using DependencyWalker or Dependencies, etc.
http://www.dependencywalker.com/
https://github.com/lucasg/Dependencies

**Comment by AmraniRiyad** [comment]
@Died Just tried 4.0.0.20190108 again right now and it seems like its working smoothly. Can't really say what changed from last time.

@Shimat Regarding OpenCvSharp3-AnyCPU 4.0.0.20181129 version,  I checked OpenCvSharpExtern.dll dependencies with DependencyWalker and this is what came out for both x86 dll & x64 dll.

**Comment by AmraniRiyad** [comment]
@Died Just tried 4.0.0.20190108 again right now and it seems like its working smoothly. Can't really say what changed from last time.

@shimat Regarding OpenCvSharp3-AnyCPU 4.0.0.20181129 version,  I checked OpenCvSharpExtern.dll dependencies with DependencyWalker and this is what came out for both x86 dll & x64 dll.

**Comment by shimat** [comment]
🤔 
Your x86 dependency seems to be fine. To check x64 OpenCvSharpExtern.dll, please use x64 Dependency Walker to get correct result.
Your C# build configuration is x86? or x64?

**Comment by AmraniRiyad** [comment]
@shimat x64 OpenCvSharpExtern.dll looks fine too with x64 Dependency Walker

I use "Any CPU" build configuration.

**Comment by blaisexen** [comment]
@AmraniRiyad 
is it solved?

if not, Try to download another set of x64 opencvsharp dlls....then reinstall at your root and sub-folder, overwrite the old, and I think that will be fine.

I ques opencvsharp.dll(x86) calls opencvsharpExtern.dll(x64), so they are not compatible.

**Comment by Tam66662** [comment]
This issue with missing OpenCvSharpExtern.dll is happening to me as well on OpenCvSharp3-AnyCPU.4.0.0.20181129 and I have a work around.

I can see in my project's "packages" folder that it contains the "OpenCvSharpExtern.dll" under the OpenCvSharp3-AnyCPU.4.0.0.20181129/runtimes/win10-x64/native/ folder.

![image](https://user-images.githubusercontent.com/12551526/61508404-89014700-a99e-11e9-8989-0cf3553989bf.png)


However, whenever I delete my Visual Studio 2017 solution's .vs folder and also the project's build output folder (this happens whenever I do a 'git clean' on my local repository), and then rebuild the project (Debug/x64), it fails to copy over this OpenCvSharpExtern.dll (along with the other one in the same folder) from the packages/ folder to the build output's "dll/x64/" subfolder.

The only way to resolve this (my work around) is to uninstall the OpenCvSharp3-AnyCPU.4.0.0.20181129 Nuget package and re-install it every time I do a 'git clean'.  Here is the creation of the build output subfolder only after I uninstall/reinstall OpenCvSharp:

![image](https://user-images.githubusercontent.com/12551526/61508298-1728fd80-a99e-11e9-819e-782018a22413.png)


I have had to do this on a daily basis for the past two months, and if you can imagine doing this 100 times, then you can imagine it gets increasingly annoying every time as well.

Any help with resolving this would be greatly appreciated.

**Comment by died** [comment]
@Tam66662 Did you try new version ?

**Comment by Tam66662** [comment]
@died I thought I was on the latest version, but I guess I wasn't!  Thanks for the tip.  When I removed the OpenCVSharp3-AnyCPU nuget package and installed the OpenCVSharp4.Windows nuget package, the issue went away.

Much appreciated!
