### ISSUE TITLE
SIFT Tutorial for OpenCVSharp 4.0.0.20181129

### ISSUE THREAD

**Issue by AlucardNosferatu** [shimat/opencvsharp#611]
use:
`SIFT sift = SIFT.Create();`
&
`SURF surf = SURF.Create();`
Instead Of
`SIFT sift = SIFT();`
&
`SURF surf = SURF();`

**Comment by AlucardNosferatu** [comment]
sift.Run() is replaced by sift.Compute()

**Comment by shimat** [comment]
What does this issue mean? What's the problem?

**Comment by AlucardNosferatu** [comment]
The wiki use different function names comparing to the version downloaded with NuGet

**Comment by AlucardNosferatu** [comment]
The wiki use different function names comparing to the version downloaded with NuGet

**Comment by shimat** [comment]
ah, I see. thanks. fixed it.
