### ISSUE TITLE
SolvePnP with InitialGuess using out parameters

### ISSUE THREAD

**Issue by DKirsch4** [shimat/opencvsharp#617]
If you want to use the SolvePnP() method with out parameters it is not possible to use InitialGuess. In the C++ API this is defined as a reference parameter, in the C# wrapper it is defined as an output only parameter. It should be redefined as a 'ref' parameter in the C# wrapper so that callers are able to set an initial value before calling the function.
```
Cv2.SolvePnP(objectPoints,
                      imagePoints,
                      cameraMatrix,
                      distortionVector,
                      out rvec,
                      out tvec,
                      true,
                      SolvePnPFlags.Iterative);
```

**Comment by shimat** [comment]
Thanks! #620 will fix this issue.
