### ISSUE TITLE
What's with OpencvSharp File Structures with Cuda?

### ISSUE THREAD

**Issue by blaisexen** [shimat/opencvsharp#625]
Emgu Cv with Cuda file structure here....
.
My .Net.Application.EXE
Emgu.CV.World.dll = file
x64 = folder -> inside_folder -> "cvExtern.dll" and Cuda files and OpenCv files(Compiled with Cuda)
.
.
What's with OpencvSharp with Cuda?

**Comment by shimat** [comment]
I am sorry but OpenCvSharp's cuda features are deleted. https://github.com/shimat/opencvsharp/pull/593

**Comment by blaisexen** [comment]
@shimat 
yes I understand, but I just want to know, if are deleted then I can used the old opencvsharp.

Just please let me know

**Comment by shimat** [comment]
OpenCV DLLs I released used by old OpenCvSharp were built without cuda. I guess OpenCvSharp's cuda features had been unusable for a long time. 
It is necessary for users to custom-build OpenCV for their own GPU. It is unmanagable and unsupportable for me, so I abolished cuda features.

**Comment by blaisexen** [comment]
@shimat 
yes I understand but just please let me know if it needs also a folder like emgu cv file structure that I write, I just want to test, that's all, and if I know then I will not ask about cuda opencvsharp.

**Comment by shimat** [comment]
I cannot understand your problem, and "emgu cv file structure" that you wrote. Sorry.
You can specify DLL load paths by `OpenCvSharp.WindowsLibraryLoader.Instance.AdditionalPaths.Add(path);`

**Comment by shimat** [comment]
Yes I saw the structure explanation, and I cannot understand it at all. What does `=` mean?  x64 = folder ???  I dont know Emgu CV details so I cannot understand "Emgu.CV.World.dll = file".

I don't support deleted features. The reason why I deleted cuda features is that I can't support them and I don't want to answer cuda issues such as this. Sorry.
