### ISSUE TITLE
KNearest + GPU

### ISSUE THREAD

**Issue by turowicz** [shimat/opencvsharp#629]
Hey guys,

If I have the OpenCV compiled and running with CUDA, will the KNearest have similar performance to the ScikitLearn's equivalent?

Cheers

cc @shimat

**Comment by turowicz** [comment]
Actually turns out Scikitlearn is not meant for deep learning, so it doesn't utilize GPU. Tensorflow does. I guess the question really is: Does OpenCV KNN utilize GPU?

**Comment by kmate95** [comment]
I used CUDA KNN implementation, but it was just an experiment never got to compare performance.
```c++
using (var matcher = new CudaBFMatcher(DistanceType.L2))
{
    var matchvec = new VectorOfVectorOfDMatch(otherpoints.Rows);
    GpuMat q = new GpuMat(otherpoints), t = new GpuMat(GetPointMatrix.Convert<float>());
    matcher.KnnMatch(q, t, matchvec, maxcheckedpoints); // is GPUMat needed?`
}
```
Not really sure what the method did, but I found this snippet on the old code.
