### ISSUE TITLE
StereoCalibrate Error  i < 0

### ISSUE THREAD

**Issue by dmm-john** [shimat/opencvsharp#631]
# Summary of your issue
I'm attempting to run StereoCalibrate on the left/right calibration images in the example data.  I can calibrate each camera separately but I get this very undescriptive error ( i < 0 ) when moving on to the StereoCalibrate function.
There's a good probability that one of my inputs isn't right, but I have no way of knowing which one.  From what I can tell, all inputs are the correct type and size.  Nothing is empty.

# Environment
Windows 10, x64

# What did you do when you faced the problem?
Checked to make sure all input lists of points are the correct size, not empty or null.  

## Example code:

`
            // images contains a list of pairs of left/right images
            var objectPointsOfFrames = new List<InputArray>(images.Count);

            var leftImagePointsOfFrames = new List<InputArray>(images.Count);
            var rightImagePointsOfFrames = new List<InputArray>(images.Count);

            var frameSize = images.First().Item1.Size();

            foreach (var imagePair in images)
            {
                // I can confirm that each image contains a chessboard pattern and returns points
                leftImagePointsOfFrames.Add(chessBoard.FindFromImage(imagePair.Item1));
                rightImagePointsOfFrames.Add(chessBoard.FindFromImage(imagePair.Item2));

                // This adds a MatOfPoint3f with the points in the chess pattern
                objectPointsOfFrames.Add(chessBoard.GetObjectMatPoints());
            }

            var essentialMatrix = new Mat();
            var fundamentalMatrix = new Mat();

              // LeftCam.CamMatrix, LeftCam.DistortionCoefficients are configured from successfully calibrating from the left image set.  The same applies to RightCam.
              Cv2.StereoCalibrate(
                    objectPointsOfFrames,
                    leftImagePointsOfFrames,
                    rightImagePointsOfFrames,
                    LeftCam.CamMatrix, LeftCam.DistortionCoefficients,
                    RightCam.CamMatrix, RightCam.DistortionCoefficients,
                    frameSize, RotationVector, TranslationVector, essentialMatrix, fundamentalMatrix);
`

## Output:

OpenCvSharp.OpenCVException: i < 0
  at OpenCvSharp.NativeMethods+<>c.<.cctor>b__1619_0 (OpenCvSharp.ErrorCode status, System.String funcName, System.String errMsg, System.String fileName, System.Int32 line, System.IntPtr userdata) [0x00010] in <45a494b8b9514a01b4c3f460652ae2ad>:0 
  at (wrapper managed-to-native) OpenCvSharp.NativeMethods.calib3d_stereoCalibrate_InputArray(intptr[],int,intptr[],int,intptr[],int,intptr,intptr,intptr,intptr,OpenCvSharp.Size,intptr,intptr,intptr,intptr,int,OpenCvSharp.TermCriteria)
  at OpenCvSharp.Cv2.StereoCalibrate (System.Collections.Generic.IEnumerable`1[T] objectPoints, System.Collections.Generic.IEnumerable`1[T] imagePoints1, System.Collections.Generic.IEnumerable`1[T] imagePoints2, OpenCvSharp.InputOutputArray cameraMatrix1, OpenCvSharp.InputOutputArray distCoeffs1, OpenCvSharp.InputOutputArray cameraMatrix2, OpenCvSharp.InputOutputArray distCoeffs2, OpenCvSharp.Size imageSize, OpenCvSharp.OutputArray R, OpenCvSharp.OutputArray T, OpenCvSharp.OutputArray E, OpenCvSharp.OutputArray F, OpenCvSharp.CalibrationFlags flags, System.Nullable`1[T] criteria) [0x0010c] in <45a494b8b9514a01b4c3f460652ae2ad>:0 

## What did you intend to be?
Not an exception :)

**Comment by dmm-john** [comment]
More info. 

 The actual exception comes from matrix_wrap.cpp line 50.
cv::_InputArray::getMat_

The data being passed in looks good, here's the general format of everything.
Object Points - Length: 13 Width: 1 Height: 54 Depth: 5 Type: CV_32FC3
Left Points - Length: 13 Width: 1 Height: 54 Depth: 5 Type: CV_32FC2
Right Points - Length: 13 Width: 1 Height: 54 Depth: 5 Type: CV_32FC2
Left Matrix - Width: 3 Height: 3 Type: CV_64FC1
Right Matrix - Width: 3 Height: 3 Type: CV_64FC1
Left Distortion - Width: 5 Height: 1 Type: CV_64FC1
Right Distortion - Width: 5 Height: 1 Type: CV_64FC1
Frame Size - (width:640 height:480)

Here's the interesting thing.  I got everything to work by using the other wrapped function:
double StereoCalibrate(IEnumerable<IEnumerable<Point3f>> objectPoints, ...
rather than
double StereoCalibrate(IEnumerable<InputArray> objectPoints, ...

**Comment by xiaofoliu** [comment]
I met the same error with you,however,I can't use the other wrapped function after changing the type of objectPoints from  (List<InputArray>  ) into ( List<List<Point3f>>) ,do you know why?

**Comment by dmm-john** [comment]
Here's my code, I hope it helps:



            var objectPointsOfFrames = new List<List<Point3f>>(images.Count);

            var leftImagePointsOfFrames = new List<List<Point2f>>(images.Count);
            var rightImagePointsOfFrames = new List<List<Point2f>>(images.Count);

            foreach (var imagePair in images)
               // Get all the points
           
            try
            {
                var essentialMatrix = new Mat();
                var fundamentalMatrix = new Mat();

                Cv2.StereoCalibrate(
                    objectPointsOfFrames,
                    leftImagePointsOfFrames,
                    rightImagePointsOfFrames,
                    LeftCamera.CameraMatrixDoubles, LeftCamera.DistortionCoefficentsDoubles,
                    RightCamera.CameraMatrixDoubles, RightCamera.DistortionCoefficentsDoubles,
                    frameSize, // end inputs
                    RotationVector, TranslationVector, essentialMatrix, fundamentalMatrix);

**Comment by dmm-john** [comment]
Oh... the camera matrix doubles were a pain in the ass.  Here's that too:

        public double[,] CameraMatrixDoubles
        {
            get
            {
                var matrix = new double[CameraMatrix.Height, CameraMatrix.Width];
                for (int i = 0; i < CameraMatrix.Rows; ++i)
                {
                    for (int j = 0; j < CameraMatrix.Cols; ++j)
                    {
                        matrix[i, j] = (double) CameraMatrix.At<float>(i, j);
                    }
                }

                return matrix;
            }
        }

**Comment by xiaofoliu** [comment]
It is indeed because of the type of camera matrix，after changing it into double[,]，the function works.Thank you for your help.

**Comment by guz-crypto** [comment]
Sorry to put that on that topic, but I'm searching with no luck how to calibrate a simple camera with version 4.x.

Is someone can give me a link to a real sample ?

Regards

**Comment by 159199** [comment]
@dmm-john, you saved my life, sir. Thanks for the code.

**Comment by nombrote** [comment]
where i can find a example to calibrate stereo cameras, i'm looking into the examples and onto the web and i dont found that example
