### ISSUE TITLE
System.AccessViolationException in Feature2D.Compute

### ISSUE THREAD

**Issue by scarlet1030** [shimat/opencvsharp#632]
# Summary of your issue
When I call the Feature2D.Compute method, System.AccessViolationException is thrown. The code was created with reference to OpenCVSharp Samples.

# Environment
Visual Studio2010
Any CPU

# What did you do when you faced the problem?

//write here

## Example code:
public void FeatureMatching()
        {
            var img1 = new Mat();
            var img2 = new Mat(@"E:\test.jpg", ImreadModes.Grayscale);

            Mat src = new Mat();
            Mat src_cvt = new Mat();

            src = camera.RetrieveMat();
            Cv2.CvtColor(src, src_cvt, ColorConversionCodes.BGR2GRAY);

            img1 = src_cvt;
            Cv2.ImShow("Left", img1);
            Cv2.WaitKey(1); // do events

            Cv2.ImShow("Right", img2);
            Cv2.WaitKey(1); // do events

            // detecting keypoints
            // FastFeatureDetector, StarDetector, SIFT, SURF, ORB, BRISK, MSER, GFTTDetector, DenseFeatureDetector, SimpleBlobDetector
            // SURF = Speeded Up Robust Features
            var detector = SURF.Create(hessianThreshold: 400); //A good default value could be from 300 to 500, depending from the image contrast.
            var keypoints1 = detector.Detect(img1);
            var keypoints2 = detector.Detect(img2);

            KeyPoint[] keypoints1_1 = new KeyPoint[keypoints1.Length * 2];
            KeyPoint[] keypoints2_1 = new KeyPoint[keypoints2.Length * 2];

            // computing descriptors, BRIEF, FREAK
            // BRIEF = Binary Robust Independent Elementary Features
            var extractor = BriefDescriptorExtractor.Create();

            var descriptors1 = new Mat();
            var descriptors2 = new Mat();

            **extractor.Compute(img1, ref keypoints1_1, descriptors1);  // System.AccessViolationException**
            extractor.Compute(img2, ref keypoints2_1, descriptors2);

            // matching descriptors
            var matcher = new BFMatcher();
            var matches = matcher.Match(descriptors1, descriptors2);

            // drawing the results
            var imgMatches = new Mat();
            Cv2.DrawMatches(img1, keypoints1, img2, keypoints2, matches, imgMatches);
            Cv2.ImShow("Matches", imgMatches);
            Cv2.WaitKey(1); // do events

            Cv2.WaitKey(0);

            Cv2.DestroyAllWindows();
            img1.Dispose();
            img2.Dispose();            
        }

## Output:

![image](https://user-images.githubusercontent.com/47444989/52467677-b369ff80-2bc9-11e9-8e76-39276b42f8b7.png)

**Comment by nombrote** [comment]
I have the some error
