### ISSUE TITLE
オプティカルフローについて 

### ISSUE THREAD

**Issue by ikeda28** [shimat/opencvsharp#636]
池田と申します。よろしくお願いします。

オプティカルフローロジックのC++のソースをC#に移植しているのですが、C++の下記のソースの
移植について質問いたします。
C++
Ptr<DualTVL1OpticalFlow> opf = createOptFlow_DualTVL1();
  opf->setWarpingsNumber(3);                      // パラメータ設定
  opf->setEpsilon(0.05);
  opf->calc(pre, now, flow);

C#
var opf = Cv2.CreateOptFlow_DualTVL1Ex();
//opf->setWarpingsNumber(3);                      // パラメータ設定
//opf->setEpsilon(0.05);
opf.Calc(pre, now, flow);

opf->setWarpingsNumber(3); と
opf->setEpsilon(0.05);ですが、メソッドがわかりませんでした。
どのように記述すればいいのでしょうか？

以上、よろしくお願いいたします。

**Comment by shimat** [comment]
このあたりの関数ですね。https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/include/opencv2/optflow.hpp#L250

開発途上にてまだラッパーがありません。改善ネタとして積みます。

**Comment by ikeda28** [comment]
了解いたしました。
よろしくお願いします。

**Comment by shimat** [comment]
可能でしたらpull requestもお待ちしております
