### ISSUE TITLE
The performance of instantiating VideoCapture class in 64-bit programs is poor.

### ISSUE THREAD

**Issue by yuzifu** [shimat/opencvsharp#641]
# Summary of your issue
The performance of instantiating VideoCapture class in 64-bit programs is poor. It takes more than 5 seconds.
# Environment
win 10 64bit (1809)
VS 2017
WPF Application
.Net framework 4.7
64bit platform target
OpenCvSharp4  4.0.0

# What did you do when you faced the problem?

If I change platform target to 32bit, It takes about 1 second.
If I downgrade OpenCvSharp4 to OpenCvSharp3 3.4.1，It only takes less than 1 second.

## Example code:

```
using System;
using System.Windows;
using cv = OpenCvSharp;

namespace WpfApp1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            cv.VideoCapture v = new cv.VideoCapture(0);
        }
    }
}
```

## What did you intend to be?
Improve instantiation performance.

**Comment by Tam66662** [comment]
I too am facing this problem with x64 and same environment as OP.  Are there any workarounds to improving the performance, such as setting a BufferSize during initialization and whatnot?
