### ISSUE TITLE
Variance of Laplacian

### ISSUE THREAD

**Issue by turowicz** [shimat/opencvsharp#642]
I'm trying to achieve the following blur detection:

https://www.pyimagesearch.com/2015/09/07/blur-detection-with-opencv/

Unfortunately I can't find the `.var()` method on current `Mat` in OpenCvSharp.

Do we have anything to achieve that?

cc @shimat

**Comment by shimat** [comment]
You can get standard deviation by Cv2.MeanStdDev(). You just need to square the standard deviation result (variance = stddev * stddev).
