### ISSUE TITLE
Timeframe for an 4.0.1 release

### ISSUE THREAD

**Issue by jensrodi** [shimat/opencvsharp#647]
Hi,

A question: What is the timeframe for the next release, that includes changes made in OpenCV 4.0.1?

I ask because I have an issue using the current release on certain Windows 7 installation. This is due to an unnecessary dependency in OpenCV which causes OpenCvSharpExtern to fail loading. I cannot change this dependency on the target system. 

I know you'll probably suggest to build a version myself. Unfortunately, though I can easily build OpenCvSharpExtern (and OpenCvSharp for that matter), I have not been able to find updated lib files for OpenCV 4.0.1 nor have the expertise to get the lib files build from sources. 

I considered downgrading to 3.4.1 (which apparently wouldn't have this issue) but am using functionality specific to the 4.0 release.

Alternately, if someone could provide the appropriate x86 and x64 lib files as used in OpenCvSharpExtern that would be greatly appreciated.

**Comment by hez2010** [comment]
I have the same problem and wait for OpenCvSharp 4.0.1 too.

**Comment by shimat** [comment]
https://www.nuget.org/packages/OpenCvSharp4/4.0.1.20190326
