### ISSUE TITLE
Forum?

### ISSUE THREAD

**Issue by tbreina** [shimat/opencvsharp#65]
Is there a forum for working with OpenCVSharp?  

I've gotten much of it working with Unity, but am still having some issues with implementing CamShift. I was hoping to submit my question to an OpenCVSharp-specific forum.

Also, in Unity, when I don't declare my IplImage as a static class, then I get this runtime warning:
"The same field name is serialized multiple times in the class iplImage". This might be a Unity issue, but wanted to see if anyone had run across it with OpenCVSharp.

**Comment by RohiniKamaraj** [comment]
Hello all!

Well,i am working on image processing. I tried the houghlines code using opencvsharp.In that, i need to read a dicom image. But iplimage doesnt support that format.
is there any other solution for this?
could anyone have idea ??
Please guide me!!!
