### ISSUE TITLE
CvDnn.BlobFromImage Method is alway return a Mat rows and cols is -1.

### ISSUE THREAD

**Issue by chinapsu** [shimat/opencvsharp#651]
# Summary of your issue
      My CvDnn.BlobFromImage Method is alway return a Mat rows and cols is -1.
# Environment

Write your environment.

Windows10
OpencvSharp4.0.0.20181129 

//write here

## Example code:

```
        static (Mat frameOpenCVDNN, List<int[]> bbox) getFaceBox(Net net, Mat frame, double conf_threshold)
        {

            Mat frameOpenCVDNN = frame.Clone();
            int frameHeight = frameOpenCVDNN.Rows;
            int frameWidth = frameOpenCVDNN.Cols;
            double inScaleFactor = 1.0;
            Size size = new Size(300, 300);
            // std::vector<int> meanVal = {104, 117, 123};
            Scalar meanVal = new Scalar(104, 117, 123);

            Mat inputBlob;
            inputBlob = CvDnn.BlobFromImage(frameOpenCVDNN, inScaleFactor, size, meanVal);
 
    }
}
```

**Comment by chinapsu** [comment]
Source Image is success loaded. but CvDnn.BlobFromImage is alway return a mat with cols = -1 and rows =-1

**Comment by adstep** [comment]
Hey @chinapsu, did you happen to figure out what was going wrong? I'm hitting the same issue.

**Comment by timstokman** [comment]
If anyone else encounters this.. the answer is the if rows=-1 and columns=-1 then the Mat is a matrix with dimension bigger than two. You can get the amount of dimensions with the .Dims property. You can get the matrix shape with .Size(0), .Size(1), ... .Size(whateverDim).
