### ISSUE TITLE
AccessViolationException during facial landmark detection

### ISSUE THREAD

**Issue by FFMB2018** [shimat/opencvsharp#653]
# Summary of your issue
An AccessViolationException is thrown when trying to perform a facial landmark detection with OpenCVSharp. The exception is thrown when the facemark.Fit() method is called.

The original discussion is at https://github.com/shimat/opencvsharp/issues/467 , but the bug there was closed with the hint to open a new one. The original bug report also contains the comments and tests of other users with useful additional information.

# Environment
OpenCVSharp v3.4.4 (official build)
Visual Studio 2017 (latest version)
Windows 10 (latest version)

## Example code:

```
CascadeClassifier classifier = new CascadeClassifier(@"haarcascade_frontalface_alt2.xml");

Mat input = MatHelper.ToMat(source);

Mat gray = new Mat();
Cv2.CvtColor(input, gray, ColorConversionCodes.BGR2GRAY);

Rect[] facesRects = classifier.DetectMultiScale(gray);
InputArray facesArray = InputArray.Create<Rect>(facesRects);

Facemark facemark = FacemarkLBF.Create();
facemark.LoadModel(@"d:\lbfmodel.yaml");

Mat landmarks = new Mat();
facemark.Fit(input, facesArray, landmarks);     // <-- AccessViolationException
```

## Output:

An AccessViolationException is thrown instead of getting the detected landmarks.

**Comment by whudee** [comment]
I also encountered the same problem and hope to get answers.
how to use `facemark.Fit` is correct?

**Comment by CobraCalle** [comment]
I have currently the same Problem.... but I do not get an AccessViolation, but I get the following error instead (when using Mat type of landmarks parameter):

"Only Mat vector, UMat vector, and vector<vector> OutputArrays are currently supported."

So what is the correct  type for landmarks? As far as I can see, InputOutputArray can only be created by casting from Mat... is that correct?

**Comment by ZYT5ting** [comment]
I got the same problem when I use the facemark.Fit function: "Only Mat vector, UMat vector, and vector OutputArrays are currently supported."Can anyone provide the solutions？Thank you a lot!
