### ISSUE TITLE
TensorFlow test

### ISSUE THREAD

**Issue by turowicz** [shimat/opencvsharp#654]
I see that Caffe and YOLO have unit tests that describe how to go about using the external networks. I would like to load up my custom TensorFlow model and it would be good to have a working example in the tests.

**Comment by turowicz** [comment]
cc @shimat

**Comment by died** [comment]
@turowicz I checked opencvsharp's [test](https://github.com/shimat/opencvsharp/tree/master/test/OpenCvSharp.Tests/dnn), didn't find test for tensorflow, maybe you can try find it form [opencv](https://github.com/opencv/opencv). I don't know opencv dnn support it or not :P
