### ISSUE TITLE
src.size == dst.size && src.type（）== dst.type（）&& src.isContinuous（）&& dst.isContinuous（）&& src.type（）== CV_32F

### ISSUE THREAD

**Issue by laolaolulu** [shimat/opencvsharp#657]
CvDnn.BlobFromImage（image，1，new OpenCvSharp.Size（800,600））报告错误

CvDnn.BlobFromImage（图片，1，新的OpenCvSharp.Size（800,500））没问题
![TIM截图20190325174407](https://user-images.githubusercontent.com/33310261/54914006-fe986180-4f2e-11e9-8590-22b9cb6b3f17.png)

**Comment by hez2010** [comment]
Assert fault: src.size == dst.size
size of the source image should be equal to the size of destination.

**Comment by laolaolulu** [comment]
scr is image?  dst is blob?

**Comment by Naked-Hidden** [comment]
你倒是把错误贴上来啊，这谁看的明白。
