### ISSUE TITLE
Issue with getting data from Mat

### ISSUE THREAD

**Issue by pcdeadeasy** [shimat/opencvsharp#660]
Unable to get the bytes from a Mat

Running on Windows 10
 byte[] yuvBuffer = File.ReadAllBytes(@"F:\tulips_yuv420_inter_planar_qcif.yuv");            
Mat src = new Mat(height, width, MatType.CV_8UC1, yuvBuffer);   

  Cv2.CvtColor(src, dest, ColorConversionCodes.YUV2RGBA_I420);
  Cv2.ImWrite(@"F:\newImage.jpg", dest);

The above write a good image file. But I want to have a way to parse the data in dest.
 int length = dest.Width * dest.Height * dest.Channels(); // or src.Height * src.Step;
 byte[] rgbBuffer = new byte[length];
Marshal.Copy(rgbBuffer, 0, dest.Data, length);

I don't end up with the right bytes in rgbBuffer

**Comment by ravazquez** [comment]
Have you tried using ImDecode instead of Marshal.Copy?

**Comment by pcdeadeasy** [comment]
I actually have a YUV frame and use the code below to convert the YUV frame to RGB:

byte[] yuvBuffer = File.ReadAllBytes(@"F:\test.yuv");            
            Mat src = new Mat(height, width, MatType.CV_8UC1, yuvBuffer);            
           
            Mat dest = new Mat(new OpenCvSharp.Size(width, height), MatType.CV_8UC4);
            Cv2.CvtColor(src, dest, ColorConversionCodes.YUV2RGBA_I420);
//            Cv2.ImWrite(@"F:\projects\sensei-testprojects\newImage.jpg", dest);

So I was hoping to get to the raw bytes of the image

**Comment by ravazquez** [comment]
If what you need is an array of bytes, try ImEncode
