### ISSUE TITLE
Does opencvsharp4 VideoCapture class can read a rtsp stream on a centos 7 system?

### ISSUE THREAD

**Issue by aisok** [shimat/opencvsharp#661]
# Summary of your issue
I am using opencvsharp4\4.0.1.20190326 and opencvsharp4.runtime.centos7-x64\4.0.0.20190129 in my a .netcore(Microsoft.NETCore.App2.1) console application.when I deploy the project to Centos 7,the app is run ,but the  VideoCapture can not Open a rtsp stream.But there is no exception throw by the code.

# Environment
Centos 7 X64

# What did you do when you faced the problem?

## Example code:

```
 var capture = new VideoCapture(this.ImageSource);
            int sleepTime = (int)Math.Round(1000 / capture.Fps);
            // Frame image buffer
            using (Mat image = new Mat())
            {
                capture.Open(this.ImageSource);
                Console.WriteLine("capture.Mode is "+capture.Mode + ", DateTime.Now is " + DateTime.Now);
                Console.WriteLine("capture.CaptureType is " + capture.CaptureType + ", DateTime.Now is " + DateTime.Now);
                Console.WriteLine("capture.Fps is " + capture.Fps + ", DateTime.Now is " + DateTime.Now);
                Console.WriteLine("capture.GStreamerQueueLength is " + capture.GStreamerQueueLength + ", DateTime.Now is " + DateTime.Now);
                while (true)
                {
                    if (! capture.IsOpened())
                        {
                        Console.WriteLine(this.ImageSource + " read image not opened , DateTime.Now is " + DateTime.Now);
                        break;
                    }
                    Console.WriteLine(this.ImageSource + " read image , DateTime.Now is " + DateTime.Now);
                    capture.Read(image); // same as cvQueryFrame
                    if (image.Empty())
                    {
                        Console.WriteLine(this.Id + " read image is Empty , DateTime.Now is " + DateTime.Now);
                        break;
                    }
  
                    this.OrginalImage = image;
                    var v = this.CurrentValue;
                    Console.WriteLine(this.Id + " value is " + v + " DateTime.Now is " + DateTime.Now);
                }
                Console.WriteLine(this.ImageSource + " read image break , DateTime.Now is " + DateTime.Now);

            }
```

## Output:

capture.Mode is 0, DateTime.Now is 19-4-9 下午5:51:05
capture.CaptureType is File, DateTime.Now is 19-4-9 下午5:51:05
capture.Fps is 0, DateTime.Now is 19-4-9 下午5:51:05
capture.GStreamerQueueLength is 0, DateTime.Now is 19-4-9 下午5:51:05
rtsp://admin:123456@219.141.184.189:554/cam/realmonitor?channel=1&subtype=1 read image not opened , DateTime.Now is 19-4-9 下午5:51:05
rtsp://admin:123456@219.141.184.189:554/cam/realmonitor?channel=1&subtype=1 read image break , DateTime.Now is 19-4-9 下午5:51:05
## What did you intend to be?
Why I can't get the image by "capture.Read(image); "?the image object is Empty.

**Comment by hez2010** [comment]
You need to invoke `capture.Grab();` first before reading an image.
