### ISSUE TITLE
OpenCvSharp4.runtime.win fallback to .NETFramework in .NETCore apps

### ISSUE THREAD

**Issue by sadqiang** [shimat/opencvsharp#663]
I got the following warning. 
The code successfully runs  on my Windows 10 (x64) machine.
But is it fine  to ignore this warning?

> warning NU1701: Package 'OpenCvSharp4.runtime.win 4.0.1.20190326' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

## Example code:

```
// Edge detection by Canny algorithm
using OpenCvSharp;

class Program
{
    static void Main()
    {
        Mat src = new Mat("test.jpg", ImreadModes.Color);
        Mat dst = new Mat();

        Cv2.Canny(src, dst, 50, 200);
        using (new Window("src image", src))
        using (new Window("dst image", dst))
        {
            Cv2.WaitKey();
        }
    }
}
```

**Comment by iXyles** [comment]
Any updates regarding full support for .Net Core 2.2+ ?

**Comment by isaacwalkercox** [comment]
Yeah I am getting the same warning. It's interfering with using this library in one of my projects.

**Comment by sadqiang** [comment]
この警告を無視してもいいですか？

**Comment by Andy1221** [comment]
This issue is affecting me as well.
Any updates on supporting .NET Core with windows runtimes?
