### ISSUE TITLE
CPU optimization build?

### ISSUE THREAD

**Issue by utarn** [shimat/opencvsharp#666]
# Summary of your issue
I found that the OpenCV can be built with CPU optimization. https://github.com/opencv/opencv/wiki/CPU-optimizations-build-options

# Environment
Intel recent generation or AMD Ryzen

## What did you intend to be?
Is the release built with CPU DISPATCH optimization? If not, could you please guide me how to build with cpu optimization?

**Comment by hez2010** [comment]
opencvsharp is only a wrapper of OpenCV, you can build OpenCV by yourself and specify the cmake flags you need while building your OpenCV.

**Comment by hez2010** [comment]
opencvsharp is only a wrapper for OpenCV, you can build your own OpenCV (including opencv_contrib) from https://github.com/opencv/opencv and https://github.com/opencv/opencv_contrib with CMake flags you need.

**Comment by shimat** [comment]
My Cmake variables are:  https://github.com/shimat/opencv_files_410/blob/master/CMakeVars_x64.txt
The CPU DISPATCH flag values are unchanged from the default.

**Comment by utarn** [comment]
Thank you. The build uses upto SSE4.2 and AVX which makes use of both ryzen and intel latest generation.
