### ISSUE TITLE
Running error reporting under Linux arm32 system

### ISSUE THREAD

**Issue by whuanle** [shimat/opencvsharp#667]
root@myd-y6ull14x14:/mnt/usb/opencv/testconsole# dotnet OpencvTest.dll
Error:
  An assembly specified in the application dependencies manifest (OpencvTest.deps.json) was not found:
    package: 'Microsoft.Win32.SystemEvents', version: '4.5.0'
    path: 'lib/netstandard2.0/Microsoft.Win32.SystemEvents.dll'
file list:
![image](https://user-images.githubusercontent.com/2189761/56945116-8427b680-6b58-11e9-8468-776944596e85.png)

**Comment by whuanle** [comment]
Find the reason...
installed opencvsharp4,then...
Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke()

Unhandled Exception: OpenCvSharp.OpenCvSharpException: Failed to create VideoCapture ---> System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke() ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke()
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.TryPInvoke()
   at OpenCvSharp.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.videoio_VideoCapture_new3(Int32 device)
   at OpenCvSharp.VideoCapture..ctor(Int32 index)
   --- End of inner exception stack trace ---
   at OpenCvSharp.VideoCapture..ctor(Int32 index)
   at OpencvTest.CaptureService.DoSomeThing(Nullable`1 startTime, Int64 count) in H:\OpenCv\OpencvTest\Program.cs:line 21
   at OpencvTest.Program.Main(String[] args) in H:\OpenCv\OpencvTest\Program.cs:line 11
Aborted

**Comment by hez2010** [comment]
You need to build and install OpenCV 4.1.0, then build and install opencvsharp as following:

```bash
wget https://github.com/shimat/opencvsharp/archive/4.1.0.20190417.zip -Oopencvsharp-4.1.0.20190417.zip
unzip opencvsharp-4.1.0.20190417.zip
cd opencvsharp-4.1.0.20190417/src
mkdir build && cd build
cmake ..
make -j8
sudo make install
sudo ldconfig
```

**Comment by whuanle** [comment]
> You need to build and install OpenCV 4.1.0, then build and install opencvsharp as following:
> 
> ```shell
> wget https://github.com/shimat/opencvsharp/archive/4.1.0.20190417.zip -Oopencvsharp-4.1.0.20190417.zip
> unzip opencvsharp-4.1.0.20190417.zip
> cd opencvsharp-4.1.0.20190417/src
> mkdir build && cd build
> cmake ..
> make -j8
> sudo make install
> sudo ldconfig
> ```

compilation terminated.
OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/build.make:62: recipe for target 'OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/aruco.cpp.o' failed
make[2]: *** [OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/aruco.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/all' failed
make[1]: *** [OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
![Uploading image.png…]()

**Comment by hez2010** [comment]
You don't have opencv with opencv_contrib 4.1.0 installed on your device. Please install them first.
You can install them as followings:
```bash
sudo apt update
sudo apt -y install build-essential checkinstall cmake pkg-config yasm
sudo apt -y install git gfortran
sudo apt -y install libjpeg8-dev libjpeg-dev libpng-dev
sudo apt -y install libjasper1
sudo apt -y install libtiff-dev
sudo apt -y install libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev
sudo apt -y install libxine2-dev libv4l-dev
sudo apt -y install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
sudo apt -y install libgtk2.0-dev libtbb-dev qt5-default
sudo apt -y install libatlas-base-dev
sudo apt -y install libfaac-dev libmp3lame-dev libtheora-dev
sudo apt -y install libvorbis-dev libxvidcore-dev
sudo apt -y install libopencore-amrnb-dev libopencore-amrwb-dev
sudo apt -y install libavresample-dev
sudo apt -y install x264 v4l-utils
sudo apt -y install libprotobuf-dev protobuf-compiler
sudo apt -y install libgoogle-glog-dev libgflags-dev
sudo apt -y install libgphoto2-dev libeigen3-dev libhdf5-dev doxygen
sudo apt -y install libtbb2 libjasper-dev libdc1394-22-dev

wget https://github.com/opencv/opencv/archive/4.1.0.zip -Oopencv-4.1.0.zip
unzip opencv-4.1.0.zip
wget https://github.com/opencv/opencv_contrib/archive/4.1.0.zip -Oopencv_contrib-4.1.0.zip
unzip opencv_contrib-4.1.0.zip

cd opencv-4.1.0
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.0/modules # you might want to specify other CMake flags through -Dflag=value
sudo make install -j8
sudo ldconfig

```

Then you can build opencvsharp successfully.

**Comment by SpontaneousDuck** [comment]
This fixed the issue for me! Thanks @hez2010 !

**Comment by thylxl** [comment]
I had a problem similar to   I at sudo make install
Consolidate compiler generated dependencies of target libwebp
[  5%] Built target libwebp
Consolidate compiler generated dependencies of target libjasper
[  7%] Built target libjasper
Consolidate compiler generated dependencies of target libprotobuf
[ 10%] Built target libprotobuf
Consolidate compiler generated dependencies of target quirc
[ 10%] Built target quirc
[ 10%] Building CXX object 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/absdiff.cpp.o
c++: error: unrecognized command-line option '--param=ipcp-unit-growth=100000'; did you mean '--param=ipa-cp-unit-growth='?
make[2]: *** [3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/build.make:76: 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/absdiff.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3560: 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
