### ISSUE TITLE
Unhelpful message 'All the input and output images must have the same size'

### ISSUE THREAD

**Issue by jakingmsft** [shimat/opencvsharp#669]
I understand from [the documentation](https://docs.opencv.org/2.4/modules/photo/doc/inpainting.html) that `src` and `dst` objects must have the same dimensions. You can see in the Watch window of the attatched image that my objects _**do**_ have the same dimensions. Yet I will get 

> OpenCvSharp.OpenCVException: 'All the input and output images must have the same size'

which preseumably is referring to those objects.

![open_cv_bug](https://user-images.githubusercontent.com/42750359/57238059-5ec5fd00-6fdd-11e9-9bfd-81d13f2144de.JPG)

**Comment by shimat** [comment]
Does the `ImageToByte2` convert Mat to byte[]? 

You do not have to create an InputArray/OutputArray explicitly.
```c#
var src = Mat.FromImageData(byteArray);
var dst = new Mat(src.Rows, src.Cols. MatType.CV_32SC3);
Cv2.Inpaint(src, mask, dst, ...);
```
