### ISSUE TITLE
Hi,how to dispose ConnectedComponents

### ISSUE THREAD

**Issue by nieshaoju** [shimat/opencvsharp#678]
# Summary of your issue
I put the code "ConnectedComponents cc = Cv2.ConnectedComponentsEx(Mymat);" in a Task and loop it,  the memory will increase with time,then, my app die。
# Environment
win 10(x64) + opecvsharp4.0.0

![shimat](https://user-images.githubusercontent.com/30792256/57611956-83564200-75a6-11e9-97f4-dd8ce43d82cc.png)

**Comment by shimat** [comment]
You have to dispose a return Mat value of `bin.Threshold()`. 

```c#

using (Mat bin = src.Threshold(...))
{
```
```c#
// alternative
using (Mat bin = new Mat())
{
    Cv2.Threshold(src, bin, ...);
    ...
```

**Comment by Naked-Hidden** [comment]
I tried it, but it didn't work.
![shimat2](https://user-images.githubusercontent.com/30792256/57663703-a543d900-7627-11e9-91fe-c96ea364f8f1.png)

**Comment by shimat** [comment]
What happens if you comment out the RenderBlobs call?

**Comment by Naked-Hidden** [comment]
still,
![shimat3](https://user-images.githubusercontent.com/30792256/57664819-2c934b80-762c-11e9-9a67-a84cf9bfd40d.png)

**Comment by Naked-Hidden** [comment]
the problem is in "ConnectedComponents cc = Cv2.ConnectedComponentsEx(bin);"
![shimat4](https://user-images.githubusercontent.com/30792256/57667956-2e630c00-7638-11e9-84e6-8454314e1b81.png)

**Comment by shimat** [comment]
:weary: 

Is the input image large?

ConnectedComponentsEx reserves a large memory space. An OutOfMemoryException may occur if the input image is large and your memory is low or fragmented.

An OutOfMemoryException is evidence of a memory allocation failure in code written in C#, not C++.
https://github.com/shimat/opencvsharp/blob/b5ce5d6ddfaceaf5d926fa2614c5f62d3e45b7c6/src/OpenCvSharp/Cv2/Cv2_imgproc.cs#L2540

**Comment by Naked-Hidden** [comment]
i used this img,[http://cdn-ak.f.st-hatena.com/images/fotolife/S/Schima/20150819/20150819211605.png](url),but nothing changes😭。。
![bt](https://user-images.githubusercontent.com/30792256/57669464-a7b12d80-763d-11e9-947b-83dc20bb147d.png)
