### ISSUE TITLE
Using OCRTesseract

### ISSUE THREAD

**Issue by DiomedesDominguez** [shimat/opencvsharp#679]
Does anyone has a working code of OCRTesseract class?

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp/blob/a0d61065240eada9706fb2df2bf7ea5ce8f599d7/test/OpenCvSharp.Tests/text/OCRTesseractTest.cs#L31

**Comment by DiomedesDominguez** [comment]
Thanks. Please add a comment/wiki saying that "TessData" can be gather from https://github.com/tesseract-ocr/tessdata_best. I lost almost two hours to understood that.

**Comment by shimat** [comment]
I only create wrappers, so I don't support the details of Tessdata (I can't be sure that the Tessdata on the site you indicated is really valid to work for a little old Tesseract(3.0.5) ).

It is common knowledge that Tessdata is required for Tesseract to work and is distributed from the official site. You should use this OCRTesseract class knowing the raw Tesseract specification.
