### ISSUE TITLE
Cv2.PointPolygonTest crahes in x64

### ISSUE THREAD

**Issue by OLEGator86** [shimat/opencvsharp#68]
I'm using opencvsharp version 2.4.10 x64 and OpenCV 2.4.10 x64.
This code crashes in Windows 7 x64:

<pre>
<code>Cv2.PointPolygonTest(new [] {new Point2f(0, 0), new Point2f(0, 10), new Point2f(10, 10), new Point2f(10, 0) }, new Point2f(5, 5), false);</code>
</pre>

Could you please fix this?

**Comment by shimat** [comment]
Sorry for my late action. This is fixed: https://github.com/shimat/opencvsharp/commit/bf85296a01004dd80ea333d588a0f1588bf5450b
