### ISSUE TITLE
how to use SetMouseCallback?  question

### ISSUE THREAD

**Issue by kimkanghyune** [shimat/opencvsharp#681]
I'm sorry I did not speak English smoothly.

# Summary of your issue
I do not know how to use SetMouseCallback changed in OpenCVSharp 4.1.

# Environment

Visual Studio 2019 OpenCVSharp 4.1

# What did you do when you faced the problem?

Code Write and this repos search
## Example code:
void mc(MouseEvent evt, int x, int y, MouseEvent evt2);
MouseEvent evt = MouseEvent.LButtonDown;
            int x = 0;
            int y = 0;
            MouseEvent evt2 = MouseEvent.LButtonUp;
            foo.SetMouseCallback(new CvMouseCallback(mc(evt, x, y, evt2)));
            Debug.WriteLine(Cv2.WaitKey());
public void mc(MouseEvent evt, int x, int y, MouseEvent evt2)
        {
        }
## Output:
심각도	코드	설명	프로젝트	파일	줄	비표시 오류(Suppression) 상태
오류	CS0501	'GUI.mc(MouseEvent, int, int, MouseEvent)'은(는) abstract, extern 또는 partial로 표시되어 있지 않으므로 본문을 선언해야 합니다.	Tracking_Object	C:\Users\vip\Source\Repos\tracking_object\Tracking_Object\1. Matrix structure\1.1 GUI\GUI.cs	13	활성
심각도	코드	설명	프로젝트	파일	줄	비표시 오류(Suppression) 상태
오류	CS0111	GUI' 형식은 동일한 매개 변수 형식을 가진 'mc' 멤버를 미리 정의합니다.	Tracking_Object	C:\Users\vip\Source\Repos\tracking_object\Tracking_Object\1. Matrix structure\1.1 GUI\GUI.cs	31	활성
심각도	코드	설명	프로젝트	파일	줄	비표시 오류(Suppression) 상태
오류	CS0121	GUI.mc(MouseEvent, int, int, MouseEvent)' 및 'GUI.mc(MouseEvent, int, int, MouseEvent)'의 메서드 또는 속성 간 호출이 모호합니다.	Tracking_Object	C:\Users\vip\Source\Repos\tracking_object\Tracking_Object\1. Matrix structure\1.1 GUI\GUI.cs	28	활성

## What did you intend to be?

I wanted to write a function that returns the X, Y coordinates when I click the mouse on the window.

**Comment by shimat** [comment]
I'm sorry for the late reply. Thank you for submitting the pull request. https://github.com/shimat/opencvsharp_samples/pull/16
