### ISSUE TITLE
Failed to allocate 921600 bytes

### ISSUE THREAD

**Issue by HanJunJun** [shimat/opencvsharp#683]
Opencvsharp calls a bug in the net core
Error:Failed to allocate 921600 bytes

`
Mat mat = new Mat();
_videoCapture.Read(mat)
`
This code will grow infinitely memory

**Comment by shimat** [comment]
Please see https://github.com/shimat/opencvsharp/issues/540 / https://github.com/shimat/opencvsharp/issues/559

**Comment by lisishen** [comment]
use gc.collect(); System will restore the memory automatically.
