### ISSUE TITLE
Opencvsharp doesnt support reading from stream when stream contains additional data

### ISSUE THREAD

**Issue by grisharav** [shimat/opencvsharp#684]
# Summary of your issue

When I try to decode an image from a stream which contains additional custom data, the library fails.
This probably happens due to custom manipulation of the input stream in `Mat.FromStream(...)` method
Is there a way to read encoded data from a stream which consumes only the relevant data from it?

# Environment

Windows 10

# What did you do when you faced the problem?

## Example code:

```
        [Fact]
        public void TestStreamWritingOpencvsharp()
        {
            var m = new Mat(new Size(87, 92), MatType.CV_8UC1);
            m.Randn(Scalar.RandomColor(), new Scalar(7));
            using (var stream = new MemoryStream())
            {
                stream.Write(new byte[] { 1, 2, 3, 4 });
                m.WriteToStream(stream);
                stream.Position = 4;
                var m2 = Mat.FromStream(stream, ImreadModes.Unchanged);
                Assert.Equal(m.Size(), m2.Size());
            }
        }
```

## Output:

Assert fails

## What did you intend to be?

Assert passes

**Comment by shimat** [comment]
Thank you. This problem was fixed by https://github.com/shimat/opencvsharp/pull/758/files#diff-66d4dcc960dbc1c3a376bd8f67e11701R658
