### ISSUE TITLE
UseInitialFlow does not work with CalcOpticalFlowPyrLK 

### ISSUE THREAD

**Issue by mv3shape** [shimat/opencvsharp#686]
# Summary of your issue
CalcOpticalFlowPyrLK has the flag UseInitialFlow which signals that it should use the values in nextPts as initial estimations. This does not work with overload of CalcOpticalFlowPyrLK that takes C# array arguments in opencvsharp because it always passes an empty point set to OpenCV as nextPts .

# Environment
Windows

# What did you do when you faced the problem?
Looked at opencvsharp source code.

## Example code:
            Cv2.CalcOpticalFlowPyrLK(prevImage, Image,
                prevFeatures, ref nextFeatures, out byte[] status, out float[] err,
                new Size(21, 21), maxLevel: 3, new TermCriteria(CriteriaType.Eps, 30, 1e-4),
                OpticalFlowFlags.UseInitialFlow, minEigThreshold: 1e-4);

## Output:
"OpenCvSharp.OpenCVException: nextPtsMat.checkVector(2, CV_32F, true) == npoints" exception

## What did you intend to be?
tracked points

**Comment by marcojoao** [comment]
I got the same problem here, and if I remove the opticalflow flag it craches.

here is my test code:
```
using AromniTrackers.Core.ImageProviders;
using AromniTrackers.Utils;
using OpenCvSharp;
using UnityEngine;

public class mainScript : MonoBehaviour
{
    private ImageProvider imageProvider;

    //Initializer
    private void Start()
    {
        imageProvider = FindObjectOfType<ImageProvider>();
    }

    private Point2f[] prevFeatures;
    private Point2f[] nextFeatures;

    private InputArray prvPyr, nextPyr;
    private Mat[] prevPyramid, nextPyramid;

    private readonly int pyrLevels = 3;
    private readonly Size winSize = new Size(5, 5);
    private readonly Mat grayMat = new Mat();
    private readonly TermCriteria criteria = new TermCriteria(CriteriaType.Count | CriteriaType.Eps, 30, 0.01);

    //Main Loop
    private void Update()
    {
        var originalMat = imageProvider.GetImage();
        if (originalMat == null || originalMat.Empty()) return;
        Cv2.CvtColor(originalMat, grayMat,ColorConversionCodes.BGR2GRAY);

        if (prevFeatures == null)
        {
            prevFeatures = Cv2.GoodFeaturesToTrack(grayMat, 200, 0.1f, 5, null, 4, true, .04);
            Cv2.BuildOpticalFlowPyramid(grayMat, out prevPyramid,winSize, pyrLevels);
            return;
        }

        if(nextFeatures == null)
            nextFeatures = new Point2f[prevFeatures.Length];

        Cv2.BuildOpticalFlowPyramid(grayMat, out nextPyramid, winSize, pyrLevels);

        nextPyr = InputArray.Create(nextPyramid);
        prvPyr = InputArray.Create(prevPyramid);

     
        Cv2.CalcOpticalFlowPyrLK(prvPyr,nextPyr
            ,prevFeatures, ref nextFeatures, out _, out _
            ,winSize,pyrLevels,criteria,OpticalFlowFlags.UseInitialFlow);
   
        Cv2.Flip(originalMat,originalMat,FlipMode.X);
        Cv2.CvtColor(originalMat,originalMat,ColorConversionCodes.GRAY2RGB);
        DrawUtils.DrawPoints(originalMat,prevFeatures,Scalar.Red);
        Cv2.ImShow("Test",originalMat);

        ARUtils.SwapArray(ref nextPyramid, ref prevPyramid);
        ARUtils.SwapArray(ref nextFeatures, ref prevFeatures);
    }
}
```

**Comment by marcojoao** [comment]
Fixed, in method CalcOpticalFlowPyrLK change  from `

> var nextPtsVec = new VectorOfPoint2f(); 

`to  

> var nextPtsVec = new VectorOfPoint2f(nextPts); 

and grant that nextPts != null && nextPts.Length > 0 by copy the prevPts to nextPts

**Comment by shimat** [comment]
Thanks!
