### ISSUE TITLE
Why BitmapSourceConverter.ToMat swap R and B channels?

### ISSUE THREAD

**Issue by hjy1210** [shimat/opencvsharp#687]
# Summary of your issue
Use Mat mat=BitmapSourceConverter.ToMat(src) to convert src(BitmapSource) to mat.
I got mat with R and B channels swapped.
# Environment
Windows 10,
OpenCvSharp4.Windows 4.1.0.20190416
Visual Studio 2019

# What did you do when you faced the problem?
Add following code to swap channels：

Mat mat2=new Mat();
Cv2.CvtColor(mat, mat2, ColorConversionCodes.BGR2RGB);

## Example code:

```
		public static void DisplayBitmapSource(BitmapSource src)
		{
			Mat mat = BitmapSourceConverter.ToMat(src);
			Mat mat2 = new Mat();
			Cv2.CvtColor(mat, mat2, ColorConversionCodes.BGR2RGB);
			using (new Window("mat2", mat2))
			{
				Cv2.WaitKey(10);
			}
		}

```

## Output:

```
paste your output
```

## What did you intend to be?
I just need convert BitmapSource to Mat.

**Comment by hez2010** [comment]
That's what ColorConversionCodes.BGR2RGB designed. BGR2RGB -- BGR to RGB
