### ISSUE TITLE
Failed to allocate 58982400 bytes

### ISSUE THREAD

**Issue by lisishen** [shimat/opencvsharp#691]
# Summary of your issue
I had used mat.dispose() to dispose the memory, but i finded it did not work, so error occured finally.
# Environment
Win7,VS2010,OpenCvSharp-4.1.0-x86-20190417

# What did you do when you faced the problem?

//I finded that the memory can no be disposed at Example1, but work at Example2.
I finded the memory in Task Manager, it changed as follow as bellow.
Example1:
loca1:306,284K
loca2:364,432K
loca3:422,158K
loca4:422,148K
loca5:422,148K
loca6:595,272K
loca7:595,272K
loca8:595,272K
Example2:
loca1:305,440K
loca2:363,756K
loca3:421,473K
loca4:421,473K
loca5:363,760K
loca6:306,040K
I don not know why dispose() can not work in Example1.

## Example code:
Example1:
                                                                             \\loca1
            Cv2.GaussianBlur(I1, mu1,opSize, 1.5);    \\loca2
            Cv2.GaussianBlur(I2, mu2, opSize, 1.5);   \\loca3
            I1.Dispose();                                             \\loca4
            I2.Dispose();                                             \\loca5
            Mat mu1_2 = mu1.Mul(mu1);
            Mat mu2_2 = mu2.Mul(mu2);
            Mat mu1_mu2 = mu1.Mul(mu2);            \\loca6
            mu1.Dispose();                                        \\loca7
            mu2.Dispose();                                        \\loca8
Example2:
                                                                             \\loca1
            Cv2.GaussianBlur(I1, mu1,opSize, 1.5);    \\loca2
            Cv2.GaussianBlur(I2, mu2, opSize, 1.5);   \\loca3
            I1.Dispose();                                             
            I2.Dispose();                                             \\loca4
            mu1.Dispose();                                        \\loca5
            mu2.Dispose();                                        \\loca6

## What did you intend to be?
The memory can be disposed in Example1.

**Comment by lisishen** [comment]
use GC.collect(); System will restore the memory automatically .

**Comment by AbdelsalamHaa** [comment]
@lisishen thanks for ur answer it helped me a lot. I would like to ask is there any side effect in using this function for the PC or for the memory in general ?
