### ISSUE TITLE
OpenCVSharp3-AnyCPU GPU support

### ISSUE THREAD

**Issue by davidprosek** [shimat/opencvsharp#693]
Please help, 
I've installed OpencvSharp from nuget, after build there is opencv_ffmpeg400_64.dll and OpenCvSharpExtern.dll in dll folder. 
I' have build opencv libraray 4.1 with cuda support, there are this dlls in build output
opencv_calib3d410.dll
opencv_core410.dll
opencv_cudev410.dll
opencv_dnn410.dll
opencv_features2d410.dll
opencv_flann410.dll
opencv_highgui410.dll
opencv_imgcodecs410.dll
opencv_imgproc410.dll
opencv_ml410.dll
opencv_objdetect410.dll
opencv_photo410.pdb
opencv_stitching410.dll
opencv_video410.dll
opencv_videoio410.dll
opencv_world410.dll

I'm using visual studio 2019 on windows, 
OpenCVSharp-ANY cpu version 4.0.0.20181129 , 
OpenCV 4.1
CUDA 10.1

Can anyone tell me , how i can get CUDA support into OpencvSharp in this versions.

Thank you

**Comment by hez2010** [comment]
Cuda module on opencvsharp hasn't been updated for a long while and it has lost its functionality, therefore it has been removed from opencvsharp.  
Maybe it's possible to use opencvsharp with cuda in future release.
