### ISSUE TITLE
Publish only one architecture specific runtime

### ISSUE THREAD

**Issue by valeriob** [shimat/opencvsharp#697]
Hi,
do you think it's possible to package the library so that only a specific native implementation gets published (for example between x86 and x64, so we can remove a good 50mb from each built artifact) ?
Would it be possible to follow this guidelines ? 
https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders

Thanks!

**Comment by WalkerCodeRanger** [comment]
(I'm not a contributor, just a user.) If you look in the nupkg file, it follows exactly that folder structure. I believe it is following the recommended practice which is to include both runtimes in one package.

**Comment by valeriob** [comment]
Sorry my bad than, i was asking because when i publish a netcore 3.0 application with rid win-x64 the output folder contains those 2 files in the root (opencv_ffmpeg410.dll and OpenCvSharpExtern.dll) and also two subfolder (x86 and x64) that contains the same files, so basically there are 3 copies of the same files (two copy for x64 and one for x86).

**Comment by valeriob** [comment]
I do not think that that #752 worked : 
I have a project with OpenCvSharp4.Windows 4.1.1.20191110.
If i run dotnet publish -r win-x64, my publish folder still contains : 3 copies of opencv (OpenCvSharpExtern.dll and opencv_ffmpeg410_64.dll)
One on the root of the publish folder, and then one x86 in the dll/x86 subfolder and one x64 in the dll/x64 subfolder.

![image](https://user-images.githubusercontent.com/1522516/68783478-59f09e80-063b-11ea-890e-51c2d1ea36e0.png)

Thanks
