### ISSUE TITLE
System.BadImageFormatException: Method has no body

### ISSUE THREAD

**Issue by gudimallaHari** [shimat/opencvsharp#698]
# Summary of your issue
Hi, Iam facing this exception (" System.BadImageFormatException: Method has no body") while trying to create "Mat" object from image path in xamarin forms. But "Mat" object is created successfully in console app when an image path is given an input.

# Environment
Project : Xamarin forms 
Configuration : Any CPU, x86, x64
dll : OpenCvSharp3-AnyCPU

# What did you do when you faced the problem?
I have changed the configuration of the project from "Any CPU" to "x86" and "x64" but no luck.
I even tried with passing stream to "FromStream" method to create "Mat" object. but no success.
I even tried with "OpenCVSharp4".

## Example code:

private async void Button_Clicked(object sender, EventArgs e) { var file = await CrossMedia.Current.PickPhotoAsync(); if (file == null) return;

        if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
        {
            await DisplayAlert("No Camera", ":( No camera avaialble.", "OK");
            return;
        }
       Test(file);
 }

 void Test(MediaFile file)
    {
        try
        {

              Mat mat = new Mat(file.Path);

        }
        catch(Exception e)
        {

        }
    }
![Capture](https://user-images.githubusercontent.com/35526061/60495376-4537ed80-9cce-11e9-9d66-a6250b34bda5.PNG)

**Comment by hez2010** [comment]
The package OpenCvSharp3-AnyCPU was no longer being maintained. 
Maybe you can try the package OpenCvSharp4.

**Comment by gudimallaHari** [comment]
Hi Steve,
i) As you said in the second step i had even tried with  opencvsharp4 dll also. But I am facing the same exception.
ii) As you in first step " you will still need to build and install original opencv libraries and OpenCvSharpExtern" . I was not able to find any "OpenCvSharpExtern" dll in nuget. I was not able to find it from any website when i googled it to add it as an external reference. Can you please provide me the link for this. Can you please also mention the original opencv libraries with their names or any source or document where there is a procedure available to make the solution worked.
ii) I even tried with "opencvsharp4.Windows" dll also. But no luck
Please find the attached screenshots
![Capture1](https://user-images.githubusercontent.com/35526061/60815558-8a1fc080-a1b5-11e9-8c63-8bd80527b3b4.PNG)
![Capture](https://user-images.githubusercontent.com/35526061/60815559-8a1fc080-a1b5-11e9-8751-87ad1840b749.PNG)

 for the installed libraries.

**Comment by hez2010** [comment]
OpenCvSharpExtern was not provided via nuget package directly. 
Its source is under this project repo: opencvsharp/src/OpenCvSharpExtern

You can build and install it for your device manually. 

For example, for Linux device you can run:
```
cd src/OpenCvSharpExtern
mkdir build && cd build
cmake ..
sudo make install -j8
```
