### ISSUE TITLE
East Text Detector

### ISSUE THREAD

**Issue by zpmmehrdad** [shimat/opencvsharp#702]
Hi everyone,

I want to convert below code to c#. How can I do it?

https://github.com/opencv/opencv/blob/master/samples/dnn/text_detection.cpp

thanks

**Comment by zpmmehrdad** [comment]
I could convert it but it does not work.
```

     public static void TextDetector()
        {
            float scoreThresh = 0.5f;
            float nmsThresh = 0.4f;
            Net net = CvDnn.ReadNetFromTensorflow(@"G:\IdCardRecog\ConsoleApplication1\ConsoleApplication1\frozen_east_text_detection.tar\frozen_east_text_detection\frozen_east_text_detection.pb");
            Mat frame = new Mat(@"G:\drive-download-20190529T042121Z-001\OCR\6.jpeg");
            Size siz = new Size(320, 320);
            int W = (int)(siz.Width / 4); // width of the output geometry  / score maps
            int H = (int)(siz.Height / 4); // height of those. the geometry has 4, vertically stacked maps, the score one 1
            Mat blob = CvDnn.BlobFromImage(frame, 1.0, siz, new Scalar(123.68, 116.78, 103.94), true, false);
            net.SetPreferableBackend(3);
            /*
            0:DNN_BACKEND_DEFAULT 
            1:DNN_BACKEND_HALIDE 
            2:DNN_BACKEND_INFERENCE_ENGINE
            3:DNN_BACKEND_OPENCV 
             */
            net.SetPreferableTarget(0);
            net.SetInput(blob);
            List<String> outNames = new List<string>();
            outNames.Add("feature_fusion/Conv_7/Sigmoid");
            outNames.Add("feature_fusion/concat_3");
            var outs = outNames.Select(_ => new Mat()).ToArray();
            net.Forward(outs, outNames);
            // Decode predicted bounding boxes.
            Mat scores = outs[0].Reshape(1, H);
            Mat geometry = outs[1].Reshape(1, 5 * H); // don't hardcode it !
            var confidencesList = new List<float>();
            List<RotatedRect> boxes = decode(scores, geometry, confidencesList, scoreThresh);
            
            int[] indices;
            CvDnn.NMSBoxes(boxes, confidencesList, scoreThresh, nmsThresh, out indices);

            // Render detections
            Point ratio = new Point((float)frame.Cols / siz.Width, (float)frame.Rows / siz.Height);
            int[] indexes = indices.ToArray();
            for (int i = 0; i < indexes.Length; ++i)
            {
                RotatedRect rot = boxes[indexes[i]];
                //Point[] vertices = new Point[4];
                var vertices = rot.Points();
                for (int j = 0; j < 4; ++j)
                {
                    vertices[j].X *= ratio.X;
                    vertices[j].Y *= ratio.Y;
                }
                for (int j = 0; j < 4; ++j)
                {
                    frame.Line(new Point(vertices[j].X, vertices[j].Y), new Point(vertices[(j + 1) % 4].X, vertices[(j + 1) % 4].Y), Scalar.Red, 2);
                }
            }

            var win = new Window("died.tw", WindowMode.KeepRatio, frame);
            win.Resize(500, 500);
            using (win)
            {
                Cv2.WaitKey();
            }
        }

        public static List<RotatedRect> decode(Mat scores, Mat geometry, List<float> confidences, float scoreThresh)
        {
            int W = geometry.Cols;
            int H = geometry.Rows / 5;

            List<RotatedRect> detections = new List<RotatedRect>();
            for (int y = 0; y < H; ++y)
            {
                Mat scoresData = scores.Row.Get(y);
                Mat x0Data = geometry.SubMat(0, H, 0, W).Row[y];
                Mat x1Data = geometry.SubMat(H, 2 * H, 0, W).Row[y];
                Mat x2Data = geometry.SubMat(2 * H, 3 * H, 0, W).Row[y];
                Mat x3Data = geometry.SubMat(3 * H, 4 * H, 0, W).Row[y];
                Mat anglesData = geometry.SubMat(4 * H, 5 * H, 0, W).Row[y];


                for (int x = 0; x < W; ++x)
                {
                    var score = scoresData.At<float>(0, x);
                    //double score = scoresData.At<double>(0, x);//[0];
                    if (score >= scoreThresh)
                    {
                        double offsetX = x * 4.0;
                        double offsetY = y * 4.0;
                        double angle = anglesData.At<double>(0, x);//[0];
                        double cosA = Math.Cos(angle);
                        double sinA = Math.Sin(angle);
                        double x0 = x0Data.At<double>(0, x);//[0];
                        double x1 = x1Data.At<double>(0, x);//[0];
                        double x2 = x2Data.At<double>(0, x);//[0];
                        double x3 = x3Data.At<double>(0, x);//[0];
                        double h = x0 + x2;
                        double w = x1 + x3;
                        Point offset = new Point(offsetX + cosA * x1 + sinA * x2, offsetY - sinA * x1 + cosA * x2);
                        Point p1 = new Point(-1 * sinA * h + offset.X, -1 * cosA * h + offset.Y);
                        Point p3 = new Point(-1 * cosA * w + offset.X, sinA * w + offset.Y); // original trouble here !
                        RotatedRect r = new RotatedRect(new Point(0.5 * (p1.X + p3.X), 0.5 * (p1.Y + p3.Y)), new Size2f(w, h), (float)(-1 * angle * 180 / Math.PI));
                        detections.Add(r);
                        confidences.Add((float)score);
                    }
                }
            }
            return detections;
        }
```

**Comment by zpmmehrdad** [comment]
I converted it but it does not work.

```

     public static void TextDetector()
        {
            float scoreThresh = 0.5f;
            float nmsThresh = 0.4f;
            Net net = CvDnn.ReadNetFromTensorflow(@"frozen_east_text_detection.pb");
            Mat frame = new Mat(@"6.jpeg");
            Size siz = new Size(320, 320);
            int W = (int)(siz.Width / 4); // width of the output geometry  / score maps
            int H = (int)(siz.Height / 4); // height of those. the geometry has 4, vertically stacked maps, the score one 1
            Mat blob = CvDnn.BlobFromImage(frame, 1.0, siz, new Scalar(123.68, 116.78, 103.94), true, false);
            net.SetPreferableBackend(3);
            /*
            0:DNN_BACKEND_DEFAULT 
            1:DNN_BACKEND_HALIDE 
            2:DNN_BACKEND_INFERENCE_ENGINE
            3:DNN_BACKEND_OPENCV 
             */
            net.SetPreferableTarget(0);
            net.SetInput(blob);
            List<String> outNames = new List<string>();
            outNames.Add("feature_fusion/Conv_7/Sigmoid");
            outNames.Add("feature_fusion/concat_3");
            var outs = outNames.Select(_ => new Mat()).ToArray();
            net.Forward(outs, outNames);
            // Decode predicted bounding boxes.
            Mat scores = outs[0].Reshape(1, H);
            Mat geometry = outs[1].Reshape(1, 5 * H); // don't hardcode it !
            var confidencesList = new List<float>();
            List<RotatedRect> boxes = decode(scores, geometry, confidencesList, scoreThresh);
            
            int[] indices;
            CvDnn.NMSBoxes(boxes, confidencesList, scoreThresh, nmsThresh, out indices);

            // Render detections
            Point ratio = new Point((float)frame.Cols / siz.Width, (float)frame.Rows / siz.Height);
            int[] indexes = indices.ToArray();
            for (int i = 0; i < indexes.Length; ++i)
            {
                RotatedRect rot = boxes[indexes[i]];
                //Point[] vertices = new Point[4];
                var vertices = rot.Points();
                for (int j = 0; j < 4; ++j)
                {
                    vertices[j].X *= ratio.X;
                    vertices[j].Y *= ratio.Y;
                }
                for (int j = 0; j < 4; ++j)
                {
                    frame.Line(new Point(vertices[j].X, vertices[j].Y), new Point(vertices[(j + 1) % 4].X, vertices[(j + 1) % 4].Y), Scalar.Red, 2);
                }
            }

            var win = new Window("died.tw", WindowMode.KeepRatio, frame);
            win.Resize(500, 500);
            using (win)
            {
                Cv2.WaitKey();
            }
        }

        public static List<RotatedRect> decode(Mat scores, Mat geometry, List<float> confidences, float scoreThresh)
        {
            int W = geometry.Cols;
            int H = geometry.Rows / 5;

            List<RotatedRect> detections = new List<RotatedRect>();
            for (int y = 0; y < H; ++y)
            {
                Mat scoresData = scores.Row.Get(y);
                Mat x0Data = geometry.SubMat(0, H, 0, W).Row[y];
                Mat x1Data = geometry.SubMat(H, 2 * H, 0, W).Row[y];
                Mat x2Data = geometry.SubMat(2 * H, 3 * H, 0, W).Row[y];
                Mat x3Data = geometry.SubMat(3 * H, 4 * H, 0, W).Row[y];
                Mat anglesData = geometry.SubMat(4 * H, 5 * H, 0, W).Row[y];


                for (int x = 0; x < W; ++x)
                {
                    var score = scoresData.At<float>(0, x);
                    //double score = scoresData.At<double>(0, x);//[0];
                    if (score >= scoreThresh)
                    {
                        double offsetX = x * 4.0;
                        double offsetY = y * 4.0;
                        double angle = anglesData.At<double>(0, x);//[0];
                        double cosA = Math.Cos(angle);
                        double sinA = Math.Sin(angle);
                        double x0 = x0Data.At<double>(0, x);//[0];
                        double x1 = x1Data.At<double>(0, x);//[0];
                        double x2 = x2Data.At<double>(0, x);//[0];
                        double x3 = x3Data.At<double>(0, x);//[0];
                        double h = x0 + x2;
                        double w = x1 + x3;
                        Point offset = new Point(offsetX + cosA * x1 + sinA * x2, offsetY - sinA * x1 + cosA * x2);
                        Point p1 = new Point(-1 * sinA * h + offset.X, -1 * cosA * h + offset.Y);
                        Point p3 = new Point(-1 * cosA * w + offset.X, sinA * w + offset.Y); // original trouble here !
                        RotatedRect r = new RotatedRect(new Point(0.5 * (p1.X + p3.X), 0.5 * (p1.Y + p3.Y)), new Size2f(w, h), (float)(-1 * angle * 180 / Math.PI));
                        detections.Add(r);
                        confidences.Add((float)score);
                    }
                }
            }
            return detections;
        }
```

**Comment by zpmmehrdad** [comment]
Can someone help me please!

**Comment by psimon78705** [comment]
Did you ever get a solution for this? Having the same problem

**Comment by ludwo** [comment]
This is my working solution https://gist.github.com/ludwo/c091ed6261d26654c8b71949d89f8142

**Comment by zpmmehrdad** [comment]
@ludwo Hi,

Thank you very much

**Comment by marquesmps** [comment]
> I converted it but it does not work.
> 
> ```cs
>      public static void TextDetector()
>         {
>             float scoreThresh = 0.5f;
>             float nmsThresh = 0.4f;
>             Net net = CvDnn.ReadNetFromTensorflow(@"frozen_east_text_detection.pb");
>             Mat frame = new Mat(@"6.jpeg");
>             Size siz = new Size(320, 320);
>             int W = (int)(siz.Width / 4); // width of the output geometry  / score maps
>             int H = (int)(siz.Height / 4); // height of those. the geometry has 4, vertically stacked maps, the score one 1
>             Mat blob = CvDnn.BlobFromImage(frame, 1.0, siz, new Scalar(123.68, 116.78, 103.94), true, false);
>             net.SetPreferableBackend(3);
>             /*
>             0:DNN_BACKEND_DEFAULT 
>             1:DNN_BACKEND_HALIDE 
>             2:DNN_BACKEND_INFERENCE_ENGINE
>             3:DNN_BACKEND_OPENCV 
>              */
>             net.SetPreferableTarget(0);
>             net.SetInput(blob);
>             List<String> outNames = new List<string>();
>             outNames.Add("feature_fusion/Conv_7/Sigmoid");
>             outNames.Add("feature_fusion/concat_3");
>             var outs = outNames.Select(_ => new Mat()).ToArray();
>             net.Forward(outs, outNames);
>             // Decode predicted bounding boxes.
>             Mat scores = outs[0].Reshape(1, H);
>             Mat geometry = outs[1].Reshape(1, 5 * H); // don't hardcode it !
>             var confidencesList = new List<float>();
>             List<RotatedRect> boxes = decode(scores, geometry, confidencesList, scoreThresh);
>             
>             int[] indices;
>             CvDnn.NMSBoxes(boxes, confidencesList, scoreThresh, nmsThresh, out indices);
> 
>             // Render detections
>             Point ratio = new Point((float)frame.Cols / siz.Width, (float)frame.Rows / siz.Height);
>             int[] indexes = indices.ToArray();
>             for (int i = 0; i < indexes.Length; ++i)
>             {
>                 RotatedRect rot = boxes[indexes[i]];
>                 //Point[] vertices = new Point[4];
>                 var vertices = rot.Points();
>                 for (int j = 0; j < 4; ++j)
>                 {
>                     vertices[j].X *= ratio.X;
>                     vertices[j].Y *= ratio.Y;
>                 }
>                 for (int j = 0; j < 4; ++j)
>                 {
>                     frame.Line(new Point(vertices[j].X, vertices[j].Y), new Point(vertices[(j + 1) % 4].X, vertices[(j + 1) % 4].Y), Scalar.Red, 2);
>                 }
>             }
> 
>             var win = new Window("died.tw", WindowMode.KeepRatio, frame);
>             win.Resize(500, 500);
>             using (win)
>             {
>                 Cv2.WaitKey();
>             }
>         }
> 
>         public static List<RotatedRect> decode(Mat scores, Mat geometry, List<float> confidences, float scoreThresh)
>         {
>             int W = geometry.Cols;
>             int H = geometry.Rows / 5;
> 
>             List<RotatedRect> detections = new List<RotatedRect>();
>             for (int y = 0; y < H; ++y)
>             {
>                 Mat scoresData = scores.Row.Get(y);
>                 Mat x0Data = geometry.SubMat(0, H, 0, W).Row[y];
>                 Mat x1Data = geometry.SubMat(H, 2 * H, 0, W).Row[y];
>                 Mat x2Data = geometry.SubMat(2 * H, 3 * H, 0, W).Row[y];
>                 Mat x3Data = geometry.SubMat(3 * H, 4 * H, 0, W).Row[y];
>                 Mat anglesData = geometry.SubMat(4 * H, 5 * H, 0, W).Row[y];
> 
> 
>                 for (int x = 0; x < W; ++x)
>                 {
>                     var score = scoresData.At<float>(0, x);
>                     //double score = scoresData.At<double>(0, x);//[0];
>                     if (score >= scoreThresh)
>                     {
>                         double offsetX = x * 4.0;
>                         double offsetY = y * 4.0;
>                         double angle = anglesData.At<double>(0, x);//[0];
>                         double cosA = Math.Cos(angle);
>                         double sinA = Math.Sin(angle);
>                         double x0 = x0Data.At<double>(0, x);//[0];
>                         double x1 = x1Data.At<double>(0, x);//[0];
>                         double x2 = x2Data.At<double>(0, x);//[0];
>                         double x3 = x3Data.At<double>(0, x);//[0];
>                         double h = x0 + x2;
>                         double w = x1 + x3;
>                         Point offset = new Point(offsetX + cosA * x1 + sinA * x2, offsetY - sinA * x1 + cosA * x2);
>                         Point p1 = new Point(-1 * sinA * h + offset.X, -1 * cosA * h + offset.Y);
>                         Point p3 = new Point(-1 * cosA * w + offset.X, sinA * w + offset.Y); // original trouble here !
>                         RotatedRect r = new RotatedRect(new Point(0.5 * (p1.X + p3.X), 0.5 * (p1.Y + p3.Y)), new Size2f(w, h), (float)(-1 * angle * 180 / Math.PI));
>                         detections.Add(r);
>                         confidences.Add((float)score);
>                     }
>                 }
>             }
>             return detections;
>         }
> ```
> 
> @shimat please help me thanks

I am trying the same, the problem is loading the pb file with OpenCVSharp4.Windows 4.2.0.20200208: 
`Net net = CvDnn.ReadNetFromTensorflow(@"frozen_east_text_detection.pb");`
also with
`Net net = CvDnn.ReadNet(@"frozen_east_text_detection.pb");`
I get the error:
System.ArgumentException: 'Cannot marshal: Encountered unmappable character.'
   at System.Runtime.InteropServices.Marshal.StringToAnsiString(String s, Byte* buffer, Int32 bufferLength, Boolean bestFit, Boolean throwOnUnmappableChar)
   at System.StubHelpers.CSTRMarshaler.ConvertToNative(Int32 flags, String strManaged, IntPtr pNativeBuffer)
   at OpenCvSharp.NativeMethods.dnn_readNetFromTensorflow(String model, String config, IntPtr& returnValue)
   at OpenCvSharp.Dnn.Net.ReadNetFromTensorflow(String model, String config)
   at OpenCvSharp.Dnn.CvDnn.ReadNetFromTensorflow(String model, String config)

I used the frozen_east_text_detection.pb from https://www.pyimagesearch.com/2018/08/20/opencv-text-detection-east-text-detector/

@zpmmehrdad Were you able to load it?

**Comment by ludwo** [comment]
Try to use full path to file, without special characters or spaces in path. Let's say @"c:\temp\frozen_east_text_detection.pb"

**Comment by marquesmps** [comment]
Hi @ludwo thank you for your reply, this will sound weird, I was opening with 
`using (Net net = CvDnn.ReadNetFromTensorflow("frozen_east_text_detection.pb"))`
Then changed it to read the file path from an argument rather than a string directly and it works:
`using Net net = CvDnn.ReadNetFromTensorflow(args[0]);` 
where **args[0]** is **"frozen_east_text_detection.pb"**
Still can't open it if the string is passed directly. I will see if I can find why this is happening.

**Comment by ludwo** [comment]
It seems like Encoding issue. String parameter from args/console has different encoding or codepage  as your string parameter "frozen_east_text_detection.pb".

**Comment by marquesmps** [comment]
@ludwo yes, that was it, thank you. I converted the file name from Unicode to ASCII, falling back the resulting special characters to empty, and now **CvDnn.ReadNetFromTensorflow** takes the string with no problem.
