### ISSUE TITLE
Opencv native mat to opencvsharp mat crash.

### ISSUE THREAD

**Issue by sevenzoe** [shimat/opencvsharp#703]
Hi:

Opencv native mat to opencvsharp mat crash.

Environment:
1. windows 10
2. visual studio 2017
3. WPF
4. C#

The program crashed after running for 25minutes.

Crashed:
![(Z3G1B3~FDM1RAWREORH5L6](https://user-images.githubusercontent.com/8321325/61039498-749ed680-a401-11e9-9ef8-725aac1878a2.png)

Code:

![)SK~`SY0UJ4PF1R% $I(K@E](https://user-images.githubusercontent.com/8321325/61039692-d6f7d700-a401-11e9-8a01-3557ea973860.png)
![(V}~1$P6R0NINF_BT~Q9~$W](https://user-images.githubusercontent.com/8321325/61039700-db23f480-a401-11e9-9b0f-1dc0a4faeb90.png)

I want to display camera pictures.

**Comment by zpmmehrdad** [comment]
Hi @sevenzoe 

You can use 
OpenCvSharp.Extensions.BitmapSourceConverter.ToBitmapSource(image);
Or
image.ToBitmapSource();// using OpenCvSharp.Extensions;

**Comment by sevenzoe** [comment]
Hi @zpmmehrdad:

The program will still crash:
![7UDYMWUASGHVG`}0GVD}ZIR](https://user-images.githubusercontent.com/8321325/61192674-d6548e80-a6e8-11e9-8519-972421571119.png)

**Comment by shimat** [comment]
Creating OpenCvSharp.Mat from your native Mat (cv::Mat*) is dangerous. You must use the same OpenCV version, the same VC++ version and  the same dependency libraries. It is difficult. Native library differences occasionally cause crashes.
