### ISSUE TITLE
dnn with cuda gpu error

### ISSUE THREAD

**Issue by pokernet** [shimat/opencvsharp#712]
this is the error i get but the application running :

OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!

**Comment by DeepDuke** [comment]
I met the same problem. Have you solved it ?

**Comment by joreg** [comment]
just found this: https://github.com/opencv/opencv/issues/14187
