### ISSUE TITLE
Memory leak on linux

### ISSUE THREAD

**Issue by haue** [shimat/opencvsharp#714]
# Memory leak on docker on linux
I have a asp.net core web project which used opencvsharp.It runs on docker on linux.The server's memory is 1G,I fond that every about 0.5 hour the memory will be reached 100%,and the program hang up.
# Environment
- server is 1 core cpu and 1G memory
- .net core 3.0.0-preview7-27912-14
- opencvsharp 4.1.0
- docker 18.03.0-ce
- debian 9

## Example code:
On windows,I use vistual studio, the diagnostics tools shows 29.3MB memory used.
But on docker on Linux,The following code caused memory leak. After it run finished,the memory use reached 306MB(use command : docker stats -a)
The following code is not all same as my asp.net web project,but I think the reason of memory leak is same.
```
using OpenCvSharp;
using System;
using System.Threading.Tasks;

namespace MemoryTestConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            Parallel.For(1, 200, (i) =>
            {
                using (var m = new Mat("Images/1.png"))
                {
                    System.Threading.Thread.Sleep(2000);
                    Console.WriteLine(m.GetHashCode());
                }
            });
            GC.Collect();
            Console.ReadLine();
        }
    }
}
```

## Output:

windows:
29MB
![windows.png](https://i.loli.net/2019/08/10/PRaVA1C7io25wdX.png)
linux:
306MB
![linux.png](https://i.loli.net/2019/08/10/U2mQHpMlCiOu3bZ.png)

**Comment by lxiaofei** [comment]
hi,i'm  use .net core same to u ,but when run the app on linux,still show error,like this:"DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory",can u tell me how to fix this problem?

**Comment by lxiaofei** [comment]
.net core 2.0 
opencvsharp 4.1.0
docker 18.03.0-ce
debian 9

**Comment by kysel** [comment]
Looks like the same problem as described here: https://github.com/dotnet/runtime/issues/13702
