### ISSUE TITLE
MouseWheel Event has a bug

### ISSUE THREAD

**Issue by keehyuck** [shimat/opencvsharp#721]
# Summary of your issue

MouseWheel event does not work.

# Environment

Visual Studio 2017 WPF

# What did you do when you faced the problem?

Other mouse events(ex. LButtonUp, RButtonUp) work, but MouseWheel Event does not work.

## Example code:

![2](https://user-images.githubusercontent.com/46583677/64160256-a1f28880-ce76-11e9-8d58-19496ad5e93a.JPG)
![1](https://user-images.githubusercontent.com/46583677/64160260-a454e280-ce76-11e9-8881-b885a874f055.JPG)

**Comment by shimat** [comment]
I'm sorry for the late reply. I'm fixing this issue by #825. The MouseEvent enum have not been modified since the OpenCV 1.x.
