### ISSUE TITLE
Conversation between System.Drawing.Point and OpenCvSharp.Point

### ISSUE THREAD

**Issue by CCRcmcpe** [shimat/opencvsharp#725]
Why not add a implicit operator between System.Drawing.Point and OpenCvSharp.Point?
And I have to use something like this:
`using PointCv = OpenCvSharp.Point; using PointNet = System.Drawing.Point;`
to avoid annoying full qualifications.

**Comment by CCRcmcpe** [comment]
Types like OpenCvSharp.Size also have this problem.

**Comment by shimat** [comment]
Previously, OpenCvSharp provided implicit conversions between System.Drawing.Point/Size/Rectangle and OpenCvSharp.Point/Size/Rect.
However, if the OpenCvSharp assembly has a reference to System.Drawing, I decided that OpenCvSharp's portability would be reduced.
