### ISSUE TITLE
Dockerfile build fails in the master branch

### ISSUE THREAD

**Issue by masantiago** [shimat/opencvsharp#727]
# Summary of your issue
Docker build fails in the master branch.
# Environment
Mac with docker installed.

# What did you do when you faced the problem?
Simply building the Dockerfile in the master branch

## Example code:
```
docker build -i opencvsharp .
```
## Output:

```
[ 64%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/std_string.cpp.o
In file included from /opencvsharp/src/OpenCvSharpExtern/quality.cpp:1:0:
/opencvsharp/src/OpenCvSharpExtern/quality.h: In function 'void quality_QualityBase_getQualityMap(cv::quality::QualityBase*, cv::_OutputArray*)':
/opencvsharp/src/OpenCvSharpExtern/quality.h:16:10: error: 'class cv::quality::QualityBase' has no member named 'getQualityMap'; did you mean 'getQualityMaps'?
     obj->getQualityMap(*dst);
          ^~~~~~~~~~~~~
          getQualityMaps
```

## What did you intend to be?
A successful compilation. It seems that there is an error on the source code

**Comment by amdi** [comment]
I've encountered the same issue.

**Comment by amdi** [comment]
Update: I updated the OpenCV version in the docker file: `ENV OPENCV_VERSION=4.1.0` from 4.1.0 to 4.1.1 and it built fine. I'm assuming the QualityBase object in OpenCV must have changed and so building against latest OpenCV breaks the docker build. Maybe opencvsharp devs can react to that change or simply update the OpenCV version in the dockerfile. 

@masantiago hopefully this helps you.

**Comment by masantiago** [comment]
It helps a lot! Thank you very much @amdi !
