### ISSUE TITLE
Please Support UWP

### ISSUE THREAD

**Issue by zhuxb711** [shimat/opencvsharp#728]
For a long time, UWP platforms have no good OpenCV packages.

I hope developers could add support for the UWP platform.

**Comment by sundxfansky** [comment]
same view

**Comment by Noemata** [comment]
Given vcpkg generates UWP libs for OpenCV 4.1.1, it seems opencvsharp could be packaged as a .Net Standard 2.0 lib with perhaps a smallish uwp piece to provide the remaining integration.  Any thoughts?

**Comment by Noemata** [comment]
I'm somewhat mystified why UWP isn't supported out of the box.  It took about an hour to get this working!  The fact that OpenCvSharp is a .Net Standard 2.0 lib made this easy.  Thank you.

P.S. The only trouble I ran into was with these macros (you'll notice my change):

#ifndef CV_EXPORTS
# if (defined _WIN32 || defined WINCE || defined __CYGWIN__) && defined(CVAPI_EXPORTS)
#   define CV_EXPORTS __declspec(dllexport)
# elif defined __GNUC__ && __GNUC__ >= 4 && (defined(CVAPI_EXPORTS) || defined(__APPLE__))
#   define CV_EXPORTS __attribute__ ((visibility ("default")))
# endif
#endif

#ifndef CV_EXPORTS
//#define CV_EXPORTS
#define CV_EXPORTS __declspec(dllexport)
#endif

I did trying defining _WIN32, but it made no difference.  I'm probably not seeing something obvious.
