### ISSUE TITLE
2.4.10

### ISSUE THREAD

**Issue by tbreina** [shimat/opencvsharp#73]
In the 2.4.10 release zip file (https://github.com/shimat/opencvsharp/releases/download/2.4.10.20141111/OpenCvSharp-2.4.10-x86-20141110.zip), the DLL config files (e.g. OpenCvSharp-2.4.10-x86-20141110/OpenCVSharp.dll.config) are pointing to the 2.4.9 DLLs. 

For example,

  <dllmap os="!windows" dll="opencv_calib3d249" target="libopencv_calib3d.so" />

Is looking for Calib dll version 2.4.9 not 2.4.10. 

Thanks for the great project. It is very useful.
-Tony

**Comment by shimat** [comment]
Sorry for the late reply. dll.config was updated. https://github.com/shimat/opencvsharp/commit/87077da0183d45768d155bdf4eae671586cadf38
