### ISSUE TITLE
InitLineIterator 

### ISSUE THREAD

**Issue by feelsyt** [shimat/opencvsharp#730]
Excuse me,  InitLineIterator   this function is not encapsulated? Or what functions can be used to substitute for the number of pixels in the straight line of the two coordinate points?

**Comment by shimat** [comment]
Please consider using LineIterator (`cv::LineIterator`'s wrapper).

```c#
// C# 8
using var mat = new Mat("foo.png");
var p1 = new Point(100, 200);
var p2 = new Point(123, 432);

using var lineIterator = new LineIterator(mat, p1, p2);

var pixelCount = lineIterator.Count(); // Linq (Enumerable.Count)
```
