### ISSUE TITLE
change frame size of video Capture

### ISSUE THREAD

**Issue by nguyenthaohut** [shimat/opencvsharp#735]
# Summary of your issue
I have 5MP camera, and I can use opencvsharp to capture(or liveview ) at 2 resolution 2592x1944 and 1280x1024, but I want to make liveview at 1280 and capture single image at 2592, it return black image at size 2592, how to do that, I stop camera and re-init it but it does not work.
# Environment
window 7, opencv sharp 4.1.0
Write your environment.

# What did you do when you faced the problem?

//write here

## Example code:

```c#
bool InitCamCapture()
        {
            _capture = new VideoCapture();

            _nCamIndex = CheckCamID();

            if (_nCamIndex <= -1) return false;

            if (_capture.IsOpened())
                _capture.Release();

            _capture.Open(_nCamIndex);

            _capture.FrameWidth = 1280;
            _capture.FrameHeight = 1044;

            _capture.Read(_framePreview);

            if (_framePreview.Height > 0)
            {
                timerWebCam.Enabled = true;

                _bmpCam = _framePreview.ToBitmap();

                //_bmpCam.RotateFlip(RotateFlipType.Rotate90FlipNone);

                picCamera.Image = _bmpCam;
                return true;
            }

            return false;
        }

private void btCapture_Click(object sender, EventArgs e)

        {
            _nCamIndex = 1;
            timerWebCam.Enabled = false;
            Thread.Sleep(100);

            if (_capture.IsOpened())
            {
                _capture.Release();
            }

            _capture = new VideoCapture();
            _capture.FrameWidth = 2592;
            _capture.FrameHeight = 1944;

            _frameCapture = new Mat();

            _capture.Open(_nCamIndex);

            _capture.Read(_frameCapture);

            _frameCapture.SaveImage("cap.bmp");

            InitCamCapture();
        }
```

## Output:

```
paste your output
```

**Comment by Tum4ik** [comment]
I also can't change the frame size on video capture. In any camera the resolution is always 640 x 480. If I try to change it via properties
```csharp
using var capture = new VideoCapture(0);
capture.FrameWidth = 640;
capture.FrameHeight = 480;
```
or even in the traditional way
```csharp
using var capture = new VideoCapture(0);
capture.Set(CaptureProperty.FrameWidth, 640);
capture.Set(CaptureProperty.FrameHeight, 480);
```
I only get the black frame.
As you could see I keep the default resolution (640 x 480) and anyway it produces the black frames.

**Comment by Tum4ik** [comment]
Hm... but today it is working with one camera and is not working with another one... So, it seems it is related to some my environment problems.

**Comment by shimat** [comment]
It's a matter of OpenCV or your device, not OpenCvSharp. Sorry but I close this issue. Try it with native OpenCV.

**Comment by ticTechtoee** [comment]
After lots of searching, I discovered that there's a way to reduce the resolution but you have to structure your code in a specific way.

- First of all, Define the VideoCapture

`capture = new VideoCapture(0);`

- Then Open the Device

`capture.Open(deviceIndex);`

- Then define the frame height and frame width

```
capture.FrameHeight = 64;
capture.FrameWidth = 36;
```

- Finally, write it into a file

`outputVideo = new VideoWriter("video.mp4", FourCC.AVC, 29, new OpenCvSharp.Size(capture.FrameWidth, capture.FrameHeight));`

**Comment by ydeydier** [comment]
> After lots of searching, I discovered that there's a way to reduce the resolution but you have to structure your code in a specific way.
> 
> * First of all, Define the VideoCapture
> 
> ```
> // 0 is the device index, you can change it as per your needs
> deviceIndex = 0;
> capture = new VideoCapture(deviceIndex);
> ```
> 
> * Then Open the Device
> 
> `capture.Open(deviceIndex);`
> 
> * Then define the frame height and frame width
> 
> ```
> capture.FrameHeight = 64;
> capture.FrameWidth = 36;
> ```
> 
> * Finally, write it into a file
> 
> `outputVideo = new VideoWriter("video.mp4", FourCC.AVC, 29, new OpenCvSharp.Size(capture.FrameWidth, capture.FrameHeight));`

"Open" BEFORE "FrameHeight" and "FrameWidth" did the job for me. Thanks a lot.

**Comment by ticTechtoee** [comment]
> > After lots of searching, I discovered that there's a way to reduce the resolution but you have to structure your code in a specific way.
> > 
> > * First of all, Define the VideoCapture
> > 
> > ```
> > // 0 is the device index, you can change it as per your needs
> > deviceIndex = 0;
> > capture = new VideoCapture(deviceIndex);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Then Open the Device
> > 
> > `capture.Open(deviceIndex);`
> > 
> > * Then define the frame height and frame width
> > 
> > ```
> > capture.FrameHeight = 64;
> > capture.FrameWidth = 36;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Finally, write it into a file
> > 
> > `outputVideo = new VideoWriter("video.mp4", FourCC.AVC, 29, new OpenCvSharp.Size(capture.FrameWidth, capture.FrameHeight));`
> 
> "Open" BEFORE "FrameHeight" and "FrameWidth" did the job for me. Thanks a lot.

Glad It worked for you :)
