### ISSUE TITLE
Wrong box's size from `MultipleTracker`

### ISSUE THREAD

**Issue by Ursanon** [shimat/opencvsharp#736]
# Summary of your issue
MultipleTracker returns correct image coordinates (`X`, `Y`) but invalid size (`Width`, `Height`) - always equals `(0;0)`. 

# Environment
OS: Linux 4.9.184-linuxkit x86_64
OpenCV: 3.4.8-pre
OpenCVSharp: 3.4.4.20181118

# What did you do when you faced the problem?
Tracking multiple detections with build-in `MultipleTracker` class.
Without `MultipleTracker`, all `Trackers` returns valid rect.

## Example code:
```
//...
var roi = new Rect2d(644, 553, 825, 475);
MultiTracker multiTracker = MultiTracker.Create();
multiTracker.Add(TrackerKCF.Create(), frame, roi);

if(multiTracker.Update(frame, our var boxes))
{
//...
}

//...
```

## Output:
`Rect(643, 552, 0, 0)`

## What did you intend to be?
`Rect(643, 553, 825, 475)`

**Comment by shimat** [comment]
Version mismatch may be the cause.

> OpenCV: 3.4.8-pre
> OpenCVSharp: 3.4.4.20181118

I will not update the wrapper for OpenCV 3.x in the future. Please try 4.x instead.
