### ISSUE TITLE
freetype module support

### ISSUE THREAD

**Issue by goodtogood** [shimat/opencvsharp#739]
Hi, 

  opencvsharp is great!
I would like to draw UTF-8 strings,
Is there some plan for supporting [freetype](https://github.com/opencv/opencv_contrib/tree/master/modules/freetype) binding?

thanks!

**Comment by shimat** [comment]
I think that many of the functions of freetype can be substituted by GDI+. My development priority of the freetype wrapper is low.

**Comment by goodtogood** [comment]
@shimat  GDI+ drawing is much slower than native lib
