### ISSUE TITLE
CvRect::Containsの挙動

### ISSUE THREAD

**Issue by KojiKobayashi** [shimat/opencvsharp#74]
http://opencv.jp/opencv-2svn/cpp/basic_structures.html
によると、
>OpenCV におけるもう 1 つの前提は，矩形の上側と左側の境界線は矩形に含まれ，右側と下側の境界線は含まれない，ということです．

とのことなので、以下のサンプルだと、
```
    var rect1 = new CvRect(10, 10, 100, 100);
    var rect2 = new CvRect(10, 10, 100, 100);

    Console.WriteLine(rect1.Contains(rect2.TopLeft));
    Console.WriteLine(rect1.Contains(rect2.Left, rect2.Top));
    Console.WriteLine(rect1.Contains(rect2.BottomRight));
    Console.WriteLine(rect1.Contains(rect2.Right, rect2.Bottom));
    Console.WriteLine(rect1.Contains(rect2));
```
True
True
False
False
True
が妥当かと思われますが、実際は、
True
True
False
True
False
となります。
この挙動は意図したものでしょうか。

**Comment by shimat** [comment]
こちらにて修正を図っています。

https://github.com/shimat/opencvsharp/pull/75
