### ISSUE TITLE
where is "MatOfByte" class in new 4.1.1?

### ISSUE THREAD

**Issue by ntuchenxy** [shimat/opencvsharp#744]
I update opencvsharp from 4.1.0 to 4.1.1, and can not find "MatOfByte" class. The sample "Accessing Pixel" from https://github.com/shimat/opencvsharp/wiki/Accessing-Pixel can not run in 4.1.1?

**Comment by shimat** [comment]
In 4.1, `MatOfT` changed to `Mat<T>`.

```c#
var mat3 = new Mat<Vec3b>();
```
