### ISSUE TITLE
WrapAffine fails on Images with Width=8192 on a 64bit architecture

### ISSUE THREAD

**Issue by JoachimBlank** [shimat/opencvsharp#745]
# Summary of your issue
WrapAffine fails with "System.AccessViolationException" on Images with a Width of 8192 and a Height >= 77 Pixel.

# Environment
Win10, running as 64 bit (does not fail on 32bit architecture).
OpenCVSharp Version 4.1.1.20191017

# What did you do when you faced the problem?

## Example code:

```
Mat src = new Mat(new Size(8192, 77), MatType.CV_8UC4);

Mat matrix = new Mat(new Size(3, 2), MatType.CV_64FC1);
matrix.Set<double>(0, 0, 1);
matrix.Set<double>(1, 1, 1);

Mat dst = new Mat();

Cv2.WarpAffine(src, dst, matrix, src.Size()); // fails with exception
```

## Output:

```
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
```

**Comment by shimat** [comment]
I was able to reproduce this problem. Thank you. This may be a problem with native OpenCV.
