### ISSUE TITLE
OpenCvSharp4.Windows Unable to load DLL 'OpenCvSharpExtern'

### ISSUE THREAD

**Issue by titovmaxim** [shimat/opencvsharp#753]
# Summary of your issue
While upgrade from OpenCVSharp3 to OpenCVSharp4 (4.1.1.20191026) got error that OpenCvSharpExtern can not be loaded. Dll folder under bin is empty. Tried both OpenCvSharp4 + OpenCvSharp4.runtime.win and OpenCvSharp4.Windows. Just changing back from 4 to 3 version by NuGet solve the problem (app works, dll folder contains necessary DLLs).

Look similar to Issue #605.

# Environment
Window 10, dotNet 4.8

# What did you do when you faced the problem?
Upgade from OpenCVSharp3 to OpenCVSharp4 (4.1.1.20191026).

**Comment by GeovaneW96** [comment]
Facing same problem here.

**Comment by shimat** [comment]
Can you show me your .csproj file? Importing .props file may fail.
```xml
  <Import Project="..\packages\OpenCvSharp4.runtime.win.4.1.1.20191026\build\net\OpenCvSharp4.runtime.win.props" Condition="Exists('..\packages\OpenCvSharp4.runtime.win.4.1.1.20191026\build\net\OpenCvSharp4.runtime.win.props')" />

```

**Comment by lkyero** [comment]
Facing same problem here.
**OpenCvSharp3** and [Releases ](https://github.com/shimat/opencvsharp/releases)both have **OpenCvSharpExtern.dll**, but **OpenCvSharp4** does not.

**Comment by shimat** [comment]
Could you confirm whether the Import command in your csproj file exists and is valid?
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\OpenCvSharp4.runtime.win.4.1.1.20191026\build\net\OpenCvSharp4.runtime.win.props" Condition="Exists('..\packages\OpenCvSharp4.runtime.win.4.1.1.20191026\build\net\OpenCvSharp4.runtime.win.props')" />
...
```

If you uninstall `OpenCvSharp4.Windows` and install `OpenCvSharp4` and `OpenCvSharp4.runtime.win` instead, does the problem occur?

I can't reproduce this problem. OpenCvSharp4.Windows works for me.

**Comment by NilesDavis** [comment]
I also ran into the problem and I also thought it was a bug. After crawling through all referenced projects I found some, still pointing to OpenCvSharp3 in .csproj-files as well as package.config.
Fixing all occurances did it for me. So the answer is: I could reproduce the problem by making mistakes myself ;)

**Comment by lkyero** [comment]
> Facing same problem here.
> **OpenCvSharp3** and [Releases ](https://github.com/shimat/opencvsharp/releases)both have **OpenCvSharpExtern.dll**, but **OpenCvSharp4** does not.

Nice!  The problem is solved  ：）
I uninstal`OpenCvSharp4`  and install `OpenCvSharp4.Windows`

**Comment by lkyero** [comment]
> Facing same problem here.
> **OpenCvSharp3** and [Releases ](https://github.com/shimat/opencvsharp/releases)both have **OpenCvSharpExtern.dll**, but **OpenCvSharp4** does not.

Nice!  The problem is solved  ：）
I uninstal`OpenCvSharp4`  and install `OpenCvSharp4.Windows`
