### ISSUE TITLE
Suspicious fragments found by PVS-Studio Static Analyzer

### ISSUE THREAD

**Issue by ekaterinanikiforova** [shimat/opencvsharp#754]
Hello,
I checked OpenCvSharp with a PVS-Studio static analyzer and found several suspicious places in the code. The most interesting places in my opinion I described in the article: "[Checking the OpenCvSharp Wrapper for OpenCV with PVS-Studio](https://www.viva64.com/en/b/0683/)". Not all of the analyzer's warnings were cited in the article. Perhaps some warnings not considered in the article will seem more interesting than the ones, described by me. Therefore, I suggest trying the [license for open-source projects](https://www.viva64.com/en/b/0614/) and check the project yourself.  Hopefully this will help you make the code even better.

**Comment by shimat** [comment]
Most of the issues you pointed out have already been corrected in the master. Do not write articles about the old code.

I don't understand what you pointed out about your "The most interesting warnings". There is no mistake. I wrote it intentionally.

In recent years, I have been able to improve code quality with the help of ReSharper. 

The writing of your article is very frustrating for me. Why don't you do a pull request? I don't agree with your company's article policy.
