### ISSUE TITLE
.nuget package does not add reference?

### ISSUE THREAD

**Issue by dooferorg** [shimat/opencvsharp#756]
Added the OpenCVsharp4 nuget packages but no references are added, same as when I tried the opencvsharp3 package as indicated here: https://ourcodeworld.com/articles/read/761/how-to-take-snapshots-with-the-web-camera-with-c-sharp-using-the-opencvsharp-library-in-winforms

How does one actually make this usable within Visual Studio 2017 on a .NET Framework 4.7.2 application?

OpenCvSharp4, OpenCvSharp4.runtime.win and OpenCvSharp4.Windows are installed

**Comment by dooferorg** [comment]
Anyone got any thoughts on this? I've done exactly what's stated on the readme for this project but it's not working, Visual Studio does not 'see' OpenCvSharp as something to 'use'

**Comment by shimat** [comment]
How did you add the OpenCvSharp NuGet to your project?

Can you run the sample project? The sample has references to the OpenCvSharp NuGet Packages.
https://github.com/shimat/opencvsharp_samples/tree/c6520b13a787ff9c9830e48ea41f538624ebd80b/SamplesCS

**Comment by dooferorg** [comment]
> How did you add the OpenCvSharp NuGet to your project?
> 
> Can you run the sample project? The sample has references to the OpenCvSharp NuGet Packages.
> https://github.com/shimat/opencvsharp_samples/tree/c6520b13a787ff9c9830e48ea41f538624ebd80b/SamplesCS

I will try that sample project, but how I added the packages was just to search within the nuget package manager (Manage Nuget packages) on Visual Studio 2017 on a .NET Framework 4.7.2 project. I searched for 'opencvsharp4'

Tried two different computers and the result is the same.

When I try and add the lines from the example it complains it's an unknown reference. I also do not see it added to the references area of the project, nor any DLL I can select. I have not gone browsing for DLLs to add but that seems not to be detailed on any requirement for installation

**Comment by dooferorg** [comment]
Ok, found out what the issue was. Visual Studio made a .csproj.user file, and it was messing up it understanding the project references.

Closing the solution and removing that file, then reopening and adding the using statements back in and it was recognized. Very odd.
