### ISSUE TITLE
UWP support is easy to add, please do.

### ISSUE THREAD

**Issue by Noemata** [shimat/opencvsharp#759]
Given how easy it is to add UWP support with OpenCV 4.1.1, please add this to the repo.

All that's needed is to create a WinRT DLL equivalent of OpenCvSharpExtern.

See issue #728

**Comment by shimat** [comment]
Sorry but my current interest is to run on Linux, not UWP. Supporting UWP will take a lot of time to  add tests/samples and support CI.

If you know what to modify, could you do a pull request?

**Comment by Noemata** [comment]
Took an hour to get 80% working.  I realize that the last 2% is sometimes a challenge.  That said, a lot of folks would be quite happy with 95% of what's there now.

I added: my_functions.cpp and put in:

```
#include "pch.h"

void StringConvert(const std::string from, std::wstring& to)
{
	int num = MultiByteToWideChar(CP_UTF8, 0, from.c_str(), -1, NULL, 0);

	if (num > 0)
	{
		to.resize(size_t(num) - 1);
		MultiByteToWideChar(CP_UTF8, 0, from.c_str(), -1, &to[0], num);
	}
}

void StringConvert(const std::wstring from, std::string& to)
{
	int num = WideCharToMultiByte(CP_UTF8, 0, from.c_str(), -1, NULL, 0, NULL, NULL);

	if (num > 0)
	{
		to.resize(size_t(num) - 1);
		WideCharToMultiByte(CP_UTF8, 0, from.c_str(), -1, &to[0], num, NULL, NULL);
	}
}
```

Adjusted my_functions.h as follows:

```
static int p(const char *msg, const char caption[] = "MessageBox")
{
    //return MessageBoxA(NULL, msg, caption, MB_OK);

	std::wstring wmsg;
	std::wstring wcaption;
	StringConvert(msg, wmsg);
	StringConvert(caption, wcaption);

	Windows::UI::Popups::MessageDialog(ref new Platform::String(wmsg.c_str()), ref new Platform::String(wcaption.c_str())).ShowAsync();
	return MB_OK;
}
```

You'll want to throw in a macro to do platform level selection.

The rest involved making OpenCvSharpExtern a WinRT dll.  Bringing in the UWP version of OpenCV 4.1.1 binaries was super easy with vcpkg.  I'm pretty sure you could get 95% of the way there in about 3 to 4 hours.  I would let the user do the vcpkg part.

**Comment by Noemata** [comment]
Very nice work, by the way.

**Comment by shimat** [comment]
Thank you for your work :+1: 
A few years ago I tried to support UWP, but P/Invoke didn't work. I'm glad if this work is successful.

> Is there a reason you are not using pre-compiled headers?

I thought that pre-compiled header would be difficult to be built on multiple platforms (e.g. Linux).

**Comment by Noemata** [comment]
You could easily add a platform flag like so for aruco.cpp and likewise for any other cpp file:

```
#ifdef WINRT
#include "pch.h"
#endif
#include "aruco.h"
```

Since your code is so nicely structured, this check would role in nicely for UWP builds.

**Comment by Noemata** [comment]
Here's how I got OpenCV for UWP.

.\vcpkg install opencv[contrib]:x64-uwp --recurse

Where x64, x86 and ARM would build the corresponding version.

**Comment by Noemata** [comment]
I've posted my repo changes here:

https://github.com/Noemata/OCVSharpTest

Hope this helps things along.

**Comment by Noemata** [comment]
The only glaring omission in OpenCVSharp I've run into is the fact that this isn't explosed:

void cv::winrt_initContainer(::Windows::UI::Xaml::Controls::Panel^ _container)

Most of my tests have worked without issue except those that use HighguiBridge code.  I've updated the repo above with some additional comments about this.

**Comment by Noemata** [comment]
I was able to get the Cv2.ImShow() and Cv2.InitContainer() working.  The changes are in the repo above.  I'm finding things quite usable under UWP at this point.  Thank you very much for making this so easy to sort out.

**Comment by shimat** [comment]
Thank you for your work :+1: 
I'm sorry but I don't have time now, but I'll check later.

**Comment by Noemata** [comment]
No rush.  I've got what I need for now.  Going very smoothly thanks to your nice design.

**Comment by shimat** [comment]
memo:
1. Since UWP does not allow static linking, I have to reconsider how to distribute OpenCvSharpExtern.dll.
1. I used vcpkg before, but it doesn't work well with the appveyor CI. I have to think about how to build native libraries for UWP. vcpkg is difficult to choose OpenCV version and build options. I will not be working with UWP in the future. I can't maintain OpenCvSharp for UWP unless I automate the development and deployment of it. 
    1. One solution is to export from vcpkg to NuGet, but the output NuGet package is too big to register with NuGet.org.

**Comment by Noemata** [comment]
That's a bit of a dilemma.  I can see the NuGet package becoming quite large.  Perhaps it could be chunked.  It's extremely easy to use the vcpkg export option to create a partial nuget payload, so that might be one option.  It's also a zero effort solution.  I'm not sure what you mean by "static linking".  Because of your wise choice of a "C" calling convention intermediate DLL, the step outside of C# land is always a dynalink to this layer.  Beyond that, the mechanics of everything are invisible to the user.  I'm not familiar with continuous integration products, so I can't really comment on that.  I did try to package things up a little better for you.  My changes are very modest in scope.  Given what you've done so far, I think once you get over the psychological hurdle of touching the sticky bits of UWP, you'll get the rest sorted out quickly.  UWP isn't as scary or as icky as it used to be.

**Comment by shimat** [comment]
Because of the static linking, the managed OpenCvSharp assembly depends only on OpenCvSharpExtern.dll and not on OpenCV DLLs such as opencv_core411.dll. It is a source of trouble that there are many DLLs to distribute. Distributing a single OpenCvSharpExtern DLL contributes to reducing github issues of “Failed to load DLL and crashed”, which is always annoying me. 
> opencv_world solves this problem somewhat. However, when including contrib, to build OpenCV often fail. I don't want to use opencv_world for development.

It is heavy to change the base of OpenCvSharp, such as nuget distribution and CI. Building OpenCvSharp on the appveyor CI is already very slow (> 20min). It will be even slower if I add build for x86/x64 UWP (> 40-50min??). I haven't made any money with OpenCvSharp, so I can't take the solution of paying CI to speed it up. It might be better to develop a separate repository for UWP wrappers.

I was able to run your code with me. Thank you for your contribution :+1: As you say, I found that it is easy to test UWP support. But it will take a lot of time to release UWP support.

**Comment by shimat** [comment]
I added your uwp code sample (CameraOpenCV) to https://github.com/shimat/opencvsharp_samples .
It references beta version of OpenCvSharp for UWP made by #763, and it seems to work fine.

**Comment by Noemata** [comment]
Ahhh … now I understand.  You create a static library blob of the entire OpenCV code base and stuff it into opencv_core411.dll, no wonder you are experiencing so much pain.  I wasn't able to see that in my initial efforts because I wasn't able to get things to build as they were, hence my venture into an alternative.  Static linking has been old school for a very long time.  Now it would be considered old old old school!  You are causing yourself needless pain by going this route.  You have already sorted out the single biggest head ache associated with many DLLs dynalinked to a C# project, by bundling all the lib calls in your OpenCvSharp.Extensions module.  That was a very simple, elegant solution to that part of the problem.  And that was all that is needed (and what made it really easy for me).  Despite the large number of external DLLs used by OpenCV, you should see that as a good thing, and not the reverse.  The whole purpose of DLLs was to solve the maintenance and build issues associated with static linking.  A problem that you are almost over your head with.  Static linking is like a stone axe, compared to the modern chain saw of DLLs.  DLLs dramatically improve maintainability because you can ship just one or two DLLs for a fix that need not affect anything above it; your memory footprint can be limited to only what is being used, and best of all, your build times are measured in seconds.   On my version of your repo, whenever I make even non-trivial changes, everything is built within seconds (often under 10 of them).  Testing is way more attractive when it doesn't cost you 20 minutes per build.   You will be far better off sorting out the details of including all the requisite OpenCV DLLs, perhaps in multiple Nuget packages, then to continue with static linking.  Your hurting yourself most of all, and also the users of the lib.  Reinvest in yourself, move away from static linking, and live in the present, it's more fun here.

**Comment by Noemata** [comment]
Thinking about this a little more, your lib would be so much nicer as a set of Nuget packages.  The core would be a super small package that incorporated just the C# bits.  The rest of the nuget packages would reflect the native DLL variants.  That way you could get a performance improvement or a bug fix without affecting anything in C# land simply by updated one of the DLL bundle packages.  How nice is that?  All your maintenance and distributions problems would go away for a one time investment in a more complicated build process of the nuget packages.

**Comment by Noemata** [comment]
Thanks for your code cleanup in the sample.  I don't think I would have spotted the missing Dispose for awhile.  The sample is still quite rough.  I'll finish cleaning that up shortly, was more focused on getting other things working.  I incorporated your changes in my repo.  Did you wind up using this in Cv2_highgui?

```
#if WINRT
        // MP! Added: To correctly support imShow under WinRT.

        /// <summary>
        /// Initialize XAML container panel for use by ImShow
        /// </summary>
        /// <param name="panel">Panel container.</param>
        public static void InitContainer(object panel)
        {
            NativeMethods.highgui_initContainer(panel);
        }
#endif
```

**Comment by shimat** [comment]
> Thinking about this a little more, your lib would be so much nicer as a set of Nuget packages. The core would be a super small package that incorporated just the C# bits. The rest of the nuget packages would reflect the native DLL variants. That way you could get a performance improvement or a bug fix without affecting anything in C# land simply by updating one of the native DLL bundle packages. How nice is that? All your maintenance and distribution problems would go away for a one time investment in a more complicated build process of the nuget packages.


The `OpenCvSharp4` package is a core C# package, and the `OpenCvSharp4.runtime.[win/uwp/ubuntu]` packages are a native part package.

#763 is doing better than expected. As you say, I can revert OpenCvSharp to a dynamic link.

**Comment by shimat** [comment]
added `Dispose`
https://github.com/shimat/opencvsharp_samples/commit/6295a94dc01ccb45806d076db985fa08a68a29fd

By the way, precompiled header makes CI build slower because /Yc disables /MP. I don't care about C++ build speed in my local environment.

**Comment by shimat** [comment]
InitContainer is added: https://github.com/shimat/opencvsharp/pull/763/files#diff-0409722ae2dfd85b0c5ed5a9a50f9e76R332

**Comment by Noemata** [comment]
I'm glad this is working out.  Thank you for your patience.  Please let me know when you have revised Nuget packages up.  I'd much rather use your work!

**Comment by shimat** [comment]
@Noemata :pray: 
https://www.nuget.org/packages/OpenCvSharp4.runtime.uwp/4.1.1.20191110
https://www.nuget.org/packages/OpenCvSharp4/4.1.1.20191110

For UWP, note that NuGet packages named OpenCvSharp4.runtime.win and OpenCvSharp4.Windows don't work. Use OpenCvSharp4.runtime.uwp instead.

**Comment by Noemata** [comment]
All I can say is fantastic!  Working nicely.  Thank you very much dear sir.  If you add me as a contributor to the samples repo, I'll clean up the uwp sample over the next couple days.

**Comment by shimat** [comment]
Everyone can make a pull request whether or not a contributor. Please try to fork my repository and edit it.
