### ISSUE TITLE
Different LICENSE.txt files

### ISSUE THREAD

**Issue by Karmahero** [shimat/opencvsharp#76]
The root LICENSE.txt file states the project as BSD license, but the source (src/OpenCVSharp) contains a LICENSE.txt files that states it is under GPL license. I assume the root license takes precedence, but it would be better to update all the LICENSE.txt files to be the same type.

**Comment by shimat** [comment]
As you say, BSD license is correct for OpenCvSharp. The old license file as LGPU is deleted. Thank you. :+1: 

https://github.com/shimat/opencvsharp/commit/7f164d056b1062089492a916498af34e7ee12be5
