### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by MikePelton** [shimat/opencvsharp#760]
Hi - I need to know exactly which OpenCV DLL's need to be deployed for 64-bit OpenCVSharp to run. OpenCV DLL's come in 3 different naming conventions depending on how OpenCV was built, and I'm not seeing any clue as to which family I need to deploy with an OpenCVSharp application.

Some OpenCV builds bag everything into a "world" DLL (e.g. opencv_world411.dll), some number individual packages (e.g. opencv_core411.dll) and some omit the numbering altogether (e.g. opencv_core.dll). Yes, I've tried Depends.exe - no joy.

Since DLL's are referenced by name, it's vital to know _exactly_ which names OpenCVSharp4.Windows is expecting to find.

All help welcome!

Thanks
Mike

**Comment by MikePelton** [comment]
Am in the happy position of being able to answer my own question. The runtime error I was seeing is NOT to do with missing OpenCV DLL's . The issue is that OpenCVSharp expects to find a sub-folder _beneath the executable folder_ called "dll" - that contains sub-folders called ""x64" and/or "x86" and those contain OpenCVSharpExtern.dll and opencv_videoio_ffmpeg411_64.dll.

Hence if you're writing an installer for code that uses OpenCVSharp, you will need to provide that folder tree beneath your install location (e.g. your executable "c:\program files\Contoso\CoolApp\Blah.exe" must have the tree "dll\x64" beneath it i.e. "c:\program files\Contoso\CoolApp\dll\x64").

I think this is unusual (and I've been doing this for a while!!) so I hope this helps someone else. No implied criticism @shimat - your work saves a lot of people a lot of hassle!

**Comment by shimat** [comment]
OpenCvSharp links static libraries of OpenCV, so no dynamic libraries (`opencv_xxx.dll`) are needed. The native wrapper DLLs (`dll/[x64 or x86]/OpenCvSharpExtern.dll`) contain all OpenCV functions. In general, you only have to be careful that your program can load OpenCvSharpExtern.dll.

(By the way, in .NET Core, the location of OpenCvSharpExtern.dll is different. )
