### ISSUE TITLE
Tesseract version

### ISSUE THREAD

**Issue by mpolicki** [shimat/opencvsharp#762]
What is the version of the Tesseract library that's bundled with OpenCvSharp?

Is there an API that can be used to find out what the version is?

**Comment by shimat** [comment]
I built Tesseract in https://github.com/shimat/VS2015_Tesseract. Its version is 3.05. 
I don't know a Tesseract API to get the Tesseract version. OpenCvSharp does not have an API that returns the Tesseract version.

**Comment by mpolicki** [comment]
Thanks. Hopefully the integrated Tesseract library can be updated to the current version since currently I have to use a separate later-version Tesseract assembly in my project, and I wouldn't be surprised if others did as well.
