### ISSUE TITLE
Why readNetFromModelOptimizer didnt include in last release?

### ISSUE THREAD

**Issue by alexgurenko** [shimat/opencvsharp#764]
Hello, dear Shimat!

Im seen this native method, and net.cs include this too. But CvDnn dont contain ReadNetFromModelOptimizer()

I compiled fork with this method succesfuly. Can you include this methon in next release?

**Comment by shimat** [comment]
Could you please send your fork here as a pull request?

**Comment by alexgurenko** [comment]
@shimat, Sorry for delay (
My fork is local (on my PC). I only added "ReadNetFromModelOptimizer" method to CvDnn.cs. Net.cs already have this method.

But now i think this is not good idea, because need recompiling solution with special version OpenCV (this version is included in the OpenVino Toolkit). And, when I compiled this, I had a lot of trouble.
More useful way is creating special wrapper for OpenVino
