### ISSUE TITLE
RTSP disconnect detection

### ISSUE THREAD

**Issue by MartinUhliar** [shimat/opencvsharp#766]
# Summary of issue

Hi there,
I have connected a camera with RTSP protocol. I can open RTSP stream and detect when camera is ready but there is a problem when camera is disconnected. Instead of returning false, in case of losing connection, VideoCapture.Read function always returns true. The issue is not in the OpenCV itself because the same issue is not present when using python wrapper around opencv

# Environment

Windows 10 64bit

## Example code:

```
VideoCapture capture = new VideoCapture(0);

while (true)
{
    var frame = new Mat();
    bool hasFrame = capture.Read(frame);

    if (!hasFrame)
    {
        break;
    }

    Cv2.ImShow("Frame", frame);
    Cv2.WaitKey(5);
}
```

**Comment by JadeYew** [comment]
The same thing happens when VideoCapture comes to the end of a video. Read() is still returning true, while saving an empty Mat.
