### ISSUE TITLE
At Mat objects Pyrup calls Cv2.Pyrdown

### ISSUE THREAD

**Issue by peashan** [shimat/opencvsharp#77]
When i use the Pyrup method of a Mat object, it calls the Cv2.Pyrdown method.

The problem is in the /src/OpenCvSharp.CPlusPlus/modules/core/Mat/Mat_CvMethods.cs file at the 1756 line.

**Comment by shimat** [comment]
it's a terrible bug... thank you! :+1: 

https://github.com/shimat/opencvsharp/commit/3728f5314a6e1f8eba432fa1614c6d5c8f7013b0
