### ISSUE TITLE
Mat.T() and Mat * operator errors

### ISSUE THREAD

**Issue by claudeHasler** [shimat/opencvsharp#775]
# Summary of your issue
Either I am doing something wrong or the .T() transpose method for Mat is not working correctly.
I tried to transpose a 3x1 Mat to a 1x3 Mat and received garbage instead.

A similar effect was observed when using the * multiplication operator.
# Environment
C# Visual Studio 2019, OpenCvSharp4.4.1.1.20191110

# What did you do when you faced the problem?

```
            Mat mat = new Mat(3, 1, MatType.CV_32F);
            mat.Set<float>(0, 1.0f);
            mat.Set<float>(1, 2.0f);
            mat.Set<float>(2, 3.0f);

            Mat trans = mat.T().Clone();
            Console.WriteLine($"{trans.Get<float>(0)},  {trans.Get<float>(1)} ,{trans.Get<float>(2)}");
```

## Output:

```
1 , 0 , 0
```

## Expected

```
1, 2 , 3
```

**Comment by NilesDavis** [comment]
Hi @claudeHasler . I think you misunderstood the Get-method. The integer parameter represents "the index along the 0 dimension" which means the rows. After transposing the matrix the 0 dimension just has an entry at the first position, leading to the result you pasted.
Use an array instead to get the full 2D output:
`float[,] testmatout = new float[mat.Height, mat.Width];`
`mat.GetArray(0, 0, testmatout);`
If you have that full information, you should also be able to use the multiplication operator correctly.
Give it a try
