### ISSUE TITLE
Provide symbol files for OpenCvSharpExtern

### ISSUE THREAD

**Issue by sharwell** [shimat/opencvsharp#776]
# Summary of your issue

I'm interested in seeing symbols for OpenCvSharpExtern.dll when viewing performance traces in PerfView. Currently the frames only show the module name and addresses. It would be helpful if the symbol files were provided either through a symbol server, embedded in the NuGet package, and/or attached to the artifacts for GitHub releases.

# Environment

Windows x64

**Comment by sharwell** [comment]
❤️

**Comment by sharwell** [comment]
Hi @shimat ,

I noticed that the package attached to [release 4.5.2](https://github.com/shimat/opencvsharp/releases/tag/4.5.2.20210404) contains symbols, but the package published to NuGet.org isn't showing them. Can you double check that the snupkg files are getting uploaded to NuGet when you push the runtime package?

**Comment by shimat** [comment]
Sorry but I've given up on releasing the NuGet package including OpenCvSharpExtern.pdb for the reason #992.

**Comment by sharwell** [comment]
@shimat it looks like there was a packaging error. The build should produce both a .nupkg and a .snupkg. Application dependencies are determined by the .nupkg, and the PDB file(s) are only part of the .snupkg.

**Comment by nietras** [comment]
I'd very much like this too for the same reason. Namely profiling. 👍

**Comment by tamirs9876** [comment]
Hi @shimat,

I'm using perfview for profiling (like @sharwell) and found that repo Releases page contains the pdb for opencvsharpextern.dll

version: `4.5.3.20211228`
nuget: https://www.nuget.org/packages/OpenCvSharp4.runtime.win/4.5.3.20211228
repo asset: https://github.com/shimat/opencvsharp/releases/tag/4.5.3.20211228

I couldn't use the repo asset opencvsharpextern.pdb to load symbols. perfview complains their GUIDs aren't match:
`FindSymbolFilePath: ************ FOUND PDB File C:\[my-local-symbol-path]\OpenCvSharpExtern.pdb has Guid 76684e72-d334-49c2-b743-a0288daa5226 age 1 != Desired Guid 48c08bd7-87d0-44c3-af69-b1e2ff174147 age 1
`
GUID `76684e72-d334-49c2-b743-a0288daa5226` is what's in the repo asset releases.
GUID `48c08bd7-87d0-44c3-af69-b1e2ff174147` is from the nuget package.

checking with dumpbin (`dumpbin /headers OpenCvSharpExtern.dll`) I see there are differences:
![image](https://user-images.githubusercontent.com/1193896/210323441-7b7b9d59-3b00-4a2f-92ac-9a4fa7b9065a.png)
![image](https://user-images.githubusercontent.com/1193896/210323486-c4a7a23f-f830-4482-ae14-a030a04c310f.png)

any chance this isn't the same dll even though the version matches?
