### ISSUE TITLE
unable to load OpenCvSharpExtern

### ISSUE THREAD

**Issue by gabeking** [shimat/opencvsharp#777]
# Summary of your issue

Exception is thrown trying to execute

`OutputArray image = new Mat();`

exception:

"The type initializer for 'OpenCvSharp.Mat' threw an exception"

inner exception:

 {"Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

# Environment

Windows 10 x64

# What did you do when you faced the problem?

attempted reinstalling package, switching between OpenCvSharp4 + OpenCvSharp4.runtime.win and OpenCvSharp4.Windows, restarting visual studio, downgrading to OpenCvSharp3, and downloading OpenCvSharpExtern.dll from release page and manually adding to bin folder

**Comment by titovmaxim** [comment]
It is similar to #753 which was closed, but the problem stil exists. I did not understand (from comments to #753) where one should include <Import Project...). I've done it manually pointing to .nuget directory. Still no succes.

My .csproj file contains just:
  <ItemGroup>
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.1.1.20191110" />
  </ItemGroup>

It works for OpenCvSharp3, but not for OpenCvSharp4.

**Comment by shimat** [comment]
Please check dependencies of the OpenCvSharpEntern.dll using DependencyWalker or other tools. Are there any DLL missing references?

**Comment by titovmaxim** [comment]
The problem appears when OpenCvSharp4.Windows is installed by NuGet to the (our own) Library (netstandard2.0). The appropriate .dll files are not copied to output directory. As well as there is not dll directory in the project.

If I additionally add OpenCvSharp4.Windows to the main app which uses this library everything works. Also dll directory appears in the project.

There were no problems with OpenCvSharp3 release, it was added just to th elib which use it.

**Comment by titovmaxim** [comment]
Beg a pardon, that was my fault. I've added OpenCvSharp4.Windows to Netstardard2.0 library, which is then used by the main app. In this case I guess windows dll files are not copied to the output dir. If I add separatelly OpenCvSharp4 to the lib and runtime.win to the head app everything works.

Pitty that with OpenCvSharp3 it works just by adding reference to the lib. Nothing had to be added to the app.

**Comment by shimat** [comment]
The behavior may be the NuGet specification.
In OpenCvSharp3, the native DLL files are copied by the msbuild script instead of NuGet.
