### ISSUE TITLE
windows XP  The  type  initializer  for  'OpenCvSharp.Mat'  threw  an  exception.  --->  System.TypeInitializationException:  The  type  initializer  for  'OpenCvSharp.NativeMethods'  threw  an  exception  System.DllNotFoundException:  Unable  to  load  DLL  'OpenCvSharpExtern':

### ISSUE THREAD

**Issue by cdyfly** [shimat/opencvsharp#778]
I'm build it with the v141_xp platform for vs2017 ,4.1.1
using DependencyWalker tools Prompt error message:
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

**Comment by cdyfly** [comment]
提示错误消息

**Comment by cdyfly** [comment]
@sebtoun nuget which version supports Windows XP system

**Comment by shimat** [comment]
Which DLL files are missing, according to DependencyWalker?
Sorry I don't know which version supports WindowsXP. I’ve never developed and used OpenCvSharp in WindowsXP.

**Comment by a312586670** [comment]
> I'm build it with the v141_xp platform for vs2017 ,4.1.1
> using DependencyWalker tools Prompt error message:
> Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
> Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module. @shimat

Have you solved the support issues on xp

**Comment by a312586670** [comment]
> > I'm build it with the v141_xp platform for vs2017 ,4.1.1
> > using DependencyWalker tools Prompt error message:
> > Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
> > Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module. @shimat
> 
> Have you solved the support issues on xp

Have you solved the support issues on xp? @cdyfly
