### ISSUE TITLE
Cv. versus Cv2. ?

### ISSUE THREAD

**Issue by tbreina** [shimat/opencvsharp#78]
What is the difference between the Cv. functions and the Cv2. functions?

**Comment by shimat** [comment]
The Cv class is a wrapper of the **C** language interface of OpenCV. The Cv2 is a wrapper of the **C++** language interface of OpenCV. Cv is deprecated. Cv2 may be easier to use than Cv.

**Comment by tbreina** [comment]
Thanks. That's helpful.

So I should use Cv2 as much as possible.

Tony
