### ISSUE TITLE
How does knn number recognition work? Is there an example?

### ISSUE THREAD

**Issue by a312586670** [shimat/opencvsharp#780]
How does knn number recognition work? Is there an example?

**Comment by kimkanghyune** [comment]
Here's a good example dude

[https://github.com/VahidN/OpenCVSharp-Samples](url)

**Comment by a312586670** [comment]
> Here's a good example dude
> 
> [https://github.com/VahidN/OpenCVSharp-Samples](url)

Is there an example of the use of opencvsharep 2.4.1 (https://github.com/shimat/opencvsharp_2410/) version of knn ocr, the gap between the two you posted is still quite large

**Comment by shimat** [comment]
Old OpenCvSharp code samples: https://github.com/shimat/opencvsharp_2410/tree/master/sample

**Comment by a312586670** [comment]
> Old OpenCvSharp code samples: https://github.com/shimat/opencvsharp_2410/tree/master/sample

No KNearest example，Does KNN support OCR?

**Comment by shimat** [comment]
Probably not. I look forward to your pull request or other contributions.
