### ISSUE TITLE
VideoWriter with ApiPreferences

### ISSUE THREAD

**Issue by meriturva** [shimat/opencvsharp#781]
Is it possible to have the support of the constructor parameter `ApiPreferences` of VideoWriter as described here:

https://docs.opencv.org/4.1.1/dd/d9e/classcv_1_1VideoWriter.html#af52d129e2430c0287654e7d24e3bbcdc

We have checked on file: https://github.com/shimat/opencvsharp/blob/a0d61065240eada9706fb2df2bf7ea5ce8f599d7/src/OpenCvSharp/PInvoke/NativeMethods_videoio.cs#L64

and there is no import about it.

Secondly, we just would like to use Intel Media SDK on our writer and we would like to ask any advice on how to integrate OpenCV library on it. We have to compile it for sure as described here: https://github.com/opencv/opencv/wiki/MediaSDK-encode-decode-backend

But how to integrate easly on OpenCvSharp new version self compile?

So thanks.

**Comment by shimat** [comment]
Thanks. The `apiPreferences` parameter was supported by #758.

OpenCvSharp's native bindings are based on pre-built OpenCV binaries located at:
https://github.com/shimat/opencv_files_411/tree/bb8b812299f959b212a3945a93d9df2aef3a91e4

You can customize the functionality of OpenCvSharp by replacing this with your own built OpenCV binaries and rebuilding OpenCvSharpExtern.

CMakeVars_*.txt are helpful for cmake settings.
https://github.com/shimat/opencv_files_411/blob/bb8b812299f959b212a3945a93d9df2aef3a91e4/windows/CMakeVars_x64.txt
