### ISSUE TITLE
Buffer Pool and ToBytes / ImEncode

### ISSUE THREAD

**Issue by turowicz** [shimat/opencvsharp#784]
Is it possible to make use of a buffer pooling technique for converting `Mat`s to `byte[]`? I'm processing a large amount of video frames and feed it to `TensorFlow`. Currently I have this ugly intermediate step that makes the conversion so that `TensorFlow` can create an input object.

**Comment by turowicz** [comment]
cc @shimat maybe you know what's the best approach to this

**Comment by shimat** [comment]
I don't have a good answer, but one thing we can do is use and keep one vector to encode.
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Cv2/Cv2_imgcodecs.cs#L193

To do this, it is needed to wrap `std::vector.clear()`.

```c#
using var buffer = new VectorOfByte();

while (true)
{
    using Mat mat = GetFrame();

    NativeMethods.imgcodecs_imencode_vector(ext, img.CvPtr, buffer.CvPtr, prms, prms.Length);

    byte[] encodedBytes = buffer.ToArray();

    buffer.Clear(); // not implemented
}
```

**Comment by turowicz** [comment]
`buffer.ToArray()` won't this allocate a new array though?

**Comment by shimat** [comment]
Ah ... `VectorOfT.ToArray` allocates memory each time, so we have to use ArrayPool.
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Vector/VectorOfByte.cs#L90

This is a pseudocode:
```c#
var pool = System.Buffers.ArrayPool<byte>.Shared;

using Mat frame = GetFrame();

// Call cv::imencode
using var bufferVec = new VectorOfByte();
NativeMethods.imgcodecs_imencode_vector(".png", frame.CvPtr, bufferVec.CvPtr, null, 0);

// vector<uchar>  =>  byte[]
byte[] bufferArray = pool.Rent(bufferVec.Size);
try
{
    Marshal.Copy(bufferVec.ElemPtr, bufferArray, 0, bufferArray.Length);

    // Use bufferArray 
}
finally
{
    pool.Return(bufferArray);
}
```

**Comment by turowicz** [comment]
Thank you @shimat !
