### ISSUE TITLE
How can I modify properties of `KalmanFilter`

### ISSUE THREAD

**Issue by Ursanon** [shimat/opencvsharp#786]
# Summary of your issue
`KalmanFilter` contains only getters (which returns new `Mat` each call) to all properties ex. `TransitionMatrix` or `ProcessNoiseCov`.

How can I modify those properties?

# Environment

Ubuntu 18.04.3 LTS

## Example code:

```
kalman.TransitionMatrix = new Mat(2, 2, MatType.CV_8U, new double[,]
{
    {1, 1},
    {0, 1}
});
```

## What did you intend to be?

I should be able to set state of filter.

Complete example of setting filter's state:
https://docs.opencv.org/trunk/de/d70/samples_2cpp_2kalman_8cpp-example.html#a12

In OpenCV all matrices are public.
https://github.com/opencv/opencv/blob/master/modules/video/include/opencv2/video/tracking.hpp#L360

**Comment by Ursanon** [comment]
@shimat

**Comment by shimat** [comment]
Could you try this?
```c#
// (double array is not supported in CV_8U Mat. )
using var mat = new Mat(2, 2, MatType.CV_64F, new double[,]
{
    {1, 1},
    {0, 1}
});
using var transitionMatrix = kalman.TransitionMatrix;
mat.AssignTo(transitionMatrix);
```

**Comment by Ursanon** [comment]
I tried this, and unfortunately it didn't work.

`TransitionMatrix` property returns new `Mat` each call.
`AssignTo()` will work on (new) instance under `transitionMatrix` variable, not on instance inside `KalmanFilter`.

Simple test:
```
[Test]
public void Should_SetNew_TransitionMatrix()
{
    var kalman = new KalmanFilter();
    var mat = new Mat(2, 2, MatType.CV_8U, new byte[,]
    {
        { 1, 1 },
        { 0, 1 }
    });

    var transitionMatrix = kalman.TransitionMatrix;
    mat.AssignTo(transitionMatrix);
    var equalData = IsDataEqual(kalman.TransitionMatrix, mat);

    Assert.IsTrue(equalData);
}

// fast/naive impl
private static bool IsDataEqual(Mat lhs, Mat rhs)
{
    if (lhs.Size() != rhs.Size())
    {
        return false;
    }

    var diff = lhs - rhs;

    return Cv2.Sum(diff) == Scalar.Black;
}
```

**Comment by Ursanon** [comment]
I think problem may cause extern function inside `video_tracking.h`:

```
CVAPI(cv::Mat*) video_KalmanFilter_transitionMatrix(cv::KalmanFilter *obj)
{
    return new cv::Mat(obj->transitionMatrix);
}
``` 

due to openCV's `Mat` ctor, data pointer `uchar* data` will be copied (it's not **).
In our case, `TransitionMatrix`'s data pointer equals `nullptr`.

**Comment by shimat** [comment]
Thank you. I am trying to fix this by #802 .

**Comment by turowicz** [comment]
Thanks for fixing this @shimat!

**Comment by Ursanon** [comment]
Thanks for your time @shimat.

Unfortunately, problem still exists #803
