### ISSUE TITLE
Recorded video length is lesser than actual video recording time.

### ISSUE THREAD

**Issue by nrajasekar7** [shimat/opencvsharp#789]
Hi @marek-stoj @yukoba @tekezo @pimms @joreg @shimat 
# Summary of your issue
Recorded video file is less time than actual recording
# Environment
C# .Net , Windows 10
# Issue
I have OpenCVSharp3 with OpenH264 dll and tried to record the video using the camera and save the file using c#.
when i opened the saved recorded file using VLC or some other video player, the video length is lesser than the actual video recording.

Thanks in Advance,
Rajasekar

**Comment by shimat** [comment]
Could you show me your code snippet? I suspect the `fps` parameter of VideoWriter.

**Comment by nrajasekar7** [comment]
@shimat 

Thank you for the prompt response. 

I am using FPS as 30.

and there is no proper end to end documentation for saving the video capture into the file. could you please let me know any documents.

Thanks,
Rajasekar

**Comment by shimat** [comment]
Please refer to the code samples. https://github.com/shimat/opencvsharp_samples/blob/master/SamplesCS/Samples/VideoWriterSample.cs#L21

**Comment by nrajasekar7** [comment]
Hi @shimat 

Thank you for the link,

I created the sample application with the shared code. but i need to learn more about the VideoCapture APIs. but i can see only the syntax. no description about the methods and use of the methods.

I could not decide, which should i use. for example Read or RetriveMat??

Thanks in Advance,
Rajasekar

**Comment by shimat** [comment]
The usage of opencvsharp is very similar to that of native OpenCV (C++). See the many OpenCV samples and documents on the Web.
You can use either ReadMat or Mat. But VideoCapture may not be necessary for your use case. 
I can't comment because I don't know the details of your application. The code I shared is just sample. 

If necessary, please resubmit an issue with a code snippet that reproduces the problem.

**Comment by nrajasekar7** [comment]
@shimat 

Thank you for the reply.

I have final clarification. 
Is there any relationship between the Height and Width with FPS?

in my application
I have set the 
FPS as 30 and
**Resolution:**
 Width = 640
Height = 480;

the output saved video seems 90% Okay.

but when  i set the resolution as below
Width = 1280;
Height = 720;

the video file length is 3 times lesser than the original video.
for example, if i record the video for 3 minutes, but the video file has only 1 minute length.

Please help me on this.

Thanks,
Rajasekar
