### ISSUE TITLE
Rodrigues throws NativeMethods Exception

### ISSUE THREAD

**Issue by 159199** [shimat/opencvsharp#790]
# Summary of your issue
When I use [Rodrigues](https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Cv2/Cv2_calib3d.cs) method with `array` arguments as

```
Rodrigues(double[,] matrix, out double[] vector);
```

it throws **"Input argument is not a valid matrix"**, which comes from [calibration.cpp](https://github.com/opencv/opencv/blob/master/modules/calib3d/src/calibration.cpp) in opencv ->

```
if( !CV_IS_MAT(src) )
        CV_Error( !src ? CV_StsNullPtr : CV_StsBadArg, "Input argument is not a valid matrix" );
```

I could not find `CV_IS_MAT` body, but I tried method's Input/OutputArray equivalent with the same `Mat` initializing (`MatType`, size, data) for input mat, output vector and even jacobian - and it works.

The whole thing

```
//This works
using (var rMat = new Mat(3, 3, MatType.CV_64FC1, rArray))
using (var rodrigues = new Mat<double>())
using (var jacobianM = new Mat<double>())
{
       Cv2.Rodrigues(rMat, rodrigues, jacobianM);
}
//This throws mentioned exception
Cv2.Rodrigues(rArray, out var rodrigues);
```

where rArray is the same - 3×3 2d double array.
# Environment

I am using OpenCvSharp4.Windows NuGet, version 4.1.1.20191110.

**Comment by shimat** [comment]
In the latest version, I tested Rodrigues with array arguments and it was successful. https://github.com/shimat/opencvsharp/pull/810
Please try using 4.1.1.20191216 version.
