### ISSUE TITLE
BitmapConverter turns image to black

### ISSUE THREAD

**Issue by mridah** [shimat/opencvsharp#791]
using  OpenCVSharp4 
on Windows 10, 64-bit

I have the following code:

    Bitmap bitmap = (Bitmap)pbSource.Image;
    var gray = BitmapConverter.ToMat(bitmap);
    Bitmap bitmapDst = BitmapConverter.ToBitmap(gray);
    pbDest.Image = bitmapDst;

![image](https://user-images.githubusercontent.com/21169606/70803336-d365e300-1dd9-11ea-829e-927c8b784416.png)

Here is the actual image I'm using for reference:

![f5](https://user-images.githubusercontent.com/21169606/70803482-2f306c00-1dda-11ea-82c5-40355493dd5f.png)

What might be causing this problem ??

**Comment by shimat** [comment]
Thank you :+1: I'm trying to fix this by #811.
If the input bitmap's PixelFormat is Format8bppIndexed, BitmapConverter.ToMat() do not use ColorPalette.
