### ISSUE TITLE
Getting Call Stack

### ISSUE THREAD

**Issue by turowicz** [shimat/opencvsharp#794]
I get random crashes with the message:

```
terminate called after throwing an instance of 'cv::Exception'
OpenCV(3.4.8-dev) /tmp/cv/opencv/modules/core/src/arithm.cpp:663: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
```

The problem is that my codebase is quite large and I would like to see any kind of stacktrace in order to be able to find the culprit.

Is it possible to have OpenCvSharp raise a .NET exception when an extern method fails?

cc @shimat

**Comment by shimat** [comment]
Is your environment Linux? On Linux, there was a problem with the process crashing when cv::Exception was thrown.

This is fixed by https://github.com/shimat/opencvsharp/pull/758.

https://github.com/shimat/opencvsharp/pull/523
https://github.com/shimat/opencvsharp/issues/517

**Comment by turowicz** [comment]
Hey @shimat thank you for your reply. We have identified the problem in our code. I think the Linux Exception redirection fix will be the resolution for this issue.

Cheers!
