### ISSUE TITLE
Mat.FromStream `OpenCVException "!buf.empty()"` in 4.1.1.20191216

### ISSUE THREAD

**Issue by Exekyel** [shimat/opencvsharp#800]
# Summary of your issue
I upgraded OpenCVSharp4.Windows from 4.1.1.20191110 to 4.1.1.20191216 today and encountered a breaking change in `Mat.FromStream(Stream, ImReadModes)`

# Environment

Windows 10 Enterprise 64 bit
Visual Studio Professional 2019
Targeting .Net Framework 4.5.1
Minimal reproduction in LinqPad 5.40.00

# What did you do when you faced the problem?

1. tried rolling back to 4.1.1.20191110
2. tried reproducing in LinqPad
3. found issue is solved by setting `Stream.Position = 0`

## Example code:

``` csharp
using (var ms = new System.IO.MemoryStream(new byte[1]))
{
	ms.Seek(0, System.IO.SeekOrigin.End);

	using (OpenCvSharp.Mat.FromStream(ms, OpenCvSharp.ImreadModes.Unchanged)){}
}
```

## Output:

```
OpenCVException "!buf.empty()"
```

## What did you intend to be?
In the previous version (4.1.1.20191110), the Mat was created without error and without seeking the stream. This may have only been due to a bug in that version. However, seeing as `Mat.FromStream(Stream, ImReadModes)` requires a stream with `CanSeek = true`, I assume that the seek operation is intended to be executed internally? I am posting mainly in case other users encounter this issue, as I have found working solution.

**Comment by shimat** [comment]
Thank you for your report. In previous versions, FromStream run Seek(0) and then read bytes by Read(). In the current version, it uses CopyTo instead of Seek and Read. 
https://github.com/shimat/opencvsharp/blob/76d84f9836464644b247db32645409f79485f5fe/src/OpenCvSharp/Modules/core/Mat/Mat.cs#L658

As you indicate, old FromStream expects Stream.CanSeek = True. Some Stream classes may not permit CanSeek = True. So, I decide that the new behavior is by design. I'm sorry to confuse you.

**Comment by Exekyel** [comment]
I am glad that you linked to the source code, because I learned from it. My application is slightly more complicated than my posted example, in fact I am already copying into a memory stream because of the restriction on `CanSeek`:
``` csharp
using (Stream stream = webResponse.GetResponseStream()) // does not support seeking
using (MemoryStream mStream = new MemoryStream())
{
    stream.CopyTo(mStream);
    mStream.Position = 0;

    using (Mat image = Mat.FromStream(mStream, ImreadModes.Unchanged))
```
But now I see that I can just call `Mat.FromImageData(byte[], ImReadModes)`:
``` csharp
using (Stream stream = response.GetResponseStream())
using (MemoryStream mStream = new MemoryStream())
{
    stream.CopyTo(mStream);

    using (Mat image = Mat.FromImageData(mStream.ToArray(), ImreadModes.Unchanged))
```
Thank you for the quick response, and thank you for developing OpenCVSharp!
