### ISSUE TITLE
`Kalman Filter`'s properties don't work correctly

### ISSUE THREAD

**Issue by Ursanon** [shimat/opencvsharp#803]
# Summary

All tests for `KalmanFilter` fails.   

Getter still returns brand new instance each call. 

Related issues: #786 #802 

# Environment

Ubuntu: 18.04.3 LTS

## Output:

```
  X OpenCvSharp.Tests.Video.KalmanTest.TransitionMatrix [< 1ms]
  Error Message:
   Assert.Equal() Failure
Expected: (width:2 height:2)
Actual:   (width:0 height:0)
  Stack Trace:
     at OpenCvSharp.Tests.Video.KalmanTest.IsDataEqual(Mat lhs, Mat rhs) in /workspaces/opencvsharp/test/OpenCvSharp.Tests/video/KalmanTest.cs:line 179
   at OpenCvSharp.Tests.Video.KalmanTest.TransitionMatrix() in /workspaces/opencvsharp/test/OpenCvSharp.Tests/video/KalmanTest.cs:line 55

[xUnit.net 00:01:40.52]     OpenCvSharp.Tests.Video.KalmanTest.TransitionMatrix [FAIL]
```

**Comment by shimat** [comment]
The tests passed in my environment and the CI environments (Windows by AppVeyor and Ubuntu by CircleCI). Did you rebuild the OpenCvSharpEntern (C++ lib)?

**Comment by Ursanon** [comment]
Thanks for answer, yeah, OpenCvSharpEntern was rebuilt.
> The tests were successful in my environment and the CI environments

Will dig deeper tomorrow then

**Comment by turowicz** [comment]
⛏

**Comment by Ursanon** [comment]
Another rebuild solved this problem.
Thanks for help.
