### ISSUE TITLE
ImRead get Mat of zero rows and zero columns

### ISSUE THREAD

**Issue by hjy1210** [shimat/opencvsharp#804]
# Summary of your issue
I have an image file barcode.jpg.
I use the statement

> Mat mat = Cv2.ImRead(@"barcode.jpg", ImreadModes.Grayscale);

and get mat with zero rows.

The image file barcode.jpg, with 206 rows 500 columns,  can be inspected corrected by double clicked it in windows explorer.
[barcode.jpg](https://drive.google.com/open?id=12wVEr7IYeZnTYa5DB3JFzvEJpaoYnKs9)

![barcode](https://user-images.githubusercontent.com/7498709/71194278-9a8ca900-22c6-11ea-878f-b1c41e449110.jpg)
.

# Environment

Windows 10, OpenCVSharp4.Windows

# What did you do when you faced the problem?

//write here

## Example code:

```
		static void Main(string[] args)
		{
			Mat mat = Cv2.ImRead(@"d:\downloads\barcodes\barcode.jpg", ImreadModes.Grayscale);
			Console.WriteLine($"barcode.jpg : Rows={mat.Rows}, Cols={mat.Cols}");
			mat = Cv2.ImRead(@"d:\downloads\barcodes\barcode.png", ImreadModes.Grayscale);
			Console.WriteLine($"barcode.png : Rows={mat.Rows}, Cols={mat.Cols}");
		}
```

## Output:

```
barcode.jpg : Rows=0, Cols=0
barcode.png : Rows=206, Cols=500
```

## What did you intend to be?
Is this is a bug in OpenCVSharp or my barcode.jpg is not of correct format?

**Comment by shimat** [comment]
The barcode.jpg seems not to be JPEG. The file extension is JPEG, but the image header is GIF. 

And OpenCV doesn't seem to have a built-in GIF codec.

**Comment by hjy1210** [comment]
@shimat 
Thanks a lot for your information.
