### ISSUE TITLE
ExecutionEngineException upon accessing Mat element in a thread

### ISSUE THREAD

**Issue by Misiakufal** [shimat/opencvsharp#808]
# Summary of your issue
I have encounter a similar issue to https://github.com/shimat/opencvsharp/issues/726
I am trying to run DNN face detection algorithm in a thread. If I use algorithm in the UI Thread, it works just fine. However any attempt to put it in a thread results in an exception System.ExecutionEngineException upon accessing a Mat element. What is interesting - it only happens for a certain Mat variable, when I try to access other's Mat element, it works fine even inside a thread. There is no problem with Mat boundaries. 

# Environment

Win 10, Visual studio 2017, .NET Standard 2.0

## Example code:

```c#
string modelFile = "Classifiers\\opencv_face_detector_uint8.pb";
string configFile = "Classifiers\\opencv_face_detector.pbtxt";

Net _net = CvDnn.ReadNetFromTensorflow(modelFile, configFile);

Mat frame = new Mat(path_to_jpeg_file);
Mat frameResized = new Mat();
Cv2.Resize(frame, frameResized, new Size(300, 300));
Mat blob = CvDnn.BlobFromImage(frameResized, 1.0, new Size(300, 300), new Scalar(104, 177, 123));
_net.SetInput(blob, "data");
Mat results = _net.Forward("detection_out");
Mat resultMat = new Mat(results.Size(2), results.Size(3), MatType.CV_32F, results.Ptr());

double confidence = resultMat.At<float>(0, 2);

```

## Output:
```
When trying to access `resultMat` element in the last line of code, an exception System.ExecutionEngineException is being thrown.

```

## What did you intend to be?

All I want this christmas is no exception System.ExecutionEngineException being thrown ;)

**Comment by shimat** [comment]
:thinking: 

The `result` may have been disposed before retrieving a value from the `resultMat`. If `result` is disposed by .NET GC, `result.Ptr()` becomes invalid.
Please try using `using` statement or using GC.KeepAlive to specify the lifetime of Mat.
```c#
// All Mats and Nets above should be also wrapped with using
using (Mat results = _net.Forward("detection_out"))
using (Mat resultMat = new Mat(results.Size(2), results.Size(3), MatType.CV_32F, results.Ptr()))
{
    double confidence = resultMat.At<float>(0, 2);
}
```

**Comment by Misiakufal** [comment]
Happy New Year!

Unfortunately your soultion does not work either, I am receiving the same exception as before.
