### ISSUE TITLE
can support debian9 runtime package?like OpenCvSharp4.runtime.debian9

### ISSUE THREAD

**Issue by lxiaofei** [shimat/opencvsharp#815]
# Summary of your issue
 I'm using Docker with dotnetcore2.0/2.1.Everything works fine on Windows, but not using dotnetcore Docker.we have try use libOpenCvSharpExtern.so file from 'https://github.com/toanlcgift/RPISpiderRobot/blob/master/LiveStreamServer/LiveStreamServer/libOpenCvSharpExtern.so' and copy to lib folder.
# Environment
.NET Core 2.0
Visual Studio 2019
Docker 2.0.0.3 (31259)
Image:microsoft/aspnetcore:2.0(Debian9)

# What did you do when you faced the problem?
when wen use docker run the application,still has error.
## Example code:

 var srcImage = new Mat(@"Images/Test3.jpg");
                Cv2.ImShow("Source", srcImage);
                Cv2.WaitKey(1); // do events

                var grayImage = new Mat();
                Cv2.CvtColor(srcImage, grayImage, ColorConversionCodes.BGRA2GRAY);
                Cv2.EqualizeHist(grayImage, grayImage);

                var cascade = new CascadeClassifier(@"Data\haarcascade_frontalface_alt.xml");
                var nestedCascade = new CascadeClassifier(@"Data\haarcascade_eye_tree_eyeglasses.xml");

                var faces = cascade.DetectMultiScale(
                    image: grayImage,
                    scaleFactor: 1.1,
                    minNeighbors: 2,
                    flags: HaarDetectionType.DoRoughSearch | HaarDetectionType.ScaleImage,
                    minSize: new OpenCvSharp.Size(30, 30)
                    );

## Output:
DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory

## What did you intend to be?
can support debian9 runtime package? like 'OpenCvSharp4.runtime.ubuntu.18.04-x64','OpenCvSharp4.runtime.centos7'

**Comment by shimat** [comment]
I use 3 CIs for OpenCvSharp to support Windows, UWP, Ubuntu 16 (for AppEngine), and Ubuntu 18. It's the limit of my effort.

To make it work with Debian 9, it is recommended that you check the dependencies of the libOpenCvSharpExtern.so using `ldd` command.

**Comment by lxiaofei** [comment]
i see,thank u very much!
