### ISSUE TITLE
BiamapConverter.ToMat() gives AccessViolationException

### ISSUE THREAD

**Issue by mridah** [shimat/opencvsharp#821]
# Summary of your issue

I just updated the library version from 4.1 to 4.2 and the existing code started giving me this error on running.

# Environment

Windows 10 64 bit
8 GB ram

# What did you do when you faced the problem?

Updated from version 4.1 to 4.2

## Example code:

```
Bitmap source = (Bitmap)pbSource.Image;
Mat mSource = BitmapConverter.ToMat(source);
```

## Output:

```
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

```

Has anything changed? @shimat

**Comment by shimat** [comment]
ToMat was changed by https://github.com/shimat/opencvsharp/pull/811/ 

Please tell me more about your image. (for example, what is the value of pbSource.Image.PixelFormat?)

**Comment by mridah** [comment]
Thanks for the fast reply. The PixelFormat is `Format32bppRgb`, Height is `287px`, and Width is `382px`

![Plier1](https://user-images.githubusercontent.com/21169606/71545104-19f83780-29ad-11ea-9a70-b1a341763393.jpg)

**Comment by shimat** [comment]
Thank you for the information. I tried testing ToMat using your image, but it worked (#822 ) . 
I don't know the cause :thinking: 

pbSource.Image is disposed?
