### ISSUE TITLE
OpenCvSharp3-AnyCPU in C# DrawCountours working very slow for large image size(More Contours)

### ISSUE THREAD

**Issue by alpesh-einfochips** [shimat/opencvsharp#829]
I am using DrawCounrers method using OpencvSharp-AnyCPU  package, but it's working  very slow for draw more number of contour.

I am using Window 10 system, with  OpencvSharp-AnyCPU  package.

**## Example code:**

 OpenCvSharp.Point[][] contours;
 HierarchyIndex[] hierarchy;
 Cv2.FindContours(f6.Clone(), out contours, out hierarchy, RetrievalModes.List, ContourApproximationModes.ApproxSimple);
int counterIndex = 0;
 foreach (OpenCvSharp.Point[] contour in contours)
 {
       double area = Cv2.ContourArea(contour);
       if (area <= 200)
       {
             Cv2.DrawContours(mask, contours, counterIndex, - 1, -1);
       }
       counterIndex++;
 }

**## Output:**
I am not able to draw counters for large image means if more contour want to draw.

**# C++ Working module:**
I was facing same issue in c++ api for DrawCountours but after exploring google below code using working properly:
**c++ Opencv  code for DrawCountours and it is working:**
 cv::findContours( contourOutput, contours, hierarchy, cv::RETR_LIST, cv::CHAIN_APPROX_SIMPLE, cv::Point(0, 0) );

    for (std::vector<cv::Point> contour : contours){
       double area = cv::contourArea(contour);
        if(area <= 200){
            cv::drawContours(mask, std::vector<std::vector<cv::Point> >(1,contour), -1, 0, -1);
        }
    }

This line i think something changes required for faster API:  cv::drawContours(mask, std::vector<std::vector<cv::Point> >(1,contour), -1, 0, -1); //c++ Api

Please give me for c# same way Api for Drawcountours.

**Comment by Exekyel** [comment]
I don't know if this will improve your performance, but the package OpenCvSharp3-AnyCPU is deprecated, use OpenCvSharp4.Windows instead ([source](https://github.com/shimat/opencvsharp/blob/master/README.md#installation))

**Comment by alpesh-einfochips** [comment]
Problem in Cv2.DrawCounter api paramters tunning,
C++ same code with drawcounter works fast and properly:

std::vector<std::vector<cv::Point>> contours;
        std::vector<cv::Vec4i> hierarchy;
        cv::Mat contourOutput = f6.clone();

        cv::findContours( contourOutput, contours, hierarchy, cv::RETR_LIST, cv::CHAIN_APPROX_SIMPLE, cv::Point(0, 0) );

        for (std::vector<cv::Point> contour : contours){
            double area = cv::contourArea(contour);
            if(area <= 200){
                cv::drawContours(mask, std::vector<std::vector<cv::Point> >(1,contour), -1, 0, -1);
            }
        }

**Comment by Exekyel** [comment]
In C# you are passing all contours, contour index, and -1 for the color (I don't know what this is converted to, probably black?)
``` csharp
Cv2.DrawContours(mask, contours, counterIndex, - 1, -1);
```
but in c++ you are passing one contour, -1 for the index (which means draw all contours), and 0 for the color
``` cpp
cv::drawContours(mask, std::vector<std::vectorcv::Point >(1,contour), -1, 0, -1);
```
Try changing your C# to
``` csharp
Cv2.DrawContours(mask, new[] {contour}, -1, 0, -1);
```

**Comment by alpesh-einfochips** [comment]
Thanks for reply, this one working.

________________________________
