### ISSUE TITLE
How do I use it in a Raspbian system

### ISSUE THREAD

**Issue by DivenLee** [shimat/opencvsharp#833]
I found that OpencvSharp supports Windows and ubuntu, but Raspbianh and CentenOS have no instructions.

Is there a plan for future support?

**Comment by shimat** [comment]
> Is there a plan for future support?

Unfortunately, I don't have a plan because I don't need it for my purpose.

If you refer to CI configuration files and Dockerfiles, you can build OpenCvSharp by yourself relatively easily.
https://github.com/shimat/opencvsharp/blob/master/.circleci/config.yml
