### ISSUE TITLE
New Releases have Performance Issues

### ISSUE THREAD

**Issue by janecek1980** [shimat/opencvsharp#834]
Release **1.1.20191217** (both 32/64 bit on Windows 10) and newer causes significant performance drop.

My test performance decreased from _225Hz to 91Hz_. Previous release **1.1.20191110** is still OK.

Profiling seems to point to the _Mat<>_ constructor with shared data - looks like _core_Mat_new8()_ function has been wrapped into BEGIN_WRAP/END_WRAP block, which translates into _try/catch_.

Are there any performance tests in the library to be sure that no other parts are affected? If the performance bottleneck is the try/catch in the native code, is it necessary to have it there given its (supposed) major overhead?

Thanks, J.

**Comment by janecek1980** [comment]
So I found one thing which is most likely the problem - clearly this is missing the **static** modifier:

```
class Mat
{
        private readonly Dictionary<Type, int> dataDimensionMap = new Dictionary<Type, int>
        {... };
        
        private readonly Dictionary<Type, MatType[]> acceptableTypesMap = new Dictionary<Type, MatType[]>
        {...};
}

```

**Comment by shimat** [comment]
Thanks. I will fix the second problem.

> Are there any performance tests in the library to be sure that no other parts are affected?

No. 

> If the performance bottleneck is the try/catch in the native code, is it necessary to have it there given its (supposed) major overhead?

On Windows, BEGIN_WRAP and END_WRAP are not replaced with try/catch. 
On Linux, I have no other way to solve #517 / #523.

**Comment by janecek1980** [comment]
Ok, thanks. J.
