### ISSUE TITLE
question only about .net core OpenCvSharpExtern.DLL

### ISSUE THREAD

**Issue by blaisexen** [shimat/opencvsharp#839]
Does it also runs or acceptable for Mac O.S or Linux?
cause I've managed to run it under Windows 7.
https://github.com/blaisexen/WebFaceDetection

**Comment by Ursanon** [comment]
Yes, you can run it on other platforms.
Take a look at this [OpenCvSharp4.runtime.ubuntu nuget](https://www.nuget.org/packages/OpenCvSharp4.runtime.ubuntu.18.04-x64)

**Comment by blaisexen** [comment]
Hello,
ump and win Only can be found in the NativeLib folder, so what's with that?

**Comment by Ursanon** [comment]
For instruction please refer to [Readme - section for Ubuntu 18.04](https://github.com/shimat/opencvsharp#ubuntu-1804-1)

**Comment by blaisexen** [comment]
runtimes\ubuntu.18.04-x64\native\libOpenCvSharpExtern.so ? with OpencvSharp.DLL?

**Comment by blaisexen** [comment]
you mean libOpenCvSharpExtern.so will call the opencvsharp dlls needed?

**Comment by Ursanon** [comment]
`OpenCvSharp` depends on `OpenCvSharpExtern`.
You have to provide valid `Exter` library for target platform.

**Comment by blaisexen** [comment]
thank you so much for letting us know it can Linux too, but I hope it can Mac soon.
