### ISSUE TITLE
How can i install OpenCVSharp on Mac OS X ?

### ISSUE THREAD

**Issue by zullo91** [shimat/opencvsharp#84]
Can someone help me with a clear and full installation of opencvsharp for unity ? 
Generate the opencvsharp dll or bundle for mac os x ? 
It can be possible ? 
I try to execute the make command but it doesn't work, it report an error at 5 % with 
error in calib3d at line that include <opencv2/opencv>

I had installed OpenCV and cmake. :/

**Comment by jbob182** [comment]
I experienced a similar issue when compiling on linux. Try re-making your opencv to include the non-free portion. You need to disable CUDA/OpenCL to do so. 

For example:

```
cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_OPENCL=OFF -D WITH_CUDA=OFF {REST OF PARAMETERS}
```

**Comment by OdysseusU** [comment]
Hello,
I am sorry to ask you that but I'm getting desperate.
I also tried to build the libraries to work with unity but it doesn't seem to work.

Could someone tell me how I can generate the libraries for Mac osx?

I did a simple cmake and I had this warning (couldn't change the policy) : 
```
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   OpenCvSharpExtern
```

And when I make I'm getting an error at 100% of the build : 
```
Linking CXX shared library libOpenCvSharpExtern.dylib
Undefined symbols for architecture x86_64:
  "CvKNearest::CvKNearest(CvMat const*, CvMat const*, CvMat const*, bool, int)", referenced from:
      _ml_CvKNearest_new2_CvMat in ml.cpp.o
```

I have OpenCV 2.4.10 installed.

**Comment by datomnurdin** [comment]
Is anyone found the solution?

**Comment by architrathi** [comment]
Does anyone have a solution?

**Comment by shimat** [comment]
Sorry but it is difficult to support Unity. Please consider using *OpenCV for Unity* (https://www.assetstore.unity3d.com/en/#!/content/21088).
