### ISSUE TITLE
cascadeClassifier.DetectMultiScale causes winform to hang on close

### ISSUE THREAD

**Issue by simonbuehler** [shimat/opencvsharp#847]
# Summary of your issue
Closing the from doesn't end process
# Environment

win10 anycpu

# What did you do when you faced the problem?

cam capture and face detection test, when commenting out the DetectMultiScale  part below the program ends normal

## Example code:

```
using OpenCvSharp;
using System;
using System.Windows.Forms;

namespace CVTest
{
    public partial class Form1 : Form
    {

        private VideoCapture capture;
        private int key = -1;
        private CascadeClassifier cascadeClassifier;

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            capture = new VideoCapture(0);
            cascadeClassifier = new CascadeClassifier("./model/haarcascade_frontalface_default.xml");

        }

        private void button1_Click(object sender, EventArgs e)
        {
            // Frame image buffer
            using (Mat image = new Mat())
            {
                while (key == -1)
                {
                    capture.Read(image);
                    if (image.Empty())
                        break;

                    // Comment out start
                    Rect[] rects = cascadeClassifier.DetectMultiScale(image, 1.1, 5, HaarDetectionType.ScaleImage, new OpenCvSharp.Size(30, 30));
                    if (rects.Length > 0)
                    {
                        Cv2.Rectangle(image, rects[0], Scalar.Red);
                    }
                    // Comment out end

                    pictureBoxIpl1.ImageIpl = image;
                    Cv2.WaitKey(30);
                }
            }

            capture.Release();
            capture.Dispose();
            cascadeClassifier.IsEnabledDispose = true; 
            cascadeClassifier.Dispose(); // Die , please
        }

        private void button2_Click(object sender, EventArgs e)
        {
            key = 0;
        }
    }
}

```

## Output:

```
Form Closes, process still hangs
```

## What did you intend to be?
Clean up everything

**Comment by simonbuehler** [comment]
@shimat do you have an idea how to debug this ?

**Comment by shimat** [comment]
I made a WinForm app sample with face detection.
https://github.com/shimat/opencvsharp_samples/tree/master/VideoCaptureForm

Capturing process should be performed in a separate thread from UI thread.

**Comment by simonbuehler** [comment]
Hi @shimat ,

thanks for your quick reply, i tested your example  and on one machine its running and closing ok while on another it still hangs, i'm trying to find out the diff and debug using the sources an not the nuget packages, hopefully i find the underlying reason

**Comment by blaisexen** [comment]
@simonbuehler 
are you using 4.2.0 (23 Jan., 2020)?

**Comment by shimat** [comment]
Please try calling `backgroundWorker1.CancelAsync();` in `VideoCaptureForm_FormClosing`.

**Comment by simonbuehler** [comment]
thanks again for your support !

i managed to find the thread that was still hanging: its 

> amdocl64.dll

which is part of an (older) amd graphics driver in my laptops docking station, used by opencl.
so the program hangs when docked and ends when not docked and using intel gpu, i was going crazy ...

closing this as its a driver/opencl issue, at least i learned how to build opencv from ground up ;)

**Comment by blaisexen** [comment]
I doubt it was different, and even more different like you said, lol,
anyway here's my little summary of video capture for windows form, include how to rotate the video,
https://sourceforge.net/projects/face-detection-accord-net-csvb/
https://sourceforge.net/projects/accord-net-rotate-video-camera/

**Comment by simonbuehler** [comment]
@shimat Regarding your sample:
When doing capturing in a own thread (backgroundworker) the UI stays responsive, but the PreviewStream gets low FPS due to some facedetection/processing.

Is there a way to have two threads:
* one capturing and pushing images to the gui, overwriting last image
* another working on a (threadsafe) copy(?) of the last Mat and doing the preocessing  and pushes the annotated frame or detection data to the gui.

kinda got it working but only without disposing the mats so the memory rises which is not usable..
I guess a ringbuffer / lastin-firstout stack would be needed.

Do you have a hint how the disposing should be done?
