### ISSUE TITLE
Grabcut, different results on multiple invocations with the same input

### ISSUE THREAD

**Issue by mariolatronico** [shimat/opencvsharp#849]
# Summary of your issue
Grabcut gives different results when invoked multiple times with the same input image and the same parameters : InitWithRect and a rectangle of a fixed size
# Environment

Windows 10 home. Net 4.6.2 , lastest OpenCVSharp from NuGet (4.2.0.20200108)
 
# What did you do when you faced the problem?

I'm developing an application where, after the user has loaded an image, the grabcut algorithm is run to remove the background. The goal is to limit the number of interactions of the user and ideally just one grabcut run is needed (with a fixed mask) due to the particular type of images and background loaded. However I noticed that when I run the program I get a result and reloading the same image I get a different result, **usually worse** (some part of the background is not removed).

## Example code:
A minimal program that reproduce the results. It loads an image (taken from here https://www.pexels.com/photo/bowl-of-cooked-food-3590401/ and attached in reduced here), 
create a rectangle almost big as the image (minus 2 pixels around the border) and starts 5 grabcut iterations.

![foodSmall](https://user-images.githubusercontent.com/665622/73344391-9323cc80-4282-11ea-8a6a-f338ef57df68.jpg)
The results are here :

![new_result_0](https://user-images.githubusercontent.com/665622/73344472-b64e7c00-4282-11ea-9c57-8bff6d374a5f.png)
![new_result_1](https://user-images.githubusercontent.com/665622/73344473-b64e7c00-4282-11ea-8724-52eb03633553.png)
![new_result_2](https://user-images.githubusercontent.com/665622/73344474-b6e71280-4282-11ea-9d9b-a7d20e5753d3.png)
![new_result_3](https://user-images.githubusercontent.com/665622/73344476-b6e71280-4282-11ea-96e2-caa96e9da4dc.png)
![new_result_4](https://user-images.githubusercontent.com/665622/73344478-b77fa900-4282-11ea-86a0-8a8a1f00ecff.png)

I also added, as suggested here [Difference between output of grabCut between runs](https://answers.opencv.org/question/200262/difference-between-output-of-grabcut-between-runs/) , **a reset of the state of the RNG,** used by the kmeans pass in the grabcut algorithm (by setting theRNG().State = 0 ) but with no results.

```
using OpenCvSharp;
namespace GrabCut420
{
    class Program
    {
        static void Main(string[] args)
        {
            // photo from https://www.pexels.com/photo/bowl-of-cooked-food-3590401/
            // FREE license
            Mat imageMat = new Mat("foodSmall.jpg");
            var result = new Mat(imageMat.Size(), MatType.CV_8UC1);
            Rect rect = new Rect(2, 2, imageMat.Width - 2, imageMat.Height - 2);

            for (int i = 0; i < 5; i++)
            {
                //Cv2.TheRNG().State = 0;
                Cv2.GrabCut(imageMat, result, rect,
                  new Mat(), new Mat(),
                  3, GrabCutModes.InitWithRect);
                Mat newResult = ((result & 1)) * 255;
                newResult.SaveImage($"new_result_{i}.png");
            }
        }
    }
}
```

A similar piece of code, written in C++ (but I tried with OpenCV 4.1.0), gives always the same result

As a reference, I post here also the  snippet of C++ code (the image has been loaded previously)
```
	Mat bgdModel, fgdModel;
	Rect rect(2, 2, image.cols - 2, image.rows - 2);
	Mat mask;
	cout << "Starting GC at" << endl;
	cv::theRNG().state = 0L;
	cv::grabCut(image, mask, rect, bgdModel, fgdModel, 3, GC_INIT_WITH_RECT);

```

## What did you intend to be?
Every invocation of grabcut, with the same parameters, should always return the same result.

**Comment by shimat** [comment]
Native OpenCV's `theRNG()` returns a reference of the default RNG object, but OpenCvSharp's `TheRNG()` returns not a reference but a value, so we can't use the workaround. At the moment, I think it cannot be done with OpenCvSharp.

https://github.com/shimat/opencvsharp/blob/76d84f9836464644b247db32645409f79485f5fe/src/OpenCvSharpExtern/core.h#L825

It may be better to add an setter method of theRNG to OpenCvSharp...

**Comment by mariolatronico** [comment]
Thank you for the fast reply; is there a different workaround that can be used to get always the same result ?

**Comment by shimat** [comment]
Unless modifing TheRNG of OpenCvSharp, I have no other solution.

**Comment by shimat** [comment]
I added a method to change TheRNG value in https://github.com/shimat/opencvsharp/pull/853

**Comment by mariolatronico** [comment]
Thank you, I tried the branch SetRNG and it works in a predictable way, I always get the same results.
