### ISSUE TITLE
VideoCapture.Retrieve() method throws an exception after calling Grab() method.

### ISSUE THREAD

**Issue by HoQam2557** [shimat/opencvsharp#854]
VideoCapture.Retrieve() method throws an exception after calling Grab() method, though Grab() + RetrieveMat() or Read() methods don't throw.

```C#
var capture1 = new VideoCapture("test.mp4");
var mat1 = new Mat();
capture1.Read(mat1);                // <- OK

var capture2 = new VideoCapture("test.mp4");
capture2.Grab();
var mat2 = capture2.RetrieveMat();  // <- OK

var capture3 = new VideoCapture("test.mp4");
var mat3 = new Mat();
capture3.Grab();
capture3.Retrieve(mat3, 0);         // <- throws an exception
```

For investigation, I've created two versions of test methods equivalent to original Retreive() refering source code.

(1)
The following one receives an "image" argument as "Mat" same as the original method, and It also throws an exception.
```C#
public static bool Retrieve1(VideoCapture capture, Mat image, int flag = 0)
{
    NativeMethods.HandleException(
        NativeMethods.videoio_VideoCapture_retrieve(
            capture.CvPtr, image.CvPtr, flag, out var ret));
    GC.KeepAlive(capture);
    GC.KeepAlive(image);
    return ret != 0;
}
```
(2)
The following one receives an "image" as "OutputArray" instead of "Mat", and it doesn't throw an exception. Original Read() method also receives it as "OutputArray".
```C#
public static bool Retrieve2(VideoCapture capture, OutputArray image, int flag = 0)
{
    NativeMethods.HandleException(
        NativeMethods.videoio_VideoCapture_retrieve(
            capture.CvPtr, image.CvPtr, flag, out var ret));
    GC.KeepAlive(capture);
    GC.KeepAlive(image);
    return ret != 0;
}
```

So I think VideoCapture.Retrieve() method should receive the "image" argument as "OutputArray" instead of "Mat" to resolve the problem.

**Comment by shimat** [comment]
Thanks!
