### ISSUE TITLE
How compile OpenCvSharpExtern  to another linux os and link .net

### ISSUE THREAD

**Issue by auriou** [shimat/opencvsharp#856]
Hello 
I would like to use opencvsharp on a linux machine which is not available in nuget package.
You have Ubuntu and centos. 

Do you have a tutorial to compile OpenCvSharpExtern on another Linux OS ?

And how to indicate in my .net program where is my new native library libOpenCvSharpExtern.so

**Comment by huanbd** [comment]
> Do you have a tutorial to compile OpenCvSharpExtern on another Linux OS ?

You should follow this guide [https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Ubuntu-14.04](https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Ubuntu-14.04)

> And how to indicate in my .net program where is my new native library libOpenCvSharpExtern.so

I'm not sure, in my case I was installed opencv, opencvsharp in my centos env, in my app install nuget OpenCvSharp4, OpenCvSharp4.runtime.centos7-x64

**Comment by auriou** [comment]
Thanks @huanbd  this link is also useful for compiling the opencv cpp lib (OpenCvSharpExtern) https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Unix
