### ISSUE TITLE
Version of OpenCVSharp on NuGet doesn't work for 64bit builds

### ISSUE THREAD

**Issue by capnmidnight** [shimat/opencvsharp#86]
System:
 - Intel Core i7
 - Windows 8.1
 - Visual Studio 2013 Ultimate
 - .NET Framework 4.5.2
 - OpenCvSharp v2.4.10.20150203

It appears that only the 32bit version works. When running a 64bit build, or an Any CPU build that does not have "prefer 32bit" checked in the VS project properties, a GUI MessageBox appears, stating:

"The program can't start because opencv_calib3d249.dll is missing from your computer. Try reinstalling the program to fix this problem."

Checking the files that were installed with the package, there is indeed no opencv_calib3d249.dll, instead it's opencv_calib3d2410.dll. 

It sounds like it's just a minor configuration issue, considering that the 32bit build works fine.

Steps to reproduce are very simple: 

 1. In Visual Studio 2013, create a new C# WinForms project (other project types may work, this is the only one I tried)
 - Right click Use "Manage NuGet Packages"
 - Under the "Online" listing, search "OpenCVSharp" and select the one created by shimat with the version number 2.4.10.20150203
 - Select "x64" as the Solution configuration.
 - Write a small program that instantiates a new OpenCvSharp.CPlusPlus.Mat object.
 - Run the program.

Alternatively, at step 4, you could instead select "Any CPU" as the configuration, then open the Properties window for the project and make sure "Prefer 32-bit" is not checked under the Build settings. The same error will occur.

Work-around is to switch to the 32bit build, by either specifying the build configuration as "x86", or as "Any CPU" with the "Prefer 32-bit" checkbox filled in the build settings.

**Comment by shimat** [comment]
The nuget package "20150203" contains old OpenCvSharpExtern.dll. I released the new package (20150212). please try it.

https://www.nuget.org/packages/OpenCvSharp-AnyCPU/2.4.10.20150212
