### ISSUE TITLE
Missing OpenCvSharp.UserInterface namespace in NuGet 4.2.0.20200208

### ISSUE THREAD

**Issue by jdunnerightpoint** [shimat/opencvsharp#861]
Updated to the  latest 4.2.0.20200208 and got compile errors that OpenCvSharp.UserInterface was missing.

# Environment
Win10 VS 2017

Using PictureBoxIpl in WinForm app.
Updated NuGet package in VS
Got compile errors re missing namespace.

Reverted back to older version to fix problem.
Something missing from latest NuGet?
Thanks,
Joe

**Comment by shimat** [comment]
Sorry but it was deleted by #840 .
