### ISSUE TITLE
Segmentation fault when ReadNetFromDarknet

### ISSUE THREAD

**Issue by huanbd** [shimat/opencvsharp#864]
# Summary of your issue
Cause app crash when initialize `OpenCvSharp.Dnn.Net` use `CvDnn.ReadNetFromDarknet(cfg, model)`
# Environment
Centos 7

Write your environment.

ASP.NET Core 3.1
Install nuget OpenCvSharp4 , OpenCvSharp4.runtime.centos7-x64

# What did you do when you faced the problem?
The first problem when deploy code is [https://github.com/shimat/opencvsharp/issues/701](https://github.com/shimat/opencvsharp/issues/701)
I've resolve it by install [opencv](https://linuxize.com/post/how-to-install-opencv-on-centos-7/), and [opencvsharp](https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Ubuntu-14.04)

The second problem is app crash when initialize `OpenCvSharp.Dnn.Net` use `CvDnn.ReadNetFromDarknet(cfg, model)`. So I think the first problem was resolved, In second problem, I don't know why
## Example code:

```
net = CvDnn.ReadNetFromDarknet(cfg, model);
```

## Output:

```
Segmentation fault.
```

Hope your help!

**Comment by TWhidden** [comment]
Lol,  dealt with this myself --- check to see if you have windows line endings on your config side. Change to Linux line endings.  That fixed it for me.

**Comment by huanbd** [comment]
Thank you @TWhidden, It has resolved!
