### ISSUE TITLE
OpenCvSharp3-AnyCPU in C# and C++ of  thresold & DrawContour API on getting different value

### ISSUE THREAD

**Issue by alpesh-einfochips** [shimat/opencvsharp#866]
We are using OpencvSharp3-AnyCPU in C#, We compared Thresold & Drawcontour API using C# opencvsharp and C++ opencv using and getting different output.

## Example code:
**Issue 1:**
Cv2.Threshold(f5, f6, 5, 255, ThresholdTypes.Binary); // C# Opencvsharp API

 cv::threshold(f5, f6, 5, 255, CV_THRESH_BINARY);  // C++ opencv API

**Issue 2:**
**C# drawcontour code:**
 OpenCvSharp.Point[][] contours;
                HierarchyIndex[] hierarchy;
                Cv2.FindContours(f6.Clone(), out contours, out hierarchy, RetrievalModes.List, ContourApproximationModes.ApproxSimple);

                for (int i = 0; i < contours.Length; i++)
                {
                    double area = Cv2.ContourArea(contours[i]);
                    if (area <= 200)
                    {
                        Cv2.DrawContours(mask, new[] { contours[i] }, -1, 0, -1);
                    }
                }
**C++ drawcounter code:**
std::vector<std::vector<cv::Point>> contours;
        std::vector<cv::Vec4i> hierarchy;
        cv::Mat contourOutput = f6.clone();

        cv::findContours( contourOutput, contours, hierarchy, cv::RETR_LIST, cv::CHAIN_APPROX_SIMPLE, cv::Point(0, 0) );

        for (std::vector<cv::Point> contour : contours){
            double area = cv::contourArea(contour);
            if(area <= 200){
                cv::drawContours(mask, std::vector<std::vector<cv::Point>>(1,contour), -1, 0, -1);
            }
        }
## Output:

- We got difference output using same input on thresold & drawcontour API.

Please give me solution for this.

**Comment by shimat** [comment]
Can you give us information to reproduce the problem? (`f5`'s image data, your OpenCV(C++) version, etc.)

(I don't support or bugfix older versions, including OpenCvSharp3, because I don't have time.)
