### ISSUE TITLE
MethodNotFound exception thrown when i call OpenCvSharp.VideoCapture("udp source")

### ISSUE THREAD

**Issue by CityAndTheStars** [shimat/opencvsharp#868]
# Summary of your issue
System.MissingMethodException: 'Method not found: 'Void OpenCvSharp.VideoCapture..ctor(System.String, OpenCvSharp.VideoCaptureAPIs)'.'

# Environment
Windows

Write your environment.
Windows 10, x86, 64-bit

# What did you do when you faced the problem?
I created a OpenCvSharp.VideoCapture("udp://0.0.0.0:11111", OpenCvSharp.VideoCaptureAPIs.FFMPEG);

I also tried creating as OpenCvSharp.VideoCapture("udp://0.0.0.0:11111");

//write here

## Example code:
OpenCvSharp.VideoCapture("udp://0.0.0.0:11111", OpenCvSharp.VideoCaptureAPIs.FFMPEG);
OpenCvSharp.VideoCapture("udp://0.0.0.0:11111");
```
paste your core code
```

## Output:

```
paste your output
System.MissingMethodException: 'Method not found: 'Void OpenCvSharp.VideoCapture..ctor(System.String, OpenCvSharp.VideoCaptureAPIs)'.'

## What did you intend to be?

**Comment by shimat** [comment]
Make sure that all assemblies of your application reference the same version of OpenCvSharp.

**Comment by CityAndTheStars** [comment]
This longer occurs with the latest OpenCvSharp4 version.
