### ISSUE TITLE
OpenCVSharpExtern build on RPI3 B - support OpenCV with OpenVino and intel's NCS2 - DNN Module throws exception

### ISSUE THREAD

**Issue by alongu** [shimat/opencvsharp#871]
Building OpenCV-4.1.1 over the Raspberry PI 3 and after that building OpenCVSharp-4.1.1 over the PI with the instructions from here: https://github.com/shimat/opencvsharp/issues/388 works as expected. I was able to run .NET Core application which uses the OpenCV dnn module for face recognition as expected.

Recently I've bought intel's NCS2 to achieve better FPS, but in order to use it I had to rebuild the OpenCV library with the inference engine of OpenVino. It works well over the PI with Python, yet I failed to make it work with the OpenCVSharp. Rebuilding OpenCVSharp for OpenCV that was compiled with the OpenVino from some reason causing a double-linked list error when using the DNN module ReadFromCaffe function. 

#Environment
* Raspberry PI 3 B+ with Raspbian Buster official release
* OpenCV-4.1.1 with OpenVino inference engine build Cross Compiled over Debian Buster (works as expected over the PI with Python)
* OpenCVSharpExtern - build was made over the PI - with respect to the include folder of the OpenCV on the PI.

I've tried to cross compile OpenCV and rebuild the OpenCVSharp library after that, and I've also tried to build OpenCV with the OpenVino on the PI itself and after that rebuilding the OpenCVSharp yet haven't got any success. 

I believe this has something to do with the build process of the OpenCVSharp on the PI as the OpenCV works well with the NCS2 on my PI when using Python.

It feels as I am missing something with the build process of the OpenCVSharp over the Raspberry PI.
I followed the instructions from DaEkstrim:
#install the Extern lib.
cd opencvsharp/src
sed -i.bak '5i\
include_directories("/usr/local/include/")\
set (CMAKE_CXX_STANDARD 11)\
' CMakeLists.txt
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig

Will the build work if the include folder is located in another location rather than in /usr/local/include/? 

## Example code:
CvDnn.ReadNetFromCaffe(faceDetectorPrototextPath, faceDetectorModelPath);

## Output:
Corrupted double linked list error

Thanks,

**Comment by frankhommers** [comment]
Did you get this to work already? Or still having the problem?

**Comment by alongu** [comment]
Yes.
I had enough with it and switched to Python. Now works like a charm

**Comment by thug1705** [comment]
what fps rate you are getting when you are running through the python @alongu ?

**Comment by alongu** [comment]
FPS with Opencvsharp without the NCS was ~1. Using Python + NCS worked with ~4-5 FPS for detection. I am using the ZeroMQ to pass from Python the video to a server written with C# which using opencvsharp to show the video to screen, so FPS is slower, not sure how much

**Comment by frankhommers** [comment]
Wondering if I should start in python with this, or give the .NET stuff a try...

**Comment by alongu** [comment]
.NET with windows and opencsharp is ok, but over the PI, just go with Python. You'll thank me later
