### ISSUE TITLE
OCRTesseract can not recognize Chinese

### ISSUE THREAD

**Issue by Sunzhuokai** [shimat/opencvsharp#873]
# Summary of your issue
OCRTesseract can not recognize Chinese
# Environment

![image](https://user-images.githubusercontent.com/8599906/75418811-5b866e00-596f-11ea-8174-d3d2509461e6.png)

# What did you do when you faced the problem?

//write here

## Example code:
```
using (var ocr = OCRTesseract.Create(“tessdata", "chi_sim"))
                        {
                            ocr.Run(topRoi, out text, out _componentRects, out  _componentTexts, out  _confidences);
                        }
```
## Output:

```
Just 0-9,a-Z
```

**Comment by shimat** [comment]
Does your tessdata contain chi_sim.traineddata ?

**Comment by Sunzhuokai** [comment]
> Does your tessdata contain chi_sim.traineddata ?

yes
![image](https://user-images.githubusercontent.com/8599906/75421681-c63aa800-5975-11ea-84e1-0af1ceb6e7e0.png)

**Comment by Sunzhuokai** [comment]
@shimat when i use  https://github.com/charlesw/tesseract wrapper , it is works

**Comment by shimat** [comment]
I could reproduce this problem. It may be an OpenCV bug.
https://github.com/opencv/opencv_contrib/issues/2062

**Comment by Jerry-Gump** [comment]
I have the same problem,anything can fix it?

**Comment by n0099** [comment]
From https://docs.opencv.org/4.7.0/d7/ddc/classcv_1_1text_1_1OCRTesseract.html#a391b1e753f0b779b72204ec15200a99a:
> char_whitelist	specifies the list of characters used for recognition. NULL defaults to "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".

https://github.com/shimat/opencvsharp/blob/0498156821f052ff6b2fd1205148f07a1de2781d/src/OpenCvSharp/Modules/text/OCRTesseract.cs#L37
https://github.com/shimat/opencvsharp/blob/0498156821f052ff6b2fd1205148f07a1de2781d/src/OpenCvSharpExtern/text.h#L87
