### ISSUE TITLE
 Can not find Enum CaptureDevice

### ISSUE THREAD

**Issue by duonghb53** [shimat/opencvsharp#876]
# Can not find Enum CaptureDevice
Dear Mr.Shimat,
When I update OpenCvSharp3-AnyCPU to OpenCvSharp4, 
I can't find enum CaptureDevice.
I don't know reason why?
This is error from Visual Studio,
> The name 'CaptureDevice' does not exist in the current context

Please help me.

**Comment by shimat** [comment]
Please use `VideoCaptureAPIs` instead.
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/videoio/Enum/VideoCaptureAPIs.cs

I renamed the enum the same as OpenCV.

**Comment by duonghb53** [comment]
Dear Mr. Shimat,
Thank you for your information.
And then:
What are difference between Version OpenCvSharp4 and OpenCvSharp3-AnyCPU?
I can't find document history of them.

**Comment by shimat** [comment]
Sorry but there is no documentation for migration.

**Comment by duonghb53** [comment]
Dear Mr. Shimat,
Thank you.
Can you tell me a little about main difference  between them?

**Comment by shimat** [comment]
That is, the version of native OpenCV was updated from 3 to 4.
Changes in the OpenCvSharp 4.x API cannot be described in a nutshell. https://github.com/shimat/opencvsharp/compare/3.4.4.20181118...4.2.0.20200208#files_bucket
