### ISSUE TITLE
BitmapConverter ToMat() NotImplementedException("Not supported halftone Palette");

### ISSUE THREAD

**Issue by FaridGad** [shimat/opencvsharp#878]
# Summary of your issue
I'm using a pair of monochrome cameras which acquire images in Bitmap format. For further image processing using OpenCVSharp, the images need to be converted to Mat format. Previous version (4.0.0.20181129) had no issues doing the conversion. The latest version (4.2.0.20200208) throws the exception "NotImplementedException("Not supported halftone Palette");". The images used as input haven't changed at all. 

# Environment
Windows 10
Visual Studio 2019
OpenCVSharp version (4.2.0.20200208) - downloaded from the NuGet Package Manager
Framework: .Net Framework 4.6.1

# What did you do when you faced the problem?
1. Tried to implement the ToMat() method without handling the Bitmap.Palette.Flag
Outcome: More errors arose

2. Tried to change the Bitmap palette from halftone to grayscale. It's not possible.

## Example code:

camera.Memory.ToBitmap(memoryID, out BitmapI); // IDS Camera library method
Mat matImage = new Mat();
BitmapConverter.ToMat(BitmapI, matImage);

**Comment by ykchoi3773** [comment]
I have the same problem as this.
Version is 4.4.0.20200725

**Comment by kanstantsin** [comment]
Same issue when attempting to process Bitmap received from Ximea camera in Mono8 mode.
As a workaround I downloaded [BitmapConverter](https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp.Extensions/BitmapConverter.cs#L159) source code, commented out lines 159-160 and everything is working fine.
Is there a reason to not handle halftone palette as usual `PixelFormat.Format8bppIndexed`?

**Comment by shimat** [comment]
I don't know how to handle the halftone palette, so I implemented it that way. OK, I'll comment out `throw NotImplementedException`.

**Comment by kanstantsin** [comment]
@shimat thanks! As for me, a quick search didn't give any detailed information about halftone palette handling. Just to make sure, that it's ok I took a look at [EmguCV conversion](https://github.com/emgucv/emgucv/blob/1c508c519931709adb50a77f47d609b0b6aa20d8/Emgu.CV.Platform/Emgu.CV.Bitmap/BitmapExtension.cs#L333) and it seems not to handle halftone palette explicitly. But looks like it handles any colors in the palette while `OpenCVSharp` only expects grayscale palette.
