### ISSUE TITLE
OpenCVSharp not compiling on MacOSX Yosemite 10.10.2

### ISSUE THREAD

**Issue by anestesya** [shimat/opencvsharp#88]
Iam trying install and use OpenCVSharp on OSX Yosemite with Unity 3d, but on running make command to compile a OpenCVSharp i get the erro message:

```
"_cvGetRealND", referenced from:
  CvCamShiftTracker::query(int*) const in legacy.cpp.o
  ld: symbol(s) not found for architecture x86_64
 clang: error: linker command failed with exit code 1 (use -v to see     invocation)
 make[2]: *** [OpenCvSharpExtern/libOpenCvSharpExtern.dylib] Error 1
 make[1]: *** [OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/all]      Error 2
 make: *** [all] Error 2
```

Iam searching for fixes and found this links: http://stackoverflow.com/questions/21676759/after-update-to-mac-os-10-8-undefined-symbols-for-architecture-x86-64-clang

But not working for me.

**Comment by shimat** [comment]
Sorry but it is difficult to support Unity. Please consider using *OpenCV for Unity* (https://www.assetstore.unity3d.com/en/#!/content/21088).
