### ISSUE TITLE
count white and black pixels for comparison

### ISSUE THREAD

**Issue by Mghobadid** [shimat/opencvsharp#880]
how count number of white and black pixels for below threshold?
` Cv2.Threshold(plate,threshold, 0, 255,ThresholdTypes.Otsu|ThresholdTypes.Binary);`

**Comment by shimat** [comment]
Please consider using `Cv2.CountNonZero`.

**Comment by Mghobadid** [comment]
for others need count white and black pixels :
 
  int TotalNumberOfPixels = threshold.Cols * threshold.Rows;
  int BlackPixels = TotalNumberOfPixels - Cv2.CountNonZero(threshold);
  int WhitePixels = Cv2.CountNonZero(threshold);
