### ISSUE TITLE
Mat.Row from OpenCvSharp3 to 4

### ISSUE THREAD

**Issue by mtherezien** [shimat/opencvsharp#883]
In OpenCVSharp3, Mat.Row {get;} was an indexer to get the entire row of a Mat as another Mat, and allowed things like
a.Row[i0] = b.Row[i1];

In OpenCVSharp4, the same a.Row[i0] indexing returns an error since Mat.Row(int y) is not a method returning a header for the specified row.

Now maybe I was doing it wrong in OpenCvSharp3 all along, but it worked and I didn't bother looking any further. What is the most effective way pass an entire row (or column) from one Mat to another in OpenCvSharp4?

**Comment by shimat** [comment]
I deleted the Mat.Row {get;} property because it causes memory leaks. Please try the following way.
```c#
using var mat1 = new Mat(3, 3, MatType.CV_8UC1, Scalar.All(1));
using var mat2 = new Mat(3, 3, MatType.CV_8UC1, Scalar.All(2));

using var mat1Row = mat1.Row(1);
using var mat2Row = mat2.Row(1);
mat1Row.CopyTo(mat2Row);

/*
mat2 = {
  {2, 2, 2},
  {1, 1, 1}, // copied from mat1
  {2, 2, 2}
};
*/
```
