### ISSUE TITLE
can i use gpu?

### ISSUE THREAD

**Issue by mey1k** [shimat/opencvsharp#888]
# Summary of your issue
I want to use gpu.
# Environment
gtx 2070, i7 10900, 32gb
# What did you do when you faced the problem?
When i use CvDnn class, i use SetPreferableBackend function and SetPreferableTarget function
but, i got a error message
----------------------------------message-------------------------------------------------------------
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!
---------------------------------------------------------------------------------------------------------
## Example code:
            var net = CvDnn.ReadNetFromDarknet(cfg, model); 
            #region set preferable
            net.SetPreferableBackend(3);
            /*
            0:DNN_BACKEND_DEFAULT 
            1:DNN_BACKEND_HALIDE 
            2:DNN_BACKEND_INFERENCE_ENGINE
            3:DNN_BACKEND_OPENCV 
             */
            net.SetPreferableTarget(1);
            /*
            0:DNN_TARGET_CPU 
            1:DNN_TARGET_OPENCL
            2:DNN_TARGET_OPENCL_FP16
            3:DNN_TARGET_MYRIAD 
            4:DNN_TARGET_FPGA 
             */
## Output:
result is ok. 
but i think it is cpu calculation result.

## What did you intend to be?
i want to use gpu.
I saw some posters. 
May i should rebuild opencv with cuda?
Is this right?
(pencv_core.dll == OpenCvSharp.Extensions.dll) and (opencv_gpu.dll == OpenCvSharp.dll)?

**Comment by TWhidden** [comment]
Yes, you can use a GPU.  Here is a sample from my code using it on an Nvidia Nano, doing darknet dnn.  Works very well.  

```
_logging.Info("ImagePrediction Starting");

var confFile = Path.Join(CurrentPath, "darknet", Config.Current.DarkNetModel, "obj.cfg");
var model = Path.Join(CurrentPath, "darknet", Config.Current.DarkNetModel, "obj.weights");
var inputNamesFile = Path.Join(CurrentPath, "darknet", Config.Current.DarkNetModel, "classes.txt");

// Read the obj.cfg file to find the input width and height 
var inputConfigTest = File.ReadAllText(confFile);
var inputConfig = inputConfigTest.Split(new[] { "\n", "\r\n" },
StringSplitOptions.RemoveEmptyEntries);

_inputWidth = inputConfig.Where(x => x.StartsWith("width="))
    .Select(x => int.Parse(x.Split("=", StringSplitOptions.RemoveEmptyEntries)[1]))
    .FirstOrDefault();
_inputHeight = inputConfig.Where(x => x.StartsWith("height="))
    .Select(x => int.Parse(x.Split("=", StringSplitOptions.RemoveEmptyEntries)[1]))
    .FirstOrDefault();

if (_inputHeight == 0 || _inputWidth == 0)
    throw new Exception($"Could not detect input width or height! {_inputWidth}x{_inputHeight}");

_inputSize = new Size(_inputWidth, _inputHeight);

// Read all the classes for prediction output
_classes = File.ReadAllLines(inputNamesFile);

// Load the network
_network = CvDnn.ReadNetFromDarknet(confFile, model);
if (Config.Current.ImageProcessingSettings.UseCuda)
{
    _logging.Info("Using CUDA backend...");
    _network.SetPreferableBackend(Net.Backend.CUDA);
    _logging.Info("Using CUDA target...");
    _network.SetPreferableTarget(Net.Target.CUDA);
}

// Get the output layer names
_outputNames = _network.GetUnconnectedOutLayersNames();
_logging.Info($"UnconnectedOutLayersNames: {string.Join(", ", _outputNames)}");

// Get all the layer names (just for output reference)
var layerNames = _network.GetLayerNames();
_logging.Info($"All Layers: {string.Join(", ", layerNames)}");

// find the last, output name
_outputName = layerNames.LastOrDefault(x => _outputNames.Contains(x));
_logging.Info($"Expected Output Layer: {_outputName}");

// Initialize the Mat output
_detectionsMat = new Mat[_outputNames.Length];
for (var i = 0; i<_outputNames.Length; i++) _detectionsMat[i] = new Mat();
```

Let me know when you are ready for how to read the output mat :) that's another joy.  Super easy once you understand the return Mat from the DNN.

Make sure you are using the right nuget package.  @shimat  was able to take my pull request months ago and can confirm this works fine under cuda.   Also, make sure you don't have windows line endings in your conf file, as that breaks the DNN (also a learning experience).

**Comment by TWhidden** [comment]
Oh, and yes, you will need to rebuild with cuda.  See my fork with the docker file that has that example:

https://github.com/TWhidden/opencvsharp/blob/master/docker/nvidia-lt4/nvidia-lt4-base/Dockerfile
