### ISSUE TITLE
cannot find CvNormalBayesClassifier.Dispose() method

### ISSUE THREAD

**Issue by KojiKobayashi** [shimat/opencvsharp#89]
CvNormalBayesClassifier を試そうとしたところ、
開放時に以下のような例外が送出されました。

```C#
            CvNormalBayesClassifier classifier = new CvNormalBayesClassifier();
            classifier.Dispose();
```

```
ハンドルされていない例外: System.EntryPointNotFoundException: DLL 'OpenCvSharpEx
tern' の 'ml_CvNormalBayesClassifier_delete' というエントリ ポイントが見つかりま
せん。
   場所 OpenCvSharp.CPlusPlus.NativeMethods.ml_CvNormalBayesClassifier_delete(In
tPtr obj)
   場所 OpenCvSharp.CPlusPlus.CvNormalBayesClassifier.Dispose(Boolean disposing)
```

おそらく以下で、「destruct」と定義してある箇所が問題だと思うのですが。
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharpExtern/ml_CvNormalBayesClassifier.h#L20

ちなみにlearn、classify は正常に機能しているようです。

**Comment by shimat** [comment]
:bow:

https://github.com/shimat/opencvsharp/commit/b76fcdf9a441aacb859d7db81182dd528b9ef89d fixed this problem.
