### ISSUE TITLE
Loading nonexistent image fails silently

### ISSUE THREAD

**Issue by dzarda** [shimat/opencvsharp#891]
# Summary of your issue

Attempting to load an image that does not exist yields a `Mat` with zero size.

# Environment

- Windows 10
- `<TargetFramework>net472`
- `<PlatformTarget>x64`
- `<PackageReference Include="OpenCvSharp4" Version="4.2.0.20200208"` />
- `<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.2.0.20200208" />`

# What did you do when you faced the problem?

Used the `Mat(string filePath, ...)` constructor

## Example code:

```cs
var hello = new Mat("C:\nonexistent\file.png", ImreadModes.AnyDepth);
```

## Output:

The `hello` object is "empty" = 0 width, 0 height.

```
{OpenCvSharp.Mat: Mat [ 0*0*CV_8UC1, IsContinuous=False, IsSubmatrix=False, Ptr=0x290b49c4240, Data=0x0 ]}
```

## What did you intend to be?

Expected to receive an exception upon trying to load a missing file.

**Comment by shimat** [comment]
It is by design of OpenCV. You can use Mat.Empty() to check if the image has been loaded or not.

**Comment by dzarda** [comment]
Thanks, I didn't know about this behaviour
