### ISSUE TITLE
Opencvsharp does not support CUDA acceleration in the current version of DNN？

### ISSUE THREAD

**Issue by HenryLee-coder** [shimat/opencvsharp#893]
# Summary of your issue

# Environment

win10
opencvsharp4.2
opencv4.2
opencv_contrib4.2.0
VS2019

## What did you intend to be?

- [ ] 

- ### **Opencvsharp does not support CUDA acceleration in the current version of DNN. I have built opencv ﹣ contrib4.2.0. What can I do to use CUDA acceleration of DNN in opencvsharp? What can I do? Can I have a detailed step**

**Comment by shimat** [comment]
I have changed the build guide of native OpenCV. 
https://github.com/shimat/opencvsharp#how-to-customize-opencv-binaries-yourself

You will need to build OpenCV and OpenCvSharpExtern.dll on your own.
