### ISSUE TITLE
Can I build opencvExtern?

### ISSUE THREAD

**Issue by mey1k** [shimat/opencvsharp#896]
after, git submodule update --init --recursive

opencv_420d.lib is not installed.

so I downloaded opencv4.2.0 and cmake build

after, I got the opencv_420d.lib

but when i build opencvExtern by using it, i got some err msg

>xphoto.obj : error LNK2019: "public: virtual void __cdecl cv::videostab::MotionStabilizationPipeline::stabilize(int,class std::vector<class cv::Mat,class std::allocator<class cv::Mat> > const &,struct std::pair<int,int>,class cv::Mat *)" (?stabilize@MotionStabilizationPipeline@videostab@cv@@UEAAXHAEBV?$vector@VMat@cv@@V?$allocator@VMat@cv@@@std@@@std@@U?$pair@HH@5@PEAVMat@3@@Z) 
External symbol (reference position: "public: __cdecl std::vector<struct cv::Ptr<class cv::videostab::IMotionStabilizer>,class std::allocator<struct cv::Ptr<class cv::videostab::IMotionStabilizer> > >::vector<struct cv::Ptr<class cv::videostab::IMotionStabilizer>,class std::allocator<struct cv::Ptr<class cv::videostab::IMotionStabilizer> > >(class std::vector<struct cv::Ptr<class cv::videostab::IMotionStabilizer>,class std::allocator<struct cv::Ptr<class cv::videostab::IMotionStabilizer> > > const &)" (??0?$vector@U?$Ptr@VIMotionStabilizer@videostab@cv@@@cv@@V?$allocator@U?$Ptr@VIMotionStabilizer@videostab@cv@@@cv@@@std@@@std@@QEAA@AEBV01@@Z) 
The function failed to check.

why??

**Comment by shimat** [comment]
OpenCvSharp does not use Debug configuration. Please use Release configuration.
I have changed the build guide. https://github.com/shimat/opencvsharp#windows
