### ISSUE TITLE
I use OpenCvSharp4 and OpenCvSharp4-runtime.uwp But Why didn't read the picture

### ISSUE THREAD

**Issue by oneSaber** [shimat/opencvsharp#904]
# Summary of your issue

# Environment

Write your environment.

# What did you do when you faced the problem?

I can't read the picture in uwp, But I can  read it in Consoles, there is the Expeti

## Example code:

 Mat mat = Cv2.ImRead("C:/Users/13578/source/repos/OpenCVSharpTest/Assets/LockScreenLogo.scale-200.png");
            Cv2.ImShow("mat", mat);
            Cv2.WaitKey();

## Output:
the exception is :
OpenCvSharp.OpenCVException
  HResult=0x80131500
  Message=size.width>0 && size.height>0
  Source=OpenCvSharp
  StackTrace:
   在 OpenCvSharp.NativeMethods.<>c.<.cctor>b__1559_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   在 OpenCvSharp.NativeMethods.highgui_imshow(String winName, IntPtr mat)
   在 OpenCvSharp.Cv2.ImShow(String winName, Mat mat)
   在 OpenCVSharpTest.OpenCvTest.Button_Click(Object sender, RoutedEventArgs e) 在 C:\Users\13578\source\repos\OpenCVSharpTest\OpenCvTest.xaml.cs 中: 第 35 行

## What did you intend to be?
So How can I do

**Comment by shimat** [comment]
I'm not familiar with UWP, but I'm guessing we can't use absolute path in UWP app.
https://stackoverflow.com/questions/37661051/readlinesasync-in-uwp-from-absolute-file-path
