### ISSUE TITLE
Superpixels?

### ISSUE THREAD

**Issue by henon** [shimat/opencvsharp#908]
I came across this [Superpixels demo](http://amroamroamro.github.io/mexopencv/opencv_contrib/superpixels_demo.html). Obviously there is no Cv2.SuperPixels(...) function in OpenCvSharp. 

OpenCv does seem to have that function: https://docs.opencv.org/4.3.0/df/d6c/group__ximgproc__superpixel.html

Just curious, is it not yet wrapped or is there another reason for it not being included?

**Comment by shimat** [comment]
It is not wrapped yet. There are many unwrapped OpenCV functions, because I don't have time and I don't need all of them myself. I look forward to someone's pull requests.

**Comment by willemvs** [comment]
> It is not wrapped yet. There are many unwrapped OpenCV functions, because I don't have time and I don't need all of them myself. I look forward to someone's pull requests.

Does this apply for issue #890 as well?
