### ISSUE TITLE
Mat.GetArray issue with vb.net

### ISSUE THREAD

**Issue by bht-eng** [shimat/opencvsharp#911]
# Summary of your issue
When upgrading to a version > 4.1.1.20191110, the Mat.GetArray function does not work with VB.NET anymore.

# Environment
Windows 10, Visual Studio 2019, VB.NET 4.7.2

# What did you do when you faced the problem?
Found the following VB.NET documentation:
[https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc32108](url)
Which states:
> 'Structure' constraint and a specific class type constraint cannot be combined

I had to revert to version 4.1.1.20191110.

## Example code:
    Public Function GetByteArray(ByVal image As Mat) As Byte()
        Dim result = New Byte() {}
        Using gray = image.CvtColor(ColorConversionCodes.BGR2GRAY)
            gray.GetArray(result)
        End Using
        Return result
    End Function

## Output:
Intellisense output when hovering over the Mat.GetArray function:
>     Function Mat().GetArray(Of T As {Structure, ?}(ByRef data As T()) As Boolean
>     Get the data of this matrix as array
>     `` is an unsupported type

**Comment by shimat** [comment]
VB.NET is no longer keeping up with the latest C# specifications. VB.NET does not support the type constraint of `where T : unamanged`. Unfortunately I've heard that Microsoft is going to lose update for VB.NET, but I'll wait for it.

```c#
public bool GetArray<T>(out T[] data)
    where T : unmanaged
```

You may be able to rewrite it using `Mat.Data` and `Marshal.Copy`.

**Comment by microlemongrass** [comment]
Sorry, Version 4.1.1.20191017 removed MatOfxxx and changed the coding, is this the same reason you can't use it in VB.NET?

すみません、Version 4.1.1.20191017でMatOfxxxが削除され、記述方法が変わりましたが、これをVB.NETで使用できないのも同様の理由でしょうか？（このissueに書くべきではなかったのならば申し訳ありません）
```C#
using (var imgt = new Mat<Vec3b>(img))
{
}
```

```VB
Using imgt = New Mat(Of Vec3b)(img)

End Using
```
