### ISSUE TITLE
Version 3.4.4 Can't build OpenCvSharpExtern under the Windows 10, Visual Studio 2017 - Windows XP (v141_xp)

### ISSUE THREAD

**Issue by JonasHdez** [shimat/opencvsharp#913]
# Summary of your issue
I  Can't build OpenCvSharpExtern under the **Windows 10, Visual Studio 2017 - Windows XP (v141_xp)**
Using **Version 3.4.4** I try the following steps.

1 | git clone   https://github.com/shimat/opencvsharp
2 | git submodule update --init to get opencv_files
3 | Start Visual Studio 2017
4 | set the build configuration to x86/Release
5 | OpenCvSharpExtern  Properties \|   Platform Set = Visual Studio 2017 - Windows XP (v141_xp)
After try to Build a got this error.
Warning | MSB8030 The linker switch "Minimum Required Version" requires "SubSystem" to be set
Error | LNK1181 cannot open input file ',5.01'
6 | OpenCvSharpExtern  Properties   \|Linker \| System \| SubSystem =  Windows   (/SUBSYSTEM:WINDOWS)
After trying to Build again I got this error and don't know how to fix it. could you please advise.
Error | LNK2001 unresolved external symbol _gzopen
Error | LNK2001 unresolved external symbol _gzputs
Plus another 80 similar errors with other libraries.
![image](https://user-images.githubusercontent.com/26067391/79670478-57b5e180-8191-11ea-8fe5-81b5d0706292.png)

# Environment
Windows 10

Write your environment.
Visual Studio 2017 with all the updates
# What did you do when you faced the problem?
I describe all the steps above.
//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
The OpenCV lib files that I made in `opencv_files` are not for XP. You probably have to make them for XP yourself.

**Comment by JonasHdez** [comment]
Let me try it. In the meantime, do you think I need these steps?
.\vcpkg install tesseract:x64-windows-static
.\vcpkg install tesseract:x86-windows-static
.\vcpkg integrate install

what are they for?

**Comment by shimat** [comment]
Tesseract is required for the opencv_text module in the opencv_contrib. If you don't use the opencv_text module, you can skip the vcpkg steps.

**Comment by JonasHdez** [comment]
Thanks for your answers. I try to compile the OpenCV 3.4.4 and send me back this error:
Error	C2065	'DXGI_FORMAT_NV12': undeclared identifier	opencv_core	\opencv-3.4.4\modules\core\src\directx.cpp	172

**Comment by shimat** [comment]
I don't think recent OpenCV has taken XP into account. https://stackoverflow.com/a/59700899
You need to either try with a much older OpenCV version or confront the error yourself. (I don't know much about it.)

I don't consider XP for OpenCvSharp, so I think it's better to use older native OpenCV in C or C++ instead of OpenCvSharp (C#) if you really need to support XP.

**Comment by JonasHdez** [comment]
Thanks. I was am going to use Nuget OpenCVSharp 3.2 which seems to be working for XP.
