### ISSUE TITLE
StdString.ToString() not correct , the info is Chinese

### ISSUE THREAD

**Issue by pkingwsd** [shimat/opencvsharp#915]
win10 
.net core 3.1
![image](https://user-images.githubusercontent.com/29122173/79710529-d462d000-82f7-11ea-8aa5-010659e2d7bd.png)

python 3.7
>>> inputImage = cv2.imread(r"C:\Users\ken\source\repos\OpenCvLessions\OpenCvLessions\qr.PNG")
>>> data, bbox, rectifiedImage = qrDecoder.detectAndDecode(inputImage)
>>> print("Decoded Data : {}".format(data))
**Decoded Data : 环境大家学习OpenCV，请到：https://blog.csdn.net/kingroc/article/details/83000191**

**Comment by shimat** [comment]
Could you show me the QR code image which you tried?

**Comment by shimat** [comment]
Thanks. This is fixed by #915.

**Comment by pkingwsd** [comment]
@shimat 

the qr code. if you want to test.  

https://github.com/kingroc711/CVSample/blob/master/OpenCV/res/QR.png
