### ISSUE TITLE
Mat.At<> AccessViolationException

### ISSUE THREAD

**Issue by ilsergeev** [shimat/opencvsharp#926]
# Summary of your issue
When i try to use method Mat.At<> in opencvsharp 4 version 4.3.0.20200421. It's throw exception AccessViolationException
# Environment

Visual Studio 2017

# What did you do when you faced the problem?

//write here

## Example code:

```c#
Mat tmp, in_mat = Cv2.ImRead(imagePath);
Mat out_mat = Cv2.ImRead(imagePath);
double percent = 1;

Debug.Assert(in_mat.Channels() == 3);
Debug.Assert(percent > 0 && percent < 100);

double half_percent = percent / 200.0;

//VectorOfMat tmpSplit = new VectorOfMat();

Mat[] tmpSplit; 
 
Cv2.Split(in_mat, out tmpSplit);

for (int i = 0; i < 3; i++)
{
    //find the low and high precentile values (based on the input percentile)

    Mat flat = new Mat();
 
    // Mat flat = new Mat();
    tmpSplit[i].Reshape(1, 1).CopyTo(flat);
    Cv2.Sort(flat, flat, (int)SortFlags.Ascending + (int)SortFlags.EveryRow);

    double flat_col = flat.Cols;
    int col = (int)Math.Floor(flat_col * half_percent);
    
    int lowval = flat.At<byte>(col);
    double flat_ceil = flat.Cols;
    int ceil = (int)Math.Ceiling(flat_ceil * (1.0 - half_percent));

    //saturate below the low percentile and above the high percentile
    // tmpSplit[i].SetTo(lowval,  tmpSplit[i] < lowval);
    // tmpSplit[i].SetTo(highval, tmpSplit[i] > highval);
    NormTypes normType = NormTypes.MinMax;
    //scale the channel
    Cv2.Normalize(tmpSplit[i], tmpSplit[i], 0, 255, normType);
}

Cv2.Merge(tmpSplit, out_mat);
Cv2.ImShow("balance",out_mat);
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
Use `using`, or use `Get()` instead of `At()`.
```c#
using Mat flat = new Mat(); // C# 8

using (Mat flat = new Mat()) // C# <= 7 
{
    ...
}
```
```c#
int lowval = flat.Get<byte>(col);
```

**Comment by moveccr** [comment]
OpenCVSharp の Mat.At(i0) の実装仕様が、opencv Mat::at の仕様と違うのが原因です。

OpenCVSharp のほうは i0 を Index along the dimension 0 (=row) としています。
https://github.com/shimat/opencvsharp/blob/ea7c67ff0df7b0bc003b46b245a413c7830ffb16/src/OpenCvSharp/Modules/core/Mat/Mat.cs#L3236-L3246

ここで呼び出している Ptr() は row を引数に取ると規定されています。

これに対し、opencv のほうは

https://github.com/opencv/opencv/blob/17234f82d025e3bbfbf611089637e5aa2038e7b8/modules/core/include/opencv2/core/mat.inl.hpp#L937-L950

https://docs.opencv.org/4.5.4/d3/d63/classcv_1_1Mat.html#aa5d20fc86d41d59e4d71ae93daee9726

にあるように、二次元配列を一次元とみなしてアクセスするようになっています。

したがって、C++ では Mat::at<>(col) と書くことができますが、
C# では Mat.At(i0) に col を渡すと、範囲外アクセスが発生します。
Mat.Get(i0) も同様です。
