### ISSUE TITLE
yolov4 Unsupported activation: mish

### ISSUE THREAD

**Issue by 147906825** [shimat/opencvsharp#927]
Hello, load yolov4 trained weights through cvdnn.readnetfromdarknet, and prompt Unsupported activation: mish

**Comment by shimat** [comment]
YOLOv4 is so new that the current OpenCV doesn't seem to support it. Please wait for the OpenCV update. This is not an issue that OpenCvSharp should be addressing, so I will close this issue.

**Comment by 147906825** [comment]
Looking forward to OpenCV update Thank you

**Comment by shimat** [comment]
https://github.com/opencv/opencv/issues/17148

**Comment by shimat** [comment]
https://github.com/opencv/opencv/pull/17185

**Comment by 147906825** [comment]
Thanks for your contribution. With your contribution, I could make my project little easier.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shimat"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月1日(星期五) 上午6:37
收件人:&nbsp;"shimat/opencvsharp"<opencvsharp@noreply.github.com&gt;;
抄送:&nbsp;"Anguslai"<147906825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shimat/opencvsharp] yolov4 Unsupported activation: mish (#927)





 
opencv/opencv#17185
