### ISSUE TITLE
CvKNearest Save/Write pointing to method that is not implemented.

### ISSUE THREAD

**Issue by oopyrj** [shimat/opencvsharp#93]
Hi,

I recently tried using CvKNearest class of latest version of OpenCVSharp from nuget and when trying to use Save or Write methods it throws an exception. It wasn't very informative so i went through the pain of compiling openCV  and generating .dpb files in order to view the exception in debugger. It turns out that both Save and Write point to CVStatModel.Write method of openCV library which in turn always throws NotImplementedException or something like that.

**Comment by shimat** [comment]
It is true. The save/load functions wiith CvMemStorage always occur a CV_StsNotImplemented error.
https://github.com/Itseez/opencv/blob/2c9547e3147779001811d01936aed38f560929fc/modules/ml/src/inner_functions.cpp#L114

https://github.com/shimat/opencvsharp/commit/d00c074fa62f5172fa7a487ab3917a29a1864baf
