### ISSUE TITLE
ReadNetFromDarknet load resnet50

### ISSUE THREAD

**Issue by 147906825** [shimat/opencvsharp#934]
# Summary of your issue
When i try to use method CvDnn.ReadNetFromDarknet load resnet50.cfg in opencvsharp 4 version 4.3.0.20200421. It's throw exception getMemoryShapes
# Environment

Visual Studio 2017

# What did you do when you faced the problem?

//write here

## Example code:

 using (var net = CvDnn.ReadNetFromDarknet(modelConfiguration, modelWeights))                    
  {
    using (var inputBlob = CvDnn.BlobFromImage(img, 1.0 / 255.0, new Size(DeepModel.Width,    DeepModel.Height), new Scalar(), true, false))
                            {
                                net.SetInput(inputBlob,"data");                                
                               var netward = net.Forward();
  }
}

## Output:

When i try to use method CvDnn.ReadNetFromDarknet load resnet50.cfg in opencvsharp 4 version 4.3.0.20200421. It's throw exception getMemoryShapes

## What did you intend to be?
resnet50.cfg

**Comment by 147906825** [comment]
When i try to use method CvDnn.ReadNetFromDarknet load resnet50.cfg in opencvsharp 4 version 4.3.0.20200421. It's throw exception getMemoryShapes

**Comment by shimat** [comment]
https://stackoverflow.com/questions/59564276/opencv-dnn-shows-error-when-use-resnet50-cfg-from-darknet
