### ISSUE TITLE
Stereo calibration example

### ISSUE THREAD

**Issue by nombrote** [shimat/opencvsharp#937]
# Summary of your issue
We need an example for stereo calibration (opencvsharp 4)

# Environment
windows

# What did you do when you faced the problem?
We have not got a sample for stereo calibration.

```
```

**Comment by shimat** [comment]
You can refer to the OpenCV sample (C++). 
https://github.com/opencv/opencv/blob/master/samples/cpp/stereo_calib.cpp

I'm not very familiar with stereoCalibrate and haven't been able to test its C# wrapper much, so there may be a bug in it. If someone can translate the C++ sample code to C#, I'd be happy if they could make a pull request to the [opencvsharp_samples](https://github.com/shimat/opencvsharp_samples) repository.
