### ISSUE TITLE
Camera Resolution not going to max value

### ISSUE THREAD

**Issue by sekulicb** [shimat/opencvsharp#938]
Hi. We are about to ship our first product and the only thing that keeps holding us back is the camera issue that we have. Right now the app is deployed to win10 tablets which will have the camera capture feature among others. For the life of me, I just cannot figure out why the library doesn't just "detect" highest resolution available and just locks to it, instead it always uses 1280x960. I tried on multiple tablets, laptops etc...but it just doesn't go past 1280x960 for some reason. For example:

- Native camera app goes up to 2560x1440x (5MP) highest settings
- Our WPF app using opencvsharp goes up to 1280x960

For comparison sake here is side by side metadata of the pictures. On the left is the picture taken and saved with opencvcharp library, on the right is the picture captured and saved with the native app:

![camera compare](https://user-images.githubusercontent.com/20758693/81317224-d9ac7280-908c-11ea-8045-ba03ccba7561.PNG)

What could be the problem, and **how to fix this**? 

Here is a small [repro](https://github.com/sekulicb/OpenCVSharpDemo.git)

# Environment

WPF, Visual Studio 2019 16.3.8., .NET Core 3.1.200, OpenCVSharp4.Windows (4.3.0.20200421)

**Comment by sekulicb** [comment]
If somebody has a more "modern" approach on how to capture from a camera, I will be more than happy to apply it, this is what I could find online, which is not related to WinForms explicitly or 7 years old question on Stackoverflow. Thanks

**Comment by thug1705** [comment]
If you want to get maximum resolution from camera, you can do in following way:

- Set camera resolutions to something very hight 
(e.g videoCapture.Set(VideoCaptureProperties.FrameWidth, 1000000);
videoCapture.Set(VideoCaptureProperties.FrameHeight 1000000);

- After you set camera resolution to max value you get it from camera
(e.g. var maxWidth = videoCapture.Get(VideoCaptureProperties.FrameWidth);
var maxHeight = videoCapture.Get(VideoCaptureProperties.FrameHeight);

Note that this will work on usb cameras but doesn't neccessary mean that will work on RTSP ones.

**Comment by sekulicb** [comment]
Hi.

I tried the following and it gives me even worse results then before. It actually shows that max resolution is 640 x 480 for some, for others is 640 x 360, where in both cases I had 1280 x 960. Is there no other way? What is the difference from setting camera resolution to 1000000 x 1000000, and let say 1600 x 1200, except in numbers. If I set it to 1600 x 1200 or 2560x1440 I get 1280 x 960 but with 1000000 x 1000000 I get lower values than before.

Right now I'm only using usb cameras and on the tablet, integrated camera.

**Comment by dabenpb** [comment]
Try this.  It was important in the order:           

capture = new VideoCapture(0);
capture.Open(0, VideoCaptureAPIs.DSHOW);
capture.FrameWidth = 1280;  // SET TO WHAT YOU WANT
capture.FrameHeight = 720;

**Comment by sekulicb** [comment]
Method that set's camera quality and resolution:

`public async Task InitCameraAsync(IProgress<CameraFeed> progress)
        {
            _cancellationTokenSource = new CancellationTokenSource();

            var token = _cancellationTokenSource.Token;

            await Task.Run(() =>
            {
                using (_capture = VideoCapture.FromCamera(0))
                {
                    var fps = GetFps(_capture);
                    _capture.Open(0, VideoCaptureAPIs.DSHOW);
                    _capture.Set(VideoCaptureProperties.Fps, fps);
                    _capture.Set(VideoCaptureProperties.FrameWidth, 1920);
                    _capture.Set(VideoCaptureProperties.FrameHeight, 1080);

                    var maxWidth = _capture.Get(VideoCaptureProperties.FrameWidth);
                    var maxHeight = _capture.Get(VideoCaptureProperties.FrameHeight);

                    ResolutionSet?.Invoke(this, new Resolution((int)maxWidth, (int)maxHeight));

                    var interval = (int) (1000 / fps);

                    using (var image = new CameraFeed())
                    {
                        while (!token.IsCancellationRequested)
                        {
                            _capture.Read(image);

                            if (image.Empty())
                            {
                                break;
                            }

                            progress.Report(image);

                            //token.ThrowIfCancellationRequested();

                            Thread.Sleep(interval);
                        }
                    }
                }
            }, token);
        }`

When the ResolutionSet event fires I get 1280 x 720 or 1280 x 960, depends on the camera quality. These are default values that can be used in native camera app:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/20758693/82622837-09a45b80-9bdf-11ea-885b-0422e22e822f.png)

So that means on this device I get 1.2MP quality while the camera can go up to 4.9MP. It would be great if the camera could be at least 2.1MP or 3.7MP. Do you get what I'm trying to achieve ?

**Comment by sekulicb** [comment]
Any feedback on this?

**Comment by sekulicb** [comment]
Just to leave my 2 cents in case anybody finds this issue useful. We switched to XamlIslands for camera capture, might use OpenCv just for text recognition from captured images. We did not found solution to this problem using this library. Thanks

**Comment by vintagefilmography** [comment]
I ran into a similar issue with emgu compiled with 2019 Visual Studio and running windows 10. Soled it by rearranging thee code order.
        VideoWriter writer;
        private void StartButton_Click(object sender, EventArgs e)
        {
           
            if (capture == null)
            {
                capture = new Emgu.CV.VideoCapture(trackBar1.Value);
                //Double AutoExp = capture.GetCaptureProperty(Emgu.CV.CvEnum.CapProp.AutoExposure);
                capture.SetCaptureProperty(Emgu.CV.CvEnum.CapProp.AutoExposure, 0);
                capture.SetCaptureProperty(Emgu.CV.CvEnum.CapProp.FrameWidth, 1920);
                capture.SetCaptureProperty(Emgu.CV.CvEnum.CapProp.FrameHeight, 1080);
                capture.ImageGrabbed += Capture_ImageGrabbed;
                capture.Start();

            }


            string DestPath = @"C:\capture\output.mp4";
            int fourcc = Convert.ToInt32(capture.GetCaptureProperty(Emgu.CV.CvEnum.CapProp.FourCC));
            int Width = Convert.ToInt32(capture.GetCaptureProperty(Emgu.CV.CvEnum.CapProp.FrameWidth));
            int Height = Convert.ToInt32(capture.GetCaptureProperty(Emgu.CV.CvEnum.CapProp.FrameHeight));
            int Fps = 18;
            writer = new VideoWriter(DestPath, Fps, new Size(Width, Height), true);


        }
