### ISSUE TITLE
Please help, simple MatchTemplate example needed

### ISSUE THREAD

**Issue by normanpaterson** [shimat/opencvsharp#94]
I have a simple requirement, to utilize the MatchTemplate to find an image within an image.
Can someone please provide a simple example?  I'm sure it is simple, this is what I've got then got stuck:
IplImage img = new IplImage("c:\\dfolder\\processed.png");
            IplImage imgsearch = new IplImage("c:\\dfolder\\searchimg.png");
            img.MatchTemplate(

**Comment by shimat** [comment]
```c#
IplImage img = new IplImage("c:\dfolder\processed.png");
IplImage imgsearch = new IplImage("c:\dfolder\searchimg.png");

int resultWidth = img.Width - imgsearch.Width + 1;
int resultHeight = img.Height - imgsearch.Height + 1;
IplImage imgResult = new IplImage(resultWidth, resultHeight, BitDepth.F32, 1);

Cv.MatchTemplate(img, imgsearch, imgResult, MatchTemplateMethod.CCoeff);

double min, max;
CvPoint minLoc, maxLoc;
Cv.MinMaxLoc(out min, out max, out minLoc, out maxLoc);

CvRect result = new CvRect(maxLoc.X, maxLoc,Y, imgsearch.Width, imgsearch.Height);

imgResult.Dispose();
imgSearch.Dispose();
img.Dispose();

```

**Comment by normanpaterson** [comment]
You rock, thank you so much, this is most helpful!  I had no luck on the AForge.net forums, thanks again!

**Comment by normanpaterson** [comment]
Couple of typos, for future readers of this thread, the corrected code is below:
IplImage img = new IplImage("c:\dfolder\processed.png");
IplImage imgsearch = new IplImage("c:\dfolder\searchimg.png");

int resultWidth = img.Width - imgsearch.Width + 1;
            int resultHeight = img.Height - imgsearch.Height + 1;
            IplImage imgResult = new IplImage(resultWidth, resultHeight, BitDepth.F32, 1);

            Cv.MatchTemplate(img, imgsearch, imgResult, MatchTemplateMethod.CCoeff);

            double min, max;
            CvPoint minLoc, maxLoc;
            Cv.MinMaxLoc(img, out min, out max, out minLoc, out maxLoc);

            CvRect result = new CvRect(maxLoc.X, maxLoc.Y, imgsearch.Width, imgsearch.Height);

            imgResult.Dispose();
            imgsearch.Dispose();
            img.Dispose();

**Comment by normanpaterson** [comment]
Corrected code
<code>
IplImage img = new IplImage("c:\\dump\\processed.png");
            IplImage imgsearch = new IplImage("c:\\dump\\searchimg.png");
            int resultWidth = img.Width - imgsearch.Width + 1;
            int resultHeight = img.Height - imgsearch.Height + 1;
            IplImage imgResult = new IplImage(resultWidth, resultHeight, BitDepth.F32, 1);
            DateTime begin = DateTime.UtcNow;
            Cv.MatchTemplate(img, imgsearch, imgResult, MatchTemplateMethod.CCoeff);
             DateTime end = DateTime.UtcNow;
            double min, max;
            CvPoint minLoc, maxLoc;
            Cv.MinMaxLoc(imgResult, out min, out max, out minLoc, out maxLoc);
            CvRect result = new CvRect(maxLoc.X, maxLoc.Y, imgsearch.Width, imgsearch.Height);                      
            imgResult.Dispose();
            imgsearch.Dispose();
            img.Dispose();
            MessageBox.Show("Found at: X:" + result.X.ToString() + " and Y:" + result.Y.ToString()+ " - " + (end-begin).TotalMilliseconds  + " ms.");
</code>

**Comment by shimat** [comment]
Thanks! :+1:
