### ISSUE TITLE
3D Reconstruction

### ISSUE THREAD

**Issue by ArtZero1** [shimat/opencvsharp#945]
Hello..

There are example for 3D Reconstruction using stereo image from Emgu.CV. The code snippet is :

      /// <summary>
      /// Given the left and right image, computer the disparity map and the 3D point cloud.
      /// </summary>
      /// <param name="left">The left image</param>
      /// <param name="right">The right image</param>
      /// <param name="leftDisparityMap">The left disparity map</param>
      /// <param name="points">The 3D point cloud within a [-0.5, 0.5] cube</param>
      private static void Computer3DPointsFromImages(Image<Gray, Byte> left, Image<Gray, Byte> right, out Image<Gray, Int16> leftDisparityMap, out MCvPoint3D32f[] points)
      {
         Size size = left.Size;

         using (Image<Gray, Int16> leftDisparity = new Image<Gray, Int16>(size))
         using (Image<Gray, Int16> rightDisparity = new Image<Gray, Int16>(size))
         //using (StereoSGBM stereoSolver = new StereoSGBM(5, 64, 0, 0, 0, 0, 0, 0, 0, 0))
         using (StereoGC stereoSolver = new StereoGC(16, 2))
         {
            stereoSolver.FindStereoCorrespondence(left, right, leftDisparity, rightDisparity);
            //stereoSolver.FindStereoCorrespondence(left, right, leftDisparity);

            leftDisparityMap = leftDisparity * (-16);
            //leftDisparityMap = leftDisparity.Clone();

            //Construct a simple Q matrix, if you have a matrix from cvStereoRectify, you should use that instead
            using (Matrix<double> q = new Matrix<double>(
               new double[,] {
                  {1.0, 0.0, 0.0, -size.Width/2}, //shift the x origin to image center
                  {0.0, 1.0, 0.0, -size.Height/2}, //shift the y origin to image center
                  {0.0, 0.0, -16.0, 0.0}, //Multiply the z value by -16, 
                  {0.0, 0.0, 0.0, 1.0}}))
               points = PointCollection.ReprojectImageTo3D(leftDisparity, q);
         }
      }

I try apply it using OpencvSharp, but i have trouble in construct a **Matrix<double>**.
Anybody know how to implement matrix in opencvsharp ???

Thanks in advance..

**Comment by shimat** [comment]
Can you show us your code with OpenCvSharp, even if it's unfinished?

OpenCvSharp does not distinguish between Image and Matrix. It's the same specification to the latest native (C++) OpenCV; please use Mat. (The EmguCV's way seems to be derived from the old OpenCV specification when IplImage and CvMat were separate.

**Comment by ArtZero1** [comment]
Hello..

Thisi is my code :

	private static void Computer3DPoints(string left, string right, ref Mat disparityMap, ref Point3f[] points)
	{
		var _left = Cv2.ImRead(left, ImreadModes.Grayscale);
		var _right = Cv2.ImRead(right, ImreadModes.Grayscale);
		Size _size = _left.Size;

		using (var stereoSolver = StereoBM.Create())
		{
			stereoSolver.Compute(_left, _right, disparityMap);

			float scale = Math.Max(_size.Width, _size.Height);

			double[,] array = new double[,]
			{
				{1.0, 0.0, 0.0, 0.0},
				{0.0, -1.0, 0.0, 0.0},
				{0.0, 0.0, -1.0, 0.0},
				{0.0, 0.0, 0.0, 0.0}
			};
			array[0, 3] = -_size.Width / 2.0;
			array[1, 3] = _size.Height / 2.0;
			array[3, 3] = scale;

			// The error was here...
			using (Mat<double> q = new Mat<double>(array))
			{
				ReprojectImageTo3D(outputDisparityMap, points, q, false, DepthType.Cv32F);
			}

			points = ReprojectImageTo3D(disparityMap, q);
		}

	}

I have no idea for returning point matrix :

			using (Mat<double> q = new Mat<double>(array))
			{
				ReprojectImageTo3D(outputDisparityMap, points, q, false, DepthType.Cv32F);
			}

			points = ReprojectImageTo3D(disparityMap, q);

Let me know if there are any more good idea for doing matrix ..

Thanks..

**Comment by shimat** [comment]
Please try using `Mat.FromArray(array)`
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/core/Mat/Mat.cs#L867
