### ISSUE TITLE
Mat versus CvMat

### ISSUE THREAD

**Issue by vtjumper** [shimat/opencvsharp#95]
I'm sure this is a very basic question, and I'm just starting with both OpenCvSharp (and haven't used OpenCv before), so apologies in advance.

But what's the difference between Mat and CvMat?   Should I be using one over the other? 

I see I can create a Mat from a CvMat, but I don't see an obvious way to get back.   They also seem to have a lot of overlap, but some functionality seems to be in only one or the other.

In particular I'm interested in pixel access to do things like (for example) contrast/brightness adjustment (unless there's a better way to do these than pixel access)

**Comment by TheMetalMonkey** [comment]
Both do the essentially same thing, there are 2 major namespaces, with quite a lot of overlap.

OpenCvSharp.CPlusPlus.Cv2 uses the Mat
OpenCvSharp.Cv uses CvMat

I think it is generally better to use the Cv2 (Mat), however just use the one with the functionality you need. Where there is a version in both namespaces I have found myself having to code for both and finding which one works.

**Comment by vtjumper** [comment]
Thanks.   I did find that you can create a CvMat from a Mat just by casting.
