### ISSUE TITLE
mat.GetArray always throws an exception.

### ISSUE THREAD

**Issue by AvenSun** [shimat/opencvsharp#952]
# Summary of your issue

mat.GetArray always throws an exception.

# Environment

win8.1 64bit 
opencvsharp (4.3.0.20200421)
vs2019 .net core 3.1

## Example code:

```
            // test.jpg 608x608x3=1108992
            var imageFile = Path.Combine(BaseDir, "test.jpg");
            var mat1 = new Mat(imageFile);
            var mat2 = new Bitmap(imageFile).ToMat();
            //mat1.GetArray<byte>(out byte[] data);
            mat2.GetArray<byte>(out byte[] data);
```

## Output:

```
Unhandled exception. OpenCvSharp.OpenCvSharpException: Provided data element num
ber (369664) should be multiple of the Mat channels count (3)
   at OpenCvSharp.Mat.CheckArgumentsForConvert[T](Array data)
   at OpenCvSharp.Mat.GetArray[T](T[]& data)
```

## What did you intend to be?
read an image and conver it to tensor,
the code looks like below,
but performance is too low.
maybe with some extra preprocessing.
finally  the type of  float[] is expected.

**Comment by shimat** [comment]
Since the mat is a color image, you need to write the following
```c#
var mat1 = new Mat(imageFile);
mat1.GetArray<Vec3b>(out var pixels);
```

If you need a byte array output, you can use Unsafe, fixed, or GCHandle to copy Vec3b array to byte array.
```c#
ref var bytes = ref Unsafe.As<Vec3b, byte>(ref pixels[0]);
var dst = new byte[pixels.Length * 3];
Unsafe.CopyBlock(ref dst[0], ref bytes, (uint)dst.Length);
```
```c#
unsafe
{
    fixed (Vec3b* dst3b = &pixels[0])
    {
        byte* dst = (byte*) dst3b;
        ...
    }
}
```

**Comment by AvenSun** [comment]
@shimat 
opencvsharp is great. 
thanks for for your efforts !

actually I want to do inference using onnx model.
the input should be a tensor of type  **float[]**  with some preprocessing.
how to perform color normalize using opencvsharp ?

python code looks like below , src /mean/std is numpy ndarray

```
def color_normalize(src, mean=np.array([0.485, 0.456, 0.406]), std=np.array([0.229, 0.224, 0.225])):
    """Normalize src with mean and std"""
    src -= mean
    src /= std
    return src
```
then convert to float[] after color normalize .
now I'm a little new to opencvsharp.
would you like to give some more details about this ?
thanks!
