### ISSUE TITLE
Load image by Mat is not working

### ISSUE THREAD

**Issue by mituha** [shimat/opencvsharp#956]
ファイル名に日本語を含む場合に Mat(string fileName, ImreadModes flags) コンストラクタ等よる読み込みが動作していません。  
エラーが出るわけではなく、Mat.Rows、Mat.Cols等が0となっています。

NuGet で取得した OpenCvSharp4.Windows 4.2.0.20200208 では読み込めており、
4.3.0.20200405 からは読み込めなくなっています。
この間に変更された NativeMethods_imgcodecs.cs の [MarshalAs(StringUnmanagedType)] が悪さをしているのではないかと思われます。

**Comment by shimat** [comment]
ありがとうございます。 #957 で解決を図ります。

お使いなのがWindowsだと（勝手に）想定しています。
Unicodeファイル名への対応でしたが、WindowsではOpenCV自体がUnicodeに対応できていないようなので、あきらめることにします。(https://github.com/opencv/opencv/issues/4242)

**Comment by mituha** [comment]
OpenCvSharp4.Windows 4.3.0.20200524 で動作するのを確認しました。
Windows 10 64bit で、.NET Framework 4.8 および .NET Core 3.1 の環境で症状が発生し、
今回の修正で解消されました。

ありがとうございます。
