### ISSUE TITLE
Can't create Mat from rectangular array of double

### ISSUE THREAD

**Issue by SSteve** [shimat/opencvsharp#958]
# Summary of your issue
I'm trying to create a `Mat` from a rectangular array of `double` but I get the error `The type 'double' must be a valid unmanaged type.`

# Environment

Visual Studio 2017 15.9.21
OpenCVSharp 4.3.0.20200524

## Example code:

```
var corners = new double[,] {
    {0.0, tablePhoto.Cols, tablePhoto.Cols, 0.0}, 
    {0.0, 0.0, tablePhoto.Rows, tablePhoto.Rows},
    {1.0, 1.0, 1.0, 1.0}
};

var imageCorners = Mat<double>.FromArray(corners);
```

## Output:

```
var imageCorners = Mat<double>.FromArray(corners);
                       ^^^^^^ <- error here
```

**Comment by SSteve** [comment]
I opened the project in VS 2019 and it works there. The error only occurs in VS 2017.

**Comment by SSteve** [comment]
Now I see it requires C# 7.3. The error happens when I change to C# 7.2.

**Comment by shimat** [comment]
This is by design. To facilitate implementation, I've changed the type parameter specification of `Mat`<T>. 
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/core/Mat/MatOfT.cs#L13

C# 7.2 or older does not support `where T: unmanaged` . Please use Mat instead of Mat<T>.

**Comment by SSteve** [comment]
> Please use Mat instead of Mat

I'm not sure what you mean by that.

**Comment by shimat** [comment]
sorry... Mat instead of `Mat<T>`
