### ISSUE TITLE
CvMat.GetDataStream

### ISSUE THREAD

**Issue by vtjumper** [shimat/opencvsharp#96]
The code looks like this:

     public UnmanagedMemoryStream GetDataStream(string ext, int[] prms)
        {
            unsafe
            {
                return new UnmanagedMemoryStream(DataByte, Rows*Cols);
            }
        }

Aside from not using the input parameters, shouldn't the stream size be Rows*Step?

**Comment by shimat** [comment]
input parameters are removed. thanks! 
https://github.com/shimat/opencvsharp/commit/f95ddf73e19b5a812abab66902c110fdddccf3b8

**Comment by vtjumper** [comment]
So the Rows*Cols is ok?  I tried using this and got only part of the image.

**Comment by shimat** [comment]
sorry, Rows*Cols is not correct. Step*Rows is correct.　
https://github.com/shimat/opencvsharp/commit/e14c7119584c51286a5ce638d3b34b62574a51ee
