### ISSUE TITLE
ANY EXAMPLE OF MAT.GETARRAY WITH C#

### ISSUE THREAD

**Issue by qaisbayabani** [shimat/opencvsharp#961]
# Summary of your issue

# Environment

Write your environment.

# What did you do when you faced the problem?

Write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp/blob/master/test/OpenCvSharp.Tests/core/MatTest.cs#L514

**Comment by githubcatw** [comment]
Any examples where the MatType is `CV_8UC3`? I only see examples with `CV_8UC1`.

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp/blob/master/test/OpenCvSharp.Tests/core/MatTest.cs#L695
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/core/Mat/Mat.cs#L4225
