### ISSUE TITLE
Running on raspbian

### ISSUE THREAD

**Issue by colombod** [shimat/opencvsharp#962]
Ho can I use openCvSharp4 on a raspberry pi4 or pi-top?
I can seem to find a suitable runtime package.

**Comment by NikolaTotev** [comment]
Adding to this question:
What is the procedure to use openCvSharp4 & openCV using .NET Core on a raspbbebrry pi4?

**Comment by colombod** [comment]
So far it seems I need to follow the instructions for building it from source like with the Ubuntu. Is there any plan to start providing a runtime nuget package for the raspberry pi 4 architecture?

**Comment by AvenSun** [comment]
actually what you should do is  building opencv static library on pi or cross compiling on PC,
then built OpenCvSharpExtern with static library of opencv.

**Comment by colombod** [comment]
That is enough to get unlocked but I was wondering if there is any plan to have the PI world covered with an official nuget package

**Comment by colombod** [comment]
I see unspecified for arm platform in github but not such packages published yet. Is it going to happen at any point?

**Comment by minhduc66532** [comment]
@AvenSun Sorry for interrupting you but can guide me how to build opencvsharp for jetson nano ? Since i'm trying to achieve the same thing but still can't manage to get it to work

**Comment by m-roberts** [comment]
This is closed by #1259
