### ISSUE TITLE
How to build properly build OpenCVSharp?

### ISSUE THREAD

**Issue by vinicius121** [shimat/opencvsharp#967]
# Summary of your issue
Hi,

I'm trying to build OpenCVSharp with Inference Engine. I first have cloned the opencvfiles repo. I have added the flags for the inference engine. Next I run the 'build_windows.ps1' script and then I build the project. However I don't know what to do next. Does anyone have build OpencvSharp with CUDA or Inference Engine? If so can someone make the detailed steps abailable?

Thanks
# Environment

Windows 10

**Comment by AvenSun** [comment]
read the [doc](https://github.com/opencv/opencv/wiki/Intel's-Deep-Learning-Inference-Engine-backend#microsoft-windows) of opencv

**Comment by vinicius121** [comment]
Hi,

Thanks for the reply but as I said in my question, I already did that. I got OpenCV compiled with OpenVino, I have followed the tutorial on the wikis page of OpenCVSharp and OpenCV. However, my question still remains on what to do  next, mainly what are the necessary files (lib files or others) that the OpenCVSharp needs from OpenCV and where to put them for the OpenCVSharp project to be build? And then after build what are the necessary dlls to be referenced in a new Project. So if anyone already made a custom build of OpenCVSharp project, can you please share the steps?
Thanks

**Comment by AvenSun** [comment]
firstly, you should build static library of opencv,
setting options correctly when generating VS olutions by cmake

> -DBUILD_SHARED_LIBS=OFF
> -DWITH_INF_ENGINE=ON
> -DWITH_CUDNN=ON
> **and other options you wanna enable or disable**

there's one project named "INSTALL",
you'll get all files (sonething like image below)within dir "install" when the project compiled successfully.
![ocv](https://user-images.githubusercontent.com/5615543/84819027-f8b60100-b049-11ea-9927-7090f529dcdf.jpg)
create dir "install"  to opencvsharp solution dir,
after some modifications about including path or lib of project OpenCvSharpExtern
now you can build it easily.

**Comment by vinicius121** [comment]
Hi @AvenSun ,

I got it complied and and copied the folder. I don't understand the last steps. How do I include the path or lib of the OpenCvSharpExtern?

Thanks

**Comment by AvenSun** [comment]
It's kinda basic operation of cpp project,
on project OpenCvSharpExtern, just right click and select **properties*,

![ocv2](https://user-images.githubusercontent.com/5615543/84857434-a43b7180-b09b-11ea-910d-25a4fc7627b1.jpg)

a new  window will pop up, then left click "VC++  Directories",
modify "Include Directories" and "Library Directories" according to your real path,
then try build it again.

**Comment by vinicius121** [comment]
Hi, I've configured the build with the Inference Engine as bellow:
![image](https://user-images.githubusercontent.com/28484866/84899490-a18f4b00-b0a0-11ea-9f57-8ae787363ae4.png)
Then I build the static library and copied the files to the OpenCvSharp project.
I've also verified the path for the OpenCvSharpExtern project and tried to build it but I'm having this errors:
![image](https://user-images.githubusercontent.com/28484866/84898496-44df6080-b09f-11ea-8077-0fe79f086cc3.png)

**Comment by AvenSun** [comment]
you should add libraries of IE to AdditionalDependencies of project when you built opencv with IE.

**Comment by vinicius121** [comment]
Hi,
I've added the IE libraries to AdditionalDependencies of the OpenCvSharp project and it build successfully. Then I created a .net core sample project and added the dlls (OpenCvSharp.dll, OpenCvSharp.Extensions.dll, OpenCvSharp.Blob.dll, opencv_videoio_ffmpeg430_64.dll, OpenCvSharpExtern.dll, OpenCvSharpExtern.pdb) but when I run it I get the following error:
![image](https://user-images.githubusercontent.com/28484866/84927039-2d669e80-b0c4-11ea-8f6d-b1650f3c0fd2.png)
Before this I've used nuget packages so maybe I'm not correctly adding the dll files to the project.

**Comment by AvenSun** [comment]
you have to copy native libraries of IE into your system path,
or put them into same directory as your application.

**Comment by vinicius121** [comment]
Hi
It does seem to be the IE dlls cause I've already added them to the project.
I used the dependecies program and I'm missing some system dlls:
![image](https://user-images.githubusercontent.com/28484866/85012622-30f93480-b15b-11ea-80e9-27ce3be2c93d.png)
I don't understand it cause I've only compiled with the IE. Any ideas?
Thanks

**Comment by AvenSun** [comment]
IE needs some extra dlls when inference,
you can check dependecies of OpenCvSharpExtern.dll if it was built with IE.

**Comment by vinicius121** [comment]
Hi,
Yes I've checked (using the dependencies program) and it was built with IE: 
![image](https://user-images.githubusercontent.com/28484866/85126942-6585f280-b226-11ea-903e-8fa84228a154.png)
It was also missing two .dlls (tbb.dll and ngraph.dll)
However, when I try to read the model again I get this error:
![image](https://user-images.githubusercontent.com/28484866/85132199-2ceb1680-b230-11ea-9e5e-3633ef04109e.png)
Am I still missing dlls? How can I know the necessary dlls?

**Comment by AvenSun** [comment]
you should expand **all nodes of IE,** 
and check the library marked with red color,
find and copy them into PATH or root of app.

**Comment by vinicius121** [comment]
Hi,
I did that and it can now load the model. However it doesn't detect any face:
```
var model = System.IO.Path.Combine(Location, Model);
var modeltxt = System.IO.Path.Combine(Location, ModelTxt);
var net = CvDnn.ReadNet(model, modeltxt);

net.SetPreferableBackend(Net.Backend.INFERENCE_ENGINE);
net.SetPreferableTarget(Net.Target.CPU);

var image = System.IO.Path.Combine(Location, sampleImage);
var frame = Cv2.ImRead(image);

var blob = CvDnn.BlobFromImage(frame, 1.0, new OpenCvSharp.Size(672, 384), new OpenCvSharp.Scalar(0, 0, 0), false, false); // name: "input" , shape: [1x3x384x672] - An input image in the format [BxCxHxW], Expected color order is BGR.

net.SetInput(blob);

using (var predictions = net.Forward())
{
      PrintMat(predictions);  //The net outputs blob with shape: [1, 1, N, 7], where N is the number of detected bounding boxes.         
}
```
The output blob is always [-1,-1]

**Comment by vinicius121** [comment]
I manage to get the output from the network:

`Mat detectionMat = new Mat(predictions.Size(2), predictions.Size(3), MatType.CV_32F, predictions.Ptr(0));`
