### ISSUE TITLE
ToBitmapSource optimization

### ISSUE THREAD

**Issue by slorion** [shimat/opencvsharp#97]
The current implementation of `OpenCvSharp.Extensions.BitmapSourceConverter.ToBitmapSource` uses GDI underneath which adds a significant overhead. Providing an overload to ToBitmapSource similar to the code below would avoid it.

```c#
    static BitmapSource ToBitmapSource(this IplImage iplImage, int horizontalResolution, int verticalResolution, PixelFormat pixelFormat, BitmapPalette palette)
    {
        return BitmapSource.Create(iplImage.Width, iplImage.Height, horizontalResolution, verticalResolution, pixelFormat, palette, iplImage.ImageData, iplImage.WidthStep * iplImage.Height, iplImage.WidthStep);
    }
```
In our case, when loading a bitmap into memory, we save a flat 15-20ms by using the overload (the image size does not seem to impact the time saved).

**Comment by shimat** [comment]
Thank you for your information. your code is added to the master branch.
https://github.com/shimat/opencvsharp/commit/fcf9ec627e24e93729ab5d4b52726c529cc9e843

**Comment by slorion** [comment]
Thank you for your diligence!
