### ISSUE TITLE
Missing implementation of UnscentedKalmanFilter 

### ISSUE THREAD

**Issue by Ursanon** [shimat/opencvsharp#970]
# Summary of your issue
Feature request for `UnscentedKalmanFilter`

# Environment

N/A

# What did you do when you faced the problem?

N/A

## Example code:

N/A

## Output:

N/A

## What did you intend to be?

In OpenCV (opencv_contrib) we have `UnscentedKalmanFilter` defined in [opencv2/tracking/kalman_filters.hpp](https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/include/opencv2/tracking/kalman_filters.hpp), unfortunately I cannot find it in OpenCvSharp.

Are there any plans for implementing this feature in the near future?

**Comment by shimat** [comment]
It is very difficult to wrap the UkfSystemModel because of function pointers...
https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/include/opencv2/tracking/kalman_filters.hpp#L110
