### ISSUE TITLE
Removing image background doesn't work in Linux container

### ISSUE THREAD

**Issue by milankr** [shimat/opencvsharp#973]
# Summary of your issue
I have an app where I am applying perspective transformation against the image. Transformation is conducted using  **Cv2.WarpPerspective** method from **OpenCvSharp**
The app is developed in .NET Core 2.2 and it works perfectly when it is deployed on Windows environment as a Web Service in the IIS for example.

I have tried to shift from the Windows environment to the Linux containers, by adding **OpenCvSharp4.runtime.ubuntu.18.04-x64**. This did not work at the part where the image background (after transformation) should be removed or should be made as a transparent background. 

This is an example:
**Windows**
![image](https://user-images.githubusercontent.com/5960576/85732385-9caf4480-b6fb-11ea-882f-c8e1b5612d26.png)

**Linux**
![image](https://user-images.githubusercontent.com/5960576/85732460-af297e00-b6fb-11ea-9c9b-97875634d2f7.png)

 

# Environment

- Windows 10 x64 **(works)**
- Linux-x64 **(doesn't work)**

# What did you do when you faced the problem?

Tried to change (update) the versions of the library, but it doesn't help.

## Example code:

Here is my code for applying the perspective transformation 
```
 private static void ApplyHomographyMatrix(ref Mat originalImage, float[] homography, float newWidth, float newHeight)
 {
            var resultImage = new Mat();

            IEnumerable<int> matrixSize = new List<int>() { HomographyMatrixRows, HomographyMatrixColumns };
            var homographyMatrix = new Mat(matrixSize, MatType.CV_32FC1, homography);
            Cv2.WarpPerspective(originalImage, resultImage, homographyMatrix, new Size(newWidth, newHeight), InterpolationFlags.Linear, BorderTypes.Transparent, Scalar.Black);

            originalImage = resultImage;
 }
```
Here is my code for removing the background
```
  private static void RemoveBlackBackground(ref Mat matrix)
  {
            var gray = new Mat();
            Cv2.CvtColor(matrix, gray, ColorConversionCodes.BGR2GRAY);

            var thresh = new Mat();
            Cv2.Threshold(gray, thresh, 0, 255, ThresholdTypes.Binary);

            var bgr = Cv2.Split(matrix).ToList();
            bgr.Add(thresh);

            var imageWithoutBlackBackground = new Mat();
            Cv2.Merge(bgr.ToArray(), imageWithoutBlackBackground);

            matrix = imageWithoutBlackBackground;
   }
```

Dockerfile for running the service in Linux container
```
# Download base image 
FROM  mcr.microsoft.com/dotnet/core/sdk:2.2 AS builder

# Identify the maintainer of an image
LABEL maintainer="xxx"

# Set work directory
WORKDIR /stitching-tool

# Add Shared files
ADD ./Shared /Shared
ADD ./src /stitching-tool/src

RUN dotnet restore src/xxx.Api/xxx.Api.csproj
RUN dotnet publish -c release  -r linux-x64 -o /foldername src/xxx.Api.csproj

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2

WORKDIR /foldername

COPY --from=builder /foldername.

RUN ls -al

ENV ASPNETCORE_ENVIRONMENT Development

# Expose port 80
EXPOSE 80 

ENTRYPOINT ["dotnet", "xxx.Api.dll"]
```

## What did you intend to be?
The result should be this:

![image](https://user-images.githubusercontent.com/5960576/85732385-9caf4480-b6fb-11ea-882f-c8e1b5612d26.png)

Instead of this:

**Linux**
![image](https://user-images.githubusercontent.com/5960576/85732460-af297e00-b6fb-11ea-9c9b-97875634d2f7.png)

**Comment by shimat** [comment]
I can't say for sure just from the images and code you've attached, but the problem may be that one of the mat is not initialized with zeros.

**Comment by milankr** [comment]
@shimat I have checked all the matrices which are initialized are initialized with zeros. What I forgot to say in the introduction is that background that has to be made transparent is black.

**Comment by milankr** [comment]
Problem is solved by changing this: 

` Cv2.WarpPerspective(originalImage, resultImage, homographyMatrix, new Size(newWidth, newHeight), InterpolationFlags.Linear, BorderTypes.Transparent, Scalar.Black);` 

with this:

` Cv2.WarpPerspective(originalImage, resultImage, homographyMatrix, new Size(newWidth, newHeight));`
