### ISSUE TITLE
OpenCvSharp on Raspberry Pi 4 Model B install

### ISSUE THREAD

**Issue by Jerac102** [shimat/opencvsharp#975]
# Summary of your issue
I want to use OpenCVSharp fore some motion detection projects.
# Environment
Raspberry Pi 4 Model B

## What did you intend to be?
I wanted to cross compile an arm version of OpenCVSharp on my Win 10 desktop pc.
Has someone done this and have an instructions, step-by-step for me?

**Comment by Jerac102** [comment]
Hi,
i have successfully compiled OpenCV and OpenCVSharp on my Raspberry Pi. Version 4.3.0. I used this tutorial: https://www.engineer2you.com/2017/11/install-opencv-raspberry-pi.html
Also i have build a program in VS 2019 for linux-arm, and it runs on RPi. Build on Windows in VS 2019: dotnet build --runtime linux-arm
On windows i have referenced OpenCVSharp nuget pkg for Windows and then i have replace OpenCvSharp (i think not needed) and additional i have copy libOpenCvSharp in executable folder on RPi to run a programm.

**Comment by Jerac102** [comment]
It was not so hard as i thought at the beginning.

**Comment by wsad4ryba** [comment]
Hi @Jerac102 ,
Did you copy OpenCVSharp.dll and libOpenCvSharp.so from your build repository. Do you had any problems with libOpenCvSharpExtern.so?

Do you think it is possible to do this without compilation of  OpenCV and OpenCVSharp?
There is no way to run this using only nuget packages and/or ready released dlls?

**Comment by jerkohren** [comment]
Hi @wsad4ryba,
  what I am doing now is i just build it with dotnet and runtime arg: --configuration $(BuildConfiguration) -r linux-arm and it works.
Also I have included nuget package:  <PackageReference Include="OpenCvSharp4.Windows" Version="4.5.2.20210404" /> (from csproj file).
I don't cop anything (any more) from build repository, so I don't have any problems with libOpenCvSharpExtern.so.
As you see, no complation of OpenCV[Sharp] is needed.

**Comment by wsad4ryba** [comment]
Hi @jerkohren,
Thank you for replay.
I use VSC with ```publish -r linux-arm -o bin/linux-arm/publish\``` and so far it has always worked.
Before asking you for help, I always included two references in the .csproj file.
I tested both publishing on windows and copying files to raspberry, and creating a project directly on raspberry with SDK installed. 
so my .csproj files contained either:
```
   <ItemGroup>
     <PackageReference Include = "OpenCvSharp4" Version = "4.5.3.20210817" />
     <PackageReference Include = "OpenCvSharp4.Windows" Version = "4.5.3.20210817" />
   </ItemGroup>
```
or:
```
   <ItemGroup>
     <PackageReference Include = "OpenCvSharp4" Version = "4.5.3.20210817" />
     <PackageReference Include = "OpenCvSharp4.runtime.linux-arm" Version = "4.5.3.20210817" />
   </ItemGroup>
```
Running the program on windows it worked without any problems, but on raspberry, no matter if publishing or running directly on raspberry via dotnet run, I always got an error "Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies". I tried all of this with ```<TargetFramework> net5.0 </TargetFramework>```
  and ```<TargetFramework> netcoreapp3.1 </TargetFramework>```. 

Now I checked your solution, so only one reference to ``` <PackageReference Include = "OpenCvSharp4.Windows" Version = "4.5.3.20210817" /> ```
The same effect, running on windows, works, not on raspberry. 

Do you have any idea what I'm doing wrong?

**Comment by jerkohren** [comment]
Here is my publish profile and `dotnet --info` from RPi. Maybe it help you to figure out what is wrong. 
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Debug</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Debug\net5.0\publish\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>linux-arm</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>False</PublishSingleFile>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>
</Project>
```

dotnet --info:
 dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   6.0.100-preview.3.21168.18
 Commit:    823c1dfceb

Laufzeitumgebung:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /usr/share/dotnet/sdk/6.0.100-preview.3.21168.18/

Host (useful for support):
  Version: 6.0.0-preview.3.21167.1
  Commit:  0f64b267ac

.NET SDKs installed:
  6.0.100-preview.3.21168.18 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.3.21167.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21167.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by albertwoo** [comment]
I am still getting issues.

My project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
     <PackageReference Include="OpenCvSharp4" Version="4.5.3.20211207" />
     <PackageReference Include="OpenCvSharp4.runtime.linux-arm" Version="4.5.3.20211207" />
   </ItemGroup>

</Project>
```

I run below command directly in Raspberry pi 4:
dotnet publish -r linux-arm --no-self-contained

Then I run:
dotnet OpenCVDemo.dll

After I execute I got below error:

Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.ExceptionHandler.RegisterExceptionCallback()
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.videoio_VideoCapture_new1(IntPtr& returnValue)
   at OpenCvSharp.VideoCapture..ctor()

**Comment by ffrankozz** [comment]
Hi @jerkohren,
The link you gave for the installation of opencvsharp4 on raspi 4 is not working. Any other link that  you can suggest? Thank you.

**Comment by jerkohren** [comment]
hi @ffrankozz ,
i don't have other links  and I don't need to build OpenCvSharp4 on RPi. Today I am using nuget package (OpenCvSharp4.Windows) and my app is deployed to RPi trough Azure DevOps CD/CI pipeline, and architecture is ARM.
Sorry that I can't help.

**Comment by ffrankozz** [comment]
@jerkohren Thank you for your reply.   if I am not using Azure Devops, I can build the linux docker image of my app on my Windows 10  m/c and run it on Raspberry pi, provided that the raspi has docker installed, I suppose.

**Comment by jerkohren** [comment]
@ffrankozz i suppose you can, because for testing i am publishing ARM from my windows visual studio to the RPi
