### ISSUE TITLE
VideoCapture.ConvertRGB Inverted Set

### ISSUE THREAD

**Issue by moleson21** [shimat/opencvsharp#976]
Hello,

Noticed that the set function of [VideoCapture.ConvertRGB](https://github.com/shimat/opencvsharp/blob/db62a1eafe9e33df67d19c830361a88d46d960ee/src/OpenCvSharp/Modules/videoio/VideoCapture.cs#L533) is inverted. It should instead have true mapped to 1 and false to 0. Directly calling VideoCapture.Set(VideoCaptureProperties.ConvertRgb, 0) works as intended.

Thanks!

**Comment by shimat** [comment]
Thank you!
