### ISSUE TITLE
OpencvSharp v4.3.0.20200524 - VideCamera does not work when build project in x64 mode

### ISSUE THREAD

**Issue by dominota** [shimat/opencvsharp#978]
# Summary of your issue
VideoCamera does not works if project is built in x64 mode, if the project is built in AnyCPU, it works

# Environment
I use Windows 10 x64, Vs 2017 and OpencvSharp v4.3.0.20200524 

## Example code:
```
OpenCvSharp.VideoCapture v = new OpenCvSharp.VideoCapture(0);
```

Do everybody get this issue like me? Is it is a bug?

Thanks

**Comment by dominota** [comment]
I go back with older version of opencvsharp then it works fine

**Comment by xiaodelea** [comment]
me too

**Comment by shimat** [comment]
Please try installing Media Foundation https://github.com/shimat/opencvsharp#requirements
```
PS1> Install-WindowsFeature Server-Media-Foundation
```

**Comment by xiaodelea** [comment]
OK，let me try ,thank you

**Comment by dominota** [comment]
@shimat thank you for updating Nuget. It works now

**Comment by mpiffari** [comment]
> Please try installing Media Foundation https://github.com/shimat/opencvsharp#requirements
> 
> ```
> PS1> Install-WindowsFeature Server-Media-Foundation
> ```

@shimat Can you give me some help on installing media foundation? I'm working on Windows 10 Pro - 22H2.
The problem that I'm facing is the following: when I run my webcam application in VS22 env, all works perfectly. When I create a setup installer (.exe or .msi), the software is not able to open webcam.

Example that cause this problem could be found in my person repo here ([example repo](https://github.com/mpiffari/WebcamOpenCV.Net-Test))
