### ISSUE TITLE
Rect.Contains function does not return all valid values.

### ISSUE THREAD

**Issue by AlexandreLaborde** [shimat/opencvsharp#979]
# Summary of your issue

I was trying to understand the way the area of a `Rect` is calculated because I think I found a bug in the `Contains` function.
The function is returning a smaller area and I think this is a critical issue.

# Environment

Windows 10 Pro 64bit 1909
WPF with .NETCore 3.1
OpenCVSharp 4.2.0.20200208

# What did you do when you faced the problem?

I created a `Rect` of size 3x3 at (0,0). I then tested all values between 0 and 4 for both X and Y to see where the limits of the rectangle are.

## Example code:

```
            Rect r = new Rect(new Point(0, 0), new Size(3, 3));
            Debug.WriteLine($"{r.X} {r.Y} {r.Width} {r.Height}");
            for (int i = 0; i < 5; i++)
            {
                for (int j = 0; j < 5; j++)
                {
                    Debug.WriteLine($"{i} {j} {r.Contains(new Point(i, j))}");   
                }
                Debug.WriteLine("-----");
            }
```

## Output:

```

0 0 True 
0 1 True 
0 2 False 
0 3 False 
0 4 False 
----
1 0 True 
1 1 True 
1 2 False 
1 3 False 
1 4 False 
----
2 0 False 
2 1 False 
2 2 False 
2 3 False 
2 4 False 
----
3 0 False 
3 1 False 
3 2 False 
3 3 False 
3 4 False 
----
4 0 False 
4 1 False 
4 2 False 
4 3 False 
4 4 False 
----
```

## What did you intend to be?
I was expecting the `Rect` to contain all points in the range [0 , 2] .
It's obvious that the `Contains` function is only returning `true` for points in [0,1].
I checked the source code and I think there is a bug in https://github.com/shimat/opencvsharp/blob/40c9e6c6fbc7a26152835240803df98efbf77e6a/src/OpenCvSharp/Modules/core/Struct/Rect.cs#L426

I think it should be:
 `return (X <= x && Y <= y && X + Width - 1 >=x && Y + Height - 1 >= y);` 
or 
 `return (X <= x && Y <= y && X + Width  > x  && Y + Height >  y);` 
for it to be correct.

I checked the same function for other types of rectangles and they all have the same code.
At this point I am not sure whether I am wrong or this is really a bug but I feel that is a very critical part of the code and it should be checked ASAP.

**Comment by AlexandreLaborde** [comment]
Thanks for the fast fix!

**Comment by shimat** [comment]
Thank you :+1:
