### ISSUE TITLE
Opencv# for unity

### ISSUE THREAD

**Issue by itsmeshreyans** [shimat/opencvsharp#982]
# Summary of your issue
Installed OpenCvSharp and all issues are sorted in VisualStudio but unity still throws could not be found error.

**Comment by cjvaughter** [comment]
You may find this answer useful: https://stackoverflow.com/a/61187711/11467100

**Comment by itsmeshreyans** [comment]
Thank you so much, I have had been looking for something like this for so long.

**Comment by itsmeshreyans** [comment]
> You may find this answer useful: https://stackoverflow.com/a/61187711/11467100

Thank you so much, I have had been looking for something like this for so long.

**Comment by shimat** [comment]
Sorry but I won't support Unity.
