### ISSUE TITLE
Usual issue with OpenCvSharpExtern

### ISSUE THREAD

**Issue by Fantasio1960** [shimat/opencvsharp#985]
Something is wrong with OpenCvSharpExtern

# Environment
Windows 7, Visual Studio 2019, Xamarin, C#, Android Emulator, OpenCvSharp4

# What did you do when you faced the problem?
Tried copying dll here and there, tried compiling OpenCvSharpExtern with CMake and Visual Studio itself

## Example code:

```
Mat bree = new Mat("c:/index.png", ImreadModes.Color);


## Output:

<!-- ↓do not remove ``` please!!! -->
```
System.DllNotFoundException: 'OpenCvSharpExtern assembly:<unknown assembly> type:<unknown type> member:(null)'

## What did you intend to be?

I understand an OpenCvSharpExtern.so (or is OpenCvSharpExtern.dll?) file is needed somewhere, and I understand some file is to be compiled. So I downloaded the whole OpenCvSharp project and tried to compile the ilbrary, but OpenCvSharpExtern does not produce any dll/so file. All the other dlls are there, but non this one. Also, I've no idea where to put these files.

**Comment by shimat** [comment]
Sorry but OpenCvSharp does not support Xamarin. You have to build OpenCvSharpExtern for Android/iOS. I've never tried that.
