### ISSUE TITLE
OpenCvSharp.dll fails to load OpenCvSharpExtern.dll

### ISSUE THREAD

**Issue by tugando** [shimat/opencvsharp#987]
# Summary of your issue

I am trying to enable support for the Intel Inference Engine within OpenCvSharp, but I am running into this "failure to load OpenCvSharpExtern.dll".  So far, I have downloaded the opencv_files, and added support for the Intel Inference Engine while using OpenVINO IE libraries.  I have also created the OpenCvSharp distribution using the release maker project.

I have built the opencv_files with support for OpenVINO while including the Inference Engine libraries which are found under the following OpenVINO directory:

C:\Program Files (x86)\IntelSWTools\openvino\inference_engine\lib\intel64\Release

I have added the following libraries into my project under a Libs directory, and included references to the x64 DLLs:

* OpenCvSharp.dll
* OpenCvSharp.Blob.dll
* OpenCvSharp.dll.config
* OpenCvSharp.Extensions.dll

I have added the following libraries to the root of my project, and set them as Content and to Overwrite if Newer:

* OpenCvSharpExtern.dll
* opencv_videoio_ffmpeg430_64.dll

The issue is when I include all of the following libraries, and try to load a model which was created for the OpenVINO framework, I receive the following error:

"Exception thrown: 'System.TypeInitializationException' in OpenCvSharp.dll
An exception of type 'System.TypeInitializationException' occurred in OpenCvSharp.dll but was not handled in user code
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception."

Inner Exception:
"DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

# Environment

Windows 10
.Net Framework 4.7.2
Build supporting x64 architecture
OpenVINO version 2020.3

# What did you do when you faced the problem?

Tried running a project using the manually built libraries.

## Example code:

yoloNet = CvDnn.ReadNet(YOLO_PROTO, YOLO_MODEL);
yoloNet.SetPreferableBackend(Net.Backend.INFERENCE_ENGINE);
yoloNet.SetPreferableTarget(Net.Target.OPENCL);

## Output:

Inner Exception:
"DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

**Comment by shimat** [comment]
Please try using DependencyWalker or other tools to find out the dependencies of the OpenCvSharpExtern.dll.

**Comment by tugando** [comment]
I did, and the following libraries are listed:

- INFERENCE_ENGINE.DLL
- INFERENCE_ENGINE_LEGACY.DLL
- INFERENCE_ENGINE_NN_BUILDER.DLL

... and a few system32 libraries.

**Comment by shimat** [comment]
Put those DLL files in the same directory as your exe file.

**Comment by tugando** [comment]
I have, but it still fails.

**Comment by shimat** [comment]
🤔 
- Please make sure your exe's platform and DLL's platform are same (x86 or x64). If you use AnyCPU, pay attention to the "Prefer 32-bit" setting in C# build options.
- Please check dependencies of INFERENCE_ENGINE.DLL, INFERENCE_ENGINE_LEGACY.DLL and so on. 

```c#
Console.WriteLine("Is my platform x64? : {0}", IntPtr.Size == 8);
Console.WriteLine("Is my platform x86? : {0}", IntPtr.Size == 4);
```

**Comment by tugando** [comment]
Hello Shimat, I am coming back to this again, would you happen to have an example of all the pieces needed to get this integration to work?

**Comment by shimat** [comment]
Does plain OpenCvSharp work in your environment? You can try it using https://github.com/shimat/opencvsharp_samples

If plain OpenCvSharp works, the problem is in your extension (OpenVINO). I have difficulty supporting it.
