### ISSUE TITLE
Exception thrown in InitCameraMatrix2D (easyfix?)

### ISSUE THREAD

**Issue by NilesDavis** [shimat/opencvsharp#989]
I am calling the second `Cv2.InitCameraMatrix2D` method with `Point3d[][]` and `Point2d[][]` as parameters, like it is defined. When calling it, an exception is thrown saying "objectPoints should contain vector of vectors of points of type Point3f".

This happened in VisualStudio2019 on WIndows 10 64Bit and OpenCvSharp 4.1.1.20191216 from nuget.org

I wanted to examine the source of the problem and started calling the first InitCameraMatrix2D with `Mat<Point3d>[]` and `Mat<Point2d>[]` as parameters, as stated in the summary. This lead to the same exception.

I decided to try and call it with `Mat<Point3f>[]` and `Mat<Point2d>[]` as parameters. This resulted in the following exception message: "imagePoints1 should contain vector of vectors of points of type Point2f"

So I was on the right way, and by calling the method using `Mat<Point3f>[]` and `Mat<Point2f>[]` worked like charm.

Theoretically a fix would just be to change from Point3d to Point3f and Point2d to Point2f, but as I am not familiar with the native calls, I am not able to fix it on my own.

**Comment by shimat** [comment]
Thank you for your report :+1:
