### ISSUE TITLE
Does this support CentOS 7?

### ISSUE THREAD

**Issue by dev-ptdi** [shimat/opencvsharp#995]
I deploy my Net Core 3.1 app on CentOS 7 x64

# Environment
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/var/www/html/my/api/runtimes/centos7-x64/native/OpenCvSharpExtern"

CentOS 7 x64

# What did you do when you faced the problem?

The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies
## Example code:

```
               Mat src = Cv2.ImRead(_filename, ImreadModes.Grayscale);
                Mat Gx = new Mat();
                Mat Gy = new Mat();
                Cv2.Sobel(src, Gx, MatType.CV_32F, 1, 0);
                Cv2.Sobel(src, Gy, MatType.CV_32F, 0, 1);
                double normGx = Cv2.Norm(Gx);
                double normGy = Cv2.Norm(Gy);
                double sumSq = normGx * normGx + normGy * normGy;

               
                float _calc_blurriness = (float)(1.0 / (sumSq / (src.Size().Height * src.Size().Width) + 1e-6));
```

## Output:

```
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies
```

## What did you intend to be?

this 
Please help.. I need to run it on CentOS 7, I have installed OpenCvSharp4.runtime.centos7-x64 but the problem still occurs

**Comment by shimat** [comment]
The following NuGet package for CentOS is not made by me. Probably the problem is that the native bindings of the package are outdated. Building OepnCV and the native bindings of OpenCvSharp yourself without NuGet may help.
https://www.nuget.org/packages/OpenCvSharp4.runtime.centos7-x64/

**Comment by dev-ptdi** [comment]
could you please help, how to build the native binding of OpenCvSharp? ..

**Comment by shimat** [comment]
I am sorry but I do not use CentOS. The Dockerfile may be helpful. You will need to rewrite `apt-get install ...` for CentOS.  https://github.com/shimat/opencvsharp/blob/master/docker/ubuntu.18.04-x64/Dockerfile
