### ISSUE TITLE
How to get all resolution in opencvsharp?

### ISSUE THREAD

**Issue by fabunion** [shimat/opencvsharp#999]
my camera support several resolution,how to code to print all the resolution?
Thank you!

**Comment by shimat** [comment]
As far as I know, there is no way to achieve that in OpenCV. You'll need another library.

**Comment by Dooh0126** [comment]
okay.
Thank you so much just for you to keep this project.
Is there something similar to the reason below?
Even if it is not there, it would be better to understand it only with your comments and close this issue.

Reasons for WONTFIX
1. No Solution
2. Too Expensive
3. Fix Would Add Too Much Complexity
4. Must Be Fixed Upstream
Reference site : https://en.opensuse.org/Bug_Status_WONTFIX
